### ISSUE TITLE
Setup k8s cluster on Digitalocean

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1000]
### Cluster dimension
- Single node 8GB

### Setup
Use the kubeadm-installer https://github.com/kubermatic/kubermatic-installer/tree/master/kubeadm-seed-installer for setting up the cluster

**Comment by kron4eg** [comment]
https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/draft-20180130-kubeadm-join-master.md

at some point all of this will be in kubeadm itself

**Comment by kron4eg** [comment]
https://artiom.kubermatic.io/

**Comment by kron4eg** [comment]
it's done
