### ISSUE TITLE
Add Kubermatic Edition and Kubermatic Version in Kubermatic Configuration CRD Status

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#10004]
### Description of the feature you would like to add / User story

As a \<user persona\>  
I would like to Add Kubermatic Edition and Kubermatic Version in Kubermatic Configuration CRD Status

### Solution details

- Requirement 1
- Requirement 2
- Requirement 3

**Comment by embik** [comment]
Why not make KKP deploy telemetry with an environment variable `KUBERMATIC_EDITION` set to either `ee` or `ce`? Using a `KubermaticConfiguration` that sets a specific edition will not work if you use the wrong binaries I think.
