### ISSUE TITLE
Pair of ResourceQuota subject's name and kind must be unique

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#10068]
Extend validation webhook with logic checking if a pair of incoming subject kind and name does not exist yet. In case it exists we should invalidate request for creating new resource quota as this pair should be unique.

**Comment by imharshita** [comment]
@pkprzekwas By `Extend validation webhook` do you mean there is an existing webhook for resource quota.
I am unable to find any.
If it doesn't exist, then task is to create a new validation webhook for resource quota here `pkg/webhook/resource-quota`, right?
cc @lsviben

**Comment by lsviben** [comment]
yes, a new webhook needs to be added. ResourceQuota CRD is new so there is nothing yet
