### ISSUE TITLE
Proposal for kkp user deletion

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#10142]
### Description of the feature you would like to add / User story

As a User/Developer
I would like to redesign how to handle user deletion 
in order to prevent loss of cluster when not desired.

Related to https://github.com/kubermatic/kubermatic/issues/8289
### Solution details

- Requirement 1
- Requirement 2
- Requirement 3

**Comment by xrstf** [comment]
Is this related to https://github.com/kubermatic/kubermatic/issues/8289 ?

**Comment by imharshita** [comment]
> Is this related to #8289 ?

yeah
