### ISSUE TITLE
Compare OVS performance with Canal

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10187]
Run tests against scenarios described in https://docs.google.com/document/d/1ECqOhP7mUU50RjIK3DB5gRnmijsmCCU__TcaNO7BcpE/edit#

**Acceptance criteria**
* store monitoring metrics on gdrive/github
* store netperf output on gdrive/github

**Comment by embik** [comment]
@hdurand0710 @mfranczy is this relevant/important for 2.21? Should it really be in the milestone?

**Comment by hdurand0710** [comment]
nope, I moved it to KKP 2.22.
