### ISSUE TITLE
Configure MachineDeploymentVMResourceQuota per Datacenter instead of Seed  

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#10207]
**User Story** 
As a user, I would like to filter cloud instances(vms) based on resources(RAM and CPU) per datacenter, instead of having configured on a global level(master/seed). The reason behind that is, the need to have customize different datacenter based on the customers needs. 

For example, a customer would like to provision small instances in datacenter A while keeping large instance only in datacenter B. This scenario is pretty important while dealing with bare metal provisioning and with edge computing. At the moment this is not possible, once a user specifies a resource limits, it will be propagated across all datacenter, across all seeds.

The field `MachineDeploymentVMResourceQuota` should be probably moved to the seed object, to the datacenter field to be very precise. Users can set this in admin panel but they should be able to choose to which datacenter exactly. 

Another approach could be, moving this functionality to the preset instead of having as a global settings.

**Acceptance Criteria**
- Users should be able to specify custom  MachineDeploymentVMResourceQuota on a datacenter level instead of global level.

**Comment by cschieder** [comment]
**UI/UX Requirements**
- Keep limit/filter management in the same location (do not separate global and specific-resource limits)
- Show limit/filter on create and edit dialogues where it applies so the user is kept aware what's happening
- Evaluate granularity (datacenter, provider, both? maybe datacenter groups)
- Suggestion: add a table where limits can be set, either in the same location, adding tabs to the top card or a new sidebar level

**Change Request**
- Remove required setting, make it possible to leave fields empty, remove "if set to 0, it's disabled" wording. Leaving a field empty would mean the limit is disabled

**Comment by lsviben** [comment]
From the API perspective what needs to be done:

- extend Datacenter with the fields for the resource limits (both in API model and Seed CRD, as Datacenters are a part of Seed) and update its API endpoints
- modify the various provider <provider>Size endpoints to accept datacenter names, and then do the image size filtering:
  - if the datacenter has resource limits set, use those
  - if not, use the global ones (current ones)

**Comment by cschieder** [comment]
We might want to remove the global limit when implementing resource limits

**Comment by csengerszabo** [comment]
let's rename it to MachineDeployment filter or something like that

**Comment by ahmedwaleedmalik** [comment]
> We might want to remove the global limit when implementing resource limits

@cschieder @csengerszabo should we remove the global limits or should we still support that as well?
