### ISSUE TITLE
Cluster controller runs multiple controllers

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1021]
I have been looking at the `kubermatic-cluster-controller` code base and I'd like to add a new `RBACController` instead of modifying existing cluster controller. That means that the `kubermatic-cluster-controller` will run more than one controller in-process.

At the same time I'd like to rename the component to
`kubermatic-controller-manager`

child of #966

**Comment by p0lyn0mial** [comment]
@mrIncompetent does it make sense ?

**Comment by mrIncompetent** [comment]
Yes, that's exactly what i had in mind :+1:
