### ISSUE TITLE
Provider preset cannot be deleted

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#10307]
### What happened?

A provider preset cannot be deleted at least from the UI.

### Expected behavior

Provider presets should be able to be deleted in order not to collect infinite elements of them as they would change in time.

### How to reproduce the issue?

With admin permissions, go to KKP / Admin settings / Provider presets. If there's already a provider preset added, click on its "three dots" icon, there is Edit preset, Add provider and Edit provider. Among the columns in the table and anywhere else in the UI there is no delete option (e.g. check marks in the rows and global delete button or something else like that). You can only disable a preset.

### How is your environment configured?

- KKP version: 2.20.4
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by embik** [comment]
There's an epic for this at #8709, I think.

**Comment by csengerszabo** [comment]
#8709
