### ISSUE TITLE
Investigate options for better dual-stack usability of GCP in KKP UI

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#10327]
In case of dual-stack user clusters in GCP, we should make it easier to deploy the clusters in a correct way, e.g.:
 - do not allow creating dual-stack clusters in non-dual-stack networks
 - ideally do not allow to go to the next step in the UI if this can be checked early
 - if nothing else, we should at least prevent creation of invalid clusters by cluster webhook

**Comment by hbernardo** [comment]
Created these tasks after investigation:
- [GCP cluster defaulting/validation: network subnet should be in the same cluster region and have the same IP stack](https://app.zenhub.com/workspaces/work-in-progress---team-b-5fb24df6da2f6a001f678bb1/issues/kubermatic/kubermatic/10343)
- [GCP network/subnetwork listing endpoints: check preset network + return subnets information](https://app.zenhub.com/workspaces/work-in-progress---team-b-5fb24df6da2f6a001f678bb1/issues/kubermatic/kubermatic/10342)
- [Improve dual-stack usability of GCP in KKP UI](https://app.zenhub.com/workspaces/work-in-progress---team-b-5fb24df6da2f6a001f678bb1/issues/kubermatic/dashboard/4679)
