### ISSUE TITLE
Test new Kubernetes clusters with Azure external CCM & CSI - Test Release 2.21

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#10439]
See epic for PRs that added support for Azure external CCM and CSI. Repeat the test procedure for all Kubernetes versions since we added external CCM support for everything since Kubernetes 1.22.

## Test Versions

Testing per minor release should be sufficient.

- [ ] v1.22.x
- [ ] v1.23.x
- [ ] v1.24.x

## Test Procedure

1. Create new user cluster for Azure (e.g. via dashboard) and wait for deployment to finish
2. Verify that Azure CCM pod is running in control plane namespace on the seed and does not throw any errors
3. Verify that `azure-cloud-node-manager` is running on each node in user cluster and does not throw any errors
4. Verify that all nodes are `Ready` and properly initialised by the CCM
5. Verify that all CSI pods are up and running in the user cluster and do not throw any errors
6. Create a `LoadBalancer` service and verify that it properly creates an Azure LB and that a dummy service (e.g. echoserver) is reachable via the LBs public IP. Make sure it gets properly cleaned up on deletion
7. Create `PersistentVolumeClaims` for both CSI drivers / StorageClasses (Azure File and Azure Disk). Try to mount them into a Pod. Make sure the Pod can write to them. Ensure they get properly cleaned up on deletion

If you can think of anything else to test, please go ahead before deleting the cluster.

## Acceptance Criteria

- Test procedure is successful for all available versions

**Comment by hdurand0710** [comment]
**1.22.9**

- Azure CCM pod is running  and no error logs
- `nodes` are `Ready`

**Comment by hdurand0710** [comment]
1.22.x tests are ok.

**Comment by hdurand0710** [comment]
1.23.6, 1.23.9 tests are ok.
Upgrades are ok from versions.
The pod with pvc (disk and file) is restarted in the upgraded nodes with no error on the storage.
pod is able to write in the volume.
