### ISSUE TITLE
Support for Clustermesh in Cilium

### ISSUE THREAD

**Issue by Prasanth-sekharan** [kubermatic/kubermatic#10449]
### Support for Clustermesh in Cilium - KKP

We're glad to see the recent addition of Cilium as a CNI plugin. However, we noticed that ClusterMesh can't be configured/enabled (or at least not without major interference for the cluster workload) 

```
$ cilium clustermesh enable
⚠️  Cluster not configured for clustermesh, use '--cluster-id' and '--cluster-name' with 'cilium install'. External workloads may still be configured.

Error: Unable to enable ClusterMesh: cannot auto-detect service type, please specify using '--service-type' option
```

Specifically, cluster-name and cluster-id are not set (to sensible values):

```
$ ks get cm cilium-config -o yaml | grep -e cluster-id: -e cluster-name:
  cluster-id: ""
  cluster-name: default
```

### Additional information
(https://docs.cilium.io/en/v1.12/gettingstarted/clustermesh/clustermesh/

As for the use-case: for increased HA, we would like to span workloads across two Kubernetes clusters, one each in our two separate OpenStack clouds (which are located in different datacenters in two remote corners of the country). In future, we'd also like to span the workloads across 2-3 Kubernetes clusters, in different setups involving hyperscalers (particularly AWS, Azure and GCP): 1) across several availability zones or regions within the same hyperscaler, 2) across two hyperscalers, 3) across our on-prem OpenStack and a hyperscaler.
)

**Comment by rastislavs** [comment]
This relates to https://github.com/kubermatic/kubermatic/issues/8540 - this one needs to be addressed first to allow sane Cilium clustermesh config.

Full support of Cilium clustermesh in KKP would however be much more complex than just configuring cluster-id and cluster-name.

**Comment by rastislavs** [comment]
This (Cilium config in general) will be fully configurable in 2.22 - see https://github.com/kubermatic/kubermatic/issues/8540
Docs: https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/networking/cilium-cluster-mesh/
