### ISSUE TITLE
Test VMs isolation network policy

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10485]
Test if a default cluster-isolation network policy is being created on KubeVirt infra cluster while creating a new user cluster.
Additionaly we have to check if:
* VM to VM communication in the same namespace work
* VM to VM inter-namespace communication is blocked
* External Load Balancer from user cluster works as it should (could be done by deploying Nginx)

**Comment by sankalp-r** [comment]
KKP version: v2.20.0-dev-gedfc53af

Results:

- [X] VM to VM communication in the same namespace work

- [X] VM to VM inter-namespace communication is blocked

- [X] External Load Balancer from user cluster works as it should (could be done by deploying Nginx)

Everything is working fine.
