### ISSUE TITLE
Test KubeVirt machine deployments

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10480]
Test should cover UI general actions like:
- [X] create (all operating systems)
- [X] update (all available fields)
- [X] delete
- [X] scale

Flags:
- [X] upgrade on the first boot
- [X] dynamic kublet configuration

Operating system input:
- [X] from http source
- [X] from pvc source 

Secondary disks:
- [X] add/delete

Labels/taints:
- [X] node labels
- [X] node taints

**Comment by sankalp-r** [comment]
All the options related to Kubevirt machine deployment from UI are working fine.

Except for the secondary disk naming issue. 
Need to retest secondary disks again after the fix is available.
