### ISSUE TITLE
Test VMs affinity rules

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10487]
Test affinity rules for VMs - UI is not implemented so it's required to create or edit a Machine Deployment CR.
Document that describes the mechanism https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/kubevirt-node-placement.md

We should test
* nodeAffinityPreset
* nodeAntiAffinityPreset
* podAffinityPreset
* podAntiAffinityPreset 

with values = "", "soft", "hard"

**Comment by hdurand0710** [comment]
- podAffinityPreset/2 nodes/"soft"
