### ISSUE TITLE
Test KubeVirt virtual machine presets

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10482]
Test VM presets (infra KubeVirt cluster):
- [X] create (on the infra and see if it's visible by API and works)
- [X] delete (delete should not be allowed)
- [X] update (after update the VM that uses the preset should not be recreated)

**Comment by sankalp-r** [comment]
Environment: QA setup v2.21.0-alpha.0

- [X] create (on the infra and see if it's visible by API and works)
- [ ] delete (delete should not be allowed)
- [ ] update (after update the VM that uses the preset should not be recreated)
