### ISSUE TITLE
Test Cilium CNI v1.12 - Test Release 2.21

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#10513]
Test the latest Cilium CNI (v1.12) deployed in a new user cluster + in a user cluster that was running Cilium v1.11 previously. Also test the Hubble addon in both scenarios.

Refer to the docs in https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/networking/cni_cluster_network/#cilium-cni

Perform each test for `iptables` and `ebpf` proxy mode. The `iptables` mode should be tested with Konnectivity diabled, `ebpf` with Konnectivity enabled. That means performing 4 tests:

- v1.12 with iptables without Konnectivity
- v1.12 with ebpf + Konenctivity
- v1.11 upgrade to v1.12 with iptables without Konnectivity
- v1.11 upgrade to v1.12 with ebpf + Konenctivity

## Testing Procedure - new cluster with v1.12
1. deploy a new user cluster with Cilium v1.12 and iptables/ebpf proxy mode
2. verify that all pods are healthy
3. verify that pod-to-pod, pod-to-service, pod-to-nodeport connectivity works fine
4. deploy the Hubble addon
5. port-forward to hubble UI and verify it works
6. run [conformance tests](https://sonobuoy.io/docs/v0.56.8/), e.g. `./sonobuoy run --wait=0 --dns-pod-labels "app.kubernetes.io/name=kube-dns,app=coredns"`

## Testing Procedure - v1.11 upgrade to v1.12
1. deploy a new user cluster with Cilium v1.11 and iptables/ebpf proxy mode
2. wait until all pods are up
3. deploy the Hubble addon
4. port-forward to hubble UI and verify it works
5. upgrade CNI version to v1.12
6. verify that pod-to-pod, pod-to-service, pod-to-nodeport connectivity works fine
7.  port-forward to hubble UI and verify it works
8. run [conformance tests](https://sonobuoy.io/docs/v0.56.8/), e.g. `./sonobuoy run --wait=0 --dns-pod-labels "app.kubernetes.io/name=kube-dns,app=coredns"`

## Acceptance Criteria
Testing procedure is successful for all described test cases.
Some conformance test are expected to fail in case of Cilium due to CIlium upstream issues (e.g. https://github.com/cilium/cilium/issues/14287). Please document them in this issue.

**Comment by hbernardo** [comment]
Sonobuoy tests that failed:

For both with ebpf + Konnectivity (v1.12 and v1.11 upgraded to v1.12):
```
    - name: '[sig-network] HostPort validates that there is no conflict between pods
        with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]'
      status: failed
      details:
        failure: |-
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:633
          Aug  5 18:15:51.517: Failed to connect to exposed host ports
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
...
```

For both with iptables without Konnectivity (v1.12 and v1.11 upgraded to v1.12):
```
    - name: '[sig-network] Services should have session affinity timeout work for
        service with type clusterIP [LinuxOnly] [Conformance]'
      status: failed
      details:
        failure: |-
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:633
          Aug  5 18:19:34.881: Affinity should hold but didn't.
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:212
...
    - name: '[sig-network] HostPort validates that there is no conflict between pods
        with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]'
      status: failed
      details:
        failure: |-
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:633
          Aug  5 18:20:14.739: Failed to connect to exposed host ports
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
...
    - name: '[sig-network] Services should have session affinity work for service
        with type clusterIP [LinuxOnly] [Conformance]'
      status: failed
      details:
        failure: |-
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:633
          Aug  5 18:22:24.221: Affinity should hold but didn't.
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:212
...
    - name: '[sig-network] Services should be able to switch session affinity for
        service with type clusterIP [LinuxOnly] [Conformance]'
      status: failed
      details:
        failure: |-
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:633
          Aug  5 18:24:36.242: Affinity should hold but didn't.
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:212
...
```
