### ISSUE TITLE
Improvement of MetalLB Addon / IPAM Pool config

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#10547]
Following topics are missing in the current metallb / IPAM pool config

### 1) Reconciling of `ipampools.kubermatic.k8c.io`
Currently if an IPAM Pool get deleted, the user cluster addon object `ipaddresspools.metallb.io` doesn't get deleted automatically.
It seams that the `kubectl apply` only updates the additional address pool field, but the automatic generated ip address pool object stays. 

<img width="637" alt="sig-cs-infra | … 2022-07-28 15-04-51" src="https://user-images.githubusercontent.com/4659261/181512314-3aedf618-7fe6-4022-ab68-24af0ebdcf3d.png">

#### Why we need this?
Let's expect that a customer want to refactor their IPAM Pools and delete one pool. Then it get split up and reconfigured and re-applied. The old user cluster IP pool is still active and metallb will serve potetnial traffic to it.  A new cluster get created and get the same IP assigned and metallb start to serve traffic to this cluster as well. This will lead to the situation that we have potential 2 services with the same IP active. What should be avoided by the developed IPAMPool. Background, metallb make the virtual IPs available via ARP, so it's can happen that in this case two cluster will get mixed up traffic - debugging is really hard in this case, because somehow you will lost packages and you are blind to find out where it get routed to. 

### 2) Make automatic IP address pool optional and highlight the yaml field as additional IP address config option
To ensure full control from a user cluster admin perspective, he should have an option to disable the automatic IP address pool assignment. Also the `yaml` config should be described in a way  a enduser understand that it gets it additional to the default config. 
![Cluster 'friendly-rosalind' in Project 'play' 2022-07-28 14-28-45(1)](https://user-images.githubusercontent.com/4659261/181513568-a7f6bdd4-9f36-48fe-a4e7-8d697c1f8206.png)

**Comment by hbernardo** [comment]
@toschneck Suggested solution for issue 1: https://github.com/kubermatic/kubermatic/pull/10583
cc @adeniyistephen
