### ISSUE TITLE
Customizable cluster templates

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#10549]
### Description of the feature you would like to add / User story

As a KKP user
I would like to customize the cluster template when I am using it to create a cluster
in order to edit some particular details like credentials for a specific installation but keep everything else the same

### Solution details

- When creating a cluster from a template there is a Customize button
- Customize button will expand the popup and loads all the parameters that can be set up in a cluster with its prefilled values from the template
- Any prefilled parameter can be edited
- It should be secure in a way that the credentials used by the template by default cannot be extracted, but could be used if one does not want to change it

### Alternative approaches

- Creating clusters from scratch without cluster template
- Add users to their own projects and let them able to create their own cluster templates (use KKP in a self-service mode)

### Use cases

- If one user would like to create multiple clusters with almost the same parameters but with different credentials, when KKP is not being used in a self-service way, and the admin executes the requests for creating clusters for example

**Comment by csengerszabo** [comment]
- we drive them to the wizard from the popup with the customize button with pre-filled values
- they can also save the new one as a new cluster template from the wizard if they want to
- we will empty the credentials for security reasons
- if they change something, they dependent values would be deleted and have to be re-filled

**Comment by ahmedwaleedmalik** [comment]
Closed with https://github.com/kubermatic/dashboard/pull/5295
