### ISSUE TITLE
Test OIDC group support - editor - Test Release 2.21

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#10551]
Test a simple flow of sharing project between user and group.

## Prerequisites:
- Google account in `kubermatic.com` domain
- Github account added to `internal` or `development` teams (kubermatic org)

## Test Procedure
1. Login to KKP using your google account.
2. Create a new project.
3. Create a small cluster inside the newly initialised project.
4. Go to members page of the new project, select groups tab and create a new group project binding with `viewers` role selected. (I suggest using `kubermatic:internal` or `kubermatic:development` group name)
5. Logout.
6. Login again, this time using your Github account. Shared project should be listed on Projects Overview page. Select it.
7. Verify that `Members` and `Service accounts` pages are not available to you.
8. On the `Clusters` page, verify that you **can** create a new cluster.
9. On the `Clusters` page, select cluster and check if you change its name in the edit mode.
10. Delete the cluster.

## Acceptance Criteria
Testing procedure is successful for all described test cases.

**Comment by hbernardo** [comment]
LGTM
