### ISSUE TITLE
Test Resource Quotas on vSphere - Test Release 2.21

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#10558]
Test steps:

**Test the cluster resource calculation**
1. Create a cluster
2. When the cluster is up, check the `cluster.status.resourceUsage`. It should correspond with the chosen node size. Check also on the user cluster the node capacity. The capacity should match the `resourceUsage`

**Test the quota**
1. Create a quota
2. In turn, set the CPU, Memory and Storage to be just above the current usage.
3. Increase the number of replicas on the Clusters machine deployment
4. Observe MD events that say that the Machine validation failed because the resource is over the quota

**Comment by ahmadhamzh** [comment]
i try to create a cluster and it been created and the MD been created but with no nodes due to resource quota issue ![Screenshot from 2022-08-22 11-13-39.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/3811e19a-c494-45db-a654-4ca6cae1abff)
