### ISSUE TITLE
Test OIDC group support - owner - Test Release 2.21

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#10552]
Test a simple flow of sharing project between user and group.

## Prerequisites:
- Google account in `kubermatic.com` domain
- Github account added to `internal` or `development` teams (kubermatic org)

## Test Procedure
1. Login to KKP using your google account.
2. Create a new project.
3. Create a small cluster inside the newly initialised project.
4. Go to members page of the new project, select groups tab and create a new group project binding with `viewers` role selected. (I suggest using `kubermatic:internal` or `kubermatic:development` group name)
5. Logout.
6. Login again, this time using your Github account. Shared project should be listed on Projects Overview page. Select it.
7. Verify that `Members` and `Service accounts` pages **are** available to you.
8. Select `Members` page and ensure you can see both list of members and groups.
  a. Create new user project binding.
  b. Create new group project binding.
  c. Delete previously created user and group project bindings.
9. Select `Service Accounts` page and ensure you can see the list of service accounts.
10. On the `Clusters` page, verify that you **can** create a new cluster.
11. On the `Clusters` page, select cluster and check if you change its name in the edit mode.
12. Delete the cluster.

## Acceptance Criteria
Testing procedure is successful for all described test cases.

**Comment by hbernardo** [comment]
LGTM
