### ISSUE TITLE
User cannot delete Cluster Template

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#10578]
### What happened?

As a project user I was trying to remove one of existing cluster templates. The API request return 200 but probably due to an existing finalizer (kubermatic.k8c.io/cleanup-credentials-secrets) it stays in the terminating state forever.

### Expected behavior

After deleting `clustertemplate` it should be removed from the cluster.

### How to reproduce the issue?

1. Create a project or use one of existing ones.
2. Go to `Cluster Templates` page and create a new cluster template.
3. After the new cluster template is saved go back to the cluster templates page again and try to remove it.

### How is your environment configured?

- KKP version: 2.21 (dev on 29.07.2022)

**Comment by embik** [comment]
Bug is caused by #10370, working on a fix PR.
