### ISSUE TITLE
Test Multi-Cluster IP Address Management (IPAM) - Test Release 2.21

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/kubermatic#10593]
Please refer to the sub-issues for test details.

Documentation of the feature will be here: https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/networking/ipam/ after this [PR](https://github.com/kubermatic/docs/pull/1117) is merged.

Original development epic: https://github.com/kubermatic/kubermatic/issues/6421

**Comment by rastislavs** [comment]
Closing as all sub-issues have been closed.
