### ISSUE TITLE
Test Resource Quota general test - Test Release 2.21

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#10598]
1. Create a ResourceQuota
2. Create a Cluster
3. Observe the `cluster.status.resourceUsage` , `resourcequota.status.localUsage`, `resourcequota.status.globalUsage` . Should all be the same and based on the chose Node type. Check also the user cluster Node capacity.

// add additnional cluster
1. add a cluster, use a different provider or node type
2. check again the calculation in the statuses

// try to enforce the  quota
1. the resource quota quota should be set to somehting that the next cluster, or a second replica of the machine should exceed the quota. 
2. Try to create an additional cluster or increase replicas.
3. observe the MD events saying that the quota is exceeded.

// increase the quota
1. The Machine above should finnaly be created 

// decrease the quota
1. Nothing should happen to already existing machines

// removing resources
1. Delete a cluster, or decrese replicas
2. The status calculations should all decrease after the machine is gone

**Comment by hbernardo** [comment]
Looks good now after the quotas enforcement fix.

**Note:** tested in dev env as the enforcement fix is not synced yet with the QA env.

**Question:** shouldn't the new cluster status be red (instead of green) when the initial machine deployment isn’t deployed due quotas exceeding?

**Comment by lsviben** [comment]
The machine deployment is present, just the machines are not created. In theory, the cluster is healthy when all the control plane components are working/running. Its not connected with the machine's state.

Not having nodes ready is visible in the Cluster view. It shows something like ready/desired (for example 1/2). But maybe that is not clear enough
