### ISSUE TITLE
Test Resource Quota multi seed - Test Release 2.21

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#10597]
Test resource quota calculation and enforcement over multiple seeds

0. Create a resource quota.
1. Create a Cluster on Seed A.
2. Create a Cluster on Seed B.

2. Check if the ResourceQuota `status.localUsage` is set to what you expect (the `cluster.status.resourceUsage`).
3. Check if ResourcQuota `status.GlobalUsage` is set to what you expect (seed A + seed B localUsage) (on both seeds)

On both seed clusters, try to go over the quota, and observe the MD events, the validation for Machines should fail with the quota of some resource being over the quota.

**Comment by hbernardo** [comment]
LGTM
