### ISSUE TITLE
Test metallb addon - Test Release 2.21

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/kubermatic#10594]
You can refer to the docs in https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/networking/ipam/ after this [PR](https://github.com/kubermatic/docs/pull/1117) is merged.

**Acceptance Criteria:**
- Check that manifests are rendered properly in the user cluster
- Check in metallb logs that pool CRDs have been applied (shouldn't be throwing any errors)
- Deploy this in vsphere user cluster and create a service of type LoadBalancer - check that assigned service’s ExternalIP is allocated from the pool

**Comment by rastislavs** [comment]
passed acceptance criteria
