### ISSUE TITLE
[UI] [vSphere] Default image does not get sent to api

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1060]
According to the hint, the default is `ubuntu-template`.
Though it does not get sent to the API.

**Comment by kgroschoff** [comment]
@mrIncompetent can't test it atm, as vsphere is not running, but it seems that we send it. We normally send everything, you could see on the summary step.

**Comment by mrIncompetent** [comment]
Closed since it seems its not the case
