### ISSUE TITLE
Kubevirt cluster provisioning and upgrading - Test Release 2.21

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#10614]
Please go through https://github.com/kubermatic/kubermatic/issues/10609 for instructions. 

Supported Operating Systems:
- [X] Ubuntu
- [X] CentOS
- [X] Flatcar
- [X] RHEL
- [X] Rocky Linux

Supported Kubernetes versions:
- [X] v1.22.5
- [X] v1.22.11
- [X] v1.23.9
- [X] v1.24.3

Supported container runtimes:
- [X] Docker
- [X] Containerd

Upgrades:
- [X] Upgrade from v1.22.5 -> v1.22.11
- [X] Upgrade from v1.22.11 -> v1.23.9
- [X] Upgrade from v1.23.9-> v1.24.3

**Comment by sankalp-r** [comment]
Tested on KKP v2.21.0-alpha.1
Working fine.
