### ISSUE TITLE
Nutanix cluster provisioning and upgrading - Test Release 2.21

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#10615]
**While creating this ticket I'm not sure whether our Nutanix setup is even functional**

Please go through https://github.com/kubermatic/kubermatic/issues/10609 for instructions. 

Supported Operating Systems:
- [ ] Ubuntu

Supported Kubernetes versions:
- [ ] v1.22.5
- [ ] v1.22.11
- [ ] v1.23.9
- [ ] v1.24.3

Supported container runtimes:
- [ ] Docker
- [ ] Containerd

Upgrades:
- [ ] Upgrade from v1.22.5 -> v1.22.11
- [ ] Upgrade from v1.22.11 -> v1.23.9
- [ ] Upgrade from v1.23.9-> v1.24.3

**Comment by embik** [comment]
> While creating this ticket I'm not sure whether our Nutanix setup is even functional

It's not because we haven't set up any cross-datacenter connectivity yet.

**Comment by embik** [comment]
Closing because Nutanix doesnt have a special control plane component (no CCM) and (node) version upgrades were already tested with KubeOne.
