### ISSUE TITLE
Test using etcd data encryption at rest - Test Release 2.21

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#10623]
Test setting up etcd data encryption at rest. Our documentation [explains the feature in depth](https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/encryption_at_rest/) and goes over what can be set up. #9654 also contained some information around the feature under the hood. Feel free to extend the test scenario with things you consider important from your initial contact with this. The epic that contains this story also contains a specific issue to attempt breaking data encryption at rest.

Questions stemming from a lack of documentation should also be noted down so we can improve it.

## Test Scenario

1. Create a cluster and create some resources on it, mainly focus on creating `Secrets` with dummy data
2. Set up encryption at rest on a cluster (make sure to start with standard settings, but extend settings like the resources that will be encrypted)
3. Observe both the cluster status updating (e.g. via [stalk](https://github.com/xrstf/stalk)) and resources in the cluster namespace updating (mostly `kube-apiserver` Pods)
4. Ensure data-encryption Job successfully finishes and lists the expected resources in its log
5. Make sure resources can still be queried via `kubectl` (those created in step 1)
6. Verify that data in etcd is encrypted. There are some pointers on [the Kubernetes docs](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#verifying-that-data-is-encrypted), you should be able to use `kubectl exec` to issue `etcdctl` commands within the etcd Pods of your user cluster
7. Disable encryption at rest and observe what is essentially the reversal of the previous steps 
8. Wait for cluster status to settle and re-run step 6, make sure data is not encrypted anymore

## Acceptance Criteria

Test scenario successfully concludes without issues (data is encrypted or decrypted when expected).

**Comment by xrstf** [comment]
The documentation doesn't mention that a feature gate needs to be set.

**Comment by xrstf** [comment]
After enabling the encryption, can confirm the pod logs are correct:

```
k -n cluster-kpt7bxbh95 logs -f data-encryption-kpt7bxbh95-9gpbv-tqcx7
secret/cloud-init-getter-token replaced
secret/eager-perlman-kube-system-bootstrap-config replaced
secret/eager-perlman-kube-system-provisioning-config replaced
secret/hello-world replaced
secret/bootstrap-token-ctvbnf replaced
secret/cloud-config replaced
secret/hcloud-csi replaced
secret/metrics-server-serving-cert replaced
secret/usersshkeys replaced
secret/kubernetes-dashboard-csrf replaced
secret/kubernetes-dashboard-key-holder replaced
```

**Comment by xrstf** [comment]
Cluster status works as expected:

```diff
--- Cluster kpt7bxbh95 v265826 (2022-08-03T19:24:56+02:00) (gen. 4)
+++ Cluster kpt7bxbh95 v266110 (2022-08-03T19:25:19+02:00) (gen. 4)
@@ -23,7 +23,7 @@
     is-credential-preset: "true"
     project-id: gskkvkz26w
   name: kpt7bxbh95
-  resourceVersion: "265826"
+  resourceVersion: "266110"
   uid: e3567b32-4e19-44d6-904e-4df23d2176c7
 spec:
   auditLogging: {}
@@ -178,9 +178,10 @@
       reason: UpToDate
       status: "True"
   encryption:
-    activeKey: ""
-    encryptedResources: []
-    phase: EncryptionNeeded
+    activeKey: secretbox/my-primary-key
+    encryptedResources:
+    - secrets
+    phase: Active
   extendedHealth:
     apiserver: HealthStatusUp
     applicationController: HealthStatusUp
```

**Comment by xrstf** [comment]
> but extend settings like the resources that will be encrypted

From the documentation (neither website nor the CRD comments) it wasn't clear that

> admission webhook "clusters.kubermatic.io" denied the request: spec.encryptionConfiguration.resources: Forbidden: list of encrypted resources cannot be changed. Please disable encryption and re-configure

**Comment by xrstf** [comment]
Apart from the notes, everything else works as described.

**Comment by embik** [comment]
@xrstf thanks for your observations, here's a PR that should fix the documentation issues: [1127](https://github.com/kubermatic/docs/pull/1127)

**Comment by xrstf** [comment]
Yep, merged, thanks, done.
