### ISSUE TITLE
Test breaking etcd data encryption at rest - Test Release 2.21

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#10624]
This is kind of an unusual test story, but I think it's important since encryption at rest is such a vital feature to get "right" (all information in Kubernetes is stored in etcd, so losing etcd data is terrible). See #10623 for the test issue to just set up encryption at rest. The epic at #10622 also links to a lot of documentation for this feature.

The idea behind this issue is that you are supposed to try breaking data encryption at rest because it's a very stateful feature. You can set it up or review the code to get an idea of the general flow (the original PR #9654 had a very in-depth description of the flow). Essentially, this is supposed to be manual chaos testing. Everything "bad" should either recover automatically or be rejected by our webhooks.

Some ideas on what could be done:
- Provide invalid keys
- Rotate keys right after setting up encryption at rest
- Delete kube-apiserver Pods at random while encryption at rest initialises
- Delete data-encryption Jobs or Pods while data is being (re-)encrypted
- Edit encryption at rest settings while keys are rotating

## Acceptance Criteria

This story is kind of open-ended, so feel free to use your own judgement on when you consider this to be "stable" / "not breaking".

**Comment by PratikDeoghare** [comment]
Normally encrypted secret is prefixed with the name of the key that encrypted it. 
I deleted encryption job pod while randomly deleting some kube-apiserver pods.
This got me a secret without the prefix as shown below. Encryption status was Failed. 
Failed state is currently a dead end in EAR. 

```
root@etcd-0:/# etcdctl get  /registry/secrets/kube-system/cloud-config
/registry/secrets/kube-system/cloud-config
�R���8<'�,�@�3F��]�`-qlʹ��bP�-�'䈫s(�ՠ�%�1�:@=q-:�
                                           w6�u�ǟ���Cb>_�"��m��Ny�
                                                                  .9�0�lG,7��B�Q��~�Z5�+
                                                                                        ҟ���h9IQ��h.;����mz�{]a����\��W�N�1��:9¾�=�s�!�!�~�S4#0�o�Of.k����n�H��ߋ���m��f�Uq�N�w�{���C�N�+�$T?j#�:�6�*��W'i� �'+�
                                                                         (��ȚG�D�c��s���o�:4H(�Dvjb),�o�O
                                                                                                         &����0������!��i2��is�9��'\E^S }Ks������S�jG� �ꃼ,��M��gbͲ'm�{I׳��j�cf�x��I�-���Џ_�����am���dv���yoO�o@�;m.�=��G�>$
                                    �P�^
>ϐe1-��W
�飉nW֑4��oHRf!�N*x���焌:�a�~����@lD�Ҟ
                                    &o�
root@etcd-0:/# 

```

**Comment by PratikDeoghare** [comment]
Created bug upstream https://github.com/kubernetes/kubernetes/issues/112001
