### ISSUE TITLE
Test API endpoints for IPAMPool - Test Release 2.21

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/kubermatic#10636]
You can refer to the docs in https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/networking/ipam/ after this [PR](https://github.com/kubermatic/docs/pull/1117) is merged.

Swagger documentation is [here](https://docs.kubermatic.com/kubermatic/master/references/rest_api_reference/).

**Endpoints to test**:
- `GET /api​/v2​/seeds​/{seed_name}​/ipampools` - Lists IPAM pools.
- `POST ​/api​/v2​/seeds​/{seed_name}​/ipampools` - Creates a IPAM pool.
- `GET /api​/v2​/seeds​/{seed_name}​/ipampools​/{ipampool_name}` - Gets a specific IPAM pool.
- `DELETE /api​/v2​/seeds​/{seed_name}​/ipampools​/{ipampool_name}` - Removes an existing IPAM pool.
- `PATCH /api​/v2​/seeds​/{seed_name}​/ipampools​/{ipampool_name}` - Patches a IPAM pool.

**Comment by rastislavs** [comment]
All endpoints are working fine.
