### ISSUE TITLE
Test IPAM allocation algorithms (range and prefix) - Test Release 2.21

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/kubermatic#10637]
You can refer to the docs in https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/networking/ipam/ after this [PR](https://github.com/kubermatic/docs/pull/1117) is merged.

For this test, you should apply IPAMPools with different configurations (i.e. types, pool CIDR and allocation size) to a user cluster datacenter and **should expected**:
- All allocations should belong to the pool subnet (i.e. `poolCidr` configured in the `IPAMPool` CR)
- Allocations for same IPAMPool + datacenter + user cluster should not overlap in any allocation type (range or prefix).
- Limits should be respected: allocation should **not** happen in some user cluster if there is no enough free available space in the pool subnet for all user clusters allocations. An error, instead, should happen for some of the user cluster(s) reconciling.

**Comment by rastislavs** [comment]
All mentioned conditions tested and working as described.
