### ISSUE TITLE
Test IPAMPool webhook validations - Test Release 2.21

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/kubermatic#10635]
You can refer to the docs in https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/networking/ipam/ after this [PR](https://github.com/kubermatic/docs/pull/1117) is merged.

**Validations to test**:
Required spec fields:
- `datacenters`
- `type` for a datacenter
- `poolCidr` for a datacenter
- `allocationRange` for a datacenter with "range" allocation type
- `allocationPrefix` for a datacenter with "prefix" allocation type

For the "range" allocation type:
- `allocationRange` should be a positive integer and cannot be greater than the pool subnet possible number of IP addresses.
- IPv4 `poolCIDR` should have a prefix (i.e. mask) equal or greater than **20**.
- IPv6 `poolCIDR` should have a prefix (i.e. mask) equal or greater than **116**.

For the "prefix" allocation type:
- `allocationPrefix` should be between **1** and **32** for IPv4 pool, and between **1** and **128** for IPv6 pool.
- `allocationPrefix` should be equal or greater than the pool subnet mask size.

Other:
- Verify that you **cannot** delete a datacenter configuration in an `IPAMPool` CR, if there is persisted allocation `IPAMAllocation` in any user cluster for it.
- Verify that you are **allowed** to delete a datacenter configuration in an `IPAMPool` CR, if there is **no** persisted allocation `IPAMAllocation` in any user cluster for it.
- Any other modifications should not be allowed. So, you should try to change all IPAMPool datacenter attributes and not succeed.

**Comment by rastislavs** [comment]
All validations work as expected
