### ISSUE TITLE
Support topology spread constraints

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10646]
As a user I want to have automatic mechanism that will spread my user cluster nodes across bare-metal nodes.

Required constraints:
* Zones - Hard, maxSkew=1
* Nodes - Soft, maxSkew=1

NOTE: test if max skew 1 will work fine across the cluster and test when zone label is missing

Related to: https://github.com/kubevirt/kubevirt/pull/7846
Nice to have: update KubeVirt upstream documentation about topology constraints

Learning materials:
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
https://kubernetes.io/blog/2020/05/introducing-podtopologyspread/

Acceptance crtieria:
* Defined default topology spread constraints
* Possibility to add custom constraints (no update/delete flow), meaning we disable our own default
* Removed Pod(Anti)Affinity mechanism, mark Affinity fields as deprecated
* Updated documentation (mention about deprecated field)
* Unit tests added
* UI tasks created (consult with Chiara about the design)
* Applicable per machine deployment
* Tested upgrade from Pod Affinity presets

**Comment by sankalp-r** [comment]
As discussed with @mfranczy , we decided to change default constraint to only have:

- Nodes - Soft, maxSkew=1

**Comment by cschieder** [comment]
kubermatic/dashboard/issues/5067 Let me know if this works
