### ISSUE TITLE
Switch from VMIPreset to VirtualMachineInstancetype API

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10645]
As a user I want to move to isntance type and preferences instead of using presets which are depracated.

Acceptance criteria:
* migration from presets to instance type and preference is supported
* we have endpoints for:
    * preferences that would return cluster and namespaced wide resources
    * instance type that would return cluster and namespaced wide resources
* resource quota calculation mechanism is switched to new templating mechanism
* standard preset of VM is being converted to instance type and preference (cpu topology - always use sockets)
* cluster wide resources should be categorized as "custom" meaning those are defined by kubevirt cluster admin
* namespaced resources should be categorized as "standard" meaning those are defined by us
* create e2e test scenario (if it's too many changes we have to create a separate issue)
* unit tests are implemented for machine controller and for kkp cloud provider
* updated documentation
* create UI issue

**Comment by hdurand0710** [comment]
Some remarks playing with instancetype and preference.

- 

> Anything provided within an instancetype cannot be overridden within the VirtualMachine. For example as CPU and Memory are both required attributes of an instancetype if a user makes any requests for CPU or Memory resources within the underlying VirtualMachine the instancetype will conflict and the request will be rejected during creation.

This is true even if values are the same.
As soon as both (instancetype and underlying vm) specify the same fields, request is rejected during creation, even if values are the same.

**Comment by hdurand0710** [comment]
Some scenario to keep in mind for migration from preset to instancetype.

---
Pre-requisite:
 Create and start a VM with a `preset`:
```
  domain:
    devices: {}
    resources:
      limits:
        cpu: "2"
        memory: 150Mi
      requests:
        cpu: "2"
        memory: 150Mi
```

---

- Apply an `VirtualMachineInstancetype` or `VirtualMachineClusterInstancetype` (same result) with:

```
spec:
  cpu:
    guest: 4
  memory:
    guest: 175Mi
```
- AND DO NOT DELETE the `preset` labels in the `vm`

- stop/start the VM

- result `vmi`
```
  domain:                                                                                                                                                                                                      │
│     cpu:                                                                                                                                                                                                       │
│       cores: 1                                                                                                                                                                                                 │
│       model: host-model                                                                                                                                                                                        │
│       sockets: 4                                                                                                                                                                                               │
│       threads: 1
    memory:                                                                                                                                                                                                    │
│       guest: 175Mi                                                                                                                                                                                             │
│     resources:                                                                                                                                                                                                 │
│       requests:                                                                                                                                                                                                │
│         cpu: "2"                 -->>> inconsistent, not a way to go                                                                                                                                                                              │
│         memory: 150Mi. -->>> inconsistent, not a way to go
```
----

- Now start again with  the `preset`, apply the previous `instancetype` BUT DELETE the `flavor` labels
- Stop/start the `vm`
- result `vmi`
```
│   domain:                                                                                                                                                                                                      │
│     cpu:                                                    --->> ok                                                                                                                                                   │
│       cores: 1                                                                                                                                                                                                 │
│       model: host-model                                                                                                                                                                                        │
│       sockets: 4                                                                                                                                                                                               │
│       threads: 1
     memory:                                                            --->>ok                                                                                                                                        │
│       guest: 175Mi                                                                                                                                                                                             │
│     resources:                                                                                                                                                                                                 │
│       requests:                                                                                                                                                                                                │
│         memory: 175Mi    --->ok
```
----

So reconciling VM created with `preset` and moving to `instancetype` for existing VM should be possible if reconciliation includes removing the `flavor` labels.

**Comment by hdurand0710** [comment]
With the `Versionning` (https://kubevirt.io/user-guide/virtual_machines/instancetypes/), 
if `instancetype` or `preference` is updated, the `vmi` keeps the previous values when stop/start.
To the new values, vm should be deleted.

**Comment by hdurand0710** [comment]
Updates in KKP:
- replace `VirtualMachineInstancePreset` with `VirtualMachineInstancetype`
- https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/common/provider/kubevirt.go#L252 -> more simple
- Do we add `preferences`
- how/do we want to handle `xxxClusterxxx` (instancetype and preference)

Update in MC:
- replace `VirtualMachineInstancePreset` with `VirtualMachineInstancetype`
- if `VirtualMachineInstancetype` -> remove any `flavor` label if any
- add `preference` ?

**Comment by mfranczy** [comment]
We should consider implementing migration from presets to instance type, even that we say that KubeVirt is a technology preview.

The API should consider, cluster wide and namespaced instance types.
Cluster wide are instance types created by KubeVirt cluster admin, namespaced types are our standard flavors.
