### ISSUE TITLE
KubeVirt: Project quota are being ignored

### ISSUE THREAD

**Issue by dermorz** [kubermatic/kubermatic#10674]
### What happened?

During testing of resource quotas for user clusters on KubeVirt (#10489) I noticed while trying to set a Resource Quota on project level in the admin panel, that set values are being ignored. I set 4GB RAM as Resource Quota but can successfully create a Cluster on KubeVirt with 8GB nodes.

### Expected behavior

After setting a Project Quota I should not be able to create a KubeVirt cluster with nodes exceeding the quota. I should also get a verification error when resizing nodes to exceed the quota.

### How to reproduce the issue?

1. Go to "Quotas" in the Admin panel and set "Memory (GB)" to 4 for a project.
![image](https://user-images.githubusercontent.com/682686/183015276-570c0c02-2624-4435-91f8-2af36374579d.png)
2. Create a User Cluster on KubeVirt in this project and set Memory to 8GB.
![image](https://user-images.githubusercontent.com/682686/183016771-8ddb8d59-7357-4515-b0ff-7584fa53156c.png)
3. The node with the requested size gets created.

![image](https://user-images.githubusercontent.com/682686/183019560-5c8d37c4-6f1d-4883-909d-4a84dca6aded.png)

### How is your environment configured?

- KKP version: `v2.21.0-alpha.0`
- KKP Installation: 2.21 QA Environment

### What cloud provider are you running on?

KubeVirt

### Additional information

The docs of Resource Quota are not reflecting the actual feature anymore. This is addressed somewhere else.

**Comment by sankalp-r** [comment]
The project quota for kubevirt is working as expected.
