### ISSUE TITLE
Metering Filenames not S3 compliant

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#10693]
### What happened?

The metering job is created files which will not play nicely with all S3 implementations. See https://github.com/kubermatic/kubermatic/issues/7337 and https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html for more information.

Filenames are currently `report-<NAME>-2022-08-07T00:00:00Z-2022-08-08T12:35:49Z.csv`, where the colons are the troublesome characters.

### Expected behavior

No problematic characters are used.

**Comment by WeirdMachine** [comment]
This is fixed in the new version: https://github.com/kubermatic/metering/blob/master/main.go#L146
