### ISSUE TITLE
ApplicationInstallation Scope Migration - Test Release 2.21

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#10695]
In https://github.com/kubermatic/kubermatic/pull/9975 we changed the scope of the ApplicationInstallation CRD. In https://github.com/kubermatic/kubermatic/pull/10694 we added migration code to delete the old CRD on the master cluster. This procedure needs to be tested.

### Procedure

1. Setup KKP 2.20 with apps enabled.
1. Create an ApplicationInstallation for a usercluster.
1. Ensure that the app was installed correctly.
1. Migrate KKP to 2.21.
1. Ensure that the app is still present.

**Comment by hdurand0710** [comment]
nothing more to test. Upgrade was tested yesterday.
