### ISSUE TITLE
Managing ApplicationDefinitions

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#10710]
For this test you will slip into the role of a KKP Administrator. So we do expect the end-user to have some knowledge in Kubernetes.

The following guide is meant to help you through the tests
https://docs.kubermatic.com/kubermatic/master/tutorials-howtos/applications/create-application-catalogue/
If you encounter any issue in the guide, please add them as comments to this ticket.

Each of the tests below can be considered a success, if the following conditions are met
1. Application shows up in the UI after ApplicationDefinition has been applied
2. An Application can be created from the ApplicationDefinition using the UI. There is no need to get fancy with values overrides or anything.
3. The status lamp in KKP in the Applications overview turns green
4. The workload can be seen in the cluster with `kubectl get`

Additionally for the tests it is fine to add all the applications to an existing cluster. There is no need to add them during cluster creation or via a template (this will be done in a separate test)

- [x] Create an ApplicationDefinition with mixed sources (at least 1 git, and 1 helm) for an open-source project
- [x] Create an ApplicationDefinition with multiple helm versions for an open-source project
- [x] Create an ApplicationDefinition for a project in a private OCI registry @vgramer Do we have a private OCI registry set-up somewhere already?
- [x] Create a private git-repository with ssh-key authentication. Create an ApplicationDefinition for it
- [x] Create a private git-repository with https authentication. Create an ApplicationDefinition for it

**Comment by wurbanski** [comment]
#10840 was created after findings for task no. 4

**Comment by wurbanski** [comment]
Fixes were tested and everything works correctly! 🎉
