### ISSUE TITLE
Bug: endpoint "applicationinstallations" is failing for "viewer" group

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/kubermatic#10728]
Please check this test issue steps to reproduce the bug: https://app.zenhub.com/workspaces/work-in-progress---team-b-5fb24df6da2f6a001f678bb1/issues/kubermatic/kubermatic/10541

After Github login, in the cluster details page, this error is happening:
![image.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/d5337c59-2aae-4fe7-a6ec-7b783dbc356d)

Response from the request to `/api/v2/projects/kfpkp6fqn4/clusters/hfmbhm7qvr/applicationinstallations`: 
```
{"error":{"code":403,"message":"applicationinstallations.apps.kubermatic.k8c.io is forbidden: User \"hugofbernardo@gmail.com\" cannot list resource \"applicationinstallations\" in API group \"apps.kubermatic.k8c.io\" at the cluster scope"}}
```

**Comment by SimonTheLeg** [comment]
* happens on both dev and qa envs
* happens both with google as well as github login
