### ISSUE TITLE
Write validation admission-webhook

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1073]
**User Story**
A user wants to create a cluster via `kubectl create -f cluster.yaml` and get the same validation when doing it via the kubermatic dashboard.

To achieve this, we need to extract the cluster validation logic from the kubermatic api into a admission webhook.

**Acceptance criteria**
- [ ] admission webhook exists as dedicated binary
- [ ] admission webhook binary gets published in the default `kubermatic/api` docker image
- [ ] admission webhook validates cluster custom resources
- [ ] admission webhook gets deployed together with kubermatic
- [ ] validation logic got removed from kubermatic-api

**Definition of Done**
- [ ] invalid clusters created via `kubectl create -f cluster.yaml` cannot be created
- [ ] invalid clusters created via the kubermatic dashboard cannot be created

**Comment by p0lyn0mial** [comment]
happy to see that we are all on the same page :)

**Comment by mrIncompetent** [comment]
@mrIncompetent

**Comment by mrIncompetent** [comment]
Will be implemented in a single webhook via https://github.com/kubermatic/kubermatic/issues/1688
