### ISSUE TITLE
Synchronize helm charts with kubermatic/kubermatic-installer

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#1076]
We want to automatically sync the current helm charts to kubermatic/kubermatic-installer.

**Comment by metalmatze** [comment]
Helm charts synchronize:
```
cert-manager
certs
kubermatic
monitoring
nginx-ingress-controller
nodeport-proxy
oauth
```

I don't think that we need the `test` and `installer` charts.

**Comment by cbrgm** [comment]
What about the bash scripts? @mrIncompetent  `deploy_seed_helm_charts.sh`, ` 	deploy_master_helm_charts.sh`

**Comment by metalmatze** [comment]
Copy those charts from `config/` into `charts/` in the installer repo.

**Comment by mrIncompetent** [comment]
@cbrgm only copy the charts/directories mentioned by @metalmatze.
Nothing else.

**Comment by metalmatze** [comment]
Step to do in drone when kubermatic/kubermatic is tagged:
* `git clone git@github.com:kubermatic/kubermatic-installer.git` into some directory somewhere in the container. You decide where exactly.
* Copy kubermatic/kubermatic `/config/` into kubermatic/kubermatic-installer `/charts/`.
* `git commit -a kubermatic-installer/config/`
* Optional: `git tag ${DRONE_TAG}`. Do we want this? Not sure, right now.
* `git push origin master --tags` in kubermatic-installer.

**Comment by metalmatze** [comment]
Maybe clone the installer to `/go/src/github.com/kubermatic/kubermatic-installer`.

**Comment by mrIncompetent** [comment]
> Maybe clone the installer to /go/src/github.com/kubermatic/kubermatic-installer.

Could you elaborate what you mean by this?

**Comment by metalmatze** [comment]
In Drone the repository is cloned to this path:
```
workspace:
  base: /go
  path: src/github.com/kubermatic/kubermatic
```
Thus we can clone the installer repo to its full path. So we have:

`/go/src/github.com/kubermatic/kubermatic`
`/go/src/github.com/kubermatic/kubermatic-installer`

I just want to avoid cloning the installer repo into the kubermatic folder :wink:
