### ISSUE TITLE
Test Resource Quotas on Equinix Metal(Packet) - Test Release 2.21

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#10773]
Test steps:

Test the cluster resource calculation

Create a cluster
When the cluster is up, check the cluster.status.resourceUsage. It should correspond with the chosen node size. Check also on the user cluster the node capacity. The capacity should match the resourceUsage
Test the quota

Create a quota
In turn, set the CPU, Memory and Storage to be just above the current usage.
Increase the number of replicas on the Clusters machine deployment
Observe MD events that say that the Machine validation failed because the resource is over the quota

**Comment by ahmedwaleedmalik** [comment]
From machine-controller:

```
E0819 15:36:23.254487       1 machineset_controller.go:141] Failed to reconcile MachineSet "kube-system/loving-engelbart-646989d44f": failed to sync Machineset replicas: admission webhook "machines.cluster.k8c.io" denied the request: error getting machine resource request: Provider equinixmetal not supported
```

**Comment by ahmedwaleedmalik** [comment]
Still not functional
![Screenshot 2022-08-24 at 3 37 30 PM](https://user-images.githubusercontent.com/18264334/186398111-5d04cd52-b556-4723-9de8-425d68424917.png)

**Comment by ahmedwaleedmalik** [comment]
Works as expected 🎊
