### ISSUE TITLE
Test Resource Quotas on VMware Cloud Director - Test Release 2.21

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#10772]
Test steps:

Test the cluster resource calculation

Create a cluster
When the cluster is up, check the cluster.status.resourceUsage. It should correspond with the chosen node size. Check also on the user cluster the node capacity. The capacity should match the resourceUsage
Test the quota

Create a quota
In turn, set the CPU, Memory and Storage to be just above the current usage.
Increase the number of replicas on the Clusters machine deployment
Observe MD events that say that the Machine validation failed because the resource is over the quota

**Comment by ahmedwaleedmalik** [comment]
Works as expected
