### ISSUE TITLE
Edit existing Applications values gives error

### ISSUE THREAD

**Issue by sankalp-r** [kubermatic/kubermatic#10836]
### What happened?
Editing the existing Applications `values.yaml` gives an error response. 

Error message from API is :

`"error":{"code":422,"message":"ApplicationInstallation.apps.kubermatic.k8c.io \"apache\" is invalid: spec.values: Invalid value: \"string\": spec.values in body must be of type object: \"string\""}}`

### Expected behavior

Editing existing Applications `values.yaml` should work.

### How to reproduce the issue?

Create a cluster on KKP, then create an Application on top of it.
After successful installation of Applications, try to edit the `values.yaml`.

For example in the case of `apache`, change the `commonLabels.owner` label and observe the error response.

### How is your environment configured?

- KKP version: dev
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by vgramer** [comment]
the problem comes from the UI, it works with API. i have created an issue in dashboard  kubermatic/dashboard#4880

**Comment by sankalp-r** [comment]
Yes. I also noticed that.
So I will close this issue.
