### ISSUE TITLE
Application:  download helm dependencies with credentials

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#10845]
### Description of the feature you would like to add / User story

if the template method is `Helm` and Source is GIT. In order to install the chat we must download the chart dependencies defined in `Chart.yaml`. These dependencies may point to a repository that requires authentication.

We have to update the applicationDefinitionCRD to handle credentials for this case.

Side-Note: we do not have this issue for helm registries, as they package a chart with all its dependencies

### Solution details
 
Add a new optional field `applicationDefinition.spec.version[].TemplateCredentials`  that holds the credentials that must be used when installing the application. 

Currently only Helm as method may require credentials at install time. To keep the crd easily extendable.

`TemplateCredentials` will be a struct that holds pointer(s) to the credentials. The choice of credentials will be done according to the templating method.

**Comment by SimonTheLeg** [comment]
Currently still in Refinement: tbd. if this is a feature required by customers. @shaase-ctrl @csengerszabo to reconcile with customers.
