### ISSUE TITLE
Applications enhancements 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#10846]
### Description of the feature you would like to add / User story

This epic is a collector for application enhances planed for KKP 2.22

**Comment by embik** [comment]
Hey @vgramer, can you maybe strip stories that won't be done for 2.22 from this epic and create a separate one to carry that over into KKP 2.23 work? Or should we move the whole epic over to 2.23?

**Comment by vgramer** [comment]
I created a new epic for  2.23 and move the left over to it :)
