### ISSUE TITLE
Add support for Cilium and Hubble metrics

### ISSUE THREAD

**Issue by aryasalim91** [kubermatic/kubermatic#10851]
### Description of the feature you would like to add / User story

Enable Cilium and Hubble metrics by default or provide a method to enable/disable it.

https://docs.cilium.io/en/stable/operations/metrics/

### Additional information
KKP - 2.20
Kubernetes Version : v1.23.9
OS Name and Version : Ubuntu 20.04.4 LTS
OS Kernel Version : 5.15.0-41-generic

**Comment by rastislavs** [comment]
Enabling the metrics endpoints by default would be a potential security issue, as cilium agents run in the host network namespace -  binding the metrics endpoint in a generic way (e.g. on `0.0.0.0` / `::`) in the host network namespace could expose the endpoints to the public Internet if access lists / firewalls are not in place at the cloud-provider / data-center level.

Instead, as part of https://github.com/kubermatic/kubermatic/issues/8540, we will provide a way for enabling it explicitly.

**Comment by rastislavs** [comment]
This (Cilium config in general) will be fully configurable in 2.22 - see https://github.com/kubermatic/kubermatic/issues/8540
