### ISSUE TITLE
Improve OIDC kubeconfig permissions

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#10886]
When getting the kubeconfig for a user cluster, with OIDC kubeconfig option being turned on, the kubecofigs which the users get dont have any permissions on the user cluster (even if they are admins or project members) unless they are added in the Cluster RBAC rules as a member of a predefined rbac role.

Try to find a way to improve this, project members and admins should have permissions on the user cluster based on their project status

**Comment by csengerszabo** [comment]
Isn't this a duplication or a potential part of Role-based kubeconfig in user cluster epic #10668 ? @lsviben
