### ISSUE TITLE
Support KubeVirt VMs disks registry

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10902]
As a user I want to have a dropdown list of all availables operating systems images for KubeVirt and addtionaly I would like to have a functionality to use my own custom images of supported os types.

**Comment by mfranczy** [comment]
I will deal with the quay.io registry creation.

**Comment by bhavyastar** [comment]
@mfranczy I don't think anyone is working on this issue. Can you assign this issue to me if no one is working on this issue!

**Comment by mfranczy** [comment]
Hi @bhavyastar, this is epic, we have sub-issues for particular features of this functionality. Additionally we are in the phase of grooming of new image sources (like PVC, OCI registry etc.)

**Comment by bhavyastar** [comment]
Yes! @mfranczy Actually, I am new to this project! But I am willing to learn and contribute to this. If you can little guide me, I am more than happy to work on this.

**Comment by mfranczy** [comment]
Sure @bhavyastar we will get back to you.
