### ISSUE TITLE
Add cluster labels to KubeVirt VM

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#10923]
From now KubeVirt CCM requires new labels to route the traffic to services.

We should add those labels to VMs:
`cluster.x-k8s.io/cluster-name: <tenant-cluster-name>`
`cluster.x-k8s.io/role: worker`

related to https://github.com/kubevirt/cloud-provider-kubevirt/pull/143

Acceptance criteria:
* KubeVirt CCM upgraded to v0.4.0
* KubeVirt CCM tested against LB creation and node initialization

**Comment by hdurand0710** [comment]
Note: the `<tenant-cluster-name> ` can be retrieved in the md as an existing labels `system/cluster`

**Comment by mfranczy** [comment]
Please as well update KubeVirt CCM to v0.3.0 and test LB creation.

**Comment by mfranczy** [comment]
Yesterday there was a new release of v0.3.1 and v0.3.2, please upgrade to the lastest version.

**Comment by mfranczy** [comment]
We have to inform users that used older CCM version that once they use a new version they must:
* update LB selector manually
* update VMs with new labels manually

We have to this test this scenario.
