### ISSUE TITLE
Disabling OSM on existing clusters during 2.21 upgrade fails on separate seeds

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#10940]
### What happened?

When upgrading a Multi-Seed KKP environment, reconciling the seed can fail with error events like these on the `Seed`:

```
Warning  SeedReconcilingError  59m (x6 over 3h57m)     kkp-seed-operator  aws-seed: [Cluster.kubermatic.k8c.io "<Cluster ID>" is invalid: spec.pause: Required value, Cluster.kubermatic.k8c.io "<Cluster ID>" is invalid: spec.pause: Required value]
````

Upgrading the seed to 2.21.0 does not progress as expected.

The issue is the OSM migration step using a `client.Update()` call, as that can easily hit different CRD versions being validated in different ways. A `Patch()` call should simplify the payload sent to the seed cluster and not trigger this issue (at least that is my assumption from looking at this; verify this is indeed the solution). https://github.com/kubermatic/kubermatic/blob/4c83dabf406ccdca8c2055b734266d92d66f57d0/pkg/controller/operator/seed/reconciler.go#L733

### Expected behavior

Upgrading seeds with existing clusters that do not have OSM enabled/disabled should work.

### How to reproduce the issue?

Not fully clear, but likely have a seed that does not live on the master cluster and have existing clusters without OSM enabled. Upgrading the environment should cause this.

### How is your environment configured?

- KKP version: 2.21.0
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

#### Workaround

It should be possible to resolve this issue by patching all affected clusters on the seed cluster (do not apply this to clusters that have OSM enabled already):

```
$ kubectl patch cluster <CLUSTER_ID> --type=merge -p '{"spec":{"enableOperatingSystemManager":false}}'
```

**Comment by ahmedwaleedmalik** [comment]
Fixed with https://github.com/kubermatic/kubermatic/pull/10948
