### ISSUE TITLE
Introduce per-registry mirrors in user cluster configurations

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#10943]
### Description of the feature you would like to add / User story

As a KKP administrator, I would like to be able to replace specific registries.
For instance, to avoid rate limiting in case of hub.docker.io, I'd like to define replacement for this specific domain.

### Possible solutions

- it can work similary to `registryMirrors` in https://docs.kubermatic.com/kubermatic/v2.20/references/crds/#nodesettings
- or `mirrors` in https://docs.kubermatic.com/kubeone/master/references/kubeone-cluster-v1beta2/#containerdregistry

### Use cases

Technically it's possible to overwrite the default registry to avoid docker hub rate limiting using `overwriteRegistry` setting, however this overwrites all registries. In our example, we want to overwrite docker hub but keep using gcr.io for images pulled from google.

**Comment by csengerszabo** [comment]
Available in 2.21

**Comment by embik** [comment]
Introduced in #10134, for future reference.
