### ISSUE TITLE
Fix CCM migration tests for release branch 2.20

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#10949]
### What happened?

In CCM migration tests, the nodes are unable to join the user cluster and it results in failure for the tests.

Logs from `kubelet` running on the node:
```
Sep 12 07:39:30 ccm-migration-e2e-debug-645bb6f796-66b7q kubelet[21179]: E0912 07:39:30.843943   21179 kubelet_node_status.go:93] Unable to register node "ccm-migration-e2e-debug-645bb6f796-66b7q" with API server: Post "https://x5k8cmng44.kubermatic.127.0.0.1.nip.io:6443/api/v1/nodes": dial tcp 127.0.0.1:6443: connect: connection refused
```

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by xrstf** [comment]
Fixed by #11154
