### ISSUE TITLE
Allow changing kube-proxy "metricsBindAddress" parameter per user cluster

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#11055]
### Description of the feature you would like to add / User story

Our customer has a request to change kube-proxy `metricsBindAddress` parameter per user cluster.
> a customer had the request to scrape the kube-proxy metrics endpoint with his own prometheus deployment.
For that, he changed the listening address of the metrics endpoint to 0.0.0.0:10249
Unfortunately, the kube-proxy configmap gets overwritten by kubermatic and the metricsBindAddress parameter will reset to the value default, which is metricsBindAddress: 127.0.0.1:10249

It's rather a bigger task that would require re-designing of the current default addons deployment mechanism to provide customization per user cluster.

### Solution details
- Documenting how to use kube-rbac-proxy to expose it, and optionally we could also make an addon for it

### Additional information

**Comment by kron4eg** [comment]
Let's try to find out which metrics are being exposed by the kube-proxy, we might want to grab them too.

**Comment by mfranczy** [comment]
> The addons mechanism allows to customize this config option:
https://github.com/kubermatic/kubermatic/blob/master/addons/kube-proxy/configmap.yaml#L55

Yes, but our customer wants to have custom configuration for his single user cluster.
By changing addon we influence all user clusters. 

That's why I wrote above:
> customization per user cluster.

I am not sure if this is a good idea to create such a mechanism.
I guess it's up you folks (sig-cluster-management) and @csengerszabo to decide.

**Comment by mfranczy** [comment]
To make it more clear, let's say we have user clusters A, B, C.
Customer wants to change configuration of kube-proxy only for the cluster C. 
He cannot beacuse addons controller will overwrite it.

**Comment by rastislavs** [comment]
I think the main reason why the metrics are not exposed on `0.0.0.0` by default is security - as kube-proxy runs in the host network namespace, binding the endpoint on `0.0.0.0` could expose the endpoint to the whole Internet if the node has a public IP and no firewalling is configured on the cloud-provider level.

Apart from making it configurable another, option that could be considered is to expose it via [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) as we already do for the node-exporter Addon [here](https://github.com/kubermatic/kubermatic/blob/e19d7235938dced93d9d2eb63226606806997b1f/addons/node-exporter/daemonset.yaml#L66-L72).

**Comment by csengerszabo** [comment]
Proposed and agreed solution for this: documenting how to use kube-rbac-proxy to expose it, and optionally we could also make an addon for it.

**Comment by mfranczy** [comment]
Addons in KKP are already documented.
