### ISSUE TITLE
Resource quota settings for Machine deployment

### ISSUE THREAD

**Issue by talhalatiforakzai** [kubermatic/kubermatic#11065]
### What happened?

The minimum requirements for a user cluster is `2 GB or more of RAM per machine` and `2 CPUs`, but we allow instances such as `T3A Nano (2 vCPU, 0.5 GB RAM, 0.0054 USD per hour)` on AWS if the minimum CPU and RAM is not set by admin, why is the default minimum requirements not enforced by kkp itself.

### Expected behavior

KKP shipped with minimum user cluster requirement for initial machine deployment.

### How to reproduce the issue?

Do not set minimum CPU and RAM in admin pannel and try to provision user cluster.

### How is your environment configured?

- KKP version: 2.21.0
- Shared or separate master/seed clusters?: Shared master/seed clusters

### What cloud provider are you running on?

AWS

### What operating system are you running in your user cluster?

Ubuntu 20.04

**Comment by csengerszabo** [comment]
Closing in favor of #11097
