### ISSUE TITLE
Display RAM size in the Admin panel  

### ISSUE THREAD

**Issue by talhalatiforakzai** [kubermatic/kubermatic#11066]
### Description of the feature you would like to add / User story

I would like to have RAM size displayed in the Admin panel `Defaults and Limits`, as currently RAM size is not displayed in the KKP dashboard and for a new user it becomes ambiguous.

### Solution details

FE can display the size if the size is to remain static.

**Comment by stroebitzer** [comment]
this is only about the missing unit (GB, Gibi, ...)

![Screenshot from 2022-09-28 15-57-44](https://user-images.githubusercontent.com/26508771/192799675-f3772d97-651c-4a91-bcc2-8ff0256d376d.png)
