### ISSUE TITLE
Cleanup Flavor/PodAffinity when UI is merged

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#11122]
We need to cleanup the Flavor in `KubevirtNodeSpec` when the switch to instancetype and preference is done (for example remove it from the
`func (spec *KubevirtNodeSpec) MarshalJSON() ([]byte, error) {`  in `pkg/api/v1/types.go`.
This will be done once the UI has switched to instancetype.

Before that, to not break the UI, the `flavor` is kept.

**Comment by sankalp-r** [comment]
Same is applicable for `PodAffinityPreset` and `PodAntiAffinityPreset`.
