### ISSUE TITLE
Don't enforce roleARN and instanceProfile validation when AWS IAM not accessible

### ISSUE THREAD

**Issue by hc2p** [kubermatic/kubermatic#11126]
### Description of the feature you would like to add / User story

As a KKP admin running KKP on AWS in airgapped VPCs (no access to IAM)
I would like to provide controle-plane roleArn and instanceProfile manually
in order to provision clusters without the need for IAM.

### Solution details

When creating a cluster on AWS, the cloud-controller within the seed-controller-manager reaches out to IAM to validate control-plane roleARN and instanceProfile. 
This is not possible in an airgapped VPC/private subnet. Even when provided with a valid role, KKP still wants to verify the role's existence against IAM.

https://github.com/kubermatic/kubermatic/blob/v2.21.1/pkg/provider/cloud/aws/provider.go#L200-L214

Error i’m seeing when creating a cluster without roleARN and instanceProfile:
```
{"level":"error","time":"2022-09-29T10:50:40.406Z","logger":"kkp-cloud-controller","caller":"cloud/cloud_controller.go:136","msg":"Reconciling failed","cluster":"in4756n56h","error":"failed cloud provider init: failed to get role: RequestError: send request failed\ncaused by: Post \"https://iam.amazonaws.com/\": dial tcp 52.119.198.223:443: i/o timeout","errorCauses":[{"error":"failed cloud provider init: failed to get role: RequestError: send request failed\ncaused by: Post \"https://iam.amazonaws.com/\": dial tcp 52.119.198.223:443: i/o timeout"}]}
{"level":"error","time":"2022-09-29T10:50:40.406Z","caller":"controller/controller.go:273","msg":"Reconciler error","controller":"kkp-cloud-controller","object":{"name":"in4756n56h"},"namespace":"","name":"in4756n56h","reconcileID":"22f0ecf1-6d30-4542-8003-7c1aa77b18b0","error":"failed cloud provider init: failed to get role: RequestError: send request failed\ncaused by: Post \"https://iam.amazonaws.com/\": dial tcp 52.119.198.223:443: i/o timeout","errorCauses":[{"error":"failed cloud provider init: failed to get role: RequestError: send request failed\ncaused by: Post \"https://iam.amazonaws.com/\": dial tcp 52.119.198.223:443: i/o timeout"}]}
{"level":"debug","time":"2022-09-29T10:50:40.406Z","logger":"kkp-cloud-controller","caller":"cloud/cloud_controller.go:109","msg":"Reconciling","cluster":"in4756n56h"}
```

Keep in mind, that there is currently no easy way of connecting an airgapped VPC to IAM ( https://docs.aws.amazon.com/vpc/latest/privatelink/aws-services-privatelink-support.html)

### Use cases

Provision KKP user clusters in airgapped /offline/ private subnets.

**Comment by xrstf** [comment]
This sounds similar to what we did in https://github.com/kubermatic/machine-controller/pull/1322 recently.
