### ISSUE TITLE
Test External Clusters AKS

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#11159]
Testing scenarios:

**Important**: while going through creation/import wizards make sure that data is properly fetched from the cloud provider API - for instance keep the network tab opened and filter cloud provider specific calls.

## Cluster creation
1. Create an external cluster using KKP.
2. Login to cloud provider account and verify cluster.
3. Add some machine deployments and see if it provisions nodes on the cloud provider account.
4. Remove machine deployments and see if nodes are removed.
5. Stop the cluster from using providers API (e.g. in its web console) and verify if the status on KKP is updated.
6. Start the cluster from KKP console and check if the change is applied on provider's side.
7. Remove the cluster.

## Cluster import
1. Import an existing cluster using KKP.
2. Follow steps 3-4 from the "Create cluster" section.
3. Unbind the cluster once you finish testing and remove the cluster from provider's account if it was provisioned for tests.

**Comment by rastislavs** [comment]
**1.** No matter how many times I try, creating a new "Machine Deployment" (== Node Pool) ends up with `Failed` Provisioning State:  
 
KKP UI:

![Screenshot 2022-10-07 at 15 11 52](https://user-images.githubusercontent.com/15926980/194613117-21a5f6f6-ccf5-40fd-a6b6-2091be945e97.png)

Azure UI:
![Screenshot 2022-10-07 at 15 11 43](https://user-images.githubusercontent.com/15926980/194613168-ced61552-0a84-4cc8-bca3-888f850d0183.png)

Creating a new node pool for the same cluster from the Azure cloud console is on the other hand always successful.

---

**2.** Operating System is always empty in the "Machine Deployments" list, whereas it is set in Azure cloud console - see the screenshots above.

---

**3.** When updating a Machine Deployment (e.g. to scale the number of replicas), Kubelet version shows "No Kubelet Versions Available" error:

![Screenshot 2022-10-07 at 15 12 42](https://user-images.githubusercontent.com/15926980/194613927-a41fe2d0-f34b-43d3-a538-1b42bec0b1f8.png)

Scaling works, but the error looks weird.

---

**4.** After pausing the cluster, Machine Deployments list is stuck in "Loading..." state:
 
![Screenshot 2022-10-07 at 17 11 49](https://user-images.githubusercontent.com/15926980/194614242-eda2c9e6-0a0a-4990-ab18-b7373a048467.png)

Azure UI shows correctly `Stopped` state for node pools:

![Screenshot 2022-10-07 at 17 12 15](https://user-images.githubusercontent.com/15926980/194614416-9dce170b-2594-4215-96ad-83e2a478ae0d.png)

**Comment by rastislavs** [comment]
All issues are present on the master version as well, so they are not related to the 2.21.2 release specifically.
