### ISSUE TITLE
Move controller-manager cleanup to sidecar

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1116]
Currently the cleanup happens during an init container.
In big clusters this takes quite long.

Therefore the cleanup should be moved to a sidecar. With a very long sleep at the end (1 year)

**Comment by p0lyn0mial** [comment]
I've updated the name to `controller-manager`

**Comment by mrIncompetent** [comment]
Maybe using a separate go routine within the controller-manager which simply calls kubectl could solve the issue as well & is simpler to manage

**Comment by mrIncompetent** [comment]
Really not needed anymore and using a init container can prevent bugs.
With the current cleanup container we can do more complex migrations & as we do all clusters in parallel, time very much improved
