### ISSUE TITLE
Use ServiceAccounts to auth with the API server instead of kubeconfig

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#112]
As the Kubermatic API server is running in-cluster, the kubeconfig should not be required, but instead the Kubermatic API server can use the ServiceAccount tokens to auth with the API server.

An example can be found at https://github.com/kubernetes/dashboard/blob/master/src/app/backend/client/apiserverclient.go

**Comment by scheeles** [comment]
Kubeconfig is required, so that the API server can access multiple cluster
