### ISSUE TITLE
Improve Slack templates for Alerts

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#1124]
I've made a mock up with improvements at the Slack website.
![screenshot from 2018-05-23 14-37-23](https://user-images.githubusercontent.com/872251/40499231-a49c8032-5f81-11e8-9527-c462bd7a9a9a.png)

Right now it adds the Severity, Assign & Action as fields to whats already there. 

Assign is problematic, because we hard code the people into the alerts. We don't work at our customers so it probably doesn't make much sense.
I guess the Action field is the only "real" addition here.

**Comment by p0lyn0mial** [comment]
Where is the alert manager deployed ?

I'm thinking how hard it would be to actually execute the command in the `Action` field on the cluster and display the output in the slack channel.

**Comment by metalmatze** [comment]
We're moving forward with the runbook URL that an alert has.
Hence this is obsolete.
