### ISSUE TITLE
Configure pfsense on hetzner vsphere as jumphost

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1125]
Due to limited IPv4 addresses available on Hetzner, VM's created on our vSphere are using NAT to reach the internet.
A pfsense is the router for the VM's.

Right now the pfsense if not accepting SSH connections on the WAN interface which makes it impossible to access the VM's from the outside.

That needs to change. The pfsense needs to accept connections from the outside so we can use it as jumphost to access all VM's

**Comment by mrIncompetent** [comment]
Maybe we can also just replace the pfsense box with an Ubuntu+ip-frowarding+dnsmasq
Might be simpler

**Comment by thz** [comment]
How was that resolved now?
Just to document that other option:
A VyOS (forked from vyatta) router as VM. 
The configuration would then be very similar to the ubiquiti routers while you can still do anything a Linux can.
The big advantage to a pet ubuntu box is the single configuration file (yay for declarative).

**Comment by thz** [comment]
Did I find the answer?
`[kubermatic/secrets] Added credentials for ubuntu router vm on vsphere (#122)`

**Comment by mrIncompetent** [comment]
Yes, we used a Ubuntu machine with dnsmasq.
We had a pfSense before but we did not get SSH to run. Setting up an Ubuntu seemed to be the easiest Solution.
@thz If you want, feel free to replace it with VyOS in case you are convinced it will make our lives easier.
