### ISSUE TITLE
k8s dashboard is not working without OIDC

### ISSUE THREAD

**Issue by archups** [kubermatic/kubermatic#11250]
### What happened?
User Cluster k8s dashboard is not working without OIDC configuration.

### Expected behavior

User Cluster k8s dashboard should work without OIDC and with static users , since not every customer would have OIDC enabled by default. 

### How to reproduce the issue?

Setup KKP without enabling the featuregate flag `OIDCKubeCfgEndpoint` to `true` in the kubermaticconfiguration. Then create user cluster and try to open the k8s dashboard, you will get OIDC issue as follows :
<img width="631" alt="image" src="https://user-images.githubusercontent.com/25936785/198548895-0d5cf82c-505d-4775-95ff-fd533d3ecebf.png">

### How is your environment configured?

- KKP version: 1.21.x
- Shared or separate master/seed clusters?: separate master/seed

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What operating system are you running in your user cluster?

Rocky Linux 8

**Comment by embik** [comment]
ref https://github.com/kubermatic/kubermatic/pull/10072

**Comment by toschneck** [comment]
with the current debug session we found out that the seed cluster couldn't reach the KKP Dex instance endpoint for OIDC, e.g. `https://kkp.example.com/dex/.well-known/openid-configuration`

As a side, me and @lsviben detected that we have their two bad things
1. An open connection from seed to master is needed
2. If a cluster uses OIDC, it depends on the master where the central DEX instance is running. If Dex is down or Master is not reachable, the access to the clusters will fail with OIDC kubeconfig access.
3. The constant trying to reach OIDC endpoint from the user cluster API server could case `client throtteling` and performance impacts.

**Comment by pkprzekwas** [comment]
Debugging this issue resulted in a following summary:

1. If you install KKP without setting OIDCKubeCfgEndpoint and OpenIDAuthPlugin feature gates, Kubernetes dashboard will no work.
2. Enabling those feature gates by default is blocked because we don't want to create a dependency between user clusters and master's Dex instance.

Action points:
- Improve dashboard by blocking or removing Kubernetes dashboard button in case feature flags are missing.
- Investigate and write a proposal for running a replica of Dex configuration on seed clusters.

**Comment by embik** [comment]
This is a very old issue, but I happened to notice that the changes implemented for this were never documented, or at least I couldn't find it. Shouldn't this kind of limitation be documented [here](https://docs.kubermatic.com/kubermatic/v2.22/tutorials-howtos/administration/admin-panel/interface/#enable-kubernetes-dashboard)? @pkprzekwas can you please take a look if we documented this somewhere besides release notes?
