### ISSUE TITLE
Adopt docker libmachine

### ISSUE THREAD

**Issue by lbb** [kubermatic/kubermatic#113]
We can use `github.com/docker/machine/drives` as our providers for the cloud `provider/cloud`.
This way we can have several datacenters abstracted and implemented.
This should be implemented as a service using swagger for auto generated and self documenting code.

**Comment by mrIncompetent** [comment]
How it should work (theory):
-Dashboard sends a createNodes request to the API
-API saves the nodes data as a ThirdPartyResource (nodes)
-A new controller listens on this ThirdPartyResource and tries to create the nodes
-For the node creation we'll use the docker lib machine drivers
-After the node has been created the ThirdPartyResource needs to be updated with the data from the driver
