### ISSUE TITLE
Seed level OIDC provider instance 

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#11316]
**User story**
As a KKP admin, I would like to be able to configure KKP Root Cluster independent OIDC provider in the Seed's Custom Resource.

**Current state**
KKP relays on OIDC protocol in order to verify user's identity. This helps integrate with external tools like the Kubernetes Dashboard and allows creating OIDC based User Cluster kubeconfigs. 

Global OIDC provider is configured in `kubermatic.yaml` before running installer. With `OpenIDAuthPlugin` feature gate enabled, OIDC configuration is passed down from KKP Root Cluster to Seed Clusters.

As for today, an admin can enable OIDC configuration at the User Cluster level by setting specific feature gates while installing KKP (`OIDCKubeCfgEndpoint` and `OpenIDAuthPlugin`). But there are two main issues:
- It creates a dependency between User Cluster (API-Server) and OIDC provider configured on KKP Root Cluster.
- Seed running behind firewall may not be able to communicate with OIDC provider configured on KKP Root Cluster.

**Acceptance criteria**
- Extend Seed CRD allowing for OIDC provider configuration.
- Seed level OIDC provider configuration should overwrite configuration passed down from master.

**Comment by toschneck** [comment]
ref #11257

**Comment by toschneck** [comment]
LGTM: maybe the seed installer target could also deploy then a seed-local dex by default (potential later improvement)?
