### ISSUE TITLE
Document the needed permissions to create and operate vSphere tags and tags category

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#11351]
**User Story**
Add documentation for the roles which are needed to create tags categories and tags creations, attachment, de-attachment and deletion in vSphere.

**Comment by xmudrii** [comment]
@moadqassem Should this ticket be closed now that https://github.com/kubermatic/docs/pull/1250 is merged?

**Comment by moadqassem** [comment]
> @moadqassem Should this ticket be closed now that [kubermatic/docs#1250](https://github.com/kubermatic/docs/pull/1250) is merged?

Thanks a lot @xmudrii, Not yet, I am working on another PR which reflects this ticket as well, so you can keep it open for now :)
