### ISSUE TITLE
Multi-cluster application workload live migration

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#11408]
### Description of the feature you would like to add / User story

As a IoT infrastructure owner
I would like to migrate containerized workload from one edge cluster to another
in order to have the same workload application on the edge IoT device which was deployed on another edge cluster

### Use cases

- Container is deployed in the edge and we want to migrate it to another edge (IoT / vehicle) device
- Connect two cluster from AWS and GCP
- Connect cloud cluster and on-prem / edge cluster

### Additional information

- https://cloud.google.com/service-mesh/docs/unified-install/multi-cloud-hybrid-mesh

**Comment by rastislavs** [comment]
Cilium Cluster Mesh on KKP with manual setup + workload migration is described in https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/networking/cilium-cluster-mesh/

Further integration will be made as part of https://github.com/kubermatic/kubermatic/issues/11521

**Comment by toschneck** [comment]
Just for the docs, we discovered another option. To use Canal + a global wire guard. Currently only working with kubeadm.
