### ISSUE TITLE
Use jobs instead of pods to process kubeone  external clusters

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#11418]
### Description of the feature you would like to add / User story

As a developer
I would like to Use jobs instead of pods to process kubeone  external clusters
in order to make it easier to  process jobs better than pods

### Solution details

- Create job using kubeone controller
- Use job to check the status of kubeone external cluster processes like import ,upgrade and migrate

**Comment by xrstf** [comment]
Please stop ignoring the issue template. We have it for a reason.
