### ISSUE TITLE
Build common KubeVirt instance types and preferences

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#11466]
We should take a look into https://github.com/kubevirt/common-instancetypes and come up with 
instance types that we want to support in KKP.

Acceptance criteria:
* Document with instance types and preferences we want to support
* Instance types and preference added to KKP after review of the document

**Comment by hdurand0710** [comment]
Document with instancetypes and preferences we want to support: [here](https://docs.google.com/document/d/1WD5H26aK1f7voIn6DlcykX__6RVj0nDwEsgtZxq_qnU/edit#)
