### ISSUE TITLE
Seed Controller - Independent Proxy Configuration for each Seed

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#11509]
### Description of the feature you would like to add / User story

As a admin,
I would like to configure for different Seeds indiviual proxy servers (or no proxy at all)
in order to respect local envrionment restrication.

### Solution details

In the current case we have
- on-premise master/seed with the need of an SSL rewriting proxy 
- extra cloud seed without proxy
Currently the operator will set at every seed the same proxy https://github.com/kubermatic/kubermatic/blob/78be1a96ccbbd07552bedb15a6852a0d6c959e18/pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go#L167

The field [`seed.proxySettings`](https://github.com/kubermatic/kubermatic/blob/2575151e82f29b300feb2330a312705ca47c945c/pkg/apis/kubermatic/v1/datacenter.go#L272) is currently used workers, but we need an option to overwrite the proxy settings of the seed controller manager objects. 

### Use cases

see above

#### *potential workaround*
scale the kubermatic-operator to 0 and patch the deployment manually

**Comment by rastislavs** [comment]
@toschneck Do I understand correctly, that the issue is that the seed-controller-manger proxy configuration does not respect the `seed. ProxySettings` in the datacenter config, and it should?
