### ISSUE TITLE
Option for adding custom annotations to users clusters

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#11569]
### Description of the feature you would like to add / User story

As a user cluster owner
I would like to add custom annotations to a user cluster during creating like it is currently possible with labels
in order to store user cluster owner related informations within the user clusters

### Solution details

- Given the cluster creation flow on the KKP UI, the user should be capable of adding custom annotations to a cluster within the creation

### Alternative approaches

- storing the customer email and some other information in labels but this has the drawback that labels do not permit all characters among others

### Use cases

- when KKP is not used as a self-service tool, it is useful to track information such as email from the customer who requested a cluster or other helpful information from them

**Comment by ahmedwaleedmalik** [comment]
Just talked to a customer and it'd be great if we can include this option for machine deployments as well; configuring annotations for machine deployments.

**Comment by JamesClonk** [comment]
Adding annotations to both, the **Add Machine Deployment** form and also the **Initial Nodes** form in KKP would be great! :+1: 
Currently there are only *Node Labels* and *Node Taints*, but no *Node Annotations*.

**Comment by ahmedwaleedmalik** [comment]
/reopen 

https://github.com/kubermatic/kubermatic/pull/13502 takes care of changes in KKP but we still need modifications in API and UI for this.

**Comment by ahmedwaleedmalik** [comment]
https://github.com/kubermatic/kubermatic/pull/13502, for me seems to be wrongly linked to this ticket. It unfortunately doesn't implement what was required in this ticket.

> I would like to add custom annotations to a user cluster during creating
This ticket was about adding this functionality for Clusters. The PR implements it for ClusterTemplates and that too in a slightly debatable manner https://github.com/kubermatic/kubermatic/pull/13502#discussion_r1735156359

cc @csengerszabo my personal opinion, this ticket needs to be reassigned and worked on.

**Comment by yaa110** [comment]
As @ahmedwaleedmalik  mentioned, it seems the [merged PR](https://github.com/kubermatic/kubermatic/pull/13502) doesn’t fully address the requirements of this issue. @csengerszabo , could you please reassign it to someone else, as I’m unable to continue working on it? A [new PR](https://github.com/kubermatic/kubermatic/pull/13642) has been created to revert the changes. Thanks.
