### ISSUE TITLE
OperatingSystemProfile (OSP) and OperatingSystemConfig (OSC) CRDs are not deployed to the seed cluster

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubermatic#11586]
### What happened?

We install OSP and OSC CRDs with kubermatic-installer. However, we do that only as part of the master stack installation: https://github.com/kubermatic/kubermatic/blob/8a66effea637ff1ed42f25b56e1e05de68402136/pkg/install/stack/kubermatic-master/stack.go#L280-L283

This was supposed to be fixed by #8528 but we added it to the wrong place. It was supposed to be added to the seed stack installation, but it was added to the CRD migration logic.

The reason why we never encountered an issue with this is that if the seed cluster is provisioned by KubeOne, those CRDs will be deployed by KubeOne. But this brings two issues:

- Those CRDs might not be compatible with KKP (see #11585)
- It's not guaranteed that KubeOne will be used to provision the seed cluster

### Expected behavior

kubermatic-installer deploys OSP and OSC CRDs as part of the seed stack.

### How is your environment configured?

- KKP version: main, 2.21, 2.20, and 2.19
- Shared or separate master/seed clusters?: Separate seed clusters

### Additional information

Fixing this issue by itself is considered simple, however, we need to coordinate it with #11585.

**Comment by ahmedwaleedmalik** [comment]
Since we are moving OSP and OSC to user clusters with https://github.com/kubermatic/kubermatic/pull/11710 we don't need this anymore.
