### ISSUE TITLE
Move OperatingSystemProfiles to user clusters

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubermatic#11585]
### Description of the feature you would like to add / User story

We create OperatingSystemProfiles (OSPs) in the seed cluster in two places:

- in the user cluster namespace: operating-system-manager consumes those OSPs from the user cluster namespace when creating OperatingSystemConfigs (OSCs) and the needed Secrets
- in the `kubermatic` namespace: custom OSPs are created in the `kubermatic` namespace -- those OSPs are propagated to the user cluster namespace upon the user cluster creation

The issue with this approach is that it requires us to deploy OSP and OSC CRDs to the seed cluster when installing KKP. We deploy those CRDs with kubermatic-installer.

However, we _already_ deploy those CRDs with KubeOne, and OSM deployed by KubeOne uses those OSPs/OSCs to provision worker nodes in the seed cluster. The following situation might happen:

- The seed cluster is provisioned with KubeOne and it deploys CRDs for OSM v1.1.1
- KKP is installed on that seed cluster and it overrides those CRDs with CRDs for OSM v1.0.0

This might break some OSM, in this case, OSM for the seed/KubeOne cluster.

### Solution details

- Drop OSP and OSC CRDs from the seed cluster. This would require changing:
  - OSM deployment to consume OSPs from the user cluster
    - We also need to move OSPs from the user cluster namespace to the user cluster itself
  - How we handle custom OSPs
    - As an idea, we can put those custom OSPs in Secret in the seed cluster so that we can still centralize OSPs management but avoid having to deploy the OSP CRD
    - Another idea is to have another API group for custom OSPs so that it doesn't conflict with CRDs deployed by KubeOne, but that we still get validation from CRDs

### Alternative approaches

- Create a compatibility matrix for compatible KubeOne and KKP versions. This wouldn't work for two reasons:
  - We don't want to couple KubeOne and KKP. We want to allow users to use the latest KubeOne with their cluster anytime
  - Support policies for KubeOne and KKP are different. KubeOne supports n-2 minor releases at the same time, while KKP supports n-3 minor releases

**Comment by ahmedwaleedmalik** [comment]
This is done now and will be shipped with KKP 2.22.
