### ISSUE TITLE
User cluster graphs in kubermatic dashboard

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#1158]
As a user of kubermatic i want to see some relevant graphs for my cluster.

Old description:
> We can basically show all Metrics that are in the Kubermatic Prometheus running in the `monitoring` namespace. Interesting metrics can also be federated from the cluster Prometheus to the Kubermatic Prometheus, by name.
> 
> What that means:
> We can actually combine metrics from the seed cluster and the user cluster. We could also show the user metrics on the nodeport-proxy and kubermatic-api, though I doubt they are interesting.
Everything that is monitored in the namespace can be exposed too, by federating the metrics. This includes the clusters apiserver, controller-manager, etcd, machine-controller & scheduler.
We might be able to get heapster metrics into our Prometheus too, but that needs to be researched as of now.
> In the future we're going to add the cloud-cost-exporter, which is going to show the current minimal cost of that cluster at the cloud provider,  and can pretty easily add kube-state-metrics to get metrics on the kubernetes objects in the cluster, like number of pods or pods that are crashing.
> 
> I'd say the current issue is to figure out which of those are most interesting to the user, when going to the dashboards.

**Comment by metalmatze** [comment]
PTAL @mrIncompetent @j3ank @kgroschoff

**Comment by mrIncompetent** [comment]
I would limit the available metrics to whats available within the cluster-namespace.
Is there somewhere a overview about what metrics exist already? So we have some real world metrics to look though

**Comment by mrIncompetent** [comment]
ping @metalmatze

**Comment by metalmatze** [comment]
The current way to look into the available metrics would be to port-forward a Prometheus of one cluster namespace and look through the metrics.
In the end, I think, it's rather a question of what we want to display and then try to make sure to get those metrics.

**Comment by mrIncompetent** [comment]
Have we a idea on how to solve the multi-seed situation?
Where the kubermatic api does run in a different cluster as some user-cluster?
