### ISSUE TITLE
Add support for Kubernetes 1.26

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#11614]
### Description of the feature you would like to add / User story

As a KKP user
I would like to create Kubernetes 1.26 clusters
in order to run the latest Kubernetes release.

### Solution details

- Implement support for Kubernetes 1.26 and upgrading from the previous 1.25 release
- Ensure that removed functionality does not leave an upgraded cluster in a broken state (disallow upgrades if e.g. CCM migration needs to be done beforehand)
- Update all component / addon images to a version that supports Kubernetes 1.26 (if available)

If you pick this up, please add stories to the epic for individual tasks.

### Additional information

For reference:
- KubeOne epic: https://github.com/kubermatic/kubeone/issues/2561
- Previous PR adding support: https://github.com/kubermatic/kubermatic/pull/11049

**Comment by embik** [comment]
@xrstf can we close this?

**Comment by xrstf** [comment]
I think so, yeah.
