### ISSUE TITLE
Write etcd s3 saver tool and add charts+config for minio and alerting

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1162]
Detailled description is in the proposal: https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/etcd-backup.md

This issue is about the following points:

> Write example tool to store to S3 & clean up old revisions - 1d
> Add Minio chart to have a in-cluster S3 solution
> Add chart for a generic S3 metrics exporter
> Define alerting rules for the generic S3 exporter

**Comment by kron4eg** [comment]
Is it for real that we want to "write" the tool instead of using https://rclone.org/s3/ for example?

**Comment by mrIncompetent** [comment]
@kron4eg Does rclone support versioning & cleanup by revision?

**Comment by kron4eg** [comment]
@mrIncompetent I'm 99% sure that yes, it does. Its commands like `sync` or `copy` have flag `--backup-dir`

**Comment by kron4eg** [comment]
`rsync --backup` + `rclone sync` will cover our needs I'm pretty sure

**Comment by mrIncompetent** [comment]
Can you provide working example code which does this for a file?

**Comment by kron4eg** [comment]
`rclone sync --backup-dir=s3_remote:backups/$(($(date +%d)%20)) /local/dir s3_remote:`
that's for daily backups, preserving (and rotating) last 20 days (times)

**Comment by mrIncompetent** [comment]
cc @alvaroaleman
