### ISSUE TITLE
Use a labelselector to determine if clusters should be worked on by a controller instance

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1166]
Right now we have the concept of a `workerName` in the cluster controller. `workerName` is an attribute of the cluster and the controllers all contain logic to not act on clusters which do not match their `workerName`.

Instead, we should define a label and then use a labelselector on the listers to only get clusters with the right label.

**Comment by kdomanski** [comment]
https://github.com/kubermatic/kubermatic/blob/89f04ac1ef3dc984bf31b39e1ae7ecdaa377d38d/api/pkg/provider/kubernetes/rbac-compliant-cluster.go#L67-L69

We're going to have to have to migrate existing clusters with the empty label to no label and then fix this. As determined during label selector implementation in the machine controller, it's not possible to cover both cases with a label selector, since multiple constraints can only work as an `AND` operator.

**Comment by alvaroaleman** [comment]
Do we have to migrate? Can't we just do a `labels.NewRequirement(controllerNameLabelKey, selection.Equals, []string{""}`?

I would much prefer it if the label was always there (We could enforce that via the API) because otherwise the user has to know the label name

**Comment by kdomanski** [comment]
The "user" is a developer. I object polluting production data with debug options.
@mrIncompetent WDYT?

**Comment by alvaroaleman** [comment]
"User" may also refer to an operator/customer of ours who wants to debug something. Not putting the label there means that person has a) to know it exists b) know how its named.

I do not quite see how continuing to always put a label on the cluster object can be considered "polluting" it.

**Comment by kdomanski** [comment]
Fair enough.

**Comment by mrIncompetent** [comment]
This will require the user to always attach an empty label to a cluster resource.
If the label is missing nothing will happen and no one knows why. A bad user experience.
I'm very strict against using Metadata as required fields which influence the lifecycle of an Object. I've not seen such a behavior in Kubernetes for now and it seems confusing to me.

Why not follow the same behavior like `deployment.spec.schedulerName` ?
It would follow an existing pattern from Kubernetes core.

**Comment by alvaroaleman** [comment]
I am not completely satisfied with the approach either but I would really like to avoid having custom logic inside every single controller to omit not matching clusters.

At the end of the day this is a technical limitation of Kubernetes, because `fieldSelectors` are not supported for CRDs yet: https://github.com/kubernetes/kubernetes/issues/53459

WRT the bad user experience for non-existing labels: We could add a `MutatingAdmissionWebhook` to have a guarantee the label is always present

**Comment by alvaroaleman** [comment]
How are we going to continue here? The PR in #1828 starts rotting ;)

Would adding a `MutatingAdmissionWebhook` in a subsequent PR that enforces the presence of the label be fine for you @mrIncompetent ?

**Comment by mrIncompetent** [comment]
Thanks for pining!

### To recab:

Our current solution - which needs to be implemented in every controller handling clusters:
```go
if cluster.Labels[kubermaticv1.WorkerNameLabelKey] != cc.workerName {
	glog.V(8).Infof("skipping cluster %s due to different worker assigned to it", key)
	return nil
}
```

We introduce a label, to exclude a cluster from being managed by the kubermatic controller-manager.
Primary usage is to utilize a label-selector for our ClusterInformer, so we don't have to keep a dedicated condition inside the controller code.

### Current suggestions 

#### all without this label key - migration
We could use the `!worker-name`(all without this label key) selector to select clusters which do not have the label & the `worker-name=foo-bar`(all with the label worker-name=foo-bar) selector to select all clusters belonging to a special instance of the kubermatic controller-manager.
This way though requires us to remove the existing label from all cluster, which do not have a value for the `worker-name` key. As right now all clusters get the label key but no value.

#### empty label - AdmissionWebhook to ensure it always exist
We use the selectors `worker-name=` (all with an empty value for worker-name) & `worker-name=foo-bar`(all with the label worker-name=foo-bar).
That would though require the label to always exist - a potential problem here are clusters which are being created not via the kubermatic-api for example: `kubectl create -f cluster.yaml` as here the label might be missing. Labels are by default an optional functionality in Kubernetes (Except for Pods in sets).
A potential solution would be to implement a AdmissionWebhook which would ensure that the label would always exist.


### How Kubernetes does it
Looking at existing similar functionality in Kubernetes:
- `Deployment.Spec.Paused` (Not the exact same - i know)
  - Uses a simple condition in the [sync handler](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller.go#L621)
- `Pod.Spec.SchedulerName`
  - The scheduler utilizes a [cache.FilteringResourceEventHandler](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/factory/factory.go#L228)


The question i have at the moment:
Does this also tries to get rid of the `cluster.spec.paused` field? I see it not being removed in the PR, but https://github.com/kubermatic/kubermatic/issues/1166#issuecomment-414596549 seems more likely to target the pause feature.
The worker-name label is a development feature - not debugging. If someone needs to debug something, the `cluster.spec.paused` field should be sufficient.

**Comment by alvaroaleman** [comment]
So if we consider `.spec.pause` to be the approach suggested to customers if they manually want to test something, I am fine with not having the label by default.

We never got a consent on the question if we want `.spec.pause` to persist: https://github.com/kubermatic/kubermatic/issues/1578#issuecomment-411435368

**Comment by mrIncompetent** [comment]
I would prefer the way with `all without this label key - migration`.
Having a label as a required field on an object seems too confusing for me.

@kdomanski would you mind updating the PR ?
