### ISSUE TITLE
[ccm-migration] [vsphere] v2.21 - CCM migrated clusters should not have validating hook?

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#11688]
### What happened?
1) For our user-cluster with vsphere providers, we faced issue with k8s v1.24 that our storage class was not getting updated to new storage class due to.. webhook "validation.csi.vsphere.vmware.com".

As per slack discussion with @embik - this is a oversight and webhook should not be present, if cluster's external CCM migration has been completed.

2) On the sidenotes, another related issue which led to above issue was.. - if we have a user clusters with k8s v 1.24, external CCM migrated and still the old vsphere provisioner, vsphere-csi-controller starts throwing very vague error "vsphere_volume_util.go:204] Cloud provider not initialized properly". So we should probably add a check and provide some better alerts to users if for some reason old StorageClass is still around after external CCM migration complete and k8s version if 1.23+

### Expected behavior

Storage Class should use the new vsphere csi provisioner.

### How is your environment configured?

- KKP version: 2.21.3
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

vsphere

### What operating system are you running in your user cluster?

Ubuntu 20.04

**Comment by embik** [comment]
> As per slack discussion with @embik - this is a oversight and webhook should not be present, if cluster's external CCM migration has been completed.

I'm not sure about this since I don't have much experience with the vSphere CSI driver. But the current half-deployed state post-migration is definitely wrong.

**Comment by WeirdMachine** [comment]
The webhook should indeed be deployed for a migrated cluster. However at the moment its only partially deployed. The connected PR is intended to fully deploy the the validating webhook for migrated cluster.
