### ISSUE TITLE
Pulling image(s) from custom registry instead of from upstream: kubermatic-installer mirror-images

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#11700]
### What happened?

I would like to use `kubermatic-installer mirror-image` to mirror images from the upstream registries, but at least for the custom user-cluster addons image it's trying to pull from the `dockerRepository` in the `KubermaticConfiguration` instead. That makes no sense to me at all.

(And it's not even using the `dockerTagSuffix`, so pulling would fail anyway.)

### Expected behavior

Pull/mirror all images from the upstream registries

### How to reproduce the issue?

1. define a custom addon image url in the `KubermaticConfiguration`.
2. run `kubermatic-installer mirror-images` with that manifest
3. observe it pulling the image from the custom url

```
$ kubermatic-installer mirror-images --config kubermatic.yaml foo.registry.bar
INFO[0000] Extracting addon manifests from image…        image="some.registry.internal/foo/bar/custom-addons:v2.21.4" temp-directory=/var/folders/m2/0x9pjrf10m3gd9h0v77xwgr40000gp/T/imageloader608481999
INFO[0000] Downloading image…                            image="some.registry.internal/foo/bar/custom-addons:v2.21.4"
INFO[0000] Executing command…                            command="docker pull some.registry.internal/foo/bar/custom-addons:v2.21.4" image="some.registry.internal/foo/bar/custom-addons:v2.21.4"
ERRO[0000] Command failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?  command="docker pull some.registry.internal/foo/bar/custom-addons:v2.21.4" image="some.registry.internal/foo/bar/custom-addons:v2.21.4"
ERRO[0000] ❌ Operation failed: failed to create local addons path: failed to download addons image: failed to download some.registry.internal/foo/bar/custom-addons:v2.21.4: failed to pull image some.registry.internal/foo/bar/custom-addons:v2.21.4: exit status 1. 
```

### How is your environment configured?

- KKP version: 2.21.4 EE
- Shared or separate master/seed clusters?: N/A

### Provide your KKP manifest here (if applicable)

```
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
    name: kubermatic
    namespace: kubermatic
spec:
...
    userCluster:
        addons:
            dockerRepository: some.registry.internal/foo/bar/custom-addons
            dockerTagSuffix: "14"
```

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A but running kubermatic-installer on darwin amd64

**Comment by judge-red** [comment]
Okay, I guess this is intended behavior, as the help says:
```
      --addons-image string     Docker image containing KKP addons, if not given, falls back to the Docker image configured in the KubermaticConfiguration
```

So I guess the bug is:
- `dockerTagSuffix` isn't observed

And I'd add a feature request:
- add flag to use the upstream addons image even if one is specified in the `KubermaticConfiguration`

No idea what the intended use case here is. I thought mirror-images is supposed to mirror new versions of images into my private registry. But instead it's trying to pull the new image from my private registry - where it doesn't exist yet.

**Comment by judge-red** [comment]
Well, this might make sense during the initial installation, but I would like to mirror images before an upgrade - just in case it wasn't clear what our situation was. Sure, I could go comment these two lines out and re-add them later, but that's cumbersome and doesn't make much sense imho.

**Comment by judge-red** [comment]
Now that I got it to print out the images (thanks to using `--addons-path`), I can say that the same issue is true for the dashboard image. (You probably expected this, but wanted to be explicit.)

**Comment by embik** [comment]
> Now that I got it to print out the images (thanks to using `--addons-path`), I can say that the same issue is true for the dashboard image. (You probably expected this, but wanted to be explicit.)

Yes, that's expected, thanks for the feedback nonetheless. Any image with a registry override should behave the same way.
