### ISSUE TITLE
Test Seed Level OIDC Provider - Test Release 2.22

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/kubermatic#11727]
## Prerequisites
- KKP instance with enabled `OIDCKubeCfgEndpoint` and `OpenIDAuthPlugin` feature gates
- OpenID Connect Provider, e.g. Okta or KeyCloak (*other than the test's KKP instance default one*)
- Permission to modify/create Seed

**NOTES**: 
- this test affects other users of a configured Seed.  Affected functionalities: user-cluster kubeconfigs, kubernetes dashboards, webterminal.
- if you don't want to configure you own Okta or KeyCloak it's fine to use one from another environment. For instance, while testing on dev, configure Seed's OIDC provider to point to https://latest.snapshots.k8c.io/. Testing may require to modify list of RedirectURIs placed inside dex config map.

## Common test steps
1. Edit your Seed adding [configuration for dedicated OIDC provider](https://github.com/kubermatic/kubermatic/blob/main/pkg/apis/kubermatic/v1/datacenter.go#L914-L945) based on the example below:
```yaml
spec:
  oidcProviderConfiguration:
    issuerURL: https://latest.snapshots.k8c.io/dex
    issuerClientID: kubermaticIssuer
    issuerClientSecret: SuperSecretValue
    cookieHashKey: SuperSecretCookieHash
    cookieSecureMode: true
```
2. Provision a new user cluster on the modified Seed.

## Test user-cluster kubeconfig
3. Go to cluster details and fetch its kubeconfig.
  3a. Verify that you have been redirected to the Seed level OIDC provider (https://latest.snapshots.k8c.io/dex in case of the example above)
4. Use the downloaded kubeconfig and verify that you can list pods in the default namespace (should return an empty list).
  4a. **Only if you used a different email to authenticate with Seed level OIDC provider** Go to the RBAC tab of your user cluster and add a new cluster-admin user with the email used to get the kubeconfig in the third step.
  4b. Go back to your console and try to list namespaces. It should succeed.

## Test Kubernetes dashbaord
3. Go to the dashboard's cluster details view and open Kubernetes Dashboard.
  3a. Verify that you have been redirected to the Seed level OIDC provider (https://latest.snapshots.k8c.io/dex in case of the example above)
4. In the Kubernetes Dashboard, switch namespace to kube-system and verify if system resources are displayed.

## Test Webterminal
**NOTE**:  Possible only if you used the same email to authenticate with Seed level OIDC provider as with default KKP OIDC Provider.
3. Go to the dashboard's cluster details view and open Webterminal.
4. Wait for provisioning.
5. Verify that it works by listing namespaces inside web terminal.

**Comment by hbernardo** [comment]
LGTM
