### ISSUE TITLE
Test Cilium CNI managed by Applications - Test Release KKP 2.22

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#11725]
## 1. Create a new cluster with Cilium 1.13.0 and test the following:

 - Verify that cluster creation is successful and cluster networking works normally
 - Verify that Hubble UI works (by port-forwarding to it) - it is now deployed automatically
 - Test editing CNI configuration via UI:
   - Under Cluster details > Applications, click on "Show System Applications" and edit Cilium configuration:
     - test changing restricted configuration - e.g. `ipam.operator.clusterPoolIPv4PodCIDR` - this should be denied by webhook
     - test changing allowed configuration - e.g. `operator.replicas` - this should work and the change should be visible in the user cluster
 - Test editing CNI configuration via ApplicationInstallation in the user cluster (`kubectl edit ApplicationInstallation cilium -n kube-system`) - it should work the same way as via UI

## 2. Test CNI upgrade from Cilium 1.12 without Hubble
 - Create a cluster with Cilium 1.12
 - Upgrade CNI to Cilium 1.13
 - Verify that cluster creation is successful and cluster networking works normally
 - Verify that Hubble UI works (by port-forwarding to it) - it is now deployed automatically

## 3. Test CNI upgrade from Cilium 1.12 with Hubble
 - Create a cluster with Cilium 1.12
 - Deploy the Hubble addon
 - Upgrade CNI to Cilium 1.13
 - Verify that cluster creation is successful and cluster networking works normally
 - Verify that Hubble UI works (by port-forwarding to it)

## 4. Test editing Cilium defaultValues in ApplicationDefinition
 - Edit cilium ApplicationDefinition in KKP master cluster (`kubectl edit ApplicationDefinition cilium -n kube-system`) and change `spec.defaultValues` - e.g. change `operator.replicas` to 3
 - This change should not have any effect on existing clusters
 - Create a new cluster with Cilium 1.13.0 and observe the new default values were applied

## 5. Test custom initial CNI values
- Create a new cluster with Cilium 1.13.0 and under "Advanced Network Configuration", click "Edit CNI Values":
![Screenshot 2023-01-26 at 09 48 16](https://user-images.githubusercontent.com/15926980/214794153-3604b663-da34-4342-8536-2e5be9f75435.png)
- The pre-loaded yaml should match the default values of ApplicationDefinition configured in the step 4
- Modify the yaml
- Create a new cluster and verify that it was created with the provided initial values
- Perform the same test on a cluster template and creating the cluster from the template

**Comment by embik** [comment]
All working according to @WeirdMachine.
