### ISSUE TITLE
User Cluster MLA: grafana-agent instead of promtail/prometheus - Test Release 2.22

### ISSUE THREAD

**Issue by wurbanski** [kubermatic/kubermatic#11737]
With KKP 2.22, if Usuer Cluster MLA is enabled, instances of prometheus and promtail in user clusters should be replaced with grafana-agent
* [x] pre-configured rules are migrated correctly
* [x] no leftover resources exist in namespace `mla-system`
* [x] no mentions of `prometheus` or `promtail` exist in the namespace (replaced with `monitoring-agent` and `logging-agent`1 respectively)

**Comment by rastislavs** [comment]
Works as expected, both for new clusters and existing clusters after KKP upgrade.
