### ISSUE TITLE
Kubermatic Installer should auto-discover CSI drivers installed

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#11740]
### Description of the feature you would like to add / User story

When using the `--storageclass` flag provided by `kubermatic-installer`, the installer should auto-discover available CSI drivers on the target cluster and if it recognises one, use that instead of built-in `StorageClass` provisioners. Those built-in/in-tree provisioners are going away soon.

### Solution details

- `kubermatic-installer deploy [...] --storageclass` scans the target cluster and choses a CSI provisioner if it finds one it recognises for the chosen cloud provider.
- The command should check if the cluster version allows to use in-tree provisioners.
- It should error if it cannot find a suitable CSI driver nor a usable in-tree provider.

### Alternative approaches

Remove the `--storageclass` flag as in-tree provisioners will go away eventually.

### Use cases

Installing KKP on more recent Kubernetes versions and trying to use the automatic `StorageClass` feature.

### Additional information

n/a

**Comment by xrstf** [comment]
When you say "it recognizes one", what does that mean exactly? Suppose there are multiple `provisioner: disk.csi.azure.com` storage classes in the cluster, would all of them match? Which one is chosen in that case?

**Comment by embik** [comment]
> When you say "it recognizes one", what does that mean exactly? Suppose there are multiple `provisioner: disk.csi.azure.com` storage classes in the cluster, would all of them match? Which one is chosen in that case?

There is a resource called `CSIDriver` (https://kubernetes-csi.github.io/docs/csi-driver-object.html) that is created when a CSI driver is installed to register it. So drivers/provisioners cannot exist twice and we can scan for object names on that level. It doesn't make sense to check StorageClasses since that's what we want to provision.
