### ISSUE TITLE
Test Web Terminal (backend) - Test Release KKP 2.22

### ISSUE THREAD

**Issue by hbernardo** [kubermatic/kubermatic#11758]
**Steps:**
- Create a user cluster (any cloud provider) and wait for it to be ready (including initial machine deployment).
- Inspect the page (developer tools) and leave it open for monitoring WS terminal connection in "Network" tab.
![image.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/ccb05767-fdbb-43b2-bf85-89e0822d2265)
- Start the web terminal by clicking on the top-right button inside the cluster page and login using same user for OIDC. 
![image.png](https://images.zenhubusercontent.com/624ac3c06ac30663c7c6816d/132144b1-dc52-4373-87dd-7dded394517f)
- Wait for the terminal to be ready and try to execute any `kubectl` command, like:
```
kubectl get pods -A
```
- Get the user cluster kubeconfig and check that you have deployed in the user cluster (with webterminal prefix): pods (one for executing the commands and other one for later cleanup), network policy, configmap and job (for cleanup):
```
kubectl get pods -n kube-system | grep webterminal
kubectl get networkpolicy -n kube-system | grep webterminal
kubectl get configmap -n kube-system | grep webterminal
kubectl get job -n kube-system | grep webterminal
```
- Check that you cannot "ping" to the user cluster web terminal pod from another pod (security restriction). For that you can run a test pod:
```
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: kube-system
spec:
  containers:
  - args:
    - while true; do sleep 30; done;
    command:
    - /bin/bash
    - -c
    - --
    image: quay.io/kubermatic/web-terminal:0.3.0
    name: test-pod-container
EOF
```
- `exec` into the test pod:
```
$ kubectl exec -it test-pod -n kube-system -- /bin/sh
```
- Try to "ping" to the deployed web terminal pod IP (you shouldn't be able to receive any response).
- Wait for 25 minutes (since you started the web terminal) and check the WS messages in developer tools: it should start receiving expiration messages from the backend (one per minute).
- Wait more 7 minutes and check that all web terminal related k8s resources are destroyed in the user cluster (pod, network policy, configmap and job).

**Comment by rastislavs** [comment]
The testing scenario works as expected.

Filed an issue for ARM platform though: https://github.com/kubermatic/kubermatic/issues/11884
