### ISSUE TITLE
Remove support for docker

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#11762]
With Kubernetes version 1.24, support for `dockershim` was officially removed from Kubernetes. Since we don't support k8s v1.23 anymore we should remove support for docker in favor of containerd. 

https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim

**Acceptance Criteria**:
- Docker is no longer supported
- Users are pushed(maybe automated) to upgrade to containerd container runtime before upgrading to KKP 2.22. This can be done in the installer

**Comment by xmudrii** [comment]
TODO: Document how to migrate all clusters to containerd using `kubectl patch`.

**Comment by ahmedwaleedmalik** [comment]
TODO: Document how to to migrate all existing MDs for the user cluster.

**Comment by ahmedwaleedmalik** [comment]
Is this complete now?

**Comment by embik** [comment]
@ahmedwaleedmalik I'm adding a section in https://github.com/kubermatic/docs/pull/1357 that mentions docker support removal and how to upgrade. From my side we can close the ticket as this will be included for sure, WDYT?
