### ISSUE TITLE
Openstack cluster provisioning and upgrading - Test Release 2.22

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#11777]
Please go through #11769 for instructions. 

Supported Operating Systems:
- [x] Ubuntu
- [x] CentOS
- [x] Flatcar
- [x] RHEL
- [x] Rocky Linux

Supported Kubernetes versions:
- [x] v1.24.9
- [x] v1.25.5
- [x] v1.26.0

Upgrades:
- [x] Upgrade from v1.24.9 -> v1.25.5
- [x] Upgrade from v1.25.5 -> v1.26.0

Note: the only supported container runtime now is containerd.

**Comment by xrstf** [comment]
```
========================== RESULT ===========================
Parameters:
  KKP Version............: v2.22.0-alpha.0-8-g7cb59f8d6 (EE)
  Name Prefix............: "xrstfqa"
  OSM Enabled............: true
  Dualstack Enabled......: false
  Konnectivity Enabled...: false
  Cluster Updates Enabled: true
  Enabled Tests..........: [gcr-images loadbalancer metrics securitycontext storage usercluster-gcr-images usercluster-rbac usercluster-seccomp]
  Scenario Options.......: []

Test results:
[ OK ] - openstack-ubuntu-containerd-1.25.5 (updated to v1.26.0) (34m34s)
```

**Comment by xrstf** [comment]
Flatcar 1.26 took a bit longer because we accidentally used an older image that did not work anymore:

> failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService
