### ISSUE TITLE
extend /versions endpoint with default version

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#1178]
Right now the `/versions` endpoint only returns `[]MasterVersion`
```
type MasterVersion struct {
	Version               *semver.Version `json:"version"`
	AllowedNodeVersions   []string        `json:"allowedNodeVersions"`
}
```

As we want to pre-select the default version in the dashboard, we need an info which version is the current default version.

**Comment by mrIncompetent** [comment]
sgtm
