### ISSUE TITLE
New nodes fail to bootstrap in KKP 2.20 and 2.19 due to missing packages

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#11793]
### What happened?

We discovered that new nodes in KKP 2.20 and 2.19 fail to bootstrap because upstream removed package versions for both `docker` and `containerd` that are referenced in user data used to bootstrap said nodes. Since the packages no longer exist but we pin to specific versions, `setup.sh` fails and nodes will never join the user cluster.

### Expected behavior

New nodes should continue to join the user cluster.

### How to reproduce the issue?

- Use KKP 2.20 or 2.19.

### How is your environment configured?

- KKP version: 2.20.12 & 2.19.14
- Shared or separate master/seed clusters?: n/a

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

n/a

### What operating system are you running in your user cluster?

Ubuntu, CentOS, RHEL, Rocky Linux

### Additional information

- KKP patch releases are planned to address this issue.
- KKP 2.21 is not affected.

**Comment by judge-red** [comment]
Are all versions of the listed operating systems affected? Does the used Kubernetes version matter?

Please provide more information so customers can make an informed call on how critical applying this patch release is for them. Currently it sounds like we have to drop everything to apply it, but as we don't think we've encountered this issue yet, that's unlikely to hold true.

**Comment by xmudrii** [comment]
@judge-red To our knowledge, affected operating systems are Ubuntu, CentOS, RHEL, and Rocky Linux. Flatcar and SLES are not affected. Operating system version doesn't matter.

Technically speaking, we're using Docker repositories on all those operating systems to install containerd and Docker. This is both for containerd-based and Docker-based user clusters. Suddenly, Docker removed containerd 1.4 and Docker 19.03 from all their repositories. Unless you have your own package mirror, you'll not be able to provision **new** worker nodes. This is not affecting existing nodes/machines.

Please note, that this only affects KKP 2.20 and 2.19. This issue does **not** affect KKP 2.21.

If you're using KKP 2.20 or 2.19, we strongly recommend upgrading to the new patch releases **as soon as possible**. We're working on those patch releases as we're speaking and we'll update this ticket as soon as they're ready.

**Comment by xmudrii** [comment]
@judge-red Is it possible that your user clusters are using containerd with Operating System Manager (OSM) enabled?

**Comment by judge-red** [comment]
@xmudrii Thanks for your quick response and the additional insights.

We're on KKP 2.20.11 but we're not enabling the OSM. Does this issue only affect OSM users? Doesn't sound like it, but I just verified that I could create a Ubuntu 20.04 Machine in an existing user cluster with no problem. I don't think we're using a package mirror, unless there's a transparent cache somewhere that I'm not aware of.

**Comment by xmudrii** [comment]
Final update to this ticket: we did another in-depth investigation. We were mistakenly using Ubuntu 22.04 with KKP 2.20 and 2.19, however, Ubuntu 22.04 isn't supported on those KKP versions. That's why we were seeing issue with packages, because containerd 1.4 and Docker 19.03 doesn't exist on Ubuntu 22.04. Ubuntu 20.04 is not affected by this issue, and same goes for CentOS 7, Rocky Linux, and RHEL.

For CentOS, Rocky Linux, and RHEL, we're unsure was there some temporary issue with using older packages. As far as I know, there were issues present with those three, but we are not able to reproduce those any longer.

With that said, patch releases are out, but upgrading is not urgent.

**Comment by embik** [comment]
Closing this ticket as per the comment from @xmudrii, as this is - after all - not a problem.
