### ISSUE TITLE
Include commit hash as version

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#118]
The API & Controller should print the commit hash from which they were built.
It should be printed on application start.

Info: http://stackoverflow.com/questions/11354518/golang-application-auto-build-versioning

So we should do the following:
-Add an uninitialized variable to the api (/api/cmd/kubermatic-api/main.go) & controller (/api/cmd/kubermatic-cluster-controller/main.go)
-Add set commit hash to variable on build (wercker.yaml & http://devcenter.wercker.com/docs/environment-variables/available-env-vars)
-Print variable in main()

**Comment by lbb** [comment]
I'd rather like to not do this in the binary. We could insert it as a label for the pod.

**Comment by scruplelesswizard** [comment]
Using a label for the pod only provides the correct version if the application was deployed with the right version attached. Injecting it in to the binary gives us a single source of truth, regardless of where it was built or deployed

**Comment by mrIncompetent** [comment]
Please reopen if still needed. Not needed from my side anymore
