### ISSUE TITLE
Optionally bind Presets to Projects - Test Release 2.22

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#11807]
We added support for binding presets to projects in #7260. Documentation will be updated by https://github.com/kubermatic/docs/pull/1333. Please test this new feature:

## Instructions

- Create a new Preset and bind it to several projects (both via the UI and via `kubectl`).
- Verify you can use the Preset from projects that are on the allowlist.
- Verify you cannot use the Preset from projects that are NOT on the allowlist.
- Update the project allowlist (this is only available via `kubectl`) and repeat verification for changed project allowlist.
- Do this for several providers as we've added new API endpoints for all of them.

Feel free to find other ways to break this feature.

**Comment by hbernardo** [comment]
Found some bugs that were fixed here: https://github.com/kubermatic/dashboard/pull/5675
Despite that, everything looks good.
