### ISSUE TITLE
test Application helm source - Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11825]
# how to test
Create an application definition with a Helm source using an

- [x] HTTP repository without authentication (can use an opensource chart)
- [x] HTTP repository with authentication (can use https://goharbor.io/docs/1.10/install-config/demo-server/)
- [x] OCI  repository without authentication (can use an opensource chart)
- [x] OCI repository with authentication (can use https://goharbor.io/docs/1.10/install-config/demo-server/)

doc: kubermatic/docs#1323

# expected result
For each variant, application should be installed with success.

**Comment by hdurand0710** [comment]
HTTP repository without authentication : OK
works as expected.

1 finding:

**Comment by hdurand0710** [comment]
HTTP repository with authentication
1 finding:

**Comment by hdurand0710** [comment]
OCI repository without authentication : OK
works as expected

**Comment by hdurand0710** [comment]
OCI repository with authentication: OK
works as expecteed
