### ISSUE TITLE
Test application cluster wizard  - Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11828]
# How to test
During cluster creation wizard add an application and create cluster

# Expected result

- [x] application's workload  is installed in the desired namespace
- [x] can edit application through the UI

**Comment by rastislavs** [comment]
Needs to be retested with the fix https://github.com/kubermatic/dashboard/issues/5679 in.

**Comment by rastislavs** [comment]
Works as expected now.
