### ISSUE TITLE
Test application Git source - Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11826]
# how to test
Create an application definition with a GIT source using an

- [x] GIT repository without authentication
- [x] GIT repository with authentication
- [x] GIT repository with authentication ("classic source credentials" ) . The helm chart in the git repository must have dependencies on a private registry (you can store private dependencies using  https://goharbor.io/docs/1.10/install-config/demo-server.  you will have to use [template credentials](https://github.com/kubermatic/docs/pull/1323/files#diff-d3ffd8271455ebcc6407011d0038d486a09cb7c1a53204636bfd305dd924287aR248-R274) to specify credentials for helm registry)

doc: kubermatic/docs#1323

# expected result
For each variant, application should be installed with success.

**Comment by hdurand0710** [comment]
GIT repository with authentication
- authentication not defined in ApplicationDefinition
```
ailed to download application source: failed to clone repository: authentication required . Please check your configuration or contact your KKP Administrator.
```

Correct failure

**Comment by hdurand0710** [comment]
Git repo with dependencies with credentials: OK
