### ISSUE TITLE
Test Application cluster template - Release 2.22

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#11829]
# How to test
create a cluster template with an application and create a cluster from it

# Expected result

- [x] application's workload  is installed in the desired namespace
- [x] can edit application through the UI

**Comment by SimonTheLeg** [comment]
I think we can flag this test for now, as already a bug has been discovered:
https://github.com/kubermatic/dashboard/issues/5679

**Comment by rastislavs** [comment]
Works as expected.
