### ISSUE TITLE
Test User Deletion Validation - Test Release KKP 2.22

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#11842]
- Test user deletion is not allowed if the user is the sole owner of a project which has resources: clusters/external clusters
- Allow user deletion if there are multiple owners

Steps:
- Have clusters/external clusters in your owned project
- Try to delete your user using kubectl
- Check if the request is rejected from the validation webhook
- Add another owner to your project
- Again try deleting your user
- Check if the request is accepted from validation webhook

**Comment by hbernardo** [comment]
Found an issue following this steps:
- Create an user cluster in the project
- Add someone as project owner
- Delete the user
- Login again (user is recreated)
- Remove the other project owner
- Try to delete the user

**Result:** in that case, you are able to delete the user even the user is the sole owner of a project which has a cluster.

**Comment by hbernardo** [comment]
Created an issue for that: https://github.com/kubermatic/kubermatic/issues/11896
