### ISSUE TITLE
User SSH Keys Agent is not working on ARM machines

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#11895]
### What happened?

In a user cluster with worker nodes based on ARM platform, User SSH Keys Agent pods are not able to run with the error `exec /bin/bash: exec format error` which suggests a platform mismatch.

### Expected behavior

The User SSH Keys Agent images should be built with multi-arch support like the rest of KKP user cluster images and should work on both amd64 and arm platforms.

### How to reproduce the issue?

Create a cluster on AWS and chose "arm64 architecture" for the machine deployments. After cluster creation check logs of `user-ssh-keys-agent` pod in `kube-system` namespace of user cluster.

### What cloud provider are you running on?

AWS

### What operating system are you running in your user cluster?

Ubuntu 22.04.

**Comment by ahmedwaleedmalik** [comment]
We had a similar issue recently with https://github.com/kubermatic/kubermatic/issues/11884

**Comment by embik** [comment]
This _should_ be working and we last fixed it in #11606. What KKP version was this observed on?

**Comment by ahmedwaleedmalik** [comment]
I observed this behavior in our dev environment yesterday when I was updating the image for web-terminal. If it's not reproducible, which would be a bit strange, we can always close this ticket.

**Comment by embik** [comment]
> I observed this behavior in our dev environment yesterday when I was updating the image for web-terminal. If it's not reproducible, which would be a bit strange, we can always close this ticket.

I mean, if you encountered it on dev it seems we're still not good on this, I just wanted to point out this was a problem recently fixed so I was wondering if this an older version. But dev should definitely not have it anymore.

**Comment by SimonTheLeg** [comment]
I am having some issues reproducing this on a fresh cluster. Here’s what I tried on dev and qa. Setup a cluster with an arm node and ssh-keys enabled:

![image](https://user-images.githubusercontent.com/20774623/219341073-37561e29-a4ba-4b14-8944-0bfb9930ba7d.png)
![image](https://user-images.githubusercontent.com/20774623/219341096-62bed56a-6edd-4438-b978-b5fe8aa27c48.png)

Logs of these two look fine to me:

```log
+ user-ssh-keys-agent-t7m8w › user-ssh-keys-agent
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:10.839Z","caller":"cli/hello.go:36","msg":"Starting KKP User SSH-Key Agent (Enterprise Edition)...","version":""}
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:10.981Z","logger":"controller-runtime.metrics","caller":"manager/manager.go:415","msg":"Metrics server is starting to listen","addr":":8080"}
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:10.982Z","caller":"runtime/asm_arm64.s:1172","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:10.983Z","caller":"controller/controller.go:242","msg":"Starting EventSource","controller":"kkp-usersshkeys-controller","source":"kind source: *v1.Secret"}
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:10.983Z","caller":"controller/controller.go:242","msg":"Starting EventSource","controller":"kkp-usersshkeys-controller","source":"channel source: 0x400027b220"}
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:10.983Z","caller":"controller/controller.go:242","msg":"Starting Controller","controller":"kkp-usersshkeys-controller"}
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:11.084Z","caller":"controller/controller.go:242","msg":"Starting workers","controller":"kkp-usersshkeys-controller","worker count":1}
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:11.213Z","caller":"usersshkeysagent/usersshkeys_controller.go:189","msg":"File has been updated successfully","file":"/root/.ssh/authorized_keys"}
user-ssh-keys-agent-t7m8w user-ssh-keys-agent {"level":"info","time":"2023-02-16T10:23:11.263Z","caller":"usersshkeysagent/usersshkeys_controller.go:189","msg":"File has been updated successfully","file":"/home/ubuntu/.ssh/authorized_keys"}
```

```log
+ user-ssh-keys-agent-72q7s › user-ssh-keys-agent
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.232Z","caller":"cli/hello.go:36","msg":"Starting KKP User SSH-Key Agent (Enterprise Edition)...","version":""}
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.425Z","logger":"controller-runtime.metrics","caller":"manager/manager.go:415","msg":"Metrics server is starting to listen","addr":":8080"}
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.426Z","caller":"runtime/asm_arm64.s:1172","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.427Z","caller":"controller/controller.go:242","msg":"Starting EventSource","controller":"kkp-usersshkeys-controller","source":"kind source: *v1.Secret"}
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.427Z","caller":"controller/controller.go:242","msg":"Starting EventSource","controller":"kkp-usersshkeys-controller","source":"channel source: 0x40000a2ff0"}
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.427Z","caller":"controller/controller.go:242","msg":"Starting Controller","controller":"kkp-usersshkeys-controller"}
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.528Z","caller":"controller/controller.go:242","msg":"Starting workers","controller":"kkp-usersshkeys-controller","worker count":1}
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.532Z","caller":"usersshkeysagent/usersshkeys_controller.go:189","msg":"File has been updated successfully","file":"/root/.ssh/authorized_keys"}
user-ssh-keys-agent-72q7s user-ssh-keys-agent {"level":"info","time":"2023-02-16T09:47:19.533Z","caller":"usersshkeysagent/usersshkeys_controller.go:189","msg":"File has been updated successfully","file":"/home/ubuntu/.ssh/authorized_keys"}
```

**However what is interesting: If we take a look at the the recently build versions of user-ssh-keys-agent, we can see that only some of them are using child manifests to publish an arm64 version.** For example comparing 5c7c84335269b7 (which is what my containers currently use) with c6f98c3503aa448, we can see that these images are structured differently. 

![image](https://user-images.githubusercontent.com/20774623/219342673-da8d03cf-17c0-4d67-85b3-81af65db67ef.png)

Currently this leads me to believe we might have some inconsistency in our build/push pipeline? Will investigate further

**Comment by SimonTheLeg** [comment]
after a bit of digging we think we figured it out: In our registry we mix images from the standard prow job that pushes images and from the setup-kubermatic-in-kind script. The script also pushes the images to the registry, but only builds an amd64 version to save time.

Could it be that one of the pods that you were working on pointed to one of the non multi-arch versions @ahmedwaleedmalik?

Lastly, I have created #11922 to separate the repositories, which I think we can tackle after the release to avoid confusion in the future.

**Comment by embik** [comment]
Important: This is not solved/caused by the findings of @SimonTheLeg and myself, but apparently a problem appearing randomly and infrequently. Since we didn't have a commit hash to work on we couldn't figure this out when looking at it, but it appears that this happens for builds from release commits. But only with some. It's unclear why exactly but it happened on the commit designated for release.

cc @xrstf

**Comment by embik** [comment]
We changed the way multi-arch images are built and hopefully do not run into buildah silently using the wrong architecture base image if rate limited. At least at the time, we suspected that to be the issue reported here, but it was impossible to reproduce.
