### ISSUE TITLE
Implement feature gate to enable/disable the share cluster

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/kubermatic#11934]
### Description of the feature you would like to add / User story

Add new feature flag to show/hide "Share Cluster" feature from admin panel. This configuration was earlier handled in the dashboard [config,json](https://github.com/kubermatic/dashboard/blob/main/modules/web/src/assets/config/config.json#L6) from assets folder but it user willl not be aware of this setting. So therefore we decided to toggle the settings from admin panel.

Also removing the defaulting of `share_kubeconfig`  from being set in kubermatic configuration. 

[Default UI Configuration ](https://github.com/kubermatic/kubermatic/blob/main/pkg/defaulting/configuration.go#L882)
[Removed Defaulting from UI](https://github.com/kubermatic/dashboard/pull/5764/files#diff-d82c3bf00b3add2232bb68e05398a1f829a6f9e82028938d736a6d39bf5cf3c7L6)

**Comment by ahmedwaleedmalik** [comment]
You don't need a feature gate for this. Just a boolean flag in the `KubermaticSettings` CRD just like https://github.com/kubermatic/kubermatic/blob/main/pkg/apis/kubermatic/v1/settings.go#L57
