### ISSUE TITLE
Limit project deletion to administrators if creation is

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#11945]
### Description of the feature you would like to add / User story

As a Administrator
I would like to limit the project deletion to administrators if project creation is limited to administrators
in order to avoid accidentals cluster deletions.  

### Solution details

If `restrictProjectCreation` is set in `KubermaticSetting` (configuration can be done in the KKP Dashboard Admin Panel, section `Limits`/`Restrict Project Creation to Administrators), then we should also restrict the Project Deletion to Administrators.

### Alternative approaches

We should discuss if it would be better to define a new option to restrict the Project deletion to administrators or base the behaviour on the `restrictProjectCreation` option.

**Comment by ahmadhamzh** [comment]
what is the approach do we need to do here ? create new option for deletion or based on `restrictProjectCreation` ?
