### ISSUE TITLE
Kubermatic API Server is deployed to seed clusters

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1195]
**Issue:**
At the moment Kubermatic API Server is deployed into the following seed clusters:

cloud.kubermatic.io asia-east1-a-1
cloud.kubermatic.io us-central1-c-1

**Expectation:**
Kubermatic API Server is deployed solely into the master cluster

**Comment by mrIncompetent** [comment]
Optimal way would be splitting the chart. 
Though it might be a bit tricky as the controller & api share some resources.

**Comment by pkavajin** [comment]
Blocked since Kubermatic RBAC related things need to be changed, because they expect cluster resources to be present at the master system instead of seed.

**Comment by p0lyn0mial** [comment]
@pkavajin I have just merged changes to RBAC controller. It reads cluster resources from seeds, though in our case we keep the resources also on the master so there is a special case that treats the the master also as a seed.

**Comment by kron4eg** [comment]
to now lose track of what was done: https://github.com/kubermatic/kubermatic/tree/feature/1195_SeperateMasterAndSeedCharts

**Comment by kdomanski** [comment]
@p0lyn0mial I'm pretty sure it was fixed in #2824. PTAL and close if the issue is solved.

**Comment by p0lyn0mial** [comment]
thanks, closing the issue.
