### ISSUE TITLE
Generated agent.yaml for mla-monitoring-agent is not valid

### ISSUE THREAD

**Issue by akurz** [kubermatic/kubermatic#11973]
### What happened?

I updated an installation of KKP 2.21.5 to 2.22.0 including the user-cluster MLA setup. There are additionally the kube-state-metrics and the node-exporter addons installed. The generated config-map wit the extra scrape config is not valid as it includes  trailing whitespaces. 

Because of this the mla-monitoring-agent is unable to start. When I remove the node-exporter and kube-state-metric addons it starts working again. 

It also looks like the agent is not restarted on configmap update - I triggered a restart manually.

### Expected behavior

The agent.yaml with extra scrape config is running as expected and the agent is reloaded on configmap changes e.g. after adding a monitoring addon.

### How to reproduce the issue?

Have node-exporter or kube-state-metrics addon installed in addtion to the user cluster mla setup ... be sure the mla-monitoring-agent is restarted and tries to use the new configuration.

### How is your environment configured?

- KKP version: 2.22.0
- Shared or separate master/seed clusters?: shared

### Additional information

Looking at the code that extra indentation comes from:

https://github.com/kubermatic/kubermatic/blob/main/pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/configmap.go#L321

**Comment by embik** [comment]
Thanks for reporting this @akurz, we will have it fixed for the next KKP 2.22 patch release.
