### ISSUE TITLE
kube-proxy migration from ipvs to epbf does not work

### ISSUE THREAD

**Issue by 0asys** [kubermatic/kubermatic#11994]
### What happened?

Kubermatic v2.21 allows a manual CNI migration with this documentation:
https://docs.kubermatic.com/kubermatic/v2.21/tutorials-howtos/networking/cni-migration/

The part to migrate the CNI from canal to cilium worked well.

After the CNI Migration I tried to migrate the kube proxy from ipvs to ebpf with the steps described which failed to change the kube proxy mode from `ipvs` to `ebpf`.
It stays on ipvs and no error is emitted. 

* Konnectivity is enabled
* Cilium CNI is used
* Needed "unsafe" labels are set:
  * `kube-proxy-replacement: true`
  * `unsafe-cni-migration: true`
  * `unsafe-cni-upgrade: true`

```
curl -X 'PATCH' \
  'https://kaas/api/v2/projects/76zkrqkzsk/clusters/g8bfdbp6h2' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'authorization: Bearer xxx' \
  -d '{"spec": {"clusterNetwork": {"proxyMode": "ebpf"}}}'
  ```

Response:
```
{
  "id": "g8bfdbp6h2",
  "name": "k8s-test-dev01",
  "creationTimestamp": "2022-09-20T19:41:16Z",
  "labels": {
    "customer": "test",
    "env": "dev",
    "kube-proxy-replacement": "true",
    "unsafe-cni-migration": "true",
    "unsafe-cni-upgrade": "true"
  },
  "type": "kubernetes",
  "spec": {
    "cloud": {
      "dc": "openstack-test-LS",
      "openstack": {
        "floatingIPPool": "public",
        "network": "kubernetes-g8bfdbp6h2",
        "securityGroups": "kubernetes-g8bfdbp6h2",
        "routerID": "0a5add56-40be-4371-88ee-befbf9c6a327",
        "subnetID": "74e7f3f2-686a-44fa-8c48-0d6efab8d39e"
      }
    },
    "version": "1.24.9",
    "oidc": {},
    "enableUserSSHKeyAgent": true,
    "enableOperatingSystemManager": false,
    "kubernetesDashboard": {
      "enabled": true
    },
    "auditLogging": {},
    "opaIntegration": {
      "webhookTimeoutSeconds": 10
    },
    "mla": {},
    "containerRuntime": "containerd",
    "clusterNetwork": {
      "ipFamily": "IPv4",
      "services": {
        "cidrBlocks": [
          "10.11.0.0/16"
        ]
      },
      "pods": {
        "cidrBlocks": [
          "10.99.0.0/16"
        ]
      },
      "nodeCidrMaskSizeIPv4": 24,
      "dnsDomain": "cluster.local",
      "proxyMode": "ipvs",
      "ipvs": {
        "strictArp": true
      },
      "nodeLocalDNSCacheEnabled": true,
      "konnectivityEnabled": true
    },
    "cniPlugin": {
      "type": "cilium",
      "version": "v1.12"
    },
    "exposeStrategy": "NodePort"
  },
  "status": {
    "version": "1.24.9",
    "url": "https://g8bfdbp6h2:30623",
    "externalCCMMigration": "NotNeeded"
  }
}
```

### Expected behavior

Kube-Proxy mode changes from `ipvs` to `ebpf`.

### How to reproduce the issue?

* Create cluster with canal and kube-proxy `ipvs`
* Follow https://docs.kubermatic.com/kubermatic/v2.21/tutorials-howtos/networking/cni-migration/ to migrate CNI and kube-proxy
* 

### How is your environment configured?

- KKP version: v2.21.6
- separate master/seed clusters

### Provide your KKP manifest here (if applicable)

Not applicable, KKP User

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

Ubuntu 22.04

**Comment by rastislavs** [comment]
Hi,
this most likely just an KKP API layer issue. The other option mentioned in the docs:

> by editing the cluster CR in the Seed Cluster (`kubectl edit cluster <cluster-name>`).

should work for you, could you please try? OFC, we will fix the API issue.

**Comment by bpereto** [comment]
Hi @rastislavs,

We tried the other option by editing the cluster CR in the Seed cluster and worked as expected.
