### ISSUE TITLE
Reload configuration without restarting API server

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#120]
The API server needs to be restarted if to pick up changes in the config file, which will result in some downtime. We can mitigate that by reloading the config either via a watch on the files, or by adding a reload endpoint

**Comment by lbb** [comment]
In some parts of the projects it's done by parsing the files every time. For example https://github.com/kubermatic/api/blob/develop/provider/cloud/digitalocean/provider.go#L145 We should also get rid of this pattern.

**Comment by mrIncompetent** [comment]
No real benifit
