### ISSUE TITLE
Cilium does not meet systemd based distribution requirements

### ISSUE THREAD

**Issue by mate4st** [kubermatic/kubermatic#12104]
### What happened?

From my understanding systemd introduced a change that manages resources that are owned by cilium. Triggering a change in the network stack effectively deletes those resources, leaving the network in an unstable state. 

To mitigate this it is possible to adjust systemd as explained in the cilium docs: https://docs.cilium.io/en/v1.13/operations/system_requirements/#systemd-based-distributions

This can be achieved in KKP by creating a custom OSP or to create an initial daemon.

### Additional information

Requirements cilium with systemd: https://docs.cilium.io/en/stable/operations/system_requirements/#systemd-based-distributions

Possible fix: https://github.com/cilium/cilium/pull/24288

Initial reported Issue: https://github.com/kubermatic/machine-controller/issues/1587

**Comment by toschneck** [comment]
@moadqassem @WeirdMachine is still open or did we released a fix?

**Comment by WeirdMachine** [comment]
> @moadqassem @WeirdMachine is still open or did we released a fix?

If there would be a fix this would be closed.

**Comment by xrstf** [comment]
The potential fix mentioned in the ticket was merged and will be released in Cilium 1.24, I guess. If and when we update to such a version, how could we verify that this problem is solved? @WeirdMachine

**Comment by vethastanley** [comment]
@xrstf do you mean Cilium 1.14? If so I checked the release notes and there is no mention of a fix for this issue.

**Comment by WeirdMachine** [comment]
This is confirmed to be no longer an issue in cilium v1.14. The systemd issue is closed and their docs are about to get updated, removing this issue.
