### ISSUE TITLE
Prepare etcd templates for distroless image in 3.5.7 version

### ISSUE THREAD

**Issue by cnvergence** [kubermatic/kubermatic#12109]
### Description of the feature you would like to add / User story

Since version [3.5.7](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#security) all etcd images are built upon distroless base images.
We should check and update all our etcd templates and related jobs, like etcd-defragger to not exec `/bin/sh` and come up with alternatives to prepare KKP for etcd bump.

### Additional information

Currently, KKP is using etcd in version 3.5.6.

### How is your environment configured?

- KKP version: v2.22.1

**Comment by embik** [comment]
I believe this is is not a bug as current functionality is not impacted, can you please re-categorise it accordingly @cnvergence?

**Comment by cnvergence** [comment]
Right, this issue needed some changes
