### ISSUE TITLE
Make addons to be part ot the cluster specification

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1211]
At the moment `Addons` are created when a 
request to create a new cluster is made. This can can be problematic as the following can happen:

1. we successfully stored/created a `cluster`
2. but for some reason we are unable to create an `Addon`

I think that we can end up in inconsistent state:
we cannot re-create the `cluster` - the request will be rejected. As a result the controller is not going to install all the required `Addons`.

**Comment by p0lyn0mial** [comment]
For the time being we have to change/update both `ClusterProvider` and `RBACCompliantClusterProvider` 

https://github.com/kubermatic/kubermatic/blob/08c61caca92618ddf0e4a912f6940fff0c168327/api/pkg/provider/kubernetes/rbac-compliant-cluster.go#L112

**Comment by mrIncompetent** [comment]
Just realizing that we cannot simply replace the Addon-resources with a string slice on the cluster as this will break the cleanup of Addons.

Right now every Addon has a Finalizer. When the Addon gets deleted, all objects belonging to that Addon will be deleted from the user-cluster.


Possible solution - though not fully convinced yet:
Have both + a control loop which will manage Addon resources based upon the string slice on the cluster object ?
@alvaroaleman @p0lyn0mial WDYT?

**Comment by alvaroaleman** [comment]
> Have both + a control loop which will manage Addon resources based upon the string slice on the cluster object ?

By that you mean a string slice element and a finalizer per addon?

Why put the addons on the cluster object in the first place? Why not simply identify relevant addons for a cluster by the `.spec.cluster` field and do cleanup via a finalizer on the addon?

**Comment by mrIncompetent** [comment]
> > Have both + a control loop which will manage Addon resources based upon the string slice on the cluster object ?

> By that you mean a string slice element and a finalizer per addon?

Correct.

> Why put the addons on the cluster object in the first place? Why not simply identify relevant addons for a cluster by the .spec.cluster field and do cleanup via a finalizer on the addon?


The reason for putting the Addons on the cluster struct:
- Single API call from the API to create a cluster
  Right now we do a call to create the cluster and a new call for each Addon. When one fails we end up in a broken state.

Also when the API creates the Addons, it expects the Namespace to be already there - which eventually fails as the cluster-controller creates the Namespace. Though this might be something we need to solve differently (Clusters will be namespaced in the future).


Or maybe we simply leave everything as is & add retry logic to the API?

**Comment by p0lyn0mial** [comment]
> Have both + a control loop which will manage Addon resources based upon the string slice on the cluster object ?

I think that this sgtm to me, an API call to create a cluster sets up desired state, in particular it puts a list of Addons that are required to be installed for the cluster. Next the controller makes sure that the current state is equal to the desired one.

**Comment by alvaroaleman** [comment]
How do we configure add-ons with this string-slice approach?

**Comment by mrIncompetent** [comment]
Addon configuration won't be possible via this approach.
I'll add some retry logic to the API first.

**Comment by alvaroaleman** [comment]
Maybe we could create the addons on the cluster object as `[]map[string]string` or `map[string]map[string]string` to allow configuration?

The cluster-controller would then move the addons to an addon crd asap and the API will shows an aggregated view of  addons on the cluster objects and addons as crd. WDYT?

**Comment by mrIncompetent** [comment]
Not worth the effort. I won't introduce a new level of abstraction just to avoid the API calls.

I added retry logic to the endpoint

**Comment by p0lyn0mial** [comment]
@mrIncompetent can you also update `RBACCompliantClusterProvider` ?

https://github.com/kubermatic/kubermatic/blob/08c61caca92618ddf0e4a912f6940fff0c168327/api/pkg/provider/kubernetes/rbac-compliant-cluster.go#L112
