### ISSUE TITLE
Support default applications for user clusters

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#12121]
### Description of the feature you would like to add / User story

As a KKP admin, I would like to enable or enforce some applications by default. For example, one might want to enforce applications like Kyverno, and Falco for all the user clusters to maintain a good security posture.

Right now, to install applications by default we rely on cluster templates. This is not ideal since KKP admins can't enforce applications since users might create the cluster directly, instead of relying on a cluster template.

### Solution details

- Support for configuring default values for applications
- We would like to split enable and enforce; in case an admin just enables a default application, it can still be toggled off by the KKP user.
- Ensure that KKP users cannot delete the Applications

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubermatic/issues/12958
- [ ] https://github.com/kubermatic/dashboard/issues/6458
```

**Comment by csengerszabo** [comment]
Should you be able to edit the application from the Application step in the wizard? Like namespace, name, values.yaml? @ahmedwaleedmalik
