### ISSUE TITLE
reuse cloud-config code between this repo and machine controller

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#1213]
We have cloud-config generation templates in two places currently:
 * this repo at https://github.com/kubermatic/kubermatic/blob/529c7e75dfa54680a4b4d8f8a8e430e2e74bbbb5/api/pkg/resources/cloudconfig/configmap.go#L44
 * `machine-controller` https://github.com/kubermatic/machine-controller/blob/13dbbe59e0bef78ecd3d740fe9d43526067fbf7a/pkg/cloudprovider/cloud/provider.go#L25

This code is somewhat divergent and can easily become more so - it would require special care to apply every improvement and every fix in both places. It would therefore be preferable to refactor both projects in order to reuse the `machine-controller`'s cloud-config code here, since it's already vendored.

**Comment by alvaroaleman** [comment]
Hm but the code in the `machine-controller` is for nodes whereas the code here is for the `controller-manager`, those two may do different hings and thus require different configuration

**Comment by kdomanski** [comment]
Don't they receive the same configuration currently?

**Comment by alvaroaleman** [comment]
Right now this may be the case but this may easely change in the future which is why sharing does not make sense
