### ISSUE TITLE
Create alerting for Seeds being unreachable from master

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12192]
### Description of the feature you would like to add / User story

As a KKP admin
I would like to receive alerts if a Seed is unreachable from the the master
in order to be able to respond to infrastructure issues.

### Solution details

- We need Prometheus alert definitions for Seeds being unreachable from the master.
- Perhaps this information is not exposed in metrics yet, so we also need to make sure we have metrics that we can write alerting definitions for.

### Use cases

When a Seed is either going down or is unreachable due to network connectivity breaking, administrators need to react. We should surface this information via alerting to administrators.

**Comment by xrstf** [comment]
Step 1: We need to define some seed metrics. Apparently KKP doesn't produce those yet.
