### ISSUE TITLE
Create Health and Readiness checks

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#122]
Write down a specification what our API & Controller should provide via health check endpoints

**Comment by scruplelesswizard** [comment]
All health endpoints should use the following semantics 

> "expecting on success that the response has a status code greater than or equal to 200 and less than 400."

We can return some text as well, but the only thing required is that it returns a status code >=200 AND <400.

As for what should be checked, please review https://vimeo.com/173610242
ref: http://kubernetes.io/docs/user-guide/pod-states/#container-probes
