### ISSUE TITLE
User cluster controller constantly OOMKilled

### ISSUE THREAD

**Issue by Baja-KS** [kubermatic/kubermatic#12204]
### What happened?
User cluster controller gets oomkilled almost immediately on start
Logs before kill:
`{"level":"info","time":"2023-04-28T08:14:45.502Z","logger":"http-prober","caller":"http-prober/main.go:127","msg":"Probing","attempt":1,"max-attempts":100,"target":"https://apiserver-external.cluster-pn94hvvjv7.svc.cluster.local./healthz"}
{"level":"info","time":"2023-04-28T08:14:45.509Z","logger":"http-prober","caller":"http-prober/main.go:116","msg":"Hostname resolved","hostname":"apiserver-external.cluster-pn94hvvjv7.svc.cluster.local.","address":"10.100.29.84:443"}
{"level":"info","time":"2023-04-28T08:14:45.514Z","logger":"http-prober","caller":"http-prober/main.go:140","msg":"Endpoint is available"}
{"level":"info","time":"2023-04-28T08:14:45.682Z","caller":"cli/hello.go:36","msg":"Starting KKP User-Cluster Controller-Manager (Community Edition)...","version":"v2.21.4"}
I0428 08:14:46.819795       1 request.go:601] Waited for 1.035360887s due to client-side throttling, not priority and fairness, request: GET:https://apiserver-external.cluster-pn94hvvjv7.svc.cluster.local./apis/opensearchservice.aws.crossplane.io/v1alpha1?timeout=32s
{"level":"info","time":"2023-04-28T08:14:50.124Z","logger":"controller-runtime.metrics","caller":"metrics/listener.go:44","msg":"Metrics server is starting to listen","addr":"0.0.0.0:8085"}
{"level":"info","time":"2023-04-28T08:14:50.153Z","caller":"user-cluster-controller-manager/main.go:262","msg":"registering components"}
{"level":"info","time":"2023-04-28T08:14:50.153Z","caller":"user-cluster-controller-manager/main.go:276","msg":"registering controllers"}
{"level":"info","time":"2023-04-28T08:14:50.154Z","caller":"user-cluster-controller-manager/main.go:315","msg":"Registered usercluster controller"}
{"level":"info","time":"2023-04-28T08:14:50.154Z","caller":"user-cluster-controller-manager/main.go:341","msg":"Registered user RBAC controller"}
{"level":"info","time":"2023-04-28T08:14:50.154Z","caller":"user-cluster-controller-manager/main.go:350","msg":"Registered Flatcar controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"user-cluster-controller-manager/main.go:357","msg":"Registered nodelabel controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"user-cluster-controller-manager/main.go:362","msg":"Registered node-version controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"user-cluster-controller-manager/main.go:367","msg":"Registered clusterrolelabeler controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"user-cluster-controller-manager/main.go:372","msg":"Registered role-cloner controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"user-cluster-controller-manager/main.go:378","msg":"Registered owner-binding-creator controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"user-cluster-controller-manager/main.go:394","msg":"Registered constraintsyncer controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"user-cluster-controller-manager/main.go:400","msg":"Registered Application Installation controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"user-cluster-controller-manager/main.go:405","msg":"Registered Resource Usage controller"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"runtime/asm_amd64.s:1571","msg":"Starting server","kind":"health probe","addr":"[::]:8086"}
{"level":"info","time":"2023-04-28T08:14:50.155Z","caller":"runtime/asm_amd64.s:1571","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8085"}
I0428 08:14:50.256254       1 leaderelection.go:248] attempting to acquire leader lease kube-system/user-cluster-controller-leader-lock...
{"level":"info","time":"2023-04-28T08:14:50.256Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-constraint-synchronizer","source":"kind source: *v1.Constraint"}
{"level":"info","time":"2023-04-28T08:14:50.256Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-constraint-synchronizer"}
{"level":"info","time":"2023-04-28T08:14:50.357Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-constraint-synchronizer","worker count":1}
{"level":"info","time":"2023-04-28T08:14:51.345Z","logger":"controller-runtime.healthz","caller":"healthz/healthz.go:128","msg":"healthz check failed","statuses":[{},{}]}
{"level":"info","time":"2023-04-28T08:14:56.344Z","logger":"controller-runtime.healthz","caller":"healthz/healthz.go:128","msg":"healthz check failed","statuses":[{},{}]}
{"level":"info","time":"2023-04-28T08:15:01.345Z","logger":"controller-runtime.healthz","caller":"healthz/healthz.go:128","msg":"healthz check failed","statuses":[{},{}]}
{"level":"info","time":"2023-04-28T08:15:06.344Z","logger":"controller-runtime.healthz","caller":"healthz/healthz.go:128","msg":"healthz check failed","statuses":[{},{}]}
I0428 08:15:07.175965       1 leaderelection.go:258] successfully acquired lease kube-system/user-cluster-controller-leader-lock
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.APIService"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.ServiceAccount"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.Service"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.ConfigMap"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.Secret"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.Role"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.RoleBinding"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.ClusterRole"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.ClusterRoleBinding"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.MutatingWebhookConfiguration"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.ValidatingWebhookConfiguration"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.CustomResourceDefinition"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.Deployment"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.PodDisruptionBudget"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"rbac-user-cluster-controller","source":"kind source: *v1.ClusterRole"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.NetworkPolicy"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"rbac-user-cluster-controller","source":"kind source: *v1.ClusterRoleBinding"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.DaemonSet"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.Secret"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.ConfigMap"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.Cluster"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-user-cluster-controller","source":"kind source: *v1.Cluster"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-user-cluster-controller"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-flatcar-controller","source":"kind source: *v1.Node"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-flatcar-controller"}
{"level":"info","time":"2023-04-28T08:15:07.179Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"rbac-user-cluster-controller"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-node-version-controller","source":"kind source: *v1.Node"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-node-version-controller"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-node-labeler","source":"kind source: *v1.Node"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-cluster-role-label-synchronizer","source":"kind source: *v1.ClusterRole"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-owner-binding-creator","source":"kind source: *v1.ClusterRole"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-cluster-role-label-synchronizer"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-owner-binding-creator","source":"kind source: *v1.ClusterRoleBinding"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-owner-binding-creator"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-role-cloner-controller","source":"kind source: *v1.Role"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-app-installation-controller","source":"kind source: *v1.ApplicationInstallation"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-role-cloner-controller","source":"kind source: *v1.Namespace"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-role-cloner-controller"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-node-labeler"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting EventSource","controller":"kkp-app-installation-controller","source":"informer source: 0xc000b345a0"}
{"level":"info","time":"2023-04-28T08:15:07.180Z","caller":"controller/controller.go:241","msg":"Starting Controller","controller":"kkp-app-installation-controller"}
{"level":"info","time":"2023-04-28T08:15:10.581Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"rbac-user-cluster-controller","worker count":1}
{"level":"info","time":"2023-04-28T08:15:10.581Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-node-version-controller","worker count":1}
{"level":"info","time":"2023-04-28T08:15:10.581Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-node-labeler","worker count":1}
{"level":"info","time":"2023-04-28T08:15:10.581Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-app-installation-controller","worker count":1}
{"level":"info","time":"2023-04-28T08:15:10.581Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-cluster-role-label-synchronizer","worker count":1}
{"level":"info","time":"2023-04-28T08:15:10.581Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-owner-binding-creator","worker count":1}
{"level":"info","time":"2023-04-28T08:15:10.581Z","caller":"node-version-controller/controller.go:124","msg":"Determined new oldest node version","version":"1.23.15"}
{"level":"info","time":"2023-04-28T08:15:10.582Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-flatcar-controller","worker count":1}
{"level":"info","time":"2023-04-28T08:15:10.582Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-role-cloner-controller","worker count":1}
{"level":"info","time":"2023-04-28T08:15:10.584Z","caller":"controller/controller.go:241","msg":"Starting workers","controller":"kkp-user-cluster-controller","worker count":1}
{"level":"info","time":"2023-04-28T08:15:11.853Z","logger":"kkp-app-installation-controller","caller":"applications/installer.go:108","msg":"reconciling namespace 'argo-cd'","applicationinstallation":"kube-system/argocd"}
{"level":"info","time":"2023-04-28T08:15:24.097Z","logger":"kkp-app-installation-controller","caller":"action/upgrade.go:142","msg":"preparing upgrade for kube-system-argocd","applicationinstallation":"kube-system/argocd"}
`

### Expected behavior

User cluster controller should not be oomkilled almost immediately on start,and resource limits should be editable,
as we could not find the option in the Cluster resource (we have searched under cluster.spec.componentsOverride object for an option)

### How is your environment configured?

- KKP version: v2.21.4
- Shared or separate master/seed clusters?: Shared

### What cloud provider are you running on?

Hetzner Cloud

### What operating system are you running in your user cluster?

Ubuntu 22.04

**Comment by embik** [comment]
Likely related to #12078, but I'm not sure since we only backported the fix for that to 2.22.

**Comment by embik** [comment]
Hey @Baja-KS, this should be fixed by #12247, which is to be merged and released in the next KKP 2.21 patch release.
