### ISSUE TITLE
Unable to import KubeOne external clusters

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#12262]
### What happened?

Importing a KubeOne external cluster fails with the cluster being stuck in `SSHError` phase/state and the consequent job that we run for KubeOne clusters being stuck in an error state.

![Screenshot from 2023-05-08 16-00-04](https://github.com/kubermatic/kubermatic/assets/85109141/8ccfdebc-2a0d-46ec-a481-864303543653)

### How to reproduce the issue?

Create a KubeOne cluster on AWS and try to import it using KKP dashboard, on our dev environment.

### How is your environment configured?

- KKP version: Dev envrionment
- Shared or separate master/seed clusters?: N/A

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Reproducible on all cloud providers.

**Comment by ahmedwaleedmalik** [comment]
@ahmadhamzh do we have anything else to add in the ticket description or this is it?

**Comment by ahmadhamzh** [comment]
> @ahmadhamzh do we have anything else to add in the ticket description or this is it?

i just add an image

**Comment by xrstf** [comment]
Tried to reproduce.

* Took an existing KubeOne cluster and used KubeOne 1.6 to create the config.
* Added it to KKP.
* Cluster was added with no issues, status is green, no failed jobs. All good.

**Comment by ahmedwaleedmalik** [comment]
> 

Cool, if it's not reproducible which is a bit strange :D then we should close this issue.

**Comment by xrstf** [comment]
The only issue I encountered was that the current KKP dev system doesn't yet know about the most recent changes to kubeone's v1beta2 API and so the strict unmarshalling failed becaues of the `cloudProviders.disableBundledCSIDrivers` field. We should bump the Go dependency on KubeOne before releasing KKP 2.23, maybe even need to backport it (from a UX standpoint it's a terrible behaviour to just say "nope, invalid manifest, no details, try again" :grin: )
