### ISSUE TITLE
Cluster Controller hits NPE

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#123]
The cluster controller on k.loodse.com has died several times due to hitting an NPE. We should investigate the cause and resolve.

**Comment by scheeles** [comment]
Where you see, that the cluster controller hits NPE. It is running since 73d without a restart.

```
NAME                                    READY     STATUS    RESTARTS   AGE
cluster-controller-v1-573317636-5xc86   1/1       Running   0          73d
```

**Comment by scruplelesswizard** [comment]
This issue needs more investigation. We can reopen if it occurs again
