### ISSUE TITLE
Deploy in various architectures - Test Release 2.23

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12322]
In previous QA, we made the mistake to not test all possible architectures in which you can deploy KKP. This has caused problems with CRDs not present on the master (#12186).

This time, let's test all available architectures so we don't forget about this. **This should be done separately from the QA environment**.

## What to Test

- [x] combined master/seed setup (master and seed share the same cluster) with a single seed
- [x] combined master/seed setup with two seeds (one "local" to the master, one remote)
- [x] dedicated master and seed setups (master and seed do NOT share the same cluster)

## How to Test

1. Set up KKP in the scenario you are testing.
2. Make sure your master and seed are healthy (e.g. by checking `kubectl get seeds` for seed health) and that no (persistent) errors are logged in KKP components.
3. Create a user cluster from the master dashboard.
4. Make sure it gets all set up, is healthy and available. Download its kubeconfig and try to connect to it.
5. Delete the user cluster from the master dashboard.
6. Ensure that the cluster is cleaned up and that KKP components still do not log any errors.

**Comment by WeirdMachine** [comment]
No issues found
