### ISSUE TITLE
Allow disabling clusterbackup metrics collector in seed-controller-manager

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12331]
### Description of the feature you would like to add / User story

As a KKP admin
I would like to disable cluster backup related metrics
in order to not query the external S3 storage every time metrics are scraped.

### Solution details

- Make registration of the `clusterbackup` metrics collector [in the seed-controller-manager](https://github.com/kubermatic/kubermatic/blob/aa748eede3baeb8bfa6dba445080805cd6741261/cmd/seed-controller-manager/main.go#L231) optional.
- Provide a configuration option either via the `Seed` object or some other means.

### Use cases

When your S3 for etcd backups is either slow or has a lot of objects, this collector querying it could create latency and cost that might not be desired. Allowing admins to turn this off might increase metrics performance for the seed-controller-manager.

### Additional information

The metrics collected by this collector seem to somewhat overlap with what the `s3-exporter` collects.

**Comment by LittleFox94** [comment]
Some ideas, I think the first one would be the better choice of those two

### Collecting outside the metrics handler

Could be changed to regularly collect the backup metrics outside the metrics handler, the handler only returning the latest collected data.

A new flag for backup metrics collection interval could also be used for disabling that altogether.

Also nice for HA Prometheus setups, only collecting this once, no matter how many Prometheus instances scrape this.

### Moving those metrics to another endpoint

Moving that collector to another endpoint to scrape less regular than the other metrics could also be an idea, though I don't see a non-clunky way to do that.

Would have the benefit of configuring the collect interval for this via Prometheus, as it still collects on every scrape.

But it's still more expensive when using a HA Prometheus setup, with multiple Prometheus instances scraping (and thus collecting) the same data
