### ISSUE TITLE
Allow vpn-client to list nodes.

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1233]
The vpn-client (running on user-cluster worker) shall allow access to all worker's kubelets ports. For that reason it would be helpful to have access to list the nodes.

Also in general it sounds okay to me to allow a worker access to the list of nodes.

Question: should we add node-listing to the default role/user or make something specific for the openvpn-client? I would say node-listing can go into default allowance.

`root@openvpn-client-5565c6f8f8-s5cgt:/# kubectl get nodes
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:kube-system:default" cannot list nodes at the cluster scope
`

**Comment by mrIncompetent** [comment]
Please use a dedicated serviceaccount. There's no need to extend the priviledges of the default serviceaccount.
