### ISSUE TITLE
Test Grafana recovery - Test Release 2.23

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#12337]
In #12195 we improved the way the MLA controller handles recovery situations when the Grafana storage is deleted. This ticket is about testing that functionality.

1. Install KKP with MLA enabled.
2. Create 2 or more KKP projects. They can just be empty.
3. Validate that both projects exist as orgs in the MLA Grafana.
4. Choose one of the 2 projects and `kubectl edit` it:
    * change the name (`spec.name`) however you like
    * change the `mla.k8c.io/organization` annotation and make it point to the _other_ project's org (i.e. here you create a conflict)
5. The MLA controller should now realize during the next reconciliation that the org ID does not match the org name in Grafana and should create a new Grafana org and then update the Project's `mla.k8c.io/organization` annotation. Wait and see if the org ID annotation on the Project is changed. Also there should then be 3 orgs in Grafana.

**NB:** Changing the `spec.name` is necessary only for testing, as Grafana org names must be unique and if we didn't change the project's name, the MLA controller would fail to reconcile (there is no way for it to list orgs, so it cannot possibly figure out that such an org already exists). In a real recovery scenario, _all_ orgs are _gone_ and no renaming is necessary to recover. (You could also change the test procedure here to nuke the Grafana PVC).

**Comment by hc2p** [comment]
Works as expected.
Reconciliation created a new Grafana org and assigned the new org ID to the name-changed project.
