### ISSUE TITLE
Test `kubermatic-installer local kind` command

### ISSUE THREAD

**Issue by wozniakjan** [kubermatic/kubermatic#12340]
PR https://github.com/kubermatic/kubermatic/pull/12216 introduced new command for the installer
```
kubermatic-installer local kind
```
Which has the main purpose of creating `kind` cluster and installing KKP there + auto-configuring KubeVirt for user clusters.

It should work all the way for Linux machines, local KubeVirt user clusters for macOS may not be performing efficiently due to KubeVirt and KVM + QEMU emulation layer (I wasn't able to figure out nested virtualization on macOS).

This ticket should test that:
1. `kubermatic-installer local kind` works out of the box in https://github.com/kubermatic/kubermatic/releases/tag/v2.23.0-beta.2
2. the KKP dashboard and API are operational
3. KubeVirt user cluster can be created and eventually becomes operational (it's expected to take [around 18 minutes](https://github.com/kubermatic/kubermatic/pull/12216#discussion_r1192624339) and needs sufficient resources, 2CPU + 8GB RAM) 
3.1. temporarily requires manual intervention in v2.23.0-beta.2 but should be addressed before the release - https://github.com/kubermatic/kubermatic/pull/12402

**Comment by wozniakjan** [comment]
just fyi https://github.com/kubermatic/kubermatic/pull/12402

**Comment by xmudrii** [comment]
@wozniakjan I'm running into the following issue:

```
FATA[0000] failed to create 'kind' config: open /home/marko/Projects/src/k8c.io/kubermatic/_build/examples/kind-config.yaml: no such file or directory
```

How do I get this config?

**Comment by wozniakjan** [comment]
hey @xmudrii, thanks for testing this. The `kubermatic-installer` creates the `kind-config.yaml` itself but it expects the release directory structure, such as directories `examples` and `charts` being available with the release content. However, from the path it looks like you built it from the repo and not executing in a downloaded release? So I suppose `examples` and `charts` are not present under your `_build` directory.
```
$ wget https://github.com/kubermatic/kubermatic/releases/download/v2.23.0-beta.2/kubermatic-ce-v2.23.0-beta.2-linux-amd64.tar.gz
$ tar -xzvf kubermatic-ce-v2.23.0-beta.2-linux-amd64.tar.gz
$ ./kubermatic-installer local kind
```

**Comment by xmudrii** [comment]
@wozniakjan I managed to proceed after taking the tarball, but then I encountered this issue:

```
INFO[0000] Creating kind cluster ...
FATA[0000] failed to create 'kind' cluster: exit status 1
ERROR: unknown shorthand flag: 'n' in -n
```

I managed to debug it and found out that it was caused by too old kind version on my machine (v0.12.0, the latest is v0.20.0). We should probably check for kind version before creating the cluster.

**Comment by xmudrii** [comment]
* I got the cluster created but installer had some warnings:
    ```
    WARN[0307]       Timed out waiting for the LoadBalancer service "nginx-ingress-controller/nginx-ingress-controller" to become ready.
    WARN[0307]       Please check the Service and, if necessary, reconfigure the
    WARN[0307]       nginx-ingress-controller Helm chart. Re-run the installer to apply
    WARN[0307]       updated configuration afterwards.
    INFO[0307] KKP installed successfully, login at ...
    ```
    The nginx-ingress-controller is up and running however. I think we should hide this warning if it's not important for this setup.
* We should also print credentials for logging in to the KKP dashboard, as it's currently unclear what credentials should be used
* `kubevirt/virt-handler` pod is crashlooping with the following error:
    ```
    {"component":"virt-handler","level":"fatal","msg":"Failed to create an inotify watcher","pos":"cert-manager.go:105","reason":"too many open files","timestamp":"2023-06-22T09:58:24.284130Z"}
    ```
    We should document that adjusting inotify might be required for this to work
* uBlock Origin is blocking `nip.io`, you need to disable it to be able to use the KKP dashboard. We might want to mention that disabling adblocker might be required because of `nip.io`

**Comment by wozniakjan** [comment]
> We should document that adjusting inotify might be required for this to work

> uBlock Origin is blocking nip.io, you need to disable it to be able to use the KKP dashboard. We might want to mention that disabling adblocker might be required because of nip.io

this is really good information, do you think it will be sufficient to explain these two just in docs? I'm hesitant to make it part of the command output for verbosity reasons.

> We should also print credentials for logging in to the KKP dashboard, as it's currently unclear what credentials should be used

good point, I will try to add a helpful message to include this

> The nginx-ingress-controller is up and running however. I think we should hide this warning if it's not important for this setup

I think we can skip the entire DNS check for `local`, will try to propose that asap

**Comment by xmudrii** [comment]
> this is really good information, do you think it will be sufficient to explain these two just in docs? I'm hesitant to make it part of the command output for verbosity reasons.

I don't have strong opinions, so whatever feels better to you. However, I think we should also check if all KubeVirt pods are running before finishing with the command. In case there's something wrong, we can report it to the user and tell them to check logs.

**Comment by xmudrii** [comment]
I had to do two things to fix the issue with virt-handler (https://github.com/kubermatic/kubermatic/issues/12340#issuecomment-1602368805):

```
sudo sysctl -w fs.inotify.max_user_watches=524288
sudo sysctl -w fs.inotify.max_user_instances=256
```

Values were picked randomly, some adjusting might be useful. I'd just point out that running only one command can result in a state where virt-handler is running and healthy, but logging a lot of errors. Creating the cluster would succeed, but all VMs will be unschedulable. Hence it's important to run both commands.

We should also have some instructions on tearing down the setup. What I did is delete the user cluster and then run `kind delete cluster -n kkp-cluster` but I'm not sure if that's suitable.

**Comment by wozniakjan** [comment]
> I had to do two things to fix the issue with virt-handler https://github.com/kubermatic/kubermatic/issues/12340#issuecomment-1602368805:

perfect, I think it makes sense to put this to the new docs section regarding the `local` command.

> What I did is delete the user cluster and then run `kind delete cluster -n kkp-cluster`

for sure will add to the docs and perhaps also the command output, I have been doing the same so I think it's a good teardown.

**Comment by xmudrii** [comment]
I'm running into the following problem two times in a row:

```
INFO[0000] Creating kind cluster ...
INFO[0034] Kind cluster ready, continuing configuration ...
INFO[0034] Installing KubeVirt ...
INFO[0038] Installing KKP at 192.168.1.167.nip.io ...
INFO[0038]    💾 Deploying kubermatic-fast StorageClass…
INFO[0038]    ✅ StorageClass exists, nothing to do.
INFO[0038]    📦 Deploying nginx-ingress-controller…
INFO[0038]       Deploying Helm chart…
INFO[0077]    ✅ Success.
INFO[0077]    📦 Deploying cert-manager…
INFO[0077]       No CertificateIssuer configured in KubermaticConfiguration, skipping.
INFO[0077]    📦 Deploying Dex…
FATA[0079] Failed to deploy kubermatic stack: failed to deploy Dex: failed to deploy Helm release: failed to install: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/marko/Downloads/examples/kube-config.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/marko/Downloads/examples/kube-config.yaml
W0623 11:36:41.388171   31781 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
Error: release oauth failed, and has been uninstalled due to atomic being set: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://nginx-ingress-controller-admission.nginx-ingress-controller.svc:443/networking/v1/ingresses?timeout=10s": read tcp 172.18.0.3:48572->10.96.30.124:443: read: connection reset by peer
```

nginx-ingress pods become available shortly after that failure (see restarts and age):

```
NAME                                        READY   STATUS    RESTARTS      AGE
nginx-ingress-controller-6987bd7c9b-cznxk   1/1     Running   1 (25s ago)   48s
nginx-ingress-controller-6987bd7c9b-tjz6r   1/1     Running   0             48s
nginx-ingress-controller-6987bd7c9b-x485z   1/1     Running   1 (22s ago)   48s
```

However, I didn't found a way to proceed after that issue. I had to delete the kind cluster, start the command again, but then I run into the issue again.

**Comment by wozniakjan** [comment]
Thanks, that is fairly unexpected for me because the local installer uses the same resource defaults that are used for production-grade KKP setups. And the resource usage here should be minimal.

So far I haven't stumbled upon OOMKilled nginx ingress controller but its resource consumption is much higher than I would expect
```
$ ps aux | grep -v 'awk' | awk '/nginx-ingress-c/{print($2)}' | while read pid; do cat /proc/$pid/cgroup; done | cut -d ':' -f 3 | while read cg; do numfmt --to si "$(cat /sys/fs/cgroup/${cg}/memory.peak)"; done

421M
421M
419M
419M
418M
418M
```

I will make a proposal to override these limits just for the local installer.

**Comment by xmudrii** [comment]
The KubeVirt user cluster is coming up successfully, but `logs` and `exec` are not operational.

```
I0623 12:25:14.081926  119728 loader.go:373] Config loaded from file:  kubeconfig-admin-o75ffmzqfr
I0623 12:25:14.085436  119728 round_trippers.go:463] GET https://o75ffmzqfr.kubermatic.192.168.1.167.nip.io:6443/api/v1/namespaces/default/pods/nginx
I0623 12:25:14.085451  119728 round_trippers.go:469] Request Headers:
I0623 12:25:14.085462  119728 round_trippers.go:473]     Accept: application/json, */*
I0623 12:25:14.085472  119728 round_trippers.go:473]     User-Agent: kubectl/v1.27.1 (linux/amd64) kubernetes/4c94112
I0623 12:25:14.085482  119728 round_trippers.go:473]     Authorization: Bearer <masked>
I0623 12:25:14.116957  119728 round_trippers.go:574] Response Status: 200 OK in 31 milliseconds
I0623 12:25:14.119176  119728 round_trippers.go:463] GET https://o75ffmzqfr.kubermatic.192.168.1.167.nip.io:6443/api/v1/namespaces/default/pods/nginx/log?container=nginx
I0623 12:25:14.119187  119728 round_trippers.go:469] Request Headers:
I0623 12:25:14.119198  119728 round_trippers.go:473]     Authorization: Bearer <masked>
I0623 12:25:14.119208  119728 round_trippers.go:473]     Accept: application/json, */*
I0623 12:25:14.119217  119728 round_trippers.go:473]     User-Agent: kubectl/v1.27.1 (linux/amd64) kubernetes/4c94112
I0623 12:25:16.834644  119728 round_trippers.go:574] Response Status: 500 Internal Server Error in 2715 milliseconds
I0623 12:25:16.834961  119728 helpers.go:246] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Get \"https://10.244.1.66:10250/containerLogs/default/nginx/nginx\": dial tcp 10.244.1.66:10250: connect: no route to host",
  "code": 500
}]
Error from server: Get "https://10.244.1.66:10250/containerLogs/default/nginx/nginx": dial tcp 10.244.1.66:10250: connect: no route to host
```

**Comment by wozniakjan** [comment]
another very good find! That might mean I have missed some port mapping between kind and host, let me take a closer look at this.

**Comment by wozniakjan** [comment]
The kube-apiserver should be exposed via nodeport, so that would be this URL which seems to resolve just fine
```
https://o75ffmzqfr.kubermatic.192.168.1.167.nip.io:6443/api/v1/namespaces/default/pods/nginx/log?container=nginx
```
but then it fails with fetching the logs from kubelet
```
"https://10.244.1.66:10250/containerLogs/default/nginx/nginx": dial tcp 10.244.1.66:10250: connect: no route to host
```
do you know if kubelet was running and operational? And what was the CNI that you picked? I tried the latest cilium as well as the latest canal and it looks operational.

**Comment by xmudrii** [comment]
> do you know if kubelet was running and operational? And what was the CNI that you picked? I tried the latest cilium as well as the latest canal and it looks operational.

Node objects were reporting status Ready, so yes, Kubelet was operational. I was also able to schedule pods, but not to exec or get logs. I was using default values, so I assume it was Canal CNI.

**Comment by xmudrii** [comment]
@wozniakjan Let's wait for rc.0 that's planned for today and then I'll try to test this again. If I run into issues again, we can debug those issues together.

**Comment by wozniakjan** [comment]
@xmudrii I finally managed to reproduce this, I needed at least two node user-cluster, here is what I found so far. I have a single deployment and one pod works ok while the other doesn't. They are on different KubeVirt virtual nodes:
```
$ k get po -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP             NODE                                    NOMINATED NODE   READINESS GATES
test-76fd457b86-bsbp4   1/1     Running   0          11m   172.26.1.19    condescending-golick-84855f5b86-c8685   <none>           <none>
test-76fd457b86-xcg4v   1/1     Running   0          11m   172.26.0.167   condescending-golick-84855f5b86-cpn8q   <none>           <none>
```
operational:
```
$ k logs test-76fd457b86-xcg4v -v9
...
I0626 16:17:19.744894  224510 round_trippers.go:553] GET https://dwh2v6hjkn.kubermatic.10.0.0.12.nip.io:6443/api/v1/namespaces/default/pods/test-76fd457b86-xcg4v/log?container=ubuntu 200 OK in 6 milliseconds
```
broken:
```
$ k logs test-76fd457b86-bsbp4 -v9
...
I0626 16:17:47.505009  224786 round_trippers.go:553] GET https://dwh2v6hjkn.kubermatic.10.0.0.12.nip.io:6443/api/v1/namespaces/default/pods/test-76fd457b86-bsbp4/log?container=ubuntu 500 Internal Server Error in 3066 milliseconds
...
  "message": "Get \"https://10.244.1.65:10250/containerLogs/default/test-76fd457b86-bsbp4/ubuntu\": dial tcp 10.244.1.65:10250: connect: no route to host",
```

**Comment by wozniakjan** [comment]
imho it's expected to be "rough around the edges", I wouldn't block the release
