### ISSUE TITLE
OpenStack cluster provisoning and upgrading - Test Release 2.23

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12354]
```[tasklist]
### Supported Operating Systems
- [x] Ubuntu
- [x] CentOS 7
- [x] Flatcar
- [x] RHEL
- [x] Rocky Linux
```

```[tasklist]
### Supported Kubernetes Versions (use latest patch releases available)
- [x] v1.24
- [x] v1.25
- [x] v1.26
- [x] v1.27
```

```[tasklist]
### Upgrades
- [x] Upgrade from v1.24.x -> v1.25.x
- [x] Upgrade from v1.25.x -> v1.26.x
- [x] Upgrade from v1.26.x -> v1.27.x
```

## General Instructions

The instructions below are meant as general guidelines, but please be creative and explore any areas or procedures you consider to be interesting outside of the given instructions.

A script has been written that automates most of this over in the infra repo: [conformance-tester.sh](https://github.com/kubermatic/infra/blob/main/clusters/kkp-qa-env/conformance-tester.sh). Some manual testing via the dashboard is highly appreciated though, since that is the main way of interacting for our users.

- Create a Kubernetes cluster running on the **2.23 QA environment**
  - Keep default settings
- Wait for the cluster to be ready, then download the kubeconfig for it
- Ensure that all nodes are ready by running kubectl get nodes
- Ensure that basic operations work
  - Create a Deployment, try exposing it using NodePort Service, and make sure you can reach it
  - Make sure access to Pods via node proxying works, e.g. by fetching Pod logs via `kubectl logs` or opening an interactive shell via `kubectl exec`
  - If external CCM is deployed (you can find out by checking feature flags on the `Cluster` object), ensure that:
    - Node object has proper IP addresses (`kubectl get nodes -o wide`)
    - Each node has providerID set (`kubectl describe node <node-name> | grep -i providerid`)
    - If supported, create a LoadBalancer Service and make sure it's reachable
    - If supported, create a PersistentVolume and mount it in a pod
- **Upgrade the cluster to the latest Kubernetes release (1.27.x)**, wait for the upgrade to complete.
- Upgrade all machine deployments, so they match the control plane version.
- Wait for all Machines to get rolled out
- Ensure that all nodes are ready by running `kubectl get nodes`
- Ensure that all resources created earlier are still functioning
- Try recreating some of the resources created earlier

**Comment by xrstf** [comment]
```
========================== RESULT ===========================
Parameters:
  KKP Version............: v2.23.0-beta.1 (EE)
  Name Prefix............: "groucho"
  OSM Enabled............: true
  Dualstack Enabled......: false
  Konnectivity Enabled...: true
  Cluster Updates Enabled: false
  Enabled Tests..........: [gcr-images loadbalancer metrics securitycontext storage usercluster-gcr-images usercluster-rbac usercluster-seccomp]
  Scenario Options.......: []

Test results:
[ OK ] - openstack-centos-containerd-1.24.13 (9m53s)
[ OK ] - openstack-centos-containerd-1.25.9 (12m22s)
[ OK ] - openstack-centos-containerd-1.26.4 (7m22s)
[ OK ] - openstack-centos-containerd-1.27.1 (8m12s)
[ OK ] - openstack-flatcar-containerd-1.24.13 (8m21s)
[ OK ] - openstack-flatcar-containerd-1.25.9 (7m50s)
[FAIL] - openstack-flatcar-containerd-1.26.4 (26m36s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-5f9w4-64f8ff8df9-dcmfp e2e-5f9w4-64f8ff8df9-n9ctb e2e-5f9w4-64f8ff8df9-vvmbs]
[FAIL] - openstack-flatcar-containerd-1.27.1 (26m31s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-5thdx-6d668ccd4c-4p2tx e2e-5thdx-6d668ccd4c-zdg8h e2e-5thdx-6d668ccd4c-zrdph]
[FAIL] - openstack-rhel-containerd-1.24.13 (28m13s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-zzrjm-7cb9567dd-d7dt4 e2e-zzrjm-7cb9567dd-rbmjq e2e-zzrjm-7cb9567dd-s5hgp]
[FAIL] - openstack-rhel-containerd-1.25.9 (26m17s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-dqmhw-5cf9f8c489-c5xq7 e2e-dqmhw-5cf9f8c489-k7j46 e2e-dqmhw-5cf9f8c489-zj5qh]
[FAIL] - openstack-rhel-containerd-1.26.4 (27m51s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-82jsp-6fc4bd8b78-bwqdg e2e-82jsp-6fc4bd8b78-dqd9l e2e-82jsp-6fc4bd8b78-j6thp]
[FAIL] - openstack-rhel-containerd-1.27.1 (27m30s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-bvnvf-7dbd5775b-fpzm9 e2e-bvnvf-7dbd5775b-qnzkl e2e-bvnvf-7dbd5775b-rmnj8]
[ OK ] - openstack-rockylinux-containerd-1.24.13 (10m19s)
[ OK ] - openstack-rockylinux-containerd-1.25.9 (7m42s)
[ OK ] - openstack-rockylinux-containerd-1.26.4 (8m22s)
[ OK ] - openstack-rockylinux-containerd-1.27.1 (8m53s)
[ OK ] - openstack-ubuntu-containerd-1.24.13 (9m55s)
[ OK ] - openstack-ubuntu-containerd-1.25.9 (11m3s)
[ OK ] - openstack-ubuntu-containerd-1.26.4 (10m38s)
[ OK ] - openstack-ubuntu-containerd-1.27.1 (8m46s)
```
