### ISSUE TITLE
vSphere cluster provisioning and upgrading - Test Release 2.23

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12356]
```[tasklist]
### Supported Operating Systems
- [x] Ubuntu
- [x] CentOS 7
- [x] Flatcar
- [x] RHEL
- [x] Rocky Linux
```

```[tasklist]
### Supported Kubernetes Versions (use latest patch releases available)
- [x] v1.24
- [x] v1.25
- [x] v1.26
- [x] v1.27
```

```[tasklist]
### Upgrades
- [x] Upgrade from v1.24.x -> v1.25.x
- [x] Upgrade from v1.25.x -> v1.26.x
- [x] Upgrade from v1.26.x -> v1.27.x
```

## General Instructions

The instructions below are meant as general guidelines, but please be creative and explore any areas or procedures you consider to be interesting outside of the given instructions.

A script has been written that automates most of this over in the infra repo: [conformance-tester.sh](https://github.com/kubermatic/infra/blob/main/clusters/kkp-qa-env/conformance-tester.sh). Some manual testing via the dashboard is highly appreciated though, since that is the main way of interacting for our users.

- Create a Kubernetes cluster running on the **2.23 QA environment**
  - Keep default settings
- Wait for the cluster to be ready, then download the kubeconfig for it
- Ensure that all nodes are ready by running kubectl get nodes
- Ensure that basic operations work
  - Create a Deployment, try exposing it using NodePort Service, and make sure you can reach it
  - Make sure access to Pods via node proxying works, e.g. by fetching Pod logs via `kubectl logs` or opening an interactive shell via `kubectl exec`
  - If external CCM is deployed (you can find out by checking feature flags on the `Cluster` object), ensure that:
    - Node object has proper IP addresses (`kubectl get nodes -o wide`)
    - Each node has providerID set (`kubectl describe node <node-name> | grep -i providerid`)
    - If supported, create a LoadBalancer Service and make sure it's reachable
    - If supported, create a PersistentVolume and mount it in a pod
- **Upgrade the cluster to the latest Kubernetes release (1.27.x)**, wait for the upgrade to complete.
- Upgrade all machine deployments, so they match the control plane version.
- Wait for all Machines to get rolled out
- Ensure that all nodes are ready by running `kubectl get nodes`
- Ensure that all resources created earlier are still functioning
- Try recreating some of the resources created earlier

**Comment by xrstf** [comment]
```
========================== RESULT ===========================
Parameters:
  KKP Version............: v2.23.0-beta.1 (EE)
  Name Prefix............: "groucho"
  OSM Enabled............: true
  Dualstack Enabled......: false
  Konnectivity Enabled...: true
  Cluster Updates Enabled: false
  Enabled Tests..........: [gcr-images loadbalancer metrics securitycontext storage usercluster-gcr-images usercluster-rbac usercluster-seccomp]
  Scenario Options.......: []

Test results:
[ OK ] - vsphere-centos-containerd-1.24.13 (16m54s)
[ OK ] - vsphere-centos-containerd-1.25.9 (22m3s)
[ OK ] - vsphere-centos-containerd-1.26.4 (22m15s)
[ OK ] - vsphere-centos-containerd-1.27.1 (16m15s)
[ OK ] - vsphere-flatcar-containerd-1.24.13 (13m28s)
[ OK ] - vsphere-flatcar-containerd-1.25.9 (13m10s)
[FAIL] - vsphere-flatcar-containerd-1.26.4 (27m28s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-kxn4n-7b986f6dfb-cd6pk e2e-kxn4n-7b986f6dfb-cdbg2 e2e-kxn4n-7b986f6dfb-pjsss]
[FAIL] - vsphere-flatcar-containerd-1.27.1 (26m13s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-zl4hp-5699846d47-gtgvs e2e-zl4hp-5699846d47-h8gsj e2e-zl4hp-5699846d47-xpsl2]
[FAIL] - vsphere-rhel-containerd-1.24.13 (27m30s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-8gt7n-64675bf546-2s45b e2e-8gt7n-64675bf546-9n2sw e2e-8gt7n-64675bf546-9rdws]
[FAIL] - vsphere-rhel-containerd-1.25.9 (26m19s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-8q5rz-6f98cd4455-4hg5k e2e-8q5rz-6f98cd4455-6gmz9 e2e-8q5rz-6f98cd4455-t58db]
[FAIL] - vsphere-rhel-containerd-1.26.4 (26m14s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-xkt92-fbb4687bb-4fwrm e2e-xkt92-fbb4687bb-7ddwd e2e-xkt92-fbb4687bb-sn74f]
[FAIL] - vsphere-rhel-containerd-1.27.1 (27m53s): failed to wait for machines to get a node: timed out waiting for the condition; last error was: not all machines have joined: [e2e-jn2l4-58fb67b5b4-2fk2j e2e-jn2l4-58fb67b5b4-m8t7s e2e-jn2l4-58fb67b5b4-rvk8g]
[ OK ] - vsphere-rockylinux-containerd-1.24.13 (14m43s)
[ OK ] - vsphere-rockylinux-containerd-1.25.9 (17m36s)
[ OK ] - vsphere-rockylinux-containerd-1.26.4 (15m20s)
[ OK ] - vsphere-rockylinux-containerd-1.27.1 (15m34s)
[ OK ] - vsphere-ubuntu-containerd-1.24.13 (20m27s)
[FAIL] - vsphere-ubuntu-containerd-1.25.9 (27m19s): failed to wait for all nodes to be ready: timed out waiting for the condition; last error was: not all nodes are ready: [e2e-5fv5d-69b696898f-pd8d4]
[ OK ] - vsphere-ubuntu-containerd-1.26.4 (15m26s)
[ OK ] - vsphere-ubuntu-containerd-1.27.1 (23m31s)
```

**Comment by xrstf** [comment]
Tests are blocked by

>   Warning  Failed     86s                    kubelet            Failed to pull image "docker.io/flannelcni/flannel:v0.16.3": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/flannelcni/flannel:v0.16.3": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/flannelcni/flannel/manifests/sha256:43d277bbb9fc2d6144c3d4bfa1d98affa3e3ad67f59eeedccb428979c6a25b1f: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

It's essentially random if and when a cluster comes up and can be upgraded.
