### ISSUE TITLE
Use secure apiserver port within seed-cluster

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1236]
**Current state**
All master components talking to the Apiserver currently use the insecure port. This port does not require authentication neither does it authorization. Also the communication happens via http and not https.
The components talking to the Apiserver via the insecure port:
- Scheduler
- Controller-Manager
- Machine-controller

**Desired state**
All above listed components should:
- Use HTTPS
- Use a dedicated kubeconfig with limited permissions
- Talk to the Apiserver service. Either via ClusterIP or DNS

The Apiserver TLS certificate might need to be updated to always include the service name & cluster-IP.

**Comment by mrIncompetent** [comment]
To create a kubeconfig with limited permissions see https://github.com/kubermatic/kubermatic-installer/blob/master/container-linux-config-generator/parse_template.go#L103

**Comment by thz** [comment]
I would go for querying clusterIP and making sure the IP is in SANs...

**Comment by mrIncompetent** [comment]
> I would go for querying clusterIP and making sure the IP is in SANs...

:+1: 
We already have logic in place which takes care of regenerating the certs if the SAN's somehow change. So we should not have to worry about backwards-compatibility

**Comment by thz** [comment]
To clarify the "limited permission" part of the desired state:
From the 3 mentioned master components 2 already have matching clusterroles: (`system:kube-scheduler` and `system:kube-controller-manager`). `machine-controller` does not seem to have a matching clusterrole.

Please confirm:

- `system:kube-scheduler` clusterrole shall be used from `scheduler` to access `apiserver`
- `system:kube-controller-manager` shall be used from `controller-manager` to access `apiserver`
- For `machine-controller` a new clusterrole needs to be established and used.

( paging @mrIncompetent )

**Comment by mrIncompetent** [comment]
sgtm

**Comment by thz** [comment]
Actually using ClusterRoles sounds incorrect to me now. 
As the master components run in the seed cluster within the specific cluster-namespace, using cluster roles would break out of that cluster-namespace and render the authorization way to permissive. Authentication would still limit access because apiservers have distinct CAs and the master-components can only talk to the correct apiserver instance.

The only benefit from using cluster roles would be reduced complexity.

Does that make sense?
