### ISSUE TITLE
Allow `mirror-images` to create a bundle of images to import in air-gapped scenario

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12368]
### Description of the feature you would like to add / User story

As a KKP implementer in an air-gapped environment
I would like to generate a bundle of all images with `kubermatic-installer mirror-images`
in order to put one single file on an USB thumb drive that I can extract to a registry within the air-gapped environment.

### Solution details

- `kubermatic-installer mirror-images` gains a flag where it writes images to a local file archive instead of a remote registry
- the output of this is a single file so it can easily be moved between environments
- `kubermatic-installer mirror-images` gains a flag where it reads images from a local file archive instead of the upstream registries

### Use cases

Air-gapped environments that do not have access to upstream registries on the internet and do not have a network zone that has access to both the internet and the local registry mirrors (or access to that zone is restricted) to run `kubermatic-installer mirror-images` directly.

**Comment by embik** [comment]
@hc2p I know you are doing a lot of work when it comes to air-gapped setups, do you think this is a valuable feature addition for the air-gapped use case?

**Comment by hc2p** [comment]
Not sure I fully understand the scenario here:
* Would the airgapped environment have a dedicated (offline) registry? Then the question would be which service (JFrog, Harbor..) do you envision. Also if there is a standard package format to exchange bundles.
* or do you want to circumvent this by doing `docker load` from the produced image-tar on all the machines, thus not needing a registry?
* Beyond containers, where would you serve binaries from? What usually gets provisioned on new machines is a mix of apt-get installs and `curl github.com`.

Just thinking out loud: maybe `kubermatic-installer` could serve as a simple registry/file server/pull-through cache available through the ssh-connection?

**Comment by embik** [comment]
> Would the airgapped environment have a dedicated (offline) registry? Then the question would be which service (JFrog, Harbor..) do you envision. Also if there is a standard package format to exchange bundles.

Yes, the assumption is there would be a dedicated registry. IMHO (feel free to correct me here) air-gapped setups without an image source are not really usable. I would not impose any specific service here and just rely on standards like OCI registry pushing to extract the bundle, so it should work against any image registry.

> Also, how was the cluster provisioned in the first place? Bringing up K8s air-gapped means you need to serve not only OCI but binaries, which usually get downloaded from e.g. GitHub and apt-get repos.

This is a very valid point, but I would argue they are out-of-scope for this. Binaries you could "easily" embed into VM images so you don't need them to be downloaded (and you provide a custom OSP that assumes all binaries are there and verifies them). I'm not saying this is the best way, but I think they would need a different mechanism anyway (since I'm not aware of a generic way to "push" packages to an in-house apt repository or something).

**Comment by embik** [comment]
For context maybe: This feature (as described in the issue description) was requested/proposed by a Kubermatic partner. Their scenario is that there is an internal registry, but that registry doesn't have Internet access. In addition, the registry is operated by a part of the organisation that is not primarily running the registry for KKP. Having a namespace and a user on that registry to push images to it would be easy, and in many of these scenarios bringing an USB stick on-site would be the easiest solution.

I'm sure there are ways to do this, the idea behind this is to extend an already existing feature in a way that covers another set of scenarios. Most customers _can_ come up with something else, but they are looking to our features for an integrated solution that saves them time.

> Can you elaborate on this part of your solution design?

`kubermatic-installer mirror-images -s ./image-archive.tar.gz my-personal-registry.com/kkp` would - instead of pulling images from an upstream registry and then mirroring it directly to the target registry (as that is `kubermatic-installer mirror-images` current functionality) - extract the image archive and push the images to the target registry directly.

**Comment by hc2p** [comment]
Within this context, it definitely sounds like a viable solution. 

But I'm still wondering how they are transporting the non-KKP images to this registry. That might be out of scope for this feature. Just trying to see the whole picture.

**Comment by embik** [comment]
Good question, let me try to figure that out.
