### ISSUE TITLE
KubeVirt node remediation - Test Release 2.23

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#12379]
**Instruction** (related PR https://github.com/kubermatic/machine-controller/pull/1645)

1. Create a KubeVirt cluster with one machine (VM)
1.1 User `rook-ceph` storage class
3. Wait for VM to be ready
3.1 Check if user cluster node is in `Ready`  state
4. Deploy test workload to the user cluster (could be nginx or something)
5. Delete the corresponding virt-launcher pod of VM on the KubeVirt infra cluster
6. Wait for VM to be recreated 
6.1 Name of the VM should stay the same
6.2 VM IP address should be different
6.3 Node object of user cluster should be initialized again
6.4 Wait for node to become `Ready` 
7. Confirm that the test workload is up and running

**Comment by cnvergence** [comment]
confirmed, VM was successfully recreated:
pre-remediation:
```bash
NAME                       STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
test-vm-69b94874fd-57v8f   Ready    <none>   6m15s   v1.26.4   10.244.2.153   <none>        Ubuntu 20.04.3 LTS   5.4.0-88-generic   containerd://1.6.21
```
post-remediation:
```bash
NAME                       STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
test-vm-69b94874fd-57v8f   Ready    <none>   6m29s   v1.26.4   10.244.2.155   <none>        Ubuntu 20.04.3 LTS   5.4.0-88-generic   containerd://1.6.21
```
Deployed workload was accessible again
