### ISSUE TITLE
Define non-continuous IP ranges in IPAM

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#12382]
### Description of the feature you would like to add / User story

As an KKP admin I want to define a list of non continous IP ranges to configure the IPAM pool.

### Solution details

- Allow range with gaps

### Use cases

Some IP addresses in a range or subnet might be in use by other application.

### Additional information

This can be done via https://docs.kubermatic.com/kubermatic/v2.22/tutorials-howtos/networking/ipam/#exclusions

**Comment by csengerszabo** [comment]
The original use case from #12258 :

> The IPAMPool allows us to define only one continuous range of pool cidr, but the desired range might not be continuous all the time, the IPAMPool should allow specifying non-continuous ranges.

The use case itself can be covered with the exclusions and creating gaps in the defined ranges described in the docs: https://docs.kubermatic.com/kubermatic/v2.22/tutorials-howtos/networking/ipam/#exclusions

At the same time, it's not the most optimal solution, since for certain use cases the opposite is the easier, which is putting certain IP addresses into an address pool.

Based on these facts, let's make this issue the lowest priority one for now from the #12258 epic.

CC: @akash-gautam

**Comment by toschneck** [comment]
In my opinion this feature is given, but lets clarify first the whole scope

**Comment by csengerszabo** [comment]
The functionality already can be achieved.

**Comment by csengerszabo** [comment]
The functionality already can be achieved.
