### ISSUE TITLE
VMware Cloud Director cluster broken after KKP 2.22 -> 2.23 upgrade

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12401]
### What happened?

While testing for #12111, I ran into the following issue:

I created a VMware Cloud Director user cluster on KKP 2.22.4 (on my QA upgrade environment) with Kubernetes v1.25.11. I used a preset that contained username and password as authentication mechanism for creating the cluster.

After upgrading to KKP 2.23.0-beta.2, the cluster did fully finish it's rolling update for all control plane components:

```
machine-controller-5b8d545b75-zfv6s                 0/1     CreateContainerConfigError   0             22m
machine-controller-webhook-6fcf559c8b-b6t2l         0/1     CreateContainerConfigError   0             22m
usercluster-controller-59bc685856-9qbcd             0/1     CreateContainerConfigError   0             12m
usercluster-webhook-7b7449f7fc-9zq95                0/1     CreateContainerConfigError   0             22m
```

All of them fail for the same reason:

```
 Warning  Failed     21m (x10 over 22m)    kubelet            Error: couldn't find key apiToken in Secret cluster-rrb759kt6f/cloud-credentials
```

It appears that the apiToken field is not optional, but older VMware Cloud Director clusters do not have it. As far as I understand the process, once the credentials are transferred into a cloud-credentials Secret upon cluster creation, KKP does not update them - So the addition of this field in KKP 2.23 never reached cloud-credentials previously created.

### Expected behavior

KKP 2.23 successfully handles VMware Cloud Director user clusters created in KKP 2.22.

### How to reproduce the issue?

See description above. The gist is:

1. Set up KKP 2.22.4
2. Create VMware Cloud Director user cluster
3. Upgrade to KKP 2.23.0-beta.2
4. Observe control plan components failing

### How is your environment configured?

- KKP version: v2.23.0-beta.2
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

VMware Cloud Director

### What operating system are you running in your user cluster?

n/a

**Comment by embik** [comment]
@ahmedwaleedmalik do you think we can make the mount for apiToken optional, so MC and OSM start without the env variable?

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik do you think we can make the mount for apiToken optional, so MC and OSM start without the env variable?

Is that causing some issue?

**Comment by ahmedwaleedmalik** [comment]
I'll check hopefully tomorrow or on Friday.
