### ISSUE TITLE
Disable DNS check for the installer local command 

### ISSUE THREAD

**Issue by wozniakjan** [kubermatic/kubermatic#12407]
### Description of the feature you would like to add / User story

As a KKP user, I would like to not observe unnecessary warnings in `kubermatic-installer local kind` command  

### Solution details

The `kubermatic-installer local kind` command calls master / seed installation, which does a DNS check. This check is not required for the local installation and creates unnecessary warnings and delays for the installation. It is desired to be able to disable the DNS check for the local command.

### Additional information

This is an excerpt from the installation logs
```
$ ./kubermatic-installer local kind
...
INFO[0175]    📦 Deploying Telemetry
INFO[0177]    ✅ Success.
INFO[0177]    📡 Determining DNS settings…
WARN[0357]       Timed out waiting for the LoadBalancer service "nginx-ingress-controller/nginx-ingress-controller" to become ready.
WARN[0357]       Please check the Service and, if necessary, reconfigure the
WARN[0357]       nginx-ingress-controller Helm chart. Re-run the installer to apply
WARN[0357]       updated configuration afterwards.
INFO[0357]
INFO[0357] KKP installed successfully, login at http://10.0.0.12.nip.io
...
```
Skipping the DNS check would save time and not print false warnings, however, neither of the current options available do just that:
https://github.com/kubermatic/kubermatic/blob/2348fd176ca7ee4f3892006cc19db229c2bf55c1/pkg/install/stack/kubermatic-master/stack.go#L353-L377
* headless installation - this would skip KKP dashboard, but `local` command wants dashboard
* ingress disablement - would make the routing and the `kind` exposed port handling harder

**Comment by dvob** [comment]
Please also consider skipping the check if the installation of the ingress controller got skipped with the option `--skip-charts nginx-ingress-controller`.
