### ISSUE TITLE
CSIDriver `csi.hetzner.cloud` is invalid: spec.fsGroupPolicy - field is immutable

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12429]
### What happened?

We discovered during upgrading an internal KKP installation that the Hetzner CSI addon fails to apply:

```json
{"level":"error","time":"2023-06-30T07:33:53.825Z","caller":"controller/controller.go:274","msg":"Reconciler error","controller":"kkp-addon-controller","object":{"name":"csi","namespace":"cluster-jlp86llkdl"},"namespace":"cluster-jlp86llkdl","name":"csi","reconcileID":"a99cc40b-aef0-4c84-9ace-79e4a3218911","error":"failed to deploy the addon manifests into the cluster: failed to execute '/usr/local/bin/kubectl-1.26 --kubeconfig /tmp/cluster-jlp86llkdl-addon-csi-kubeconfig apply --prune --filename /tmp/cluster-jlp86llkdl-csi.yaml --selector kubermatic-addon=csi' for addon csi of cluster jlp86llkdl: exit status 1\nsecret/hcloud-csi unchanged\nserviceaccount/hcloud-csi unchanged\[nclusterrole.rbac.authorization.k8s.io/hcloud-csi](http://nclusterrole.rbac.authorization.k8s.io/hcloud-csi) unchanged\[nclusterrolebinding.rbac.authorization.k8s.io/hcloud-csi](http://nclusterrolebinding.rbac.authorization.k8s.io/hcloud-csi) unchanged\ndeployment.apps/hcloud-csi-controller created\ndaemonset.apps/hcloud-csi-node configured\nservice/hcloud-csi-controller-metrics unchanged\nservice/hcloud-csi-node-metrics unchanged\nThe CSIDriver \"csi.hetzner.cloud\" is invalid: spec.fsGroupPolicy: Invalid value: \"File\": field is immutable\n","errorCauses":[{"error":"failed to deploy the addon manifests into the cluster: failed to execute '/usr/local/bin/kubectl-1.26 --kubeconfig /tmp/cluster-jlp86llkdl-addon-csi-kubeconfig apply --prune --filename /tmp/cluster-jlp86llkdl-csi.yaml --selector kubermatic-addon=csi' for addon csi of cluster jlp86llkdl: exit status 1\nsecret/hcloud-csi unchanged\nserviceaccount/hcloud-csi unchanged\[nclusterrole.rbac.authorization.k8s.io/hcloud-csi](http://nclusterrole.rbac.authorization.k8s.io/hcloud-csi) unchanged\[nclusterrolebinding.rbac.authorization.k8s.io/hcloud-csi](http://nclusterrolebinding.rbac.authorization.k8s.io/hcloud-csi) unchanged\ndeployment.apps/hcloud-csi-controller created\ndaemonset.apps/hcloud-csi-node configured\nservice/hcloud-csi-controller-metrics unchanged\nservice/hcloud-csi-node-metrics unchanged\nThe CSIDriver \"csi.hetzner.cloud\" is invalid: spec.fsGroupPolicy: Invalid value: \"File\": field is immutable\n"}]}
```

The gist is that #12191 changed an immutable field on the `CSIDriver` resource for `csi.hetzner.cloud` and in KKP v2.23.0, the addon fails to apply.

### Expected behavior

The CSI addon can be applied/upgraded from KKP 2.22 to 2.23.

### How to reproduce the issue?

- Create Hetzner user cluster on KKP 2.22 with CCM/CSI enabled.
- Upgrade KKP setup to 2.23.0.
- Observe addon failures from seed-controller-manager logs.

### How is your environment configured?

- KKP version: v2.23.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Hetzner

### What operating system are you running in your user cluster?

N/A

### Additional information

A workaround for this is deleting the `csidriver` resource (`kubectl delete csidriver csi.hetzner.cloud`) and letting the addon-controller recreate it.

**Comment by wozniakjan** [comment]
the `CSIDriver.fsGroupPolicy` introduced in https://github.com/kubermatic/kubermatic/pull/11968 is indeed immutable but upstream proposes simple and supposedly safe mitigation with recreating the `CSIDriver` object 
https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1682-csi-driver-skip-permission#risks-and-mitigations
