### ISSUE TITLE
Wait for Client etcd to be ready before deploying kube-apiserver and kube-cluster-controller

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#125]
As we are using persistence for etcd volumes now it takes longer for them to be provisioned. As a result, the API Server and Cluster Controller continuously restart because they cannot reach etcd. 

We should wait to start the Kube API Server and Cluster Controller until the etcd pod we have created is ready.

**Comment by mrIncompetent** [comment]
This would mean a significant change in our code to fix this. Do we really want to tackle this?
Does it hurt in any way? Does it improve anything?
@chaosaffe

**Comment by mrIncompetent** [comment]
It does not hurt
