### ISSUE TITLE
Create vm folder for vSphere

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1250]
Each cluster should get its own vm folder on vSphere.
The creation of the folder should happen in the CloudProvider init phase of the controller.

Also:
The root-folder in which to create the cluster sub folders, should be configurable via flag on the controller-manager.

**Comment by pkavajin** [comment]
Folder currently gets passed using the cloudprovider config, isn't that already better than passing by flag to the controller manager?

**Comment by mrIncompetent** [comment]
The root folder needs to be specified on the kubermatic-controller-manager not the machine-controller.

We want that all clusters, created via kubermatic have the same root-folder for VM's.
Each cluster will get a dedicated subfolder which we then pass into the cloudprovider config of a machine

**Comment by mrIncompetent** [comment]
As discussed, the `root` folder should be configurable via the datacenters.yaml.
Within `api/pkg/provider/cloud/vsphere/provider.go:65` we have to create a cluster specific sub folder like `root/cluster-name`
And in `api/pkg/provider/cloud/vsphere/provider.go:70` we'll cleanup the folder
