### ISSUE TITLE
Vmware Cloud Director support for flatcar

### ISSUE THREAD

**Issue by 4ch3los** [kubermatic/kubermatic#12576]
### Description of the feature you would like to add / User story

As SVA, we would like to use flatcar as OS with Vmware Cloud Director. Currently only Ubuntu is supported, which comes with a lot of overhead, resulting in more maintenance work.

### Solution details

- A supported lightweight container oriented OS for VMware Cloud Director

### Alternative approaches

- As alternative, another lighweight container os would also be possible

**Comment by ahmedwaleedmalik** [comment]
Already complete
/close
