### ISSUE TITLE
Upgrade VPA to v0.14.0

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#12601]
### Description of the feature you would like to add / User story
VPA should be upgraded to v0.14.0 to support latest version of kubernetes. Currently, VPA implementation in KKP is v0.11.0

### Solution details
As mentioned in v0.12.0 [release notes](https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.12.0), older version will not work with newer k8s versions.

In our clusters right now recommender does not provide any recommendations. It is filled with below errors.
```
E0824 05:13:42.364062       1 reflector.go:178] k8s.io/autoscaler/vertical-pod-autoscaler/pkg/recommender/input/controller_fetcher/controller_fetcher.go:137: Failed to list *v1beta1.CronJob: the server could not find the requested resource
```
Upgrarding to latest version should solve the issue.

### Alternative approaches
NA

### Use cases

Vertical pod autoscaler works nicely.. but has stopped working after upgrade to k8s version 1.25 and above.

**Comment by embik** [comment]
Fixed in #12604.
