### ISSUE TITLE
Custom folder configuration for vSphere provider presets

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#12632]
### Description of the feature you would like to add / User story

As a KKP admin with clients as KKP users on vSphere
I want to be able to select a specific parent folder from a dropdown when configuring the vSphere provider preset
In order to organize customer clusters within different subfolders in vCenter for better organization and resource management

### Solution details

- When configuring a vSphere provider preset, there is a new option to select a custom parent folder for each customer
- Folders in the dropdown are preexisting, they had been created in vCenter
- When using the specific preset, User Cluster nodes are going to be created in this specified folder
- The fallback can the `roothPath` configured in the Seed

### Alternative approaches

- Having User clusters in the root folder defined on the Seed

### Use cases

- When having multiple customers who are using KKP for creating their clusters in vSphere, it's useful to organize their VMs into specific customer folders for organization, billing and resource management reasons

### Additional information

- When a cluster is created using this preset, KKP automatically creates the cluster-specific folder within the specified custom parent folder path. For example, if the custom parent folder is `/Place/Customers/XY/XY_k8s`, KKP should create a cluster-specific folder like `//Place/Customers/XY/XY_k8s/asd1234fd`.
- Each customer is assumed to have a vSphere Service Account, which has permissions to specific folders
- Billing to customers are based on their separate folders in VCenter
- Each customer is supposed to have a separate preset as well

### Questions

- How about migrating clusters that have already been created? Can it be automated or should it be done manually?

**Comment by csengerszabo** [comment]
Outcome of internal discussions:

- ability to enter / create new folder from this field in the preset creation has a significant complexity, and since it's not even needed, we will skip that from the implementation and only fetch existing folder
- Migration is not possible, even manually, since folders are immutable

**Comment by embik** [comment]
This has been implemented (see linked PRs).
