### ISSUE TITLE
Configurable webhook backend for audit logging for User Clusters 

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#12631]
### Description of the feature you would like to add / User story

As a KKP user
I want the ability to configure a webhook backend for audit logging of my User Cluster
in order to enhance security and compliance monitoring.

### Solution details

- In Edit cluster, there is a new option to configure an external webhook backend for audit logging
- When configuring the webhook backend, I can specify the following parameters:
  - Edit the config file `--audit-webhook-config-file`
  - Setting up retry mechanism `--audit-webhook-initial-backoff`
- KKP provides status information regarding the webhook integration to aid in troubleshooting and monitoring
- The feature is compatible with the `k8s_audit` source in Falco
- Possible to enable and disable

### Alternative approaches

- using file-based audit logging that can be shipped to a specific location

**Comment by embik** [comment]
- We need to look at tagging audit logs with the user cluster ID. Is this needed?
- Focus on the falco integration (installed on the seed?) working.
- Configure webhook backends on the `Seed` object and make them selectable per user cluster.
