### ISSUE TITLE
Option to disable CSI drivers - Test Release 2.24

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#12649]
__TBD__

Reference: https://github.com/kubermatic/kubermatic/issues/12008

**Comment by embik** [comment]
Notes:
- No documentation (https://github.com/kubermatic/kubermatic/issues/12008#issuecomment-1782841722).
- UI issue open (https://github.com/kubermatic/dashboard/issues/6206).
- When disabling the CSI driver on an existing cluster, you need to delete the `StorageClass` created by the `default-storage-class` addon, else the webhook will refuse it.

**Comment by embik** [comment]
It's possible to disable the CSI driver by deleting the `StorageClass` while PVCs and PVs using it still exist. SC deletion does not delete associated PVs. PVs and PVCs continue to exist but are dead in the water with the CSI driver removed.

**Comment by embik** [comment]
The feature could use some improvements, but fundamentally it works. Since it's not documented and not available in the UI, I suspect its usage will be low. Improvements can be done in future releases. Closing this.
