### ISSUE TITLE
Custom container limits for addons like kube-state-metrics

### ISSUE THREAD

**Issue by al-lac** [kubermatic/kubermatic#12689]
### Description of the feature you would like to add / User story

As a k8s administrator  
I would like to update the container limits of addons  
in order to not run into OOM Killed scenarios

### Solution details

In the [addons documentation](https://docs.kubermatic.com/kubermatic/v2.23/architecture/concept/kkp-concepts/addons/) i was not able to find a way to supply container limits to addons like kube-state-metrics. 

- Having the option to provide custom container cpu and memory limits for an addon
- Being able to update these values via the UI (optional) 

### Alternative approaches

Using an applicationdefinitions or a helm release.

### Use cases

Bigger clusters need a higher limit for certain pods, if this would be possible one could also use addons on bigger clusters without running into issues.

**Comment by embik** [comment]
Hi @al-lac, there is no way to dynamically override addons like that as far as I know. Two options are available from my perspective:

1. You open a PR with this repository to increase the default limits. If it's within a reasonable range we are happy to accept the change.
2. You [maintain a custom addon image](https://docs.kubermatic.com/kubermatic/v2.23/architecture/concept/kkp-concepts/addons/) that overrides the kube-state-metrics addon with your limits of choice.

**Comment by embik** [comment]
@al-lac checking out your PR and looking at the current limits - Can you please do me a favour and test behaviour in your environment if you bump the CPU limit to `1` (from `100m`) and leave the memory untouched? I've seen memory ballooning in the past because CPU was throttled severely, this might be the case here as well.

**Comment by al-lac** [comment]
Hey @embik, tried it out. Did not change anything, pod instantly gets OOMKilled.
