### ISSUE TITLE
vSphere: add basePath configuration options - Test Release 2.24

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12755]
This is the testing issue for #12668. It is about the new `basePath` field on `Cluster` and `Preset` objects (both in the vSphere cloud spec part).

The idea behind the field is the following: When using a preset to create user clusters, I want cluster folders to be created in a subfolder structure (e.g. one folder for each preset). Previously, we provided the `rootPath` option on seeds, but this was per seed/datacenter.

Example:
- I create a vSphere user cluster with preset `preset-1` with `basePath=/org/preset-1`, and I end up with the folder `/org/preset-1/cluster-xxxxxx` created by KKP in which my VMs get created.
- I create a vSphere user cluster with preset `preset-2` with `basePath=/org/preset-2`, and I end up with the folder `/org/preset-2/cluster-xxxxxx` created by KKP in which my VMs get created.

In addition, this feature supports relative paths for `basePath`. If it's a relative path and not an absolute one, the base path will be appended to the configured root path (from the seed/datacenter) to construct the final folder location.

Your mission, should you chose to accept it, is to test this feature, verify that it works as described and poke any potential holes you can find.

**Comment by xrstf** [comment]
Seems to work
