### ISSUE TITLE
Security group / firewall requirements for nodes.

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1277]
### context

I am currently looking in AWS security group provisioning. Plan is to make it more robust (read: idempotent) to unexpected disturbance.

### Situation

Currently the code tries to add 5 different rules to the created security group:

1. "Allow node-to-node communication" - matching src ip on vpc cidr ip addresses (all protocols).
2. "Allow SSH from everywhere" - allows tcp:22 from everywhere
3. "Allow kubelet 10250 from everywhere" - allows tcp:10250 from everywhere
4. "Allow UDP within the security group" - matches on: all ports in udp protocol
5. "Allow ICMP within the security group" - matches on: all icmp types

### Problem

- `1.` makes `4.` and `5.` obsolete as everything is allowed anyways.
- `4.` and `5.` are intended to limit access to the security group but they do not (no sg specified).
- `4.` and `5.` cause invalid AWS api calls because no CIDR or sg is specified

### Question

What are our exact requirements for communication between nodes?

Is the following complete?

1. Allow every inter-node communication.
2. Allow tcp 22 and 10250 from the outside.

**Comment by mrIncompetent** [comment]
> Is the following complete?
> 
> 1. Allow every inter-node communication.
> 2. Allow tcp 22 and 10250 from the outside.

Yes. Should work out.

**Comment by mrIncompetent** [comment]
@thz This issue can be considered as done?

**Comment by thz** [comment]
Indeed. The change landed in master already.
