### ISSUE TITLE
Test functionality of the Default Apps

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#12784]
Install the catalog in accordance with the steps described in #12782.

Afterwards verify for each of the Apps can successfully be rolled out into the cluster. Criteria for a successfully rollout:
* All Pods are running
* From KKP dashboard, under deployed user cluster > Applications tab, verify the deployed application appears healthy in status without any error.
* Basic sanity check for each of the applications to verify each of them are functional.

**Comment by embik** [comment]
Found #12820 which is not directly related to the app catalog itself and more a fault in the Application feature.

**Comment by embik** [comment]
Could not find any obvious issue with the applications in the app catalog themselves.
