### ISSUE TITLE
Default app catalogue creation fails if AppDefs already exist

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#12780]
### What happened?

When you re-run the installer (or have AppDefs) already in the cluster, the Appinstaller is going to fail.

### Expected behavior

It should be running idempotently and skip the installation if AppDefs already exist

### How to reproduce the issue?

Run the installer twice with default appcatalogue

**Comment by embik** [comment]
Note: this should likely use the reconciling framework.
