### ISSUE TITLE
Fixup kubermatic-installer repo

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1279]
The kubermatic-installer currently has some hiccups which we should fix:

* There should be a script which downloads helm if not present and inits it together with rbac permissions
* There should be a script which applys all charts in the correct order in the correct namespace with the correct name
* The ingress-nginx daemonset does not tolerate the masters no schedule taint
* A storage class is not part of the installer at all but one for kubermatic-fast must be present for cluster creation to work
* There are no templates for the various cloud configs
* The initcontainer in the v2.5 branch is broken if there are no crds to delete and prevents the cluster controller from coming up

**Comment by mrIncompetent** [comment]
The installer is gone. We will only offer helm charts and that's it.

**Comment by mrIncompetent** [comment]
> There should be a script which downloads helm if not present and inits it together with rbac permissions

No, helm is a prerequisite as we offer helm charts. Otherwise customers will expect this script to be backwards compatible, work on different architectures, etc. Won't happen.

> There should be a script which applys all charts in the correct order in the correct namespace with the correct name

Correct, there's a order to follow in the monitoring charts. Something we should document. But we won't maintain a script for this.


> The ingress-nginx daemonset does not tolerate the masters no schedule taint

And that's fine. We cannot expect every customer setup to have a separation between masters & workers.

> A storage class is not part of the installer at all but one for kubermatic-fast must be present for cluster creation to work

Correct, and that is documented. We need storage but we'll not add a chart/templating for this.

> There are no templates for the various cloud configs

Definitely something we should add.

> The initcontainer in the v2.5 branch is broken if there are no crds to delete and prevents the cluster controller from coming up

We should cherry pick https://github.com/kubermatic/kubermatic/pull/1186

**Comment by alvaroaleman** [comment]
> No, helm is a prerequisite as we offer helm charts. Otherwise customers will expect this script to be backwards compatible, work on different architectures, etc. Won't happen.

What exactly is the issue with having a minimal "Download helm and install it with rbac" script? I doubt this will create more expectations

> There should be a script which applys all charts in the correct order in the correct namespace with the correct name

Its not just an order, its also a required namespace. Whats the issue about having a simple script for this?

> > The ingress-nginx daemonset does not tolerate the masters no schedule taint

> And that's fine. We cannot expect every customer setup to have a separation between masters & workers.

I think you understood me wrong. The daemonset does not spawn pods on the kubeadm-generated masters because the pods do not have the toleration for the abovementioned taint.

**Comment by mrIncompetent** [comment]
> > No, helm is a prerequisite as we offer helm charts. Otherwise customers will expect this script to be backwards compatible, work on different architectures, etc. Won't happen.

> What exactly is the issue with having a minimal "Download helm and install it with rbac" script? I doubt this will create more expectations

Without the script -> no effort to maintain / write it.
A link to the helm documentation is enough.

> > There should be a script which applys all charts in the correct order in the correct namespace with the correct name

> Its not just an order, its also a required namespace. Whats the issue about having a simple script for this?

What requirement on the namespace do we have?


> > > The ingress-nginx daemonset does not tolerate the masters no schedule taint

> > And that's fine. We cannot expect every customer setup to have a separation between masters & workers.

> I think you understood me wrong. The daemonset does not spawn pods on the kubeadm-generated masters because the pods do not have the toleration for the abovementioned taint.

You're right, should be fixed!

**Comment by alvaroaleman** [comment]
> Without the script -> no effort to maintain / write it.
Helm docs to the rbac stuff were plain broken the last time I checked. Currently they are fixed again but this would be a five liner that just pulls the lastest stable version.

The background for me on wanting all of this scripted is testability, I do not only want the product to be tested but also the install routine. I do not think there is a sane way to test the contents of docs and I want a __verified__ source of truth.

> What requirement on the namespace do we have?

Off of the top of my mind, might not be everything: The certs must be in the default namespace as thats where nginx looks for it, cert-manager must be in the cert-manager namespace

**Comment by mrIncompetent** [comment]
> I do not think there is a sane way to test the contents of docs and I want a verified source of truth.
To mention what i wrote on slack:
The charts to install differs on the environment.
- Without LB -> No nodeport-proxy
- Offline -> No cert-manager / certs

Already this logic is something i don't want to have in a script. Though if you want to add a customer specific script into the secrets repo -> :+1: 

We'll document the steps for now & point to the helm documentation.

**Comment by mrIncompetent** [comment]
Ending the discussion with:
If we run into issues with the documentation approach -> We can re-evaluate the script-idea.

The init-container has already been fixed in the v2.5 branch:
https://github.com/kubermatic/kubermatic/commit/5e6f1af5d44fd75bb5f170f1028bad1535d51cc5
First release using it: `v2.5.21`

Examples for cloud-configs:
https://github.com/kubermatic/kubermatic/issues/1345

Flag to ignore master-toleration:
https://github.com/kubermatic/kubermatic/issues/1346
