### ISSUE TITLE
CSI driver can be disabled while PVs using it still exist

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12797]
### What happened?

As part of testing the feature to disable CSI drivers on existing clusters (#12649) I tried to disable the CSI driver via `disableCsiDriver` on the `Cluster` after creating a cluster. I ran into the following situation:

A webhook prohibits disabling the CSI driver if there is a `StorageClass` still referencing it, e.g. the one created by the `default-storage-class` Addon. Deleting the `StorageClass` allows to set `disableCsiDriver: true`.

I went through this, but unfortunately existing `PersistentVolumes` are not considered - StorageClasses do not have a direct association with PVS, at least not in the sense that deleting a SC means that associated PVs are cleaned up. This means that when I create `PersistentVolumeClaims` that reference a StorageClass, then delete the `StorageClass` later on in preparation of disabling the CSI driver, I still have PVs lying around. 

These PVs are dead in the water when `disableCsiDriver: true` is set since the CSI driver will be uninstalled. Pods trying to mount them will see errors like this one:

```
Warning  FailedAttachVolume  62s (x2 over 3m3s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-2a77fa80-cc64-40fb-9aba-4013ac7d6ac9" : timed out waiting for external-attacher of ebs.csi.aws.com CSI driver to attach volume vol-0d4e206c6f8509bbf
Warning  FailedMount         47s (x2 over 3m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage], failed to process volumes=[]: timed out waiting for the condition
```

### Expected behavior

The webhook blocking `disableCsiDriver: true` checks for `PersistentVolumes` referencing a specific `CSIDriver` instead of (or in addition to) `StorageClasses`.

### How to reproduce the issue?

1. Create user cluster on KKP for provider with CSI driver deployment (e.g. AWS).
2. Create `PersistentVolumeClaim` to dynamically create volume from default StorageClass.
3. Wait for `PersistentVolume` created dynamically.
4. Delete `StorageClass`.
5. Switch to seed cluster, `kubectl edit cluster <cluster ID>` and set `spec.disableCsiDriver: true`.
6. Observe CSI driver components being deleted.
7. Attempt to launch pod mounting the still existing PV(C). Observe it failing.

### How is your environment configured?

- KKP version: v2.24.0-beta.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

AWS, but applicable to all CSI-enabled providers

### What operating system are you running in your user cluster?

N/A

**Comment by embik** [comment]
@ahmedwaleedmalik @akash-gautam I would need some input on this from your side. I assume that the checks done for this feature should cover this scenario and refuse to disable the CSI driver?

**Comment by akash-gautam** [comment]
@embik I can include a check to ensure that any PVs are not using the CSI driver before disabling it, but deleting the storage class which is in use can still have other undesirable impacts on the cluster so if the cluster admin deletes the storage class and then disabling the CSI driver used by it then it is expected that they know what they are doing & in case of problems like these they can also enable it again (if it is not disabled at the data center level) or install the drivers manually.

**Comment by embik** [comment]
I'm okay with the "they should know what they are doing" approach, but then the feature has to be documented. So I would prioritise a PR to kubermatic/docs over "fixing" this issue.

> deleting the storage class which is in use can still have other undesirable impacts on the cluster

Can you expand on this?

**Comment by akash-gautam** [comment]
@embik Okay, I will try to get the docs PR out first & then work on this issue. 
Deleting the storage class which is in use can have undesirable impacts such as if any sts has the storage class specified in its volumeClaimTemplates scales then the PVC for the new pod will remain in a pending state with "storage class not found" error, and if the storage class is also the default for the cluster & any user deploys workload without specifying any storage class expecting the default to be picked then the pods, in this case, will also remain in pending state.

**Comment by akash-gautam** [comment]
WIP, /remove-lifecycle stale.

**Comment by ahmedwaleedmalik** [comment]
@akash-gautam can you please create a testing ticket for this?

**Comment by akash-gautam** [comment]
@ahmedwaleedmalik Added [this](https://github.com/kubermatic/kubermatic/issues/13014) ticket for testing.
