### ISSUE TITLE
OpenVPN on user cluster fails with readiness probe timing out

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12803]
### What happened?

During upgrade tests from 2.23.6 to 2.24.0-beta.1 it was discovered that the OpenVPN pod on the user cluster fails to start after the 2.24.0-beta.1 upgrade has been rolled out (it's unfortunately not clear if this was broken on 2.23.6 _before_ the upgrade, I didn't check). Same happens when I create the same cluster on 2.24.0-beta.1 directly.

The `openvpn-client` container in it gets continuously killed because of its probes:

```
  Warning  Unhealthy  92s (x13 over 2m56s)  kubelet            Readiness probe failed: command "/bin/ping -c 1 -w 5 10.20.0.1" timed out
  Warning  Unhealthy  92s (x3 over 112s)    kubelet            Liveness probe failed: command "/bin/ping -c 1 -w 5 10.20.0.1" timed out
  ```

Accessing pod logs is not possible because it requires control plane to node connectivity provided by OpenVPN. I suspect the whole thing is non-operational.

### Expected behavior

OpenVPN works / continues to work after 2.24.0-beta.1 upgrade.

### How to reproduce the issue?

Create user cluster with `spec.clusterNetwork.konnectivityEnabled=false` on KKP 2.24.0-beta.1

### How is your environment configured?

- KKP version: 2.24.0-beta.1
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: Cluster
metadata:
  name: openvpn-test-cluster
  [...]
spec:
  clusterNetwork:
    konnectivityEnabled: false
    [...]
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### Additional information

While OpenVPN is officially deprecated in 2.24, we still support it. So it should be operational.

**Comment by wozniakjan** [comment]
I will take a look what could be the culprit

**Comment by wozniakjan** [comment]
I can reproduce it and by ssh into the node I managed to get some logs, however, I am learning just now how our OpenVPN setup used to work.

The first suspicious finding is that the dnat container manipulating iptables seems to contain some incorrect rules
```
root@u478r6lpxv-worker-g8ss85-65b58bbf79-nfhbx:~# cat /var/log/containers/openvpn-client-69f687cc59-svqfx_kube-system_dnat-controller-7322b9f3db660b5f294ac90aae306280e01112367cdaad45a9a8cf47143f7018.log
2023-11-06T16:46:33.775036167Z stderr F iptables: No chain/target/match by that name.
2023-11-06T16:46:33.77635855Z stderr F iptables: No chain/target/match by that name.
2023-11-06T16:46:41.223166193Z stderr F iptables: No chain/target/match by that name.
```

**Comment by wozniakjan** [comment]
never mind, ^^ was a red herring, this is just when trying to delete a chain from table that doesn't yet exist. The chains are later added to tables in 5s periodic intervals and there are no more `iptables: No chain/target/match by that name` errors after the first while loop
https://github.com/kubermatic/kubermatic/blame/050a2310542825263a5d1ccf1149a4291bd5da88/addons/openvpn/openvpn-client-dep.yaml#L95-L102

**Comment by wozniakjan** [comment]
there is this section from the openvpn-client that repeats frequently
```
 21 2023-11-06T18:11:24.444382258Z stdout F 2023-11-06 18:11:24 TCP/UDP: Preserving recently used remote address: [AF_INET]100.64.30.10:1194
 22 2023-11-06T18:11:24.44444304Z stdout F 2023-11-06 18:11:24 Attempting to establish TCP connection with [AF_INET]100.64.30.10:1194 [nonblock]
 23 2023-11-06T18:11:24.444732592Z stdout F 2023-11-06 18:11:24 TCP connection established with [AF_INET]100.64.30.10:1194
 24 2023-11-06T18:11:24.444747386Z stdout F 2023-11-06 18:11:24 TCP_CLIENT link local: (not bound)
 25 2023-11-06T18:11:24.444752054Z stdout F 2023-11-06 18:11:24 TCP_CLIENT link remote: [AF_INET]100.64.30.10:1194
 26 2023-11-06T18:11:25.445984228Z stdout F 2023-11-06 18:11:25 Connection reset, restarting [-1]
 27 2023-11-06T18:11:25.446499801Z stdout F 2023-11-06 18:11:25 SIGUSR1[soft,connection-reset] received, process restarting
```
iiuc this means OpenVPN client tries to establish connection to server but then a second later the connection is restarted

**Comment by wozniakjan** [comment]
this imho looks like infrastructure misconfiguration rather than regression. While it's broken on QA, our DEV environment with OpenVPN works just fine.

But I have no idea why it's not working on QA, I set MTU for seed cilium to 1600, all VETH pairs are reporting 1600 too, OpenVPN defaults to 1500, so this should be fine. Logs contain no errors, just warnings about flag deprecations in the future but these warnings are present on dev too.

**Comment by embik** [comment]
We are as of now considering this a problem with our QA environments and not with the feature itself.

**Comment by wozniakjan** [comment]
so yeah, even a brand new cluster when I pick `NodePort` as the expose strategy works ok, I will check what's broken with the tunnelling envoy.

**Comment by wozniakjan** [comment]
for the record, I just tried this in `kubermatic-installer local kind` setup and all works fine, I will spend a little longer debugging QA.
