### ISSUE TITLE
`ApplicationInstallation` "cilium" fails to update immutable value`spec.values.ipam`

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#12802]
### What happened?

During a KKP 2.23.6 to 2.24.0-beta.1 upgrade the following issue was observed in the seed-controller-manager log. The cluster in question is a 1.26.9 cluster with Cilium 1.13.8 as CNI:

```json
{"level":"error","time":"2023-10-31T11:02:01.926Z","caller":"controller/controller.go:266","msg":"Reconciler error","controller":"kkp-cni-application-installation-controller","object":{"name":"c5cnp55hxx"},"namespace":"","name":"c5cnp55hxx","reconcileID":"08f35f5c-3696-4698-8e2e-6f461ec70bda","error":"failed to ensure ApplicationInstallation kube-system/cilium: failed to update object *v1.ApplicationInstallation \"kube-system/cilium\": admission webhook \"applicationinstallations.apps.kubermatic.k8c.io\" denied the request: ApplicationInstallation validation request 371461d4-fb17-46cf-8111-3952fdd89fbe denied: [spec.values.cni: Invalid value: map[string]interface {}{\"chainingMode\":\"portmap\", \"exclusive\":false}: value is immutable spec.values.ipam: Invalid value: map[string]interface {}{\"operator\":map[string]interface {}{\"clusterPoolIPv4MaskSize\":\"24\", \"clusterPoolIPv4PodCIDR\":\"172.25.0.0/16\", \"clusterPoolIPv4PodCIDRList\":[]interface {}{\"172.25.0.0/16\"}}}: value is immutable]","errorCauses":[{"error":"failed to ensure ApplicationInstallation kube-system/cilium: failed to update object *v1.ApplicationInstallation \"kube-system/cilium\": admission webhook \"applicationinstallations.apps.kubermatic.k8c.io\" denied the request: ApplicationInstallation validation request 371461d4-fb17-46cf-8111-3952fdd89fbe denied: [spec.values.cni: Invalid value: map[string]interface {}{\"chainingMode\":\"portmap\", \"exclusive\":false}: value is immutable spec.values.ipam: Invalid value: map[string]interface {}{\"operator\":map[string]interface {}{\"clusterPoolIPv4MaskSize\":\"24\", \"clusterPoolIPv4PodCIDR\":\"172.25.0.0/16\", \"clusterPoolIPv4PodCIDRList\":[]interface {}{\"172.25.0.0/16\"}}}: value is immutable]"}]}
```

The "current" values for this field are:

```yaml
    ipam:
        operator:
          clusterPoolIPv4MaskSize: "24"
          clusterPoolIPv4PodCIDR: 172.25.0.0/16
 ```
 
And now KKP tries to override this to set the new `clusterPoolIPv4PodCIDRList`, but apparently it is immutable. 

It looks like this was changed in #12561.

### Expected behavior

Upgrade works without Cilium system application failing to reconcile.

### How to reproduce the issue?

As per the description above, create a user cluster with Cilium 1.13 on KKP 2.23.6, then upgrade to KKP 2.24.0-beta.1.

### How is your environment configured?

- KKP version: 2.24.0-beta.1
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### Additional information

The PR mentions that the fields were deprecated and removed in Cilium 1.14. I haven't even tried to upgrade to Cilium 1.14 as part of this testing, because it breaks before. But that is another case that needs to be considered, especially in how to handle those fields and their immutability (?).

**Comment by cnvergence** [comment]
I have tested the upgrade of the Cilium version to 1.14 and can confirm that it works fine.
This happens only during the KKP upgrade.

**Comment by embik** [comment]
Correct, during the upgrade the Cilium version was unchanged.

**Comment by cnvergence** [comment]
This issue is going to happen everytime:
- we introduce new settings to immutable values (like cni.chainingMode)
- There was a change of key in upstream charts(ipam.operator.	clusterPoolIPv4PodCIDRList)
I have started the PR with adding some exclusions to unblock this issue, but we would need to find a better approach to this problem in the followup.
One idea would be to signal and handle KKP upgrades in application installer for KKP system applications.

**Comment by embik** [comment]
This issue is back after #12841.

```json
{"level":"error","time":"2023-11-14T07:07:25.904Z","caller":"controller/controller.go:266","msg":"Reconciler error","controller":"kkp-cni-application-installation-controller","object":{"name":"x9x57s8cg2"},"namespace":"","name":"x9x57s8cg2","reconcileID":"697574d3-866c-4219-8003-f27baf6db4c1","error":"failed to ensure ApplicationInstallation kube-system/cilium: failed to update object *v1.ApplicationInstallation \"kube-system/cilium\": admission webhook \"applicationinstallations.apps.kubermatic.k8c.io\" denied the request: ApplicationInstallation validation request 38eb9371-983a-4866-8400-6e4a5f4f7cb2 denied: [spec.values.ipam: Invalid value: map[string]interface {}{\"operator\":map[string]interface {}{\"clusterPoolIPv4MaskSize\":\"24\", \"clusterPoolIPv4PodCIDRList\":[]interface {}{\"172.25.0.0/16\"}}}: value is immutable]","errorCauses":[{"error":"failed to ensure ApplicationInstallation kube-system/cilium: failed to update object *v1.ApplicationInstallation \"kube-system/cilium\": admission webhook \"applicationinstallations.apps.kubermatic.k8c.io\" denied the request: ApplicationInstallation validation request 38eb9371-983a-4866-8400-6e4a5f4f7cb2 denied: [spec.values.ipam: Invalid value: map[string]interface {}{\"operator\":map[string]interface {}{\"clusterPoolIPv4MaskSize\":\"24\", \"clusterPoolIPv4PodCIDRList\":[]interface {}{\"172.25.0.0/16\"}}}: value is immutable]"}]}
```

**Comment by embik** [comment]
False alarm.
