### ISSUE TITLE
kubermatic-installer doesn't unpack addons correctly

### ISSUE THREAD

**Issue by moelsayed** [kubermatic/kubermatic#12866]
### What happened?
With version 2.24.0, when using the `mirror-images`, the kubermatic-installer fails to unpack the addon image and generate the image list.

- Download the and unpack the release tarball.
- run the `mirror-images` command:
```bash
$ $PWD/kubermatic-installer --charts-directory $PWD/charts mirror-images example.registry.com/kubermatic --config $PWD/examples/kubermatic.example.yaml --helm-values $PWD/examples/values.example.yaml   -v --dry-run 

DEBU[0000] Loading versions                              versions-filter=
DEBU[0001] Exporting addon image to archive file…        export-file=/tmp/kkp-mirror-images-2971815469/image.tar image="quay.io/kubermatic/addons:v2.24.0" temp-directory=/tmp/kkp-mirror-images-2971815469
INFO[0002] 🚀 Collecting images…                         
DEBU[0002] Collecting images…                            cni-plugin=canal cni-version=v3.19 provider=vsphere version=1.26.1
ERRO[0002] ❌ Operation failed: failed to get images: failed to get images from addons: unable to list addons: open /tmp/kkp-mirror-images-2971815469/addons: no such file or directory. 
```
### Expected behavior
Full list of images generated.

### How is your environment configured?

- KKP version: v2.24.0
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by embik** [comment]
Problem is likely this line: https://github.com/kubermatic/kubermatic/blob/7e77b7ac6e8f5e63af8695cd3c7401ed0e8cb366/cmd/kubermatic-installer/cmd_mirror_images.go#L192

It made sense in the big `MirrorImagesFunc`, but now it more or less immediately deletes the extracted folder again before it can be used.
