### ISSUE TITLE
Determining DNS settings fails if non-default ingress controller is used

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#12928]
### What happened?

I've disabled deploying the `nginx-ingress-controller` Helm chart and will try to use the Cilium built-in ingress controller instead.

Now running `kubermatic-installer deploy` ends with this:
```
time="2023-12-21T13:22:48Z" level=info msg="   📡 Determining DNS settings…"
time="2023-12-21T13:22:48Z" level=debug msg="      Waiting for \"nginx-ingress-controller/nginx-ingress-controller\" to be ready…"
time="2023-12-21T13:22:48Z" level=warning msg="      Timed out waiting for the LoadBalancer service \"nginx-ingress-controller/nginx-ingress-controller\" to become ready."
time="2023-12-21T13:22:48Z" level=warning msg="      Please check the Service and, if necessary, reconfigure the"
time="2023-12-21T13:22:48Z" level=warning msg="      nginx-ingress-controller Helm chart. Re-run the installer to apply"
time="2023-12-21T13:22:48Z" level=warning msg="      updated configuration afterwards."
time="2023-12-21T13:22:48Z" level=info msg="🛬 Installation completed successfully. ✌"
```

### Expected behavior

It probably shouldn't rely on a component that is disabled. But more importantly, it should probably just fetch the IPs from the ingresses that it created - not sure why it's looking at the ingress controller's LoadBalancer service at all.

They literally provide the same info:
```
$ k -n kube-system get svc cilium-ingress -o json | jq .status.loadBalancer.ingress
[
  {
    "hostname": "86.119.36.151.nip.io"
  }
]

$ k -n kubermatic get ingress kubermatic -o json | jq .status.loadBalancer.ingress
[
  {
    "hostname": "86.119.36.151.nip.io"
  }
]
```

... but the latter should be more agnostic.

### How to reproduce the issue?

`kubermatic-installer deploy kubermatic-master --skip-charts="nginx-ingress-controller" [...]`

I think that's all it takes.

### How is your environment configured?

- KKP version: 2.24.1
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

I guess this could technically matter:
```
  ingress:
    domain: kkp.foo
    certificateIssuer:
      kind: ClusterIssuer
      name: letsencrypt-production
    className: cilium
```

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

Ubuntu 22.04

**Comment by xrstf** [comment]
Thanks for the report, I'll look into it.
