### ISSUE TITLE
Add field for Application logo in API

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#12938]

**Comment by Waseem826** [comment]
I think we also need this in the dashboard API.

**Comment by Waseem826** [comment]
Nevermind, its picked up by the dashboard API automatically. However, the list endpoint for application definition still only returns name and description. I think we might need to update it to return the Logo as well.

**Comment by Waseem826** [comment]
Looks like we just need to add new fields here: https://github.com/kubermatic/dashboard/blob/main/modules/api/pkg/handler/v2/application_definition/conversion.go#L30
So I'll take care of that.
