### ISSUE TITLE
Make node version configurable in the UI

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1298]
Currently the nodes always get the master version, we should make this an optional configuration field to avoid deadlocks when there are kubelet bugs in a given version as has e.G. happend with volume subPath in the 1.9 tree.

**Comment by mrIncompetent** [comment]
Should we offer every patch release in a DropDown but default to the master-version?
WDYT @alvaroaleman @kgroschoff 

Via the API its already possible to specify the kubelet version

**Comment by kgroschoff** [comment]
We could make it configurable if it already is possible via the api. I only need all versions including default.
And if we could choose them we could think about down-/upgrading as well ;)

**Comment by alvaroaleman** [comment]
> Should we offer every patch release in a DropDown but default to the master-version?

Yep, we should provide an endpoint for the available kubelet versions

> And if we could choose them we could think about down-/upgrading as well ;)

That is not possible because the machine-controller can not down/-upgrade nodes in-place, the user has to create a new one if he or she wants a different version

**Comment by maciaszczykm** [comment]
We will track from https://github.com/kubermatic/dashboard-v2/issues/983.

/close
