### ISSUE TITLE
Add k8sgpt as a default Application 

### ISSUE THREAD

**Issue by mfahlandt** [kubermatic/kubermatic#12994]
### Description of the feature you would like to add / User story

As a SRE i would love to utilize the [k8sgpt operator](https://docs.k8sgpt.ai/getting-started/in-cluster-operator/) in order to optmize cluster debugging with AI

### Solution details

Implement k8sGPT as a default Application into KKP EE

### Use cases

With the Help of k8sgpt it is easier to debug Issues in your K8s Cluster

**Comment by xrstf** [comment]
Fixed by #13025
