### ISSUE TITLE
Add Nvida Operator as default Application

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#13017]
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html

Install the Operator with the default configuration:

```helm install --wait --generate-name  -n gpu-operator --create-namespace nvidia/gpu-operator```

**Comment by toschneck** [comment]
@csengerszabo  did it make it to the release?

**Comment by SimonTheLeg** [comment]
@toschneck fyi. This will make it into the next release
