### ISSUE TITLE
vSphere cluster provisioning and upgrading - Test Release 2.25

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#13037]
## General Instructions

Run [kubermatic/infra/blob/main/clusters/kkp-qa-env/conformance-tester.sh](https://github.com/kubermatic/infra/blob/main/clusters/kkp-qa-env/conformance-tester.sh) like `PROVIDERS=vsphere conformance-tester.sh`.

## Checklist

```[tasklist]
### Supported Operating Systems
- [x] Ubuntu
- [x] CentOS 7
- [x] Flatcar
- [x] RHEL
- [x] Rocky Linux
```

```[tasklist]
### Supported Kubernetes Versions (use latest patch releases available)
- [x] v1.27
- [x] v1.28
- [x] v1.29
```

```[tasklist]
### Upgrades
- [x] Upgrade from v1.27.x -> v1.28.x
- [x] Upgrade from v1.28.x -> v1.29.x
```

**Comment by kron4eg** [comment]
| version / OS | Ubuntu | CentOS 7 | Flatcar | RHEL | Rocky Linux |
|--------------|--------|----------|---------|------|-------------|
| v1.27 |  |  |  |  |  |
| v1.28 |  |  |  |  |  |
| v1.29 |  |  |  |  |  |

**Comment by kron4eg** [comment]
<details id="suite.0">
<summary >
<span style="color: red">⛔</span>
<span class="testsuite-name" title="vsphere-ubuntu-1.27.11">vsphere-ubuntu-1.27.11</span>
Tests: <b>7</b>,
Failures: <b>1</b>,
Errors: <b>0</b>,

<em>Time: 1597.041379326</em>
</summary>
<div><details style="margin-left: 1em" id=case.0.0>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Create cluster [KKP] Create cluster">
[KKP] Create cluster
[KKP] Create cluster
</span>
<em>2.3662805860000002</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.1>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Wait for successful reconciliation [KKP] Wait for successful reconciliation">
[KKP] Wait for successful reconciliation
[KKP] Wait for successful reconciliation
</span>
<em>75.464767606</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.2>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Wait for control plane [KKP] Wait for control plane">
[KKP] Wait for control plane
[KKP] Wait for control plane
</span>
<em>15.294634968</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.3>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Add LB and PV Finalizers [KKP] Add LB and PV Finalizers">
[KKP] Add LB and PV Finalizers
[KKP] Add LB and PV Finalizers
</span>
<em>0.595158685</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.4>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Create MachineDeployments [KKP] Create MachineDeployments">
[KKP] Create MachineDeployments
[KKP] Create MachineDeployments
</span>
<em>1.9912499559999999</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.5>
<summary >
<span title="failed" style="color: red">⛔</span>
<span class="testcase-name" title=" [KKP] Wait for machines to get a node [KKP] Wait for machines to get a node">
[KKP] Wait for machines to get a node
[KKP] Wait for machines to get a node
</span>
<em>1500.003946835</em>
</summary>
<div style="margin-left: 1em" >
<div>


<div><b>Content:</b></div>
<div><pre>context deadline exceeded; last error was: failed to list machines: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline</pre></div>
</div>
<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.6>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Delete cluster [KKP] Delete cluster">
[KKP] Delete cluster
[KKP] Delete cluster
</span>
<em>0.077922581</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details></div>
</details>

<details id="suite.0">
<summary >
<span style="color: red">⛔</span>
<span class="testsuite-name" title="vsphere-ubuntu-1.29.2">vsphere-ubuntu-1.29.2</span>
Tests: <b>9</b>,
Failures: <b>1</b>,
Errors: <b>0</b>,

<em>Time: 1602.54161374</em>
</summary>
<div><details style="margin-left: 1em" id=case.0.0>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Create cluster [KKP] Create cluster">
[KKP] Create cluster
[KKP] Create cluster
</span>
<em>2.9759664900000002</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.1>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Wait for successful reconciliation [KKP] Wait for successful reconciliation">
[KKP] Wait for successful reconciliation
[KKP] Wait for successful reconciliation
</span>
<em>90.08026033</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.2>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Wait for control plane [KKP] Wait for control plane">
[KKP] Wait for control plane
[KKP] Wait for control plane
</span>
<em>5.285416268</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.3>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Add LB and PV Finalizers [KKP] Add LB and PV Finalizers">
[KKP] Add LB and PV Finalizers
[KKP] Add LB and PV Finalizers
</span>
<em>0.240985892</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.4>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Create MachineDeployments [KKP] Create MachineDeployments">
[KKP] Create MachineDeployments
[KKP] Create MachineDeployments
</span>
<em>2.32594058</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.5>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Wait for machines to get a node [KKP] Wait for machines to get a node">
[KKP] Wait for machines to get a node
[KKP] Wait for machines to get a node
</span>
<em>10.078123884</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.6>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Wait for nodes to be ready [KKP] Wait for nodes to be ready">
[KKP] Wait for nodes to be ready
[KKP] Wait for nodes to be ready
</span>
<em>10.123644521</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.7>
<summary >
<span title="failed" style="color: red">⛔</span>
<span class="testcase-name" title=" [KKP] Wait for Pods inside usercluster to be ready [KKP] Wait for Pods inside usercluster to be ready">
[KKP] Wait for Pods inside usercluster to be ready
[KKP] Wait for Pods inside usercluster to be ready
</span>
<em>1479.798670546</em>
</summary>
<div style="margin-left: 1em" >
<div>


<div><b>Content:</b></div>
<div><pre>context deadline exceeded; last error was: not all Pods are ready: [cilium-operator-84c84875bd-77k2w coredns-5c787b86-q6ksh coredns-5c787b86-t6jth dashboard-metrics-scraper-7f8c9dbc8c-mg9m9 dashboard-metrics-scraper-7f8c9dbc8c-pbzmq hubble-generate-certs-46j5j hubble-relay-7b89794c94-kwk6z hubble-ui-6f48889749-s9fr4 konnectivity-agent-b6dfd9dc4-495mk konnectivity-agent-b6dfd9dc4-zgf7f metrics-server-5f764f5b47-8djdb metrics-server-5f764f5b47-lsmgk snapshot-controller-78d89c7569-bt8fp snapshot-controller-78d89c7569-zvcr9 snapshot-validation-deployment-8964f7d7c-zqwsv vsphere-csi-controller-c84d5b9c9-g52q4]</pre></div>
</div>
<div>


</div>
</div>
</details><details style="margin-left: 1em" id=case.0.8>
<summary >
<span title="passed" style="color: green">✅</span>
<span class="testcase-name" title=" [KKP] Delete cluster [KKP] Delete cluster">
[KKP] Delete cluster
[KKP] Delete cluster
</span>
<em>0.402689516</em>
</summary>
<div style="margin-left: 1em" >

<div>


</div>
</div>
</details></div>
</details>

**Comment by kron4eg** [comment]
all tests passed

/close
