### ISSUE TITLE
Test KKP Upgrade - Test Release 2.25

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#13042]
As usual (see #12799 for previous ticket), we need to run a couple of upgrade tests to make sure we don't run into problems with KKP 2.24 being upgraded to KKP 2.25.

Please add your things to test in comments below, so I can add them to the things to be validated during and after a KKP upgrade.

```[tasklist]
### To Be Validated
- [x] Create clusters in various configurations (versions, CNI, addons) in 2.24 and observe their upgrade behaviour
- [x] Use app catalog feature, install apps in 2.24 and upgrade KKP installation to 2.25 to observe app upgrades
- [x] Deploy MLA stacks and observe their upgrade behaviour
```

```[tasklist]
### Found Issues
- [ ] #13142
- [ ] https://github.com/kubermatic/kubermatic/issues/13143
- [ ] https://github.com/kubermatic/kubermatic/issues/13144
- [ ] https://github.com/kubermatic/kubermatic/issues/13145
- [ ] https://github.com/kubermatic/kubermatic/issues/13146
```

**Comment by SimonTheLeg** [comment]
To be validated: With the change of the values and defaultValues to a string in https://github.com/kubermatic/kubermatic/pull/13053, we need to verify that this does not brick the upgrade proces

**Comment by archups** [comment]
To be validated: With the change of the helm chart version for default applications in https://github.com/kubermatic/kubermatic/pull/13058, we need to verify that this does not brick the upgrade process.

**Comment by wurbanski** [comment]
to be validated: MLA upgrades:
* loki upgrade (#12967)
* grafana upgrade (#12965 
* minio upgrade (including fs/xl storage type)
* cortex upgrade (#12935 )

**Comment by embik** [comment]
Results so far:

- MLA upgrade worked well up to #13142.
- Applications just vanished from the user cluster. See #13143. I'll try to find more details retroactively, but I expect someone needs to do their own upgrade tests to observe this in detail. I honestly did not expect this to happen.
- AWS CCM crash loops, see #13144.

**Comment by embik** [comment]
Notes on the upgrade:

- The upgrade itself was pretty painless, I did not need to adjust any configuration.
- Upgrade guide should still feature all the MLA values changes. Since I had a minimal configuration it didn't affect me, but some users are probably customizing their MLA setup further.

**Comment by embik** [comment]
Upgrading from v2.24.4 to v2.25.0-rc.0:

- `spec.cloud.aws.roleARN` got migrated automatically to the fully qualified way. No CCM crashes observed.
- apps did not vanish from the user clusters and have their upgraded versions available from the version drop-down.

**Comment by embik** [comment]
Seems we are all good!
