### ISSUE TITLE
Azure load balancer SKU default should be standard

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#13069]
### Description of the feature you would like to add / User story

As noted in https://github.com/kubermatic/kubermatic/issues/13063, Azure will is in process of removing `Basic` SKU for load balancer (by Sept 2025). Currently, the default value for laodBalancerSKU in azure user-cluster is `basic`. We need to default it to `standard`

Ref: [Azure announcement](https://azure.microsoft.com/en-us/updates/azure-basic-load-balancer-will-be-retired-on-30-september-2025-upgrade-to-standard-load-balancer/)

**Comment by embik** [comment]
/unassign

We have just entered code freeze, I'd prefer to keep the current default. We should do this for 2.26 for sure.

**Comment by xrstf** [comment]
Sorry for all the spam here.
