### ISSUE TITLE
Azure cluster creation ignore loadBalancerSKU value from preset

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#13063]
### What happened?
If 
1. We have setup a preset for Azure which includes `loadBalancerSku: "standard"`
1. We create a user-cluster in Azure with no additional customization in `spec.cloud.azure` for cluster.
1. We add nginx-ingress addon

then
1. The `cloud-config` secret in cluster-xxx namespace shows `"loadBalancerSku":"basic"` instead of `standard`.
1. The load-balancer which gets created in Azure is of SKU Basic.

Earlier, user-cluster creation in Azure used to respect loadBalancerSKU value from preset. I have a feeling that this bug might have got introduced due to changes done as part of #8855 

If we specifically provide `loadBalancerSku: "standard"` as part of `spec.cloud.azure`, the KKP picks that value and create standard SKU load balancer.

As a aside: Azure is [reporting](https://azure.microsoft.com/en-us/updates/azure-basic-load-balancer-will-be-retired-on-30-september-2025-upgrade-to-standard-load-balancer/) that they will be phasing out basic SKU loadbalancer by 30th Sept 2025. So it might be good idea to at least start defaulting to loadBalancer type as standard.

### Expected behavior
If I specify `loadBalancerSku: "standard"` in Azure cluster preset, the user-cluster created load balancer should be of standard SKU.

Potentially - if I do not specify any SKU, it should still be standard SKU due to upcoming removal of Basic SKU by Azure.

### How to reproduce the issue?
See Above

### How is your environment configured?

- KKP version: 2.24.2
- Shared or separate master/seed clusters?: Shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: Preset
metadata:
  name: cld-sandbox
spec:
  azure:
    ...
    loadBalancerSku: "standard"
    ...
```

</details>

### What cloud provider are you running on?
Azure

### What operating system are you running in your user cluster?
Ubuntu 22.04

**Comment by embik** [comment]
I'll take a look.

**Comment by embik** [comment]
> Earlier, user-cluster creation in Azure used to respect loadBalancerSKU value from preset. I have a feeling that this bug might have got introduced due to changes done as part of https://github.com/kubermatic/kubermatic/pull/8855

Looking at the code for this (see https://github.com/kubermatic/dashboard/pull/6506), I have some serious doubts it ever worked. Can you specify in which versions it was working?

**Comment by embik** [comment]
> As a aside: Azure is [reporting](https://azure.microsoft.com/en-us/updates/azure-basic-load-balancer-will-be-retired-on-30-september-2025-upgrade-to-standard-load-balancer/) that they will be phasing out basic SKU loadbalancer by 30th Sept 2025. So it might be good idea to at least start defaulting to loadBalancer type as standard.

@dharapvj can you do me a favour and raise a separate issue for this, so we can track it?

**Comment by dharapvj** [comment]
@embik - thank you for the fix in dashboard side. But I think the issue exists in kubermatic api side as well. We observed the issue when we create cluster directly by calling api and providing it a cluster.Json.

Will that need fix in dashboard or API code?

**Comment by embik** [comment]
> @embik - thank you for the fix in dashboard side. But I think the issue exists in kubermatic api side as well. We observed the issue when we create cluster directly by calling api and providing it a cluster.Json.
> 
> 
> 
> Will that need fix in dashboard or API code?

The fix _is_ in the API code :-)

**Comment by dharapvj** [comment]
Ah ok. Then cool. I was not clear on that
