### ISSUE TITLE
VCD: Move CSI controller to seed cluster - Test Release 2.25

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13070]
## Instructions

1. Create a user cluster on VCD
2. Ensure that the CSI controller in the seed cluster and node agent in the user cluster are in the correct state
3. Create a PV and test attachment/dettachment.

## References
PR: https://github.com/kubermatic/kubermatic/pull/13020

**Comment by akash-gautam** [comment]
Attachment/detachment of volumes works fine for a VCD user cluster, csi node-plugin on user cluster & csi-controller on the user cluster namespace are stable as well.

<img width="1439" alt="image" src="https://github.com/kubermatic/kubermatic/assets/20444009/2b31a00c-e666-4c8b-9d57-4bc3076c7005">
