### ISSUE TITLE
Multi-AZ support for VMware Cloud Director - Test Release 2.25

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13071]
## Instructions

1. Create a user cluster on VCD
2. Attach multiple networks from the provider settings step in the cluster creation wizard
3. Open the VCD console to ensure that multiple networks have been attached to the vApp

## References
PR: https://github.com/kubermatic/kubermatic/pull/12996
Ticket: https://github.com/kubermatic/kubermatic/issues/12650

**Comment by ahmadhamzh** [comment]
LGTM
/close
