### ISSUE TITLE
Test Applications - Test Release 2.25

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#13099]
```[tasklist]
### Tasks
- [ ] #13096
- [ ] #13097
- [ ] #13098 
```

**Comment by SimonTheLeg** [comment]
I have discovered a bug on AppInstalls that blocks the current testing for the topics assigned to @akash-gautam and @xrstf. Please only start with your testing after this PR is merged

https://github.com/kubermatic/kubermatic/pull/13131

**Comment by embik** [comment]
All tasks completed, closing this.
