### ISSUE TITLE
Test MLA dashboards - Release 2.25

### ISSUE THREAD

**Issue by wurbanski** [kubermatic/kubermatic#13101]
Test Dashboards in UserCluster MLA's Grafana and make sure all the dashboards and all the queries are working.

For this:
* [x] enable user cluster MLA in a cluster and required addons
* [x] deploy some workload emitting metrics to Prometheus
* [x] give it time (about 30 minutes of collecting metrics)
* [x] Check all available dashboards

**Comment by xrstf** [comment]
Looks good, all dashboards and Loki show data.
