### ISSUE TITLE
usercluster-controller-manager crash looping after disabling CSI and upgrading to newer Kubernetes version

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#13146]
### What happened?

After disabling CSI on a user cluster that was created in KKP v2.24.4 prior to upgrading to KKP v2.25.0-beta.2 by using the option in the dashboard and then upgrading the Kubernetes version from 1.27.10 to 1.28.7, the usercluster-controller-manager fails to start.

Looking at the logs, this is the error it encounters:

```json
{"level":"error","time":"2024-03-01T12:43:09.720Z","caller":"controller/controller.go:266","msg":"Reconciler error","controller":"kkp-user-cluster-controller","object":{"name":"identifier"},"namespace":"","name":"identifier","reconcileID":"074449bd-ff71-49d5-a5f3-54a1af44fe7b","error":"failed to get csi config: failed to get legacy cloud-config ConfigMap: ConfigMap \"cloud-config-csi\" not found"}
```

### Expected behavior

usercluster-controller-manager does not crash for clusters for which the "disable CSI driver" feature is enabled.

### How to reproduce the issue?

1. (Unclear if needed) Set up a KKP v2.24.4 environment.
2. Create vSphere cluster with CSI initially enabled on e.g. Kubernetes 1.27.
3. (Unclear if needed) upgrade to KKP v2.25.0-beta.2.
4. Disable CSI driver for vSphere user cluster.
5. (Unclear if needed) upgrade Kubernetes version of user cluster from 1.27 to 1.28.
6. Observe usercluster-controller-manager not starting anymore.

### How is your environment configured?

- KKP version: v2.25.0-beta.2
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

vSphere

### What operating system are you running in your user cluster?

N/A

**Comment by xrstf** [comment]
Just by creating a VCD cluster and then disabling the CSI Driver i can reproduce this. No cluster upgrades necessary. The errors happen pretty much instantly after disabling the CSI Driver.
