### ISSUE TITLE
"Failed to undeploy cluster backup components" on new clusters

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#13181]
### What happened?

When creating a new user cluster in KKP v2.25.0-rc.0, the very early phases of cluster creation often see events on the cluster regarding cluster backup components:

> failed to undeploy cluster backup user-cluster components: failed to undeploy cluster backup user-cluster resources: failed to delete cluster backup user-cluster resource: failed to get API group resources: unable to retrieve the complete list of server APIs: apps/v1: Get "https://apiserver-external.cluster-a5pvzhh49r.svc.cluster.local./apis/apps/v1": dial tcp 10.240.27.81:443: connect: operation not permitted

>failed to undeploy cluster backup user-cluster components: failed to get user cluster client: Secret "internal-admin-kubeconfig" not found

This doesn't seem to have any impact and vanishes as soon as more components of the user cluster are up, but I feel like this code path should be more vigilant in checking the cluster status before trying to get clients.

No cluster backup is intended to be used.

### Expected behavior

These warnings do not show up.

### How to reproduce the issue?

- Create new user clusters on KKP v2.25.0-rc.0

### How is your environment configured?

- KKP version: v2.25.0-rc.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

**Comment by archups** [comment]
/customer-request 
Customer is affected by this issue.
