### ISSUE TITLE
Add chery-pick bot for release branches

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1320]
Currently, if we have changed that need to land in both master and one or more release branches, we have to manually create multiple PRs for it. This is tedious and easy to forget.

It would be awesome if we instead had a cherry-pick bot that would automatically cherry-pick based on Github Labels in the appropriate release branch after the initial PR got merged and report back in the PR.

**Comment by mrIncompetent** [comment]
Something for a Hackathon?
The only thing i've found so far was https://github.com/adtac/cherry-pick-bot
and i'm not sure if that's suitable for us

**Comment by kdomanski** [comment]
@alvaroaleman Is this done? Does the bot still work with prow-enabled repos?

**Comment by alvaroaleman** [comment]
This can be considered done. We use the Prow bot which right now does not work because DroneCI refuses to build forks, so the tests never pass and hence stuff never gets merged. @nikhita Is currently working on moving everything over from Drone to Prow, once thats done we can have autmatic cherry picks again.

I'll close this issue as theres nothing to be done here
