### ISSUE TITLE
Support for OS - Ubuntu 24.04 LTS at User Cluster

### ISSUE THREAD

**Issue by archups** [kubermatic/kubermatic#13340]
### Description of the feature you would like to add / User story

As a end customer, I wish to have support for OS - Ubuntu 24.04 LTS version for User cluster setup
in order to be able to create user cluster machine deployment/worker nodes with Ubuntu 24.04 LTS. 

### Solution details

- Provide support for Ubuntu 24.04 LTS as part the supported Operating systems for User cluster setup in KKP.

**Comment by ahmedwaleedmalik** [comment]
/assign @csengerszabo 

I am simply assigning this to you, Csenger, to ask if we'll have/want this in 2.26 or if it should land later. Also, this would affect https://github.com/kubermatic/kubeone/issues/3161 as without support for 24.04 in MC and OSM it cannot be added completely to KubeOne or KKP either.

**Comment by ahmedwaleedmalik** [comment]
/unassign 

Probably should have just tagged instead of assigning you to the ticket....
