### ISSUE TITLE
Document how to generate documentation locally

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1338]
Document how to generate documentation locally.
Where should this be documented?
I see we already include https://github.com/kubermatic/docs/blob/master/README.md in the website?

**Comment by cbrgm** [comment]
Maybe we can add this to the README file in the docs repository?
There is a guide about how to contribute to the docs [here](https://docs.kubermatic.io/contributing/contributing/). I think it describes already how to generate the docs locally.

**Comment by mrIncompetent** [comment]
Ah brilliant - didn't saw this one. Yeah, just a link the readme would be good!

**Comment by cbrgm** [comment]
Fixed in https://github.com/kubermatic/docs/issues/30
