### ISSUE TITLE
Unexpected deletion of pods in the shared master/seed KKP cluster

### ISSUE THREAD

**Issue by cnvergence** [kubermatic/kubermatic#13392]
### What happened?

After installation of the shared master/seed KKP environment in AWS, deleting seed CRD from the cluster resulted in clean up of all resourced from kubermatic namespace, including master components.

### Expected behavior

The operator should be aware of the shared environment and not clean up pods that are part of the master KKP.

### How to reproduce the issue?

Having installed the shared KKP environment, delete seed CRD from the cluster and observe the deletion of pods in kubermatic namespace.

### How is your environment configured?

- KKP version: 2.24.6
- Shared or separate master/seed clusters?: shared

### What cloud provider are you running on?

AWS

**Comment by xrstf** [comment]
This is surprising, the operator should be able to handle such cases just fine. Just from glancing at the code I'm also wondering how this could even happen. There is no code in KKP's operator to delete the Deployments.. The `kkp-master-controller-manager` Deployment is owned by the KubermaticConfiguration, so only if that is removed, should the Deployment be GC'ed.

**Comment by xrstf** [comment]
So today we reproduced this issue _purposefully_ *cough* and I think the bug is somewhere in https://github.com/kubermatic/kubermatic/blob/main/pkg/controller/master-controller-manager/seed-sync/reconciler.go#L231-L233

This ticket should have higher priority.
