### ISSUE TITLE
OpenVPN - node-access assumes node-network not greater than /16

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1343]
### context:

The OpenVPN addon is doing a mapping from addresses in a (virtual) node access network (default: 10.254.0.0/16) to real node addresses.
The current approach for this is very simple:

1. it is assumed the real node-network is a /16 at maximum
2. it is assumed the node-access-network is a /16 at minimum
4. the mapping happens by replacing the first two octets of the node-access-network with the real node-network.

### example:
* you have nodes on AWS with private IP addresses: `172.31.100.200` and `172.31.50.60`. 
* you have the default node-access-network: `10.254.0.0/16`
* you can access the two nodes from the master components as `10.254.100.200` and `10.254.50.60`

### the issue:
* this breaks if your node-network is bigger than a /16 (or at least when you get ambiguity in the last two octets of the real node ip address)
* you have to calculate the node-access addresses from the node addresses
* you need a huge /16 for node-access-network even if you just have very few nodes

### idea / plan:
* some real IPAM is needed.
* when new nodes join a node-access ip should be allocated from the node-access-network
* nodes should get an annotation with the node-access ip

**Comment by mrIncompetent** [comment]
@alvaroaleman please open up a docs issue to document the limitation
