### ISSUE TITLE
Prometheus chart: Scrape controller-manager and scheduler

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1347]
The prometheus chart currently has no scrape targets for the controller-manager and scheduler. This results in the Grafana Dashboard Kubernetes -> Cluster-Status to show N/A for Controller-Managers up and Schedulers up.

**Comment by metalmatze** [comment]
Yes. That is because we can't scrape those on GKE.
The dashboard are on the edge of being moved to newer once in the next weeks, after the Prometheus migration to statefulset is done.

**Comment by alvaroaleman** [comment]
So why do we have it in the dashboard, then?

Also: For our customers this limitation does not apply, right? Maybe just add a config option in the helm chart for it

**Comment by metalmatze** [comment]
It was a dashboard from earlier version provided by the Prometheus Operator.
I basically copied them and made most adjustments to make them work. On GKE this one thing just isn't possible.
Yes. For customers this would work and we'd need to scrape those.

In the future we won't have the dashboard anymore, as this has been removed upstream. Instead all those things are alerted on.

If that's not a major problem I'd just leave it as it is right now and focus on the new dashboards. Nobody complained in 8 months. So the last 2 weeks should be fine too :innocent:

**Comment by pkavajin** [comment]
TODO:
* regarding dashboards: nothing, that will be done upstream
* regarding scraping: Add a flag to values.yaml which indicates whether controller-manage/scheduler should be scraped

**Comment by xrstf** [comment]
There's nothing really to do here. The dashboards are long gone, there are alerting rules in place for missing scheduler and controller-manager and there is nothing we need to scrape because alerts originate at their source and not on the master/seed level.
