### ISSUE TITLE
Cilium - kubeProxyReplacement use new defined Values

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#13489]
### Description of the feature you would like to add / User story

As a user
I would like to be safe to cilium values and using the current values of `kubeProxyReplacement` (`true` or `false`)
in order to ensure to running in unexpected issues using cilium

### Solution details

See updated helm chrats values and depricated note:
https://github.com/cilium/cilium/blob/v1.15.6/install/kubernetes/cilium/values.yaml#L1788 

### Use cases

Regular Maintenance of CNI flags

**Comment by toschneck** [comment]
Could be already fixed in  latest main brunch

**Comment by cnvergence** [comment]
fixed by https://github.com/kubermatic/kubermatic/pull/13291
