### ISSUE TITLE
Add StorageClass for new Clusters

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1349]
Every new cluster (when using OpenStack/Azure/AWS/vSphere) should get a StorageClass which fits to the environment.
The StorageClass should be added via an Addon.

**Comment by mrIncompetent** [comment]
Blocked as i'm waiting until we change the request body for the create-cluster request

**Comment by kdomanski** [comment]
This needs more reasearch. StorageClasses have provider-specific config options that we need to look into. We probably want to split this up into per-provider stories.

**Comment by mrIncompetent** [comment]
I added the question label

**Comment by toschneck** [comment]
related to #1666
