### ISSUE TITLE
usercluster-mla kube-state-metrics pdb prevents node-rotation

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#13493]
### What happened?

If usercluster-mla is enabled on user-clusters and if we have enabled the kube-state-metrics addon (which is mandatory for usercluster-mla dashboards to function), if we try to rotate the machine deployment, one node from old machine deployment gets stuck. Specifically, the node which is running kube-state-metric pod cannot get cordoned and removed until we kill the ksm pod manually.

This happens due to [PDB for KSM](https://github.com/kubermatic/kubermatic/blob/main/addons/kube-state-metrics/pdb.yaml#L21) which does not allow pod strength to go below 1.

### Expected behavior

Just like all the other pods, ksm pod should also get evicted from old node and moved to new node. The old node then can get recycled.

### How to reproduce the issue?

1. enable usercluster-mla on a user-cluster
2. install kube-state-metrics addon
3. force restart the machine deployment / upgrade k8s version so that MD gets rotated.
4. wait for all old nodes to get removed.
5. Observe that one old node remains where ksm pod is running

### How is your environment configured?

- KKP version: 2.25.6
- Shared or separate master/seed clusters?: shared and dedicated

### What cloud provider are you running on?
Azure, VSphere

### What operating system are you running in your user cluster?
Ubuntu 22.04

**Comment by xrstf** [comment]
Can confirm, we're looking into it. It seems that PDBs are more problematic than I thought (https://github.com/kubernetes/kubernetes/issues/93476) and we might generally have to stop deploying them by default.
