### ISSUE TITLE
Use semver.Version instead of string for `clusterSpec.Version` 

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1351]
We currently define the clusterVersion as string, this has the drawback that on every place where we want to switch based on cluster version we have to parse that string.

We should instead define it as something that is easier to handle internally, e.G.`github.com/Masterminds/semver.Version`

**Comment by mrIncompetent** [comment]
As we recently switched from `Cluster.Spec.MasterVersion` to `Cluster.Spec.Version` this won't be possible within the `v2.6` branch.
We have a migration which checks if the `Cluster.Spec.Version` is empty and then copies `Cluster.Spec.MasterVersion` to `Cluster.Spec.Version`.

When using `semver.Version` for `Cluster.Spec.Version` JSONUnmarshal would fail if `Cluster.Spec.Version` is empty. So retrieving the Cluster via the Kubernetes go-client would fail.

**Comment by mrIncompetent** [comment]
I added the `v2.7` and `blocked` label for now.

**Comment by alvaroaleman** [comment]
Moving discussion over from #2095:

@mrIncompetent wrote:

> With v2.9 we should be safe with just removing Cluser.Spec.MasterVersion & the migration step.
If the semver.Version supports json unmarshalling, we could just make cluster.spec.version a *semver.Version ?

I'd prefer to be sure the migration can also migrate older clusters, otherwise we basically force customers to update kubermatic version by kubermatic version, which is why I'd like to still have that field available just for the migration.

`semver.Version` does support json marshalling, I just tested that. I'd prefer `cluster.spec.version` to be a `semver.Version` literal instead of a pointer since its non-optional but other than that, SGTM.

**Comment by mrIncompetent** [comment]
> I'd prefer to be sure the migration can also migrate older clusters, otherwise we basically force customers to update kubermatic version by kubermatic version, which is why I'd like to still have that field available just for the migration.

I would rather make this a documented guarantee from this release onwards. I cannot guarantee if we followed that approach so far.
