### ISSUE TITLE
Use calculated DNS-IP in machine-controller deployment

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1357]
Current state:
We always use `10.10.10.10` as IP for the DNS inside the user-clusters.
`10.10.10.10` is a ServiceIP inside the users-cluster.

Desired State:
As we implemented configurable Service/Pod CIDR's for user-clusters, the DNS IP might be completely different. 
Right now, the addon-controller defines the ServiceIP for the DNS inside the user-cluster.
The logic must be extracted so it can be used elsewhere.

Currently the only other place where the DNS IP gets used:
- machine-controller deployment
The deployment must be changed so the calculcated ServiceIP gets used.

**Comment by thz** [comment]
Sounds like something for me.

**Comment by mrIncompetent** [comment]
Already asked @glower to take a look as he implemented the ip-calculation part on the addon-controller.
I don't mind who does it

**Comment by thz** [comment]
Ah right. It also fits perfectly in the templating task's context.
And `getKubeDNSClusterIP` is from @glower already anyways.
