### ISSUE TITLE
Do hash based comparision for ConfigMap & Secret reconciling

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1359]
### Intro
The cluster-controller creates/updates ConfigMaps & Secrets for each user-cluster it maintains.

### Current state
Right now, the cluster-controller has a update-if-needed logic (ConfigMap Example):
- Generate ConfigMap without applying it
- Get current ConfigMap from API (actually from the lister)
- Compare generated & current ConfigMap with `deep.Equal`
  - If they are diferent
    - Do a `PUT` to update/replace the object
  - If they are equal
    - Skip

#### Owner Reference
Each resource, the cluster-controller creates, gets a owner-reference to the responsible cluster object.
If the resource changes, the cluster-controller gets notified via event & does a sync of the cluster object.

For example:
- Administrator edits cloud-config -> `kubectl -n cluster-xxxxx edit configmap cloud-config`
- Cluster-controller gets notified
  - Syncs cluster
    - Checks cloud-config ConfigMap
    - Generated != current 
      - Updates/Replaces ConfigMap

### Problem
If a customer would implement a AdmissionWebhook to modify the cloud-config it would cause an endless loop of cluster-syncs, as the controller will always detect a difference & therefore will trigger an update:
- Cluster-Controller creates ConfigMap
- Webhook changes ConfigMap
- Cluster-Controller gets notifies about changes
- Cluster-controller gets notified
  - Syncs cluster
    - Checks cloud-config ConfigMap
    - Generated != current 
      - Updates/Replaces ConfigMap
      - Webhook changes ConfigMap
      - ....

### Desired state
Instead of comparing the content of the generated & current resource.
During creation of the ConfigMap a hash of the ConfigMap content should be stored inside the ConfigMap labels.
When later comparing the generated & current version of the ConfigMap:
  - Generate hash of generated ConfigMap content
  - Get hash from current ConfigMap labels
  - Compate both hashes & only act if they are not equal

**Comment by alvaroaleman** [comment]
Sounds fine :+1: 

Maybe we should do a label per configmap key and not for the whole configmap?

**Comment by mrIncompetent** [comment]
@alvaroaleman what would be the benefit of having `n` keys & `n` labels over a single hash for the whole `ConfigMap.Data`?

**Comment by alvaroaleman** [comment]
I thought it would probably easier to implement. But I guess we can just serialize the whole `map[string]string`, get a hash of it and use that, then we don't have to manage multiple labels

**Comment by p0lyn0mial** [comment]
Will it be okay if we change/update the `generated` config map and as a result overwrite the existing config map ? The customer might lose some custom data ? It probably depends if their webhook listens for `UPDATE` and `CREATE` verbs.

We could also put all custom data under the "payload" key (`map["payload"] = customerValue) and if the key is present during update/change of the config map we could just rewrite it. Regarding comparison we could compare all keys except "payload".

**Comment by mrIncompetent** [comment]
The Webhook needs to handle the update call.
