### ISSUE TITLE
Addons image needs update / openvpn manifest outdated

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1362]
With https://github.com/kubermatic/kubermatic/pull/1350/files#diff-1bd4a03c257de60e101fa8832bd02ffaR29 we changed readiness check for the openvpn client.

We must rebuild the addons image & push a new version.

As right now, we still deploy the Addon which expectes `/tmp/running` to exists.

**Comment by thz** [comment]
Okay - so we have:
* [kubermatic/addons](https://hub.docker.com/r/kubermatic/addons/tags/) at docker-hub referenced in `addons/README.md` and 
* [quay.io/kubermatic/addons](https://quay.io/repository/kubermatic/addons?tab=tags) referenced in `config/kubermatic/values.yaml`.

The repo at quay.io is about 3 weeks old while docker-hub is about 3 months old.

`addons/README.md` gives some instructions for building and pushing to docker-hub.

So I would summarize the due actions:
1. Clarify correct registry and update README.md
2. Discontinue/delete addons image in obsolete registry
3. Build/push addons image from master
