### ISSUE TITLE
`cloud-credentials` Secret in cluster namespace is not updated when `credential-` is

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#13648]
### What happened?

When credentials expire, they need to be rotated. The "source of truth" is the Secret in the `kubermatic` namespace (named `credential-<Provider>-<ID>`), and it's synced by the `cluster-credentials-controller` (https://github.com/kubermatic/kubermatic/tree/main/pkg/controller/seed-controller-manager/cluster-credentials-controller).

The secret in the cluster namespace (`cloud-credentials`) is not updated because the controller only listens to `Cluster` changes. It is necessary to restart the seed-controller-manager (or wait until the next periodic reconcile, which can be hours away) to update the secrets.

### Expected behavior

- The `cloud-credentials` Secret should be automatically synced from the `credential-` (in the `kubermatic` namespace one.
- Components that use the `cloud-credentials` Secret (to set environment variables, for example) should be automatically restarted.

### How to reproduce the issue?

1. Create a cluster
2. Find the `credential-` Secret as referenced in `spec.cloud` of the `Cluster` object
3. Update this secret
4. Observe the `cloud-credentials` Secret in the cluster namespace not changing unless you restart the seed-controller-manager

### How is your environment configured?

- KKP version:  `main`
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

**Comment by judge-red** [comment]
Just reporting my findings because I've recently looked into credentials rotation as well.

It seems that while the cloud credentials secret is the source of truth, we're not supposed to update it directly. Instead, add the new credentials to the Cluster resource, which will both update the cloud credentials secret and roll it out. Except not everything is restarted, see my bug report #13670.
