### ISSUE TITLE
User cluster deletion for kubevirt provider - Test Release 2.26

### ISSUE THREAD

**Issue by akash-gautam** [kubermatic/kubermatic#13643]
Test ticket for the changes made in https://github.com/kubermatic/kubermatic/pull/13635

Steps:
1. Create a user cluster with kubevirt on a KKP setup where kubevirt provider and KKP seed are the same cluster.
2. Enable etcdbackups for the user cluster and ensure a few backps are taken.
3. Delete the cluster, the cluster deletion should complete without complaing that it's stuck at etcdbackup cleanup.

**Comment by ahmedwaleedmalik** [comment]
> Create a user cluster with kubevirt on a KKP setup where kubevirt provider and KKP seed are the same cluster.

Had to hack my way around this a bit, tested it and it works fine.

/close
