### ISSUE TITLE
Default applications retain enforce, default, selector values after KKP upgrade - Test Release 2.26

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13658]
## Steps

1. Pick any application from https://github.com/kubermatic/kubermatic/tree/main/pkg/ee/default-application-catalog/applicationdefinitions and configure all of the following fields
    - spec.Default
    - spec.Enforced
    - spec.Selector
2. Perform a KKP upgrade; this re-installs the default application catalog
3. Ensure that the configured values are not overridden

/milestone KKP 2.26

**Comment by xrstf** [comment]
Cannot test this. The 3 fields mentioned in the ticket do not exist in KKP 2.25.x.
