### ISSUE TITLE
Migration from machine-controller userdata to OSM after KKP upgrade - Test Release 2.26

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13660]
## Steps

1. Install KKP 2.25 and create a working environment
2. Create 2-3 clusters on different cloud providers with OSM disabled
3. Upgrade to KKP 2.26
4. Ensure the following for each cluster:
   1. OSM is deployed
   2. Default OSPs are deployed
   3. MachineDeployments have the annotation `k8c.io/operating-system-profile` set to the name of the operating system profile
   4. OSCs exist against all the machine deployments
   5. Scale the existing machine deployment up by 1
   6. Ensure that the new machine is created and joins the cluster

### Disabling OSM for clusters

OSM can be disabled during cluster creation from UI:

![Screenshot 2024-09-03 at 12 25 46](https://github.com/user-attachments/assets/9aa84274-96fe-41a5-adae-5d915568e53d)
   
## References
- https://github.com/kubermatic/kubermatic/pull/13659/
- https://github.com/kubermatic/kubermatic/issues/13402

/milestone KKP 2.26

**Comment by xrstf** [comment]
Tested against DigitalOcean and Hetzner, works as expected.
