### ISSUE TITLE
flatcar-linux-update-operator 0.7.3 does not have ARM support

### ISSUE THREAD

**Issue by ealogar** [kubermatic/kubermatic#13662]
### What happened?

The version 0.7.3 that KKP is deploying for flatcar-linux-update-operator does not have ARM support.
However there are two new versions 0.8.0 and 0.9.0 who has.

### Expected behavior

deploy a operator with supports ARM as the rest of kkp components
Provide an option to remove it via addon configs, ...

### How to reproduce the issue?

Create a machinedeployment with an ARM machine

### How is your environment configured?

- KKP version: 2.25.3
- Shared or separate master/seed clusters?: shared

### What cloud provider are you running on?
AWS

### What operating system are you running in your user cluster?
flatcar

### Additional information

When 
```yaml
   operatingSystemSpec:                                                                                                                                                                                       
      disableAutoUpdate: true
```
is set, update the nodeSelector in daemonset to ignore that nodes to schedule a new pod of the server.

**Comment by xrstf** [comment]
> When `ooperatingSystemSpec.disableAutoUpdate=true` is set, update the nodeSelector in daemonset to ignore that nodes to schedule a new pod of the server.

Can you elaborate? I don't quite understand.

**Comment by ealogar** [comment]
> > When `operatingSystemSpec.disableAutoUpdate=true` is set, update the nodeSelector in daemonset to ignore that nodes to schedule a new pod of the server.
> 
> Can you elaborate? I don't quite understand.

if the disableAutoUpdate is in place, the xxx-update-operator shouldnt be doing anything and It might be a good idea to directly not deploy it in the clusters. One way of doing it (maybe tricky :d ) is to change the nodeSelector to something that is never gonna be scheduled because any node has the label.....

**Comment by xrstf** [comment]
Hm this would be difficult to achieve. The `disableAutoUpdate` flag is on a Machine object, not a Node, but the controller works purely based on nodes (so it also works when something other than the machine-controller is used to create the nodes). There is nothing really on a Node object that would indicate whether updates are disabled.
