### ISSUE TITLE
VPA Adminssion controller pdb prevents node-rotation

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#13697]
### What happened?

Very similar to #13493, if VPA feature gate is enabled and if we try to rotate the machine deployment for the seed, one node from old machine deployment gets stuck. Specifically, the node which is running vpa-admission-controller pod cannot get cordoned and removed until we kill that pod pod manually.

### Expected behavior

Just like all the other pods, VPA admission controller pod should also get evicted from old node and moved to new node. The old node then can get recycled.

### How to reproduce the issue?

1. enable VerticalPodAutoscaler FeatureGate in KubermaticConfiguration
2. verify that you have vpa-admission-controller pod running
3. force restart the machine deployment / upgrade k8s version so that MD gets rotated.
4. wait for all old nodes to get removed.
5. Observe that one old node remains where vpa-admission-controller pod is running

### How is your environment configured?

- KKP version: 2.25.6
- Shared or separate master/seed clusters?: shared and dedicated

### What cloud provider are you running on?
Azure, VSphere

### What operating system are you running in your user cluster?
Ubuntu 22.04

**Comment by judge-red** [comment]
This has been fixed in 2.25.7 through #13515

**Comment by dharapvj** [comment]
Aah! thank you there! I didn't realize it is already fixed.

/close
