### ISSUE TITLE
Baremetal cluster provisioning and upgrading - Test Release 2.26

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#13715]
## General Instructions

Run [kubermatic/infra/blob/main/clusters/kkp-qa-env/conformance-tester.sh](https://github.com/kubermatic/infra/blob/main/clusters/kkp-qa-env/conformance-tester.sh) like `PROVIDERS=baremetal conformance-tester.sh`.

## Checklist

```[tasklist]
### Supported Operating Systems
- [ ] Ubuntu
```

```[tasklist]
### Supported Kubernetes Versions (use latest patch releases available)
- [ ] v1.28
- [ ] v1.29
- [ ] v1.30
- [ ] v1.31
```

```[tasklist]
### Upgrades
- [ ] Upgrade from v1.28.x -> v1.29.x
- [ ] Upgrade from v1.29.x -> v1.30.x
- [ ] Upgrade from v1.31.x -> v1.31.x
```

**Comment by ahmedwaleedmalik** [comment]
Update: With KKP 2.26, we are only going to support `Ubuntu` with Baremetal provider.
