### ISSUE TITLE
vSphere CCM and CSI components fail to pull their images from `gcr.io/cloud-provider-vsphere`

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#13719]
### What happened?

vSphere user clusters fail to pull container images for CCM and CSI components, so CSI Pods within the user cluster and CCM Pods in the cluster control plane namespace fail to start. These images were all hosted in `ghcr.io/cloud-provider-vsphere`, which has apparently been deleted in the last few hours:

```
$ skopeo inspect docker://gcr.io/cloud-provider-vsphere/csi/release/driver:v3.3.1
FATA[0000] Error parsing image name "docker://gcr.io/cloud-provider-vsphere/csi/release/driver:v3.3.1": unable to retrieve auth token: invalid username/password: denied: Project cloud-provider-vsphere has been deleted.
```

While CCM has a new location (see https://github.com/kubernetes/cloud-provider-vsphere?tab=readme-ov-file#container-images), CSI drivers were never published to another registry.

### Expected behavior

vSphere user clusters work.

### How to reproduce the issue?

- Create or upgrade any vSphere user cluster.
- Add new machines to a vSphere user cluster.

### How is your environment configured?

- KKP version: ALL AFFECTED
- Shared or separate master/seed clusters?: N/A

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

vSphere

### What operating system are you running in your user cluster?

N/A

### Additional information

I've asked upstream about this: https://kubernetes.slack.com/archives/C9PGCDKV5/p1726572676507989

**Comment by embik** [comment]
We are working on a ASAP fix for our users and customers and are looking into options to make these component images available.

**Comment by embik** [comment]
Upstream report: https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/3053

**Comment by hexchen** [comment]
ftr, the CSI seems to be here now: https://github.com/kubernetes-sigs/vsphere-csi-driver/commit/36f196356c17d97e6fb3a48821735c4dd5a3d410

**Comment by embik** [comment]
@hexchen Yes, upstream seems to be publishing new image builds into that repository, but the oldest image there is from September 3rd and is built for this commit: https://github.com/kubernetes-sigs/vsphere-csi-driver/commits/ea2b91cb. So future releases might be available from there, but currently no release build (i.e. stable enough for us to ship in KKP) is available from there unfortunately.

**Comment by blackbaddl13** [comment]
We are also having issues with the following two components here in this context apart from the CCM

gcr.io/cloud-provider-vsphere/csi/release/driver
gcr.io/cloud-provider-vsphere/csi/release/syncer

**Comment by embik** [comment]
> We are also having issues with the following two components here in this context apart from the CCM
> 
> gcr.io/cloud-provider-vsphere/csi/release/driver gcr.io/cloud-provider-vsphere/csi/release/syncer

Those are images used by the CSI driver. They are affected by the same problem (compounded by the fact that there is currently no upstream location for CSI driver releases that is available).

**Comment by blackbaddl13** [comment]
> > We are also having issues with the following two components here in this context apart from the CCM
> > gcr.io/cloud-provider-vsphere/csi/release/driver gcr.io/cloud-provider-vsphere/csi/release/syncer
> 
> Those are images used by the CSI driver. They are affected by the same problem (compounded by the fact that there is currently no upstream location for CSI driver releases that is available).

@embik Yes we are aware of that. Just wanted to mention that here. Found during debugging that these seem to be the only two other images which are affected by that. All other images were moved to registry.k8s.io quite some time ago apparently

**Comment by embik** [comment]
This has been fixed in:

- #13720
- #13721
- #13722
- #13724

Patch releases for KKP are available:

- [v2.23.19](https://github.com/kubermatic/kubermatic/releases/tag/v2.23.19)
- [v2.24.13](https://github.com/kubermatic/kubermatic/releases/tag/v2.24.13)
- [v2.25.9](https://github.com/kubermatic/kubermatic/releases/tag/v2.25.9)

If you are affected, please upgrade to the latest patch release of your respective release series. I'll go ahead and close this issue since it's been resolved, but it will probably stay pinned to the repository for a while longer for visibility.

/close
