### ISSUE TITLE
Implement Node HTTP Endpoint

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1371]
At the moment API allows to retrieve and modify `node` resources from the following endpoint
`/dc/{dc}/cluster/{cluster}/node`. 

In our new world all resources belong to `project` and this fact must be reflected in our API. Therefore in this issue we would like to define and implement a new endpoint.

Details:
The new endpoint: `v1/projects/{project_id}/dc/{dc}/clusters/{cluster}/node`
The new implementation must use the new `RBACCompliantClusterProvider` cluster provider.

child of #966

**Comment by kdomanski** [comment]
Before we can implement a new endpoint working as you describe, we should first have the new architecture where datacenters are per-project, which we still do not have, right?

**Comment by p0lyn0mial** [comment]
> Before we can implement a new endpoint working as you describe, we should first have the new architecture where datacenters are per-project, which we still do not have, right?

At the moment a datacenter is not a resource, so the answer is no. But the `clusters` were implemented as resources that belong to project.

**Comment by kdomanski** [comment]
So multiple projects can use the same datacenter, right?

**Comment by p0lyn0mial** [comment]
> So multiple projects can use the same datacenter, right?

Yes,  but in general we use datacenters to specify how to interact with the clusters.

**Comment by p0lyn0mial** [comment]
closed by:https://github.com/kubermatic/kubermatic/pull/1576
