### ISSUE TITLE
Remove leftover images sourced from repositories at `gcr.io`

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#13723]
### Description

`gcr.io` will be shut down eventually (see [this GCP documentation](https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown)) and we are in active incident (#13719) with it. We should make sure we eliminate the last few image references that still use `gcr.io` images. For the most part, there should be new registry locations hosted by the Kubernetes project anyway.

### Solution details

- Remove all image references pulled in by KKP at runtime that use `gcr.io` and replace them with other upstream sources.
- Investigate whether distroless (used at build time) is staying on `gcr.io` and at risk of being shut down.

### Alternative approaches

N/A

### Use cases

N/A

**Comment by xrstf** [comment]
distroless so far seems to have made no statements regarding its future home.

etcd seems to stay on gcr (GCR was introduced in https://github.com/etcd-io/etcd/pull/8932 to supersede quay.io), the latest release plannings in https://github.com/etcd-io/etcd/issues/18013 mention pushing things to the Artifacts Registry, which will be the GCR backend after May 2025 according to https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown.

**Comment by xrstf** [comment]
distroless will stay with a gcr.io address: https://github.com/GoogleContainerTools/distroless/issues/1612#issuecomment-2208717851
