### ISSUE TITLE
Applications - Test Release 2.26

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13745]
We need to test Applications thoroughly because of the various issues that we are encountering recently.

- [x] Initial applications are working
- [x] Applications created after cluster creation have the correct namespace, values, and are properly installed
- [x] Default applications are installed for new clusters
- [x] Enforced applications are installed for all cluster, updating applicationDefinition updates the applicationInstallation for all clusters
- [x] Enforced/Default application with datacenter selector
- [ ] Deletion of applications works fine and namespaces are also cleaned up
- [ ] Not sure what other scenarios can be tested...

These tickets/PRs also need to be tested:
- https://github.com/kubermatic/kubermatic/issues/13742
- https://github.com/kubermatic/kubermatic/pull/13746
- https://github.com/kubermatic/kubermatic/pull/13743
- https://github.com/kubermatic/kubermatic/pull/13741
- https://github.com/kubermatic/kubermatic/pull/13121

For dashboard we tested the defaulting/enforcement functionality with https://github.com/kubermatic/dashboard/issues/6788

/milestone KKP 2.26

**Comment by ahmedwaleedmalik** [comment]
cc @csengerszabo someone needs to pick this and rest of the testing tickets as well

**Comment by ahmedwaleedmalik** [comment]
Would be nice if we can wait for https://github.com/kubermatic/kubermatic/pull/13746 before starting this ticket. Since those changes should also be tested against this ticket as already mentioned in the ticket description.

**Comment by cnvergence** [comment]
hi @ahmedwaleedmalik, I will also add this one https://github.com/kubermatic/kubermatic/pull/13121

**Comment by xrstf** [comment]
> Deletion of applications works fine and namespaces are also cleaned up

This doesn't work for me. I created a usercluster and selected nginx as one of the initial apps. Once the cluster was up and running and had nodes, I `kubectl -n nginx delete appinstall nginx`. The AppInstall was then gone, but the namespace still remained.

**Comment by xrstf** [comment]
After having talked with Waleed, we agreed that the item from the list above was misleading. We do not actually want the namespace to be deleted when the AppInstall is deleted.

Given that, all items on the list are complete and this ticket is also complete.
