### ISSUE TITLE
CoreDNS Resource Overwrites - Test Release 2.26

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#13756]
This is about testing https://github.com/kubermatic/kubermatic/pull/13409

### Test Plan

1. Create a usercluster in KKP.
2. get the seed's kubeconfig
3. `kubectl edit` the Cluster object:
   1. Set `spec.clusterNetwork.coreDNSReplicas`  and observe if it influences the CoreDNS deployment in the usercluster.
   2. Try to also set `spec.componentsOverride.coreDNS.replicas` -> KKP webhook should reject it
   3. Replace old config option (step 1) with new one (step 2) -> observe that the new flag also influences the CoreDNS deployment.
   4. Also set some resource constraints for CoreDNS and observe if they are applied to the CoreDNS deployment.

**Comment by ahmedwaleedmalik** [comment]
## ✅ Configuring Core DNS replicas

### Cluster spec

![Image](https://github.com/user-attachments/assets/f14af32c-004c-4474-adf2-0859cb638b4b)

### Deployment in user cluster

![Image](https://github.com/user-attachments/assets/6946ea65-6adf-474a-a61c-0d357c5b7051)


## ❌ Try to also set spec.componentsOverride.coreDNS.replicas -> KKP webhook should reject it

Was edited without the webhook blocking it.

![Image](https://github.com/user-attachments/assets/0b55079b-95ea-496f-a64f-5066eefa0c02)

**Comment by xrstf** [comment]
I'm taking a look

**Comment by xrstf** [comment]
Hm the webhook works fine for me.

> error: clusters.kubermatic.k8c.io "tff9p6nx9q" could not be patched: admission webhook "clusters.kubermatic.io" denied the request: spec.componentsOverride.coreDNS.replicas: Invalid value: 4: both the new spec.componentsOverride.coreDNS.replicas and deprecated spec.clusterNetwork.coreDNSReplicas fields are set

**Comment by ahmedwaleedmalik** [comment]
> Hm the webhook works fine for me.
> 
> > error: clusters.kubermatic.k8c.io "tff9p6nx9q" could not be patched: admission webhook "clusters.kubermatic.io" denied the request: spec.componentsOverride.coreDNS.replicas: Invalid value: 4: both the new spec.componentsOverride.coreDNS.replicas and deprecated spec.clusterNetwork.coreDNSReplicas fields are set

I'll give it another go tomorrow then but it didn't work at all for me.

**Comment by xrstf** [comment]
Any updates? If it helps, I first set the clusterNetwork.coreDNSReplicas field and then the one in the components override.

**Comment by ahmedwaleedmalik** [comment]
It seems to be working now, but now I'm a bit worried as to why it didn't work earlier. Because I tried the exact same thing previously as well. Anyways, we can close this testing ticket.

![Image](https://github.com/user-attachments/assets/0a2a4465-221d-4f4d-84d4-02e122b839a2)


/close
