### ISSUE TITLE
Test cluster-autoscaler - Test Release 2.26

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#13753]
This is about testing the functionality of the `cluster-autocaler` **addon**.

### Testing Plan

* create a usercluster with KKP
* ensure the cluster has some nodes in it, managed by a MachineDeployment
* install the cluster-autoscaler **addon**
* observe that the autoscaler pods become ready and detect the nodes properly

**Comment by akash-gautam** [comment]
Created a user cluster with min/max replicas specified for the md & deployed cluster-autoscaler addon.

Cluster autoscaler detects the md/nodegroup
```
clusterapi_provider.go:68] discovered node group: MachineDeployment/kube-system/loving-poincare (min: 1, max: 3, replicas: 3)
```
Created a deployment with high CPU request to make the pod go in pending state which triggered a scale up 
```
Events:
  Type     Reason            Age   From                Message
  ----     ------            ----  ----                -------
  Warning  FailedScheduling  27s   default-scheduler   0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
  Normal   TriggeredScaleUp  20s   cluster-autoscaler  pod triggered scale-up: [{MachineDeployment/kube-system/loving-poincare 1->2 (max: 3)}]
```
Deleted the deployment after scale up, cluster autoscaler marked the node as "unneeded" & removed it after sometime.
```
nodes.go:84] loving-poincare-548dc9478d-k5h8n is unneeded since 2024-09-24 10:53:21.547786564 +0000 UTC m=+1019.093887011 duration 6m12.756299305s
```
