### ISSUE TITLE
Test OpenStack lb-method/lb-provider - Test Release 2.26

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#13754]
This is about testing #13574.

### Testing Plan

1. Configure an OpenStack datacenter with `loadBalancerProvider` and `loadBalancerMethod` configured.
2. Create a usercluster using this datacenter.
3. Check if the generated cloud-config contains `lb-method` and `lb-provider`.

**Comment by ahmedwaleedmalik** [comment]
Works as expected:

### CCM
![CCM](https://github.com/user-attachments/assets/623ae8de-cbf1-4ab2-8341-e1d97625eec2)

### CSI
![CSI](https://github.com/user-attachments/assets/7bcd335c-69c1-41a5-8511-22b2ca115cfe)

### DC configuration
![dc](https://github.com/user-attachments/assets/ec3118c4-1fcf-445c-977c-bfb0c1fb6ed2)

/close
