### ISSUE TITLE
Test single-namespace mode for KubeVirt - Test Release 2.26

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#13752]
This ticket is about testing

* https://github.com/kubermatic/kubermatic/pull/13552
* https://github.com/kubermatic/kubermatic/pull/13614

**Comment by cnvergence** [comment]
Test scenario:

1. Enable namespacedMode for the KubeVirt datacenter in the seed
Modify seed resource and add this configuration under kubevirt datacenter
```bash
namespacedMode:
  enabled: true
  name: infra-ns
```
2. Deploy multiple Kubevirt user-clusters
3. Confirm that cluster creation is successful and all of the KubeVirt resources are deployed in the single namespace

**Comment by akash-gautam** [comment]
Enabled namespaced mode and created a couple of kubevirt user clusters. On kubevirt provider cluster resources (pods) for both the user cluster got created in the `infra-ns` namespace.
/close
