### ISSUE TITLE
CNI none still tries to reconcile cilium addon

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13760]
### What happened?

On creating a cluster with CNI set to none, there are events regarding reconciliation for cilium addon failing:

<img width="1204" alt="Screenshot 2024-09-24 at 10 32 31" src="https://github.com/user-attachments/assets/51a7525a-cccf-430e-b1c8-7e56313ce3c2">

### Expected behavior

Cilium addon is not required and should never be reconciled/processed when CNI is set t `none`.

### How is your environment configured?

- KKP version: QA environment on [v2.26.0 (Beta 2)](https://github.com/kubermatic/kubermatic/releases/tag/v2.26.0-beta.2)
- Shared or separate master/seed clusters?: N/A

**Comment by ahmedwaleedmalik** [comment]
/milestone KKP 2.26

@csengerszabo this should _ideally_ be fixed in KKP 2.26. I'm not sure if the bug exists in previous versions of KKP as well. Will leave the priority, whether it's fixed for 2.26, etc. upto you.

**Comment by judge-red** [comment]
Can't reproduce this on 2.25.11. But what got my curiosity is that it says addon ... isn't the Cilium CNI a system application nowadays? Or is this a UC with some old Kubernetes version where it was still an addon? (I tested with 1.29.9)

**Comment by xrstf** [comment]
In 2.25 we still had a cilium addon, but 2.26 doesn't anymore. We simply forgot to also remove it from the defaultAddons list in the defaulting code for KubermaticConfigurations.
