### ISSUE TITLE
Write e2e tests for seed-installer

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1381]
What the test should cover:
- Create temporary keypair in the beginning
  - This should be deployed onto every node
- Create 6 Nodes on OpenStack (Use terraform here)
  - We'll use 3 masters & 3 worker nodes
  -  1 Core & 4GB memory
  - Everyone gets a floating IP
- Provision
  - Use our seed-installer to provision the nodes
- Testing
  - Run conformance tests
  - Create a StorageClass which utilizes some cinder storage
  - Deploy the storage-test https://github.com/kubermatic/kubermatic/blob/master/config/test/storage-test.yaml
  - Verify that the pod started successfully

**Comment by alvaroaleman** [comment]
Which Openstack are we going to use for this?

**Comment by mrIncompetent** [comment]
Simon from Syseleven said we can use their OpenStack

**Comment by pkavajin** [comment]
Test OS: Ubuntu

**Comment by alvaroaleman** [comment]
The basic scaffolding (Creating instances, executing seed installer, cleaning up) was done in kubermatic/kubermatic-installer#44

What is still missing here:

* [ ] Run conformance tests
* [ ] Create a Storageclass which utilizes some cinder storage
* [ ] Deploy the storage-test https://github.com/kubermatic/kubermatic/blob/master/config/test/storage-test.yaml
* [ ] Verify that the pod started successfully
