### ISSUE TITLE
Unexpected Storage Classes deployed on UCs

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#13887]
### What happened?

I think this only happens on OpenStack, but didn't check all the other csi addons.

The storage class(es) that get pre-installed in a UC are supposed to come from the `default-storage-class` addon afaik. And this works. On OpenStack, the storage class `cinder-csi` for the Cinder CSI provisioner is installed. However, the OpenStack CSI driver installs two more storage classes, `csi-cinder-sc-delete` and `csi-cinder-sc-retain`. See:

```
$ k get storageclasses.storage.k8s.io 
NAME                   PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
cinder-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   27d
csi-cinder-sc-delete   cinder.csi.openstack.org   Delete          Immediate              true                   27d
csi-cinder-sc-retain   cinder.csi.openstack.org   Retain          Immediate              true                   27d
```

imho this is undesired and leads to confusion with the end user. Also, while it's simple to just replace the `default-storage-class` addon, or to not deploy that addon at all (but maybe a `custom-storage-class` addon instead), the csi/openstack addon is way more complicated or at least a considerably bigger hassle to change.

So on our UCs, it currently looks like this:

```
$ k get storageclass
NAME                                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-cinder-sc-delete                     cinder.csi.openstack.org   Delete          Immediate           true                   19m
csi-cinder-sc-retain                     cinder.csi.openstack.org   Retain          Immediate           true                   19m
switch-cloud-performance-delete          cinder.csi.openstack.org   Delete          Immediate           true                   19m
switch-cloud-performance-retain          cinder.csi.openstack.org   Retain          Immediate           true                   19m
switch-cloud-standard-delete (default)   cinder.csi.openstack.org   Delete          Immediate           true                   19m
switch-cloud-standard-retain             cinder.csi.openstack.org   Retain          Immediate           true                   19m
```

Our storage classes set a `type` (called volume type in OpenStack), which the ones from the driver don't (and shouldn't).

And again, I think no other csi addon installs any storage classes.

### Expected behavior

Don't installed storage classes into UCs other than those of the addon.

### How to reproduce the issue?

Deploy a UC on OpenStack, I guess

### How is your environment configured?

- KKP version: 2.26.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

N/A

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

N/A

### Additional information

Related code (storage classes):
- https://github.com/kubermatic/kubermatic/blob/release/v2.26/addons/default-storage-class/snapshot-class.yaml#L18-L25
- https://github.com/kubermatic/kubermatic/blob/release/v2.26/addons/csi/openstack/driver.yaml#L57-L71

**Comment by ahmedwaleedmalik** [comment]
@judge-red we'll fix the bug and it'll be backported to 2.26 as well, thanks for pointing it out.
