### ISSUE TITLE
Write tool for parsing release notes from closed PR's

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1400]
We need a CLI tool which generates release notes based on a specific text from PR's.

### PR's
Each PR must have a specific text in the PR description:
```
release-notes: foo-bar
```
This text must be extracted and will be taken as release note.

### CLI
CLI arguments:
- `from-tag`
- `to-tag`

Based on the inputs the tool will collect all PR's which where made between `from-tag` & `to-tag`.
The tool must validate that both tags were made on the same branch.

**Comment by alvaroaleman** [comment]
What about PRs with no release note, e.G. for refactorings?

**Comment by mrIncompetent** [comment]
I would propose:
```
release-notes: None
```
as special keyword. The tool would then ignore the PR

**Comment by alvaroaleman** [comment]
SFTM

**Comment by mrIncompetent** [comment]
Maybe we have a solution with https://github.com/github-changelog-generator/github-changelog-generator

**Comment by cbrgm** [comment]
https://github.com/cbrgm/gchl (I can change the repository to kubermatic intern if you wish)

Usage: `gchl between [branch/tag] [branch/tag]` to list all merged PRs between two references

You can use `gchl between [branch/tag] [branch/tag] --release-notes` to list all merged PRs between two references using `release-notes` from PR message annotation

**Comment by mrIncompetent** [comment]
Must be put into the kubermatic ogranization.
Work you do for Loodse belongs to Loodse. Never simply put your work open source without asking first.

Please put code in https://github.com/kubermatic/gchl

**Comment by cbrgm** [comment]
Deleted the public repo. PR can be found [here](https://github.com/kubermatic/gchl/pull/1)
