### ISSUE TITLE
Document on how to run the kubernetes conformance tests

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1401]
### Current state
We have a script called `seed-installer` which creates a kubernetes cluster. 
We use this cluster as seed-cluster for kubermatic.

### Problem
As environments differ, each seed-cluster might have issues caused by the environment & the configuration.

### Desired state
Document on how to run the kubernetes conformance tests.
It must be easy for a customer to run those against any cluster.

**Comment by kron4eg** [comment]
@mrIncompetent https://scanner.heptio.com/ is pretty convenient :)

**Comment by mrIncompetent** [comment]
Feel free to put some sentences in github.com/kubermatic/docs ;)

**Comment by xrstf** [comment]
@mrIncompetent Is this required anymore given that we now have KubeOne?

**Comment by mrIncompetent** [comment]
I don't think so.
