### ISSUE TITLE
Add metrics for etcd backups (S3)

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1407]
### Current state
For each user-cluster a CronJob exists, which is responsible for creating a snapshot of the user-cluster etcd & afterwards to store it.
The whole storing of the snapshot is highly configurable.
Proposal: https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/etcd-backup.md

By default we offer a chart for Minio & provide a Store-Container which supports storing to S3.

### Problem
We have no monitoring in place for the backups.

### Desired state
We have monitoring in place for the backups.
Ideally we have some kind of S3 exporter as this is the default solution.
Using a minio exporter might be too limited, as customers probably wan't to use a custom out-of-cluster S3 solution.

### Scope
This issue just focuses on getting the exporter in place.
Alerts & Dashboards should be done in separate issues

**Comment by pkavajin** [comment]
Track fileage + filesize

**Comment by kron4eg** [comment]
There is another possibility: utilize https://github.com/kubernetes/kube-state-metrics and alert on failing cronjobs.
Relevant blogpost: https://medium.com/@tristan_96324/prometheus-k8s-cronjob-alerts-94bee7b90511

**Comment by alvaroaleman** [comment]
Yep and we already have alerts on that (AFAIK). That does however not cover everything, e.G. cronjobs not getting created
