### ISSUE TITLE
kube-bench kubelet issues

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#1425]
child of #1424

* [ ] --allow-privileged argument is set to false
* [ ] --anonymous-auth argument is set to false
* [ ] --read-only-port argument is set to 0
* [ ] --streaming-connection-idle-timeout argument is not set to 0
* [ ] --protect-kernel-defaults argument is set to true
* [ ] --make-iptables-util-chains argument is set to true
* [ ] --keep-terminated-pod-volumes argument is set to false
* [ ] --hostname-override argument is not set
* [ ] --event-qps argument is set to 0
* [ ] --tls-cert-file and --tls-private-key-file arguments are set as appropriate
* [ ] RotateKubeletClientCertificate argument is set to true
* [ ] RotateKubeletServerCertificate argument is set to true

**Comment by mrIncompetent** [comment]
> --allow-privileged argument is set to false

This will break all clusters as we run Canal as Daemonset.

> --anonymous-auth argument is set to false

Needed for the kubeadm discovery.

**Comment by kron4eg** [comment]
Moved to kubermatic/machine-controller#258
