### ISSUE TITLE
Investigate machine-controller deletion issue

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1437]
### Problem

In some situations it seems the machine-controller is not aware that the machine-resources do have the deletionTimestamp set.

This leads to machines not being deleted.
Instead if you manually delete the instance at Digitalocean, the machine-controller will automatically recreate it.

It seems the machine-controller is not using the up-to-date information, although we're using an informer.

### Update

As this could not be reproduced in a reasonable time, we'll add metrics & alerts to get notified when this happens again.

### Acceptance criteria
- [ ] have metrics in place for the machine-deletion timestamp
- [ ] have a alerting rule in place which alerts if a machine is in deletion for more than 30min

**Comment by metalmatze** [comment]
I have created a PR:
https://github.com/kubermatic/machine-controller/pull/270

**Comment by kdomanski** [comment]
could it be related to kubermatic/machine-controller/issues/269 ?

**Comment by alvaroaleman** [comment]
@kdomanski No. As mentioned in Slack I did a debug build of the machine-controller that prints the machines as it sees them. The machine-controller got a version that had a very old `resourceVersion` and no `deletionTimestamp` set. So the machine-controller did exactly what it was supposed to do: nothing.

Restarting the apiserver always fixed the issue. We have however no idea how the apiserver got in this broken state in which it would serve old versions to clients that use the client-go caching.

**Comment by alvaroaleman** [comment]
We can currently not reproduce this, but have an alert in place in case this happens again.

Closing this ticket as not reproducible, we will create another ticket if this happens again.

**Comment by mrIncompetent** [comment]
We're not been able to reproduce the issue.
We introduced alerts to get notified when a machine cannot get deleted.
Also we enabled authentication on the apiserver, so connections to different apiserver should not happen as well. 
If this happens again,a  new issue should be created
