### ISSUE TITLE
unused vendor/github.com/vmware/govmomi/simulator

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1440]
`dep ensure -v` removes the `vendor/github.com/vmware/govmomi/simulator` package it seems.

So this is probably not used any more but somewhere we lost doing the vendor update?

Should we catch that in ci pipeline somehow? A build process which removes files which are in git sounds a bit wrong to me...

**Comment by mrIncompetent** [comment]
Instead of running `dep status` in drone we could run `dep ensure` & diff against whats in git.

We already do a diff for the swagger-spec & codegen.

WDYT? @thz

**Comment by kdomanski** [comment]
Huh
https://github.com/kubermatic/kubermatic/blob/99d9015b39740982d8dd51199424042faa3c23a4/api/pkg/handler/vsphere_test.go#L11
