### ISSUE TITLE
User cannot be created invalid: metadata.labels

### ISSUE THREAD

**Issue by frittenlab** [kubermatic/kubermatic#1442]
One of our customers cannot create any clusters. After logging in to the dashboard via the openstack authentication he receives this error:  

`
"User.kubermatic.k8s.io "user-dtql6" is invalid: metadata.labels: Invalid value: "-rRUWaeIDhikDyrv3-IACPqmfXc": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"
`

The user does not get created. It looks like a problem with the labels for the  id field.

**Comment by bashofmann** [comment]
We have a second user now reporting this problem.

**Comment by bashofmann** [comment]
Any chance of getting this patch released sometime this week?

**Comment by cbeneke** [comment]
Updated and tested, works like a charm. Thanks!
