### ISSUE TITLE
Prepare Kibana Helm Charts

### ISSUE THREAD

**Issue by guusvw** [kubermatic/kubermatic#1459]

**Comment by kdomanski** [comment]
Requires more detail

**Comment by toschneck** [comment]
Is this related to #1460?

**Comment by pkavajin** [comment]
@pkavajin Talk to guus about this one.

**Comment by pkavajin** [comment]
After talking about this with @guusvw we're fine with the existing kibana helm chart we have in kubermatic, therefore i'll close this issue.
