### ISSUE TITLE
Vsphere: Make folder configurable per cluster

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1461]
Currently the vsphere folder is set via the `datacenters.yaml`, it should be possible to overwrite it via the UI.

**Comment by mrIncompetent** [comment]
@alvaroaleman Is this still relevant / useful ?

**Comment by alvaroaleman** [comment]
It may be sort-of nice but I don't think it has a high priority as the cloudifire ppl never contacted us again about it.

**Comment by mrIncompetent** [comment]
@kdomanski anything against changing the prio to low?

**Comment by kdomanski** [comment]
Done.

**Comment by toschneck** [comment]
@alvaroaleman I have something in my mind, that this was also something SHAW requested. Is it still needed by them?

**Comment by alvaroaleman** [comment]
@toschneck not sure, we have to ask them
