### ISSUE TITLE
Configure Ceph RBD dynamic storage provisioner for user clusters

### ISSUE THREAD

**Issue by guusvw** [kubermatic/kubermatic#1462]
We want to use our existing Ceph setup for providing persistent storage to our user clusters. We need to figure out a way to configure StorageClass resources on newly provisioned clusters.

CloudiFire-Ref: https://github.com/CloudiFire/caas/issues/30

**Comment by pkavajin** [comment]
@guusvw add proposal link.

**Comment by guusvw** [comment]
https://github.com/CloudiFire/docs/pull/39

**Comment by mrIncompetent** [comment]
@guusvw @kdomanski Is this still relevant?

**Comment by guusvw** [comment]
@mrIncompetent I don't think so, could be closed from my POV, otherwise we can re-create a new issue
