### ISSUE TITLE
Define interesting metrics which could be visualized in the Kubermatic UI dashboard 

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1464]
### Current state

The kubermatic api offers an endpoint which calls the prometheus running inside the cluster-namespace.
This has been implemented to eventually display metrics in the kubermatic dashboard.

### Desired state
Though having the endpoint, we need to find metrics from the master-components which would be interesting

Child of #1158

**Comment by xrstf** [comment]
@kdomanski Please define things you would like to visualize in the dashboards and then seed team can find out if there are already metrics for this.

**Comment by kdomanski** [comment]
@mrIncompetent Little help here? I don't remember the context.

**Comment by mrIncompetent** [comment]
We have functionality in the APIserver to expose metrics for the Dashboard.
It would be a great user experience if the user could see some basic metrics about the cluster, like Utilization, number of pods, number of nodes, etc.

So this issue is mostly about thinking of interesting metrics a user could find helpful.
Users typically love dashboards
