### ISSUE TITLE
Vsphere: Allow configuring a dedicated user for the cloud provider functionality in the UI

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1470]
We currently use the same user for both the virtual machine creation and the cloud provider functionality in vsphere.

It should be possible to configure a dedicated user just for the cloud provider functionality, i.E. the variables that are set in the the machine-controller and controller-manager deployment. This will allow to create vsphere clusters on which the end user can not see the vsphere user that is used to CRUD virtual machines.

**AC:**

* [x] A vsphre user that is used just for the cloud-provider functionality and not for the instance creation can be configured on a per-cluster level

**Comment by kdomanski** [comment]
@alvaroaleman  please create a story for the UI part

**Comment by alvaroaleman** [comment]
This was added via #1592
