### ISSUE TITLE
Define Viewer role

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1474]
Access to all resources exposed by our API will be restricted by the group the user belongs to. 

So far we have defined `Owner` and `Admin/Editor` groups which give the users ability to retrieve, write and modify resources. 

In this issue we would like to add a new role that would only allow to read the resources.

child of #966

**Comment by thz** [comment]
What is the difference between Owner and Admin/Editor?
Will read access to certain resources (secrets) imply write-access?

**Comment by p0lyn0mial** [comment]
`Admin/Editor`  represents the group name. At the moment the group is actually named `Admin` but some time ago we decided that we will change the name to `Editor`.

**Comment by p0lyn0mial** [comment]
> Will read access to certain resources (secrets) imply write-access?

I'm not sure what exactly do you mean by that. In general read access will allow to GET the resource. Any attempt to modify the resource `PUT`, `PATCH` will be rejected.

**Comment by p0lyn0mial** [comment]
> What is the difference between Owner and Admin/Editor?

At the moment the only difference is that `Admin/Editor` cannot delete the project. 
You may want also to have a look at https://docs.google.com/spreadsheets/d/1XDoCd1PUWqjkyDVx1cso2zQzkKeHf6BJXIVMk6Zd5uI/edit?ts=5b35d3f5#gid=0

ask @kgroschoff  in case you don't have access to that file.

**Comment by cbrgm** [comment]
Should the group be called `viewers` or `readers`? The title of this issue says viewers but in the spreadsheet they are called readers, that's the reason for asking :-)

**Comment by p0lyn0mial** [comment]
heh :) I'm fine with `viewers`. If that's okay with you please also update the spreadsheet.

**Comment by cbrgm** [comment]
Okay, I'll update the sheet :-)

**Comment by cbrgm** [comment]
See #1617
