### ISSUE TITLE
Implement machine-ipam-controller

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1475]
Implement the `machine-ipam-controller` according the proposal:
https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/machine-ipam-controller.md

Acceptance criteria:
- [ ] Implement machine-ipam-controller
Tests:
  - [ ] allocates IP from CIDR's
  - [ ] allocates IP from second CIDR's when first is full
  - [ ] fails when no free IP is left
  - [ ] re-uses a IP that has been released

**Comment by kdomanski** [comment]
I propose an additional test:
 - [ ] re-uses a IP that has been released

**Comment by mrIncompetent** [comment]
@kdomanski i updated the description

**Comment by pkavajin** [comment]
@mrIncompetent add story for ui

**Comment by mrIncompetent** [comment]
UI Issue: https://github.com/kubermatic/dashboard-v2/issues/712
