### ISSUE TITLE
Grafana Dashboards for Seed & Customer Clusters

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#1477]
Currently there's a Kubernetes folder in Kubermatic's Grafana that visualizes different metrics of the seed cluster.

In the future we'd like to have this split up into 2 folders. One for looking at the seed cluster metrics and one for the customer clusters. The dashboards for the customer cluster should have a dropdown where one can select the cluster to look at.

**Comment by xrstf** [comment]
For many things we now have dashboards that are flexible enough to gain insights into user clusters.
