### ISSUE TITLE
[AWS] Subnet Cluster Tag gets overridden

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1479]
The clustertag on the subnet kubermatic lives in gets overridden when a cluster gets added.

**Effects:**
* AWS Loadbalancers aren't attached to the instances (controller manager says: "Couldn't reconcile node routes: error listing routes: unable to find route table for AWS cluster: kubernetes")
* Probably all clusterprovider related Features for every except the last added cluster is fucked up badly.

**Steps to Reproduce:**
* Create a new Cluster on dev.kubermatic.io with AWS ClusterProvider
* Open up EC2 Dashboard and you'll see that the clustertags from the subnet got removed and a KubernetesCluster-Tag with the id of the last cluster as value was added

**Comment by mrIncompetent** [comment]
Can be reproduced as well just by creating 2 AWS user clusters with the same AWS account using dev.kubermatic.io?
