### ISSUE TITLE
Fix etcd member replacement

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1490]
### Current state

Each user-cluster has a etcd cluster managed by a statefulset: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/etcd/statefulset.go

### Problem

When having an initialized cluster, it is impossible to replace a member (in case a volume is corrupted for example).
When replacing the member, it won't join the cluster as it gets started with the `INITIAL_STATE=new`.

**Steps to replicate**
```bash
Scenario: Member etcd-2 is corrupted

1. Delete PVC:
kubectl -n cluster-xw99v4lt4g delete pvc data-etcd-2

2. Delete Pod:
kubectl -n cluster-xw99v4lt4g delete pod etcd-2

3. Get into one of the remaining etcd pods:
kubectl -n cluster-xw99v4lt4g exec -ti etcd-1 sh

  # Needed to use the etcd v3 api
  export ETCDCTL_API=3
  # List existing members in the etcd cluster
  etcdctl member list
  # Remove etcd member for etcd-2 (deleted/corrupted pod)
  etcdctl member remove 4b7b57f93f39cac1
  # Add etcd-2 as new member
  etcdctl member add etcd-2 --peer-urls=http://etcd-2.etcd.cluster-xw99v4lt4g.svc.cluster.local:2380
  # exit from pod

4. Restart etcd-2 pod
kubectl -n cluster-xw99v4lt4g delete pod etcd-2

# Now it won't join the cluster
```

### Acceptance criteria
- A etcd member can be replaced
  - [ ] new etcd node joins the cluster
  - [ ] data gets replicated
  - [ ] `etcdctl member list` shows 3 running & healthy members after joining
  - [ ] a test-script exists for the scenario (removing & rejoining)

**Comment by alvaroaleman** [comment]
Please also make it an AC to have a script for the test case so it is reproducible and reviewers can determine if that test is actually accurate.

**Comment by mrIncompetent** [comment]
This is not a bug. There's nothing we could sanely solve via code, its something to be handled in documentation.
Closed via https://github.com/kubermatic/docs/pull/45
