### ISSUE TITLE
kubermatic-e2e pipeline integration

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#1491]
As we now have automated Conformance testing (with help of kubermatic-e2e) merged and tested and with acceptable time run (~15-20 minutes), we need to integrate it to pipline run it **after every master merge**.

TODO plan:
* build kubermatic/kubermatic-e2e image
* create bunch of secrets in our drone with cluster/node specs combinations, each for different cloud we'd like to e2e test
* modify drone.yml to run kubermatic-e2e on top of dev/cloud environment **after** each deploy

**Comment by kron4eg** [comment]
reference: https://github.com/CloudiFire/caas/issues/51

**Comment by thz** [comment]
"after every master" merge only? Would it make sense to run it on PR branches?

**Comment by kron4eg** [comment]
Every run takes about 15-20 minutes, depending on cloud. And every run will cost us money. And it’s even more expensive since we will need a “matrix” of clouds X kubernetes versions to test.

**Comment by thz** [comment]
But "after merge" is a bit too late, right?

**Comment by kron4eg** [comment]
I think it’s right on time, we only need to confirm that cluster can pass conformance tests, and in case if it fails, well OK, next merge will fix the problem.

It’s not critical functionality and it can wait a bit to be in broken state.

Having it run after the merge is a way to minimize costs associated withy running multiple clusters on multiple clouds.
