### ISSUE TITLE
Etcd cluster "etcd": insufficient members (30). on cloud

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#1507]
cloud environment alerts are showing:
```
:fire:EtcdInsufficientMembers:fire:
Etcd cluster "etcd": insufficient members (30).
```

**Comment by mrIncompetent** [comment]
We should do 3 things here:
- Investigate the root cause (Potentially create a fix or create a follow up issue)
- Add a runbook for this error
- Include the cluster name in the alert

**Comment by pkavajin** [comment]
TODO: update to newest jsonnet rules after alerts have been moved to usercluster.

**Comment by xrstf** [comment]
This has been resolved. Matze moved the alerts over to the user cluster level, updated the jsonnet rules and now that we're not grouping all etcd instances over all clusters together, the bogus alert is not triggered anymore.
