### ISSUE TITLE
Show UI error messages longer

### ISSUE THREAD

**Issue by madddi** [kubermatic/kubermatic#1523]
Error messages in the Kubermatic UI are only shown for a few seconds, making it hard to read through all information and maybe copy them. It'd be nice if the red error message boxes would stay for something like 10 seconds.

**Comment by thz** [comment]
I think a major issue is that trying to copy the text from the error message includes a click on it and a click on it will dismiss the message.

**Comment by kdomanski** [comment]
@thz could you create a separate ticket for that issue?

**Comment by maciaszczykm** [comment]
I'd like to work on it as it looks like a good starting issue.
