### ISSUE TITLE
Move alerts for Kuberentes master components to namespace Prometheus

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#1533]
Right now we only have alerts in the Kubermatic Prometheus.
It would be easier to just have those alerts in the namespaced Cluster Prometheus as this one only sees its cluster metrics, thus making it easy to use upstream alerts without changing them.

**Comment by mrIncompetent** [comment]
Isn't that something we solve via federation?
What is the benifit in moving those alerts to the Prometheus running inside the cluster-namespace?

**Comment by metalmatze** [comment]
There are several parts involved why moving the alerts to the cluster clusters makes sense:

1. For alerts we want to have all metrics that we can get from components, so the alerts actually work. Federating everything (or too much) is to expensive and unnecessary.
2. We can use the alerts as they come from upstream (mixins for example) and have them work in our context. Example: `count by(job) (up{job=~".*etcd.*"} == 0) > (count by(job) (up{job=~".*etcd.*"}) / 2 - 1)` is wrong when running on Kubermatic Prometheus, as we might have 3, 6, 9, 12, ... etcds, which doesn't always fulfill `(n+1)/2`[1] that the rule is based on. So either we change those alerts and need to diff them every time, or we simply use them on a per cluster basis.
3. We can also move machine-controller alerts to the cluster prometheus and thus only alert on machine-controller if a cluster really exists.
4. We spread the responsibilities across Prometheus in the cluster, not Kubermatic Prometheus does it all. Increased resilience against many problems, like network partitions or Prometheus crashing.

[1] https://coreos.com/etcd/docs/latest/faq.html#operation
