### ISSUE TITLE
LoadTest for Beta

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#154]
Please write a script which creates ~500 clusters. Those clusters should be distributed across all available seed clusters.

If all clusters are up, create 3-5 nodes per cluster. For simplicity use just one provider.

All this should happen via script!

**Comment by mrIncompetent** [comment]
I case something breaks, maybe have a seconds script by hand, which deletes all clusters (including nodes)

**Comment by scruplelesswizard** [comment]
@realfake what is the status on this?

**Comment by lbb** [comment]
@chaosaffe The script for load testing is written and tested against the api. @mrIncompetent was executing the tests, he knows about the results.

**Comment by scruplelesswizard** [comment]
@realfake please attach the PR and make sure the usage instructions for the load test are documented
