### ISSUE TITLE
Analyze: Can Kubermatic clusters run with enforced SELinux?

### ISSUE THREAD

**Issue by guusvw** [kubermatic/kubermatic#1547]
SELinux can provide an additional layer of security to container workloads. OpenShift has SELinux enabled as default. It would be favourable to have this in the CloudiFire stack, too.
source: https://docs.google.com/spreadsheets/d/1M-4yj7MvE4pDoVbHx2zmgXHH-hHCKo5XCOYU7XC40CA/edit#gid=363762844&range=A5

CloudiFire Ref: https://github.com/CloudiFire/caas/issues/54

**Comment by alvaroaleman** [comment]
This is primarily blocked on kubeadm supporting selinux as we use kubeadm for seed cluster setup and node joining: https://github.com/kubernetes/kubeadm/issues/279

**Comment by alvaroaleman** [comment]
@guusvw Do we still need this issue now that the cloudifire one has been closed?

**Comment by scheeles** [comment]
For me it seems in the issue they mostly talking about etcd. Are we sure this is also valid for worker nodes.

**Comment by kdomanski** [comment]
The answer is no.
