### ISSUE TITLE
rewrite cluster/metrics endpoint

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1555]
rewrite existing `GET /api/v3/dc/{dc}/cluster/{cluster}/metrics` to `GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_name}/metrics`

child of #966

**Comment by kdomanski** [comment]
@p0lyn0mial hmm, but that endpoint seems to be present only in v3 API. Is this a mistake in the description, or am I missing something?

**Comment by p0lyn0mial** [comment]
yes, only in `v3`. I've updated the description.
