### ISSUE TITLE
migrate existing resources

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1556]
We need to move existing resources like `clusters` and `ssh keys` to the new world. In the new world resources belong to a project, thus the necessary steps are required for migration:

1. Find all `clusters` for the given user.
2. Create a project and give it a `Default` name.
3. Attach the `clusters` to the project (`OwnerReferences`)
4. Make the user the owner of the project.
5. Attach the ssh keys to the project

I would recommend to create a small "spike" and try to actually execute the above steps even manually to see if nothing is missing.

Note:
* It is preferable to put the logic into the existing cleanup command we have.

* It is preferable to backup the database before.

child of #966

**Comment by mrIncompetent** [comment]
I would recommend using the existing cleanup command we have. It would be perfectly suited.

Do we really want to create a project for each cluster?
Maybe rather create a project(called `Default`) for each user who has clusters and move all clusters to that project?

**Comment by p0lyn0mial** [comment]
> Maybe rather create a project(called Default) for each user who has clusters and move all clusters to that project?

sgtm
