### ISSUE TITLE
no business logic in handlers/encoders/decoders

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1558]
Description: TBD

child of #1539

**Comment by nikhita** [comment]
@p0lyn0mial Is it decided on what needs to be done here? I can help, if needed. :)

**Comment by p0lyn0mial** [comment]
@nikhita I'd love your help :) 

@nikhita If you don't mind I'd start off implementing https://github.com/kubermatic/kubermatic/issues/1557 
@nikhita to be honest even a directory layout with some description - where to put what - would be very helpful. At the moment the package is very flat https://github.com/kubermatic/kubermatic/tree/master/api/pkg/handler

**Comment by nikhita** [comment]
@p0lyn0mial Sgtm! I'll take a look and reach out to you on Slack with questions later. :)
