### ISSUE TITLE
"null" HTTP response

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1559]
When we don't want to return any data then the response body should be empty. At the moment empty response contains `null` text.

child of #1539

**Comment by mrIncompetent** [comment]
We could potentially add it to our json encoding function. We already use it to check that our 0-len slices are returned as `[]` instead of `null`

https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/handler.go#L77

**Comment by xrstf** [comment]
What does "body should be empty" mean exactly? Empty as in "zero bytes" or as in `{}`? Cause the former wouldn't be valid JSON..

**Comment by p0lyn0mial** [comment]
Interesting question :) I'd like to have it as "zero bytes" because usually you read the body and check the length before parsing. Does it make sense ?

**Comment by xrstf** [comment]
Is this meant as pure runtime optimization?

I'm afraid that empty bodies could break some Angular middleware that handles our API responses. And in general, not sending valid JSON when we're responding with `Content-Type: application/json` just doesn't feel right to me.

If we really, really want to save a few bytes, I would much rather see us adopting HTTP 204 - No Content responses, paired with a `text/plain` content type.

In order of preference, this is what I would suggest:

* Return a JSON body `{}` and let the frontend do a `response.length == 0` to check for empty responses.
* Return text/plain with HTTP 204
* anything else

**Comment by p0lyn0mial** [comment]
I'd prefer to return `{}` then (the first option) as the second option would require to have a specialised code in the client.
