### ISSUE TITLE
a cluster without a machine-controller can never be deleted

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#1563]
Situation:
Developer is experimenting with a local version of a machine controller on a dev cluster. He pauses the cluster and removes the `machine-controller` deployment.

Now he either tries to delete the cluster or just waits for the overnight deletion trigger.

The cluster still has the `kubermatic.io/delete-nodes` finalizer that a `machine-controller` is required to resolve. However, that missing `machine-controller` deployment will never be restored, even by unpausing the cluster, since the cluster is already marked for deletion.

**Comment by mrIncompetent** [comment]
I'll definitely will vote against changing the cluster-controller logic to cope with that.
The cluster is not beeing managed by the controller & the state has been manually changed.

The only change i see here, is that we don't delete clusters which have `paused=true`.
WDYT?

**Comment by kdomanski** [comment]
> The only change i see here, is that we don't delete clusters which have paused=true

Good enough for me.

Note to self: the script lives in https://github.com/kubermatic/infra/blob/master/garbagecollect-clusters/gc-configmap.yaml

**Comment by alvaroaleman** [comment]
This cant be fixed because one can only get in this situation when manually fiddling around with clusters
