### ISSUE TITLE
Vsphere seed: Rebooting nodes requires manual detaching of volumes

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1571]
When using a vsphere seed and rebooting a node that runs one or more pods with attached PVs, that node can not be started anymore because the cloud provider does not remove the volume binding from the old node even thought the pod will get rescheduled to another node.

This then means that the vsphere instance can not be started anymore until an operator manually removes the binding to the node inside vsphere.

Upstream issue: https://github.com/kubernetes/kubernetes/issues/63577

A possible quickfix would be to implement a systemd unit that taints and drains nodes prior to rebooting them and removes the taint on startup.

**Comment by mrIncompetent** [comment]
Looking at https://github.com/kubernetes/kubernetes/pull/63413#issuecomment-402807143 we might just simply wait for 1.12 to land?

**Comment by alvaroaleman** [comment]
Yes, we should potentially communicate this for the time being to Kubermativ + Vsphere users and leave this issue open as internal tracking issue but not act on it.

**Comment by mrIncompetent** [comment]
Closed in favor of https://github.com/kubermatic/docs/issues/44
