### ISSUE TITLE
Do not delete cluster etcd backups directly after cluster deletion

### ISSUE THREAD

**Issue by bashofmann** [kubermatic/kubermatic#1572]
It would be nice to net delete the etcd backups directly after/during cluster deletion but only a (configurable) few days later, so that an accidental deletion could potentially be recovered.

**Comment by alvaroaleman** [comment]
Generally speaking this is rather tricky to get right as the cluster object which is responsible for the lifecycle of the cluster including its backups wont exist anymore.

Theoretically we could use a kube cronjob that deletes itself after successful completion, however we can not reconcile it post cluster deletion and it would be rather hard to reason about it.

**Comment by mrIncompetent** [comment]
@bashofmann could you check if https://github.com/kubermatic/kubermatic/issues/1590 fits your needs?

**Comment by bashofmann** [comment]
Sounds good, closing this in favor of #1590.
