### ISSUE TITLE
Provide exactly one way to make Kubermatic not manage a cluster

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#1578]
Currently there are three ways to tell Kubermatic to not manage a given cluster:

* Set `.labels.worker-name` to an non-empty string: AFAIK this has no effect
* Set `.Spec.pause`: Only respected by machine-controller
* Set `.Spec.workerName`: Respected by (AFAIK) everything

We should instead provide exactly one way to configure this, everything else is confusing.

IMHO the label is the nicest approach, because it allows us to include at the lister/informer level and consequently we won't have to put any logic for this inside the controllers. But this is something that has to be discussed first.

*Acceptance criteria:*

* The three options were discussed and one of them was chosen
* The two not-chosen options were removed

**Comment by kdomanski** [comment]
@alvaroaleman `.labels.worker-name` does in fact work and is respected by the cluster-controller.
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/controller/cluster/cluster_controller.go#L322-L325

@mrIncompetent What's your opinion on removing `.Spec.pause`?

**Comment by alvaroaleman** [comment]
`Spec.workerName` was removed as part of #1668

**Comment by mrIncompetent** [comment]
`Spec.pause` should be kept.

As the rest of this issue is covered by https://github.com/kubermatic/kubermatic/issues/1166 I'm closing this here.
