### ISSUE TITLE
Add CIS scanner to the e2e test (user cluster)

### ISSUE THREAD

**Issue by guusvw** [kubermatic/kubermatic#1585]
We want to integrate one CIS scanner in our E2E pipeline for the user cluster.

DoD:

* evaluate a CIS scanner
https://github.com/aquasecurity/kube-bench
https://github.com/neuvector/kubernetes-cis-benchmark
https://github.com/nccgroup/kube-auto-analyzer
* add an additional step to our e2e pipeline

CloudiFire-Ref: https://github.com/CloudiFire/caas/issues/60

**Comment by kron4eg** [comment]
we tried kube-bench recently. Its results are unreliable.

cc @alvaroaleman

**Comment by mrIncompetent** [comment]
@guusvw @kron4eg So we can close this one?

**Comment by kron4eg** [comment]
@mrIncompetent yeah

**Comment by toschneck** [comment]
Due to the fact that the available CIS scanner are out of date, this don't make sense. So we was able to run it manually and fixed the sens full issues with: https://github.com/kubermatic/machine-controller/pull/286
