### ISSUE TITLE
Move etcd backup cleanup into dedicated CronJob

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#1590]
**User Story**
When a cluster gets deleted a Job gets created which will delete all etcd backups for the cluster.
As a user i might have accidentally deleted the cluster and would need to restore it from a backup. Unfortunately that has been deleted.

When deleting a cluster, a CronJob will be created which will spawn a Job to finally delete all backups of that cluster after a given period.
When Job successfully deleted all Backups it will finally delete its parent CronJob.

**Acceptance criteria**
- [ ] Cleanup of etcd backups gets executed via Kubernetes CronJob
- [ ] The cleanup job triggered by the CronJob must delete the CronJob when successfully done.
- [ ] The period after which the CronJob executes the cleanup must be configurable via a flag on the kubermatic controller-manager

**Definition of Done**
- [ ] cleanup of etcd backups is beeing delayed by a configured period

**Comment by alvaroaleman** [comment]
We either need a finalizer on the cluster to be sure that cleanup cronjob will get created or create it beforehand (on cluster creation) and just let it check if the cluster exists. If that is the case it will just do nothing.

**Comment by mrIncompetent** [comment]
I would prefer going the way via a Finalizer - like we already do at the moment

**Comment by kdomanski** [comment]
@mrIncompetent
Is there an easy way to restore a cluster from that backup or does it require another user story?
What about destroyed data volumes of applications within the cluster? Is restoring the cluster state but losing user data sufficient improvement over losing both?

**Comment by mrIncompetent** [comment]
So far only restoring the etcd from a backup has been covered: https://docs.kubermatic.io/operation/etcd/restoring-from-backup/

Restoring a full cluster (cluster crd & cluster-namespace are gone) is not covered. But we don't backup the manifests in the cluster namespaces & the crd yet.
Though there is an ongoing effort to include ARK to solve that. cc @xrstf 

> What about destroyed data volumes of applications within the cluster? Is restoring the cluster state but losing user data sufficient improvement over losing both?

Data inside the user-cluster is not our responsibility atm as the user could use anything he/she wants (nfs, rook, gluster, host-path, sftp, voodoo) and we have no control over it. Content inside the user-cluster is out of responsibilty IMO. This data is not managed by us anyway (GCP, AWS, OpenStack).

**Comment by alvaroaleman** [comment]
@mrIncompetent @alvaroaleman Revisit this

**Comment by mrIncompetent** [comment]
Other suggestion:
When deleting the cluster the backup controller moves the last backup into a "trash" folder inside the bucket.
A CronJob deletes files inside the "trash" folder which are older 14d ?

@alvaroaleman

**Comment by mrIncompetent** [comment]
@alvaroaleman @mrIncompetent Lets revisit this issue and check if the current description makes sense
