### ISSUE TITLE
an endpoint that gets current user's profile

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1596]
Add an HTTP endpoint that displays detailed profile information about the current user. 
The profile should contain: 
 * id 
 * name
 * email
 * creationTime 
 * the list of project the user belongs to along with the group names.

Potential path could be of the form:

* /api/v1/me
* /api/v1/users

### To Do
- [x] implement an endpint
- [x] add unit test

child of #966

**Comment by xrstf** [comment]
This has high priority, but is it urgent as well? It seems like a nice issue to get my feet wet, but it could take a bit for me to get all components (dashboard, api, etc.) up and running and be able to actually code some stuff.

On that note, a big 👍 for `/api/v1/users/me`.
