### ISSUE TITLE
EC2 instances are not deleted.

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1609]
After running e2e tests, EC2 instances that were used by the tests are stuck in deletion state. 

This situation caused our AlertManager to trigger alerts:
```
Machine e2e-test-runner-fnq78 is stuck in deletion since more than 30min.
https://docs.kubermatic.io/monitoring/runbook/#alert-machinecontrollermachinedeletiontakestoolong

Machine e2e-test-runner-snj9p is stuck in deletion since more than 30min.
https://docs.kubermatic.io/monitoring/runbook/#alert-machinecontrollermachinedeletiontakestoolong

Machine e2e-test-runner-vj9p9 is stuck in deletion since more than 30min.
https://docs.kubermatic.io/monitoring/runbook/#alert-machinecontrollermachinedeletiontakestoolong
```

* Investigate if EC2 instances are properly deleted. 
* In case they actually are make sure that deletion can take up to 40 min. 
* Lastly increase the timeout to make AlertManager happy

**Comment by p0lyn0mial** [comment]
@kron4eg I'm assigning this to you :)

**Comment by kron4eg** [comment]
cc @mrIncompetent

**Comment by p0lyn0mial** [comment]
since the tests actually create machine resources to tell machine controller to create an AWS instance, perhaps there is something wrong with machine controller actually ?

or perhaps deletion can take very long time ?

**Comment by p0lyn0mial** [comment]
![screen shot 2018-07-25 at 13 52 24](https://user-images.githubusercontent.com/21304151/43199381-06484f26-9012-11e8-8698-0a8aa9efa7b6.png)

**Comment by p0lyn0mial** [comment]
some instances need more than one hour to disappear ? ( see the attached picture)

**Comment by kron4eg** [comment]
@p0lyn0mial that's OK, AWS automatically GC them. The main point that they are "Terminated" and not belong to us anymore (in the sense that we don't have to pay for them).

**Comment by p0lyn0mial** [comment]
@kron4eg we are not charged for instances in `terminated` state.

so I think that everything is actually okay, we only have to increate the timeout in AlertManger ?

**Comment by mrIncompetent** [comment]
For the machine-controller the instance is considered deleted when it reached the state `terminated` in AWS. See:
- https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/aws/provider.go#L738
- https://github.com/kubermatic/machine-controller/blob/master/pkg/controller/machine/machine.go#L450
- https://github.com/kubermatic/machine-controller/blob/master/pkg/controller/machine/machine.go#L411

I wrote in the #alerting-cloud channel yesterday that the alertingrule i added might be broken. 
I'll fix it

**Comment by p0lyn0mial** [comment]
@mrIncompetent missed that one. Thanks.
@mrIncompetent I'm assigning this issue to you, just update the alert rule and close the issue.

**Comment by mrIncompetent** [comment]
Closed via https://github.com/kubermatic/kubermatic/pull/1611
