### ISSUE TITLE
Evaluate ways to write unit tests for the controller (phase pending)

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#161]
Things the controller does in the pending phase of a cluster:
-Deploy applications (Kubernetes master components, etcd) - templates are located in controller/static/master in the config repo
-Generate certificates
-Generate auth-token
-Generate ssh-key

**Comment by aklinkert** [comment]
Okay, I've spend a couple of hours reading through the code and checking tons of things now. There are some functions (like https://github.com/kubermatic/api/blob/develop/controller/cluster/pending.go#L107 ff or https://github.com/kubermatic/api/blob/develop/controller/cluster/pending.go#L288 ff) defined within the smaller controller functions which could be extracted and tested isolated, but that would require a little refactoring first.

Speaking of Kubernetes, there is a `NewSimpleClientset()` at `k8s.io/client-go/kubernetes/fake` method which generates a fake ClientSet that can be injected into the controller loaded with existing api objects. Most of the methods should be testable by that - after extracting the inline functions though.

Here is an example on how to use this fake ClientSet: https://fossies.org/linux/kubernetes/pkg/controller/serviceaccount/tokens_controller_test.go

Any opinions / ideas / thoughts on this? I'd personally prefer to start implementing a few test cases. Most of the problems will be pop up while doing so. Is this fine for all of ya?

**Comment by scruplelesswizard** [comment]
Yeah, I would be for extracting the methods for sure. It also tends to make the code more readable as well.

**Comment by mrIncompetent** [comment]
LGTM
