### ISSUE TITLE
API endpoint for dashboard v2 to generate a cluster in one step

### ISSUE THREAD

**Issue by mrahbar** [kubermatic/kubermatic#165]
With https://github.com/kubermatic/dashboard-v2/issues/5 the user can generate a whole cluster after the inital flow. Provides data contains:
- Cluster name
- Datacenter
- Cloud provider, region, ssh-key, node count (in case of aws and datacenter)

Necessary steps:
- [ ] Define Api Model
- [ ] Define Api Endpoint

Endpoint will be the following:
- POST "/api/v1/clusters"

**Comment by mrahbar** [comment]
Initial version of api model. Let me know if it suits the requirements:
```json
{
	"name": "cluster-name",
	"node": {
		"provider": {
			"name": "digitalocean",
			"user": "user-identifier",
			"secret": "user-secret"
		},
		"region": "do-ams2",
		"count": 3,
		"type": "t2.nano",
		"sshKeys": [
			"ssh-key-name",
			"ssh-key-name"
		]
	}
}
```
//cc @scheeles @apinnecke @mrahbar @mrIncompetent @realfake 
Last Edit: 17.01 1745

**Comment by scruplelesswizard** [comment]
Updated request spec from @apinnecke 
```json
{
  "cloud": {
    "user": "dtrump",
    "secret": "melania123",
    "name": "aws",
    "region": "eu-central-1a"
  },
  "spec": {
    "human_readable_name": "cluster-name"
  },
  "node": {
    "count": 3,
    "type": "t2.nano"
  },
  "ssh_keys": [
    "ssh-key-name",
    "ssh-key-name"
  ]
}
```

**Comment by aklinkert** [comment]
So we ( @chaosaffe , @mrIncompetent , @apinnecke) decided to remove the node node creation from the new create cluster endpoint and keep executing two separate calls to create the actual cluster and to create the nodes. The new create cluster endpoints then looks like:

```json
{
  "cloud": {
    "user": "dtrump",
    "secret": "melania123",
    "name": "aws",
    "region": "eu-central-1a"
  },

  "spec": {
    "human_readable_name": "cluster-name"
  },

  "ssh_keys": [
    "ssh-key-name",
    "ssh-key-name"
  ]
}
```

the user flow remain the same, but the dashboard needs to execute two separate calls sequentially. We need to delay the node creation because the API has to wait for the cloud details to be set by the kubermatic cluster controller, which may need some seconds, up to some minutes.

**Comment by mrahbar** [comment]
@apinnecke Would the flow look like this then:
-> Request: POST "/api/v1/clusters"
<- Response: 201 - Body: cluster-spec incl. dc-id and cluster-id

Should the dashboard wait here?

-> Request: POST "/api/v1/dc/{dc}/cluster/{cluster}/node"
<- Response: 201 - Body...

Is this flow complete from your perspective?

~~Btw. what is the cloud.user for? Do you want it to be the nickname of the user?~~
In case of AWS we have the field Access Key ID and Secret Access Key. I think we should update the payload model to be:

```json
{
  "cloud": {
   "user": "username",
    "key": "my-key",
    "secret": "my-secret",
    "name": "aws",
    "region": "eu-central-1a"
  },
  "spec": {
    "human_readable_name": "cluster-name"
  },
  "ssh_keys": [
    "ssh-key-name",
    "ssh-key-name"
  ]
}
```

**Comment by scruplelesswizard** [comment]
The dashboard doesn't need to wait. The second call will hang, but we want immediate response on the first call in case of error. 

Cloud.user is the user identifier for services that require it (I. E. AWS)

**Comment by mrahbar** [comment]
@chaosaffe How is cloud.user provided? Should the user enter it or should it be the nickname of the logged in user?

**Comment by scruplelesswizard** [comment]
For cloud providers that require a user identifier, the user will need to provide it. This will be used in calls against the provider api. For cloud providers that don't require it, it should be left empty.

**Comment by scruplelesswizard** [comment]
@mrahbar The struct should be as follows:

```
{
  "cloud": {
    "user": "dtrump",
    "secret": "melania123",
    "name": "aws",
    "region": "eu-central-1a"
  },

  "spec": {
    "human_readable_name": "cluster-name"
  },

  "ssh_keys": [
    "ssh-key-name",
    "ssh-key-name"
  ]
}
```

Field Descriptions

Field | Description 
--- | ---
user| The user identifier used to authenticate with the Cloud Provider. On AWS this will be the Access Key ID, on Digital Ocean this is not required and should be blank. _Entered by User_
|secret| The token/password used to authenticate with the Cloud Provider. On AWS this will be the Secret Access Key, on Digital Ocean this will be the Personal Access Token. _Entered by User_|
|name| The name of the Cloud Provider the API should use|
|region| The geographic location to use for creating instances (On AWS this is a zone, on DO this is a datacenter etc. The target where we create nodes from which we can conclude where our seed cluster is located)(This is *the* datacenter the user selects out of the given choices)|
|human_readable_name|The name that the user has entered for the cluster. _Entered by User_|
|ssh_keys| The user-selected SSH keys to deploy on the cluster nodes|

**Comment by mrahbar** [comment]
@apinnecke @chaosaffe 

Concerning the api-call flow. According to the following statement we do two sequential api calls. 

> the user flow remain the same, but the dashboard needs to execute two separate calls sequentially. We need to delay the node creation because the API has to wait for the cloud details to be set by the kubermatic cluster controller, which may need some seconds, up to some minutes.

1. create cluster: POST "/api/v1/clusters" with the above model
2. add nodes to cluster: POST "/api/v1/dc/{dc}/cluster/{cluster}/node"

To do the second api-call the response of api-call of nr. 1 has to return something like:
https://github.com/kubermatic/api/blob/develop/types.go#L330
which includes values which can then be filled in {dc} and {cluster}.

Furthermore from https://github.com/kubermatic/api/blob/develop/handler/node.go#L191 I can tell that the request body for nr. 2 will be something like:

```
{
	"dc": "dc-name",
	"user": "user-name",
	"cluster": "cluster-name"
	"instances": 3,
	"spec": {
		"dc": "dc-name",
		"digitalocean": {
			"type": "type-name",
			"size": "size-name",
			"sshKeys": []
		}
	}
}
```

I will plan changes to the dashboard api-service which will incorporate that if this is the flow we are going to use.

Side note: probably wrong type definition on AWSNodeSpec
https://github.com/kubermatic/api/blob/develop/types.go#L50

**Comment by aklinkert** [comment]
@mrahbar @j3ank 80% of the API is using camelCase json keys, so we decided to stick with that _for now_ and change the json keys in one stap later, probably next sprint together with the node controller.

So the new create cluster request will look like: (just sshKeys and humanReadableName changed)
```
{
  "cloud": {
    "user": "dtrump",
    "secret": "melania123",
    "name": "aws",
    "region": "eu-central-1a"
  },

  "spec": {
    "humanReadableName": "cluster-name"
  },

  "sshKeys": [
    "ssh-key-name",
    "ssh-key-name"
  ]
}
```
