### ISSUE TITLE
kubermatic-api and kubermatic-controller-manager are crashing on startup

### ISSUE THREAD

**Issue by bashofmann** [kubermatic/kubermatic#1650]
Starting with today's 2.6.x releases both kubermatic-api and kubermatic-controller-manager are crashing on startup with the error

"flag provided but not defined: -addons"

The helm chart still contains this startup flag

**Comment by bashofmann** [comment]
We can not reproduce this anymore on our side, apparently for some reason when deploying we got a wrongly tagged docker image somehow.

All works now.

Sorry for the confusion.

**Comment by pkavajin** [comment]
Hey, thanks for the update.
Just had a look at it, we actually did some mistagging here - sorry for the trouble. Was fixed shortly after the tag got uploaded, but looks like you still had the old image cached. Just in case: better remove and repull the kubermatic images on all nodes.
