### ISSUE TITLE
incorporate digitcalocean into api endpoint /ext/${dc}/keys

### ISSUE THREAD

**Issue by mrahbar** [kubermatic/kubermatic#166]
Proposal: 
value for dc is provided for either one of:
 - aws
 - digitalocean

payload of request contains json formated data. In case of:
- aws: {"username": "..." , "password": "..."}
- digitalocean: {"token": "..."}

Response should return a list of the following JSON object:
{"name": "...", "fingerprint": "..."}

This API endpoint is necessary for https://github.com/kubermatic/dashboard-v2/issues/5

**Comment by scruplelesswizard** [comment]
This is no longer required, as Kubermatic will now manage SSH Keys internally, not depending on CP's
