### ISSUE TITLE
Use NodeSets for nodes

### ISSUE THREAD

**Issue by lbb** [kubermatic/kubermatic#167]
To group node types we need sth. like gcloud's instance groups https://cloud.google.com/compute/docs/instance-groups/

Requirements
* Each node has to be a member of  a group
* Every node is in only one group
* Node groups contain only one node type (i.e. same configuration)
* Node type in the group can't be changed

**Comment by scruplelesswizard** [comment]
What is the intent behind grouping nodes? Where do we need to group them and why?

**Comment by scruplelesswizard** [comment]
After discussions in the office the intent is to use the Instance Groups (GCP) and Auto-scaling groups (AWS) for scaling the cluster size using the node-controller, which requires us to use some form of grouping for the nodes

**Comment by mrIncompetent** [comment]
Should be implemented using the NodeSet github.com/kube-node/nodeset

**Comment by mrIncompetent** [comment]
Dup of https://github.com/kubermatic/kubermatic/issues/512
