### ISSUE TITLE
Service Accounts

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1678]
As a user i want to:
- Create static access credentials to talk to the kubermatic-api
- Delete those credentials
- Create those credentials with a specific role in a project

In general a service account is a special type of an account that usually belongs to some application. The application uses the service account to call our APIs. 

Requirements: https://docs.google.com/document/d/10XuwM-_7V9kgn72LV06q36vHl1gtLwoCM5xTGmbrOtk/edit

**Comment by floreks** [comment]
If there is anything not finished please reopen. I'll close for now.

/close
