### ISSUE TITLE
Handle reconcile/update for master kubeconfigs

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1689]
### Context:

Scheduler, MachineController and ControllerManager talk with a dedicated kubeconfig with the api.

The kubeconfig creation happens in api/pkg/controller/cluster/auth.go (`getKubeconfigSecret()`).

### Current behaviour:

In the case of an existing secret which holds the kubeconfig, the existing kubeconfig is returned unconditionally.

### Desired behaviour:

The existing version is checked to see if an update is necessary. In that case a new kubeconfig is returned instead of the existing one.

**Comment by alvaroaleman** [comment]
@mrIncompetent Verify if this has been fixed

**Comment by mrIncompetent** [comment]
Yes, the controller by now checks if the kubeconfig is up-to-date and updates it if necessary.
This included the CA, Address & Certificate (Lifetime & CommonName & Orgs)
