### ISSUE TITLE
Implement proposal user-cluster-controller

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1706]
**User Story**

The proposal implements a dedicated controller for user-cluster resources.

cluster-controller currently creates some resources for the user-cluster. this shall move to a user-cluster-controller living in the user-cluster itself.

**Acceptance criteria**

**Definition of Done**

**Comment by nikhita** [comment]
As the initial skeleton (https://github.com/kubermatic/kubermatic/pull/2671) has been merged, I'll close this in favour of follow up issues (https://github.com/kubermatic/kubermatic/issues/2827). 

Please reopen if needed.
