### ISSUE TITLE
[Spike] Create a plan to do customization of prometheus & grafana

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1728]
A customer wants to specify own grafana dashboards and prometheus rules/alerts.
We should research ways to do that without having to deploy custom grafanas/prometheuses or do some hacking on the helm charts.

So result of this spike should be:
* a written masterplan on how to solve that
* the corresponding issues created

**Comment by xrstf** [comment]
There are two things involved here:

* Customizing the Prometheus rules/alerts involves possibly chaning how we deploy user clusters.
* Changing Grafana dashboards is only relevant for the seed cluster and should be solvable by "just" having custom values for the Helm chart.

**Comment by pkavajin** [comment]
-> Created corresponding issues, therefore closing this one:
• https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/1782
• https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/1789
• https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/1792
• https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/1793
• https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/1795
• https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/1796
