### ISSUE TITLE
[Spike] Research Prometheus Federation scaling

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1729]
A customer plans to have >=150 User Clusters per Seed Cluster.
So we should have a look how well our current monitoring stack (prometheus federation particularly) scales.

Result should be a documented statement on how well that works and - if necessary - issues about improving that situation.

**Comment by xrstf** [comment]
This has been obsoleted by Thanos. See the https://github.com/kubermatic/kubermatic/issues/3540 proposal.
