### ISSUE TITLE
New default addons are not automatically created in existing user clusters

### ISSUE THREAD

**Issue by bashofmann** [kubermatic/kubermatic#1749]
When a new default addon is added to the controller-manager, we would expect that his new addon is also added to existing user clusters, but it will only be added to new user clusters.

**Comment by toschneck** [comment]
the same effect happens if we remove a custom add-on from the config

**Comment by bashofmann** [comment]
@mrIncompetent Can this be closed with the changes made in the addon-controller in 2.7?

**Comment by mrIncompetent** [comment]
Yes, missing addons are being added automatically.
