### ISSUE TITLE
AddOns are not automatically update in existing clusters

### ISSUE THREAD

**Issue by bashofmann** [kubermatic/kubermatic#1750]
If we update an addon, for example by bumping the image version in a deployment. The deployment is not updated in existing clusters with this addon. Only when we manually delete the deployment in an existing cluster, or in new user clusters, will the udpated deployment be created.

**Comment by bashofmann** [comment]
@mrIncompetent Can this be closed with the changes made in the addon-controller in 2.7?

**Comment by mrIncompetent** [comment]
Yes! This was done in v2.7
