### ISSUE TITLE
Evaluate alternatives to dex

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#1764]
Since CoreOS no longer actively maintain `dex` after their acquisition by RedHat, the long term viability of `dex` as our auth solution comes into question. For that reason, we need to evaluate possible solutions:
 * forking and maintaining `dex` ourselves
 * Keycloak
 * something else?

**Comment by kron4eg** [comment]
relevant discussion on dex itself: https://github.com/coreos/dex/issues/1273

**Comment by kron4eg** [comment]
dex came back to life
