### ISSUE TITLE
[Grafana/Prom Customizing] [CLUSTER-NS] Custom Alerts for Prometheus in cluster namespaces

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1792]
Users should be able to create alerts for the prometheuses running in the individual cluster namespaces.
Therefore we should extend the cluster controller to deploy custom alerts (additionally to our existing, autogenerated rules).
To do that, the cluster controller should read a specific configmap (which gets created by helm and populated by values.yaml) containing the custom rules and insert those rules into the prometheus-rules configmap.

**Comment by xrstf** [comment]
Do we need to read the contents of the configmap when we deploy the user cluster? Can't we check if the configmap exists and if it does, mount it to the prometheus pod and then also extend Prometheus' `prometheus.yaml` to include files from that configmap? Then the configmap can be updated at any time and if we configure the config-reloader thingy correctly, the seed maintainer can easily deploy a new configmap and have all Prometheus in all user clusters be updated automatically.
