### ISSUE TITLE
Pre-aggregate metrics in user-cluster Prometheus

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#1803]
**User Story**

Customers are experiencing high (3+GB) memory and storage requirements for running the seed-level Prometheus. Data for roughly a month with less than 10 user clusters is already reaching 20+GB on disk. This leads to high CPU usage when Prometheus is compacting its TSDB and can get the pod killed, leading to an endless cycle of restarts and failed compaction attempt, filling the disk even more.

To prevent this, we need to reduce the amount of data that is scraped from the user-level Prometheus instances. For this we need to define extra rules to aggregate metrics in the user-cluster. This however will also affect the metrics names and maybe labels, so we need to adjust the Grafana dashboards as well. At this point, keeping them in sync with the upstream jsonnet mixins will become a total PITA. It's easier for us to take the dashboards we have now, remove the jsonnet stuff and adjust the dashboards as needed.

We _could_ in theory use jsonnet to generate our dashboards, but in that case we will lose the ability to just edit a dashboard, download the new JSON and replace the .json file in our repository. And we introduce a new level of complexity without much to gain.

So the master plan for this issue is to go through each dashboard, determine the required information for each panel, create a fitting rule, rewrite the panels and when done, download and store the new JSON in the `config/monitoring/grafana/dashboards/...` directory.

**Acceptance criteria**

* All existing dashboards are working.
* We only scrape metrics required for the dashboards (and maybe a few minor other ones, depends on a case-by-base basis; but keep it light).

**Comment by multi-io** [comment]
So you can reproduce this too? Was this issue triggered by our conversation yesterday?

In our stage cluster (~8 user clusters) we've removed all our custom rules yesterday evening and also started with a new empty tsdb. With that, the Prometheus initially consumed about 1.9 GB, which has now grown to about 4.1 GB.

We can roll out your keys on the stage nodes if you want to.

**Comment by xrstf** [comment]
This issue was indeed triggered by our conversation. Our own Prometheus setups are running mostly smoothly.

**Comment by xrstf** [comment]
With the Kubermatic 2.9 release we will only be federating metrics labelled with `kubermatic=federate` up to the seed Prometheus. In addition to that, all alerts that can be handled in the user clusters are also handled there. This leaves us with only those metrics being federated that are required for Grafana dashboards. This is roughly 100, most of which for the etcd dashboards.
