### ISSUE TITLE
Move nodePort generation

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#181]
<a href="https://github.com/mrIncompetent"><img src="https://avatars.githubusercontent.com/u/14090308?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mrIncompetent](https://github.com/mrIncompetent)**
_Wednesday Dec 07, 2016 at 22:02 GMT_
_Originally opened as https://github.com/kubermatic/kubermatic-internal/issues/13_

----

Currently we are generating the unique nodePort in the api.
Needs to be moved to the controller

**Comment by mrIncompetent** [comment]
Implemented
