### ISSUE TITLE
Competitor Comparison

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#182]
<a href="https://github.com/chaosaffe"><img src="https://avatars.githubusercontent.com/u/15822260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chaosaffe](https://github.com/chaosaffe)**
_Thursday Dec 08, 2016 at 21:18 GMT_
_Originally opened as https://github.com/kubermatic/kubermatic-internal/issues/14_

----

Don't know if this is the complete list, but as starting point:

https://platform9.com
http://rancher.com
http://www.navops.io
https://stackpoint.io

**Comment by scheeles** [comment]
I close this and let Krissi work on it
