### ISSUE TITLE
Automatically upgrade clusters to newer version

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#1822]
A user needs to have the ability to configure a cluster to be automatically upgraded to the latest version.

A cluster with an annotation `auto-upgrade` will be upgraded depending on the annotation's value:
 * `minor` - to the latest minor version of the same major version, i.e. cluster of version `X.Y.Z` will be upgraded to any higher version `X.A.B`. Note that `X` must stay the same.
 * `patch` - to the latest patch version of the same minor version, i.e. cluster of version `X.Y.Z` will be upgraded to any higher version `X.Y.C`. Note that `X.Y` must stay the same.
 * any other value - the cluster will not be upgraded automatically.

Acceptance criteria:
 * [ ] update_manager automatically applies updates according to the rules laid out above

Remaining questions:
 * is an annotation really the best place to set this?
 * perhaps we need to add a new field to the CRD?
 * use the upstream's cluster object's `ProviderConfig` field?

**Comment by alvaroaleman** [comment]
This can already be done with the `updates.yaml`

**Comment by toschneck** [comment]
@alvaroaleman can someone document it how it works? Would be good chapter for https://docs.kubermatic.io/operation/
