### ISSUE TITLE
Versioned Kubermatic Documentation

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1833]
Make the documentation for kubermatic version aware, so that we have different documentations for the different releases.

Possible solution:
* run multiple docs instances for different release/* branches
(maybe later?: * share the template and let it contain like a side panel with links to all different versions)

**Comment by xrstf** [comment]
This is still in discussion with the "sig-docs" Loodse team. Not neccessarily something seed-team has to do.
