### ISSUE TITLE
apiserver-running initContainer need to give up or re-lookup

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1853]
**User Story**

`controller-manager` has an initContainer called `apiserver-running` which does an endless loop of http-requests to the (assumed) ip-address of the apiserver. The idea is to wait for apiserver's reachability before continuing. The problem with this is that there is no re-lookup of the apiserver's ip-address. It can happen that the apiserver pod got restarted/recreated and will never listen to the old ip-address.
The initContainer needs to give up and die (causing a new lookup) or the initContainer needs to use dns instead of being created with a pre-looked-up ip-address.

**Acceptance criteria**

After being brought in the situation described above (apiserver ip changed during initContainer lifetime) the `controller-manager` must be able to recover.

**Definition of Done**

**Comment by thz** [comment]
As a failing initContainer would be restarted only and by that being restarted with the same spec (and incorrect apiserver adress), it might be better to follow the documentation:
```Use activeDeadlineSeconds on the Pod and livenessProbe on the Container to prevent Init Containers from failing forever. The active deadline includes Init Containers.```

**Comment by thz** [comment]
Actually the used IP is the svc ip and should be constant and need no re-lookup. Still need to investigate why initContainer fails to reach apiserver.

**Comment by mrIncompetent** [comment]
@thz is this still relevant after we migrated to the [http-prober command](https://github.com/kubermatic/kubermatic/tree/master/api/cmd/http-prober)?

**Comment by mrIncompetent** [comment]
Ping

**Comment by mrIncompetent** [comment]
Has been fixed with https://github.com/kubermatic/kubermatic/tree/master/api/cmd/http-prober

@thz Please reopen if you disagree
