### ISSUE TITLE
ImagePullSecret only for dockerhub

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1854]
**User Story**

There is `resources.ImagePullSecretName = "dockercfg"`.
Then there is `kubermatic.docker` and `kubermatic.quay` in values.yaml which is used by templates for `quay` and `dockercfg` secrets in kubermatic ns.

Now in cluster-namespace:
Cluster-controller only ensures the `dockercfg` in `ensureSecrets` by copying `dockercfg` from kubermatic namespace.

This is a problem if one wants to use a non-public image from non-dockerhub registries programmatically.

This could be resolved by ensuring more secrets for image pulling into the cluster-ns, or by having the set of "to-be-available" registry credentials compiled into one ImagePullSecret in kubermatic-ns already.

**Acceptance criteria**

It is programmatically possible to access non-public images from other registries.

**Definition of Done**

**Comment by alvaroaleman** [comment]
We want quay only, closing
