### ISSUE TITLE
cloud providers endpoints 

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1856]
**User Story**
As @xrstf suggested we should group cloud providers at `api/v1/providers` instead of keeping them at the root level e.g. `api/v1/openstack`.

**Acceptance criteria**
- New EP were added
- The dashboard is updated and uses the new EPs
- The Old EPs are removed

**Comment by glower** [comment]
I will change all provider-specific routes to have /providers prefix.
I will keep old routes with 301 redirect, so we can have both routes in place first

**Comment by kdomanski** [comment]
@p0lyn0mial is this still unfinished, or was the re-open by @glower an accident?

**Comment by p0lyn0mial** [comment]
yeah, I think so. 
I'm closing this issue as this is already implemented.
