### ISSUE TITLE
API checks if a cluster has been initialised. 

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1860]
**User Story**
As a user of kubermatic API server I'd like it to detect and signal back when I'm trying to do operations associated with `cluster` resource that hasn't been initialised yet. For example adding a `node` to not initialised `cluster` will return an error. The actual error can be misleading for example it can return `404` `secret \"admin-kubeconfig\" not found`. Instead our API should check if the `cluster` resource has been initialised and if not it should yield back an error. Possibles error codes could be `202` or `503` or something else ? 

How to check if a cluster has been initialised ?
use `cluster/health` endpoint and check if all listed components have its field set to `true`

Possible implementation:
Change `GET` method of the rbac compliant cluster provider so that it accepts "options" (similarly to List method). If the option is set then the provider will ensure that the cluster was initialised and if not it will return an error. 
Next identify all possible places in API. For example  the handler for `POST` to `/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodes` and set appropriate option when getting the cluster.

**Acceptance criteria**
- API verifies if the given cluster has been initialised before allowing to an operation that requires it.

**Comment by p0lyn0mial** [comment]
@kgroschoff I know that we already check if the cluster has been initialised but I figured that it would be nice if our API server could verify this as well

**Comment by toschneck** [comment]
@p0lyn0mial can we also add there the state of the different components is we deploy:
* master-components
  * etcd
  * ...
* cluster add-on's
  * canal
  * ...

For me as kubermatic user a cluster should only fully healthy if all components are up and running. @kgroschoff  I expect you will use later on the API endpoint in the UI?

**Comment by kgroschoff** [comment]
There is an open issue for the health status #1485, because currently we only get true or false for a master component, which makes it nearly impossible to detect if they are running, failed or pending.  :sweat_smile:

I think we could definitely think about adding more stuff in it 👍 

And yes the UI will use it.
