### ISSUE TITLE
API checks if a project has been initialised

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#1861]
**User Story**
As a user of kubermatic API server I'd like it to detect and signal back when I'm trying to do operations associated with projects resource that hasn't been initialised yet. Creating a project is a asynchronous operation. It kicks off the controller that performs initialisation. The controller updates the status of the project once it finishes. API server should check if the project resource has been initialised and if not it should yield back an error. Possibles error codes could be 202 or 503 or something else ? (See also: https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/1860)

How to check if a project has been initialised ?
```
type Project struct {
	NewObjectMeta
	Status string `json:"status"`
}
```
the project's status field must be set to `active`

Possible implementation:
Change GET method of the rbac compliant project provider so that it accepts "options" (similarly to List method). If the option is not set then the provider will not check if the project was initialised. By default (if the option was not set) it checks if the project has been initialised. 

Next identify all possible places that don't require a project to be initialised in our API server and set appropriate option when getting the project.

**Acceptance criteria**
- API verifies if the given project has been initialised before allowing to an operation that requires it.

**Comment by p0lyn0mial** [comment]
@kgroschoff please make sure that our frontend checks the project's status field.

**Comment by kgroschoff** [comment]
sounds good 👍
