### ISSUE TITLE
[Kubermatic-Installer] [UI] Create base infrastructure

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1865]
We should plan, implement and document a base infrastructure for the kubermatic installer ui.

**Therefore we have to:**
* Settle on a web-framework to use
* Include a material-ui module to that framework
* Setup buildsystem
* Create a base component mixin/class/interface/ w/e, so we can later easily add things to all our components at once
* There should be generic boilerplate for field validation (as in: regex, alphanumeric, number, email, domain, ...) which should later be usable from each component.
* Define & document project structure (as in: which code/style/markup goes where, how are components splitted and reused, where are service abstractions (do we autogenerate them?), etc.)
* Define & document testing

**Comment by kron4eg** [comment]
done (with angular)
