### ISSUE TITLE
[Kubermatic-Installer] [UI] Advanced Mode

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1869]
**User Story:**
As a novice User I want to quickly setup a sane cluster without having to care about all the details, so I want to be able just to specify the minimum needed settings.
Also, as a more advanced User I want to be able to setup more detail things, like custom grafana rules, etc. 

**Description:**
Since not all available configuration settings are mandatory or even regularly used, we should be able to attribute components (including whole wizard steps!) as "advanced".
To define whether our wizard runs in "advanced" mode, the first step of the wizard should be the selection between Simple & Advanced mode.

**ACs:**
* First step of the wizard should be mode selection:
    * There should be two Radioboxes: Simple Mode and Advanced Mode
    * Simple Mode should be default
    * There should be a small explanation text beneath the individual modes
    * When switching from "advanced" to "simple" the user should be notified with a confirm-box that all related changes (as in: everything filled in "advanced"-flagged components) will be resetted to default (which, obviously, should be done aswell)
* Depending on the selection, the wizard should hide advanced steps, as in:
    * The forward/backword buttons should skip them
    * The steps should be hidden from the progress overview
* There should be generic boilerplate to flag any component as "advanced" which then should be hidden and filled with their default values.
* There should be documentation on how to flag components as "advanced" and how to programatically  get that information

Mockup:
![image.png](https://images.zenhubusercontent.com/5b644b515ee8b743f67f4fb9/7b2cdc09-a358-4f2e-9728-6f35cd676ef3)

**Comment by toschneck** [comment]
@pkavajin it would be also helpful,if we can modify some setup/config files over the UI. If we then may add a new feature what's currently not added to the UI installer, we would also be able to configure it over a in-build editor. Therefore the [ACE editor](https://github.com/ajaxorg/ace) works pretty well in the former project.

**Comment by kdomanski** [comment]
The whole purpose of the installer is to insulate the customer from manually fiddling with the files. If we let the customers edit the files then they will break their installations and complain about it.

**Comment by toschneck** [comment]
@kdomanski I can't agree. If I can use 90% of the "simple" installation and only have to add some special config or fresh enabled feature (which is not already implemented in the UI) I can only adjust one small config. This is more comfortable then do the manual setup completely file based. It even looks more professional and I would expect such a feature from a enterprise product. 
If someone add bullshit -> his fault (maybe a warning should pop up). The same approach is done by OpenShift UI and everywhere where you can apply a `.yaml` file.

**Comment by xrstf** [comment]
It's IMHO a lot simpler, especially for an MVP, to tell the user on the last wizard page that they can download the generated configuration (the "manifest") and review it. We can even be so bold and tell the user "please note that some customization options might not have been available in the wizard yet", though this would create a kind of "third level" of advancedness: simple, advanced and "super advanced".

Another reason for me to advocate killing the advanced mode in the wizard entirely, offer all steps with sensible defaults and then tell the user that there might be even more in the manifest after they've downloaded it.

**Comment by toschneck** [comment]
IMHO the sensible data is ok, because if you setup a meta orchistrator you should be aware that the config has sensible data. Also the people who setup a master cluster should be smart enough. Maybe a hint would be enough?

**Comment by xrstf** [comment]
This has nothing to do with Kubermatic itself and so far this has not been important. When the need arises, we should open a new issue in https://github.com/kubermatic/kubermatic-installer.
