### ISSUE TITLE
[Kubermatic-Installer] Kubernetes Dependencies

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1876]
**User Story**
As a user i don't want to manually install all the needed dependencies for kubernetes, yet I want to be able to specify which kubernetes/docker version the seed cluster uses. 

**Additional Notes:**
For the moment the backend implementation should only care about ubuntu, in the future followup stories probably will appear for further distributions.

**Acceptance criteria**
UI:
* A "Versions" step has been implemented:
* There should be a dropdown to select the kubernetes version (aka version for kubeadm/kubelet)
* The list of available kubernetes versions is defined by loodse
* Also, a second dropdown to select the docker version (source also defined by loodse) should be provided.
* Default value for both should be the newest available (as in: defined by loodse) version.
* The "Versions" step is flagged as "Advanced"
* There should only be a read-only text field telling the user the kubermatic version he's installing

Backend:
* A backend task has been implemented for setting up k8s dependencies (atm only on ubuntu):
    * Specific versions (as in: user defined in the manifest) of kubelet, kubeadm and docker get installed
    * The installed packages get flagged as "hold" in apt to disable auto updates.

Mockup:
![image.png](https://images.zenhubusercontent.com/5b644b515ee8b743f67f4fb9/e6106eae-fdcc-4378-ab36-8555ba9434f8)

**Comment by pkavajin** [comment]
@kdomanski please attach a matrix of supported kubernetes/docker versions for the seed clusters.

**Comment by kdomanski** [comment]
**Kubernetes: `1.9.0` and higher**

In general, we support versions enumerated in https://github.com/kubermatic/kubermatic/blob/4d468ffbb63a544a7b8353551d02581d776f88b4/config/kubermatic/static/master/versions.yaml
1.8 support will be dropped soon, so we're not advising it for new installations.

**Docker: `1.13.1` and higher**

The version available in CentOS 7 repos is `1.13.1`.
The version available in Ubuntu Xenial repos is `17.03.2`.
CoreOS typically has the latest or almost latest version bundled. At this time it's `18.03.1`.

**Comment by kron4eg** [comment]
closed in favour of kubeone
