### ISSUE TITLE
/api/v1/ext/aws-us-west-2/keys: KeyPairs isn't always a list

### ISSUE THREAD

**Issue by j3ank** [kubermatic/kubermatic#188]
where there are no keys configured for a region, the response is
```
{"KeyPairs":null}
```
this breaks code that is written in the assumption that `KeyPairs` is always a list.

we should clarify if KeyPairs is nullable or not.

**Comment by scruplelesswizard** [comment]
@mrIncompetent can you please review and clarify? Is this coming from the AWS SDK, or are we returning the `nil`? If we are returning it, can you modify the code so it returns an empty list.

**Comment by mrIncompetent** [comment]
Already fixed!
