### ISSUE TITLE
cluster details / node details lacks instance type

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1881]
**User Story**

As a user I would like to see the instance type of a specific node. This is neither in the list nor in the details which open when clicking on a list entry.
I can see it when I click the duplicate node button.

**Acceptance criteria**

The user can read the instance type (e.g. t2.small) in the list (or the details).

**Comment by kgroschoff** [comment]
closed, duplicate of: https://github.com/kubermatic/dashboard-v2/issues/754
