### ISSUE TITLE
[Kubermatic-Installer] Node Setup

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1883]
**User Story**
As a user I want to specify my already provisioned machines on the installer so it setups Kubernetes on it.

**Acceptance criteria**
UI:
* A "Nodes" step exists in the wizard
* It should NOT be flagged with "advanced"
* There should be a table of nodes with the following columns:
    * Public IP
    * Private IP
    * Username - used for ssh access
    * IsMaster - A flag whether this is a master or worker node
    * Actions - EDIT and DELETE Buttons
* Pressing the delete button should show a confirmation popup before deleting the entry
* Pressing the edit button should open a formular where I can edit the public/private ip, username and a checkbox to toggle whether the node should be a master
* When no nodes have been added to the table, there should be a default text, stating that no nodes have been added yet.
* There should be a ADD button which opens a formular where I can put in the public/private ip, username and a checkbox to toggle whether the node should be a master
* A validator should check that atleast 3 worker and 3 master nodes exist.
* Beneath the table there should also be a field to specify the SSH key used to access the machines
* A validator should check that a ssh key has been specified as well.

Backend:
* The ssh connections should be tested BEFORE installing any components on the nodes.
* Connection to the node should be established using the specified SSH key
* Tasks should be implemented to deploy a Kubernetes Installation onto the specified machines and check its health:
    * A task should setup the kubeadm MasterConfiguration
    * A task should create the etcd pod manifest
    * A task should create the relevant certificates
    * A task should deploy the etcd manifest
    * A task should should create the kubeconfig for the kubelet
    * A task should validate that etcd comes up
    * A task should bootstrap the remaining components using kubeadm init and validate the clusters health
    * A task should deploy a cni network module (flannel)
    * A task should set the public address to the kubeproxy config
    * A task should join the worker nodes to the cluster
* The values for NODEPORT_RANGE, POD_SUBNET, SERVICE_SUBNET should be hardcoded for the moment, a follow up story will handle customizable subnets/ranges.

Mockup:
![image.png](https://images.zenhubusercontent.com/5b644b515ee8b743f67f4fb9/47a1f1a9-ec0f-4f28-b24e-28a056c0e74b)

**Comment by xrstf** [comment]
Obsoleted for the MVP by the decision to use a pre-existing Kubernetes cluster instead.

**Comment by kron4eg** [comment]
closed in favour of kubeone
