### ISSUE TITLE
Epic: Seed-Cluster Backups

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#1885]
Customers shall be provided with a backup solution for the contents of seed clusters that allows manual restores in case of hardware failures. This epic describes the general idea and links to the individual tasks associated.

We want to use [Ark](https://github.com/heptio/ark) to perform backups for us. A "backup" consists of Kubernetes manifests (deployments, configmaps, secrets, ...) and the contents of persistent volumes. Ark in itself cannot handle all cloud providers that Kubermatic supports, which is why we are going to use Ark's native [restic](https://github.com/restic/restic) integration. While Ark itself uses the API from cloud providers to create volume snapshots, restic works on a per-file basis and simply reads files from the volumes directly.

For more information on the decision process, see issue #1271.

**Comment by kdomanski** [comment]
@xrstf Is this epic finished, or are there issues that need to be attached to it?

**Comment by xrstf** [comment]
Minus instability on preemtible nodes, this is working.

**Comment by kdomanski** [comment]
Does that mean you will attach a new issue or that you will close the epic?
