### ISSUE TITLE
Allow scraping of usercluster resources

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1903]
**User Story**
As a user I want to create custom dashboards for tracking resources which get deployed to the user cluster as an kubermatic addon. For example a nginx ingress controller which I deploy to all my user clusters.

**Acceptance criteria**
* Prometheus should be able to scrape pods/resources running on the user cluster
-> Implementation detail: We could use the openvpn side car for that
* I should be able to define custom scraping configs and rules to scrape those resources

**Comment by kron4eg** [comment]
I came across this blogpost: https://banzaicloud.com/blog/prometheus-federation/ and that make me think, can we, instead of openvpn sidecar, use proxy API too.

**Comment by thetechnick** [comment]
**Recap of slack history:**
After discussion between @kron4eg and @mrIncompetent, we had first settled on using the openvpn-client sidecar of #2149 to speed up the implementation.
But permission issues with the `SecurityContext` of the prometheus deployment, changed our decision to go with the kubernetes proxy API instead.
