### ISSUE TITLE
Grafana Nodes Dashboards for Usercluster

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1904]
**User Story**
As a user I want to monitor the usercluster nodes in the same way I can monitor the seed cluster nodes.

**Acceptance criteria**
* The same grafana dashboard we're offering for the seed cluster on kubernetes/nodes should be offered for the usercluster nodes.
* There should be a dropdown for selecting the individual clusters
* The dashboard should be put onto a folder which makes clear that this dashboard is related to user clusters.

**Comment by toschneck** [comment]
@pkavajin also one graph per cluster where the overall cpu/memory/availability with each node as a line will be helpful

**Comment by xrstf** [comment]
Providing this would require us to install the node-exporter into the user cluster and have it run on all user nodes. This is not something we want to support/maintain out-of-the-box in kubermatic.

If this is still an actual hard requirement from the customer, please re-open and consult @mrIncompetent about the proper way to handle this (deploying additional dashboards is already easily doable for customers without us having to provide them).
