### ISSUE TITLE
Quotation marks break the cloud config

### ISSUE THREAD

**Issue by cbeneke** [kubermatic/kubermatic#1905]
**User Story**
As a user I want to be able to use the full range of allowed characters in passwords without breaking my cluster

**Acceptance criteria**
* Any character (especially ") may be used in the password

**Comment by cbeneke** [comment]
This may only affect OpenStack, I could not test it on other providers so far. When a customer uses a " in the password, the quotation of the password breaks (ending at the ") and e.g. the controller-manager has troubles connecting to the cluster.

fix/escape-quotationmarks-cloudconfig addresses this issue. As I'm quite new to golang there might be a more performant/better solution to this. This might affect other cloud providers aswell.

**Comment by cbeneke** [comment]
Closing in favor of https://github.com/kubermatic/machine-controller/issues/304

**Comment by cbeneke** [comment]
Reopening since this should also affect the way the cloud-controller and apiserver interact with the cloud-config (the configMap is not escaped either)

**Comment by bashofmann** [comment]
Closing because it is fixed with https://github.com/kubermatic/machine-controller/pull/310
