### ISSUE TITLE
possibility to add custom node labels at the user cluster level 

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#1906]
**User Story**
As a Kubermatic user I wan't to be able to set some custom node labels, so that I can use in my user cluster deployment some special nodes. In Example I want to create some cheap standard work nodes and and some high-performance nodes which have other VM settings, like example SSD.  On AWS we already add a label like `beta.kubernetes.io/instance-type=t2.small`, but for e.g. vSphere we don't have any labeling opportunities.

Could be a quick-win for general node handling, before we implement #1680. 
Also some potential customers ask for this in Kubermatic demos.

**Acceptance criteria**
* A custom `key=value` can specified in the UI, independent of the cloud provider
* The created nodes get labeled and listed if I execute `k get nodes -l key=value`

**Comment by mrIncompetent** [comment]
I think this is already available via the API :thinking: 
cc @kgroschoff ?

**Comment by kgroschoff** [comment]
In the UI we currently could set `tags` for AWS (key-value) and DO (list of strings). For all other providers there is no field for that.

We had labels in the metadata in our endpoints:
```
      "labels": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string"
      },
```
But with the new project endpoints this field isn't there anymore.

So I think this is not completely available in the API and therefor an open task.

**Comment by toschneck** [comment]
@kgroschoff but the tags won't be set to created kubernetes node object

**Comment by toschneck** [comment]
@kgroschoff do we have a timeline for this? @pkavajin will be useful for shaw.

**Comment by kgroschoff** [comment]
PING @kdomanski

**Comment by kdomanski** [comment]
> A custom key=value can specified in the UI, independent of the cloud provide

You cannot really make it independent of the cloud provider, because like @kgroschoff different providers have different concepts of tags. That being said, it wouldn't be that complex to implement for providers where we don't support it yet - it would simply behave differently depending on the provider, but...

> The created nodes get labeled and listed if I execute `k get nodes -l key=value`

Node labels/roles and instance tags are different concepts. Trying to reconcile them would require a design proposal and all in all might actually not be worth it, seeing how the work on MachineDeployment is steadily progressing.

@alvaroaleman WDYT?

**Comment by alvaroaleman** [comment]
Actually this does not have much to do with `MachineDeployments` or not `MachineDeployments`. Both our downstream machine types and the upstream types contain a `metav1.ObjectMeta` in `Spec` which our machine-controller already applies.

So the only thing we would have to do for this would be:

* Extend the api to allow setting `machine.Spec.Labels` / `machinedeployment.spec.template.labels`
* Espose that in the UI

**Comment by maciaszczykm** [comment]
Linking with issue from Dashboard's repo: https://github.com/kubermatic/dashboard-v2/issues/354

**Comment by maciaszczykm** [comment]
I'd like to confirm that we would like to add the labels to `machinedeployment.spec.template.labels` not the `machinedeployment.labels`. 

cc @alvaroaleman

**Comment by alvaroaleman** [comment]
The field is `machinedeployment.spec.template.spec.labels`, not `machinedeployment.spec.template.labels`. They must end up in the machines spec, then the machine-controller will put them onto the nodes and you can create pods that have a `labelSelector` to run on the machines of a specific MachineDeployment
