### ISSUE TITLE
Use new /api/v1/providers/* routes in the FrontEnd

### ISSUE THREAD

**Issue by glower** [kubermatic/kubermatic#1940]
**User Story**

This is a FE part of this ticket: https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/1856

Please map the routes:
* /api/v1/azure/sizes => /api/v1/providers/azure/sizes  
* /api/v1/digitalocean/sizes => /api/v1/providers/digitalocean/sizes 
* /api/v1/digitalocean/sizes => /api/v1/providers/openstack/networks
* /api/v1/openstack/securitygroups => /api/v1/providers/openstack/securitygroups
* /api/v1/openstack/sizes => /api/v1/providers/openstack/sizes
* /api/v1/openstack/subnets => /api/v1/providers/openstack/subnets
* /api/v1/openstack/tenants => /api/v1/providers/openstack/tenants
* /api/v1/vsphere/networks => /api/v1/providers/vsphere/networks

**Acceptance criteria**
All routes in the frontend are moved to the new

**Comment by glower** [comment]
Please ping me after this ticket is done. I will remove old routes and redirects from the backend code

**Comment by kgroschoff** [comment]
will close this, as it's a duplicate of https://github.com/kubermatic/dashboard-v2/issues/761

But yes, will ping :)
