### ISSUE TITLE
dns-resolving broken with ubuntu-18.04 and kubeadm < 1.11

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1942]
**Background**

Ubuntu 18.04 uses systemd-resolve and changes `/etc/resolv.conf` to point to itself (`127.0.0.53`). Network namespaces on this host with a configured loopback interface with `127.0.0.1/8` (pretty much almost the case). Will not be able to reach that host-address because it is routed directly to the netns' lo-iface.

Upstream workarounded this by using the kubelet flag `--resolv-conf=/run/systemd/resolve/resolv.conf` to use the original resolv.conf (which has the cloud-provider's nameserver). This upstream change landed with kubeadm in 1.11 (see https://github.com/kubernetes/kubernetes/pull/64665).

**Problem**

As a result of the above ubuntu-18.04 based clusters with k8s version < 1.11 are severely broken (no public dns, no vpn connection between user/seed, and more).

**Approach for fix**

For k8s versions < 1.11 on ubuntu-18.04 we should supply the `--resolv-conf` flag unconditionally (as we know that we are using systemd-resolv then).

**Comment by mrIncompetent** [comment]
Its `/run/systemd/resolve/resolv.conf`, not `/run/systemd/resolv/resolv.conf`

**Comment by mrIncompetent** [comment]
Fixed with https://github.com/kubermatic/machine-controller/pull/314
