### ISSUE TITLE
Documentation: CLI Machine creation

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#1973]
**User Story**
As a user I want to be able to create machines in a cluster using kubectl.
Therefore I want documentation on whats important and how to do it. 

**Acceptance criteria**
* docs.kubermatic.io should contain a page about cli cluster creation
* There should be an explanation of all the fields of the machine struct.
* Fixed formats (e.g. nodename should be machine-CLUSTERNAME-foo) should be documented
* It should be also documented on how to safely remove the machines
* There should be at least one example for a working machine yaml

**Comment by alvaroaleman** [comment]
Closing as wontfix as this is a non-supported use case
