### ISSUE TITLE
[Kubermatic-Installer] Cloudprovider Configuration - Custom - Backend

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#1974]
**User Story**
As a user I want to choose on which cloud i want to run the seed cluster. This is the backend part of #1875.

**Acceptance criteria**

Backend:
* A task has been implemented to handle the custom cloud provider:
    * It extends the kubeadm-config with "cloudProvider" and "cloud-config" flags.
    * It creates a new systemd service config file for all nodes and sets the specified cloudprovider flag
    * It creates and sets the specified cloud-config on all nodes.

**Comment by kron4eg** [comment]
closed in favour of kubeone
