### ISSUE TITLE
OpenStack clusters are not deleted properly when a LoadBalancer exists in the cluster

### ISSUE THREAD

**Issue by bashofmann** [kubermatic/kubermatic#1985]
When we try to delete an OpenStack cluster that has a Service with the type "LoadBalancer", the cluster hangs at the `kubermatic.io/cleanup-openstack-network` finalizer because the cluster's network can't be deleted before the OpenStack loadbalancer including its pool, listener and security group are deleted.

Either the Service resource needs to be deleted manually before deleting the cluster (which will trigger Kubernetes to delete the LB resources in OpenStack), or the cluster creation logic needs to check for OpenStack resources that are attached to the network and clean these up as well.

**Comment by bashofmann** [comment]
@mrIncompetent Could we bump this a bit in priority? Customers are starting to run into this problem very frequently.

**Comment by bashofmann** [comment]
Backend part is implemented in https://github.com/kubermatic/kubermatic/pull/2514, but this should be kept open until https://github.com/kubermatic/kubermatic/issues/2449 is done.

**Comment by kdomanski** [comment]
@bashofmann Is this still an issue in the current version?

**Comment by mrIncompetent** [comment]
@bashofmann we have code in place to cover this. Please reopen if it does not work
