### ISSUE TITLE
AWS creates security groups with Allow All

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#202]
Currently the API creates an AWS SG allowing all traffic from everywhere. This should be modified to only allow required traffic from specified addresses

**Comment by scruplelesswizard** [comment]
https://github.com/kubermatic/api/pull/192

**Comment by mrIncompetent** [comment]
@chaosaffe please clarify which addresses you would like to allow

**Comment by mrIncompetent** [comment]
Not needed atm
