### ISSUE TITLE
remove all `v3` routes

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#2023]
**Description** Once the dashboard switches to `v1` endpoints, all `v3` endpoints will be unused. Thus they should be removed from API server. We don't have to maintain the backward compatibility because the dashboard is our only client.

**Comment by mrIncompetent** [comment]
Syseleven is using a fork of our Dashboard. The switch from v3 -> v1 is basically the usage of the new project endpoints.
cc @bashofmann @multi-io
