### ISSUE TITLE
Store SSH Keys in TPR on seed-cluster

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#203]
We need to store and manage SSH Keys within Kubermatic. This abstracts us away from the cloud providers implementation.

We will need endpoints to 
* list
* create
* delete 

SSH keys. 

The structure of the SSH key should be `Name: string, Fingerprint: string, PublicKey: string`

**Comment by mrIncompetent** [comment]
Before implementing the endpoints, please create a swagger spec!

**Comment by lbb** [comment]
Things ToDo:
- [ ] Add SSH types to API
- [ ] interact with k8s-TPR functions (User encapsulated SSH-store)
  - [ ] Create
  - [ ] Delete
  - [ ] List
- [ ] Implement handlers form swager-spec
