### ISSUE TITLE
Grafana machine controller dashboard: Allow chosing clusters by name, not by ID

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2037]
**User Story**

As a user I want an intuitive way to choose my cluster in the Grafana machine-controller dashboard. Hence I want to use the name I see in the dashboard, not the internal ID why I may not even know about

**Acceptance criteria**

* In the grafana machine-controller dashboards, clusters can be selected by name

**Comment by alvaroaleman** [comment]
@mrIncompetent Suggested to use `fmt.Sprintf("%s/%s (%s)", project.Name, cluster.Spec.HumanReadableName, cluster.Name)` as cluster name

**Comment by mrIncompetent** [comment]
This is just a nice to have as the Grafana dashboards are primarely targeted to people operating kubermatic. We expect that those folks are able to handle cluster id's.
Not the end users who create clusters.

**Comment by xrstf** [comment]
From what I've gathere in the Grafana documentation, it's not possible to have associative variables, i.e. have something like `{"3rzgfsuzfg": "My Cluster (3rzgfsuzfg)", "bfuz28rrf": "Another Cluster (bfuz28rrf)"}`. Variables are a plain list of values.

Given this, we would need a pre-made label on not just the `cluster_info` metric, but also tag all other cluster-related resources with the same human-readable label. I think that's not really something we want for the minor convenience of having a nice dropdown in Grafana.

**Comment by mrIncompetent** [comment]
So this can be closed?

**Comment by xrstf** [comment]
I think so, just wanted to give you guys the opportunity to interject and correct me :)
