### ISSUE TITLE
Document configuring Dex

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#2062]
Document how to configure auth with:
 - LDAP
 - OAUTH
 - SAML
 - Active Directory

**Comment by kron4eg** [comment]
@kdomanski should we replicate dex's original documentation?

**Comment by kdomanski** [comment]
Only to the extent of needing to configure it `values.yaml`. This issue is moved over from the CF org and _might_ become obsolote when the configuration is done through the new installer.
