### ISSUE TITLE
[Research] Look into K8S audit logging.

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#2082]
**User Story**
For many customers, it would be preferable to have Kubernetes audit logging enabled. The feature is available as beta in Kubernetes 1.11+ and requires a logging backend to be configured. We need to agree on a default supported solution for the backend and test whether the impersonated user data from kubermatic apiserver calls is consistently and fully there.

GKE already offers its own audit logging and is enabled on `dev`, but it seems that it maybe inconsistent with normal K8S audit logging because some data appears to have been stripped. We need to test this on a vanilla K8S 1.11 seed cluster.

**Acceptance criteria**
- [x] a default backend solution for audit logs storage has been picked
- [x] a vanilla Kubernetes 1.11 seed cluster has been deployed for the duration of the experiment
- [x] it's been confirmed that the full user information coming from kubernetes apiserver is present in the audit logs pertaining operations performed by the kubermatic apiserver
  - [x] if that is not the case, then user stories are created to address the issue

**Comment by kdomanski** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#dynamic-backend

**Comment by scheeles** [comment]
1. Enhance the cluster resource with the flags for enabling the Auditing
2. Create a config to enable Auditing per Datacenter

@mrIncompetent @alvaroaleman @kdomanski Please add your thoughts 

What  backends type do we want support?
Log backend or Webhook backend or both?
As Dynamic backends is still alpha I would see this out of scope
