### ISSUE TITLE
Document development flow

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#210]

**Comment by mrIncompetent** [comment]
Maybe should be done together with the move to drone ci

**Comment by mrIncompetent** [comment]
My idea:


Branches:
-master
-release/v1.0
-feature/foo
-bugfix/bar

feature/foo -PR against-> master
bugfix/bar  -PR against-> master

Jenkins (gets triggered by every push):
- Lint
- Build
- Test
- Standup clusters for every provider & run e2e tests (Maybe not on every push??? @chaosaffe )
- deploy to dev (Only on PR)

Releases:
-Create release branch from master
-Create github release with appropriate version on github
-Jenkins will get triggered by release
  -build&push image with release tag
  -deploy on beta

Bugfix which needs to get into a release:
-Cherry pick commit and open PR against release branch
-Create new release from release branch (use semver)

Release tag examples:
v1.0
v1.0.1


Any other ideas @scheeles @chaosaffe @realfake @j3ank @susman

**Comment by aklinkert** [comment]
Jenkins? WTF? 🤔

**Comment by scheeles** [comment]
LGTM
