### ISSUE TITLE
Adapt E2E testing

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2104]
**User Story**
To have a decent E2E testing, we need to cover:
- every cloud-provider
- individual test scenarios
- each supported version

For debugging, the test results should be uploaded to gcs or something
**Acceptance criteria**

**Comment by kron4eg** [comment]
@mrIncompetent seems like we'd need to decouple e2e testing somehow from "deploy" event, as it will drive costs significantly up. Probably run it on schedule, once a day or something like that, WDYT?

**Comment by mrIncompetent** [comment]
Good idea, we're thinking about utilizing prow to execute the tests whenever someone adds a specific comment on a PR.

**Comment by mrIncompetent** [comment]
Closed in favor of a proper epic https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/2167
