### ISSUE TITLE
Define and align Github Labels

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#211]

**Comment by scheeles** [comment]
My idea would be this: 

- priority/... ( Emergency, Urgent, Normal, Non-urgent )
- bug
- enhancement
- refactoring
- review
- in progress
- customer request 
- duplicated 
- needs details

**Comment by scruplelesswizard** [comment]
I prefer integers for the priority, makes the order much clearer. If we use words I would suggest
{critical, urgent, important, trivial}. Emergency implies that something must be done immediately, so you would not usually create a ticked for that (i.e. Production system is down)

**Comment by scheeles** [comment]
I prefer names because with names it is directly clear what is behind it. What we could do is e.g. `priority/P2 Urgent` to make the order clear. With names it is directly clear what goes in what prio.  We could call it also critical, but this means all other task should be stopped and we that's the main prio for work. Normally we should not have any critical issue

**Comment by mrIncompetent** [comment]
@susman this can be called done?
