### ISSUE TITLE
Move datacenters into CRD

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2113]
Epic to group all actions required to move the `datacenters.yaml` into CRD's

**API**
- ~Implement endpoint to return SeedDatacenter's from CRD instead of file~
- ~Implement endpoint to return NodeLocation's from CRD instead of file~
- Implement a new endpoint that returns `Datacenters` only and not `Seeds`
- Make the new endpoint return `Datacenters` with a new type that doesn't contain any info about their seed
- Mark the existing endpoint that returns both `Seeds` and `Datacenters` as deprecated

**UI**
- ~Replace existing datacenters endpoints with new SeedDatacenter & NodeLocation endpoints~ Use  the new `Datacenter` endpoint that returns `datacenters` only and not `Seeds`

**Controller**
- ~[Add new CRD's](https://github.com/kubermatic/kubermatic/issues/2114)~
- ~[Add migration step to migrate the existing datacenters.yaml to CRD's](https://github.com/kubermatic/kubermatic/issues/2116)~
- [Remove handling of datacenters in all controllers by copying all fields to the cluster spec](https://github.com/kubermatic/kubermatic/issues/2118)
- [Implement a `MutatingAdmissionWebhook` to handle defaulting & validation for clusters](https://github.com/kubermatic/kubermatic/issues/1688)

**Docs**
- Document required migration steps
- Document how to create new SeedDatacenter's & NodeLocation's

**Comment by alvaroaleman** [comment]
cc @kdomanski
