### ISSUE TITLE
Add migration step for `datacenters.yaml` -> CRD

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2116]
**User Story**
To make the switch from `datacenters.yaml` -> CRD's as easy as possible, a migration step should be implemented which will convert the passed `datacenters.yaml` to the relevant CRD (SeedDatacenter/NodeLocation).
The migration step should be part of our existing migration cmd: https://github.com/kubermatic/kubermatic/blob/master/api/cmd/kubermatic-controller-manager-cleanup/main.go

Flow:
- Check if `datacenters.yaml` has been passed via flags
  - If not -> Skip the migration step (If its a new system, it probably has no `datacenters.yaml`)
- Parse `datacenters.yaml`
- Iterate over `datacenters.yaml->datacenters`
  - Take the key as `name`
  - Determine if it is a SeedDatacenter or NodeLocation (Via `is_seed: true`)
  - Check if the CRD already exists
    - Yes: Skip (Do not make any modifications)
    - No: Create a new CRD based on the given data

**Acceptance criteria**
- [ ] A migration step has been added to https://github.com/kubermatic/kubermatic/blob/master/api/cmd/kubermatic-controller-manager-cleanup/main.go which implements the above mentioned flow.
- [ ] A unit test exists which covers the basic logic of the above mentioned flow

**Comment by kdomanski** [comment]
Needs more research.

**Comment by mrIncompetent** [comment]
@kdomanski What details are missing here exactly?

**Comment by kdomanski** [comment]
I don't remember, this comment was an outcome of discussion during backlog grooming.

**Comment by xrstf** [comment]
As the original controller mentioned in this issue does not exist anymore *and* Seed CRs are automatically copied into each seed (by the seed-sync controller), I will put the migration logic into the Master Controller Manager.
