### ISSUE TITLE
Remove handling of datacenters in all controllers

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2118]
**User Story**
To make cluster resources independent(the single source of truth), all fields from the Datacenter/NodeLocation must be copied to the cluster spec.

**Acceptance criteria**
- [ ] A migration step has been added to migrate existing clusters (Copy data from the datacenter to cluster)
- [ ] All kubermatic controllers do not use the Datacenter 
- [ ] Defaulting logic gets extended to copy fields from the datacenter to the cluster during creation

**Comment by kdomanski** [comment]
Needs more refinement.

**Comment by mrIncompetent** [comment]
@kdomanski What is missing here?

**Comment by kdomanski** [comment]
I don't remember, this comment was an outcome of discussion during backlog grooming.
