### ISSUE TITLE
master "edit settings" broken

### ISSUE THREAD

**Issue by multi-io** [kubermatic/kubermatic#2127]
**User Story**

Setting the adminToken to "" in cluster responses in cf2d7bb91bb7a54f804023eec45b4b7a952cb89c seems to have broken the "Edit Settings" (editProviderSettings()) feature in the UI, which now posts a cluster object with empty adminToken to /api/v3/dc/dbl1/cluster/{cluster}, resulting in a 400 response ("invalid cluster: invalid admin token: token is malformed, must match [bcdfghjklmnpqrstvwxz2456789]{6}\\.[bcdfghjklmnpqrstvwxz2456789]{16}").

We're using 2.7.7 currently.

**Acceptance criteria**

"Edit Settings" in the dashboard should work.

**Comment by multi-io** [comment]
We wrote a small patch ourselves (based on 2.7.7) that keeps the adminToken intact in all cluster responses, and that fixes this issue. We've already rolled this out to our installations, so the problem isn't urgent for us. I would've created a PR, but the patch isn't based on master, and we're not entirely sure if this would be your preferred solution anyway :)

**Comment by p0lyn0mial** [comment]
@multi-io thanks for letting us know, at the same time I'd like to apologise for recently increased amount of defects.

I was thinking about something like this https://github.com/kubermatic/kubermatic/pull/2136

**Comment by multi-io** [comment]
It's all good, reviewing your PR right now :)
