### ISSUE TITLE
API endpoint which returns created clusters without iterating over all clusters for each seed-dc

### ISSUE THREAD

**Issue by mrahbar** [kubermatic/kubermatic#213]
Endpoints will be the following:

- GET "/api/v1/clusters"
~~- GET "/api/v1/clusters/{id}"~~

Additionally the endpoints can be summarized in a swagger spec.

**Comment by mrIncompetent** [comment]
Make sure, on cluster creation we're not running into name collisions

**Comment by mrahbar** [comment]
Edit: Dropped endpoint GET "/api/v1/clusters/{id}" because id are not generated per created resource but are user defined names which have can potentially collide.

**Comment by mrIncompetent** [comment]
Currently not necessary

**Comment by mrahbar** [comment]
After backend anlysis this additional endpoint is associated with an unreasonable effort which does not justify ATM. Frontend will call first dc/:dc/cluster/:cluster and iterate over clusters. If this will increase in an untenable hassle this issue will be opened again.
