### ISSUE TITLE
Enable OpenID Connect as optional login method for user cluster 

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#2138]
**User Story**

As a user-cluster admin I want provide different users different access on resources for a user cluster . The token should be used initial login method, afterwards I can enable specific user to access only specific resources. 

Enable OpenID Connect as optional (additional to the token) login method for user clusters. This should be a global option (additional to the token). When this option is enabled enabled all user cluster should connect to our central dex.

See also: 
https://github.com/dexidp/dex/blob/master/Documentation/kubernetes.md#configuring-the-openid-connect-plugin

**Acceptance criteria**

A user can only have access to a specific `namespace` inside a user cluster

**Comment by mrIncompetent** [comment]
cc @kdomanski

**Comment by scheeles** [comment]
https://github.com/kubermatic/kubermatic/pull/2236

**Comment by alvaroaleman** [comment]
Closing as duplicate
