### ISSUE TITLE
Limit node cpus on vsphere

### ISSUE THREAD

**Issue by pkavajin** [kubermatic/kubermatic#2139]
**User Story**
As a user I want to be able to specify the amount of CPUs for the nodes I create.
Since vsphere limits the amount of CPUs per node to a maximum of 8, I want to be limited to that amount in kubermatic as well.

**Acceptance criteria**
* The inputfield for CPU count for nodes on "Cluster Creation" aswell as "Add Node" screen should have a maximum limit of 8 for vsphere:
    * When pressing the + Button on the control, it should stop at 8
    * When pressing the - Button on the control, it should stop at 1
    * When I enter a value higher than 8, an error should be displayed
    * When I copy-paste a value higher that 8 into that field, an error should be displayed aswell.
* Also please rename the field label from "cpu's" to "cpus"

**Comment by kgroschoff** [comment]
Sounds like a frontend task, WDYT @p0lyn0mial ?

**Comment by p0lyn0mial** [comment]
I think that we also need to adjust the API, it should also validate if the number of CPUs is not greater than 8.

**Comment by kgroschoff** [comment]
ok, then I will also create a single issue for the frontend 😃
