### ISSUE TITLE
Delete in-cluster resources when deleting client cluster

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#215]
Currently when we delete a client cluster we do not remove any of the resources within the client cluster, meaning that some cloud resources (i.e. Load Balancers, Storage Devices) are left on the cloud provider.

Before destroying the nodes and master components we should iterate through the resources (i.e pvc/svc/dep/rc/ds/etc...) on the client cluster and delete them, then destroy the cluster nodes and components.

**Comment by scheeles** [comment]
We should only delete the resources and let the namespace stay.  Then we could write third party resources which we need longer then the cluster itself. e.g usage of the cluster for billing. 

Create separate job for deleting the namespaces for deleted cluster e.g. after 30 days.

**Comment by kdomanski** [comment]
Needs more detail, split into backend and frontend parts.

**Comment by thz** [comment]
Adding some input according to slack discussions:
1) We do not want to delete volumes or LBs automatically on cluster deletion (just like google does not delete them).
2) We can have an option for deleting LBs with the cluster deletion.

**Comment by thz** [comment]
ping @mrIncompetent

**Comment by mrIncompetent** [comment]
Making it optional via a Checkbox in the UI sounds reasonable.
Though right now, the correct component to implement the cleanup would be the `cluster-controller`.
If anyhow possible, I would like to avoid it in the `cluster-controller`.

@thz Does it make sense to implement the `user-cluster-resources-controller` before?

The flow I have in mind when the user clicks delete with the checkbox "delete in cluster resources":
- Kubermatic-API somehow adds Finalizer `kubermatic.io/cleanup-in-cluster-resources` to the cluster resource
- Kubermatic-API deletes the cluster-resource
- `user-cluster-resources-controller` sees the finalizer and cleans up in-cluster resources. Afterwards it removes the finalizer


@thz WDYT?

**Comment by thz** [comment]
I see no need to rush that into the cluster-controller. And I want to start on the user-cluster-resources-controller really soon now.
The flow sounds good to me.

**Comment by thz** [comment]
So blocked by user-cluster-resource-controller refactoring.

**Comment by thz** [comment]
user-cluster-controller issue: #1706

**Comment by mrIncompetent** [comment]
Closed for https://github.com/kubermatic/kubermatic/issues/2450
