### ISSUE TITLE
Make the selection of tests opt-out instead of opt-in

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2173]
**User Story**
In the current way, we collect the test scenarios, we let each provider return a list of scenarios.
This list always contains a matrix of supported Kubernetes versions and operating systems.

To avoid us having to add a new test case to each cloud provider, we should rather provide a list, where each cloud provider must opt-out, to avoid having blind spots.

We have such a architecture already in the machine controller.

A possible way would be:
Each provider will implement a function (called `clusterForCommonScenarios`) which returns a "sample" cluster, sample nodes and a list of excludes. 
A "collect" function will call `clusterForCommonScenarios` for all providers and build a list of common scenarios. To opt-out from a specific scenario, a exclude can be specified.

```go
func clusterForCommonScenarios(secrets secrets) (*kubermaticv1.Cluster, []*kubermaticapiv2.Node, []*regexp.Regexp) {}
```

**Sample cluster**
This is just a cluster object with the cloud provider specific data set. It will be used to create a list of common scenarios (version*operating system).

**Excludes list**
This is a list of regular expressions which will be used when building the common scenarios. If a scenario name matches the regular expression, the scenario will be dropped/skipped.

**Acceptance criteria**
- [ ] All cloud provider scenarios return tests in a opt-out manner instead opt-in

**Comment by kdomanski** [comment]
Estimated as 5
