### ISSUE TITLE
Clean up deprecated create cluster code

### ISSUE THREAD

**Issue by aklinkert** [kubermatic/kubermatic#220]
When the old _create cluster_ and _set cloud_ endpoints are being removed we have to clean up the code from dirty hacks that have been made adding the net _create cluster_ endpoint.

Search for `Remove with https://github.com/kubermatic/api/issues/220` on the code. Here are some places:

Config:
- [ ] [api/templates/kubermatic-api-dep.yaml#L43](https://github.com/kubermatic/config/blob/5832a6cd47fc1d6e99c372dae8383806a0cdf021/api/templates/kubermatic-api-dep.yaml#L43)
- [ ] [api/templates/kubermatic-api-dep.yaml#L72](https://github.com/kubermatic/config/blob/5832a6cd47fc1d6e99c372dae8383806a0cdf021/api/templates/kubermatic-api-dep.yaml#L72)

API:
- [ ] [provider/kubernetes/kubernetes.go#L195](https://github.com/kubermatic/api/blob/1f957583b36ae173fc569b09b629127aea9fa9d1/provider/kubernetes/kubernetes.go#L195)
- [ ] [provider/kubernetes/kubernetes.go#L302](https://github.com/kubermatic/api/blob/1f957583b36ae173fc569b09b629127aea9fa9d1/provider/kubernetes/kubernetes.go#L302)
- [ ] [provider/kubernetes/kubernetes.go#L363](https://github.com/kubermatic/api/blob/1f957583b36ae173fc569b09b629127aea9fa9d1/provider/kubernetes/kubernetes.go#L363)
- [ ] [provider/kubernetes/kubernetes.go#L397](https://github.com/kubermatic/api/blob/1f957583b36ae173fc569b09b629127aea9fa9d1/provider/kubernetes/kubernetes.go#L397)
- [ ] [handler/cluster.go#L77](https://github.com/kubermatic/api/blob/1f957583b36ae173fc569b09b629127aea9fa9d1/handler/cluster.go#L77)
- [ ] [handler/cluster.go#L131](https://github.com/kubermatic/api/blob/1f957583b36ae173fc569b09b629127aea9fa9d1/handler/cluster.go#L131)
- [ ] [handler/cluster.go#272](https://github.com/kubermatic/api/blob/1f957583b36ae173fc569b09b629127aea9fa9d1/handler/cluster.go#272)
- [ ] [handler/cluster.go#279](https://github.com/kubermatic/api/blob/1f957583b36ae173fc569b09b629127aea9fa9d1/handler/cluster.go#279)

**Comment by mrIncompetent** [comment]
Done
