### ISSUE TITLE
Use kube_node_status_condition metric for monitoring nodes

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#2209]
**User Story**
Monitor and alert on `kube_node_status_condition{condition="Ready"}` metric in user-cluster prometheus

**Comment by mrIncompetent** [comment]
We should restrict the pods we monitor here - otherwise we get alerts if a customer is deploying some broken stuff.

**Comment by xrstf** [comment]
The metric monitors *nodes* and not pods, so I'm not quite sure what you mean here, @mrIncompetent ?

**Comment by mrIncompetent** [comment]
@xrstf Misunderstanding. I thought this is about pods, not nodes.
