### ISSUE TITLE
Create an endpoint for creating MachineDeployments

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#2212]
**User Story**
In order to introduce MachineDeployment support, we're going to need an API endpoint for the UI to add them.

The new endpoint shall be POST `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodesets` analogous to the existing POST `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodes` endpoint. Instead of a `Machine` CRD, it will create a `MachineSet`.

**Acceptance criteria**
 * A new `NodeSet` API structure exists to use for the new API endpoint.
 * A  POST `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodesets` endpoint exists, and sending a `NodeSet` object to to it results in a `MachineDeployment`.
 * There is a unit test for the functionality

**Comment by maciaszczykm** [comment]
>The new endpoint shall be POST `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodesets` analogous to the existing POST `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodes` endpoint. Instead of a `Machine` CRD, it will create a `MachineSet`.

@kdomanski Shouldn't it create `MachineDeployment`? 

At the moment my understanding is that we would like to have following mapping:

```
MachineDeployment ---> MachineSet ---> Machine
        ^                                 ^
        |                                 |
        |                                 |
Kubermatic NodeSet ------------------> Kubermatic Node
```

Is it true?

/cc @alvaroaleman

**Comment by alvaroaleman** [comment]
@maciaszczykm Your understanding is correct and it should indeed create a `MachineDeployment`
