### ISSUE TITLE
Monitor cluster addons

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubermatic#2226]
**User Story**
As cluster administrator, I want to monitor the cluster addons deployed by kubermatic to ensure their functionality.

Follow up to #1903, #2219

**Acceptance criteria**
- Cluster addons with prometheus endpoints are scraped
- Sane default alerting rules are in place to alert by failing cluster addons

**Comment by xrstf** [comment]
@kdomanski Can we discuss if and how we really want this?

**Comment by kdomanski** [comment]
Please create an appointment w/ you, @thetechnick and me.
