### ISSUE TITLE
Changing a project doesn't change selected tab

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#2235]
**User Story**
As a user of kubermatic's dashboard I can switch between projects by selecting project's name from the dropdown menu. The current implementation will always bring me to the `Project View` tab after selecting a new project. However I would like stay on the same tab, for example when I'm on `Clusters View` tab after changing the project I should be on the same tab. 

**Acceptance criteria**
Changing the current project should not move me to `Project View` tab.

**Comment by p0lyn0mial** [comment]
![Screenshot 2018-10-16 at 09.15.01.png](https://images.zenhubusercontent.com/5b644aa4e115f66327ad8122/351e1aa9-33c1-4e9a-9e16-55e321e41774)

**Comment by p0lyn0mial** [comment]
![Screenshot 2018-10-16 at 09.15.16.png](https://images.zenhubusercontent.com/5b644aa4e115f66327ad8122/03133581-60ba-456e-b2e5-77539528582e)

**Comment by kdomanski** [comment]
`AmberGold` xD

**Comment by p0lyn0mial** [comment]
> AmberGold xD

xD

**Comment by kgroschoff** [comment]
@p0lyn0mial frontend task, right? :D

**Comment by p0lyn0mial** [comment]
> @p0lyn0mial frontend task, right? :D

yes :)

**Comment by kgroschoff** [comment]
ok will move it to dashboard issues, for not loosing it :) https://github.com/kubermatic/dashboard-v2/issues/818
