### ISSUE TITLE
Extract the s3-exporter to a separate chart

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#2238]
**User Story**
Since 2.7, the s3-exporter has been introduced as a part of the kubermatic chart. This basically enforces the installation thereof in every kubermatic installation, unless removed by manual intervention. The exported must be moved to a separate chart.

**Acceptance criteria**
- [ ] the `s3-exporter` is a separate chart
- [ ] nothing `s3-exporter`-related remains in the kubermatic chart
- [ ] it is possible to split them on an existing install by an upgrade
- [ ] the fix is backported to `2.8`
- [ ] the fix is backported to `2.7`

**Comment by alvaroaleman** [comment]
@kdomanski Can you please explain _why_ the s3 exporter must be moved to a separate chart?

**Comment by kdomanski** [comment]
So that Amazon S3 isn't a hard requirement for running Kubermatic.

**Comment by alvaroaleman** [comment]
Amazon S3 is not a hard requirement, a hard requirement is to have something that is _S3 compatible_, by default this is Minio, but there are others apart from S3 itself, e.G. Openstack Swift has a S3 compatible API and  Ceph has the RadosGW for this.

We use the S3 compatible API to store backups, so IMHO it makes sense to keep the S3 exporter in the main chart, because if we don't have that exporter we can not alert on missing backups.

**Comment by xrstf** [comment]
So can we close this or do we still want to move it into a dedicated chart?

**Comment by kdomanski** [comment]
We had a mostly unresolved chat conversation about that. @mrIncompetent please make the call.

**Comment by mrIncompetent** [comment]
As we had this chat already on Slack:
S3 is not a hard requirement at all. 
We use S3 as the default mechanism to store backups of the user cluster etcd's. 
Though this can be easily replaced with any technology like`sftp`, ftp, - even doing a post request with `curl` would do the job.

Yes, we deliver S3 as default mechanism - We did a pretty good job on that :muscle: .
But the metrics exporter does not belong to the kubermatic chart.

Extracting the metrics exporter into an own chart seems generally fine.
Regarding the S3 credentials:
- They won't be duplicated by this move. They exist exclusively in the `minio` chart.
The minio chart creates the `kube-system/s3-credentials` secret, which gets consumed by the exporter & the store&cleanup container.
The exporter has the `kube-system` namespace currently hard coded.

If the minio chart should be responsible here to create that secret, is something i'm sceptical, but does not belong into this discussion.
