### ISSUE TITLE
[Investigation e2e] how to authenticate to dex

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#2243]
This issue is for investigation purposes for the upcoming e2e testing.

- How could software authenticate to dex?
- [space for further questions]

ping @kubermatic/developers

**Comment by alvaroaleman** [comment]
Dex has the option to configure static users: https://github.com/dexidp/dex/blob/0db538a4bbf4fc059d5bd29f0c84eee6b50a40c4/examples/config-dev.yaml#L84

We could do that and then just fake the login via curl or a mini go app to get a token

**Comment by p0lyn0mial** [comment]
> Dex has the option to configure static users

Perfects, this is something I was hoping for.

**Comment by p0lyn0mial** [comment]
> We could do that and then just fake the login via curl or a mini go app to get a token

Or just use the static credentials and perform normal flow to get the token.

**Comment by p0lyn0mial** [comment]
@alvaroaleman is there something else that block us from writing E2E tests for the Dashboard & API (other than the lack of tooling that would set up the test's infrastructure) ? If I recall correctly on the last dev meeting you said that we don't know how to authenticate the users programatically (from the tests) ?

**Comment by alvaroaleman** [comment]
WRT dashboard, I have no idea how frontend testing is done so I can't answer that.

WRT the api I _think_ if we have a valid token we can just adjust the existing testing to use our API rather than creating a cluster CRD directly. Can you confirm that @mrIncompetent ?

**Comment by mrIncompetent** [comment]
@kgroschoff @p0lyn0mial Is this still relevant?

**Comment by kgroschoff** [comment]
I don't think so

**Comment by p0lyn0mial** [comment]
not relevant anymore, thanks for closing.
