### ISSUE TITLE
Unify date format

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#2257]
**User Story** Noticed when working on #2254. Date format differs depending on currect localization, i.e.:

UTC:`"creationTimestamp":"2013-02-03T19:54:00Z"`
+1: `"creationTimestamp":"2013-02-03T20:54:00+01:00"`

Date is the same, but format is different. It may cause potential issues as it is applied during JSON unmarshal among others. In my case it caused test failure, because in tests we are checking mostly for UTC.

**Acceptance criteria** Like Kubernetes we should make sure that specific rule is used and follow it, i.e. https://github.com/kubernetes/kubernetes/blob/7cbb9995189c5ecc8182da29cd0e30188c911401/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L167-L176

/cc @p0lyn0mial

**Comment by p0lyn0mial** [comment]
one way of fixing this would be to create a custom type (for fields that hold time) and write custom Marshal and Unmarshal methods that would always encode/decode to desired format, WDYT ?

**Comment by maciaszczykm** [comment]
@p0lyn0mial I think that is a pretty clean solution. One thing that comes to my mind is conversions between these types. I am not sure if we wouldn't have any problems/additional workload caused by them.

**Comment by p0lyn0mial** [comment]
if we expect to get the time always in RFC3339 form (etcd) then if we encode/decode (api) to the same format we should we good, right :) ?

**Comment by maciaszczykm** [comment]
@p0lyn0mial Yep, it should be fine. I was thinking about conversion between types in the code, not format conventions :) It shouldn't be too many changes though.
