### ISSUE TITLE
add alerts for OOMKilled pods

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#2259]
**User Story**
As a user I'd like to get alerted when my pods (and especially the critical components of Kubermatic) are getting OOMKilled. 

A pod metric for that has been recently introduced in `kube-state-metrics` and we can set up an alert on it as soon as it makes it into a release. https://github.com/kubernetes/kube-state-metrics/commit/5119063031ef8fbefeedcef4fbba2f8578cce719

**Acceptance criteria**
 - [ ] an Alert is triggered whenever a pod is OOMKilled

**Comment by xrstf** [comment]
We are currently on 1.3.1 and could at the very least upgrade to 1.4.0. The new metric is only available in 1.5-beta0 so far, which is a month old at this point. There aren't any significant bugreports for it so I suggest we try the beta and see what breaks?

cc @kron4eg @thetechnick @xmudrii

**Comment by xrstf** [comment]
1.5.0 has been released a few days ago. Going to update and then submit my PR.
