### ISSUE TITLE
Remove apiv1.LegacyUser type

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#2260]
**Description**
After removing legacy endpoints (`v3`) `LegacyUser` type is redundant and can be replaced with `apiv1.User` type. 

There is only one endpoint `api/v1/dc` that make use of it though. There is a special case in the handler that checks if the authenticated user is an admin (https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/datacenter.go#L29) not sure if this is something that still applies, @mrIncompetent ?

**Acceptance criteria**
 - `LegacyUser` is removed and replaced with `apiv1.User`

**Comment by kgroschoff** [comment]
@mrIncompetent can you give an answer here, please?

**Comment by mrIncompetent** [comment]
It seems we can remove it. We only used this actually for internal purpose, but this was a long time ago.
