### ISSUE TITLE
Machine deletion broken after cluster-api migration

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2279]
**User Story**
After migrating a cluster from the kubermatic machine types to the upstream types, 
deleting machines did not cleaned up the cloud provider instance.
Affected cloud providers:
- AWS
- Azure
- Hetzner
- OpenStack
- DO

It seems the reason is that we store the machine UID on the cloud provider instance via Tag/Metadata.
The machine UID changes after migrating to the cluster api types

**Acceptance criteria**
- [x] Cloud provider instances can successfully be deleted after they have been migrated on AWS
- [x] Cloud provider instances can successfully be deleted after they have been migrated on Azure
- [x] Cloud provider instances can successfully be deleted after they have been migrated on Hetzner
- [x] Cloud provider instances can successfully be deleted after they have been migrated on Openstack
- [x] Cloud provider instances can successfully be deleted after they have been migrated on DO

**Comment by mrIncompetent** [comment]
@alvaroaleman this can be considered done?

**Comment by alvaroaleman** [comment]
Yes
