### ISSUE TITLE
[Investigation] Make Terms of Service - text configurable 

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#2282]
**User Story**
As a company I possibly want to show my Terms of Service in the UI. It is already possible to configure via values.yaml, if the Terms of Service link should be displayed. Atm this will display the Terms of Service from Loodse.
Investigate how a company could set they're own Terms of Service text via config file without touching the UI.

**Comment by floreks** [comment]
@scheeles is it important? Should we work on that?

**Comment by xrstf** [comment]
@shaase-ctrl I think showing the Kubermatic ToS is pretty much pointless for every possible KKP installation except for our own. At the very least we should IMHO just remove the option entirely until we have a better solution.

**Comment by shaase-ctrl** [comment]
I cannot see an immediate value and afaik our users can achieve this goal in various different ways (e.g. ToS Link on sign-up page etc.).
