### ISSUE TITLE
Export Changelog

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2319]
**User Story**
Most customers do not have access to the kubermatic/kubermatic repository.
The changelog must be exported therefore to some public accessable location (Or semi public -> kubermatic-installer repo)

Additionally:
The fact that kubermatic v2.8 uses & requires Ubuntu bionic is not mentioned in the changelog <- this must be fixt 

**Acceptance criteria**
- [ ] Changelog can be accessed without kubermatic/kubermatic access
- [ ] Changelog mentions xenial->bionic update

**Comment by alvaroaleman** [comment]
@mrIncompetent Should we fix this for the 2.10 release?

**Comment by mrIncompetent** [comment]
We should probably, i'll pull it into the backlog

**Comment by alvaroaleman** [comment]
This is done, the Changelog is available here: https://docs.kubermatic.io/changelog/2.10/
