### ISSUE TITLE
Manual E2E test

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#2328]
**Description** Conduct a manual test to verify if the feature was implemented. Please read the description and the acceptance criteria defined in the epic:  https://app.zenhub.com/workspaces/all-kubermatic--58863654794153994b62af76/issues/kubermatic/kubermatic/2242

**Comment by p0lyn0mial** [comment]
blocked because this feature hasn't been fully implemented yet.

**Comment by p0lyn0mial** [comment]
would be nice if we could implement automatic e2e test though :)

**Comment by zreigz** [comment]
Works fine on dev environment

**Comment by toschneck** [comment]
@p0lyn0mial my feedback ;-)

I think from the pure technical perspective the feature works. But as person who didn't read https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/user-cluster-authentication-via-dex.md is not really clear what the aim of the feature is. For this I gathered some possible Improvements of my point of view:

## 1. Share Kubeconfig dialog
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/f9fe009e-ef91-42f0-a38e-680126a247fd)
* I think aim of the feature is to enable admin to manage the user cluster permission. Maybe something like "User Access Management" would fit better.
* As far as I understand, the current workflow would look like. First apply RBAC rules to an user  e.g. `tobi2` in the cluster as admin (with the admin `kubeconfig` ). Then share the link to a specific user e.g. `tobi2`. Now he can generate his `kubeconfig` if he use the right authentication method and finally connect to the cluster. For me this workflow is not explained in the Dialog and should pointed out more clearly.
* A link to the documentation of this Feature would be helpful.
* In later versions, it would be great if we can apply some (default) RBAC rules directly at this dialog. In Example, give user `tobi2` only view rights on namespace `default`.

## 2. Documentation
The feature is not self explaining, so we need a detailed explanation what the purpose of it at docs.kubermatic.io. A direct link in the dialog to the documentation will also help.
I really like the proposal from @mrIncompetent https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/user-cluster-authentication-via-dex.md. The chapter `Motivation` and `User flow` would be a good start there. Also a linkt to RBAC page in Kubernetes would be nice: [Using RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/)

## 3. Error handling and transparency
* I would suggest to add `-admin` as name to the admin kubeconfig. So it would be clear that is dangerous to share. Also a hint would be good, something like "Do not share the admin `kubeconfig`. Use instead ..."
* Also hint about that I have to be in the correct organisation to use the shared link would be nice.
* The dialog where I as cluster user `tobi2` login should give some information for what I login. Something like "You need to authorize you, to get access as `tobi2` for the cluster xyz and download your kubeconfig. I later version we may can think about to give him a small dashboard where he can download all for him accessable kubeconfigs. A table with the information, about the cluster, the applied roles, the person who granted the access would be awesome.
* The dialog don't show an error message when I use the wrong credentials and stuck forever this state. This is not a nice behavior.  ![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/9677e31e-340f-4d4f-a662-bd3dc4bb378d)

**Comment by p0lyn0mial** [comment]
@toschneck We are working on creating a documentation for that feature. Once we have it we will include the link. In general this feature is experimental and temporary it will be replaced by more automated functionality. Thanks for your feedback we will address your comments :)

https://app.zenhub.com/workspaces/all-kubermatic--58863654794153994b62af76/issues/kubermatic/kubermatic/2443

**Comment by toschneck** [comment]
@p0lyn0nimal sounds like a great plan! Looking forward to version 2 😃

**Comment by p0lyn0mial** [comment]
@toschneck We added the documentation, changed and updated the title and the content of the "Share cluster" modal window and we added `-admin` prefix to the admin `kubeconfig`. 

@toschneck I wanted to make sure that the errors are propagated from the provider to the browser but I think I cannot reproduce "The dialog don't show an error message when I use the wrong credentials and stuck forever this state. This is not a nice behavior." point. Whenever I type incorrect password my provider (google) presents a nice error message to me.

**Comment by toschneck** [comment]
@p0lyn0mial thx for the feedback. LGTM, so from my point of view we can close this issue :wink:

**Comment by toschneck** [comment]
@p0lyn0mial small thing what I found. The `Connect Dialog` needs also an adjustment for the `-admin` change:
![image](https://user-images.githubusercontent.com/4659261/51090261-959bad00-1779-11e9-9e43-ef94ddd97242.png)

**Comment by p0lyn0mial** [comment]
@toschneck fixed, thx!

![screenshot 2019-01-17 at 08 49 25](https://user-images.githubusercontent.com/21304151/51303193-e3900980-1a34-11e9-8812-65a6b8324f7a.png)
