### ISSUE TITLE
[Proposal] Dynamic resizing of control plane components

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2329]
**User Story**
As the resource usage of control plane components depend on the cluster size, it might be necessary to adjust them during lifetime of a cluster.
Right now the only way to do this is the [components-override](https://docs.kubermatic.io/operation/control-plane/scaling/) feature on the cluster object. This though is a manual effort and requires constant monitoring of the resource usage.

To avoid the manual effort, the cluster-controller should take care of adjusting the resource usage of components.

The idea is to define certain Classes/Levels for a cluster. Each class/level has fixed resource limits/requests assigned for each components.
The cluster controller will take certain cluster metrics as input and then decides for a class/level.

Possible cluster metrics:
- Number of nodes
  - As each node creates a request to the API server every 5 seconds, it is a significant scaling factor
- Number of pods
  - Each pod needs to be scheduled, thus is heavily affects the scheduler, controller-manager & API server
- Number of Namespaces
  - With an increasing number of namespaces, the load on the controller-manager increases

**Acceptance criteria**
- [ ] A proposal has been written and merged

**Comment by alvaroaleman** [comment]
SGTM. I was also wondering if we could just use the raw pod metrics (CPU/memory) as an alternative input?

**Comment by mrIncompetent** [comment]
I'm not very sure if using the CPU & Memory usage is a good input.
It would be very similar to using no limit at all.

We might risk, increasing the request+limit for a component that has a memory leak or similar

**Comment by mrIncompetent** [comment]
A probably more desirable approach would be to utilize the VerticalPodAutoscaler for all non-horizontal scalable components.
For the components which can be scaled horizontally, the HorizontalPodAutoscaler should be used

**Comment by mrIncompetent** [comment]
Closed in favor of https://github.com/kubermatic/kubermatic/issues/2424
