### ISSUE TITLE
use secretKeyRef in user cluster k8s object

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#2336]
**User Story**
The current cluster object contains the provider secrets as plain values. For doing demo use cases (e.g. screen sharing) it's not great when we show the secrets as plain text, e.g:
```
kubectl get cluster dmmsjw8nnz -o yaml
address:
  adminToken: sg6nzz.q74dq2dr7vtnrkx2
  externalName: dmmsjw8nnz.europe-west3-c-1.cloud.kubermatic.io
  ip: 35.234.122.0
  url: https://dmmsjw8nnz.europe-west3-c-1.cloud.kubermatic.io:30952
apiVersion: kubermatic.k8s.io/v1
kind: Cluster
metadata:
  creationTimestamp: 2018-11-05T16:22:23Z
  finalizers:
  - kubermatic.io/cleanup-backups
  - kubermatic.io/delete-nodes
  generation: 1
  labels:
    project-id: p7fmvrx899
  name: dmmsjw8nnz
  resourceVersion: "213454149"
  selfLink: /apis/kubermatic.k8s.io/v1/clusters/dmmsjw8nnz
  uid: f9eacd97-e116-11e8-9fac-42010a9c00f1
spec:
  cloud:
    dc: do-fra1
    digitalocean:
      token: XXXXXXXXXXXXXXXXXXXXXXX
  clusterNetwork:
    dnsDomain: cluster.local
    pods:
      cidrBlocks:
      - 172.25.0.0/16
    services:
      cidrBlocks:
      - 10.10.10.0/24
  componentsOverride:
    apiserver: {}
    controllerManager: {}
    etcd: {}
    scheduler: {}
  humanReadableName: do-testa
  masterVersion: ""
  pause: falseUI 
  version: 1.12.1
```
**Solution:** use for all cloud provider `secretKeyRef` like here: https://github.com/kubermatic/machine-controller/blob/dbbc29796d291d9329780efeccea6659f11227d3/pkg/apis/cluster/v1alpha1/conversions/testdata/machinesv1alpha1machine/hetzner.yaml

**Acceptance criteria**
- [ ] if a new cluster get created through the UI the command `kubectl get cluster <cluster-id> -o yaml` doesn't contain any secret.
- [ ] it is implemented at all cloud providers

**Comment by mrIncompetent** [comment]
@toschneck has this been discussed with anyone from the development so far?

**Comment by toschneck** [comment]
@mrIncompetent no not so far, just trap into this at every demo and it opens up some questions on the audience. Also if someone takes a picture or video it's not perfect.
The cluster itself is created trough the UI.

**Comment by mrIncompetent** [comment]
@toschneck Please do not set a priority if things have not been discussed yet.

**Comment by toschneck** [comment]
@mrIncompetent sorry didn't know the workflow.

**Comment by alvaroaleman** [comment]
CC @p0lyn0mial As you mentioned that you want this to be changed

**Comment by maciaszczykm** [comment]
It is connected to https://github.com/kubermatic/dashboard-v2/issues/860.

**Comment by p0lyn0mial** [comment]
Secrets are secrets and should be kept in secret :) I'd like also to keep them apart. It's very common to copy/paste a cluster definition for troubleshooting purposes

**Comment by p0lyn0mial** [comment]
assigning to `lifecycle` team because `cluster` resources are owned by that team.

**Comment by toschneck** [comment]
In further projects we need the possibility to have different Kubermatic Ops RBAC settings:
- One group is "superadmin" and see the cloud provider credentials and the user cluster `kubeconfig`s
- Second group is "admin", can manage the cluster resources but not the secrets.

In an context of regulation (atech), the "superadmin" rights will only get given on purpose e.g. when a production incident happens.

Another thing is, that this will gave us the possibility to manage the secrets in a more secured way by a [KMS Provider plugin](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/). So enterprises can store there secrets in an independent  (hopefully secured) store. To use Vault as secret provider see: https://github.com/oracle/kubernetes-vault-kms-plugin or https://github.com/Boostport/kubernetes-vault

So extract the cloud provider credentials, would be the first needed step to be able to build around it.

**Comment by alvaroaleman** [comment]
Sidecomment: Since secrets are namespaced and we need to store the cloud provider credentials before we have a cluster namespace, we must have one dedicated namespace for all cloud provider secrets of all clusters. Maybe just `kubermatic-secrets`?

**Comment by toschneck** [comment]
We got this requirement now also from a customer see: https://github.com/kubermatic/customer-projects/issues/47

**Comment by alvaroaleman** [comment]
This can not possibly be a customer requirement as the Cluster CRD is an internal API that is explicitly not documented and not intended to be used by anyone directly.

The ticket you referenced is about using an external data source, which is a different topic

**Comment by toschneck** [comment]
@alvaroaleman our customers are not only users who create clusters. They also operate the Kubermatic stack. I don't think it's currently possible to operate the stack without touching the CRDs at all. So as we don't offer a managed service, it is indeed part of the interfaces a customer will touch. If we want to discuss this, we shouldn't do this in this issue.

Why a customer really care about this?
a) like mentioned they want to use an external data source
b) the want to have different RBAC rules on e.g. cluster object and the referenced secret object to manage the access policies in a proper way

**Comment by alvaroaleman** [comment]
> @alvaroaleman our customers are not only users who create clusters. They also operate the Kubermatic stack. 

Yes. That implies that they can and potentially should _look_ at the CR but not change them. There are currently two exceptions to that, which are the `spec.pause` and the `spec.componentOverride` fields. 
But generally we do change the cluster CRD without notifying customers and we will continue to do so, it is _not_ an extenal api and apart from the two fields mentioned before we do not provide any kind of stability guarantee for them.

> the want to have different RBAC rules on e.g. cluster object and the referenced secret object to manage the access policies in a proper way

Can you please create an epic for that? Instead of doing this piece by piece after someone notices something, we should write down the use case and think about how to achieve this. Also there should be docs that document the corresponding rbac policies. Lastly, this will need priorization by @kdomanski

**Comment by toschneck** [comment]
> But generally we do change the cluster CRD without notifying customers and we will continue to do so, it is not an extenal api and apart from the two fields mentioned before we do not provide any kind of stability guarantee for them.

That's ok that this is not stable. But the operators will still look at the CRDs. So it's better to have the secrets not in the spec. 

> Can you please create an epic for that? Instead of doing this piece by piece after someone notices something, we should write down the use case and think about how to achieve this. Also there should be docs that document the corresponding rbac policies.

Currently the requirements are not clear enough for a general approach. First we will analyze it and gather all requirements in detail. Afterwards I can create a dedicated epic for this.  The only thing we get so far from multiple discussions, is that they all don't want to have the secrets in the cluster spec.

**Comment by alvaroaleman** [comment]
> That's ok that this is not stable. But the operators will still look at the CRDs. So it's better to have the secrets not in the spec.

Then there is no user story behind any of this. So far Kubermatic operators have been able to view the credentials of the user clusters. This wont change when we store them in a secret.

**Comment by moadqassem** [comment]
Duplicate for the other ticket which found here:
https://app.zenhub.com/workspaces/all-kubermatic-58863654794153994b62af76/issues/kubermatic/kubermatic/3792
