### ISSUE TITLE
Test idempotency of controllers that create kubernetes objects

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2342]
**User Story**

As a developer I want my CI system to automatically test as much as possible and give me meaningful feedback. 

**Acceptance criteria**

* There is a test that verifies that the controllers won't update any resources after they got created

**Notes**

May be a good usecase for kind: https://github.com/kubernetes-sigs/kind

**Comment by mrIncompetent** [comment]
Needs more details on the actual impact when things go wrong here

**Comment by alvaroaleman** [comment]
Proposed approach: Add an additional alert just on dev.kubermatic.io on a high PUT request rate of the kubermatic controller manager
