### ISSUE TITLE
Build CI step for executing conformance tests on one cloud provider

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2346]
**User Story**

 As a developer of Kubermatic I want as much assurance that a given change doesn't break as possible without having to remember to manually execute those tests

**Acceptance criteria**

* There is a CI step that gets executed on PRs
* It deploys the kubermatic version of that PR into a dedicated namespace
* It leverages the conformance-test tool to create and test a cluster on one cloud provider without testing cloud provider functionality like LBs or PVs and labels it appropriately so it will get worked on by the previusly installed kubermatic
* Regardless of the test result, the created cluster gets deleted
* Regardless of the test result, the dedicated namespace with its kubermatic installation gets deleted

**Comment by mrIncompetent** [comment]
Use AWS to avoid quota issues

**Comment by p0lyn0mial** [comment]
How does it differ from the tests that will be run as part of `kubeone` project ?
Will that tool install `kubermatic` differently than the new installer ?

**Comment by alvaroaleman** [comment]
> How does it differ from the tests that will be run as part of kubeone project ?

To my knowledge in  `kubeone` you create a cluster via `kubeone` and then run conformance tests against that cluster.

Here, we create a cluster via `Kubermatic` and then run conformance tests against that cluster

**Comment by p0lyn0mial** [comment]
> Here, we create a cluster via Kubermatic and then run conformance tests against that cluster

oh, it will tests the "user's cluster", thanks.

**Comment by alvaroaleman** [comment]
Resolved via #2491
