### ISSUE TITLE
Calico CNI Logging can expose Kubernetes service account tokens

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#2353]
Check if you effected by: In certain scenarios, Calico will write configuration data in log files including service account tokens included in the configuration. This will expose client service account tokens in the log files which could lead to unauthorized cluster access or privilege escalation if users are able to access these log files.

https://www.projectcalico.org/security-bulletins/

**Comment by alvaroaleman** [comment]
@mrIncompetent Check if this applies

**Comment by mrIncompetent** [comment]
We are actually not affected. It only applies to configurations where the serviceaccount token gets set explicitly via config (We don't do that).
