### ISSUE TITLE
 Use the “underscore test” for the handler package

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#2359]
**Description**
Go doesn’t let you include multiple packages in one folder except for when you use a separate test package.

Using a separate `_test` package means that user can’t access the unexported fields and functions in the package. The test can see only exported API, so it makes the code more usable, safe and complete.

**Comment by maciaszczykm** [comment]
+1 from me. Like I said in https://github.com/kubermatic/kubermatic/pull/2348#discussion_r233378650 it would be good to use it in all packages in my opinion.

**Comment by p0lyn0mial** [comment]
+1
