### ISSUE TITLE
Error is displayed when creating a project with a dash

### ISSUE THREAD

**Issue by bashofmann** [kubermatic/kubermatic#2376]
If you create a project that contains a dash in the name (e.g. "foo-bar") a 403 error is displayed, the project seems to be correctly created though:

```
Error 403
projects.kubermatic.k8s.io "grcmt8lhtp" is forbidden: User "b.hofmann@xxx.yyy" cannot get resource "projects" in API group "kubermatic.k8s.io" at the cluster scope
```

**Comment by bashofmann** [comment]
@mrIncompetent This is still happening, any news on this? /cc @shahbazn

**Comment by p0lyn0mial** [comment]
![screenshot 2019-01-09 at 11 51 10](https://user-images.githubusercontent.com/21304151/50894973-0010be00-1405-11e9-8f32-446eae851e3a.png)

**Comment by p0lyn0mial** [comment]
![screenshot 2019-01-09 at 11 53 16](https://user-images.githubusercontent.com/21304151/50895044-364e3d80-1405-11e9-8ae0-aee7820cc555.png)


request

**Comment by p0lyn0mial** [comment]
![screenshot 2019-01-09 at 11 53 21](https://user-images.githubusercontent.com/21304151/50895057-40703c00-1405-11e9-9697-37f2bd0d923e.png)

response

**Comment by p0lyn0mial** [comment]
@bashofmann works for me, unable to reproduce on `dev.kubermatic.io`

**Comment by bashofmann** [comment]
Maybe something that is fixed in master but not in 2.8. It's not so critical. I'll keep an eye on it and see if it still is happening in 2.9 I'll try to get more details then.

**Comment by p0lyn0mial** [comment]
@bashofmann can you try to reproduce the error on 2.9 ?

**Comment by bashofmann** [comment]
We haven't updated to 2.9 yet, though we plan on doing it this week. I'll be back with more information then.

**Comment by bashofmann** [comment]
We can't reproduce this anymore with 2.9. Closing it then.
