### ISSUE TITLE
Migrate from docker hub to quay

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#2398]
**User Story**
Currently some party of our images are on docker hub and some are one quay. 

In a first step deploy all image additional to docker hub to quay and change all helm charts.

- [ ] Kubermatic api/controller
- [ ] Kubermatic dashboard

**Acceptance criteria**
With kubermatic 2.9 only quay is required and we can mask docker hub as deprecated.

**Comment by scheeles** [comment]
@mrIncompetent: you add the images which are missing

**Comment by kdomanski** [comment]
All images have been going to Quay and getting pulled only from there as well. We can start tearing down the parts of CI that push to Docker Hub.

**Comment by mrIncompetent** [comment]
Kubermatic api/controller
 Kubermatic dashboard

Both are being deployed to quay only.
