### ISSUE TITLE
Manually spin up a OpenShift control plane on Kubernetes

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2404]
To be able to automate the creation of a OpenShift cluster on kubernetes we first need to figure out how to properly configure OpenShift so it runs successfully on Kubernetes.

Acceptance criteria
- [ ] A namespace on dev.kubermatic.io exists which a running control plane of OpenShift
- [ ] The OpenShift control plane is accessable from the outside
- [ ] The OpenShift CLI works properly with the remote control plane
- [ ] The deployed manifests have been saved so they can be used later for other issues in this epic

**Comment by kdomanski** [comment]
Estimated as 3
