### ISSUE TITLE
Manually sping up TWO OpenShift nodes

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2405]
To be able to automate the creation of OpenShift worker nodes, we first need to figure out how to properly provision a node so it successfully works in a OpenShift cluster.

Acceptance criteria
- [ ] Not one but TWO CentOS nodes successfully join a OpenShift control plane
- [ ] Pods can be scheduled onto the new nodes
- [ ] pods can communicate between each other
- [ ] Cluster DNS works
- [ ] All provisioning steps have been documented so they can be used later for other issues in this epic

**Comment by kdomanski** [comment]
Estimated as 5
