### ISSUE TITLE
Define needed resources for a OpenShift control plane

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2407]
To be able to deploy OpenShift on Kubernetes, we need to figure out what resources we need to deploy into a namespace so OpenShift is correctly working.
Those resources are:
- Secrets (What certificates)
- ConfigMaps (What config?)
- Deployments (What pods do we need?)
- StatefulSets (etcd?)
- Services (Do we need some services?)

**Comment by alvaroaleman** [comment]
This is already done
