### ISSUE TITLE
Investigate difference betweek our go-kit wrapper and klog

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2422]
Check the differences between both packages and define which should be used for the future in our projects.

Requirements:
- We want structured logging
- We want to have the log emitting code line in the logs
- Less maintenance for us is good!

**Comment by nikhita** [comment]
I was looking a bit into klog over this weekend...can I take this up? :slightly_smiling_face:

**Comment by mrIncompetent** [comment]
The controller-runtime ships by default with `zap` - Since its so tightly integrated with the controller-runtime, should we try to utilize that?

It supports structured logging out of the box :)

**Comment by mrIncompetent** [comment]
cc @alvaroaleman

**Comment by alvaroaleman** [comment]
I'd be in favor of trying to utilize events more and not spending much time on logging. I am not really sure if replacing glog is worth the time.

**Comment by mrIncompetent** [comment]
@alvaroaleman @nikhita Please check whats needed here :)

**Comment by alvaroaleman** [comment]
The main difference seems to be that glog-gokit is a replacement for glog, wheres klog can coexist with glog.

The main thing klog does compared to glog is to solve some compatibility isues, by e.G. stopping to register flags via an `init`. Other than that, its doing mostly the same.

**Comment by alvaroaleman** [comment]
But it doesn't seem like klog does structured logging. It could probably hacked by calling `func SetOutput(w io.Writer)` with an `io.Writer` that parses the log lines, structures them and then writes them to `/dev/stdout`, but that doesn't sound like a great option

**Comment by alvaroaleman** [comment]
@mrIncompetent How to proceed with this issue?

**Comment by mrIncompetent** [comment]
A cleaner solution would be to implement a replacement package like https://github.com/kubermatic/glog-gokit but for zap.

Based on the loc of glog-gokit it should be fairly quick to do.

WDYT?

**Comment by alvaroaleman** [comment]
Sure

**Comment by mrIncompetent** [comment]
I created https://github.com/kubermatic/kubermatic/issues/3489 as follow up to implement the zap specific package
