### ISSUE TITLE
Ban possibility to add SSH keys with already existing name

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#2426]
**User Story**
Atm it is possible to add a SSH key that has the same name as an already existing one (within the same project). This should not be possible, as it confuses users, because "the same" SSH key is shown twice (or even more often).

**Acceptance criteria**
It should only be possible to successfully add a new SSH key to a project, if its name isn't used within the project yet. Trying to add a SSH key with an already existing name should cause an error.

**Comment by p0lyn0mial** [comment]
please make sure that it is not possible to create duplicates for `projects` and `clusters`

**Comment by p0lyn0mial** [comment]
for `projects` you cannot own more than one project with the given name.
