### ISSUE TITLE
Controller-Manager crashloops when using vsphere and a user with `ADDOMAIN\USERNAME` notation

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2434]
**User Story**

Shaw reported issues of the controller-manager crashlooping when using the active directory notation of `ADDOMAIN\USERNAME`, most likely due to incorrect/no escaping in the cloud provider config

**Acceptance criteria**

* The `ADDOMAIN\USERNAME` can be used for creating a new cluster without any component crashlooping or having authentication issues

**Comment by mrIncompetent** [comment]
Use the struct & function from the machine-controller, as there we have the relevant escaping logic
