### ISSUE TITLE
Investigate/Test potential OpenShift deployment options

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2438]
OpenShift is currently migrating towards a full Extension API server, which will just extent Kubender.
Instead of the current fork of Kubernetes.

Using the Extension API server approach would ease our development & lead to less duplicated code.

**Acceptance criteria**
- [ ] The potential installation using the extension API server approach has been documented & discussed with upstream folks.
- [ ] A decision has been made if we either go for the experimental extension API server approach or the current "fork" one.

**Comment by alvaroaleman** [comment]
@mrIncompetent Do you think there is a point in keeping this ticket?

**Comment by mrIncompetent** [comment]
Nope
