### ISSUE TITLE
[OpenStack] Make allocation of FloatingIP's optional

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2439]
**User Story**
As a user of OpenStack, i might not wan't a Floating IP for all my nodes.
Currently all Kubermatic nodes though get one - as the relevant flag in the Machine, which kubermatic creates, is hardcoded.

As a FloatingIP though is mandatory for some OpenStack environments, it must be possible to enforce the allocation of FloatingIP's on a datacenter level.

**Acceptance criteria**
- [x] A user can decide via a CheckBox in the Dashboard to allocate FloatingIP's for the nodes
- [x] A setting in the datacenters.yaml can enforce the allocation of FloatingIP's
- [ ] If the datacenter is configured to always allocate FloatingIP's, the Dashboard won't show the option

**Comment by p0lyn0mial** [comment]
@mrIncompetent  Do we want to store a list of `FloatingIP` in the `datacenters.yaml` file ? If yes would it be okay to sort the list and assign the first one from the list to all nodes ?

**Comment by mrIncompetent** [comment]
@p0lyn0mial 

> Do we want to store a list of FloatingIP in the datacenters.yaml file ?

No. How did you came up with this idea?

**Comment by p0lyn0mial** [comment]
> No. How did you came up with this idea?

@mrIncompetent Because during a cluster creation a user can choose a `FloatingIP` from the list (a dropdown menu). Should we hide/disable the dropdown when there is a value in the datacenters.yaml file ?

**Comment by mrIncompetent** [comment]
@p0lyn0mial Do you mean the `Floating IP pool` which can be selected in the extended view when creating a OpenStack cluster?

**Comment by p0lyn0mial** [comment]
> @p0lyn0mial Do you mean the Floating IP pool which can be selected in the extended view when creating a OpenStack cluster?

@mrIncompetent yes, this issue is about something else :) ?

**Comment by floreks** [comment]
@mrIncompetent should `datacenters.yaml` be updated to enforce floating IP usage for any of our providers or just leave it as is for now?
