### ISSUE TITLE
Investigate potential CSS override possibilities

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2447]
**User Story**
Some customers would like to whitelabel the Dashboard. 

Here we should differentiate between 3 kind of whitelabelings:
- Just colors & logo
- Colors, Logo, custom menu options - potential smaller modifications to our Logic
- Complete custom - self written - Dashboard

The second option is the way we proceeded now for most of the time. It involves forking of the dashboard & requires the customer to build custom images.

The first option is something we need to find a simple way for - which should not require a fork of the dashboard.

Possibilities:
- We can mount custom CSS into the dashboard container & load it via HTML ?
  - How can we do priorities?
  - We need to document what can be overwritten & how to do so
- NPM build during container start & mount potential overwrites ?

What other ways do exist? What would be the simples way to specify custom colors & logo - without forking the dashboard ?

**Comment by maciaszczykm** [comment]
I will add some thoughts from my side:

One of the options to change colors, even dynamically, is to use Angular Material theming functionality. Its demo can be found in the top right corner of https://material.angular.io. We have added similar functionality to Kubernetes Dashboard. Most important thing was keeping all color related stuff in one place. See:

- https://github.com/kubernetes/dashboard/blob/ng-migration/src/app/frontend/_theming.scss
- https://github.com/kubernetes/dashboard/blob/ng-migration/src/app/frontend/_dark.scss
- https://github.com/kubernetes/dashboard/blob/ng-migration/src/app/frontend/_light.scss

Things to consider:

- It seems like logo location can be customized from CSS files: `src/app/core/components/navigation/navigation.component.scss:27` and `src/app/overlays/mobile-navigation/mobile-navigation.component.scss:4`.
- Most likely some effort to migrate all color-and-logo-related CSS rules into this one file is required.
- Finding a good way to load stylesheets and configure their location during app startup would allow to use mount. 
- What to use to configure stylesheet location? Some sort of flag/config? I.e. `--custom-theme` that would make Dashboard use different CSS file? If it would be undefined then Dashboard would load default theme.
- In the end only 1 CSS file with colors and logo location needs to be customized to provide custom theme? 2 files to be mounted?
- We should also ensure that `dist` directory will have some specific structure where we will be able to mount CSS and logo files.

**Comment by maciaszczykm** [comment]
Moved to https://github.com/kubermatic/dashboard-v2/issues/920.
