### ISSUE TITLE
Openstack: ugly errors in the UI when account cannot list tenants

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#2458]
**User Story**
When creating an Openstack cluster, Kubermatic attempts to pull the list of tenants/projects from Openstack API in order to add them to the dropdown. It's not unusual however, for the used account not to have the permissions necessary to list tenants. In this case the name of the tenant can still be provided manually, however an ugly error message appears in the UI and it can be quite confusing for the user.

![image](https://user-images.githubusercontent.com/993296/49217599-43bbe500-f3ce-11e8-85cb-42aa9c66ff96.png)

Instead, the UI should just do nothing if fetching the list of tenants fails due to access being denied.

**Acceptance criteria**
 - [ ] The `providers/openstack/tenants` endpoint returns 403 Forbidden instead of 500 Internal Server Error when it fails to fetch the list of tenants due to lack of permissions
 - [ ] The UI doesn't do anything if `providers/openstack/tenants` endpoint returns 403 Forbidden

**Comment by p0lyn0mial** [comment]
@kdomanski  are you sure about it ? A tenant seems to me like a project. Providing credentials allows for getting a list of projects/tenants the user belongs to. Since the user cannot get the list might indicate he does't have read access to a tenant/project which may cause a ripple effect - the request eventually fails at a later stage.

/cc @alvaroaleman

**Comment by kdomanski** [comment]
I encountered this on Telekom Cloud. I couldn't get he list of tenants, but if I provided the tenant name manually, then everything worked fine on later stages.

**Comment by maciaszczykm** [comment]
Issue moved to [kubermatic/dashboard-v2 #1135](https://github.com/kubermatic/dashboard-v2/issues/1135) via [**ZenHub**](https://www.zenhub.com/)
