### ISSUE TITLE
Replace alert EtcdHighNumberOfFailedGRPCRequests

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2462]
**User Story**
The `EtcdHighNumberOfFailedGRPCRequests` alert gets triggert for every restart of the Kubernetes API server as it seems to not gracefully shutdown etcd-watch connections.

The alert gets triggert because the API server might connect to a different etcd member, which will result in a 100% error rate on the old etcd member.

For a default etcd cluster this alert is fairly reasonable, but not in a scenario where only only member at a time is being used.

The alert should be replaced with an alert which expresses etcd connection errors from the API server side.

**Acceptance criteria**
- [ ] The `EtcdHighNumberOfFailedGRPCRequests` alert has been disabled
- [ ] A new alert got introduced which fires as soon as the API server has connection issues with the etcd
- [ ] The new alert does not get fired when the apiserver restarts
- [ ] The new alert does not get fired when any etcd member goes offline (Reconnects from the AP server are a common scenario)

**Comment by xrstf** [comment]
There are apparently no metrics for failed etcd connections, so I'm trying to see if we can deduce "etcd has gone whoopsie" by checking the apiserver's `up` status.

**Comment by xrstf** [comment]
Can confirm. After scaling down the etcd StatefulSet, I get these metrics:

```
up{job="kubernetes-nodes"}	0
up{job="controller-manager"}	1
up{job="machine-controller"}	0
up{job="apiserver"}	0
up{job="scheduler"}	1
up{instance="etcd-0",job="etcd"}	0
up{instance="etcd-1",job="etcd"}	0
up{instance="etcd-2",job="etcd"}	0
```
