### ISSUE TITLE
IP Management: Enable Machine Networks only for VSphere

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#2485]
**User Story**
Via UI you will not have the possibility to set Machine Networks if provider != VSphere, but theoretically it's possible to add Machine Networks to every provider atm. Please make sure that it is only possible to set this feature for VSphere as it could cause problems with other providers or "in best case" the settings will not have any effect.
Additionally atm it's only possible to set them on VSphere, if the Operating System is CoreOS (Container Linux), as CentOS and Ubuntu are not implemented yet (and it's not sure if it will be implemented anyway).

**Acceptance criteria**
Machine Networks will only be added to Cluster Spec if VSphere is selected. Please make also sure, that CoreOS is selected.

**Comment by p0lyn0mial** [comment]
I think we can close this issue.

A cluster will not be created if a wrong provider is requested and there are machine networks
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/validation/cluster.go#L76

Machine controller will reject any nodes that have incorrect operating system defined
https://github.com/kubermatic/dashboard-v2/pull/829#issuecomment-444866413
