### ISSUE TITLE
Move dex.caBundle into kubermatic chart

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2488]
The ca bundle is only required by Kubermatic - thus it does not make sense to have it specified inside the `dex` values block.

Instead it creates now a dependency on the `dex` block to exist for the kubermatic chart.

Rule: A chart should only use values from its own values block.

**Comment by p0lyn0mial** [comment]
I agree we could move it to `kubermatic.auth`.
