### ISSUE TITLE
Create test package to execute e2e tests to check: infrastructure provisioning, cluster deployment, conformance tests

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#2496]
**User Story**
Implement a test suite with a common interface to be able to test various provider.
**Acceptance criteria**
Test suite validate: infrastructure provisioning, cluster deployment, conformance tests
The user can easily add other providers to check cluster created by kubeone

**Comment by p0lyn0mial** [comment]
moving to GH, https://github.com/kubermatic/kubeone/issues/96
