### ISSUE TITLE
Loodse Prometheus is logging errors

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2512]
The Loodse Prometheus is logging errors:
```
level=error ts=2018-12-12T14:31:35.903108081Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:monitoring:default" cannot list pods in the namespace "monitoring""
```
https://kibana.cloud.kubermatic.io/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(),index:f3b70890-f5b3-11e8-a107-a1aab5834863,interval:auto,query:(language:lucene,query:'log:%20*error*%20AND%20kubernetes.pod_name:%20prometheus-loodse-*%20AND%20kubernetes.namespace_name:%20monitoring'),sort:!('@timestamp',desc))

**Acceptance criteria**
- [ ] Prometheus has all required permission to do the Kubernetes service discovery

**Comment by mrIncompetent** [comment]
The instance is running on cloud-eu

**Comment by kron4eg** [comment]
So it was some relics from old times that was deployed manually and now all removed.
