### ISSUE TITLE
Migrate all tests to use Prow

### ISSUE THREAD

**Issue by nikhita** [kubermatic/kubermatic#2520]
**User Story**

As a developer of Kubermatic, I want to have all my tests run on Prow.

**Acceptance criteria**

- [x] All presubmit jobs have been migrated to Prow.
- [x] All postsubmit jobs have been migrated to Prow.
- [x] All the changes to the scripts and Makefile have been backported to 2.8 (https://github.com/kubermatic/kubermatic/issues/2577)

**Comment by nikhita** [comment]
Update: I had started working on the post submits, the remaining thing here is to add post submits for the `deploy-*` ones. I'll work on that tomorrow morning.

**Comment by kdomanski** [comment]
Estimated as 3 story points.

**Comment by nikhita** [comment]
Done
