### ISSUE TITLE
Replace word `kubermatic` with `kubernetes` in all cloud provider resources

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2533]
**User Story**
If a customer want's to use Kubermatic & "whitelabel" it, still all cloud provider resources for user clusters have the prefix `kubermatic`.

This prefix must be replaced with the word `kubernetes`.

**Acceptance criteria**
- [ ] `kubermatic` does not get used for any cloud provider resource anymore
- [ ] This change is backwards compatible

**Comment by kdomanski** [comment]
@scheeles do you approve of this?

**Comment by scheeles** [comment]
Where do we have `kubermatic` in the cloud provider?

**Comment by alvaroaleman** [comment]
Just talked to @scheeles, he is fine with changing that

**Comment by scheeles** [comment]
Ok for me

**Comment by kdomanski** [comment]
As discussed with @alvaroaleman in the office, renaming it to `kubernetes` is too generic and will result in names like `kubernetes-kubernetes-43x7yt834`. Let's just make it configurable at first install.
