### ISSUE TITLE
Backport v1.13 to v2.8

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2565]
**User Story**
Support for Kubernetes v1.13 should land in kubermatic v2.8. 

The required PR's which should be cherry picked:
- https://github.com/kubermatic/kubermatic/pull/2515
- https://github.com/kubermatic/kubermatic/pull/2548 (To enable support for v1.13.0)

**Acceptance criteria**
- [ ] The changes have been backported
- [ ] the conformance tests succeeded

**Comment by kdomanski** [comment]
@alvaroaleman this is done, right?

**Comment by alvaroaleman** [comment]
yes

/close
