### ISSUE TITLE
Add more details to the user-cluster-controller proposal

### ISSUE THREAD

**Issue by nikhita** [kubermatic/kubermatic#2567]
The user cluster controller [proposal](https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/user-cluster-controller.md) already exists but it would be good to add more details in it, especially details on the implementation, so that the overall architecture is completely clear.

Epic issue: https://github.com/kubermatic/kubermatic/issues/1706

**Acceptance criteria**:

- [ ] The proposal accurately reflects all the tasks necessary for implementation of the user cluster controller.
- [ ] All the comments in https://github.com/kubermatic/kubermatic/pull/1938 are addressed and the proposal contains any further updates to the architecture.

**Comment by kdomanski** [comment]
Estimated as 2 points.

**Comment by nikhita** [comment]
Quick update here: Haven't forgotten this, I want to first figure out how to reconcile resources that need the Cluster CRD in their creator funcs and then update the docs as whole.

Ref:

- https://github.com/kubermatic/kubermatic/pull/2671 - Initial skeleton of user cluster controller (reconciles only those resources which don't need the Cluster CRD info)
- https://github.com/kubermatic/kubermatic/issues/2827 - follow up to migrate all user cluster resources to the user cluster controller

**Comment by nikhita** [comment]
Update: code exists, docs need update :see_no_evil: 

I closed https://github.com/kubermatic/kubermatic/pull/1938 and will create a new one.

**Comment by mrIncompetent** [comment]
@mrIncompetent write issue to document all controllers and their responsibilities
