### ISSUE TITLE
move deployment of dashboard to prow

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#2574]

**Comment by p0lyn0mial** [comment]
all steps have been moved except deployment.

**Comment by maciaszczykm** [comment]
With this update we should be able to remove Drone CI from our pipeline.

**Comment by maciaszczykm** [comment]
Issue moved to [kubermatic/dashboard-v2 #1271](https://github.com/kubermatic/dashboard-v2/issues/1271) via [**ZenHub**](https://www.zenhub.com/)
