### ISSUE TITLE
Ensure prow runs successfully for v2.8

### ISSUE THREAD

**Issue by nikhita** [kubermatic/kubermatic#2577]
Any changes made to scripts in `api/hack/*` and the `Makefile` to be able to run the prow postsubmits and presubmits in the `master` branch should be backported to the `release/v2.8` branch - so that prow can run on that branch successfully as well.

Related: https://github.com/kubermatic/kubermatic/issues/2520

**Acceptance criteria**

- [x] All prowjobs run successfully for the `release/v2.8` branch.

**Comment by nikhita** [comment]
@mrIncompetent This needs to be backported only to v2.8, right? Or is it v2.7 as well?

**Comment by mrIncompetent** [comment]
v2.8 should be fine

**Comment by nikhita** [comment]
Done
