### ISSUE TITLE
Master build is failing

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#2591]
See: https://github.com/kubermatic/kubermatic/pull/2582#issuecomment-452349393

```
Error: UPGRADE FAILED: render error in "iap/templates/deployments.yaml": template: iap/templates/deployments.yaml:22:28: executing "iap/templates/deployments.yaml" at <include (print $.Tem...>: error calling include: template: iap/templates/configmaps.yaml:1:17: executing "iap/templates/configmaps.yaml" at <.Values.iap.deployme...>: can't evaluate field iap in type interface {}
```

Last 3 build have failed.

**Comment by bashofmann** [comment]
Arrgh: https://github.com/helm/helm/issues/1311 and of course `helm lint` does not complain at all...

This fixes it for me:

```
--- a/config/iap/templates/deployments.yaml
+++ b/config/iap/templates/deployments.yaml
@@ -1,3 +1,4 @@
+{{- $root := . -}}
 {{- range .Values.iap.deployments }}
 ---
 apiVersion: apps/v1
@@ -19,8 +20,8 @@ spec:
         app: iap
         target: {{ .name }}
       annotations:
-        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
-        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
+        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") $root | sha256sum }}
+        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") $root | sha256sum }}
     spec:
       containers:
       - name: keycloak-proxy
```

I will open a PR in a minute. Sorry.

**Comment by xrstf** [comment]
I was just this moment figuring out that we need `$` instead of `.`. :-D

**Comment by bashofmann** [comment]
What's strange is: Why didn't it break the build in the PR so that we would've caught it before merging?

**Comment by xrstf** [comment]
The stock values.yaml has no deployments, so the deployment isn't rendered at all.

**Comment by maciaszczykm** [comment]
Is the error from https://drone.loodse.com/kubermatic/kubermatic/5810/6 connected to this or is it something else? Just letting you know about it.

@bashofmann @xrstf

**Comment by maciaszczykm** [comment]
Please close it if it is not connected.

**Comment by p0lyn0mial** [comment]
is someone working on it ?

**Comment by xrstf** [comment]
```
+ helm upgrade --install --wait --timeout 300 --tiller-namespace=kubermatic-installer --set=kubermatic.isMaster=true --set=kubermatic.controller.image.tag=2718529816dbd4e6b5d772636d2c87b245a12fc9 --set=kubermatic.api.image.tag=2718529816dbd4e6b5d772636d2c87b245a12fc9 --set=kubermatic.rbac.image.tag=2718529816dbd4e6b5d772636d2c87b245a12fc9 --values /go/src/github.com/kubermatic/kubermatic/values.yaml --namespace kubermatic kubermatic ./config/kubermatic/
Error: UPGRADE FAILED: render error in "kubermatic/templates/rbac-generator-dep.yaml": template: kubermatic/templates/rbac-generator-dep.yaml:28:44: executing "kubermatic/templates/rbac-generator-dep.yaml" at <.Values.kubermatic.p...>: can't evaluate field dry_run in type interface {}
```

This does not look related to the IAP template hiccup, but rather like a separate issue. It's caued by this line:

```
-dry-run={{default "false" .Values.kubermatic.project_migrator.dry_run}}
```

**Comment by xrstf** [comment]
That flag is as far as I can see only set in 

```
ci-run-minimal-conformance-tests.sh:  --set=kubermatic.project_migrator.dry_run=true \
```

Without this, not even `project_migrator` exists and I think this will cause an error even before the `default` function can kick in. Simple fix should be to add

```
kubermatic:
  project_migrator:
    dry_run: false
```

to the `values.yaml`?

**Comment by p0lyn0mial** [comment]
I think this https://github.com/kubermatic/kubermatic/pull/2554/files pull introduced the issue

**Comment by xrstf** [comment]
I'll prepare a PR to do what I suggested.

**Comment by p0lyn0mial** [comment]
it actually might work because the mentioned pr changed
```
 -dry-run={{default "false" .Values.kubermatic.project_migrator.dry_run}}
```

**Comment by xrstf** [comment]
```
{{default "false" .Values.kubermatic.project_migrator.dry_run}}
```

will fail if `kubermatic.project_migrator` is not defined.

**Comment by p0lyn0mial** [comment]
@xrstf if you don't mind please make sure that other fields exist

**Comment by xrstf** [comment]
What *is* the default value actually? The Helm chart defaults to `false`, but the Go code defaults to `true`:

```
flag.BoolVar(&ctx.dryRun, "dry-run", true, "If true, only print the object that would be created, without creating them")
```

**Comment by p0lyn0mial** [comment]
since this concerns only the test I think it can default to `false`, the main purpose of `project_migrator` is to create a default project for running cluster resources.
