### ISSUE TITLE
Add Volumes and LB checkboxes to dashboard during delete cluster operation 

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#2603]
**User Story**
The user can specify if all  PVC/PV and/or LB should be deleted from the cluster in the cluster delete dialog
The dashboard shows a warning that the user must take care of potential left over resources at the cloud provider

**Comment by p0lyn0mial** [comment]
see also https://app.zenhub.com/workspaces/all-kubermatic-58863654794153994b62af76/issues/kubermatic/kubermatic/2449

**Comment by p0lyn0mial** [comment]
@zreigz I think we need to move it to `dashboard-v2` repo and I think there is no other way than closing this issue and creating a new one.
