### ISSUE TITLE
Make coreos autoupdate configurable

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#261]
During cluster creation the customer should be able to set if the coreos nodes have autoupdate enabled or disabled.

This needs to be later set in the cloud-config

**Comment by mrIncompetent** [comment]
Will be discussed with customer on 2017-03-08

**Comment by scruplelesswizard** [comment]
This should not be utilized as it goes against the entire purpose of Container Linux. We should instead defer to customer education and deploy clusters with a spread of the release channels instead for assurance that each release in progress is suitable for use in the cluster.

**Comment by mrIncompetent** [comment]
Reasons the customer had:
-No trust in coreos auto update
-Want to update cluster nodes them self (replace node by node)
-Autoupdate could deploy a new docker version which is not supported by the Kubelet which is running on the node
