### ISSUE TITLE
Write a proposal for cluster-autoscaler machine-deployment provider

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2620]
**User Story**

As a Kubermatic user I would like to leverage the cluster-autoscaler. As a Kubermatic developer, I would like concensus on how that could look like.

**Acceptance criteria**

* A proposal for cluster-autoscaler has been written
* The proposal for cluster-autoscaler has been agreed on
* The proposal for cluster-autoscaler has been merged

**Comment by mrIncompetent** [comment]
@alvaroaleman please evaluate the redhat work which has been done upstream and potentially close this issue here in favor of a new one

**Comment by alvaroaleman** [comment]
The RedHat implementation of the cluster-api provide for the CA just works, the only thing we have to do is to extend the machine-controller to add an annotation to nodes containing the owning machines name. Closing this and creating a follow-up
