### ISSUE TITLE
Dev deploy potential dependency cycle

### ISSUE THREAD

**Issue by floreks** [kubermatic/kubermatic#2631]
**User story**
Because of a typo in the config [this](https://drone.loodse.com/kubermatic/kubermatic/5924/6) build failed on a `helm upgrade ...` step that should have updated dex. Even after providing a fix it was impossible to get to this step again as `alertmanager` in the `iap` namespace has a dependency on dex ([build](https://drone.loodse.com/kubermatic/kubermatic/5931/6)). It started to fail before it could get to the place where it could fix dex deployment. The only option was to manually fix it with the CLI.

**Acceptace criteria**
We should make sure that dex upgrade step is executed before this one to avoid such issues in the future.

**Comment by mrIncompetent** [comment]
The deployment how happens in a particular order: https://github.com/kubermatic/kubermatic/blob/master/api/hack/deploy.sh

@floreks can you check if the above mentioned scenario won't happen in the future?

**Comment by alvaroaleman** [comment]
Closing as there was no feedback. @floreks Please re-open if this is still an issue

**Comment by floreks** [comment]
Looks fine now. It should be fixed. Sorry for late response.
