### ISSUE TITLE
Update Kubernetes Dashboard to v1.10.1

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#2642]
Currently v1.8.3 is used:

https://github.com/kubermatic/kubermatic/blob/616916df19f2fb3edd97c955e85c8c7e2e4d6efc/addons/dashboard/dashboard-controller.yaml#L32

We should use [v1.10.1](https://github.com/kubernetes/dashboard/releases/tag/v1.10.1).

**Comment by maciaszczykm** [comment]
cc @floreks

**Comment by floreks** [comment]
Oh wow. That is a bit old :slightly_smiling_face: We should update it asap.
