### ISSUE TITLE
New alertmanager slack template breaks alertmanager

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2655]
https://github.com/kubermatic/kubermatic/pull/2650 introduced changes in the alertmanager template.

This results in Alertmanager to crash:
```
level=error ts=2019-01-18T16:17:53.712863606Z caller=main.go:325 msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="template: kubermatic.tmpl:10: function \"match\" not defined"
```

**Acceptance criteria**
- [x] The supplied template does not lead to crashes and works.

**Comment by xrstf** [comment]
Pods were still being created with the old Alertmanager version. Waiting a bit for the StatefulSet to take effect and nuking the old pods solves the issue.
