### ISSUE TITLE
Centralized alertmanager client authentication

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#2659]
In kubermatic setups where there are more than 1 seed cluster, it's useful to have alerts centralized in 1 central point. So I'd like to introduce alertmanager that is only deployed in master cluster, all other prometheuses from other clusters will use it. That brings-up authentication question, how should we securely authenticate prometheuses from other clusters and not expose alertmanager to whole internet.

We already have cert-manager and ingress-controller in our stack, and they should be put together to resolve external client authentication issue.

The plan:
* [ ] generate CA key/cert
* [ ] Save CA key/cert to secret in every cluster
* [ ] create cert-manager `Issuer` that uses aforementioned CA
* [ ] create `Certificate` that uses CA `Issuer`
* [ ] use that `Certificate` in new `Ingress` and require client authentication
* [ ] change prometheuses deployments to grab cert/key
* [ ] prometheuses will use `tls_config:` to configure client certificate for alertmanager requests

**Comment by xrstf** [comment]
Obsoleted by newer plans on master monitoring setup.
