### ISSUE TITLE
Controller managers stops working in some situations

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2692]
The kubernetes controller-manager seems to stop working in some situations.
So far we've seen that in e2e tests where we had multiple replicas + the VPA enabled.

The restart of the API server pod led to this situations.

Some logs from an affected cluster:
https://kibana.dev.kubermatic.io/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2019-01-24T13:56:56.012Z',mode:absolute,to:'2019-01-24T15:33:37.295Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e940f290-1db3-11e9-ba32-3935bfaacc2f,key:kubernetes.labels.app,negate:!f,params:(query:controller-manager,type:phrase),type:phrase,value:controller-manager),query:(match:(kubernetes.labels.app:(query:controller-manager,type:phrase))))),index:e940f290-1db3-11e9-ba32-3935bfaacc2f,interval:auto,query:(language:lucene,query:'kubernetes.namespace_name:%22cluster-prow-e2e-7rtgw6hf%22%20AND%20log:%22failed%22%20AND%20%20(NOT%20log:%22because%20it%20is%20being%20terminated%22)'),sort:!('@timestamp',desc))

**Comment by alvaroaleman** [comment]
How do you derive the "controller manager stops working" from the logs above? Does "stops working" imply its livenyness check also fails?

**Comment by mrIncompetent** [comment]
The controller-manager does not sync ReplicaSets / Deployments anymore - but unfortunately, I don't have any logs for this. 
I only saw this live on a affected cluster :/

**Comment by alvaroaleman** [comment]
@mrIncompetent Can we close this as there is no clear path to repro this?
