### ISSUE TITLE
Delete button of node deployment at cluster details view broken

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#2701]
Currently if I trigger the deletion of a node deployment over the cluster details view, the `Delete Node Deployment` dialog shows up, but no action is triggered afterwards. If I click on node deployment, which open the node deployment detail view, and click then the `Delete Node Deployment` button the same `Delete Node Deployment` dialog  will trigger t the deletion.

![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/b548ed6e-7cf2-4755-b92b-73a60336014e)

**Comment by maciaszczykm** [comment]
It was fixed in https://github.com/kubermatic/dashboard-v2/pull/1035.

**Comment by p0lyn0mial** [comment]
I have validated if a `Node Deployment` can be deleted both from `Cluster Details` and `Node Deployment` page.
 
closing, fixed by https://github.com/kubermatic/dashboard-v2/pull/1035
