### ISSUE TITLE
Make Container Linux version configurable on AWS

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#271]

**Comment by scruplelesswizard** [comment]
We should allow the customer to select the update channel, but _not_ select a version. The node will update to the latest version in the channel once it detects it.
Related to https://github.com/kubermatic/api/issues/261 we should defer to education instead.

**Comment by scheeles** [comment]
CoreOS provides the similar function with their paid subscription. 
"Roll out specific versions of Container Linux to a channel"
See https://coreos.com/products/container-linux-subscription 

and here you find all versions for stable https://stable.release.core-os.net/amd64-usr/
