### ISSUE TITLE
Add basic operation manual

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#2726]
**User Story**
As end-user currently it's not clear how to operate Kubermatic in general.
Because auf this we should transfer the slides Kubermatic Basic Operations into the docs.
https://github.com/kubermatic/secrets/tree/master/seed-clusters/run.kubermatic.io

**Acceptance criteria**
*  Content is added to the docs

**Comment by mrIncompetent** [comment]
Slides: https://docs.google.com/presentation/d/1wXviNqCiU2FGBE1mkKr6obMvNAeQVU0J4j4UA_yKR-E/edit#slide=id.g3de0e6e9ef_2_62

**Comment by toschneck** [comment]
The general version of Kubermatic Ops Intro + Debugging tasks, can be found here: https://docs.google.com/presentation/d/1ijk4Ha5IOrlorVEqW6mTbMvmMy9xQUbQSYreA5o1c3A/edit#slide=id.g4cc7d10ed4_0_36

**Comment by mrIncompetent** [comment]
@toschneck Please check the updated docs & reopen this issue in case we've missed something
