### ISSUE TITLE
Make disksize configurable on aws

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#273]

**Comment by scruplelesswizard** [comment]
This encourages use of `hostPath`. We should turn down this feature request and instead size up the nodes from 8GB to something like 30GB, or make the image GC more aggresive

**Comment by mrIncompetent** [comment]
@chaosaffe Some customers WILL have GB-size docker images and they need it to be configurable.

**Comment by scruplelesswizard** [comment]
If they have GB sized containers, then they need a lot more help than Kubermatic can provide them... The only way you have containers that big is if you are doing something _very_ wrong. 

That being said, we should not define this as storage for the node then, we should call this "Container Storage Size" or something similar, and map the separate volume to the Docker image store. This allows for the customer to have large images, but prevents the from using the node for data storage
