### ISSUE TITLE
Support AWS spot instances in Kubermatic

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2769]
**User Story**

As a user of Kubermatic I have clusters that I want to run on AWS and whose workloads may get interrupted as long as running them is cheap.

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/2769).

**Acceptance criteria**

* The machine-controller supports creation of AWS spot instances: https://github.com/kubermatic/machine-controller/pull/449
* The API supports specifying weather an AWS Machinedeployment should use spot instances
* The UI supports specifying weather an AWS MachineDeployment should use spot instances
* When using AWS spot instances, we deploy a DaemonSet that automatically drains instances prior to terminiation to minimize runtime interruptions, e.G. https://github.com/pusher/k8s-spot-termination-handler
* We know exactly how this DaemonSet works, e.G. what happens if draining doesn't finish within the two minute grace period from AWS
* We have documented what it means for the availability of workloads to use AWS spot instances
* We have documented how this DS works for AWS spot instances

**Comment by alvaroaleman** [comment]
@kdomanski @scheeles What is the priority on this?

**Comment by zreigz** [comment]
we would like to keep this issue for later

**Comment by shaase-ctrl** [comment]
How to ensure that the user receives correct feedback about availability of the spot instance?
