### ISSUE TITLE
Make the disk space on other platform configurable 

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#2789]
**User Story**

On AWS the can configure the disk space of the worker-nodes. Adopt this feature also to other platform where it would be possible

According to @alvaroaleman Azure perhaps Digitalocean no, Hetzner no, Openstack yes, Vsphere yes

**Acceptance criteria**

**Comment by alvaroaleman** [comment]
@scheeles What is the priority on this?

**Comment by alvaroaleman** [comment]
@alvaroaleman create a distinct ticket per provider

**Comment by mrIncompetent** [comment]
@alvaroaleman Please create a distinct ticket per provider
