### ISSUE TITLE
Grafana - drill down to namespace is broken

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#2842]
On the current version of the Grafana Dashbaord - `compute-resources-cluster` the drill down feature is broken. If I select an namespace the link is not valid and the error `Dashboard not found` appears.

Created URL after click on `Drill down`: `https://grafana.dev.kubermatic.io/d/85a562078cdf77779eaa1add43ccec1e/k8s-resources-namespace?var-datasource=prometheus&var-namespace=cluster-nzhx4nrb9f&orgId=1`

![image](https://user-images.githubusercontent.com/4659261/53125661-cb913580-355e-11e9-990a-1034a2b0e28c.png)

**Comment by xrstf** [comment]
This has been fixes by #3009.
