### ISSUE TITLE
Set up automated scanning for outdated and/or vulnerable Docker images

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#2855]

**Comment by alvaroaleman** [comment]
* This issue is mainly about getting notified, the image scanning itself is already done by quay
* The notifying may be especially important for images that get updated seldom, like e.G. the openvpn

@kdomanski Clarify what exactly this issue should be about

**Comment by mrIncompetent** [comment]
Closing as it needs clarification from the SIG dependencies
