### ISSUE TITLE
ARM support for nodes

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#2856]
**Scope**

Kubernetes already runs nicely on ARM. Potential customers are starting to ask for ARM support of Kubermatic. There is no real known technical difficulty supporting Kubermatic on ARM.

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/2856).

**Status**

Summary: [a presentation](https://docs.google.com/presentation/d/117dzJxV9-COamB58L5SF-o7VlZZYOWoz47El5KFZIog)

* Kubermatic addons have some hardcoded `amd64` architecture references.
* Kubermatic addons are outdated (very old canal, needs update to have multi-arch image)
  - or we could change the CNI to calico and use the multiarch images

**Desired**

* ARM workers can join a Kubermatic cluster

**Comment by kdomanski** [comment]
@irozzo-1A Please create a story for migration to Calico, which is blocking this.

**Comment by irozzo-1A** [comment]
@kdomanski #5589

**Comment by moadqassem** [comment]
After some discussion about this ticket, the first idea was to create arm worker nodes. Regarding running KKP on ARM machine this has to be discussed again to see if it really brings any value for now. If at some point of time we decide we need that for KKP too we can of course open this topic again,

**Comment by moadqassem** [comment]
At the moment, we are only interested of supporting ARM worker loads than running KKP on ARM machines, thus this epic will be close.
