### ISSUE TITLE
Delete cluster where the secret is not valid anymore

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#286]
Currently it is not possible to delete a cluster if you first delete the access tokens.

You can try it with this one https://beta.kubermatic.io/dc/europe-west1/cluster/7vtb9lfj9

**Comment by mrIncompetent** [comment]
@scheeles Shouldn't we rather ignore a ~"invalid token"-error on cluster deletion?

**Comment by scheeles** [comment]
Yes
