### ISSUE TITLE
Add an endpoint to return possible kubelet versions for a specific control plane version

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#2866]
**User Story** I'd like to have an endpoint that is not only able to return possible kubelet versions for a cluster (using its control plane versions) but also for specific control plane versions. It can be used when user would like to modify control plane and kubelet versions at once and can be built like already existing endpoint.

**Acceptance criteria** New endpoint is available and there are tests for it.

**Comment by maciaszczykm** [comment]
cc @p0lyn0mial

**Comment by p0lyn0mial** [comment]
after adding the new ep the old one should be removed https://github.com/kubermatic/kubermatic/blob/86b9c9c6c7c7680aa5d09df15f25554b37cf554c/api/pkg/handler/routes_v1.go#L150

**Comment by maciaszczykm** [comment]
Request param for `GET /api/v1/upgrades/node` should be in query not in the body. We'll have to update this.
