### ISSUE TITLE
NetworkPluginNotReady error displayed during node creation

### ISSUE THREAD

**Issue by bashofmann** [kubermatic/kubermatic#2867]
The dashboard often displays a NetworkPluginNotReady not ready error for a few secondes when a node is created:

```
During the create there was runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized message.
```

We know that this is not serious, and the nodes are created successfully after that. But it is very confusing for our users and we already had several support tickets because of that. It also does not create trust for the user, if we show an error that actually is not an error.

**Comment by kgroschoff** [comment]
@bashofmann Does this "error" still appear for you?

**Comment by bashofmann** [comment]
Yes it still does, but it is way more hidden now:

![Bildschirmfoto 2020-01-09 um 15 41 06](https://user-images.githubusercontent.com/243056/72076847-8a308280-32f6-11ea-85e8-46d139d07984.png)
