### ISSUE TITLE
Deleting project causes error 404

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#2883]
**User Story**
Delete project in Dasboard.
During this process when Dasboard calls for /projects list the removed project is not assigned to the user anymore. This generates the error: `projects.kubermatic.k8s.io "rqmp9lqzg8" is forbidden: User "xxx@loodse.com" cannot get projects.kubermatic.k8s.io at the cluster scope`

**Comment by kgroschoff** [comment]
Also see similar error sometimes during cluster deletion, but definitely not as often as during project deletion, will put in explicit error in here whenever I see it again.
