### ISSUE TITLE
Tag clusters with a configuration version and creation/update timestamp

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#290]
Currently we don't know which configuration the client clusters are using. Once we have a CI/CD pipeline for Config, we can annotate the namespace with the configuration version (commit hash?) that was deployed last, and the timestamp for the cluster creation and cluster update. 

Ideally, this would be implemented as part of the 'Pending' phase

**Comment by mrIncompetent** [comment]
@scheeles solveable via kubermatic-installer?

**Comment by mrIncompetent** [comment]
Clusters are now always up to data as the controller always checks actual state & desired state and acts upon that
