### ISSUE TITLE
Implement Authorization Webhook

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#2925]
**Background**: Users download kubeconfig from the Dashboard for the given cluster. The config contains ID and Refresh tokens and is valid for as long as the Refresh token is valid. Kube API server knows how to verify the token and extract a user info from it.

**Motivation** When accessing a cluster users are dynamically assigned to the group they currently belong. Note that affiliation to a group is not fixed and can change at any time. Being able to assign users to a group at runtime don't force them to download the configuration file each time they are assigned to a different group. In addition to that we can revoke and give access to the cluster again every time a user is removed and then added to the project.

**Implementation**: TBD

**Comment by p0lyn0mial** [comment]
@alvaroaleman last time we spoke you suggested to use certificates. I think a Webhook is better mainly because we can dynamically assign users to a group and revoke access to the cluster. What do you think ?

**Comment by alvaroaleman** [comment]
> @alvaroaleman last time we spoke you suggested to use certificates. I think a Webhook is better mainly because we can dynamically assign users to a group and revoke access to the cluster. What do you think ?

Yes, certificates have the huge drawback that we cant revoke them (except if we revoke the CA which casues all nodes to break)

So the idea is to have basically proxy access to the kube api with something that sets appropriate groups?

**Comment by mrIncompetent** [comment]
I'm missing some context here.
Does changing the group of a user require the user to download the kubeconfig again (Does it make the old kubeconfig invalid)?
