### ISSUE TITLE
Model resource deployment as a DAG

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#2948]
**User Story**

Right now we deploy the control plane components ordered by type and then ordered by what the developer of the code did (e.G secrets first, then ConfigMaps, then Deployments). This is only a very rough approximation of the actual hirarchy and requires developers and reviewers to be very careful, to e.G. always make sure that CA secrets get created before certificates that use that CA get created, otherwise we run into a dead lock.

Ideally it would be possible that every resource can specify its requirements (other resources but also e.G. something that is managed by another controller like the cloud-controller) and we calculate a DAG from that and just traverse that DAG.

**Acceptance criteria**
* All resources managed by the cluster-controller or openshift-controller can specify requirements they have
* These requirements may either be other resources or something that can be derived from the cluster CR
* Based on those requirements we calculate a DAG
* The resource deployment is done by traversing the DAG instead of by deploying the resources ordered by type

**Comment by alvaroaleman** [comment]
An alternate approach (suggested by @moadqassem ) would be to let all kube objects we deploy  implement a

```
type resourceDeployment interface {
  // Blocks until all dependencies are met
  // Uses a kube client to poll the API
  WaitForDependencies() error
  // Deplos the object
  Deploy() error
}
```

Then have in the cluster/openshift controller a simple
```
resources := []resourceDeployment{...}
errChan := make(chan error)
for _, resource {
  go func() { 
    if err := resource.WaitForDependencies(); err != nil {
         errChan <- err
         return
     }
    if err := resource.Deploy(); err != nil {
      errChan <- err
    }
  }()
}
```

(waitgroup and timeout omitted for simplicity)

**Comment by irozzo-1A** [comment]
Re-opening as this approach could be a good fit for #6225 and #5949.

**Comment by irozzo-1A** [comment]
I'm also evaluating [expectations](https://github.com/kubernetes/kubernetes/blob/1889a6ef52eb18b08e24843577c5b9d3b9a65daa/pkg/controller/controller_utils.go) used in some k8s controllers as an alternative approach (thx @mfranczy for the suggestion).
