### ISSUE TITLE
[machine-controller] External userdata plugins

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2987]
**User Story**

We want to keep the UserData code for OpenShift closed, which requires us to version the OpenShift specific UserData code outside the [machine-controller repo](https://github.com/kubermatic/machine-controller).

To avoid the forking & rebasing workflow which requires a constant effort we're going to make the UserData functionality pluggable.

- [ ] UserData plugins will be stored as binary next to the machine-controller binary.
- [ ] Invocation of the plugins as start with environment variables containing the arguments and return of results via STDOUT

**Using a plugin**

When the machine-controller needs to create userdata it does the following steps:

- [x] Initially check if there is a plugin for an OS
  - Check list of registered plugins
  - Check binaries on the host with a suitable name (Example: `/usr/local/bin/machine-controller-userdata-centos7`)
  - Directories for search a specified by 
    - Environment variable `MACHINE_CONTROLLER_USERDATA_PLUGIN_DIR`
    - Directory of the machine controller binary
    - Working directory
    - `PATH`
- [x] Check if the plugin has been registered already
- [x] Register the plugin
- [x] Call the plugin to get the userdata

**Plugin CLI interface**

- [ ] Every plugin must expose the following flag:

```
// Enables / Disables debug logs
-debug
```

- [ ] Every plugin has to check the environment variable `REQUEST` for the concrete request
- [ ] Every plugin has to understand the request `MACHINE_CONTROLLER_USER_DATA_REQUEST` and to check the according environment variable for the request arguments

**Kubermatic integration (Switch Kubernetes/OpenShift)**

The machine controller will be deployed with an Init container which copies the user data plugins onto a shared volume.

- [ ] If its a OpenShift cluster, only the CentOS 7 and OpenShift plugin must be copied
- [ ] If it's a Kubernetes cluster, all normal plugins will be deployed

The OpenShift and Kubernetes UserData plugin for OpenShift must have the same name. We will not use a generic `openshift` name, as the operating system names will be used by the cloud provider implementation. This also enables us to later expand the OpenShift support to other operating systems (Or add others, like Atomic).

**Comment by themue** [comment]
After short evaluation the first approach will use `net/rpc` via Unix domain sockets instead of gRPC.

**Comment by themue** [comment]
Switched to simple call of binary and passing arguments in environment and results in STDOUT.

**Comment by alvaroaleman** [comment]
PR in Kubermatic for an Openshift plugin: #3096
