### ISSUE TITLE
Add ContainerLinuxUpdateOperator

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#2996]
**User Story**
As a user of Kubermatic i want that my ContainerLinux based cluster does coordinated reboots.

The [ContainerLinuxUpdateOperator](https://github.com/coreos/container-linux-update-operator) does exactly that.

Issue though is that user clusters can have mixed nodes, which will make the pods fail if they run on a non ContainerLinux node.

To schedule the pods only on ContainerLinux nodes they need to be labeled. (By default there is no label on Nodes which would enable this)

**Acceptance criteria**
- [ ] Extend the user cluster controller to label all ContainerLinux nodes with the label `kubernetes.io/coreos=true`
- [ ] Add a addon for the ContainerLinuxUpdateOperator

**Comment by kdomanski** [comment]
Duplicate of #2080
