### ISSUE TITLE
Add the Prometheus node-exporter to the addons

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3017]
**User Story**
To better be able to identify the healthiness of a user cluster we must scrape more information from the worker nodes. The Prometheus node-exporter does give us enough system level metrics.

**Acceptance criteria**
- [ ] The node-exporter has been added to the addons
- [ ] The node-exporter uses [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) to ensure that the metrics endpoint is secured

**Comment by alvaroaleman** [comment]
This is done alrady

**Comment by alvaroaleman** [comment]
@alvaroaleman check if this should be in the default addons
