### ISSUE TITLE
Add node overview dashboard for user clusters 

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3022]
**User Story**
As a admin of Kubermatic i want to have a dashboard which shows the utilization of the worker nodes of individual user clusters.

Basically a clone of the seed cluster's "Nodes overview" dashboard where i could select the cluster to look at.

**Acceptance criteria**
- [ ] A the new dashboard has been added

**Comment by xrstf** [comment]
This would require installing node-exporter into user clusters, hoping that users will not nuke it. Are we sure we want to do that?

**Comment by mrIncompetent** [comment]
Even if users nuke it, the addon controller will reinstall it.

Idea is to add it as optional addon (Always enabled for dev, cloud, run & ci)
