### ISSUE TITLE
AWS: allow providing a CIDR with which to create a new VPC for a cluster

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#3024]
**User Story**
On providers like Azure or OpenStack, we create a new virtual network for each cluster (if no specific network is provided in the config), ensuring that each cluster is isolated from other clusters' traffic. In our AWS provider, however, we use the default VPC instead, causing multiple clusters to share a network. This often cannot be the case.

**Acceptance criteria**
- [ ] If no VPC is provided, a new VPC will be created for the cluster on its creation
- [ ] If Kubermatic created a VPC for a cluster, then it will delete the VPC on the cluster's deletion

**Comment by mrIncompetent** [comment]
@mrIncompetent Check for the priority

**Comment by mrIncompetent** [comment]
@kdomanski This issue needs clarification around the subnet CIDR.
How does this affect multi AZ support?

**Comment by kdomanski** [comment]
From my chat w/ Henrik on March 26th:
```
my proposal for the AWS VPC creation workflow:
- a new field in AWS provider config, `vpcCIDR`
- controller wil create a new VPC with that CIDR
- the CIDR will be split into 4 equal chunks
- chunks will be equally distributed among subnets, 1 for each availability zone
```

**Comment by kdomanski** [comment]
Note: we're currently adding a default storage class in the addons, bound to the first AZ.

It seems like we have this one subnet/AZ binding, because at some point we created a VPC ourselves, and we wanted simplicity. But since that time, we removed the VPC creation
https://github.com/kubermatic/kubermatic/pull/282

**Comment by kdomanski** [comment]
VPC creation was initially added in https://github.com/kubermatic/kubermatic/commit/8eb32a51ce8acaf0042694d5cf96c36829b80e11

**Comment by mrIncompetent** [comment]
To sum it up, we create
- VPC
- Subnets (1 per zone)
- InternetGateway
- RouteTable
- Routes

And in the end we use the subnet, which fits to the zone defined in the datacenters.yaml?

**Comment by mrIncompetent** [comment]
Does creating a VPC mean its public or private?
So do we create a InternetGateway or a NAT Gateway?

**Comment by kdomanski** [comment]
IMO InternetGateway, because NAT gateways do not support IPv6 egress which might be an issue in the future.
@thz WDYT?

**Comment by thz** [comment]
For v6 aws advises to use an egress-only-internet-gateway which is not the same thing as an igw.
If we really consider v6 for decisions now, then we should first clarify some details about that. Are we doing it mutually exclusive with v4? Do we plan dual stack? We would probably leave some options for the user here too. I think we should solve this thing here for v4 only and handle v6 with dedicated thinking.

**Comment by thz** [comment]
Will solving this issue remove the functionality of using the default VPC?

**Comment by kdomanski** [comment]
No it won't and I think it would be prudent to stay as close to the defaults here as possible.

**Comment by alvaroaleman** [comment]
Just as an FYI, Kubernetes doen't support IPV6 at all. The only place where ipv6 could be used is during machine provisioning and when downloading docker images. All traffic that has a pod as src or dest is guranteed to be ipv4

**Comment by thz** [comment]
Kubernetes does support some v6. Kube-proxy can do v6. Currently this is mutual exclusive with v4 but dual stacking is what is currently worked on in sig network.

**Comment by alvaroaleman** [comment]
Yeah that is true but the very first alpha will land in 1.16 and its a huge topic so I doubt if it will become stable anytime soon.
My point was that IMHO ipv6 is not a good reason for or against anything right now.

**Comment by mrIncompetent** [comment]
@kdomanski @toschneck 
Does this issue (And the Azure one as well) conflict with the KubeTerra integration?
As i understood KubeTerra it is meant to setup basic infrastructure for Kubermatic clusters

**Comment by kdomanski** [comment]
Conflict in what way? I only see an overlap in scope.

**Comment by mrIncompetent** [comment]
>  I only see an overlap in scope.

Right it is just an overlap in scope.
Since a customer requires this until the end of this month does this issue still make sense to implement? Unless we want to have 2 different ways of spinning up new networks

**Comment by toschneck** [comment]
@mrIncompetent @kdomanski  currently I don't think so. We can start with kubeterra execution after the VPC is created. Please talk with @kron4eg about this topic. He is already think about, how we can integrate/call kubeterra in the future into Kubermatic.

**Comment by toschneck** [comment]
/remove-lifecycle stale

could be still a valid case but low prio

**Comment by kirek007** [comment]
Hey, Is this feature still on your roadmap? Currently I would like to create a multiple clusters in AWS but I've to manage VPC on my own, it would be great if KKP could take care of creation based on provided CIDR.
