### ISSUE TITLE
Add a liveness probe to the openvpn-client (Addon)

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3025]
**User Story**
The openvpn-client pod must have a liveness check. This ensures the openvpn-client gets restarted when its not healthy.
We've seem in a recent outage that the pod might reach the "limbo" which required manual intervention.

This only focuses on the openvpn-client which gets deployed into user clusters.

**Acceptance criteria**
- [ ] Add a liveness probe to the OpenVPN client pod

**Comment by alvaroaleman** [comment]
@thz knows how the actual liveness check should look like

**Comment by thz** [comment]
My proposal is to do a curl or ping to the apiserver.

**Comment by thz** [comment]
Because the apiserver IP in the vpn network is not static, it might be difficult to "curl or ping the apiserver" via the vpn. For that reason it might be a better approach to just `ping -c 1 -w 5 10.20.0.1` for assessing the vpn-client health. It is also more correct.
