### ISSUE TITLE
Investigate increasing the conntrack limit via kube-proxy

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3026]
**User Story**
During a recent outage we've encountered that we reached the conntrack limit within the seed cluster.

As this can potentially happen within a user cluster as well, we should check if we should set a higher conntrack limit.

Kube proxy does offer the following flags:
```
--conntrack-max-per-core int32     Default: 32768
    Maximum number of NAT connections to track per CPU core (0 to leave the limit as-is and ignore conntrack-min).
--conntrack-min int32     Default: 131072
    Minimum number of conntrack entries to allocate, regardless of conntrack-max-per-core (set conntrack-max-per-core=0 to leave the limit as-is).
--conntrack-tcp-timeout-close-wait duration     Default: 1h0m0s
    NAT timeout for TCP connections in the CLOSE_WAIT state
--conntrack-tcp-timeout-established duration     Default: 24h0m0s
    Idle timeout for established TCP connections (0 to leave as-is)
```

**Comment by mrIncompetent** [comment]
cc @thz

**Comment by thz** [comment]
I do not like the per-cpu-core too much in our setting. I'd propose to set this to 0 and go with 512k conntrack-min for user-cluster.
We can also reduce close-wait timeout to 15min and to 2h for established connections.
That should be a sane default.
