### ISSUE TITLE
deploy helm-exporter

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#3031]
[helm-exporter](https://github.com/helm/charts/tree/master/stable/helm-exporter) will help to detect early that there are some problems it deploys.

**Comment by xrstf** [comment]
The current version 0.3.1 is broken for Tillers not installed into `kube-system`, we'll have to wait for https://github.com/sstarcher/helm-exporter/pull/12 to be merged.

**Comment by xrstf** [comment]
PR has been merged and release in 0.4.0.
