### ISSUE TITLE
Create alert for init_node_deployment_failures metric

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#3041]
**User Story** Alert for `init_node_deployment_failures` should be created once #2989 gets merged.

**Acceptance criteria**
- [ ] There is an alert for `init_node_deployment_failures` metric.

**Comment by p0lyn0mial** [comment]
I think that's [the place](https://github.com/kubermatic/kubermatic/tree/master/config/monitoring/prometheus/rules) where we could add the metric
