### ISSUE TITLE
[needs design] Azure: allow providing a CIDR with which to create a new network for a cluster

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#3091]
**User Story**
Currently the Azure provider creates a network and a single subnet within it for clusters with no network/subnet ID specifed. For both of them, the CIDR `10.0.0.0/16` is used.

At this time, we need to be able to customize the CIDR used, because some customers use the `10.0.0.0/8` CIDR for internal networks and only a specific slice of it is unrouted and usable for LANs.

Any more sophisticated changes to Azure provider network handing are **out of scope**.

**Acceptance criteria**
- [ ] **NEEDS REFINEMENT**
- [ ] **NEEDS UI TICKET**
- [ ] The Kubermatic API allows specifying a custom CIDR to assign to new clusters' networks

**Comment by mrIncompetent** [comment]
@kdomanski Please clarify

**Comment by kdomanski** [comment]
The ticket is analogous to the AWS network creation ticket #3024
