### ISSUE TITLE
Openshift support in Kubermatic

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3119]
**User Story**

As a customer of Kubermatic I want to use it to manage Openshift.

**Acceptance criteria**

* Users can create Openshift clusters via the Kubermatic UI
* Automated testing for Openshift is set up
* Openshift Routes can be created and work
* The openshift UI can be accessed and works
* Openshift clusters can be setup on any provider that is supported for Kubernetes

Further details on the topic and discussions are tracked here: https://docs.google.com/document/d/1wjqpcoAqscGuP0HjyFM5fJVo5KTUjQaMN0PHDbWf17w/edit?ts=5ca1bc0e

**Comment by kdomanski** [comment]
Closing in favor of #3638
