### ISSUE TITLE
Add the OpenShift webconsole

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3124]
**User Story**
The OpenShift webconsole is a relevant part of the OpenShift control plane.
It must be deployed inside the seed cluster & be available for the user.

**Acceptance criteria**
- [ ] The OpenShift APIserver uses Dex for authentication
- [ ] The webconsole is available from the outside (Without cert issues)

**Comment by alvaroaleman** [comment]
A potential solution to the "redirect to a site that doesnt pass the hsts check" could be to fork the webconsole
