### ISSUE TITLE
[cluster/cloud-controller] Investigate multi AZ support

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3139]
**User Story**
Investigate if there's anything to do within the cluster/cloud-controller to support https://github.com/kubermatic/kubermatic/issues/678

Things that come to my mind which we should check: 
- Cloud provider initialization
  Each AWS zone has a dedicated subnet. Each subnet for an kubernetes cluster must be tagged, but we only tag one atm
- cloud-config
  Validate that we have no zone specific settings inside the cloud configs

**Comment by mrIncompetent** [comment]
Timeboxed to 1day

**Comment by alvaroaleman** [comment]
* Change the `zone_character string` in the  AWS datacenter spec to `zone_characters []string` (Potentially leave the old setting and just add it to `zone_characters` for compatibility reasons)
* Subnet tagging: Nothing to do here, we already tag all subnets of the VPC in the region (The ec2 client contains the region, thats why its not tagging _all_ subnets of the VPC): https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/cloud/aws/provider.go#L165-L179
* The AWS cloudspec currently contains a `SubnetID` string. It is only used during machine creation. We must change this to a `map[string]string`, containing an AZ/SubnetID mapping
* We pass the Zone into the controller-manager and APIServer both via an env var `AvailabilityZone` and as part of the `cloud-config`. There is a comment in the cloud provider code thought, that sounds like its not really required: https://github.com/kubernetes/kubernetes/blob/32b37f5a85e8f2987f8367e611147cd4d4dfa4f9/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L539
* We set the `SubnetID` in the cloud-config, but there are only one references to it from the AWS code: https://github.com/kubernetes/kubernetes/blob/32b37f5a85e8f2987f8367e611147cd4d4dfa4f9/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1272 The subnetID for the instances is fetched from the API, not the cloud-config: https://github.com/kubernetes/kubernetes/blob/32b37f5a85e8f2987f8367e611147cd4d4dfa4f9/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1757

Tl, dr: Should be trivial from controller-side. We obviously must verify at the end that there are no errors and LBs and PVs still work, but I am optimistic that will be the case

**Comment by alvaroaleman** [comment]
Created a follow-up for the implementation: https://github.com/kubermatic/kubermatic/issues/3456
