### ISSUE TITLE
Memory request & limit should be configurable via values.yaml for kubermatic controller manager

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3156]
**User Story**
In v2.9 the requests & limits where hardcoded - but far to small for a medium cluster.

We changed that in master for all charts. To avoid complications, we should cherry pick only the kubermatic controller manager changes into v2.9

**Acceptance criteria**
- [ ] Memory+CPU limit+request for the Kubermatic controller manager can be configured via values.yaml (Same values.yaml structure as in the master branch)

**Comment by mrIncompetent** [comment]
cc @multi-io

**Comment by xrstf** [comment]
This has been fixed.
