### ISSUE TITLE
VPA recommender does not set recommendations on VPA objects

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3210]
**User Story**
The VPA recommender does not set recommendations on VPA objects.
This can be reproduced by creating a new cluster on dev.kubermatic.io & watching the VPA objects in the cluster namespace.

**Acceptance criteria**
- [ ] The VPA recommender sets recommendations on VPA objects

**Comment by xrstf** [comment]
I can see that not all verticalpodautoscaler resources have recommendations, but some do. So I'm not sure the VPA is actually broken.

**Comment by mrIncompetent** [comment]
Cannot be replicated :/
