### ISSUE TITLE
Setup test environment for offline environment

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3227]
**User Story**

As a Kubermatic developer I want a way to verify that offline support actually works.

**Acceptance criteria**

* There is a test environment for offline support
* It contains a VPC. Instances created within that VPC can not reach the internet
* It also contains a proxy instance, that provides a HTTP proxy to reach the internet
* It contains a Docker Registry that is available without a proxy
* It contains a DNS server that allows resolving the registry and proxy
* The whole environment is reproducible
* The environment is created at AWS

**Comment by mrIncompetent** [comment]
Needs clarification on follow up issues when this is done

**Comment by alvaroaleman** [comment]
This is done on GCP now, as AWS doesn't support reaching its IAM API from an instance that doesn't have Internet access.
