### ISSUE TITLE
GCE support

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3234]
**User Story**

As a user of Kubermatic I want to be able to use it for GCE-based clusters

**Acceptance criteria**

* It is possible to configure GCE node datacenters
* The cloud controller can create and cleanup the required GCE infrastructure
* The conformance tester can test GCE clusters and they pass the tests
* It is possible to choose GCE from the UI when configured

**Comment by nikhita** [comment]
Related issues:

- https://github.com/kubermatic/kubermatic/issues/3120
- https://github.com/kubermatic/dashboard-v2/issues/1207

**Comment by nikhita** [comment]
Quick update - https://github.com/kubermatic/kubermatic/pull/3350 has merged.

**Comment by nikhita** [comment]
https://github.com/kubermatic/dashboard-v2/issues/1207 has merged. Closing.

**Comment by kdomanski** [comment]
Reopening to add some additional tickets.
