### ISSUE TITLE
Add Kubevirt support to Kubermatic

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3241]
**User Story**

As a user of Kubermatic I want to be able to use Kubevirt as backend for my Kubernetes clusters

**Acceptance criteria**

* It is possible to configure a Kubevirt node datacenter
* The conformance-tester binary can test Kubevirt clusters and they pass
* The kubevirt nodes use a PV-backed root disk
* It is possible to choose Kubevirt as provider from the UI

**Comment by alvaroaleman** [comment]
reopening, we are still missing to properly safe the kubeconfig in a secret

**Comment by maciaszczykm** [comment]
Done from the UI perspective.

**Comment by alvaroaleman** [comment]
Thanks!
/close
