### ISSUE TITLE
Add kubevirt support to the Kubermatic API

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3243]
**Acceptance criteria**

* The Kubermatic API endpoints have been extended to allow managing a Kubevirt cluster

**Comment by floreks** [comment]
@alvaroaleman what is the status of this? Is API for this ready?

**Comment by alvaroaleman** [comment]
Yeah, got added in https://github.com/kubermatic/kubermatic/pull/3942
