### ISSUE TITLE
Kubermatic Proxy environment support

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3245]
**User Story**

As a user of Kubermatic I want to use it in an environment where Internet access is only possible via a proxy

**Acceptance criteria**

* There is a testenvironment for installations that can reach the Internet only via a proxy
* There is a CI job that verifies this

**Comment by mrIncompetent** [comment]
> There is a test environment for complete offline installations

Is missing to complete this epic.
@kdomanski whats is the priority on a "full" offline environment?
So far we only requests from customers using a proxy environment

**Comment by alvaroaleman** [comment]
@mrIncompetent Can we also add documentation regarding what has to be configured for a proxy env? :grimacing:

**Comment by mrIncompetent** [comment]
Docs have been updated

**Comment by kdomanski** [comment]
The priority for a "full" offline environment is very low at this time.
