### ISSUE TITLE
Make the root disk size of Openstack instances configurable

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3251]
**User Story**

As a user I want to configure the size of the rootdisk of my Openstack instances

**Acceptance criteria**

* It is possible to configure the root disk size of Openstack instances via Kubermatic

**Comment by alvaroaleman** [comment]
Possible form controller side

**Comment by kdomanski** [comment]
cc @alvaroaleman 
Missing API and UI tickets

**Comment by bashofmann** [comment]
Making this configurable with the mechanism here https://github.com/kubermatic/machine-controller/pull/579 can be very dangerous when using localstorage node flavors: Instead of getting a fast local storage disk, like you would expect, you would get a network storage volume as disk.

**Comment by alvaroaleman** [comment]
> Instead of getting a fast local storage disk, like you would expect, you would get a network storage volume as disk.

Yes but the rootdisk size is derived from the flavor when using ephemeral storage and some users want to configure that. Any ideas on how to best cope with that? Add a big warning aside of the config option that this will result in slower disks?
