### ISSUE TITLE
Create periodic prow job to execute conformance test on all providers

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3256]
**User Story**
Create a Prow job (Periodic) which tests all cloud providers.

**Acceptance criteria**
- [] A Prow job exists which executes the conformance tests for all cloud providers
- [] Failures are being reported to the cluster-lifecycle slack channel

**Comment by alvaroaleman** [comment]
* [ ] Azure
* [x] Digitalocean
* [X] GCP
* [x] Hetzner
* [ ] Openstack
* [X] Packet
* [x] vSphere

**Comment by alvaroaleman** [comment]
Azure and Openstack nodes are unable to communicate with the API. Swapping out the Weave CNI for Flannel solves that. I created https://github.com/kubermatic/kubermatic/issues/3543 for finding an alternate CNI.

/lifecycle blocked
