### ISSUE TITLE
Allow other OS for Bring-Your-Own template generation

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#328]
We now need templates for CoreOS and Ubuntu. We should abstract away and just use template files for different OS's

**Comment by susman** [comment]
CentOS should be also included.
Most enterprise clients will prefer it.

**Comment by mrIncompetent** [comment]
Maybe we should rethink bring-your-own. The customer should only install a public ssh-key & kubermatic should provision the node

**Comment by mrIncompetent** [comment]
Closed due to https://github.com/kubermatic/config/issues/219
