### ISSUE TITLE
Make OIDC provider URL configurable

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#3314]
In case when dex is not enough (because of lack of some functionality) people would use keycloak probably. So we need a way to point dashboard to alternative (not dex) OIDC provider.

**Comment by maciaszczykm** [comment]
Issue moved to [kubermatic/dashboard-v2 #1201](https://github.com/kubermatic/dashboard-v2/issues/1201) via [**ZenHub**](https://www.zenhub.com/)
