### ISSUE TITLE
Support dedicated LB per user cluster

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3344]
## User Story
To avoid having the NodePort proxy LB as [SPOF](https://de.wikipedia.org/wiki/Single_Point_of_Failure) we should implement a second mode where each user clusters gets its own LB.

The "mode" should be made configurable via a flag of the kubermatic controller-manager:
```
-apiserver-expose-strategy=[LB|NodePort]
```

#### `-apiserver-expose-strategy=LB`
For each user cluster the `external-apiserver` service will be of type `LoadBalancer`.
To avoid complexity we won't utilize DNS. Thus `cluster.Address.ExternalName` must contain `service.Spec.LoadBalancerIP` of the `external-apiserver` service.

Note: `service.Spec.LoadBalancerIP` is typically an IP address, but on AWS we get a DNS record.

#### `-apiserver-expose-strategy=NodePort`
For each user cluster the `external-apiserver` service will be of type `NodePort`.
This is what we currently do.

**This change must be backwards compatible**
To be able to not break existing clusters, we should make the cluster-controller smart enough not try to change `service.ServiceType` to something different.

**Acceptance criteria**
- [ ] Support LB & NodePort as exposing mode for user clusters
- [ ] Docs have been updated to explain both modes & how to configure them
- [ ] The kubermatic helm chart has a values.yaml flag to configure `-apiserver-expose-strategy` on the kubermatic controller-manager

Unit tests exist which cover: 
- [ ] backwards compatibility
- [ ] Service creation for both modes
- [ ] Address handling for both modes

**Comment by alvaroaleman** [comment]
@mrIncompetent Update this

**Comment by mrIncompetent** [comment]
### Update
What we missed in the previous design was that we have 2 services which we export to the outside:
- APIServer
- OpenVPN server

To avoid having 2 LB's per cluster, we'll use envoy as TCP proxy.
Since we now have a very similar setup like with the NodePort proxy, we'll try to reuse it.

To allow reuse of the NodePort proxy we must change it, so it can work on a single namespace.


The overall design will be:
```
			 -> APIserver
			/
LB	->	Envoy(NodePortProxy)	
			\
			 -> OpenVPN
```

**Comment by irozzo-1A** [comment]
> To avoid having the NodePort proxy LB as SPOF we should implement a second mode where each user clusters gets its own LB.

I do not fully agree with the initial statement, I think that main cloud providers (AWS, GCE,...) handle redundancy themselves and that SLAs they provide should be enough.
