### ISSUE TITLE
Add GCP support to dashboard

### ISSUE THREAD

**Issue by nikhita** [kubermatic/kubermatic#3351]
Issue for adding GCP support: https://github.com/kubermatic/kubermatic/issues/3120
PR for adding GCP support to Kubermatic: https://github.com/kubermatic/kubermatic/pull/3350

**Acceptance criteria**

It is possible to create clusters on GCP via the UI.

**Comment by p0lyn0mial** [comment]
Issue moved to [kubermatic/dashboard-v2 #1207](https://github.com/kubermatic/dashboard-v2/issues/1207) via [**ZenHub**](https://www.zenhub.com/)
