### ISSUE TITLE
Add Packet support to Kubermatic

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#3352]
**User Story**
As a user, I want to use Kubermatic to create Kubernetes Clusters on Packet

**Acceptance criteria**

It is possible to use Packet as a provider to create Kubermatic-managed clusters on

**Comment by nikhita** [comment]
UI issue  - https://github.com/kubermatic/dashboard-v2/issues/1219

**Comment by alvaroaleman** [comment]
Reopening because I think this is not fixed until kubermatic/dashboard-v2#1219 is resolved
