### ISSUE TITLE
Integrate cluster-autoscaler

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3370]
**User Story**

As a user I want my clusters to autoscale to save cost

**Acceptance criteria**

* A fork of the RedHat cluster-api provider for CA is in the kubermatic org: https://github.com/kubernetes/autoscaler/pull/1866
* Prow has a postsubmit to build on commits of the `frobware:clusterapi-cloudprovider` branch
* The cluster-controller and openshift controller deploy the CA
* The usercluster controller deploys appropriate (Cluster-)RoleBindings for the CA to work
* The machine-controller puts an `cluster.k8s.io/machine: machine-ns/machine-name` annotation onto nodes

**Comment by alvaroaleman** [comment]
@alvaroaleman please add your finding from testing it out

**Comment by alvaroaleman** [comment]
@mrIncompetent and me discussed this, specifically:

* Cluster-Autoscaler poses the unique challenge that it watches a huge lot of things (Deployments, Statefulsets, Daemonsets, Replicasets, Pods, PodDisruptionBudget)
* This implies that the resource requirement for both cluster-autoscaler and kube-apiserver changes wildly depending on total amount of objects and churn rate of objects (first increases memory consumption, second increases CPU consumption)
* This in turn means we need to either allocate enough resorces for the worst-case scenario or have some mechanism to automatically scale cluster-autocaler and kube-apiserver vertically
* Proposed idea to solve this is to make the cluster-autoscaler opt-in via a button in the UI that explicitly marks the feature as Beta
* When the user chooses to opt-in to cluster-autoscaler for their cluster, the vertical pod autoscaler gets activated automatically
* The cluster-autoscaler feature will not be available when the VPA is disabled kubermatic-wide
* We need to extend the cluster object to contain some kind of feature flags to indicate weather features like VPA and the cluster-autoscaler are enabled

**Comment by mrIncompetent** [comment]
Additionally:
The Kubermatic operator* should be able to enable the VPA support but disable the cluster autoscaler.
In case the operator* decides the cluster autoscaler is not stable enough

*The humans operating the kubermatic installations
