### ISSUE TITLE
Upgrade test: Verify reconciliation was done prior to running conformance tests

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3417]
**User Story**

Currently, our upgrade tests:

1. Deploy old Kubermatic
1. Create a Cluster
1. Run conformance tests
1. Upgrade conformance tests
1. Deploy new Kubermatic

This has the issue that we don't wait for the new Kubermatic to actually reconcile the cluster. If it fails, we will never notice and basically just run the tests again against the same, unchanged cluster.

**Acceptance criteria**

* Upgrade tests wait for all Kubermatic controller to successfully reconcile the cluster before running the conformance tests the second time
* To achieve this, all our controllers must emit a metric, telling the version with which they last successfully reconciled: `lastSuccessfullSyncTimestamp{controller_name: string, reqAfter: bool, kubermatic_version: string, cluster_name: string}`
* This includes all controllers in the Kubermatic controller manager and in the usercluster controller manager
* After upgrading Kubermatic, the conformance tester waits for this metric to appear for all controllers
* After this metric appeared, the conformance tester waits for all Deployments and Statefulsets to have `replicas == .status.updatedReplicas` and for all Pods to be `Ready` to ensure all Pods were successfully updated

**Comment by mrIncompetent** [comment]
@alvaroaleman @mrIncompetent Please refine
