### ISSUE TITLE
AWS: Multi AZ support for nodes in controllers

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3456]
**User Story**

As a user of Kubermatic I want to spread my nodes accross AZs in an AWS region.

**Further context:**

* https://github.com/kubermatic/kubermatic/issues/678
* https://github.com/kubermatic/kubermatic/issues/3139

**Acceptance criteria**

* The controllers support this use case
* The code still builds
* PVs and LBs still work
* Change the `zone_character string` in the  AWS datacenter spec to `zone_characters []string` (Potentially leave the old setting and just add it to `zone_characters` for compatibility reasons)
* The AWS cloudspec currently contains a `SubnetID` string. It is only used during machine creation. We must change this to a `map[string]string`, containing an AZ/SubnetID mapping
* We pass the Zone into the controller-manager and APIServer both via an env var `AvailabilityZone` and as part of the `cloud-config`. Remove this
* We set the `SubnetID` in the cloud-config, remove this
* Add a validation for `datacenters.yaml`, that in an AWS node dc `len(zone_characters) >= 1`
* Change all current references from the API to the datacenter specs `zone_character` to `zone_characters[0]`, until the API and UI fully support multiple zones
* Change all current references from the API to the `cluster.Spec.Cloud.AWS.SubnetID` to `cluster.Spec.Cloud.AWS.SubnetIDs[dc.zone_characters[0]]`, until the API fully supports multiple zones

**Comment by mrIncompetent** [comment]
> We pass the Zone into the controller-manager and APIServer both via an env var AvailabilityZone and as part of the cloud-config. Remove this

Looking at the aws code its required: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1210

We can create a zone based on the region + the first entry in `zone_characters`

> We set the SubnetID in the cloud-config, remove this

Required as well, unless we switch to the RoleARN functionality.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1272

We could take the subnet matching the first zone though.

**Comment by alvaroaleman** [comment]
> Looking at the aws code its required: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1210

Oh good point, althought that is relevant for the controller-manager only, for the nodes themselves it gets discovered via metadata service: https://github.com/kubernetes/kubernetes/blob/8fecbd8eca4dae11b5936bc85aac31074c94fd51/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L1203

**Comment by kdomanski** [comment]
Is there any reason to enforce available zones through `zone_characters` in `datacenter.yaml`? The list of zones in a region can be retrieved via AWS API.

**Comment by mrIncompetent** [comment]
> Is there any reason to enforce available zones through zone_characters in datacenter.yaml? The list of zones in a region can be retrieved via AWS API.

I cannot remember the reason
