### ISSUE TITLE
discussion: kubeone dogfooding

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#3470]
We, as company that develop kubeone, should use it.

Plan is to initially move (actually redeploy) `dev` environment. Cloud provider of choice is GCE (for financial reasons).

Rough ideas (all questionable, but will bring us closer to clients) for new cluster:
* OIDC authentication
* Replace dex with keycloak
* secrets in Vault [using k8s auth](https://www.vaultproject.io/docs/auth/kubernetes.html)
* "Private" VPC
* Bastion setup https://github.com/kubermatic/kubeone/issues/337

cc @mrIncompetent

**Comment by xrstf** [comment]
Discussion happened, goal was defined and put in #3471.
