### ISSUE TITLE
migrate dev to kubeone

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#3471]
We currently use GKE for our [dev cluster](https://dev.kubermatic.io).
Since we've developed [KubeOne](https://github.com/kubermatic/kubeone) and sell it to customers we should use it for our dev cluster as well (Called [dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)).

What needs to be done:
- [x] Write a terraform script which creates the infra
  -  1 master (~2CPU/8GB) / 6 worker (~4CPU/16GB)
- [x] Keep the terraform code & kubeone config in the [infra repository](http://github.com/kubermatic/infra)
- [ ] Install Kubermatic into the new Kubernetes cluster based on the values.yaml from dev.kubermatic.io

xref #3470

**Comment by eqrx** [comment]
On it :)

**Comment by eqrx** [comment]
Hey all. I would like to start by creating a new cluster in the kubermatic-dev project but that would exceed the quota for SSDs (```E0619 14:15:46.116583       1 machine.go:386] Failed to reconcile machine "dev-pool1-b76789866-ls8vt": An error of type = InvalidConfiguration, with message = Failed to insert instance: GCE operation failed: {QUOTA_EXCEEDED  Quota 'SSD_TOTAL_GB' exceeded.  Limit: 2048.0 in region europe-west3. [] []} occurred```). What is the best approach here? Increate the quota temporarily?

**Comment by kron4eg** [comment]
I believe this issue was fixed by purging ES data

**Comment by youssefazrak** [comment]
@eqrx any update on this?

**Comment by kdomanski** [comment]
@eqrx ping

**Comment by eqrx** [comment]
Sorry for the delay. Yeah I started with that but had multiple problems.... so I abandoned it. It boils down to: After that was fixed I could not recreate the kubermatic setup. So kubeone cluster yes, kubermatic in it no.
