### ISSUE TITLE
Filter instance types based on resource quota

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#3485]
**User Story** In the situations where a lot of the addons are installed to the user clusters we should make sure that instance types that we list can handle the whole cluster, and filter out those which are too small. This would prevent the users from running into the issues with too small instances, that can't handle all the apps that we deploy to the clusters. It should be implemented after https://github.com/kubermatic/dashboard-v2/issues/1245 will be done.

**Acceptance criteria**
- [ ] filtering of the instances based on the resource quota is introduced to the API (how we are defining/calculating the resource quota?)
- [ ] there are structures for instance type(s) of each provider, containing information about instance CPU, memory and storage
- [ ] filtering is based on CPU, memory, and the storage - all parameters have to be high enough to make the cluster usable
- [ ] instance types that are too small should no be returned from the API (should we return them and disable them? or add some more information to the UI for the user to know that some of the instance types were too small?)
- [ ] the tests are added

An other idea would be displaying information about the instance types in the UI in a generic way. Using not only instance type names but also CPU, memory and storage for every provider.

cc @kubermatic/ui-team @mrIncompetent @scheeles

**Comment by mrIncompetent** [comment]
I think this mixes 2 different issues:
- Filter out instances which are simply too small in general (based on the amount of configured addons)
- Show error messages if the requested instances will hit the quota limit

Filtering out instances which are too small has been implemented by https://github.com/kubermatic/kubermatic/pull/3487

The errors based on the quota's has been implemented in the Syseleven fork.

IMO: We should not filter out instances if they would hit the quota limit - That seems confusing.

**Comment by maciaszczykm** [comment]
> IMO: We should not filter out instances if they would hit the quota limit - That seems confusing.

I agree, that this may be confusing if we filter out some of the instance types and don't show any information to the end user.

> Filtering out instances which are too small has been implemented by #3487

What about providers other than OpenStack? We would like to move AWS for example to the API, so there should be some generic solution or we want to keep it per-provider?

**Comment by mrIncompetent** [comment]
> What about providers other than OpenStack? We would like to move AWS for example to the API, so there should be some generic solution or we want to keep it per-provider?

If we can figure out a generic approach: Great.
But the history has shown that it can be really hard to implement something generic - which is why i would be fine with a per-provider implementation as well.

**Comment by floreks** [comment]
@scheeles what do you think about this feature?
