### ISSUE TITLE
Document default resource usage on a customer cluster worker node

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3493]
**User Story**
We must document how much resources a minimal node must have to be able to host all default addons.

Since we set resource requests & limits for all addons, documenting it becomes mandatory.
Otherwise customers add nodes to their clusters and the only thing which runs on those nodes are the addons.

**Acceptance criteria**
- [ ] Minimum resource requirements are documented in the docs repo

**Comment by kdomanski** [comment]
according to @alvaroaleman : we should write something that extracts this from the code, otherwise the documentation will become outdated soon
