### ISSUE TITLE
Migration to DynamicKubeletConfig

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3494]
**User Story**
We should migrate to the DynamicKubeletConfiguration.

It allows dynamic reconfiguration of kubelets without having to rotate all nodes.

Open questions:
- Should we allow users to change certain settings ?
  - A customer mentioned that they would like to change the maximum number of pods per node
  - A customer mentioned that they would like to change the reservations (system-reserver & kubelet-reserved)

**Acceptance criteria**
- [ ] All nodes use the DynamicKubeletConfiguration

**Comment by kdomanski** [comment]
Dynamic config is still experimental. For now, we're using the static file, and dynamic config is currently implemented as optional.
