### ISSUE TITLE
Switch kube-proxy to IPVS

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3495]
**User Story**
IPVS is the more performant and easier to manage solution which is why i propose to use it for clusters.
The support in Kubernetes is considered stable since [v1.11](https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/)

**Acceptance criteria**
- [ ] All user clusters use ipvs instead of iptables
- [ ] a test has been performed to validate that switching does not cause a downtime

**Comment by mrIncompetent** [comment]
Some talks at KubeCon mentioned the kube-proxy IPVS implementation was not as stable as the IPTables one, we might wan't to postpone working on this issue.

**Comment by nikhita** [comment]
Closing in favour of https://github.com/kubermatic/kubermatic/issues/3935
