### ISSUE TITLE
Take Azure credentials from the environment

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3555]
**User Story**
As an operator of Kubermatic i create clusters for users. 
Those users should not have direct access to the credentials.

Current state: The Azure credentials are embedded inside the Machine object.

To fix this there are 2 things required:
- Fix the machine-controller to load the secrets from the environment
  - Use `GetConfigVarStringValueOrEnv` for: `SubscriptionID`, `TenantID`, `ClientID`, `ClientSecret`
    - The place to fix it: https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/azure/provider.go#L174
- Fix kubermatic to set the required environment variables on the machine-controller deployment
  - The place to fix this: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/machinecontroller/deployment.go#L160  
- Do not set the credentials inside the machine object when creating it from the API
  - The place to fix this: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/machine/common.go#L91

**Acceptance criteria**
- [ ] Kubermatic clusters can create machines on Azure
- [ ] Machine objects for azure clusters do not contain credentials

**Comment by mrIncompetent** [comment]
cc @kron4eg

**Comment by kron4eg** [comment]
MC PR is here: https://github.com/kubermatic/machine-controller/pull/551
