### ISSUE TITLE
Allow ICMP in all security group rules we create

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3562]
**User Story**

In order to be able to cope with an MTU < 1500 anywhere on the route between Kubelet and user cluster APIServer (Internet, Cloudprovider SDN, CNI) we need path MTU discovery. This uses ICMP underneath, which implies that we need to allow that in the security groups we create

**Acceptance criteria**

* All security groups we create at all cloudproviders allow ICMP inbound and outbound
* There is a migration in place, that adds an allow rule for ICMP inbound/outbound to all existing security groups that do not allow ICMP

**Comment by kdomanski** [comment]
Let the migration run in series over the clusters in order to avoid perpetual rate limit issues due to many GETs.

**Comment by kdomanski** [comment]
On GCP there is a default firewall rule that allows ICMP regardless of source and destination. However, this rule can be deleted. Does it make sense to add additional ICMP allow rule for each cluster just to be sure? cc @nikhita @mrIncompetent

**Comment by alvaroaleman** [comment]
Yeah lets add it, our customers don't necesarily leave cloud defaults
