### ISSUE TITLE
[AWS] Look for existing InstanceProfile

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3567]
**User Story**
As a user of Kubermatic i don't want to create an account which has the permissions to create new roles. 
Currently, Kubermatic creates a new Role + InstanceProfile which then gets used for all worker nodes.

Instead of creating a new InstanceProfile, Kubermatic should check for an existing InstanceProfile to be used.

When looking for an InstanceProfile, take the first one which has the tag `kubernetes.io/use-for-workers: true`.
If one is found, use this InstanceProfile and do not create one.

**Acceptance criteria**
- [ ] Kubermatic looks for an existing InstanceProfile & uses it if one is found
- [ ] The required tag has been documented in docs.kubermatic.io
- [ ] If an existing InstanceProfile gets used, it must not be deleted when deleting the cluster

**Comment by toschneck** [comment]
@mrIncompetent / @thz isn't this implemented already?

**Comment by thz** [comment]
> @mrIncompetent / @thz isn't this implemented already?

I do not think so. We implemented a "mitigation" for the missing feature as a shell controller patching the cluster crd and adding the instanceProfile name. This is done after Kubermatic tried and failed to create the role+profile (or while it is trying).

With respect to DoDs here: Neither is Kubermatic checking for an existing profile, nor is there deletion prevention implemented. No documentation either.

I am not aware of status of this feature in release planning.

**Comment by mrIncompetent** [comment]
It's not.
I've mentioned this 2 weeks ago before the sprint planning to @kdomanski and he mentioned that he wan'ts to get it contact with @toschneck because he thinks its too customer specific.

**Comment by thz** [comment]
In the sense of "least privilege" it should be in every customer's interest to NOT grant permissions to create new roles (which is complete privilege escalation). Without that permission it is essential for the product to support the use of pre-existing instance profiles.

**Comment by toschneck** [comment]
I agree with  @thz. This not only a issue on one customer we know. So this will needed in general. I also don't want to rely on the shell controller in production.
@mrIncompetent @kdomanski let me know what you think about

**Comment by mrIncompetent** [comment]
@toschneck @kdomanski Please define the priority.

**Comment by toschneck** [comment]
From my point of view we will need this in the next release, if we don't want to go with this in production. But final decision have to be done by @kdomanski

**Comment by mrIncompetent** [comment]
Ping @kdomanski

**Comment by toschneck** [comment]
@mrIncompetent is already done right?  @ivomarino is currently looking for the docs of the correct permissions as far as I know.
cc @thz

**Comment by ivomarino** [comment]
We are going to test the correct seed code on an AWS test cluster actually which we are preparing for this purpose, as info

**Comment by mrIncompetent** [comment]
> @mrIncompetent is already done right ?

No. We have a workaround using a ~DaemonSet~ bash controller which will set the InstanceProfile on the cluster object.
@thz wrote that & it's available in the customer-projects repo (I'm not posting the link as it contains the customer name)

**Comment by toschneck** [comment]
@ivomarino @mrIncompetent we can already enter the value of an existing instance profile trough the UI. What is currently enough, so the need of this [bash profile controller](https://github.com/kubermatic/customer-projects/tree/master/projects/atech/config/kubermatic-seed-controller/profile-controller) is no longer needed.
