### ISSUE TITLE
Synchronize cluster SSH keys to machines during runtime

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#3573]
**User Story**
As a user i would like to add&remove SSH keys to a cluster & directly access all nodes via the newly added SSH key.

Right now i'm required to rotate all nodes to archive which imposes a risk to my workload.

A potential fix would an agent which runs on each node & updates the `authorized_keys` file on the host.

Open questions:
- [ ] How to handle keys which got manually added ?

**Acceptance criteria**
- [ ] We have a solution which automatically synchronizes the authorized keys

**Comment by alvaroaleman** [comment]
Another open question: How do we know the user? Alternatively, we could synchronize for all potential users if they exist (root, core, centos, ubuntu)

**Comment by mrIncompetent** [comment]
Synchronizing to all (root, core, centos, ubuntu) if they exist sounds good :+1:
