### ISSUE TITLE
Verify metrics scraping on Kubernetes v1.15

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#3588]
**User Story**
We need to verify that on new Kubernetes v1.15 the metrics still work as expected. Apparently we've had issues before when moving on to a new release.

We must make sure that on v1.15:
- scraping succeeds
- all metrics we use for alerting are there as expected

**Comment by xrstf** [comment]
Is this regarding user clusters, seeds or both?

**Comment by kdomanski** [comment]
Both.

**Comment by kdomanski** [comment]
Note that v1.15 is still in beta and it would probably make sense to wait for the .0 release.

**Comment by xrstf** [comment]
After deploying Prometheus, node-exporter and kube-state-metrics into a user cluster running 1.15rc1, all alerts and dashboards kept functioning. I don't expect metrics related changes after rc1.
