### ISSUE TITLE
Openstack: duplicate sec groups created if setting rules failes

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#3589]
**User Story**
In the OpenStack provider, a security group is created and then its rules are inserted one by one as a separate operation. As a result, if one of these rule insertions fails, the group will not be deleted and a new security group with the same name will be created during the next reconciliation attempt.

![image](https://user-images.githubusercontent.com/993296/59098132-c397ae80-891f-11e9-9261-c106b9af5ac1.png)

The additional security groups are subsequently not cleaned up on cluster deletion. It is not clear whether the rules insertion works correctly with duplicate group names.

**Acceptance criteria**
 - [ ] failure to create a security group rule does not result in creating a duplicate group

**Comment by alvaroaleman** [comment]
This got fixed in #3848
