### ISSUE TITLE
Create Kubermatic Operator

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#3626]
This is a proposal to create a Kubermatic Operator to deploying and managing the various parts that make up a Kubermatic setup.

### Motivation

* Managing complexer migrations via Helm is complicated and brittle.
* [add more pls]

### Proposal

A new operator takes care of the Kubermatic stacks. What was previously the `values.yaml` is replaced with one or possibly multiple CRDs (i.e. one for kubermatic, monitoring, logging).

I would start by implementing the operator logic for a simple chart like the s3-exporter and once we are sure this is the way to go, would then go on with Kubermatic itself and then the rest.

#### How to retain configuration flexibility?

* The monitoring stack especially allows to freely mix and match how and where Grafana dashboards, Prometheus rules etc. are located.

### Acceptance criteria

* Helm isn't used anymore.
* All configuration is done via a new CRD.
* It should be much, much easier to configure the Kubermatic stack through the new CRD we introduce.
* A deployment of Kubermatic means to deploy only that operator and fill out the CR, the rest happens automagically.

**Comment by alvaroaleman** [comment]
* Helm isn't used anymore
* All configuration is done via a new CRD
* A deployment of Kubermatic means to deploy only that operator and fill out the CR, the rest happens automagically

**Comment by xrstf** [comment]
* It should be much, much easier to configure the Kubermatic stack through the new CRD we introduce.
* Think about maybe splitting the configuration into simple/extended or mandatory/optional or something along the lines.

**Comment by alvaroaleman** [comment]
On a very high level I would consider one of the main goals with this: "Allow someone with a Kubernetes cluster and without knowledge about kubermatic architecture to use this operator and less than a page of docs to set up a functioning Kubermatic installation"

**Comment by xrstf** [comment]
Most of the grunt work is done, the remaining stuff is tracked in https://github.com/kubermatic/kubermatic/issues/4723.
