### ISSUE TITLE
Allow to configure other certificate issuers

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#3631]
**User Story**
For clusters where there is no Internet access or Let's Encrypt is for whatever reason not possible, it would be nice to allow users to override the issuer used for the certs. Currently our certs chart hardcodes letsencrypt-prod as the issuer.

**Acceptance criteria**
* [ ] I can configure the default certificates to be issued by something other than Let's Encrypt.
* [ ] I can create self-signed default certificates.

**Comment by xrstf** [comment]
@kdomanski Given that Keycloak and Dex require valid certificates and this would require the customer to manage their own CA and mount certs into all these pods, is this really something we want to support out of the box? It's easy enough to manually define an issuer later and use that one.

**Comment by kdomanski** [comment]
Is there even a solution alternative to Let's Encrypt that we could possibly support out of the box? If there isn't, we can't claim to support it.

**Comment by kdomanski** [comment]
Alright, I see that a CA cert/key pair is an available issuer in cert-manager. At least once we had a customer who asked about the possibility of using their own CA.

Perhaps we can split this issue into two:
 - [ ] dealing with the hardcoding and making it easy to set any issuer
 - [ ] testing and documenting a setup, where we give the cert-manager an intermediate CA cert/key to use, figuring out how to put the CA cert everywhere

**Comment by xrstf** [comment]
This has been implemented. The issuer can be freely chosen and if needed, a custom CA can be injected into the containers to make the API->Dex communication work.
