### ISSUE TITLE
Machine-Controller: Add openshift 4 support

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3635]

**Comment by alvaroaleman** [comment]
AC:

* Machine-Controller can spawn openshift 4 machines
* They successfully join an Openshift 4 cluster and become ready

**Comment by mrIncompetent** [comment]
We initially planned to use RHEL CoreOS / Fedora CoreOS.
RHEL CoreOS though updates through a private channel - Which requires a valid subscription.
Fedora CoreOS is in its early beta stage with insufficient availability.

Thus we decided to stick to CentOS 7.
We'll later think about integrating Fedora CoreOS.
