### ISSUE TITLE
Setup a Mumbai seed DC for dev.kubermatic.io

### ISSUE THREAD

**Issue by nikhita** [kubermatic/kubermatic#3685]
Due to the high latency between Europe and Asia, I have trouble connecting to dev sometimes and need to retry multiple times while starting a controller locally. It would be helpful to have a mumbai node setup for dev.kubermatic.io which would prevent latency issues.

/assign

cc @alvaroaleman

**Comment by alvaroaleman** [comment]
What needs to be done is:

* Create a GKE cluster in a Datacenter thats close to you
* Add a seed datacenter to the `datancenters.yaml` for dev in the secrets repo
* Extend the kubeconfig for dev in the secrets repo to contain a new context with the same name as the new seed datacenter. The name must be dns compliant
* Duplicate all node datacenters in the datacenters.yaml you want to use, with the difference that they use the new seed datacenter
* Set up CI to also deploy the non-master kubermatic components into that new seed datacenter. We already do the same thing in cloud-asia and cloud-us so you could use those scripts as inspiration

**Comment by nikhita** [comment]
- Created GKE cluster in `asia-south1-c` (mumbai) - https://console.cloud.google.com/kubernetes/clusters/details/asia-south1-c/kubermatic-dev-asia?project=kubermatic-dev

- Updated kubeconfig, datacenters.yaml and values.yaml in https://github.com/kubermatic/secrets/pull/314. The postsubmit run on the secrets repo will update the values in Vault.

- https://github.com/kubermatic/kubermatic/pull/3688 adds a script to deploy to `dev-asia`.

- https://github.com/kubermatic/infra/pull/438 adds a postsubmit which runs the above script.

**Comment by nikhita** [comment]
All PRs have merged.

/close
