### ISSUE TITLE
Publish Swagger Spec and libraries 

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#3704]
**User Story**
I would like to consume our API via Service Accounts. The minimum what we should provide here is the Swagger Spec and library for Golang (Python/Javascript??)

**Acceptance criteria**

I can create an cluster via a Service Accounts and our API

**Comment by kdomanski** [comment]
Fixed in #3890

**Comment by scheeles** [comment]
Do we have the library as well?

**Comment by kdomanski** [comment]
Right, forgot about that.
