### ISSUE TITLE
Improve AWS cluster separation

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#3716]
Based on: https://github.com/kubermatic/customer-projects/issues/36

**User Story**
The current "bring-your-own" account approach is solving the separation of AWS resources. We now facing to the requirement, that access needed to be separated on cluster level:

- In the same account end user of cluster A could not access resources of cluster B
- This includes resources created by the CCM (Volumes, Loadbalancer, ...)

**Identified Problems**
- Created AWS worker nodes (kubelet) get the IAM instance profile assigned -> trough host path mounting or root container the instance profile is accessible from the inside of the cluster
- The default IAM policy Kubermatic deploys is not limited to the cluster resources  -> access to other cluster resources is possible
- More details can be found here: https://github.com/kubermatic/customer-projects/issues/36

**Potential solution**
A potential solution approach have been discovered by @kron4eg. For detail see: https://github.com/kubermatic/customer-projects/issues/36#issuecomment-507447343

**Acceptance criteria**
- [ ] A end user of a cluster can only access the AWS resource they belong
- [ ] A end user cannot read out AWS credentials or IAM policies at all. AWS credentials are only visible in the Kubermatic operator scope

**Comment by kron4eg** [comment]
First step is to:
* create custom policy (currently we use existing and very liberal policy provided by AWS).
* allow only ec2:DescribeRegion and ec2:DescribeInstance (preferably lock it down to given tag)

Next step would be to lockdown somehow control plane permissions.

**Comment by mrIncompetent** [comment]
I had a quick chat with @thz on this topic.

A sane AWS access management could look the following (For the use case of a global AWS account):

Kubermatic creates:
- 2 AWS roles for each cluster (Both roles are limited to the tagged resources)
  - Kubelet/Node
  - Control plane
- 1 set of AWS API credentials
  - Will be used on the control plane components(controller-manager / machine-controller). We're using dedicated/very limited credentials which only can be used to do the assumeRole action.

We deliberately run the control-plane with a custom role so it runs with the minimal set of permissions & we ensure that no one can trick the control-plane into deleting another teams volume.

**Comment by toschneck** [comment]
@mrIncompetent sounds good to me. Hopefully we can fix this soon.

**Comment by mrIncompetent** [comment]
@kdomanski @toschneck Please define the priority.

**Comment by toschneck** [comment]
From my point of view, it's high. We will need this for the go-live and we should also test it upfront that we don't have any side effects. But I'm not aware of the whole product planing, so final decision is on @kdomanski

**Comment by kdomanski** [comment]
according to @alvaroaleman "we should simply say that clusters created before version X cannot do this and you need a new cluster"

**Comment by toschneck** [comment]
@kdomanski sounds ok for me. So this means that the current cluster just stay as before, right?
Could we potential apply it manually for old clusters? This is currently not asked, but want to know if it would be theoretically possible

**Comment by alvaroaleman** [comment]
Only when rolling over all nodes and that is not something I want to do automatically.

**Comment by toschneck** [comment]
I agree! But if someone need's it,  we could potential trigger the rollout of the nodes by hand?

**Comment by alvaroaleman** [comment]
> I agree! But if someone need's it, we could potential trigger the rollout of the nodes by hand?

You will probably be able to manually edit the cluster object to make that happen, but that is not something we will publish

**Comment by toschneck** [comment]
> You will probably be able to manually edit the cluster object to make that happen, but that is not something we will publish

SGTM -  no extra work on this, just wanted to understand the possibilities just in case

**Comment by toschneck** [comment]
@mrIncompetent is the documented AWS IAM permissions of the doc still correct? https://docs.kubermatic.io/requirements/cloud_provider/_aws/

I think we should also document here how the mechanism works.

**Comment by toschneck** [comment]
@ivomarino FYI - please link your PR's here
