### ISSUE TITLE
Clusters get stuck in deletion

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#3758]
**User Story**
There are a couple of user clusters on cloud-eu that are not getting properly deleted. In all of them, the pods from the etcd StatefulSet are still running. Affected clusters:

* 7qmthd8vkz
* 8ssp7q8465
* 98kq8xs7rr
* v6snpfvj82

All of these clusters are hosted at **Azure** and have these finalizers left:

* kubermatic.io/cleanup-in-cluster-lb
* kubermatic.io/cleanup-in-cluster-pv

**Acceptance criteria**
* Deleted cluster are being deleted.

**Comment by nikhita** [comment]
This has been solved now.
