### ISSUE TITLE
vSphere: Support nested folder handling for VMs and networking

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#3764]
Customer requested: https://github.com/kubermatic/customer-projects/issues/38

**User Story**
Every component of our stack need to handle nested paths for:
* Network (nested network addressing/reconciling)
* VMs (nested path/folder handling)

**Components**
#### Machine Controller 
Findings provided by 
@thetechnick:
> The Machine Controller currently struggles to work with nested vSphere objects, because the folder/path lookup logic is non-existent or to simple.
(the vsphere terraform module needs 500+ loc for just path/folder handling)
Having the MC work with the same input parameters as the terraform module would make the integration with KubeOne easier and lowers the documentation overhead.
At time of writing the machine controller cannot work with nested networks at all. Workaround is to specify the network directly in the vSphere template.
(culprit is probably this: https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/vsphere/helper.go#L247-L262)

#### Kubermatic Dashboard
To prevent wrong user input, the nicest solution would be that the user enters his credentials and can select the folders (also nested folders) for the VMs and the network at the cluster creation dialog. If this is makes to much effort in the first place, it would be also acceptable to enter a nested folder path as string. If so, we should ensure that the UI show's an hint how to write the path correctly.

**Acceptance criteria**
- [ ] Machine Controller: implement folder/path lookup for Networks
- [ ] Machine Controller: implement folder/path lookup for VMs
- [ ] Kubermatic: update machine controller version
- [ ] Kubermatic Dashboard: usage of nested folders for VMs an Networks are possible
- [ ] A successful E2E has been done (at least manual)
- [ ] Documentation haven been updated if needed

**Comment by toschneck** [comment]
@kdomanski @scheeles screenshot of the vsphere setup
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/d398f90a-3d85-4986-a3c7-ed49d2be6927)

govc output ....
```
lee@EX013007:~/git/inf-kubermatic_poc$ govc ls -l -u 'acsandboxvc01.corp.edrlandmark.net' -i '/Abbey Court Sandbox/network/'
DistributedVirtualPortgroup:dvportgroup-67 /Abbey Court Sandbox/network/VLAN-406
DistributedVirtualPortgroup:dvportgroup-46 /Abbey Court Sandbox/network/iSCSI-1
DistributedVirtualPortgroup:dvportgroup-65 /Abbey Court Sandbox/network/vDS-DVUplinks-64
DistributedVirtualPortgroup:dvportgroup-120 /Abbey Court Sandbox/network/VLAN-407
DistributedVirtualPortgroup:dvportgroup-45 /Abbey Court Sandbox/network/iSCSI-DVUplinks-44
DistributedVirtualPortgroup:dvportgroup-47 /Abbey Court Sandbox/network/iSCSI-2
DistributedVirtualPortgroup:dvportgroup-66 /Abbey Court Sandbox/network/VLAN-403
VmwareDistributedVirtualSwitch:dvs-44 /Abbey Court Sandbox/network/iSCSI
VmwareDistributedVirtualSwitch:dvs-64 /Abbey Court Sandbox/network/vDS
Network:network-33 /Abbey Court Sandbox/network/VM Network
lee@EX013007:~/git/inf-kubermatic_poc$ 
```

**Comment by kdomanski** [comment]
@toschneck I created separate issues for different aspects of this epic. I moved most of the feedback from you to each of these issues for easier navigation.

**Comment by toschneck** [comment]
@kdomanski thx :+1: . As soon we have a first draft, we could test it on the customer test environment what they setup for us :wink:
