### ISSUE TITLE
Label MachineDeployments created by Kubermatic with the project and cluster IDs

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#3822]
**User Story**
As a user, I want to be able to tell which project and cluster does a particular VM on my cloud provider account belong to.

**Acceptance criteria**
 - [ ] each instance is tagged/labeled with `kubermatic/project: PROJECT_ID`
 - [ ] each instance is tagged/labeled with `kubermatic/cluster: CLUSTER_ID`
 - [ ] it is verified, that the tagging/labeling works properly on all cloud providers on which it is supported
   - [ ] in particular, it must be tested that the characted composition and maximum length of these tags' labels and their values will fit into the maximum length allowed by the cloud providers

crossref: kubermatic/customer-projects#65

**Comment by kdomanski** [comment]
The label `kubermatic/*` is not appropriate because it collides with the whitelabeling requirements.

**Comment by toschneck** [comment]
@kdomanski the `kubermatic/*` prefix was just an suggestion. Maybe it would be an opportunity to use the API group for kubermatic related labels:
```
k api-resources | grep kubermatic
addons                                             kubermatic.k8s.io              true         Addon
clusters                           cl              kubermatic.k8s.io              false        Cluster
projects                                           kubermatic.k8s.io              false        Project
userprojectbindings                                kubermatic.k8s.io              false        UserProjectBinding
users                                              kubermatic.k8s.io              false        User
usersshkeies                                       kubermatic.k8s.io              false        UserSSHKey
```
