### ISSUE TITLE
All components are marked as failed on cluster creation

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#3880]
Related to https://github.com/kubermatic/dashboard-v2/issues/717, all components (api server, etcd, machine controller,...) are marked as failed during cluster creation.

There already is some progress with this PR https://github.com/kubermatic/kubermatic/pull/3784. 
Nevertheless as said in the PR comments, there is space to improve.

**Comment by alvaroaleman** [comment]
@thetechnick suggested that we can add a "ClusterIinitailized" condition and set it to true once the cluster was ready. This means:
* We need to add a new controller/extend an existing one that sets this condition
* It can be set to `true` once `pkg/crd/kubermatic/v1/helper.ClusterReconciliationSuccessful` returns true and the `ClusterConditionSeedResourcesUpToDate` has a value of `true`
* Once it was `true` it should never get changed again

**Comment by maciaszczykm** [comment]
cc @kubermatic/ui-team 
/label team/lifecycle
