### ISSUE TITLE
Add validatingAdmissionWebhook for Seed CRD

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3888]
**User Story**

As an operator of Kubermatic, I want validation that prevents me from accidentally bringing my Kubermatic installation in a defunct state.

**Acceptance criteria**

* There is a ValidatingAdmissionWebhook for the `Seed` CRD
* It gets deployed in both seeds and master clusters
* It gets automatically set up within the Kubermatic chart
* It validates that no Datacenter can be deleted or updated as long as there are clusters that use it
* It validates that Datacenter names are unique

**Comment by alvaroaleman** [comment]
Actually this is not done, some validation points are missing:
* I believe its currently not possible to update a DC; as the webhook doesn't exclude the seeds its checking from all seeds when checking if the Datacenter name is already in use
* It is currently possible to create one DC with multiple providers, that should not be possible
* It is currently possible to update the provider of a DC; that should not be possible

**Comment by xrstf** [comment]
I'm going to take this over so help with the Kubermatic Operator.
