### ISSUE TITLE
NodeDeployment does not set useFloatingIP field

### ISSUE THREAD

**Issue by floreks** [kubermatic/kubermatic#3895]
**User Story**
When getting already existing Node Deployment from the API, `useFloatingIP` is not set. This result in showing an inaccurate state in the UI when editing it. Possibly it is due to this part: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/machine/convert.go#L116

**Acceptance criteria**
- [ ] Floating IP usage status should be set when getting Node Deployment

**Comment by zreigz** [comment]
I've checked this. It seems to work fine. I will close it
