### ISSUE TITLE
Kubermatic e2e tests: Include cluster deletion

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/kubermatic#3987]
**User Story**

Currently we dont include cluster deletion in e2e tests, allowing bugs there to not make the tests fail

**Acceptance criteria**

* The kubermatic e2e tests delete the cluster
* They wait until the cluster is gone
* They fail if the cluster doesn't disappear within a given timeout

**Comment by kdomanski** [comment]
kubermatic/kubermatic#2739

**Comment by alvaroaleman** [comment]
Taking this over so we have something here asap.
/assign
