### ISSUE TITLE
Rolling release of Kubermatic

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#4009]
This epic tracks the pieces we need to be able to reliably deliver a rolling "stable" release for customers that require to run the bleeding edge features.

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/4009).

**Comment by xrstf** [comment]
We have the weekly releases and currently there are no further plans to extend this aspect. We can close this for now.
