### ISSUE TITLE
Use `kubectl apply` logic to create non-default ressources

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#401]
Problem: Currently we import coreos/etcd-operator so we can create etcd-cluster TPR's.
This has the problem that we are forced to use the same kube-client as the etcd-operator...

Instead we should use the `kubectl apply` logic, which generically handles any ressource you want.

**Comment by lbb** [comment]
We don't have any *hard* dependencies to the etc operator, we have modelled the etcd-operator struct to have no dependency.
