### ISSUE TITLE
Deleted user appears in the project again 

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#4018]
**User Story**
When I delete a user from a project after a short time (approx 10min) he appears again

**Acceptance criteria**

**Comment by mrIncompetent** [comment]
It appears that a restart of either the master-controller-manager or the kubermatic-controller-manager triggers that bug.

**Comment by zreigz** [comment]
I will take a look

**Comment by mrIncompetent** [comment]
@zreigz i had a look and prepared a potential fix: https://github.com/kubermatic/kubermatic/pull/4020

I'm not 100% sure if that is the best way as i'm not an expert on that codebase.
But it feels that is the smallest/less invasive fix to implement.
I could not find a reason why we generate `UserProjectBindings` based on a projects `OwnerReferences`. Maybe that has historical reasons?

**Comment by zreigz** [comment]
works for me. I will take a look closer to this
