### ISSUE TITLE
Enable Pod Security Policies

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#4053]
**User Story**
customer cross ref: https://github.com/kubermatic/customer-projects/issues/155

For many customers, it would be preferable to have Kubernetes PSP enabled. The feature is available as beta in Kubernetes 1.15 and requires an admission controller to be configured. 

We can not enable this for all cluster especially for existing cluster because this can break running workload.

As a first step it would be great if we can activate it on a per cluster basis and afterwards customers can decide if they want to enable it per default.

**Acceptance criteria**

- [ ] per cluster the admission controller can be enabled
- [ ] It can be configured if the default for the admission controller is enabled or disabled

**Comment by scheeles** [comment]
1. Enhance the cluster resource with a flag for  enable or disable the admission controller 
2. Create a config to enable/disable the PSP per Datacenter

@mrIncompetent @alvaroaleman @kdomanski Please add your thoughts

**Comment by alvaroaleman** [comment]
Acceptance criteria:

* There is an option in the CREATE and UPDATE cluster endpoint to enable/disable PSPs
* On the Cluster CRD there is a field that indicates whether PSPs are enabled
* If PSPs are enabled, the relevant admission controller on the APIServer is set
* There is an E2E tests that runs with PSPs enabled and passes
* There is an E2E tests that runs with PSPs disabled and passes
* It is possible to enforce one of enabled/disabled on a per-Datacenter level

**Comment by scheeles** [comment]
@alvaroaleman 
I would add
- There is an E2E tests that runs with PSPs disabled and passes

**Comment by bashofmann** [comment]
We are currently implementing this in our fork. If you want I can create a PR for this later today.

**Comment by alvaroaleman** [comment]
> We are currently implementing this in our fork. If you want I can create a PR for this later today.

That would be super awesome!

**Comment by bashofmann** [comment]
I submitted https://github.com/kubermatic/kubermatic/pull/4062 to make the admission plugins configurable through the api. What is still missing:

* Dashboard support to easily activate and deactivate PodSecurityPolicy (we can provide a PR for this as well)
* Adding PodSecurityPolicies and corresponding RBAC bindings for all addons
* e2e tests

**Comment by toschneck** [comment]
> Dashboard support to easily activate and deactivate PodSecurityPolicy (we can provide a PR for this as well)

@bashofmann this would be awesome as well :heart_eyes:

**Comment by alvaroaleman** [comment]
Why was this closed? The dashboard does not yet have support for PSPs, does it?

**Comment by eqrx** [comment]
Oh, I am very sorry. Closed the wrong one.

**Comment by bashofmann** [comment]
Dashboard support was merged in https://github.com/kubermatic/dashboard-v2/pull/1507. addon changes in https://github.com/kubermatic/kubermatic/pull/4174

**Comment by alvaroaleman** [comment]
Oh I didn't know about the dashboard changes. Is there a reason this can not be configured during cluster creation?
