### ISSUE TITLE
Refactor all endpoint names `*NoCredentialsEndpoint` to `*WithPresetEndpoint`

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#4061]
**User Story**
Change the name of the endpoint functions from  `*NoCredentialsEndpoint` to `*WithPresetEndpoint`

**Comment by alvaroaleman** [comment]
@zreigz okay, @kgroschoff explained it to me again and the difference seems to be that the endpoints that currently have the `NoCredential` in their name need a cluster because they derive the credentials from the cluster.

So probably `WithCluster` instead of `WithPreset` makes more sense?
