### ISSUE TITLE
spread etcd among availability zones

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#4078]
**User Story**
- Customer cross ref: https://github.com/kubermatic/customer-projects/issues/115

To ensure that etcd cluster is still fully functional after an AZ outage, the stateful etcd needs to setup with at least 3 running pods and an node anti affinity what spreads the pods across the availability zones and different nodes.

**Acceptance criteria**
- [ ] There is a new affinity defined in the `resources` package, that gives pods of the same app a preferred pod anti-affinity on the `failure-domain.beta.kubernetes.io/zone` label
- [ ] the etcd, as well as Prometheus StatefulSets get their existing affinity combined with the one mentioned above if the cluster's seed is running on one of the following cloud providers:
  - AWS
  - Azure
  - GCP

Note https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity says that the anti-affinity should not be applied if some or all nodes do not have the corresponding `topologyKey`. That is why we only apply it on those clouds that put the zone label on their nodes.

**Comment by scheeles** [comment]
Customer cross ref https://github.com/kubermatic/customer-projects/issues/157
