### ISSUE TITLE
[AWS] InstanceProfile selection via presets

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#4139]
**Background**

Kubermatic allows the specification of an existing instanceprofile to be used instead of creating role+profile itself, which would require quite drastic permissions on the provisioning AWS account.

#3567 describes the story of an automatic selection of an instanceprofile based on AWS-tags on it. This story makes #3567 obsolete or at least low-prio.

**User Story**
As a cluster-creator using Kubermatic I want the instanceprofile selection happen automatically. I want my Kubermatic administrator to pre-define the instanceprofile for me using presets.

**Acceptance criteria**

- [ ] Instanceprofiles can be specified using presets.
- [ ] a preset example is documented
- [ ] If an existing InstanceProfile gets used, it must not be deleted when the cluster is deleted

**Comment by thz** [comment]
This would probably make sense for role name+arn too. Did I mention subnet and security group?

**Comment by toschneck** [comment]
fixed already https://github.com/kubermatic/kubermatic/blob/master/api/pkg/crd/kubermatic/v1/preset.go#L78
Docu issue: https://github.com/kubermatic/docs/issues/175
