### ISSUE TITLE
[AWS] Allow to set `assignPublicIP` during NodeDeployment creation

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#4149]
**User Story**
As a user of Kubermatic i might have a cluster which is running in a private subnet.
Thus, my nodes don't need a public IP.

If a AWS Machine should not get a public IP, `assignPublicIP` must be set to `false`: https://github.com/kubermatic/machine-controller/blob/master/examples/aws-machinedeployment.yaml#L64

**Acceptance criteria**
- [ ] Its possible to set `assignPublicIP` via the API upon Node/NodeDeployment creation

**Comment by thz** [comment]
This is also required for a subnet with no auto apply set when you actually want one assigned.
