### ISSUE TITLE
[aws] instanceProfile should be per node deployment (and not per cluster)

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#4211]
The `instanceProfile` is currently an attribute of the cluster which can be set during cluster creation. The purpose is to set the AWS `instanceProfile` of worker nodes which defines roles/permissions the instances will have in AWS IAM scope. With the advent of node deployments, distinct groups of nodes can be created separately. This is already used to put distinct groups of nodes into different availability zones.
The attribute `instanceProfile` should move from cluster scope to node deployment scope, allowing the user to specify different `instanceProfile`s for different groups of workers.
There are valid uses of such where specific groups of instances need specific permissions to perform their duty (least privilege principle requires distinct profiles).

**Comment by alvaroaleman** [comment]
@thz the instance profile is already a property of the machines. Would it it be sufficient if we make it configurable on machine create/update in the UI/API and default to the one thats on the cluster?

**Comment by thz** [comment]
Actually defaulting is the only reason I see why this could be on the cluster at all. But I am not sure that is a strong enough reason for having it there.
When you said "machine" you meant "machineDeployment"? Yes it should be there.

**Comment by thz** [comment]
Even though the instance profile belongs to the MachineDeployment, having zero or one InstanceProfile created together with the cluster which can then be used for MachineDeployments that have no explicit InstanceProfile specified, makes sense. (The lifecycle of that InstanceProfile can then stay connected with the lifecycle of the cluster itself)
UI/UX wise there should be an explicit opt-out on the creation of that InstanceProfile. With that opt-out the specification of InstanceProfiles becomes mandatory. Independently of the K8c-created-profile-opt-out for every MachineDeployment  the user must be allowed to specify a pre-existing InstanceProfile.

**Comment by thz** [comment]
related ui issue: https://github.com/kubermatic/dashboard-v2/issues/1602
