### ISSUE TITLE
Add OpenAPI docs to the ssh-keys the nodes endpoint

### ISSUE THREAD

**Issue by andriisoldatenko** [kubermatic/kubermatic#424]
TODO:
- [x] `GET /api/v1/dc/{dc}/cluster/{cluster}/node`
- [x] `POST /api/v1/dc/{dc}/cluster/{cluster}/node`
- [x] `DELETE /api/v1/dc/{dc}/cluster/{cluster}/node/{node}`
- [x] `GET /api/v1/dc/{dc}/cluster/{cluster}/k8s/nodes`
- [x] `GET /api/v1/ssh-keys`
- [x] `POST /api/v1/ssh-keys`
- [x] `DELETE /api/v1/ssh-keys/{meta_name}`

**Comment by andriisoldatenko** [comment]
@guusvw @scheeles 
BTW, what's the differences between 
`GET /api/v1/dc/{dc}/cluster/{cluster}/k8s/nodes` and `GET /api/v1/dc/{dc}/cluster/{cluster}/node`?
Both endpoints uses `api/handler/routing.go:339`

**Comment by scheeles** [comment]
@mrIncompetent can you comment on this

**Comment by mrIncompetent** [comment]
Sorry for my late reply:
`GET /api/v1/dc/{dc}/cluster/{cluster}/k8s/nodes` Was a direct passthrough to the kubernetes nodes endpoint
`GET /api/v1/dc/{dc}/cluster/{cluster}/node` was a custom endpoint from kubermatic where we fetched some information from the cloud-provider specified in the cluster.

But now both are actually a passthrough to the kubernetes nodes endpoint.
We can actually delete `GET /api/v1/dc/{dc}/cluster/{cluster}/k8s/nodes`

**Comment by scheeles** [comment]
I created a separate issue for deleteing `GET /api/v1/dc/{dc}/cluster/{cluster}/k8s/nodes `https://github.com/kubermatic/kubermatic/issues/467
