### ISSUE TITLE
Automatically upgrade Node

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#4240]
Updates triggered by `automatic: true` in `updates.yaml` are limited to the control-plane.

There is customer demand for also updating all machine-deployments on these automatic updates. This should not be default but configurable.

**Comment by thz** [comment]
Proposal have a `automaticNodeUpgrade: true|false` in the `updates.yaml` next to the existing `automatic: true`.
This would also help in cases where a kubelet update is necessary without a control-plane update (kubelet CVE).

**Comment by alvaroaleman** [comment]
This got fixed in #4258
