### ISSUE TITLE
Add global settings API

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#4284]
**User Story**
The goal of this epic is to introduce user/admin settings for the kubermatic cluster.
**Acceptance criteria**
User settings:
- themes
- display configurations (items per page)
- user presets

Admin settings:
- custom links
- datacenters
- presets
- user management
- clean up settings
- initial nodes number
- default addons
- demo info
- terms of service
- API docs
- k8s/openshift option picker
- google-analytics

**Comment by maciaszczykm** [comment]
I have updated the branch with the changes from the hackathon: https://github.com/kubermatic/kubermatic/compare/master...user-global-settings

**Comment by maciaszczykm** [comment]
The initial version of user settings is already implemented. Admin settings require admin user as we cannot allow everyone editing them. First, we have to implement this role, then we can complete this task.

**Comment by maciaszczykm** [comment]
The basic version is done. We should open issues for the improvements but I think we can close the epic now.
