### ISSUE TITLE
Allow audit logging to be forced on via datacenter config and globally

### ISSUE THREAD

**Issue by eqrx** [kubermatic/kubermatic#4298]
**User Story**
A customer wants to enable policy logging on all (user) clusters, without exceptions. ~To ensure that this is the case they want to force this via an option in values.yaml.~

**Acceptance criteria**
- A new per-datacenter setting `enforceAuditLogging` will cause all clusters created within the given datacenter to have audit logging enabled.
- This will be added to both old file-based DCs, as well as DC CRDs.
- The nornal per-cluster setting is ignored.
- The value of `enforceAuditLogging` is sent over the API then datacenter(s) are fetched.

**Comment by kdomanski** [comment]
What is "policy logging"?

**Comment by eqrx** [comment]
Sorry, fixed that
