### ISSUE TITLE
Cleaning up cluster ids in the UserSSHKey object once a key is detached from a cluster

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#4358]
**Bug**
When a UserSShKey is assigned to a given cluster, the cluster id will be attached to the UserSSHKey object. However, when the cluster is deleted or cleaned up, the cluster id remains the UserSSHKey specs which makes it hard to sync those cluster with the designated key.

edit from @kdomanski 2010-10-04-14:51
After talking to everyone involved, it appears that this cleanup belongs into a controller. It might end up being racy, since cleaning up the keys and deleting the cluster are not a single atomic operation.

**Acceptance criteria**
- [ ] Once the cluster is deleted, verify the cluster id has been cleared from the UserSSHKey object that was assigned to the cluster.

**Comment by kdomanski** [comment]
Added a few words to the description after talking this through with some peeps.
cc @maciaszczykm @zreigz @alvaroaleman @moadqassem

**Comment by alvaroaleman** [comment]
What should be considered here is the fact that we only have the ssh keys in the master whereas the clusters may be in any seed. Hence this controller must talk to all seeds to figure out if a given cluster exists.
