### ISSUE TITLE
Deduplicate secretKeySelector getters

### ISSUE THREAD

**Issue by nikhita** [kubermatic/kubermatic#4367]
There are multiple implementations of the `GetGlobalSecretKeySelectorValue` method in the codebase, so they should be de-duplicated and a single implementation should be used everywhere.

/kind cleanup
/team lifecycle
/assign

**Comment by moadqassem** [comment]
@nikhita Are you still working on this ticket?

**Comment by nikhita** [comment]
Not currently, nope!
