### ISSUE TITLE
Renaming a cluster throws error

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#4384]
When renaming a cluster an error will appear (at least for digitalocean).

Steps to reproduce:
1. In Cluster Details View click the burger menu on the right in the cluster overview box. A popup will appear
2. Enter a different name and click save.

For Digitalocean you will get following error:
```
{
  "error":{
     "code":400,
     "message":"invalid cluster: invalid cloud spec: GET https://api.digitalocean.com/v2/regions: 401 Unable to authenticate you."
  }
}
```

Just tested on Digitalocean (not working) & AWS (working) so far, please also check all other providers!

**Comment by maciaszczykm** [comment]
It's fixed on dev for both AWS and DO (just tested it). https://github.com/kubermatic/kubermatic/pull/4450 and https://github.com/kubermatic/dashboard-v2/pull/1653 covered that.
