### ISSUE TITLE
Add User Management

### ISSUE THREAD

**Issue by lbb** [kubermatic/kubermatic#441]
## What is is the issue/problem to improve:

Currently we have to keep track of our provider keys (AWS,DO,...) by our own.
This is a tedious work as well as time consuming. We are also managing our ssh keys.

 ## Idea:

We should expand the user management for tokens.
Later we can also expand this idea to organisations which can encapsulate actual secrets from workers who should be able to have access to specific operations/information.
We can use the whole kubernetes-RBAC logic. This removes a lot of complexity from our side of responsibility. The whole user management and right management can be done in Kubernets as this will be a step further to kubermatic being a kube-app.

**Comment by lbb** [comment]
PTAL  @scheeles @chaosaffe @j3ank @mrIncompetent

**Comment by mrIncompetent** [comment]
Before thinking about this we need a technical design for user management in general

**Comment by lbb** [comment]
related #622

**Comment by lbb** [comment]
# Terminology
* `group`: _(*Kubernetes*)_ object that can be bound to a set of rules. (currently not in use)
* `rule`: _(*Kubernetes*)_ a manifest to specify actions a ServiceAcoount/User/Group is allowed to perform.
* `user`: a person that interacts with the system. A user can have different `groups`.
* `project`:  An abstraction to group different users and resources.
* `role`: Controls a set of actions the user can perform.
* `resource`: A _thing_ that will be owned by a `user` or a `project`. i.e A customer cluster

# Log from our discussion, user flow
* We use dex/(oauth) as AuthN source.
  + If the use is removed from the auth provider he shouldn't be able to login into our product.
  + We wan't to get AuthZ information from the auth provider (In a later stage) i.e Map LDAP groups to our permission system
* A `user` can create a project, a project will own multiple `resources`.
* A `user` can create `resource` that belong to the `user`.
* A `user` in a `project` can create a `resource` (i.e customer cluster / SSH key) that belongs to the `project`.
* A `user` is restricted in a project it's `roles`.
* `roles` are additive.
* A `user` can add other `users` to a`project`.
* A `user` can add other `users` to an `role` in the `project`.
* We wan't to have 4 different `role`s:
  + Owner (can do everything)
  + Admin (can add users...)
  + Editor (can create/delete resources...)
  + Viewer (can view resources...)
* `role` maps to the`project` resources.
* `role` maps to the internal customer cluser i.e A Viewer-`role` can see every Kubernetes resource in the cluster.
* A resource always has to belong to a `project`.
* When a user logs in for the first time a default project is created.

---
# Technical design
The general idea is to map `project`/`role` to Kubernetes `group` which are bound to `rule`s
![untitled drawing](https://user-images.githubusercontent.com/7387703/34309206-2c49e604-e751-11e7-8264-16ed5bca7ee1.jpg)
When a project gets created we generate all of it's rules in Kubernetes. When a `user` joins an `role` the rules get bound to the user. This also happens in all client cluster. The client cluster will also have the `role`s as rules but differently generated.
We use [User Impersonation](https://kubernetes.io/docs/admin/authentication/#user-impersonation) to perform user actions such as listing/editing `resources`. For that we can't use the K8s indexer which normally would heavily improve request times. We have to call the API server with every user request.

**Comment by mrIncompetent** [comment]
Shouldn't this be moved to https://github.com/kubermatic/kubermatic/issues/622 ?
And i assume you mean `role` instead of `rule` ?

**Comment by mrIncompetent** [comment]
Why do we want to have `Owner` and `Admin` as `AccessLevel`? Whats the difference?
What do we want that for?
We do need to know who owns a resource but that should not be realized using `AccessLevel`. Instead the resource should know about its owner. (At least that's the way kubernetes handles owners)

**Comment by mrIncompetent** [comment]
This design should *not* cover the propagation into client-clusters

**Comment by mrIncompetent** [comment]
Also i'm not sure if `AccessLevel` is the correct word. Why not using `role`?

**Comment by lbb** [comment]
We should distinguish between Kubernetes objects/resources and Kubermatic ones. Therefore I wanted to choose a very different name to not mess things up. `accessLevel` might not be a good fit what dou you think about `projectRole` ?

**Comment by mrIncompetent** [comment]
As is still think that we need to do a design the business logic i think we should use `role`

**Comment by lbb** [comment]
I wanted to cover the propagation into client-clusters so that we have a clear understanding of the whole concept now. This is not part of the first implementation.

**Comment by lbb** [comment]
*Owner* and *Admin* should be an `accessLevel` because they can perform different actions on the Project CRD. This has nothing to do with the *ownerReference*. Do we need to care who's the _owner_(creator, Kubernetes) of a project, this can be the kubermatic controller. We may want to have multiple *Owners* of a project who can edit/delete the `project`.

**Comment by scheeles** [comment]
I agree with @mrIncompetent we should name it base on the business logic and `role` makes more sense.

**Comment by scheeles** [comment]
PTAL @guusvw

**Comment by lbb** [comment]
> - GET /projects/{id}/me -> returns a description of the acting member in the project context

> - GET /projects -> returns list of projects
> - POST /projects -> Create project
> - PUT /projects/{id} -> Update Project
> - DELETE /projects/{id} -> Delete project


> - GET /projects/{id}/members -> returns list of all users in a project # This can be a composite endpoint
> - PUT /projects/{id}/members -> Update a member
> - POST /projects/{id}/members -> Invite/add user to project
> - Delete /projects/{id}/members/{id} -> Remove user from project

**Comment by mrIncompetent** [comment]
I would prefer user centric endpoints.
/lgtm

**Comment by mrIncompetent** [comment]
One note on the technial implemenration:
Can we **not** expose the types for the CRD to the frontend?
So instead we create a api-type which only exposes the data the frontend really needs?
