### ISSUE TITLE
make node eviction behavior configurable for cluster user 

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#4417]
**User Story**
If an end user triggers an change or delete in the machine deployment, the node eviction will stuck if an user uses a `local storage` like e.g. istio does. 

Since https://github.com/kubermatic/machine-controller/pull/562 a fix timeout of `2 hours` will skip the eviction and delete the node. At least after this time and the machine get deleted. To improve the use experience, it would be great to make this timeout configurable. Maybe it make more sense to move this value to the `MachineDeployment` spec it-self. 

If you would trigger the drain by kubectl you would need to set the flag `kubectl drain --delete-local-data ...`. But I didn't find a possibility to set a taint what respect this.
  
**Acceptance criteria**
- [ ] A change or deletion of machine deployment evict nodes with `local storage`
- [ ] The enforcement behavior is configurable for end users by the front-end

**Comment by alvaroaleman** [comment]
The `--delete-local-data` flag you are mentioning is about `EmptyDir` volume types, not PVs: https://github.com/kubernetes/kubernetes/blob/514ea6f8f8da86a72fdcd68b9781090aff7bb1b2/staging/src/k8s.io/kubectl/pkg/drain/filters.go#L202

I don't think ` A change or deletion of machine deployment evict nodes with local storage` is a fulfillable AC, because there is no API to detect if a PV is backed by something local or not.

> The enforcement behavior is configurable for end users by the front-end

What do you mean by that, do you want a setting to skip draining altogether or a configurable timeout?

**Comment by toschneck** [comment]
>The --delete-local-data flag you are mentioning is about EmptyDir volume types, not PVs: https://github.com/kubernetes/kubernetes/blob/514ea6f8f8da86a72fdcd68b9781090aff7bb1b2/staging/src/k8s.io/kubectl/pkg/drain/filters.go#L202

`Empty Dir` or PV's of type `local storage` seems to fall both under this category. If a pod on a node use such a storage the deletion of the `Machine` object stuck until the timeout of `2h` is reached. 

If we can't detect this use case, we should be able to define a `gracePeriod` for Machines (similar to Pods). The `gracePeriod` could be set by default to e.g. `5min`. If some customer want to enforce (skip the draining) the deletion they can set it to `0`. This field should then also be part then of the advanced options for the MachineDeployments at the Kubermatic UI. 
@alvaroaleman what do you think about?

**Comment by toschneck** [comment]
@kdomanski could we remove this from icebox, as from Alvaro confirmed this is a bug: https://github.com/kubermatic/customer-projects/issues/35#issuecomment-539409516

The steps to reproduce the error are described in the issue
