### ISSUE TITLE
Allow assigning Cluster labels through the API

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#4428]
**User Story**
Analogous to #4374, but for clusters

**Acceptance criteria**
- [x] The API `Cluster` object is extended with a `Labels map[string]string` field
- [x] A cluster's metadata labels are returned in the endpoints:
  - [x] `GET /projects/{project_id}/clusters`
  - [x] `GET /projects/{project_id}/dc/{dc}/clusters`
  - [x] `GET /projects/{project_id}/dc/{dc}/clusters/{cluster_id}`
- [x] The labels can be set/changed by specifying them in the object when using the endpoints:
  - [x] `POST /projects/{project_id}/dc/{dc}/clusters`
  - [ ] `PATCH /projects/{project_id}/dc/{dc}/clusters/{cluster_id}`

**Comment by kdomanski** [comment]
@maciaszczykm did I miss any endpoints?

**Comment by maciaszczykm** [comment]
@kdomanski Looks okay, we will add it to all cluster endpoints.
