### ISSUE TITLE
Add ARNs to AWS presets

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#4456]
**User Story**
Users that have to set a specific **control plane role (ARN)** cannot use presets as this attribute is missing in the AWS preset struct.

**Acceptance criteria**
Presets should allow to set all AWS specific provider settings.

**Comment by kdomanski** [comment]
@maciaszczykm @zreigz At this time the dashboard disables the whole AWS provider settings form the moment a preset is set - therefore it's not possible to specify a role or ARN at all when using presets.

**Comment by zreigz** [comment]
thanks for the info, we will taka a look

**Comment by thz** [comment]
This has quite some urgency. I propose to reduce the acceptance criterion to only add "roleARN" to preset support. Then it matches the $title again.
