### ISSUE TITLE
Flavors are not selectable when creating a new NodeDeployment for cluster on Open Telekom Cloud

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#4517]
**User Story**

When adding a new NodeDeployment to a cluster on OTC, the VM flavor is not selectable. 

![Screenshot 2019-10-21 at 11.19.19.png](https://images.zenhubusercontent.com/5cf547a42356dd3bc0e53bb8/1bdbf215-57c2-4292-9acf-250da7f3f11d)

Machine-controller webhook rejects the request without flavor after adding NodeDeployment:
```
Error 500: failed to create machine deployment: Internal error occurred: admission webhook "machine-controller.kubermatic.io-machinedeployments" denied the request: defaulting or validation failed: validation failed: flavor must be configured
```

Problem seems to be OTC specific, works on other OpenStack instances (SysEleven).

**Acceptance criteria**

User should be able to add NodeDeployments to existing cluster.

**Comment by kdomanski** [comment]
fixed in kubermatic/dashboard#2222
