### ISSUE TITLE
Remove 2nd credential set for vSphere

### ISSUE THREAD

**Issue by thetechnick** [kubermatic/kubermatic#4550]
**User Story**
As user of Kubermatic the 2nd set of credentials confuses me, because there is no description in the UI how these extra fields differ from the other credential set.
Also there is no documentation, why this 2nd credential pair is only needed for vSphere, but not for any other provider.

Thats why I would like to see the feature removed.

---

As a kubermatic developer supporting the 2nd set of credentials makes handling vSphere credentials especially complicated and error prone, so I would like to remove this feature.

**Acceptance criteria**
- [ ] 2nd credential pair is removed from Kubermatic

@alvaroaleman @kgroschoff

**Comment by toschneck** [comment]
As far as I remember, the credentials have been used like this
1. will get used for the cloning of the VM template
2. for the creation of the new disk

In general I agree that this feature is confusing. I think  this was a first step that we need lower permissions for the vsphere datacenter. But if the documentation is missing, we should please add the documentation. 

In my opinion we should investigate first, how can we achieve minimal rights for the end user cluster credentials and maybe split it like we do in AWS 
1. credentials for the cluster creation (maybe could also stored per data center?)
2. for the worker nodes only

**Comment by toschneck** [comment]
link to documented roles: https://docs.kubermatic.io/requirements/cloud_provider/_vsphere/
=> UI and Docs should be in sync

After some more insides with a recent customer feedback, we can't remove this now.  I think it's a good idea to separate credentials for the `cloud config`. As least as long we can't hide the credentials from the end user cluster, with e.g. out of tree CCM #3877 what can be hidden in user cluster. Another possibility what to improve the UX is:

Split the creation of a cluster creation in:
* cluster provisioning credentials (with description/help text about components what get created  and what permissions are needed)
* cluster cloud provider credentials (with description/help text what describes where the cloud provider credentials will get used and what permissions they need). 

@thetechnick let me know your thoughts

**Comment by thetechnick** [comment]
Yeah that makes a lot of sense and it would be something that we can support for all cloud providers - so we don't have this special one-of case for vSphere.

**Comment by alvaroaleman** [comment]
> Yeah that makes a lot of sense and it would be something that we can support for all cloud providers - so we don't have this special one-of case for vSphere.

The main reason this is needed for vsphere is that the set of permissions needed to create instances is extremely broad, as vsphere does not have the concept of multitenancy. This is why vsphere operators are more hesitant to give out credentials.

Multitenancy does exist on all other providers, which is why its not needed there.

**Comment by thetechnick** [comment]
I would argue differently - usually Kubermatic needs more permissions to setup stuff at the Cloud Provider, then the cluster itself needs to operate.

As the cluster-level credentials (for the cloud controller manager) can be exposed to users of the cluster, a split of credentials for infrastructure setup and the cloud controller manager makes a lot of sense to me and is not unique to vSphere (But I agree that it's a especially bad thing for vSphere).

**Comment by alvaroaleman** [comment]
> As the cluster-level credentials (for the cloud controller manager) can be exposed to users of the cluster, a split of credentials for infrastructure setup and the cloud controller manager makes a lot of sense to me and is not unique to vSphere (But I agree that it's a especially bad thing for vSphere).

Well, the remaining providers that have an in-tree provider all have the concept of an instance profile except for openstack. And for Openstack I'd prefer to instead integrate the external CCM and then not have that problem in the first place.

**Comment by thetechnick** [comment]
Oh, I always forget about instance profiles...

So for the external CCM, we would run it alongside the kube-apiserver in the seed clusters so users will not have access to it, which means we don't need separated credentials (for openstack)?

**Comment by alvaroaleman** [comment]
> So for the external CCM, we would run it alongside the kube-apiserver in the seed clusters so users will not have access to it, which means we don't need separated credentials (for openstack)?

Yes, exactly
