### ISSUE TITLE
vSphere: increase default CPU and Memory

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#4606]
**User Story**
With current defaults (`1` CPU, `512` MB ) nodes probably don't come up. So we should configure the defaults to some higher values, e.g.: `2` CPU and `4096` RAM

**Acceptance criteria**
- [x] new defaults get shown in the UI
- [ ] new defaults are present in the kubermatic installer

**Comment by kgroschoff** [comment]
Created seperate Issue for the Dashboard https://github.com/kubermatic/dashboard-v2/issues/1951

**Comment by kgroschoff** [comment]
According to @xrstf there are no provider defaults in the kubermatic installer.

@toschneck / @kdomanski Is this issue fixed? UI is already merged https://github.com/kubermatic/dashboard-v2/pull/1952

**Comment by kdomanski** [comment]
The UI change seems to cover the topic. Closing
@toschneck "probably" don't come up? ;-)
