### ISSUE TITLE
Fix the cleanup condition in Azure cloud provider

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#4637]
**User Story**
The instances should be deleted if there was no error returned during the fetching of that instance. If there was an error returned and that error was not 404 error, then it should be returned. 

**Acceptance criteria**
- [ ] Fix the condition in the Cleanup method: https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/azure/provider.go#L492-L497

**Comment by alvaroaleman** [comment]
This was done in https://github.com/kubermatic/machine-controller/pull/654
