### ISSUE TITLE
Test and update the installer

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#464]
Test if the installer is working.
https://github.com/kubermatic/kubermatic/tree/develop/config/installer 

Update the https://github.com/kubermatic/kubermatic/blob/develop/config/README.md

**Comment by susman** [comment]
The way I see the final product ( that installer ):
Two parts:
1. Internal, one of us creates ‘environment’ for new customer:
  * Dockerhub account, readonly rights, should check if exists first
  * Image contains:
    * installer
    * assets
    * dockerhub auth json hardcoded
    * shipped version hardcoded
2. Customers part:
 * Image with no entrypoint comes as a tarball ( download link ) / docker hub credentials shared with 
 * customer, they pull themselves ( dangerous )
   * Customer calls installer in image with parameters:
   * Future URL for dashboard
   * Deployment type ( baremetal/DO/aws/openstack/gke/gcp? )
   * datacenters.yaml if it’s baremetal, if not - default one
   * If deploy monitoring, provide prometheusauth
   * storage zone for non-baremetal

**Comment by susman** [comment]
Regarding "storage zone for non-baremetal" @mrIncompetent suggests we should either expect storage-class ready, or deliver it as a different package, as the only two parameters currently controlled by helm charts are zone and type, which is not enough.

**Comment by susman** [comment]
Currently the picture seems entirely different:
The desired state involves complete delivery by CI. Our systems build an image containing helm charts, secret data ( clinet's kubeconfig and values.yaml ) is stored in drone secrets, later delivered to client's k8s cluster and stored as secret in there. Installer image picks on those secrets and executes helm.
