### ISSUE TITLE
Update ELK 

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#465]
Update our ELK setup https://github.com/kubermatic/kubermatic/tree/develop/config/efk-logging 

We could reuse https://github.com/clockworksoul/helm-elasticsearch

alternative
https://github.com/giantswarm/kubernetes-elastic-stack or 
https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch

**Comment by alvaroaleman** [comment]
This was done within #1216
