### ISSUE TITLE
Removing a user cluster on vsphere leaves behind an empty folder

### ISSUE THREAD

**Issue by eqrx** [kubermatic/kubermatic#4722]
**User Story**
When we delete a user cluster that resides in vsphere, the folder that was originally contained all the cluster related resources remains and clogs up the server

**Acceptance criteria**
- Cluster folder in vsphere gets deleted

**Comment by toschneck** [comment]
@eqrx are your sure that this isn't related to a permission issue. Please see the updated permissions docs: https://docs.kubermatic.io/kubermatic/v2.12/requirements/cloud_provider/_vsphere/

**Comment by moadqassem** [comment]
@kdomanski Are you working on this? if not you can unassign yourself again :)

**Comment by moadqassem** [comment]
I have spent some time debugging this issue, by creating user clusters in vSphere cloud provider using all os options and all the cluster folders were deleted on clean up.
