### ISSUE TITLE
Removal of beta.kubermatic.io

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#473]
- [x] Record cluster with nodes

- [x] Inform the user with nodes to migrate to cloud.kubermatic.io

- [x] Delete beta seed clusters

- [ ] Inform all User about the new cloud.kubermatic.io (Krissi)

**Comment by mrIncompetent** [comment]
Before we need to migration cloud to 1.7!

**Comment by mrIncompetent** [comment]
Deleted.
