### ISSUE TITLE
Integration of vCloud Director

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#4772]
**User Story**
Integrate vCloud Director as a new cloud provider in Kubermatic

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/4772).

**Acceptance criteria**
- Create cluster
- Delete cluster
- Worker nodes are deployed

**Comment by scheeles** [comment]
Hi @sebastian, how are the tests and implementation of vCloud Director going? I just found a method to insert cloud-init metadata into VM deployments using DataSourceOVF. Apparently the vcloud go sdk also implemented this: https://github.com/vmware/go-vcloud-director/pull/235

**Comment by scheeles** [comment]
could be usefull

**Comment by scheeles** [comment]
For more Infos check this https://loodse.slack.com/archives/CNYMA318U/p1576142571000100

**Comment by kron4eg** [comment]
@scheeles is this still relevant?
