### ISSUE TITLE
Addon deletion does not work

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#4850]
**User Story**

When deleting an optional addon (e.g. node-exporter) using the UI, the addons.kubermatic.k8s.io object is deleted from the user clusters namespace. However, the deployed objects (e.g. DaemonSet) keep running in the user cluster.

**Acceptance criteria**

All resources that have been deployed as an addon should be deleted from the cluster if the addon object is removed from the seed.

**Comment by toschneck** [comment]
Bug is still present, tested it with the weekly `weekly-2020-03`. After a addon is deleted the addon still remains in the cluster.

**Steps to reproduce:**

1. Configure a selectable addon and ensure this is not in the default addons (e.g. the node-exporter)
2. Create a cluster and apply the addon
3. check that the add-on is created in the cluster
4.  delete the add-on from the ui
5. check the deployments in the user cluster (node-exporter was still there) No errors in logs :-/

![image](https://user-images.githubusercontent.com/4659261/73143971-792a9400-40a0-11ea-8896-99bc0d2db147.png)

**Comment by xrstf** [comment]
> {"level":"error","time":"2020-01-31T13:47:39.720Z","logger":"kubermatic_addon_controller","caller":"addon/addon_controller.go:193","msg":"Reconciling failed","worker-name":"","cluster":"6x7pnz56j2","addon":"node-exporter","error":"failed to delete manifests from cluster: failed to execute 'kubectl --kubeconfig /tmp/cluster-6x7pnz56j2-addon-node-exporter-kubeconfig delete -f /tmp/cluster-6x7pnz56j2-node-exporter.yaml --ignore-not-found true' for addon node-exporter of cluster 6x7pnz56j2: exit status 1\nerror: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well\n","errorCauses":[{"error":"failed to delete manifests from cluster: failed to execute 'kubectl --kubeconfig /tmp/cluster-6x7pnz56j2-addon-node-exporter-kubeconfig delete -f /tmp/cluster-6x7pnz56j2-node-exporter.yaml --ignore-not-found true' for addon node-exporter of cluster 6x7pnz56j2: exit status 1\nerror: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well\n"}]}
