### ISSUE TITLE
Resource leak when creating Kubernetes dashboard connections from UI

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#4862]
**User Story**

Connecting to the Kubernetes dashboard from the Kubermatic UI increases the memory usage of the kubermatic-api pod with each connection. The kubermatic-api eventually becomes unresponsive. The memory consumption of the kubermatic-api does not decrease anymore.

**Acceptance criteria**

- Resources should be freed properly
- Creating new dashboard connections should be restricted rather than the kubermatic-api becoming unresponsive

**Comment by kdomanski** [comment]
crossref: #4524, #4483
