### ISSUE TITLE
Multi AZ support for OpenStack

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#4909]
**User Story**

OpenStack datacenters contain currently a fixed availability zone in the datacenters.yaml / CRD. To support HA clusters over multiple AZs, the zone should be selectable when creating a machine deployment.

This is already supported by the machine-controller, but missing in the Kubermatic API / UI. Editing a machine-deployment from the UI currently sets it to the AZ, configured for the datacenter.

**Acceptance criteria**

Availability zone is selectable during machine deployment creation from the UI

**Comment by alvaroaleman** [comment]
Does Openstack have working cross-AZ networking?

**Comment by chrkl** [comment]
At least on OTC private subnets are not bound to an AZ.
