### ISSUE TITLE
Move drone agents to office vm's

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#492]
Drone is not good at handling restarts of nodes during a build.

That's why we should move the agents to our hardware.
Please create 2 VM's (ubuntu/8vcpu/8gb)

**Comment by metalmatze** [comment]
As long as the agents are able to connect to our drone server via port 9000 with gRPC, this should work. 👍

**Comment by mrIncompetent** [comment]
@metalmatze The connection is unidirectional, right?
The server is not calling the agents?

**Comment by metalmatze** [comment]
AFAIK the agents requests a connection to the server and then they both talk via gRPC streaming.
