### ISSUE TITLE
Kubermatic API server doesn't work when one of the seeds is down

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#4950]
![image](https://user-images.githubusercontent.com/993296/72166805-37c09600-33ca-11ea-8539-6a4c07c22bc9.png)

**Comment by xrstf** [comment]
In case of bad Seeds, the API pods will still come up and are already just carefully logging errors. The individual API endpoints however are more stricter and treat each bad Seed as a user-visible fault.

This can easily be reproduced by deleting the kubeconfig Secret for a Seed (the admission webhook would prevent you from changing the Seed itself to point to a non-existing Secret).
