### ISSUE TITLE
Do not include vSphere credentials in machinedeployments

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#4974]
**User Story**
When creating a vSphere user cluster in dev.kubermatic.com with default preset the vSphere credentials are included in clear in the machinedeployment field `overwriteCloudConfig`. e.g.
```
          overwriteCloudConfig: |+
            [Global]
            user              = "dummy-user"
            password          = "PWD_IN_CLEAR"
            port              = "443"
            insecure-flag     = false
            working-dir       = "2md62sxqdv"
            datacenter        = "dc-name"
            datastore         = "dummy-datastore"
            server            = "VCENTER-URL"

            [Disk]
            scsicontrollertype = "pvscsi"

            [Workspace]
            server            = "VCENTER-URL"
            datacenter        = "dc-name"
            folder            = "/dc-1/vm/kubermatic/2md62sxqdv"
            default-datastore = "dummy-datastore"
            resourcepool-path = ""
```

**Acceptance criteria**

MachineDeployment resources do not include credentials in cleartext.

**Comment by toschneck** [comment]
It's also present at the nodes it self. So it would be the best to somehow refactor the whole implementation and use external CCM and CSI

**Comment by moadqassem** [comment]
> It's also present at the nodes it self. So it would be the best to somehow refactor the whole implementation and use external CCM and CSI

Either cases, you still need to provide the coud-config parameters to the yet to be provisioned node as the documentations suggests [here](https://github.com/kubernetes/cloud-provider-vsphere/blob/5fb7d5ecbaa6f40a26acb1e00c7b11c1b8072a5c/docs/book/tutorials/kubernetes-on-vsphere-with-helm.md#create-a-cpi-configmap). 

There is another possibility that we can actually go with, which is OSM. For example, this field here: https://github.com/kubermatic/operating-system-manager/blob/master/deploy/osps/default/osp-ubuntu.yaml#L606-L612 can be entered by the user. However, the credentials will be presented in the secret which OSM will create to provision the cluster. This secret exists in the user cluster of course not in the seed.

**Comment by toschneck** [comment]
@moadqassem I think a secret is still better as plain text file on the node. Potentially we can manage it via RBAC, so that the assigend "cluster-admin" role, don't see it by default. I know, somehow you will be able to get it, but it would be better protected as it is right now. 

Especially we should separate it from the machinedeployment config, as this is something I want to store inside of e.g. a git repo for managing my machine deployment objects.
