### ISSUE TITLE
enforcement of default addons in user cluster

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#4979]
**User Story**
As Kubermatic operator I want to enforce that some addons are placed in the cluster. Even if the user cluster admin deletes a addon it should get recreated.

Currently Kubermatic only recreates the addons when a cluster definition is changed. In my opinion the addon controller should continuously check if there is a diff between addon config and addon deployment
This behavior was tested at the  `weekly-2020-03` version. 

**Acceptance criteria**
- [ ] default addons get enforced
- [ ] a deleted default addon in the user cluster get created immediately

**Comment by kron4eg** [comment]
Apparently, "always enforce" is also not a desired behaviour, for example "kubelet-configmap" is not needed to be reconciled.

Probably we should have some additional flag that will prevent some addons from reconciling.

**Comment by toschneck** [comment]
kubelet-configmap is indeed a corner case. 
For normal add-ons where you don't overwrite existing add-ons I would vote for using the accessible add-on construct, see https://docs.loodse.com/kubermatic/master/advanced/addons/#accessible-addons
Maybe adding a flag what enables an initial deployment of an accessible add-ons could do the trick

**Comment by kron4eg** [comment]
We could also try to use annotations (in manifests).

**Comment by moelsayed** [comment]
@kron4eg What do we like here?:
- Enforce everything _except_ for addons with a specific annotation?
- Enforce _only_ addons with a specific annotation?

@toschneck I am not sure I understand the accessible addon construct in this context, could you please explain ?

**Comment by kron4eg** [comment]
@moelsayed I suggest to take a look at the https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager#addon-manager and use the same model, with default to`Reconcile` (for backward compatibility)

**Comment by floreks** [comment]
Based on the customer reports (support ticket 145) this issue does not seem to be fixed.

/reopen

**Comment by kron4eg** [comment]
Overall this story has been implemented. There is a corner-case for kubeadm-config reconciliation (from kubelet-config addon), that will be tracked in #7141 .
