### ISSUE TITLE
upgrade to nginx-ingress-controller 0.28

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#4985]
**User Story**
We'd like to upgrade to `nginx-ingress-controller` `v0.28.0`, however some changes that were present since at least `v0.27.0` result in it crashlooping with our current configuration. The log says:
```
ssl.go:389] unexpected error storing fake SSL Cert: could not create PEM certificate file /etc/ingress-controller/ssl/default-fake-certificate.pem: open /etc/ingress-controller/ssl/default-fake-certificate.pem: permission denied
```

**Comment by bashofmann** [comment]
0.27.x and 0.28.0 work for us, but we are also using this helm chart: https://github.com/helm/charts/tree/master/stable/nginx-ingress.

Could it be that the error is because of this change in 0.27.0:

```
Due to the migration to alpinelinux the uid of the user is different.
Please make sure to update it runAsUser: 101 or the ingress controller will not start (CrashLoopBackOff).
```

See https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.27.0

**Comment by kdomanski** [comment]
Nice catch, thx.
