### ISSUE TITLE
Assign Public IP flag not respected for MachineDeployments on Azure

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5013]
**What happened?**:

When creating a MachineDeployment on Azure, the nodes get a public IP address, even if the `Assign Public IP` checkbox is not selected.

**What should happen?**:

Public IP should be assigned only if checkbox selected

**How to reproduce?**:

**Environment**
- UI Version: 2.25.2
- API Version: 2.25.2
- Domain:
  - [x] run
  - [ ] cloud
  - [ ] dev
  - [ ] locally
- Others:

**Comment by kgroschoff** [comment]
Might be related to https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/machine/common.go#L107 ?

cc @kdomanski do you know something about the status of the "DNAT topic"?

**Comment by kdomanski** [comment]
I don't know a "DNAT topic", but it would make sense to me if what we were missing there was routing out of private networks on Azure.
Either way, the code should not be silently overwriting the value of the private IP setting, i.e. it's better to fix the disabling of private IPs and just have plan broken networking in this case.

**Comment by kgroschoff** [comment]
Agree 👍 

Will move it to kubermatic repo, as this has nothing to do with the frontend.
