### ISSUE TITLE
Kube-Machine - Created ~100 ssh keypairs but not a single node

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#502]
On sys11 we ran into the issue where the node-controller was creating ssh-keypairs at openstack but failed to create nodes.
Make sure that ssh-keys are getting cleaned up if a node cannot be created.

Seems some docker-machine drivers are not cleaning up ssh-keys when a instance deletes fails. 

The digitalocean driver deletes the ssh-key before deleting the instance (correct): https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go#L365

The openstack one deletes the key after the machine has been deleted (wrong):
https://github.com/docker/machine/blob/master/drivers/openstack/openstack.go#L454

After patching make sure, we use the patched version in kube-machine

**Comment by guusvw** [comment]
Changes for docker/machine-fork

https://github.com/kubermatic/machine/pull/2

and using the fork in the kube-node/kube-machine

https://github.com/kube-node/kube-machine/pull/24
