### ISSUE TITLE
Docker Image tag's on quay.io

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#5024]
**User Story**
@kdomanski 
During the upgrade of run-2 to the current release candidate, similar to the last weekly release, also the release candidate tags `v2.13.0-rc.1` are missing at quay.io for our images.

**Acceptance criteria**
- [ ] a new release, creates the images tags in quay.io

**Comment by kdomanski** [comment]
CI scripts are currently broken.

**Comment by kdomanski** [comment]
https://prow.loodse.com/view/gcs/prow-data/logs/ci-push-images/1224707059098849280

**Comment by toschneck** [comment]
@kdomanski many thanks
