### ISSUE TITLE
Cleanup kubermatic-installer repo

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#5026]
**User Story**
Currently the end user experience of https://github.com/kubermatic/kubermatic-installer/tree/release/v2.13 is not nice. It's seams there are a lot of outdated things. We should provide a clean structure here, what belongs to the kubermatic operator installer and what to the helm chart installer.

**Acceptance criteria**
- [ ] end user needed resources are structured and accessible in an easy way
- [ ] unused resources have been removed

**Comment by kdomanski** [comment]
Please name all these users, I'll remove their access to the repo as soon as the kubermatic operator is out.
