### ISSUE TITLE
Enable SNAT for created VPC on OTC

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5028]
**User Story**

SNAT for the created VPC is not activated when creating a cluster on OTC (OpenStack). Nodes are not able to join the cluster with this setting if no public IP address is assigned.

**Acceptance criteria**

- [ ] Activate SNAT for VPCs on OTC

**Comment by kdomanski** [comment]
Still waiting for access to OTC, so I can investigate.
