### ISSUE TITLE
Option to limit project creation to admin users

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5032]
**User Story**

Customer wants to limit project creation to specific admin users. 

**Acceptance criteria**

- [ ] Option to limit project creation globally, e.g. in admin-panel
- [ ] Only admin users can create new projects when activated

**Comment by toschneck** [comment]
connected to https://github.com/kubermatic/kubermatic/issues/4996

**Comment by scheeles** [comment]
I would not restrict it to admin. We should great RABC rules for User for Projects similar we have inside a project.
