### ISSUE TITLE
Generic ways to add admission plugin for API server

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#5033]
**User Story**
Make a generic way to extend the admission plugin flag for the user cluster API server.
There are two supported plugins right now PodSecurityPolicy And PodNodeSelecter. The user would like to have possibilities to set other plugins without touching the code.

**Comment by toschneck** [comment]
We should discuss if the admission plugins are settings per cluster, datacenter or a global level

**Comment by zreigz** [comment]
This one is only for the user cluster (during cluster update or creation). Right now we have checkboxes for two plugins `PodSecurityPolicy` and `PodNodeSelector`. There is no way to add some extra plugins. I was thinking to add string field to the cluster struct and the user will be able to add comma separated plugins which will be applied to the API server.
