### ISSUE TITLE
CoreOS EOL

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#5048]
**User Story**

End-of-life announcement for CoreOS Container Linux on May 26, 2020,
https://coreos.com/os/eol/

We should consider either Fedora CoreOS or Flatcar Container Linux

**Acceptance criteria**

**Comment by kdomanski** [comment]
Update: Since many pieces are missing for Fedora CoreOS, e.g. they have podman/docker conflicts, there's no update operator, we'll go with Flatcar for now.
