### ISSUE TITLE
Add overwriteRegistry support for Openshift resource deployment

### ISSUE THREAD

**Issue by moelsayed** [kubermatic/kubermatic#5059]
**User Story**
Currently, the Openshift resource deployment code doesn't respect the overwriteRegistry passed to the seed controller. It should be supported.
**Acceptance criteria**
- [ ] When `overwriteRegistry` is used, all Openshift related images should be pulled from that registry.

**Comment by moelsayed** [comment]
Since the Openshift images use a single base image with different digests, each pointing to a layer representing the actual image used. It's not possible to "re-tag" image digests, so, as a work around, PR #5055 adds a helper function to use the digest hex as a tag. PR #5052 will use the same convention to push the images to a private registry.

re: https://github.com/kubermatic/kubermatic/pull/5055#issuecomment-584072099:
I agree that it's not a very clean solution, it just works (TM). However, I don't think we need to support the official mirroring procedure since we already have a supported alternative. 

It makes more sense to use the kubermatic image-loader in this case since we also load our _own_ images that are required for the deployment. Even if the user uses the ocp official mirroring procedure for Openshift images, they will still have to use the kubermatic image-loader for the kubermatic-related images anyway. It would be pointless to do this.

**Comment by irozzo-1A** [comment]
> It makes more sense to use the kubermatic image-loader in this case since we also load our own images that are required for the deployment. Even if the user uses the ocp official mirroring procedure for Openshift images, they will still have to use the kubermatic image-loader for the kubermatic-related images anyway. It would be pointless to do this.

I partially agree with this, I take your point that anyway we need our images, but I think that it's worthy to explore the way mirrored images are supported in OCP4 and if we can implement something compatible with their tooling it could bring even more value.
Having a clear picture of how things work in OCP4 is fundamental to me in order to have an opinion on which is the best approach to take and I don't have it yet.

**Comment by moelsayed** [comment]
I updated the PR to support the same format as the OCP4 tool using component names and Openshift version for the tags.
