### ISSUE TITLE
Set new basic-auth for sys11 prom setup

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#506]
Current state:
Default credentials

Desired state:
- New, secure credentials
- user: admin
- pw: 12 random chars
- Place the new credentials in a textfile on the jumper host on sys11
- Let them via slack know that we changed the credentials and tell them where to find the new one

**Comment by metalmatze** [comment]
You did that yesterday, right @mrIncompetent?

**Comment by mrIncompetent** [comment]
Yep
