### ISSUE TITLE
Add support for custom images on Azure

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5065]
**User Story**

Users should be able to create MachineDeployment using a custom image for the supported OS types.

**Acceptance criteria**

- [ ] Image can be selected in MachineDeployment

**Comment by moadqassem** [comment]
As RHEL default images in Azure do not support cloud-init by default, I had to add the functionality of using custom images for azure thus this ticket is resolved implicitly by this PR: 

https://github.com/kubermatic/machine-controller/pull/694/files#diff-c2031bd230a01a9bc34ee22c779655edR141-L139
