### ISSUE TITLE
Support Data Encryption Config and Key

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#509]
Kubernetes stores a variety of data including cluster state, application configurations, and secrets. Kubernetes supports the ability to encrypt cluster data at rest.

see:
https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/06-data-encryption-keys.md

**Comment by mrIncompetent** [comment]
What should be encrypted?
Whats the goal if this issue?

**Comment by mrIncompetent** [comment]
@scheeles ?
