### ISSUE TITLE
Support OPA Policies on User cluster

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#5201]
**User Story**
As a user I would like to enforce a specific set of polices e.g. for security. This polices should be describe as OPA. For this we would like to deployed the https://github.com/open-policy-agent/gatekeeper as an addon to each user cluster. 

**Acceptance criteria**

- [ ] Gatekeeper via Addon deploy
- [ ] Collect metrics per cluster 
- [ ] Aggregate metrics over all cluster e.g. violations

**Comment by youssefazrak** [comment]
@kdomanski any update on this one?

**Comment by kdomanski** [comment]
@scheeles will write a proposal.

**Comment by xrstf** [comment]
We track the work in #5759.
