### ISSUE TITLE
Allow enforcing PSP on datacenter level

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#5225]
**User Story**
Analogous to #4298, but for PSPs.

**Acceptance criteria**
- [ ] A new per-datacenter setting `enforcePSP` will cause all clusters created within the given datacenter to have PSP enabled.
- [ ] This will be added to both old file-based DCs, as well as DC CRDs.
- [ ] The nornal per-cluster setting is ignored.
- [ ] The value of `enforceAuditLogging` is sent over the API then datacenter(s) are fetched.

**Comment by moelsayed** [comment]
https://github.com/loodse/docs/pull/307
