### ISSUE TITLE
Set the globalsettings object from the kubermatic helm chart

### ISSUE THREAD

**Issue by kgroschoff** [kubermatic/kubermatic#5226]
There is a request from a customer, if we plan to set the globalsettings object from the kubermatic helm chart, because it’s not supported yet.

This should be the first issue for further planing

**Comment by kdomanski** [comment]
No, we don't. The helm charts will eventually deprecated in favor of the operator. We also won't be taking internal architecture change requests to match a customer's specific installation workflow - especially one that couples unrelated components.
