### ISSUE TITLE
Ensure kube-dns svc IP is not used by any other service

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#5232]
**User Story**
When a cluster is deployed, on the user side we have couple of services that are created. One of them is kube-dns svc. This one is using a hardcoded IP.
Right now we can hit race conditions where another service could get allocated the "hardcoded" IP of kube-dns. In this scenario, this leads to whole user-cluster failure as DNS resolution can't work properly.
The probability of this happening is still very slim (4094 usable addresses in the svc network range).
 
**Acceptance criteria**
kube-dns IP is not attributed to any other services in the user cluster.

**Comment by moelsayed** [comment]
fixed in #5370
