### ISSUE TITLE
Add dynamic datacenters

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#5357]
**User Story**

The admin user can manage datacenters (list, get, patch, delete, put). The data centers are part of the seed object. The datacenters should be displayed for the provider:
`/api/v1/admin/providers/{provider_name}/dc`

Filter by: country and seed

Design: https://app.zenhub.com/workspace/o/kubermatic/dashboard/issues/1902

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/dashboard/issues/5357).

**Comment by tharun208** [comment]
@xrstf @zreigz I like to work on this
