### ISSUE TITLE
Move cloud-provider initialization into controller

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#536]
**Current state**:
We initialize the cloud provider in the create-cluster api call.

Cloud-provider intialization means:
- Creating infrastructure (security-groups, networks, etc.) at the cloud provider (currently aws & openstack)

This has the drawbacks, that we cannot create clusters via `kubectl create -f my-cluster.yaml`

**Desired state**:
- Cloud provider Initialization happens in the pending phase of the cluster controller
- Write a cluster condition (success & failed) when initialization done (Goal is that we can show cluster conditions to the user in the long term)
- Block further processing of the cluster when the initialization fails (can we actually fail a pending-function and update the cluster?)
- We have a new function `Validate(*kubermaticv1.CloudSpec) error` on the `NodeProvider` interface.
Goal is to validate the given cloud spec. 
- During the create cluster api call, we call the `Validate` function to prevent creating clusters with invalid credentials.

**The flow**
Create cluster api call:
- Call the validate function to check if the cloud provider input is correct
- Create the cluster resource

cluster controller (pending phase):
- Call the Initialize function for the cloud provider & write a cluster condition

@realfake Please validate - you are probably the person implementing this ;)

**Comment by mrIncompetent** [comment]
My goal is that we use this during ci to create clusters for conformance tests.
This avoids the token handling completely.

Though: we would need to render the nodeclass

**Comment by lbb** [comment]
I wouldn't call the validate function during the cluster creation.
We schlould utilise the status on the cluster CRD. (I'll just sum this up)
0. Call Initilauze() to crate cloud resources (if fails)-> CRD status=Failed + Error message is in Condition
1. Call Validate (if fails)-> CRD status=Failed + Error message in condition

**Comment by lbb** [comment]
This way we can have it fully declarative and reliable.

**Comment by lbb** [comment]
This way we should have a conditions fiel in our status.
i.e:
```yaml
phase: Rinning
status:
  conditions:
  - lastTransitionTime: 2017-10-21T22:11:42Z
    lastUpdateTime: 2017-10-21T22:11:42Z
    reason: Cluster available
    status: "True"
    type: Available
```

**Comment by mrIncompetent** [comment]
Then we let the user create a failed cluster. Very bad user experience - that is already something we got as feedback.

Also: 
- A error during Initialize should not cause the failed state on the cluster. We should retry and therefore set a condition. Thats at least the normal behaviour of a k8s-controller.

**Comment by lbb** [comment]
👍

**Comment by lbb** [comment]
Oh I think I misunderstood the issue. So we need to validate user input not the _created_ resources. OCF we do a retry on the controller.

**Comment by mrIncompetent** [comment]
On the create-cluster api call, we:
- Call the Validate function to check that the cloud-provider specific inputs are correct - For example: The given security-group exists.
- If the validate function succeeded, we create a cluster-resource.

The controller then:
- The controller then creates cloud provider infrastructure - when needed

**Comment by lbb** [comment]
Okay, then it’s the same as I already have written except that the order is different. We should still use the `condition` object in the cluster status.

**Comment by mrIncompetent** [comment]
Got higher priority as sys11 ran multiple times into the missing validation.
