### ISSUE TITLE
DigitalOcean: Set kubermatic tag on created nodes

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#537]
Based on tags one can manage firewalls for nodes at DigitalOcean. I currently have a `kubernetes` tag on my maches. But maybe we should add a `kubermatic` tag to the nodes we create, so firewall rules I create for that tag apply automatically.

**Comment by mrIncompetent** [comment]
I would rather go for a cluster specific tag like:
`kubermatic-cluster-2k2wvnxxw`

Thats fairly simple to solve, as docker-machine already provides a flag to set the tags:
https://docs.docker.com/machine/drivers/digital-ocean/

Feel free to add this to the nodeclass:
https://github.com/kubermatic/kubermatic/blob/master/config/kubermatic/static/nodes/digitalocean.yaml
