### ISSUE TITLE
DigitalOcean: Enable private IPv4 by default?

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#538]
I had to go to the settings and enable private IPv4 manually. Given I want to create a cluster, I think it makes sense to enable that by default?

**Comment by mrIncompetent** [comment]
docker-machine provides a flag:
https://docs.docker.com/machine/drivers/digital-ocean/

nodeclass:
https://github.com/kubermatic/kubermatic/blob/master/config/kubermatic/static/nodes/digitalocean.yaml

Keep in mind:
Pod networking does not use the private networking at the moment.
