### ISSUE TITLE
Add flags for nodeclass templates

### ISSUE THREAD

**Issue by lbb** [kubermatic/kubermatic#540]
Currently our resources for node controller have to be at a hardcoded position, 
we should have a flag that specifies this https://github.com/kubermatic/kubermatic/blob/909d989c08f79caf1780d28cd6394eef7b9c8221/api/pkg/provider/cloud/openstack/provider.go#L21

**Comment by mrIncompetent** [comment]
Why has this already been assigned?

**Comment by lbb** [comment]
Sry

**Comment by lbb** [comment]
My fault

**Comment by alvaroaleman** [comment]
Wontfix as we don't have a nodeclass anymore.
