### ISSUE TITLE
Creating node deployment without name gives 500

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#5447]
SysEleven while working on terraform provider for kubermatic discovered a problem described below, info from @furkhat :

> Creating node deployment without name gives **500** if cluster was previously created without node deployments.
>     Steps to reproduce:
>        1. Create a cluster with zero node deployments
>        2. Add node deployment without specifying a name
>     Expected behaniour:
>           Node deployment successfully created
>     Actual behaviour:
>           500 Internal Server Error

**Comment by mfranczy** [comment]
If name is not passed, is it server side generated? If not, shouldn't we return bad request instead of internal server error?

**Comment by kdomanski** [comment]
I was unable to replicate the issue on our dev environment.
I would be helpfull to see kubermatic-api container logs corresponding to the failed request.

**Comment by furkhat** [comment]
I can no longer reproduce this bug.
I remember it seemed like node deployment's name would be generated based on the name of previous node deployment. If I remember right it would go like ...worker-1 ...worker-2, and when there are no initial node deployment it would fail. But once again, I can no longer reproduce this bug.

If I encounter this bug again I will provide kubermatic-api logs.
