### ISSUE TITLE
Structure for PATCH requests in go-kubermatic

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#5449]
SysEleven while working on terraform provider for kubermatic discovered a problem described below, info from @furkhat :

> Cluster PATCH go-kubermatic. Expected an actual structure here https://github.com/kubermatic/go-kubermatic/blob/master/client/project/patch_cluster_parameters.go#L64, but found interface{}

**Comment by mfranczy** [comment]
I am not sure, but I think this is how go-swagger generates the client and it's not on kubermatic api side. Worse case they could import kubermatic API types when the code is opened.
Any thoughts?

**Comment by zreigz** [comment]
Yes, this how the go-swagger generates the client. We have to stick with this right now
