### ISSUE TITLE
API fields validation

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#5450]
SysEleven while working on terraform provider for kubermatic discovered a problem described below, info from @furkhat :

> POST Payload values validation.
>     Steps to reproduce:
>        1. Create a cluster with 'version` = '1.2.3'
>     Expected behaviour:
>           400 Bad Request
>     Actual behaviour:
>           200

**Comment by furkhat** [comment]
I think k8s version validation is very important also for upgrades. K8s suggest to perform upgrades one by one. Which basically means if I want to upgrade from 1.15.x to 1.17.x, I should perform two upgrades: 1.15.x -> 1.16.x -> 1.17.x. Right know nothing stops me from changing version to whatever I desire, this is prone to errors. Let's add validation for step-by-step upgrades too.
