### ISSUE TITLE
GET request for deleted cluster from deleted from returns `no userInfo in request`

### ISSUE THREAD

**Issue by furkhat** [kubermatic/kubermatic#5462]
I encountered this error when tried to request info on deleted cluster, and was surprised to see 500 reply
Try `/api/v1/projects/foo/dc/dbl1/clusters/bar`, reply is
```
{
  "error": {
    "code": 500,
    "message": "no userInfo in request"
  }
}
```

**Comment by zreigz** [comment]
@furkhat can you clarify your steps. I have created the cluster, deleted it and executed 
`GET api/v1/projects/57lm65pgrf/dc/europe-west3-c/clusters/pgr7psdqd9`
and I got proper response:
`{"error":{"code":404,"message":"clusters.kubermatic.k8s.io \"pgr7psdqd9\" not found"}}`

Additionally, I have fixed error handling for cluster endpoints. Should return the real cause of the error.

**Comment by furkhat** [comment]
@zreigz in short, try deleting project altogether and you should see the error.

Here's all the steps I did to repro:
1. Create an openstack cluster
2. Request cluster details 200
3. Delete the cluster and the project
4. Request cluster details with same URL, get 500 `no userInfo in request`

**Comment by zreigz** [comment]
@furkhat thanks, I will test it and confirm if my PR fixes the problem
