### ISSUE TITLE
dynamic datacenters - add hidden option for dc

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#5466]
**User Story**
Add option to set DCs as hidden.

**Comment by kdomanski** [comment]
How would using that work? Would it be simply hidden in the UI but still usable by the API? Or would it require manual adding of cluster objects?

**Comment by lsviben** [comment]
I see it as hidden for normal members, but still visible for admins - case when admins dont want to have some DCs available to members, or want to temporarily suspend a DC. So admins would still be able to use it in UI and API. But normal members (which anyway can just GET/LIST) wont be able to access them.

To be honest those can be done with the existing email filtering, only that it could be more time-consuming to catch all the email domains. So I guess this task is not a big priority

`Or would it require manual adding of cluster objects?` Could you elaborate, I dont think i fully understand this question.

cc: @zreigz @maciaszczykm @kgroschoff if you have anything to add
