### ISSUE TITLE
Move the configuration of the AddonConfigs to the main repo

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#5499]
**What would you like to be added? / User Story**:
The configs with logos etc. should be deployed with the application in all environments. Currently we keep the config for node-exporter in the infra repo which makes it private only for us.

**Comment by maciaszczykm** [comment]
Current location: https://github.com/kubermatic/infra/blob/master/seeds/dev.kubermatic.io/addonconfigs.yaml

Docs: https://docs.kubermatic.com/kubermatic/v2.13/advanced/addons/

**Comment by maciaszczykm** [comment]
It should be possible to override this config if anyone wants to.

**Comment by maciaszczykm** [comment]
I have done some investigation of it and also discussed it with @xrstf on Slack and it seems to me that we should discuss it further before we decide what to do next. I would like to avoid taking any decisions here as I am not 100% aware of how currently we are handling the installation of Kubermatic, especially since we are using the Kubermatic Operator which is our new solution. It would be perfect if the cluster-lifecycle team could join the discussion and move it further. If it can be done without modifying the operator I could do it on my own, but otherwise, I'd rather discuss it here and avoid breaking anything.

Few more things from the discussion on Slack:
1. The configuration has to be shipped to the user, especially for the addons that are common like node-exporter. Without config, the user would see only the name of the addon in the UI. The configuration provides a logo, description, and optionally form configuration.
1. Perhaps we can ship the configuration files to the customer without putting them in the Kubermatic Operator so the user that will be installing Kubermatic can decide which AddonConfigs he wants to include in his installation. He can edit them before and adjust to his needs. This adds one more manual step but it makes the configuration more visible to the user.
1. At some point, we should make AddonConfigs namespaced. To do this we would also need to update the API. It should not be a big problem, we just have to synchronize it.

**Comment by maciaszczykm** [comment]
cc @kdomanski for prioritization. This change was requested by @scheeles.

**Comment by zreigz** [comment]
cc @xrstf any update?
