### ISSUE TITLE
support Huawei CCM

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#5511]
OpenTelekom Cloud is an OpenStack-based IaaS. A dedicated [Kubernetes CCM](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud) is provided.

The goal of this task is to install this CCM when OpenTelekom Cloud is in the picture. Part of this task is to define how to distinguish between OpenStack and OpenTelekom Cloud.

The goal of this task is to deploy the HuaweiCloud CCM instead of the OpenStack CCM when OTC provider is used, this will enable to use LBs.

**Comment by irozzo-1A** [comment]
Once the OTC provider has been introduced the CCM could be deployed by the `seed-controller-manager` similarly to what is done today for openstack:
https://github.com/kubermatic/kubermatic/blob/821208f/pkg/resources/cloudcontroller/deployment.go#L29
