### ISSUE TITLE
Cannot install addons

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#5528]
After trying to install addons in the newly created cluster following errors appear in the events:

![image](https://user-images.githubusercontent.com/2823399/84905958-a3153f00-b0b1-11ea-957e-927e1fdd067e.png)

Error comes from addon controller: https://github.com/kubermatic/kubermatic/blob/d600952a16449a351498a3a5e9bb491ac4a55d98/api/pkg/controller/seed-controller-manager/addon/addon_controller.go#L276

**Comment by maciaszczykm** [comment]
cc @kdomanski for prioritization.

**Comment by toschneck** [comment]
Addon Creataion is fully broken, for all clusters:
As a customer view, urgent to fix. @kdomanski please prio it.
![Peek 2020-07-08 14-47.gif](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/d3b797b0-b06e-4523-85d8-fe61aeac649c)

**Comment by toschneck** [comment]
on a other enironment I got:
`failed to reconcile Addon "node-exporter": failed to ensure that the cleanup finalizer existis on the addon: addons.kubermatic.k8s.io "node-exporter" not found`
