### ISSUE TITLE
Rename kubermatic CRD

### ISSUE THREAD

**Issue by lbb** [kubermatic/kubermatic#554]
Currently our crd's name is `s:cluster` `p:clusters` which collides with the kubernetes resource name for federation.

**Comment by mrIncompetent** [comment]
How does it collide? As resources are in groups, they shouldn't or?

**Comment by mrIncompetent** [comment]
@realfake ?

**Comment by lbb** [comment]
Yes only with kubectl, you can write v1beta1…/cluster or kubermatic…./cluster but it currently is not very explicit.

**Comment by mrIncompetent** [comment]
So does this cause an error or not?

If not, i don't see a point in renaming our CRD.
This is one of the advantages of API groups in k8s.

@realfake

**Comment by mrIncompetent** [comment]
@realfake ?

**Comment by lbb** [comment]
No it should not, but I might be a bit confusing 🙃

**Comment by mrIncompetent** [comment]
Closed since this is not necessary at all.
