### ISSUE TITLE
etcd launcher image location should be dynamically configurable

### ISSUE THREAD

**Issue by multi-io** [kubermatic/kubermatic#5549]
**User Story**

Currently the deployed etcd launcher statefulset's image is harcoded to `quay.io/kubermatic/etcd-launcher-v3[34]:${KUBERMATICCOMMIT}`. This should be user-settable via the controller-manager command line, just like it is for the kubermatic api and dnatcontroller images.

**Acceptance criteria**

* [ ] image location (the part up to baseTag, i.e. "quay.io/kubermatic/etcd-launcher-" by default) can be configured via command-line parameters
* [ ] `--overwrite-registry=...` command-line parameter, if given, should be honoured

**Comment by moelsayed** [comment]
This is already implemented in #5710. Closing.
