### ISSUE TITLE
Add support to provide own certificates for ingresses

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5554]
**User Story**

Kubermatic 2.14 moved the creation of certificate resources from a dedicated Helm chart to the Kubermatic and IAP charts. This makes the affected charts relying on the cert-manager CRDs. Some on-premise installations use an internal CA since their ingresses are not exposed to the public internet.

With Kubermatic 2.13 or older, a simple workaround for such environments was skipping the installation for cert-manager and the certificates chart. Afterwards an own certificate could be deployed to the `default/kubermatic-tls-certificates` secret, which was configured as default certificate for the ingress controller.

Since the ingress controller Helm chart has a `.Values.nginx.extraArgs` parameter, setting a default certificate is easily possible. However, the dependency of the cert-manager CRDs make it impossible to run Kubermatic without cert-manager.

**Acceptance criteria**

The minimal solution would be to allow deploying Kubermatic without creating certificate resources. In best case also a custom certificate could be installed via Helm charts. However, I see the difficulty that some customers will use a wildcard certificate (which has to be deployed as a default certificate for the ingress controller), other will use an individual certificate per ingress resource.

**Comment by xrstf** [comment]
cert-manager/Velero CRD handling is soon (#5552) allowing/requiring users to install the CRDs themselves, without Helm. Does that not "solve" the problem? Just install the CRDs, but not the cert-manager chart.

**Comment by chrkl** [comment]
Would be nicer to do not have to install unused CRDs at all, but at least a small improvement.

**Comment by chrkl** [comment]
How about using the `cert-manager.io/cluster-issuer` annotation instead of explicitly creating `certificate` resources? We would get rid of the cert-manager dependency in the Kubermatic chart by this.

**Comment by irozzo-1A** [comment]
> How about using the `cert-manager.io/cluster-issuer` annotation instead of explicitly creating `certificate` resources? We would get rid of the cert-manager dependency in the Kubermatic chart by this.

I also agree this would be cleaner https://cert-manager.io/docs/usage/ingress/
