### ISSUE TITLE
demo platform is "offline" invalid cert and 404

### ISSUE THREAD

**Issue by xinity** [kubermatic/kubermatic#5567]
The official documentation: https://docs.kubermatic.com/kubermatic/v2.14/getting_started/create_cluster/
refers to: https://cloud.kubermatic.io/ to access a demo of kubermatic.

connecting to this URL today, lead to an invalid certificate error and even if you pass through, you get a 404 error.

easy to fix I'm sure, I just wanted to let you know :)

**Comment by toschneck** [comment]
cloud.kubermatic.io is not active anymore, we will soon release some doc how you could setup the open source kubermatic version by yourself. Otherwise you could write to sales@kubermatic.com  and we can offer some access to a demo system.

**Comment by xinity** [comment]
@toschneck got it, I'll wait for the DIY documentation then :)
Let me know

**Comment by kdomanski** [comment]
I've removed the mention of the old demo instance from the docs. We don't have a publicly available demonstration environment at this time.
