### ISSUE TITLE
Provide Programmatic Etcd Backup initiation for the Controller Manager

### ISSUE THREAD

**Issue by multi-io** [kubermatic/kubermatic#5570]
**User Story**

As one building block for etcd backup, restore and migrations, the Kubermatic controller manager must be able to initiate backups of a user cluster's etcd storage to S3 or another long-term storage backend.

**Acceptance criteria**

* [x] there is an internal API in the controller manager that can initiate a backup of a user cluster's etcd storage, track the progress of a running backup, and list existing backups

* [x] the backups are uploaded to S3 by default

* [ ] Kubermatic admins should be able to configure (at Kubermatic installation time) a different storage other than S3

**Comment by moelsayed** [comment]
This is partially implemented in #5668. The support for additional backup backend will be tracked in a different issue.
