### ISSUE TITLE
Delete seed param from the endpoints

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#5581]
**User Story** It seems that seed param (`/dc/*`) is not required in multiple endpoints. Datacenter names have to be globally unique and they can be retrieved from cluster CRD, seeds can be retrieved from datacenter CRD. It will simplify the UI code a lot too.

**Acceptance criteria**
- [ ] seed param is removed from possible endpoints
- [ ] v2.15 should contain both type of endpoints (those with seed and those without), we can remove them after the release

cc @kubermatic/ui-team

**Comment by shaase-ctrl** [comment]
Can we close this one?

**Comment by maciaszczykm** [comment]
I think so. Last time I've checked all of these were done besides deprecated ones. @zreigz has a day off today, but if there is something more to do he can reopen.
