### ISSUE TITLE
Automated & Tested Kubermatic Upgrades

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5582]
**User Story**
Upgrades are often very sensitive (e.g. CNI upgrade) and manual tests don't scale well, take lot of time of resources. The goal of this story is to put in place automated upgrade test.

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/5582).

**Acceptance criteria**
Having upgrade tests in place. They don't have to be run necessarily at each PR, as they could take time and resources, but scheduled on a regular basis (e.g. daily, weekly) and/or on-demand.

**Comment by xmudrii** [comment]
This issue is blocked until we don't have the Kubermatic Installer in the place.

**Comment by xrstf** [comment]
I think we were talking about different things here (guessing based on the "CNI upgrade" comment).

The upgrade tests I was thinking of and Marko is referring to from our last discussion is for upgrading Kubermatic itself. But this does not involve upgrading any CNI, only Helm charts.

Are you @irozzo-1A talking about updating user clusters from one Kubernetes version to another?

**Comment by irozzo-1A** [comment]
@xrstf I'm talking about k8c upgrades, they can have side effects on user clusters also e.g. upgrading from 2.11 to 2.12 triggered a Canal upgrade that caused issues to clusters using `NetworkPolicies`. I admit that catching this kind of scenarios would require a fairly complicated test.

See: https://docs.kubermatic.com/kubermatic/v2.15/upgrading/2.11_to_2.12/
