### ISSUE TITLE
Migrate CNI from Canal

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5589]
**User Story**
We are currently using [canal](https://docs.projectcalico.org/getting-started/kubernetes/flannel/flannel) as CNI for user clusters for historical reasons. Calico fully supports VXLAN networking, migrating to calico for both networking and policy enforcement would have some benefits:
- Actively developed with respect to flannel
- Additional features, and better scaling (supposedly :-))
- Multi-arch images (flannel multi-arch images are not shipped)

**Acceptance criteria**

- Calico in VXLAN mode is installed in user clusters instead of Canal

- Having a proper migration path for existing user clusters

**Comment by irozzo-1A** [comment]
> Multi-arch images (flannel multi-arch images are not shipped)

This assumption was coming from #2856 but does not seem to be relevant any longer.

In addition, we should probably consider Cilium as an alternative.

**Comment by almereyda** [comment]
Is there some progress on the matter that is visible from the public?

**Comment by rastislavs** [comment]
Cilium CNI is going to be integrated as part of https://github.com/kubermatic/kubermatic/issues/7577
