### ISSUE TITLE
Print/Deliver copyright notice

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#559]
We need to print out every package we use & the appropriate license of it.

Idea:
Generate a go file containing all package names & licenses as strings (or map).
Declare 1 function to print out all package names & licenses.

For getting the used packages & licenses i recommend using: https://github.com/frapposelli/wwhrd/blob/master/walker.go

If the tool cannot detect a license (like with `github.com/howeyc/gopass`) i would recommend creating a file before containing that license.

Any other ideas?
@realfake @guusvw @metalmatze @scheeles

**Comment by guusvw** [comment]
There filewalker looks a little bit strange and this approach only covers vendored files.
The `go` cli can pretty easy list all dependencies with `go list -f '{{ join .Deps "\n" }}'`, based on this list we can check the license files, no matter if it's vendored or not.

**Comment by mrIncompetent** [comment]
Do we need to care about non-vendored code?
We could also parse the `Gopkg.lock`
@guusvw Your command does only output the following when executed in github.com/kubermatic/kubermatic/api:
```
errors
runtime
runtime/internal/atomic
runtime/internal/sys
unsafe
```

**Comment by scheeles** [comment]
What about this tool https://github.com/pmezard/licenses

**Comment by kdomanski** [comment]
@mrIncompetent ping

**Comment by kdomanski** [comment]
@mrIncompetent The issue name is referring to copyright notice, the text of the issue is referring to list of packages and licenses. Please clarify which of these two roughly separate objectives we want to achieve here and why.

I bet that it's about fulfilling the legal obligation of authorship attribution, but that's actual work with no clever tool to do it, so the ticket drifted away towards a useless related topic.

**Comment by mrIncompetent** [comment]
It's about listing the open source libraries we use + the licenses of those libraries.
That should cover most of the legal requirements for using open source libraries?

**Comment by alvaroaleman** [comment]
Needs more details, e.G. what information exactly has to be redistributed and how (in our docs? In the UI?)

**Comment by kdomanski** [comment]
Related: kubernetes/kubernetes#44505
