### ISSUE TITLE
DC not found when trying to use OTC

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubermatic#5607]
**User Story**
![image](https://user-images.githubusercontent.com/993296/86602427-e83adb80-bfa2-11ea-9e26-9b9ff2068c60.png)

I'm trying to create a cluster on OTC. It fails both using a preset and using manual credentials, claiming that the datacenter does not exist. However the datacenter does definitely exist, since I was able to select it on the previous screen.

**Comment by kgroschoff** [comment]
@kdomanski 
Openstack I guess?
Where did you get this error? I couldn't reproduce it on dev 🤔

**Comment by lsviben** [comment]
I see that the `otc-eu-de` has the email filtering set:
```       
requiredEmailDomains:
          - loodse.com
```
if your user is not from that domain, the error should be expected. But still you should not be able to see it in the previous screen.

EDIT: additional info - unless you are the admin, then the email filtering is skipped.

**Comment by kgroschoff** [comment]
Good hint, @lsviben 
I can confirm that @kdomanski is an admin without loodse address :D

**Comment by kdomanski** [comment]
Bingo, thanks @lsviben

**Comment by kgroschoff** [comment]
Also tested it with my private account. There I couldn't even see the otc datacenter, which is intended from what I've read 👍

**Comment by kdomanski** [comment]
We're going to have a talk to determine whether admins should be able to access DCs where they are filtered by domain and then make the behavior consistent.

**Comment by kdomanski** [comment]
We've decided that administrators should be able to see and use all DCs, regardless of usual domain restrictions.
