### ISSUE TITLE
DisableAutoUpdate ignored when creating ND

### ISSUE THREAD

**Issue by floreks** [kubermatic/kubermatic#5653]
### Request
![Zrzut ekranu z 2020-07-14 13-28-46](https://user-images.githubusercontent.com/2285385/87420774-26a14d80-c5d6-11ea-9e0e-587588f6f623.png)

### Response
![Zrzut ekranu z 2020-07-14 13-29-00](https://user-images.githubusercontent.com/2285385/87420772-24d78a00-c5d6-11ea-8796-8608de9a1912.png)

**Comment by zreigz** [comment]
The `containerLinux` is depricated, we support those OS:
```
	OperatingSystemCoreos  OperatingSystem = "coreos"
	OperatingSystemUbuntu  OperatingSystem = "ubuntu"
	OperatingSystemCentOS  OperatingSystem = "centos"
	OperatingSystemSLES    OperatingSystem = "sles"
	OperatingSystemRHEL    OperatingSystem = "rhel"
	OperatingSystemFlatcar OperatingSystem = "flatcar"
```
