### ISSUE TITLE
componentsOverride settings spill into other clusters

### ISSUE THREAD

**Issue by multi-io** [kubermatic/kubermatic#5654]
# Overview

We're seeing a problem here where setting the `componentsOverride` (e.g. for prometheus or etcd) on one cluster will “spill over” to the other clusters, i.e. the same overrides are then set not just on that one cluster but on all clusters eventually, causing all their prometheus/etcd pods to be recreated. Even worse, if you set `componentsOverride` on more than one cluster (and to different values on each), then those different will stomp over each other on the clusters with no overrides set, i.e. their prometheus/etcd statefulsets will be modified constantly.

Please note that the componentsOverrides do not "spill" into the other cluster resources themselves, i.e. their `componentsOverride` fields aren't modified. Only their respective control plane components are updated as if the `componentsOverride` had been set on the cluster resource.

It looks like the clusters that have `componentsOverride` set themselves are not affected by this, i.e. their statefulsets get the correct overridden settings and then aren't updated anymore afterwards. Just the clusters with no overrides set will be updated erroneously.

We think the problem was introduced with 2.13, possibly with the clustercomponent_defaulter controller (not sure yet). I initially thought it may be just in our fork, but I could just reproduce it with with the seed-controller-manager I’m using for etcd development, which is basically the upstream master just with the new etcd launcher and backup controller (which I don't think have any relation to the problem). So I’m pretty certain now it’s an upstream problem.

# Reproduction

Just set e.g. `componentsOverride.prometheus.resources.limits/requests` for one cluster, restart the seed-controller-manager, and watch prometheus statefulsets and pods eventually updated/recreated in all cluster control planes, not just the one where you set the override.

**Comment by xrstf** [comment]
Can reproduce. No need to restart the seed-controller-manager even.

**Comment by xrstf** [comment]
I updated the componentsOverride in `7528bstngf` and got this log from the seed-controller-manager (first two lines are expected, then suddenly weirdness):

```
I0722 23:07:57.817701       1 ensure.go:139] Updated *v1.StatefulSet prometheus in Namespace "cluster-7528bstngf"
I0722 23:07:57.825973       1 ensure.go:139] Updated *v1beta2.VerticalPodAutoscaler prometheus in Namespace "cluster-7528bstngf"
I0722 23:08:10.797492       1 ensure.go:139] Updated *v1.StatefulSet prometheus in Namespace "cluster-svnhfb4bfc"
I0722 23:08:10.856678       1 ensure.go:139] Updated *v1.StatefulSet prometheus in Namespace "cluster-cn6qnl4b85"
I0722 23:08:10.955919       1 ensure.go:139] Updated *v1beta2.VerticalPodAutoscaler prometheus in Namespace "cluster-svnhfb4bfc"
I0722 23:08:10.975545       1 ensure.go:139] Updated *v1beta2.VerticalPodAutoscaler prometheus in Namespace "cluster-cn6qnl4b85"
I0722 23:08:11.055361       1 ensure.go:139] Updated *v1.StatefulSet prometheus in Namespace "cluster-8s6x4s95n4"
I0722 23:08:11.162614       1 ensure.go:139] Updated *v1beta2.VerticalPodAutoscaler prometheus in Namespace "cluster-8s6x4s95n4"
I0722 23:08:11.762156       1 ensure.go:139] Updated *v1.StatefulSet prometheus in Namespace "cluster-dvzr8ms276"
I0722 23:08:11.949919       1 ensure.go:139] Updated *v1beta2.VerticalPodAutoscaler prometheus in Namespace "cluster-dvzr8ms276"
```

**Comment by xrstf** [comment]
I think I found the issue. When reconciling e.g. the Prometheus StatefulSet, we call `resources.SetResourceRequirements()`: https://github.com/kubermatic/kubermatic/blob/master/pkg/resources/resources.go#L944

This function gets handed a map with the default requirements, then proceeds to update said map and then apply the values to the containers. Unfortunately this just modified the defaults for all future reconciles of that StatefulSet, until the next one with different overrides comes around.

Fix should be as simple as cloning the map somewhere.
