### ISSUE TITLE
Sensitive auth data should be stored securely

### ISSUE THREAD

**Issue by floreks** [kubermatic/kubermatic#5679]
Currently, all `kubeconfig` files (potentially even more auth info) used to connect to the user/seed clusters are stored in secrets as a plain text. Therefore, they are available for any Kubernetes user that has access to the seed cluster secrets. With import cluster feature that becomes even more dangerous as more 'kubeconfig' files that potentially grant full access to production clusters will be stored.

We should use some kind of encryption mechanism before storing sensitive data so that only api/controllers can actually decrypt and read those files.

**Comment by shaase-ctrl** [comment]
Originally this epic was planned for KKP, but it includes the issues for KubeOne. We will close this one successfully and open another for KKP.
