### ISSUE TITLE
Import Kubernetes cluster

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#5687]
**User Story**
Import external Kubernetes cluster. The Kubermatic should import the existing k8s cluster from kubeconfig. 
New ImportedCluster object holds a reference to the kubeconfig. The API can retrieve the cluster details and transform to API cluster structure to display in the dashboard.

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/5687).

**Comment by xrstf** [comment]
> The Kubermatic should import the existing k8s cluster from kubeconfig.

What does this mean? What exactly are we importing? Are we copying etcd volumes into our cluster?

> The API can retrieve the cluster details and transform to API cluster structure to display in the dashboard.

Isn't this what we did with the BringYourOwn / kubeadm clusters?

> New ImportedCluster object holds a reference to the kubeconfig.

What about calling the CRD "ExternalCluster"? "ImportedCluster" to me reads like "this cluster *was* somewhere else, but now it runs inside Kubermatic". Or is this what we want to do?
