### ISSUE TITLE
KubermaticOperator CE requires an image pull secret

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5694]
**User Story**
KubermaticOperator requires an image pull secret to be specified in the `KubermaticConfiguration` manifest even when CommunityEdition is used (it is allowed to be empty though), where all platform images are public.

This is the error thrown by the operator when no `imagePullSecret` is specified in `KubermaticConfiguration` spec:
```
{"level":"error","time":"2020-09-15T19:00:07.503Z","logger":"controller","caller":"controller/controller.go:209","msg":"Reconciler error","controller":"kubermatic-master-operator","name":"kubermatic","namespace":"kubermatic","error":"failed to reconcile Secrets: failed to ensure Secret kubermatic/dockercfg: failed to create *v1.Secret 'kubermatic/dockercfg': Secret \"dockercfg\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": unexpected end of JSON input"}
```

**Acceptance criteria**
KubermaticOperator do not fail if no image pull secret is provided (CE only).

**Comment by kdomanski** [comment]
cc @xrstf
