### ISSUE TITLE
Move away from hyperkube image

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5717]
**User Story**

Hyperkube image is now deprecated and [community maintained](https://github.com/kubernetes/kubernetes/issues/81760), and individual images are shipped for `apiserver`, `controller-manager`, `scheduler` instead.

https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-apiserver-amd64
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-scheduler-amd64
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-controller-manager-amd64

The goal of this task is to stop using `hyperkube` image for each of the aforementioned components and use the official instead.

**Acceptance criteria**

Hyperkube image is not used in Kubermatic. *Note that* kubelet is out of scope as it is controlled by [machine-controller](https://github.com/kubermatic/machine-controller).

**Comment by xmudrii** [comment]
I'd just add a note that we shouldn't use the `gcr.io/google-containers` images directly. Kubernetes has recently switched to the community-owned project and bucket (`{asia,eu,us}.gcr.io/k8s-artifacts-prod`). It's recommended to use `k8s.gcr.io` image URLs (e.g. `k8s.gcr.io/apiserver`), as they point to the correct repository.

**Comment by irozzo-1A** [comment]
This is a blocker for Kubernetes 1.19 integration, where neither official nor community maintained Hyperkube images will be shipped. Do you confirm @xmudrii ?

**Comment by xmudrii** [comment]
Yes, that's right. There will be no Hyperkube image in the 1.19 release.

**Comment by xmudrii** [comment]
In #5758, we have migrated away from Hyperkube for Kubernetes clusters. We need to consider should we do it for OpenShift as well, and I've created another issue for that: #5801

/close
closing in favor of #5801

**Comment by kron4eg** [comment]
> In #5773, we have migrated away from Hyperkube for Kubernetes clusters. We need to consider should we do it for OpenShift as well, and I've created another issue for that: #5801
> 
> /close
> closing in favor of #5801

Amendment: In #5758, we have migrated away from Hyperkube for Kubernetes clusters.

**Comment by xmudrii** [comment]
@kron4eg Updated the comment.
