### ISSUE TITLE
Implement Prometheus Federation for seed-clusters

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#572]
Every seed cluster gets is own prometheus (managed by prometheus operator) but we'll have 1 master seed-cluster where we gather all data from ever seed-cluster prometheus

**Comment by metalmatze** [comment]
I would like to implement something like this in December.
Where would be run the Prometheus that gathers all data?

**Comment by mrIncompetent** [comment]
No, need to happen in November. You have 9 hours left.

To have this clear, per Kubermatic-setup we have 1 master, that master hosts the master-prometheus wich gathers the data from all other prom's (from the other seed-clusters)

**Comment by metalmatze** [comment]
Yes. But it still doesn't answer where we run the Prometheus that scrapes the other Prometheus?

**Comment by metalmatze** [comment]
This is still blocked by:
https://github.com/coreos/prometheus-operator/pull/1100

Once the Operator supports this static targets in its ServiceMonitor we can easily setup an Prometheus which scrapes all our datacentes via federation.

**Comment by metalmatze** [comment]
This can be closed as we now have this global Prometheus running on cloud. See the PR on the infra repo.
