### ISSUE TITLE
[vSphere] Add UI support for Datastore and DatastoreCluster

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5721]
**User Story**
[Here](https://github.com/kubermatic/kubermatic/pull/5399) we introduced support for specifying vSphere `Datastore` or `DatastoreCluster` to be used for storing VMs at cluster level. The UI should be updated to give the possibility to specify them during user-cluster creation. 

**Acceptance criteria**
When creating a user cluster on vSphere the Settings form should present input fields for Datastore and DatastoreCluster, they should be mutually exclusive.

**Comment by zreigz** [comment]
moved to Dashboard: https://app.zenhub.com/workspaces/all-kubermatic-58863654794153994b62af76/issues/kubermatic/dashboard/2611
