### ISSUE TITLE
Fork HuaweiCloud CCM and fix authentication issue with OTC

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5735]
The goal of this issue is to fork [HuaweiCloud CCM](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/) to fix an authentication issue due to an API version mismatch between HuaweiCloud and OTC. 

Find below more details about this issue:
https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/issues/76

**Comment by xrstf** [comment]
https://github.com/opentelekomcloud/cloud-provider-opentelekomcloud this now exists.
