### ISSUE TITLE
Introduce new OTC provider in Kubermatic

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5736]
**User Story**
[Open Telekom Cloud](https://open-telekom-cloud.com/en) is a cloud provider base on [HuaweiCloud](https://cloud.huawei.com/) which in turn is based on Openstack with some API extensions/suppressions.

The main reason why we decided to have a dedicated provider is that LB API is not Openstack compatible (i.e. neutron/octavia LBaaS), the Kubernetes clusters using OTC cannot use Openstack CCM, but need to use a dedicated one that requires a different configuration.
This will also give us the possibility to use a dedicated SDK in future, but for the moment the idea is to share as much as we can code between `Openstack` and `OTC` providers.

Why not having a more generic `HuaweiCloud` provider? OTC is using an API version that is not aligned with respect to latest `HuaweiCloud` platform, thus there are some specificities that should be handled (e.g. https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/issues/76), and this also allow to have a simpler configuration as some values can be hardcoded (e.g. OTC API endpoints) 

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/5736).

**Acceptance criteria**
We have support for OTC provider in Kubermatic Kubernetes Platform.

**Comment by xmudrii** [comment]
At the moment, we didn't decide to use Huawei CCM. If this changes, we'll reopen the issue.
/close
