### ISSUE TITLE
Make dnsPolicy and dnsConfig configurable for KubeVirt datacenter

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5762]
**User Story**

KubeVirt MachineDeployments allow to set a dnsPolicy and dnsConfig: https://github.com/kubermatic/machine-controller/pull/747

Make this configurable per datacenter to avoid manually editing the MachineDeployment after creating a cluster.

**Acceptance criteria**

Cluster creation with the requirement of datacenter specific DNS settings should be possible without touching the MachineDeployments.

**Comment by moadqassem** [comment]
@chrkl IIRC this issue was addressed in this PR: 
https://github.com/kubermatic/kubermatic/pull/6129

**Comment by chrkl** [comment]
Yes, #6129 seems to fix this
