### ISSUE TITLE
image_loader fails to pull all images

### ISSUE THREAD

**Issue by nico-netminded** [kubermatic/kubermatic#5792]
**User Story**
We are trying to install kubermatic in a complete offline environment. I've compiled the image_tool from v2.14.4 and it starts downloading the required docker images, but stops with this error message:

{"level":"error","time":"2020-08-26T22:27:27.461+0200","caller":"docker/docker.go:42","msg":"Command failed","image":"quay.io/kubermatic/kubeletdnat-controller:","command":"docker pull quay.io/kubermatic/kubeletdnat-controller:","output":"invalid reference format\n"}
{"level":"fatal","time":"2020-08-26T22:27:27.461+0200","caller":"image-loader/main.go:134","msg":"Failed to process images","error":"failed to download all images: failed to download quay.io/kubermatic/kubeletdnat-controller:: failed to pull image quay.io/kubermatic/kubeletdnat-controller:: exit status 1"}

Looks like it tries to download an image without a tag, but fails.

**Acceptance criteria**

**Comment by xrstf** [comment]
@nico-netminded Can you show _how_ you compiled the image-loader? Did you just `go build` it or use the Makefile? No image tags on the Docker image seems to imply that `resources.KUBERMATICCOMMIT` is not set, which should be if you used the Makefile.
