### ISSUE TITLE
[OpenStack] Migration path for existing user clusters to external CCM and CSI

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5799]
**User Story**
User clusters created with KKP having version => 1.15 make use of out-of-tree CCM/CSI, but existing user clusters still using in-tree cloud provider are not migrated automatically. The goal of this issue is to implement a migration path for such clusters. 

**Acceptance criteria**
A cluster administrator is enabled to migrate a user cluster from in-tree cloud provider to out of tree CCM/CSI with a documented (and possibly automated) procedure.

**Comment by xmudrii** [comment]
#6592 got closed, so I'll be closing this issue as well.
/close
