### ISSUE TITLE
Implement Envoy LB for the new expose strategy

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#5804]
**User Story**
The goal of this issue is to implement the Envoy SNI LB for the new expose strategy. We will enhance the existing Nodeport-proxy. 

We are dealing with two types of traffic. The bootstrap one for the Kubelet and the rest.
Regarding the Kubelet traffic going to the APIServer of the Control Plane, we need to load balance the traffic hitting the Seed cluster to the right control plane.
This can be done using SNI as the traffic from the Kubelet to initiate the bootstrap process is using HTTPS and SNI.
We will be implementing this part on the seed by using Envoy as a generic ingress controller that will send the traffic to the right control plane.
Moreover, the Ingress Controller needs to support TLS passthrough. This is to prevent another of certificates management and have a "transparent" load balancing that doesn't terminate the TLS connection between the User cluster and the Seed cluster.
The Seed Controller Manager will take care of the provisioning and the lifecycle of this component.

**Acceptance criteria**
Envoy is deployed and is able to load balance TLS traffic using SNI and without termination to the right Control Plane.

**Comment by irozzo-1A** [comment]
This is implemented.
