### ISSUE TITLE
Implement Envoy Proxy for the new expose strategy

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#5805]
**User Story**
The goal of this issue is to implement the Envoy proxy on the Seed side for the new expose strategy. We will enhance the existing Nodeport-proxy. 

As mentioned in the #5804  we are dealing with two types of traffic. The bootstrap one for the Kubelet and the rest.
Regarding the Pods traffic going to the APIServer, but also the Kubelet traffic (after the bootstrap process) those are not using SNI and will be tunneled from the User cluster to the Seed cluster.
The LB will be done using HTTP2.0 Authority header. Envoy will be deployed on the Seed side.
Configuration of the Envoy will be managed using GO Api.
This will be using the same Envoy deployment as in #5804

**Acceptance criteria**
Envoy is deployed and is routing the tunneled traffic to the right control plane.

**Comment by irozzo-1A** [comment]
The nodeport proxy should now be able to handle both SNI and HTTP/2 CONNECT traffic.
