### ISSUE TITLE
Update the Kubermatic Operator to take into account the new expose strategy

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#5806]
**User Story**
The goal of this issue is to implement the logic to install the components.

We are moving to the Kubermatic Operator installation process.
Thus for the new Expose strategy, this will be the preferred choice to install the components on the Seed cluster.

No Helm charts will be used.

**Acceptance criteria**
Install all the required components

**Comment by irozzo-1A** [comment]
As we decided to extend the nodeport proxy the operator has no additional components to deploy. It should just enable the SNI and tunneling entrypoints. This was done in #6235.
