### ISSUE TITLE
Create an agent on the User cluster for the new expose strategy

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#5810]
**User Story**
The goal of this issue to have an agent (Envoy) running on the User cluster side.

The agent will include an Envoy container that will be configured statically by means of a ConfigMap. It will be configured as TCP proxy with two listeners: one for the KAS, the other for OpenVPN server. The cluster will be configured to use the DNS entry pointing to the nodeport proxy.

The `user-controller-manager` should apply the agent manifests to the user cluster (DaemonSet, ConfigMap).

The ports used by the agent for KAS and OpenVPN server should be configurable.
 
**Acceptance criteria**
Agents are deployed on each node, tunneling the TCP requests using HTTP2 to the right target.

**Comment by irozzo-1A** [comment]
Implemented by #6445
