### ISSUE TITLE
User cluster upgrade fails on Google Cloud

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5837]
**User Story**

When trying to upgrade a user cluster on Google Cloud, the UI shows the following error:

`Error 400: invalid cluster: invalid cloud spec: serviceAccount cannot be empty`

Cluster is not upgraded.

Tested on 2.14.2 and master.

**Acceptance criteria**

Cluster upgrade should work.

**Comment by xrstf** [comment]
What version did you upgrade from/to? Anything more we should know?

**Comment by chrkl** [comment]
On the run environment (2.14.2), I see the issue when trying to upgrade from 1.17.9 to 1.18.6. I cannot reproduce it anymore on the dev environment.
