### ISSUE TITLE
Migration Path for Legacy Installations

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#5845]
This issue describes the possible migration paths for legacy Kubermatic setups. "Legacy" in this sense means the following:

- Manually installed `kubermatic` Helm chart using Helm 2.
- Manually installed `kubermatic-operator` Helm chart using Helm 2.

Our Helm charts only reached proper Helm 3 support with v2.15, so this issue does not target these custom installations. if the migration works out for Helm 3, great, but Helm 2 is definitly the priority.

The operator also deprecated the `nodeport-proxy` Helm chart, so it must be removed from all seeds and replaced with the new proxies.

Besides the way Kubermatic is installed, we also need to migrate the following:

* the `datacenters.yaml` is now represented as `Seed` custom resources
* the Helm `values.yaml` has been significantly altered for the `KubermaticConfiguration` CRD, assistance in automatically converting it would be a very-very-nice-to-have
* `cert-manager`, `oauth` and `nginx-ingress-controller` need to be installed using Helm 3 (see below for reasoning why)

## Goal

We want all installations to be managed with the Kubermatic Operator and Helm 3. As the Kubermatic Installer is only in beta yet, we do not plan on forcefully migrating everyone to use it yet, *but* the migration will lead an installation in a state where the installer can then pick it up later when it has matured more (e.g. in Kubermatic v2.16).

As the installer always uses Helm 3, and we want to be able to pick up the installation once the installer is polished, we also need to migrate `cert-manager`, `oauth` and `nginx-ingress-controller` to Helm 3.

The `datacenters.yaml` is not used anymore.

The Installer shall automate the migration as good as it can, but because it's beta we need to keep manual upgrades in mind.

It's acceptable to have a short interruption in cluster reconciling work, which is kind of unavoidable.

It's *not* acceptable to change the main LoadBalancer (nginx-ingress-controller) in a way that could lead to IP changes, bringing down the dashboard and other services (Prometheus, Grafana, ...).

## Migration: `datacenters.yaml`

=> https://github.com/kubermatic/kubermatic/issues/5848

This should be easy to accomplish. We have/had migration code for datacenters to Seeds already, so it's just a matter of wrapping it up in a nice subcommand of the installer and implement `./installer migrate <datacenters.yaml >seeds.yaml`. offering a conversion as a standalone CLI command makes it much easier to the user to review the changes before they apply them.

The created Seed YAML files can then be applied before the operator is installed, so that the new controllers will pick it up and not need the datacenters.yaml anymore.

## Migration: `KubermaticConfiguration`

=> https://github.com/kubermatic/kubermatic/issues/5849

This can also be automated, in a similar fashion to the `datacenters.yaml`.

## Migration: `kubermatic` Chart (Master Cluster)

I see two possible options: An in-place, fragile upgrade or a clean re-install with somewhat longer downtime (including the dashboard).

### Clean Install

As Helm never touches CRDs and we always installed CRDs for Kubermatic manually (compared to some other charts, which only recently were migrated to manual CRD management), it's possible to simply delete the `kubermatic` chart and then install the `kubermatic-operator` chart. `Cluster` and related objects will remain intact.

*Pro:*

- Clean and easy
- Works even if the `kubermatic` chart was installed using Helm 3

*Con:*

- Dashboard is down

### In-Place Upgrade

To minimize downtime, it's also possible to first install the `kubermatic-operator` chart and applying the `KubermaticConfiguration`. This will merge both Helm charts into the same namespace and the Operator will take over a few resources.

A `kubermatic`-based installation looks like this:

```
NAME                                    READY   STATUS    RESTARTS   AGE
controller-manager-v1-689fc5fb4-t8xj2   1/1     Running   0          7m8s
kubermatic-api-v1-66644b4bf6-n68r5      1/1     Running   0          131m
kubermatic-api-v1-66644b4bf6-q86fw      1/1     Running   0          131m
kubermatic-dashboard-675f6ccdf-n9chj    1/1     Running   0          7m9s
kubermatic-dashboard-675f6ccdf-qkhdl    1/1     Running   0          24h
master-controller-v1-6ddc8bdb5d-dl66r   1/1     Running   0          7m9s
tiller-deploy-58df8496c-7chpd           1/1     Running   0          4h40m
tiller-deploy-58df8496c-8zhcx           1/1     Running   0          4h39m
tiller-deploy-58df8496c-d6nq9           1/1     Running   0          4h40m
```

With the operator, it looks like this:

```
NAME                                                    READY   STATUS    RESTARTS   AGE
kubermatic-api-766cc8fb5-dsc27                          1/1     Running   0          6h11m
kubermatic-api-766cc8fb5-kknnf                          1/1     Running   0          6h11m
kubermatic-dashboard-5d784d586b-cxnpl                   1/1     Running   0          5h17m
kubermatic-dashboard-5d784d586b-tt8h2                   1/1     Running   0          7h41m
kubermatic-master-controller-manager-677bf745bc-ksdfc   1/1     Running   0          6h11m
kubermatic-operator-bf7cffc54-srt52                     1/1     Running   0          6h11m
kubermatic-seed-controller-manager-6988794bf5-rzt99     1/1     Running   0          6h10m
```

Only the `kubermatic-dashboard` collides, which is taken over by the Operator and turned into a v2.15 dashboard immediately.

As we take away resources from Helm, a clean Helm deletion is not possible anymore. We would have to manually clean up, i.e. implement a cleanup routine in the Kubermatic Installer.

So the migration plan for this method would be:

1. Delete `kubermatic-api-v1`, `controller-manager-v1` and `master-controller-v1` Deployments and wait for the Pods to be gone.
1. Update Kubermatic CRDs.
1. Apply the `KubermaticConfiguration`, so in the next step the operator can quickly begin doing its work and update the dashboard.
1. Install `kubermatic-operator` chart into `kubermatic` namespace, using Helm 3.
1. Wait for the magic to happen.

At this point the admin must verify that Kubermatic is working fine, before they can continue with the migration by running the installer again and telling it to clean up, i.e. delete all old Kubermatic resources and Helm release metadata.

*Pro:*

- Minimal dashboard downtime
- Works even if the `kubermatic` chart was installed using Helm 3

*Con:*

- Super fragile and impossible to abort in the middle

## Migration: `kubermatic` Chart (Seed Clusters)

With the new operator, there is no need anymore to install any Kubermatic chart onto seed clusters. This however also means that whenever the operator in the master cluster starts up, it will begin to reconcile seeds (install the Seed-Ctrlmgr and the Seed Validation Webhook, mainly). To not have both the old and the new Kubermatic omponents running at the same time in the cluster, admins would have to shut down *everything*, i.e. master and _all_ seed clusters at the same time.

To prevent this global outage, we should extend the Seed CRD to contain a "pause"-like flag. When this flag is set, the operator will not provision the seed cluster (but KKP itself will still see and try to use it). For a short period of time it should then be possible to run with a 2.15 Kubermatic on the master and 2.14 seeds. Then the seeds can be migrated one after another by uninstalling the `kubermatic` chart on the seed and then removing the "pause" flag on the Seed resource.

=> https://github.com/kubermatic/kubermatic/issues/5882

## Migration: `kubermatic-operator` Chart (Master Cluster)

In this case, a migration is only required if the admin used Helm 2 so far. As the operator is not required for Kubermatic to function in production, a migration here would simply involve

1. Delete the chart using Helm 2.
1. Install the chart using Helm 3.

This can be automated by the installer.

## Migration: `nodeport-proxy` Chart (Seed Cluster)

In the old days, admins had to manually install the `nodeport-proxy` chart on every seed cluster. Nowadays the Kubermatic Operator manages the basic provisioning of seeds and therefore also installs the nodeport-proxy.

It's possible for admins to install the Operator, apply the Seed custom resources and then let the operator install the nodeport-proxy. This will then be installed in-parallel to the Helm chart. As the two LoadBalancer services use the same ports, it's possible to transparently switch over DNS to the new nodeport-proxy services (in the `kubermatic` namespace) and later safely remove the old Helm chart.

For the migration we should do the first half and advise the admin to change DNS and then later clean up seeds manually.

## Migration: cert-manager / oauth (Dex)

=> https://github.com/kubermatic/kubermatic/issues/5850

As these charts are not required for Kubermatic to work and a short downtime in Dex is acceptable, a migration for these two Helm chart can be a simple delete+reinstall. Admins can maybe also choose Helm 2to3, but we should probably explore if it works for us for these charts as well.

## Migration: nginx-ingress-controller

=> https://github.com/kubermatic/kubermatic/issues/5850

This chart **must not** be deleted or re-installed, as this would create a new LoadBalancer service and possibly change Kubermatic's IP. Instead we should explore Helm 2to3 to handle this chart.

**Comment by irozzo-1A** [comment]
> This should be easy to accomplish. We have/had migration code for datacenters to Seeds already, so it's just a matter of wrapping it up in a nice subcommand of the installer and implement ./installer migrate <datacenters.yaml >seeds.yaml. offering a conversion as a standalone CLI command makes it much easier to the user to review the changes before they apply them.

Agree with this, I had something similar in mind.
