### ISSUE TITLE
OpenStack certificate signed by internal CA

### ISSUE THREAD

**Issue by balous** [kubermatic/kubermatic#5852]
**User Story**
We've got an internal CA that is used for all internal services including our OpenStack cluster. I try to setup kubermatic to work with this cluster. I see that vsphere has an `allow_insecure` option documented. Is there something similar for openstack?

If not, are there other chances? I could probably rebuild all images with our CA inside and than patch kubermatic binaries to use custom images but this will take much time.

**Comment by irozzo-1A** [comment]
I think that @erdii had a similar use case for vSphere.

**Comment by irozzo-1A** [comment]
@balous Openstack has no flag similar to `allow_insecure` at the moment.

**Comment by toschneck** [comment]
/remove-lifecycle stale support of self-signed CAs at multiple cloud provider is needed

**Comment by xmudrii** [comment]
This seems to be a duplicate of #6181.
/close
