### ISSUE TITLE
Kubermatic Installer: Allow to Skip Charts

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#5859]
**User Story**
It would be nice if the installer allowed to not install certain charts. Why install Dex if an external OIDC solution is used anyway?

Allowing the user to explicitly skip charts would also inversly mean that if a chart is *not* skipped, the user wants to have it. This allows for more fine-grained validation; currently we can only warn if Dex is misconfigured, as to not interrupt the installation by accident (because Dex might not even be used).

This ability would also speed up our e2e tests a bit, because we currently install cert-manager and nginx, even though we don't use them.

This would also make re-installs and single-chart updates easier, so the user does not have to re-deploy an entire stack.

**Acceptance criteria**
- [ ] Users can choose the subset of Helm charts they want to install.

**Comment by marioreggiori** [comment]
Hey, we've successfully tested skipping helm charts deployed by the installer and like to contribute on this feature. Our proposal would be to have a  `skip-charts` flag which receives a set of chart names (e.g. `--skip-charts=cert-manager,nginx-ingress-controller`) to be skipped by the installer. Is this something we'd get approved in a PR?
