### ISSUE TITLE
Provide a way to run Kubermatic with own CA

### ISSUE THREAD

**Issue by chrkl** [kubermatic/kubermatic#5876]
**User Story**

When using certificates that have been issued by an internal CA for DEX, trusting this CA by the IAP proxy pods (and the Kubermatic dashboard?) is required. In previous installations, we solved this issue by injecting the internal CA to all pods using the PodPresets admission controller.

Since PodPresets will be removed in Kubernetes 1.20 (https://github.com/kubernetes/kubernetes/pull/94090) and KubeOne (https://github.com/kubermatic/kubeone/issues/1104), a new solution for this issue is required.

Related issues:
https://github.com/kubermatic/kubermatic/issues/5554
https://github.com/kubermatic/kubermatic/issues/5852

**Acceptance criteria**

Possible solutions could be:
- Providing a mutating webhook that mounts a CA to all pods
- Modifying the Helm charts in a way to mount the CA to the required pods

**Comment by xrstf** [comment]
For the Kubermatic API itself, we allow to set a custom CA bundle in the KubermaticConfiguration, so API<->Dex can work. Whatever we decide upon should take this into account, so we don't end up with multiple solutions fo the same problem.

**Comment by erdii** [comment]
For the record: User-cluster apiserver<->dex can also be enabled by feeding the ca bundle into `KubermaticConfiguration.spec.auth.caBundle`.

**Comment by toschneck** [comment]
The missing peace in the puzzle is the machine controller, see https://github.com/kubermatic/machine-controller/issues/876

**Comment by kron4eg** [comment]
Fixed by https://github.com/kubermatic/kubermatic/pull/6538
