### ISSUE TITLE
Setting up KKP in clusters with Pod Security Policies activated

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5891]
**User Story**
The goal of the user story is to provide guidelines for setting up KKP on [Pod Security Policies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) enabled Kubernetes clusters. This would involve:

- [ ] Defining the minimal requirements of each KKP component pods
- [ ] Improve them where reasonably possible in a way that they can run with [restricted](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml) policy.
- [ ]  Define policies for the containers that cannot cope with restricted policy.

**Acceptance criteria**
Having a clear and documented procedure for deploying KKP on Pod Security Policies enabled clusters.

**Comment by irozzo-1A** [comment]
To start with we could just document current requirements in terms of PSP without doing any improvement.

**Comment by shaase-ctrl** [comment]
Will be deprecated in Kubernetes 1.21 and removed Kubernetes 1.25.
