### ISSUE TITLE
Remove kubermatic-operator-util

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#5906]
**User Story**
The utility was introduced to make some operator-related commands available to users, but now that we have the kubermatic-installer, we should move the last remaining util command over:

```
app.Commands = []cli.Command{
		{
			Name:      "defaults",
			Usage:     "Outputs a KubermaticConfiguration with all default values, optionally applied to a given configuration manifest (YAML)",
			Action:    defaultsAction,
			ArgsUsage: "[MANIFEST_FILE]",
		},
	}
```

The command was never documented anyway IIRC.

**Acceptance criteria**
- [ ] The util command is removed from the repository.
- [ ] The `defaults` command is either also just removed or moved to the installer.

**Comment by u5surf** [comment]
Hi @xrstf,  I can take a stab at this issue, if anyone already work in progress.
