### ISSUE TITLE
Migrate k8s components docker repositories for KKP <= 2.14 

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5967]
**User Story**

Kubernetes images should now be fetched from `k8s.gcr.io/` and not `gcr.io/google_containers`. Recent versions like `1.17.11` are not available in the old location. 

xref: https://github.com/kubermatic/kubermatic/pull/5963

**Acceptance criteria**

It is possible to create user clusters with recent k8s versions (e.g. 1.17.11) in KKP <= 2.14

**Comment by xmudrii** [comment]
This has been fixed.
/close
