### ISSUE TITLE
Flatcar OS is broken on AWS

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#5994]
**User Story**
Currently creating an AWS cluster at dev.kubermatic.io is broken, due to some user data limites:
https://dev.kubermatic.io/projects/nztx8frfmh/dc/europe-west3-c/clusters/mbrjpjhmbf/md/laughing-feynman
```
failed to create machine at cloudprovider, due to failed create instance at aws, due to InvalidParameterValue: User data is limited to 16384 bytes status code: 400, request id: 6e581280-4174-477c-8e86-a2ba89780527
```

**Acceptance criteria**
- Flatcar node can get provisioned

**Comment by xrstf** [comment]
How many SSH keys did you have assigned? I experienced the same, but when I lowered my nodes from 2 to just 1 SSH key, it worked.

Still a bug though, just wanting to narrow it down.

**Comment by toschneck** [comment]
@xrstf I don't remember exact, but it was max 1 ssh key

**Comment by xrstf** [comment]
This is going to be obsolete with the refactoring/reimagination of the machine-controller v2. With the current implementation, there is no (easy) fix for this. At least no fix that would be available before the refactoring is done.
