### ISSUE TITLE
Configurable default control plane component settings

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#5998]
**User Story**
Cluster resource spec includes [componentsOverride](https://github.com/kubermatic/kubermatic/blob/979aceef489f54df2ef6db6b6e85383a78315017/pkg/crd/kubermatic/v1/cluster.go#L111) (probably the name is not appropriate), which includes settings for the control plane components (e.g. limits, number of replicas).
Today the default settings are [hardcoded](https://github.com/kubermatic/kubermatic/blob/979aceef489f54df2ef6db6b6e85383a78315017/cmd/seed-controller-manager/controllers.go#L87) and it's not possible to customize them.

**Acceptance criteria**
Having a way of specifying default settings for control plane components at master or seed level.

**Comment by irozzo-1A** [comment]
xref: https://github.com/kubermatic/kubermatic/pull/5756

**Comment by toschneck** [comment]
Please Include as well the Prometheus Component Settings. Basically every Setting whats managed by the [`ComponentSettings`](https://github.com/kubermatic/kubermatic/blob/00b0f7414c8936805ca35e6b1c0ea98e55686830/pkg/crd/kubermatic/v1/cluster.go#L397) struct should be configurable at the seed level as default as well. 

For Prometheus, it could be hard to configure every single cluster, if you have a huge amount of crashing instances, like described at: https://github.com/kubermatic/community-components/pull/26
