### ISSUE TITLE
Implement application creation during cluster creation

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#6000]
**User Story**
- user can pick Applications during cluster creation
- applications should be created in the background once the cluster is ready (similar to node deployment creation)

**Comment by cschieder** [comment]
Hey :) This was planned for 2.18 but not implemented, is there anything you need?

**Comment by SimonTheLeg** [comment]
The functionality described in this ticket will be added with the new Applications mechanism. Currently we do not plan to extend the current AddOn mechanism with this functionality

As a result I think it makes sense to re-use this ticket. I will rename it to applications and move it into the Applications epic.
Additionally I will also move and rename the UI ticket this story blocks.

**Comment by csengerszabo** [comment]
Issue moved to [kubermatic/dashboard #4437](https://github.com/kubermatic/dashboard/issues/4437) via [**ZenHub**](https://www.zenhub.com/)
