### ISSUE TITLE
Upgrade Canal as a CNI for user clusters.

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#6016]
**User Story**
We are currently using Canal as a CNI for user clusters. Till we implement #5589 and for clusters running older versions of Kubermatic, we should upgrade to the latest version: 3.16.3 from 3.8.0.

**Acceptance criteria**
- Canal in VXLAN mode is installed in user clusters.
- Having upgrade documentation for existing user clusters.

**Comment by youssefazrak** [comment]
After some thinking, going with Cilium (eBPF) might be a good idea. This wouldn't change much on the difficulty compared to upgrading Calico to the latest version for existing installations.

**Comment by HaveFun83** [comment]
any news here?
