### ISSUE TITLE
Tailor CoreDNS version to the right K8s version for user clusters

### ISSUE THREAD

**Issue by youssefazrak** [kubermatic/kubermatic#6023]
**User Story**
We are currently using CoreDNS 1.3.1 for all our user clusters, without taking into account the Kubernetes version of the cluster.
This is done as a way to simplify the versioning but could introduce issues as some features of CoreDNS are deprecated for example.

**Acceptance criteria**

- Follow for the [official CoreDNS <-> Kubernetes](https://github.com/coredns/deployment/blob/master/kubernetes/CoreDNS-k8s_version.md) version mapping
- CoreDNS is successfully deployed in the user clusters and is using the correct version depending on the Kubernetes version.

**Comment by jplgec** [comment]
Any update on this issue? We recently experienced coredns related issues in our Kubermatic user clusters (1.16, 1.17) and before we investigate any further we would like to have the coredns version up to date first.

**Comment by shaase-ctrl** [comment]
I added this as a top priority for estimation.
