### ISSUE TITLE
Add imagePullSecret support to KKP Helm charts

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6062]
**User Story**
Starting from November 1st DockerHub will introduce a [download rate limit](https://docs.docker.com/docker-hub/download-rate-limit/).

In order to mitigate the impact on KKP all charts generating pods with images coming from dockerhub should support `imagePullSecrets`.

Impacted charts from a quick autit seems to be:
- [ ] backup/velero
- [ ] kubernetes-dashboard
- [ ] logging
- [ ] minio
- [ ] monitoring
- [ ] nodeport-proxy

**Acceptance criteria**
Having the possibility to apply `imagePullSecret` for all KKP platform pods using docker hub images coming from Helm charts.

**Comment by xrstf** [comment]
kubernetes-dashboard can be left out, as per https://github.com/kubermatic/kubermatic/issues/6073.
