### ISSUE TITLE
kubermatic-installer: unable to parse helm version output if extra messages are present

### ISSUE THREAD

**Issue by Be-El** [kubermatic/kubermatic#6070]
**User Story**

We are deploying kubernetes clusters with a terraform script. At the end the script generated the kubeconfig file.

Using this file and kubermatic-installer result in the following error message:

    $ kubermatic-installer --charts-directory <redacted>/charts deploy --config kubermatic-master.yaml --helm-values values.yaml --force
    ERRO[13:52:04] ❌ Operation failed: failed to check Helm version: Invalid Semantic Version. 

It is caused by the fact that the generated kubeconfig file is group readable (and has to be group readable):

    $ helm version
    WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: <redacted>/kube_config_cluster.yml
    WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: <redacted>/kubermatic/master/terraform/kube_config_cluster.yml
    version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

This warning can be ignored (at least in our case), and the parse should be able to skip over it (either on request per command line option, or by default and add an extra warning in the kubermatic-installer output?)

**Acceptance criteria**
 * allow kubermatic-installer to be used with group/world readable kube config files

**Comment by xrstf** [comment]
Thanks for reporting, we will take a look soon at this.
