### ISSUE TITLE
Adding 'instanceReadyCheckTimeout' and 'instanceReadyCheckPeriod' to the API 

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#6113]
**User Story**
Openstack has now a configurable timeout values where the user can specify `instanceReadyCheckPeriod` and the `instanceReadyCheckTimeout`. Those values used to be hardcoded, however, with different openstack setups this can be a bit challenging(e.g a slow setup). There is already a merged PR(https://github.com/kubermatic/machine-controller/pull/843) which introduces those fields in the machine deployment object. Would it make sense also to have two in node deployment object which sets those fields via the api(UI)?

**Acceptance criteria**
Two new fields added to the MachineDeployment object:
- instanceReadyCheckPeriod
- instanceReadyCheckTimeout

**Comment by floreks** [comment]
When can we expect to get the new MC release?

**Comment by moadqassem** [comment]
There is already a new release https://github.com/kubermatic/machine-controller/tree/v1.20.0 which actually contains the change.
