### ISSUE TITLE
Fix node-exporter not being scrapable

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#6165]
**What this PR does / why we need it**:
It is pretty much impossible to configure Prometheus to scrape the node-exporter addon in user clusters.

This has been extracted from a PR.

---

## Foreword

The most important piece of knowledge here is that the node-exporter **runs in the host network.** This puts it (and its pod IP) outside the Pod IP range of the user cluster and therefore outside of the VPN.

Old solution: In order to not make the node-exporter available on all interfaces of a node (and hence make it public, unless someone put firewall rules into place), we make the exporter run on `127.0.0.1:9100` and then have a *kube-rbac-proxy* sidecar which binds on the pod IP (this can be an internal or external IP, dependending on the cloud provider), checks credentials and then forwards to the upstream node-exporter on `127.0.0.1`.

## Solution: Escape host network via UNIX sockets

The kube-rbac-proxy is gone entirely. Instead the node-exporter pod now has a socat sidecar, which listens on a socket on the host and forwards traffic to the node-exporter. A second DaemonSet runs another socat proxy, but this time taking Prometheus scrape requests and forwarding them to the local socket. This removes the need to find the neighboring pod, as the proxy simply uses whatever is present on the host's disk.

## Addon Configuration

This PR also extends the addon configuration so that the scrape annotation prefix is available for templating in addon manifests. This makes it so that cluster operators can configure the prefix once and have the addons be reconciled properly.

In order to not leak our Product name, we have to revert the default value for the flag to an empty string.

The node-exporter addon now expects a `port` variable and defaults to a **non-default** port for the exporter. This makes it so that customers can install their own node-exporter without conflicting with the addon.

## Security Considerations

This PR makes a socket available on every node, under which anyone can reach the node-exporter. I don't think this makes it less secure: If you can read the socket file, you could also just talk to port 9100 locally.

## Backwards Compatibility

The default port for node-exporters changed from 9100 to 49100. Given that nobody so far could feasably have scraped it, I don't think we need to classify this as "breaking change". The new port should hopefully be safer and cluster operators can override it by setting the variable for each user-cluster manually.

The changed default value for the scrape annotation however is breaking, but I think it's okay to document that customers need to set `kubermatic.monitoringScrapeAnnotationPrefix=whatever.they.like` when updating.

**Does this PR introduce a user-facing change?**:
```release-note
The node-exporter addon gets automatically scraped when installed into user clusters.
Action required: default scrape annotation prefix default value was removed.
```

#### Attempt 1: Scrape Pod via kube-apiserver proxy.

The obvious approach and what we already do for all other pods in the user-cluster (if they have the special scraping prefix annotation). This makes Prometheus send the scraping request to the kube-apiserver, which proxies it to the pod.

I tried

* `/api/v1/namespaces/kube-system/pods/node-exporter-xyz:9100/proxy` (sic)
* `/api/v1/namespaces/kube-system/pods/node-exporter-xyz:9100/proxy/metrics`
* `/api/v1/namespaces/kube-system/pods/https:node-exporter-xyz:9100/proxy/metrics`

All ended up in a timeout. Even if this worked, the credentials are not forwarded by the kube-apiserver, so the bearer token would be received by kube-rbac-proxy anyway.

#### Attempt 2: Scrape Nodes via kube-apiserver proxy.

Same as before, but doing Prometheus service discovery on nodes instead of pods. I tried

* `/api/v1/nodes/<ip>:9100/proxy/metrics`
* `/api/v1/nodes/https:<ip>:9100/proxy/metrics`
* `/api/v1/nodes/<hostname>:9100/proxy/metrics`
* `/api/v1/nodes/https:<hostname>:9100/proxy/metrics`

All failed.

#### Attempt 3: Scrape the node directly

This fails because

* we might have firewall rules in place that prevent access to the nodes
* we never know if a node IP is internal or external
* internal node IPs are not reachable via VPN

#### Attempt 4: Remove kube-rbac-proxy, bind to private IP

This would make the node-exporter bind to the node's internal IP instead of localhost. Not all cloud providers provide internal IPs, so this is out. It would also not solve the issue of reaching the node in the first place (see attempt 3).

#### Attempt 5: Run a kubectl-proxy sidecar container

This sidecar cannot run in the node-exporter pod, because it would not solve anything attempt 4 would not have solved (removing authentication). So the "sidecar" would be a "sidecar pod", i.e. a second DaemonSet. The problem then is that the pod needs to find its neighboring node-exporter pod. This is simple with kubectl and jq, but we need to do this in a public Docker image, because due to whitelabelling we cannot create a quay.io/kubermatic/... helper image with the required tools. Good luck finding good kubectl+jq images out there.

**Comment by xrstf** [comment]
Two solutions were proposed but not evaluated yet: #5243 and #5264.

**Comment by irozzo-1A** [comment]
@rastislavs do you think we can close this after the new monitoring stack is integrated?

**Comment by rastislavs** [comment]
> @rastislavs do you think we can close this after the new monitoring stack is integrated?

Yes, the node-exporter should work fine with the new MLA stack (as Prometheus runs in the user cluster).
Should we keep this open until it is integrated and the new user cluster MLA option is available?

**Comment by irozzo-1A** [comment]
Agreed, let's close this once the MLA option is available. I doubt we will invest in a solution for the legacy stack.

**Comment by rastislavs** [comment]
As agreed with @shaase-ctrl, we are closing this issue.
node-exporter can now be used with the new [User Cluster Monitoring Logging & Alerting Stack](https://docs.kubermatic.com/kubermatic/v2.18/architecture/monitoring_logging_alerting/user_cluster/).
