### ISSUE TITLE
Annotation Option for nginx LoadBalancer Services

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#6172]
**User Story**
As an kubermatic user
I want to set a (cloud) specific annotations to the kubermatic ingress chart:

E.g. to deploy Kubermatic behind a private network at AWS a customer would need to set the annotation `service.beta.kubernetes.io/aws-load-balancer-internal: "true"`. Therefor currently he could use a patch command as workaround (or create the service upfront):
```
kubectl annotate svc nginx-ingress-controller -n nginx-ingress-controller service.beta.kubernetes.io/aws-load-balancer-internal=true
```

But this not following the infrastructure as code principal. So we would need a helm value option for the chart at this point:
https://github.com/kubermatic/kubermatic/blob/master/charts/nginx-ingress-controller/templates/service.yaml#L25

Other use case, are fore example a on-premise installation with metallb where some CIDRs need to get specified.

**Acceptance criteria**
- [ ] Custom [service annotations](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer) can be set
- [ ] Docs are updated

**Comment by xrstf** [comment]
>  So we would need a helm value option for the chart at this point

Do we though? Firstly, the Helm chart is deprecated and will not receive new options. It's going to be removed in 2.17 anyway.

For the KKP Operator, it is trained to not overwrite annotations on Ingresses, so it could very well be solved by running

```
helm install kkp-operator
kubectl annotata whatever you like
```

This is still "infrastructure as code".

**Comment by toschneck** [comment]
@xrstf as far as I see it right now, the helm based ingress setup is still managed by helm. So we should also allow to set some annotations at https://github.com/kubermatic/kubermatic/blob/master/charts/nginx-ingress-controller/values.yaml
