### ISSUE TITLE
Exclude incompatible instance sizes 

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#6175]
**User Story**

The admin will be able to set up min and max resource quota for user cluster instances. We can use global settings for this.

**Note:** Issues relating to this epic are managed [via ZenHub](https://app.zenhub.com/workspace/o/kubermatic/kubermatic/issues/6175).

**Comment by kgroschoff** [comment]
I think we already fetch sizes from providers api whenever possible. What needs to be done for sure: Check if all providers have all necessary informations or if we can get them, e.g. CPU, Memory,...
Afterwards we have to exclude the incompatible sizes.
