### ISSUE TITLE
Flatcar update operator pods end-up in NodeAffinity status

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6185]
**User Story**
When creating a user-cluster in KKP with Flatcar workers, it arrives from time to time to observe Flatcar update operator pods (see #5875) ending up in `NodeAffinity` status, with the following reason `Pod Predicate NodeAffinity failed`.
From my observations, there should be no big impact as those pods are scheduled again, apart from making our conformance tests flaky, as the test verifying that all pods get to ready state fails.

The reason for this seems to be a race condition between Scheduler and Kubelet (see https://github.com/kubernetes/kubernetes/issues/93338#issuecomment-663664597), that may occur when a pod has a `nodeSelector` based on a label that is not added by the kubelet. e.g. 

```
  nodeSelector:
    x-kubernetes.io/distribution: flatcar
```

Note that this was observed for Flatcar update operator pods but could potentially impact any other pods.

**Acceptance criteria**

Make sure that no pods end up in `NodeAffinity` status. As the main impact seems to be on conformance tests, we can consider mitigations as:

- Garbage-collect those pods.
- Ignore those pods for the purposes of the integration tests (after having double-checked that pods are rescheduled).

**Comment by imharshita** [comment]
/close

Fixed in Kubernetes upstream v1.19.8+
Details:  https://github.com/kubernetes/kubernetes/issues/93338
