### ISSUE TITLE
Use Konnectivity as a drop-in replacement for OpenVPN

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6188]
**User Story**
The goal of this story is to replace our current solution to allow control plane components to reach the cluster network based on OpenVPN with [Konnectivity](https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/). The main gain would be simplifying our stack by:

- getting rid of `openvpn-client` and `dnat-controller` sidecar containers in several control-plane components.
- avoid custom "dnsConfig" in control plane components.
- getting rid of `openvpn-server` and `openvpn-client` deployments, in favor of Konnectivity Server and Agent.

I already did some experiments and the migration seems to be quite straightforward, but a few things should be considered:

- Apiserver extensions are supposed to be located in the "cluster" network, today we are deploying `metrics-server` in the "master" network (see https://github.com/kubernetes/kubernetes/pull/93103).
- Some components other than KAS are currently configured to reach cluster network (e.g. scheduler, controller-manager, openstack-cloud-controller-manager). While I'm not sure why this would be useful we still need to double check.
- beta since k8s 1.18

**Acceptance criteria**
Having replaced OpenVPN with Konnectivity :-).

**Comment by irozzo-1A** [comment]
Find here a presentation about the topic: https://drive.google.com/file/d/1TsofmwBsCVwPzuBEEduXOiLBAfWE_Jp5/view?usp=sharing (restricted access)

**Comment by rastislavs** [comment]
Konnectivity implementation has been completed. Further tasks for making it GA are being tracked in https://github.com/kubermatic/dashboard/issues/3995
