### ISSUE TITLE
Allow arbitrary cluster names

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#6190]
**User Story**
Currently cluster names must be alphanumeric and lowercase characters only. From what I can see, the cluster name is not used as an identifier anywhere (not in URLs and not in Kubernetes resource names), so why not allow arbitrary text for the cluster names?

**Acceptance criteria**
- It's possible to name a cluster `My Cluster 🎉`

**Comment by shaase-ctrl** [comment]
I have seen some very uncommon bugs with naming schemes (e.g. to long username enabled privilige escalation). How can we make sure this is not happening if we allow arbitrary names? Also tools we might not know of, may have a problem if the cluster name is too unique?

**Comment by xrstf** [comment]
> Also tools we might not know of, may have a problem if the cluster name is too unique?

What does "too unique" mean?

> How can we make sure this is not happening if we allow arbitrary names?

`if len(name) > 1000 { return errors.new("name is too long") }`
