### ISSUE TITLE
Allow third-party-jwt on kubernetes-api server for Istio

### ISSUE THREAD

**Issue by paepke** [kubermatic/kubermatic#6191]
**User Story**
As a consumer of a kubermatic created cluster I want to enable [Service Account Token Volume Projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) to allow Istio the usage of third party tokens as referenced in [Istio Security Best Practices](https://istio.io/latest/docs/ops/best-practices/security/)

**Acceptance criteria**
Istio can be deployed with the use of third party tokens
The api has the TokenRequest endpoint enabled
```$ kubectl get --raw /api/v1 | jq '.resources[] | select(.name | index("serviceaccounts/token"))'
{
    "name": "serviceaccounts/token",
    "singularName": "",
    "namespaced": true,
    "group": "authentication.k8s.io",
    "version": "v1",
    "kind": "TokenRequest",
    "verbs": [
        "create"
    ]
}
```

**Comment by stroebitzer** [comment]
Our customer is trying to install Onepanel (https://docs.onepanel.ai/) - which installs Istio itself.

On installing istio via istioctl you get the following warning:

```
❯ istioctl install                                                                                                                                                                                                      
This will install the default Istio profile into the cluster. Proceed? (y/N) y
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete
```

So you can install istio into kubermatic clusters but with less secure first party JWT. As it looks Onepanel does not do that via `istioctl` and does not default to first party JWT.

**Comment by toschneck** [comment]
Current temporary workaround:
1) Pause Cluster:
```
# set cluster.spec.pause=true
kubectl edit cluster xxxxxxxxxx
```
2) Patch this values at the `apiserver` deployment:
```
        - --service-account-issuer
        - api
        - --service-account-api-audiences
        - api,nats
        - --service-account-signing-key-file
        - /etc/kubernetes/service-account-key/sa.key
```

**Comment by toschneck** [comment]
@paepke you could test it like described: https://docs.kubermatic.com/kubermatic/master/advanced/sa_token_projection/

**Comment by paepke** [comment]
we finally managed to update kubermatic - works perfectly, thanks you can close the issue
