### ISSUE TITLE
Improve handling of CRDs within addons

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#6194]
**User Story**

Some addons may contain CRDs and their instantiations (CRs) at the same time. In that case, it takes several attempts in reconciliation loop until the addon is successfully installed. That results into a delay by installation and several warnings in the cluster event log in the KKP UI.

**Acceptance criteria**

Make sure that addons that contain CRDs and their instantiations (CRs) are installed seamlessly, as fast as possible, and without unnecessary warnings.

**Comment by rastislavs** [comment]
A quick solution could be just separating all CRDs within the addon folder to a specific subfolder (e.g. `crds`), and have the addon controller to apply them first (inspired by helm3).

**Comment by redradrat** [comment]
Anyone know if the manifests are read in the respective controller? I can't find the actual source code...

Are they parsed? Or just posted to the API server?

**Comment by rastislavs** [comment]
@redradrat the manifests are currently sorted by filename in the addon folder [here](https://github.com/kubermatic/kubermatic/blob/master/pkg/addon/template.go#L187).

The addon-controller templates the addons as Go templates before applying them in the user clusters: https://docs.kubermatic.com/kubermatic/master/advanced/addons/
