### ISSUE TITLE
Improve Error for expired/deleted Tokens

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#6211]
**User Story**
After deleting a token I created for my ServiceAccount in the KKP Dashboard, I used the old token again with curl and got

```
$ curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9......" https://example.com/api/v1/projects/wlrfpbdjvt/dc/captain/clusters/dq8zg9rfpp/kubeconfig
{"error":{"code":401,"message":"access denied due to an invalid token, details = [oidc: id token issued by a different provider, expected \"https://example.com/dex\" got \"\", sa: the token 228gx4ln9m has been revoked for serviceaccount-xhbnxdcp8r@example.com]"}}
```

While this does contain the actual cause, the first part of the error message is confusing. Maybe we can handle expired tokens better and provide a simpler error message.

**Acceptance criteria**
- [ ] Errors on expired/deleted tokens do not mention that the token's issuer is wrong.

**Comment by maciaszczykm** [comment]
It needs improvement as at the moment we have a token verifier plugin mechanism where it is possible to register new plugins to do different checks. Unfortunately, plugins are on the same level and happen in all cases (`oidc` and `sa`). To avoid adding conditions on top of that we'll have to change it a bit. It would be the best to find out which kind of token we are dealing with first (we might use the `serviceaccount-` prefix that is added to all service accounts).

**Comment by maciaszczykm** [comment]
This will take some time so at the moment I'm moving it back to the collector. We need to estimate it and then put back in the backlog again.
