### ISSUE TITLE
Allow to run KKP in KKP

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#6213]
**User Story**
Currently, from memory, it's not possible to run KKP inside a usercluster managed by KKP itself. Some IP ranges conflicted, if memory serves. For complexer setups it will be very helpful to provide userclusters that can run _anything_.

**Acceptance criteria**
- [ ] KKP inside userclusters works as expected.

**Comment by shaase-ctrl** [comment]
Can you describe such a setup?

**Comment by xrstf** [comment]
@shaase-ctrl I would like to remind you of last week's SIG Infra presentation. It contains a very real example use case. ;-)

**Comment by xrstf** [comment]
cc @moadqassem (This is part of the "extend Captain cluster's usage" story)
