### ISSUE TITLE
Operating System Management in KKP 

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#6214]
**User Story**
As a user, I would like to read and evaluate the suggested approach to fix the OS versioning issues in KKP and Machine-Controller, to have a better overview and evaluation.

**Acceptance criteria**
- Explaining the backgrounds of this proposal
- Explaining the implementation and the workflow of the new approach 
- Defining the tasks and efforts for the added logic  

The proposal: 
https://docs.google.com/document/d/1oq--ldnq0B0kEgboEYtCbRoOQKcbFe5IsR9qgkKmhmc/edit#heading=h.4dm4qevh2lmf

**Comment by shaase-ctrl** [comment]
https://docs.google.com/document/d/1oq--ldnq0B0kEgboEYtCbRoOQKcbFe5IsR9qgkKmhmc/edit#heading=h.4dm4qevh2lmf

**Comment by moadqassem** [comment]
Finished working on the proposal and the link in the description is in the ready to review state
