### ISSUE TITLE
[Proposal] Migration path for existing user clusters to external CCM and CSI

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubermatic#6225]
**User Story**

Kubernetes has deprecated the in-tree cloud providers responsible for integrating with the cloud provider APIs in favor of external cloud controller managers and CSI drivers/plugins. The removal is supposed to happen in 1.23.

Affected cloud providers are AWS, Azure, GCE, OpenStack, and vSphere.

**Acceptance criteria**

* Explain the background of the change
* Explain the difference between in-tree and external implementations
* Explain the migration path
* Define tasks and efforts

**Comment by irozzo-1A** [comment]
it's merged
