### ISSUE TITLE
Move http related errors out of Kubernetes provider

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#624]
api/pkg/provider/kubernetes/kubernetes.go makes use of http errors.
It shouldn't. It clearly violates the principle of separation of concern.

We should define errors to expect in api/pkg/provider/types.go

Out http handler's should be responsible for returning a http error.

**Comment by p0lyn0mial** [comment]
how about returning k8s related errors from `provider/kubernetes/*` and then map to HTTP related errors in the HTTP handler ?

for example, provider:
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/kubernetes/project.go

mapping:
https://github.com/kubermatic/kubermatic/blob/92d9d9555bff3f880c17eb82e2c158f142bdc7cf/api/pkg/handler/project.go#L33-L34

**Comment by mrIncompetent** [comment]
sgtm
