### ISSUE TITLE
Validate machine types compatibility when choosing ARM machines in KKP  

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#6263]
At the moment, the machine controller is able to provision arm machines and installing all the proper binaries dynamically without any configuration(https://app.zenhub.com/workspaces/work-in-progress---the-a-team-5fa971db111c0d0018ce0008/issues/kubermatic/kubermatic/6252). This however, might raise a potential issues while choosing the right machine type and image. for instance, the images that we pick to run on machines types on aws might not be compatible/permitted which would lead to encounter errors while provisioning those machines. 

We are actually hitting this issue already while creating machine in AWS and choose the `t4g`Instance Type.

**Comment by moadqassem** [comment]
A potential solution to this issue, can be reflected automatically when finishing implementing the Operating System Management functionality, by adding all the relevant information in the OperatingSystemProfile object and based on it the correct Machine Types and Image can be selected accordingly.

**Comment by maciaszczykm** [comment]
@xrstf @moadqassem What needs to be done here from the UI/API perspective?

**Comment by moadqassem** [comment]
@maciaszczykm From a UI perspective, having some kinda filter which split the machine types into two groups(similar like aws for example). Like 2 radio buttons the first one `64-bit (x86)` and the second one `64-bit (ARM)`. Based on the selection, dashboard will filter out the irrelevant machines, and only shows the machines that runs the chosen arch.

**Comment by floreks** [comment]
Add note to documentation about instance/image compatibility.
