### ISSUE TITLE
Effortless CI/CD toolchain integration

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6295]
**User Story**
As a user, I want to integrate KKP and my develpoment toolchain effortlessly, so that my project ramp up time is minimal.

**Acceptance criteria**
- API functionality is summarized in an How To
- We provide an integration via Add-Ons functionality for the most common use cases (gitlab, jira, github)

Hackathon is planed for this topic.

**Comment by almereyda** [comment]
Is this Hackathon still on?

**Comment by shaase-ctrl** [comment]
Yes, we are just trying to find a suitable time slot.

**Comment by almereyda** [comment]
Do you know where and when an announcement of this event can be expected?

**Comment by shaase-ctrl** [comment]
We tackled this topic a bit differently. This issue will be closed but you can watch out for our talks at https://www.containerdays.io/

**Comment by almereyda** [comment]
Thank you for the update! I'll be sending my colleague.
