### ISSUE TITLE
Create a migration plan for CoreOS users

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6310]
How do I find out that I have CoreOS running? 
How do I switch my deployments? 
What do I have to consider before I start and how do I avoid downtimes would be the first thing coming to my mind.

**Comment by mfranczy** [comment]
I have to find out how machine-controller will act if I will drain a node.

**Comment by mfranczy** [comment]
There is already evicition implemented in the machine controller, so it would be enough to tell users to consider a pod disruption budget.

**Comment by mfranczy** [comment]
Blog post https://docs.google.com/document/d/1F0tQnBWyER-qfBAO8Is-ai9CAsUi1c7GBdEdY4pt3p8/edit#, now I have to check if everything works exactly as described, to be more precise if eviction mechanism will work fine.

**Comment by mfranczy** [comment]
Eviction in Kubermatic works as described in the doc

**Comment by kron4eg** [comment]
it's done: https://forum.kubermatic.com/t/support-for-coreos-container-linux-has-ended/216
