### ISSUE TITLE
replace OpenVPN with Wireguard

### ISSUE THREAD

**Issue by cedi** [kubermatic/kubermatic#6313]
**User Story**
Currently OpenVPN is used for the communication from the control plane to the worker node.
OpenVPN is a rather slow und clumsy VPN which was ok a few years ago.
But now that we have wireguard I would suggest replacing OpenVPN with wg due to it's massive performance gain and the easier configuration

**Acceptance criteria**
* OpenVPN is replaced with Wireguarg

**Comment by irozzo-1A** [comment]
Hi @cedi,

Wireguard would definitely be interesting tool and we considered it in the past, but note that we are already planning to replace OpenVPN with [Konnectivity](https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/) #6188. The main driver is not performances, but simplifying our stack and adopting a Kubernetes native solution.
