### ISSUE TITLE
Standardized User cluster monitoring

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6321]
**User Story**
As a User, I want to get out of the box user cluster Monitoring, Logging, Alerting integration for all relevant aspects of my cluster.

**Acceptance criteria**
- deliver a best practice setup
- Every component must be accessible easily (grafana, loki, prometheus, thanos, etc.)
- the authentication needs to be integrated in KPP as Kubernetes dashboard
- Automate roll out of standard dashboards 

Nice to have:
- Integrate previews it into the KKP UI 
- Ideally some configurations are possible without disabling the functionality
- loki (considering there is a central management cluster Loki component) receiving user cluster workload logs (about control plane logs - I'm not sure if they potential could exploid sensible date, so I would keep them only for KKP admins for now)

Non Goal: MLA for application integration is not part of the story. Further investigation is needed how to enable this without disabling the functionality.

**Comment by moadqassem** [comment]
Here are some links that could give some hints about what has been done regarding monitoring: 

https://github.com/kubermatic/kubermatic/issues/3540

https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/global-monitoring.md

**Comment by shaase-ctrl** [comment]
Removed estimations after attaching and reframing it.
