### ISSUE TITLE
Full support for api accounts usage

### ISSUE THREAD

**Issue by furkhat** [kubermatic/kubermatic#6333]
**User Story**

As a kubermatic user 
I want to have simple way to create credentials to access the API
So that I can do **everything via API** that I can do via UI

Note: #6247 was closed by disallowing projects creation for api accounts. Usage of api accounts is now inferior to UI and we can't take full advantage of API

**Comment by zreigz** [comment]
@furkhat After some discussion, we decided to allow SA to create a project. The main problem was the orphaned project. The SA can not be the owner of the project. So the solution is to extend the existing endpoint for project creation with a body parameter that will contain the "regular user email" to bind this user to the project. This body parameter will be required only when SA wants to create the project. For the "regular user", it will stay the same.

**Comment by furkhat** [comment]
@zreigz did you think about making api account a resource which is independent of project? So users can create it without projects. Then at api side you could identify api accounts owning user email and set it as owner reference. This way we have clean API and intuitive way of using API Accounts. What do you think @zreigz? If you have time to chat I can elaborate on this more.

**Comment by zreigz** [comment]
when we extend SA ability we will get the same result. There is no point to create another kind of user. Adding the possibility to create/delete projects by SA should solve the problems. Only one endpoint requires the extension to pass the owner of the project for the binding when it's created by SA

**Comment by furkhat** [comment]
> when we extend SA ability we will get the same result.

I assume by "same result" you mean "fix" of problem. I am trying to discuss a better and cleaner solution. Do you think we can discuss one?

> There is no point to create another kind of user. 

Wouldn't it be the same api account resource just not bounded to project?


> Only one endpoint requires the extension to pass the owner of the project for the binding when it's created by SA

It seems to me that this is the easiest solution to fix the problem. But I also think it makes api less clean even by one endpoint. Also, don't you think that it is inconvinient that you have to create a project to create api account that is capable of creating projects?
@zreigz

**Comment by zreigz** [comment]
I understand your concerns. Let me discuss it internally on Monday again and I will back to you

**Comment by furkhat** [comment]
#7043 /close
