### ISSUE TITLE
Create user clusters via gitops

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6355]
As a user I want to create and delete user clusters via gitops so that  I can leverage full automation & infrastructure as code to the fullest.

Acceptance Criteria
* users can spawn & delete clusters via tooling
* The user can opt for dedicated credentials or use their individual credentials
* RBAC is in full effect
* Kubermatic already has predefined tooling available as an addon (e.g. ArgoCD & Harbor)
* Alternatively integration is well documented with popular third party tooling

**Comment by toschneck** [comment]
xref https://github.com/kubermatic/kubermatic/issues/6414
