### ISSUE TITLE
Do not override authorised SSH keys when no keys are provided

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6381]
**User Story**
KKP is deploying in user clusters an agent (via DaemonSet) that takes care of synchronizing the SSH keys in all user homes found on the worker nodes using a secret as the source.

The agent is deployed even if no SSH keys are present in the secret, this means that the synchronization cannot be opt-out and that SSH keys provided with other means will be overridden.

https://github.com/kubermatic/kubermatic/blob/d652a660ab0176847969f0f6d2d86f1d76c1e6db/pkg/controller/usersshkeysagent/usersshkeys_controller.go#L172-L197

The goal of this task is to skip overriding the keys if no ssh key is present in the secret. This can be achieved by adding a check in the aforementioned logic.
As an optimization, it would also be possible to defer the deployment of the agent DaemonSet until some keys are added.

**Acceptance criteria**

authorized key files are not overridden when no SSH key is added to the user cluster.

**Comment by moadqassem** [comment]
Closed in favour of this epic https://github.com/kubermatic/kubermatic/issues/6383
