### ISSUE TITLE
Display GPU Information in machine deployment & node UI

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6400]
User Story:
As a user I want to see the GPU information for my nodes / machine deployments so that I know how much capacity I associated to the machine deployment.

Acceptance Criteria:
- relevant information is displayed in the UI for a single node (must have)
- relevant information is displayed in the UI for  a cluster (nice to have)

Additional information:
Within Kubermatic Dashboarda at the moment no information is given about the GPU capacity, capability and vendor.

Within Kubernetes Dashboard these capability is given (see screenshot attached)

![k8s dashboard-gpu nodes-an.png](https://images.zenhubusercontent.com/5f883d9f199cab5256a585cd/05519023-115f-4d32-9c59-1e41a5d431be)

**Comment by rastislavs** [comment]
Thanks to NVIDIA / AMD device plugins, the information about `Allocatable` and `Allocated` GPUs is available in node details (e.g. `kubectl describe nodes`) as `nvidia.com/gpu` or `amd.com/gpu`, e.g.:

```
Allocatable:
  amd.com/gpu:                 1
  attachable-volumes-aws-ebs:  39
  cpu:                         15600m
  ephemeral-storage:           21211389914
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      64323112Ki
  pods:                        110
```

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests    Limits
  --------                    --------    ------
  cpu                         630m (4%)   1100m (7%)
  memory                      258Mi (0%)  838Mi (1%)
  ephemeral-storage           0 (0%)      0 (0%)
  hugepages-1Gi               0 (0%)      0 (0%)
  hugepages-2Mi               0 (0%)      0 (0%)
  amd.com/gpu                 1           1
  attachable-volumes-aws-ebs  0           0
```

For the beginning, it may be enough to show `Allocatable` - `Allocated` count in the UI per node and cluster if  `nvidia.com/gpu` or `amd.com/gpu` are present on some nodes.

**Comment by floreks** [comment]
Focus on AWS, Azure, Google, Alibaba in this order.

**Comment by shaase-ctrl** [comment]
Creating machine controller integration as a first step.
