### ISSUE TITLE
Vault integration

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6424]
As a User I want to have a platform level integration for secure secret handling so that the integration effort is minimized. 

https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates

**Comment by themue** [comment]
Additional requirements by @shaase-ctrl :

1. In addition to reading, creating, updating and deleting are important, and the credentials should be able to change (especially with SSH).
2. Authentication via Dex OpenID Connect Provider has to be supported.
3. All Kubernetes secrets, machine secrets and provider secrets must be supported, and later possibly also application secrets.

**Comment by themue** [comment]
1. Retrieving secrets from the vault must only be done when they are actually needed. No one wants to have a secret inside a container image, as this makes the secret accessible to a larger number of users and processes than necessary. Secrets should only be transferred when the corresponding container is running, and not before.
2. It must be managed which containers have access to which secrets - secrets should only be accessible to those containers that actually need them.
3. Secrets must be stored securely in containers. A Secret must not be accessible to disk and must not be readable from the host level. When the container is shut down, it must disappear.
4. Updated secrets, for example after a rotation, must be transferred to the containers that use them.

**Comment by embik** [comment]
@shaase-ctrl do you remember why this was closed? Should we re-open it?
