### ISSUE TITLE
Coredns upgrade from 2.14 to 2.15 not working properly

### ISSUE THREAD

**Issue by phiphi282** [kubermatic/kubermatic#6428]
When upgrading from 2.14 to 2.15 the dns addon is being replaced by coredns created from the user-cluster-controller.

Since the dns addon manifests got deleted from the repository already they won't be deleted from inside the cluster. 
The user-cluster-controller will not update the existing resources though because the deployment selector is immutable. This breaks the cluster since the coredns service can't find the respective pods anymore. 

This bug can be fixed by not deleting the manifests directly and only deleting it in 2.16.

**Comment by moelsayed** [comment]
fixed in  #6785
