### ISSUE TITLE
Allow instances with GPU support

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#6433]
Instances sizes with GPU support cannot be selected from UI at various cloud providers. The UI should allow it, and it should also show the count of available GPUs in the instance list (next to the CPU count / RAM amount).

**AWS:**
UI only shows instances [cheaper than 1 USD / hour](https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/common/provider/aws.go#L240-L244), which only covers two G4 instance types (and no [P2 / P3 / P4 / G2 / G3 instances](https://docs.aws.amazon.com/dlami/latest/devguide/gpu.html)).

**Azure:**
UI does not show any [GPU-enabled instances](https://docs.microsoft.com/en-us/azure/virtual-machines/sizes-gpu?toc=/azure/virtual-machines/linux/toc.json&bc=/azure/virtual-machines/linux/breadcrumb/toc.json), as they do not fall into [PossibleContainerServiceVMSizeTypesValues](https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/common/provider/azure.go#L316).

**Alibaba Cloud:**
[GPU-enabled instances](https://www.alibabacloud.com/help/doc-detail/108496.htm) are not part of the [recommendedInstanceFamilies](https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/common/provider/alibaba.go#L82).

**Google Cloud:**
[GPU support in Google Cloud](https://cloud.google.com/compute/docs/gpus) is a bit more tricky, as it does not support dedicated GPU instance sizes, but GPUs have to be expicitly attached to generic instance sizes (N1 / A2) via API - needs some machine-controller work.

**Digital Ocean**
Not supported

**Comment by shaase-ctrl** [comment]
See https://app.zenhub.com/workspaces/input--estimation-5fa947bf2732730014ef98c1/issues/kubermatic/kubermatic/6400  as well.
