### ISSUE TITLE
Manage KKP Projects with OIDC Groups

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#6451]
**User Story**
As KKP user
I currently can manage cluster permissions with OIDC Groups. The Project Management is Limited to the user entity
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/89d821fb-533a-4c7b-8a99-17262dca3b6a)

As enterprise user I want to manage the permissions by binding it to an company OIDC group (e.g. LDAP) so I can manage the access to KKP projects in my external ID management tool.

**Acceptance criteria**
- [ ] OIDC groups could be used for project permission 
- [ ] Owner / Editor / Viewer could be a assigned to multiple OIDC Groups

**Comment by shaase-ctrl** [comment]
If I have an e-mail for the OIDC group (example: organization-alpha@companyabc.com), does this work? @toschneck

**Comment by toschneck** [comment]
Puh I don't know, I currently have no constellation to test this.

**Comment by toschneck** [comment]
@shaase-ctrl I don't think so, because the user needs be logged in before into KKP, otherwise you get this error
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/ccbf9bbb-0c00-4713-ad9b-031978dc6b52)

**Comment by moadqassem** [comment]
@xrstf Please add your thoughts about this topic

**Comment by csengerszabo** [comment]
This will be delivered in 2.21 by #9897
