### ISSUE TITLE
Hetzner Cloud controller not present in user cluster

### ISSUE THREAD

**Issue by almereyda** [kubermatic/kubermatic#6454]
**User Story**

As a cluster administrator, I seek to provision user clusters on Hetzner Cloud with already preconfigured storage interface and cloud controller, in so the cluster can be used right away.

**Current Situation**

When a user cluster is provisioned to Hetzner, the https://github.com/hetznercloud/csi-driver is already present.

**Expected Situation**

When a user cluster is provisioned to Hetzner,

- https://github.com/hetznercloud/csi-driver and
- https://github.com/hetznercloud/hcloud-cloud-controller-manager (as in KubeOne)

are present, in so the entirety of possible resources

- Networks
- Machines
- Load Balancers
- Volumes

are preconfigured with the API token that has been provided during creation.

**Acceptance criteria**

- [ ] A new user cluster on a Hetzner Cloud datacenter configuration has also a preconfigured https://github.com/hetznercloud/hcloud-cloud-controller-manager available.

**Comment by xmudrii** [comment]
Support for Hetzner Cloud Controller Manager has been added in Kubermatic v2.16.3.
/close
