### ISSUE TITLE
[vSphere] Inconsistent cloud-config when specifying a folder different from the default one 

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6462]
**User Story**
When creating a user cluster in vSphere it's possible to select a folder with a drop-down menu. The issue is that selecting a folder results in the creation of an inconsistent cloud-config, which prevents for instance to dynamic provisioning to work:

```
  Warning  ProvisioningFailed  4m47s (x12 over 15m)  persistentvolume-controller  Failed to provision volume with StorageClass "standard": folder '7ss45sbclz' not found
```

The problem seems to be related to the `working-dir` pointing to a folder that does not exist.

```
[Global]
user              = "***"
password          = "***"
port              = "443"
insecure-flag     = false
working-dir       = "7ss45sbclz" <-this should be consistent with the folder
datacenter        = "dc-1"
datastore         = "exsi-nas"
server            = "***"

[Disk]
scsicontrollertype = "pvscsi"

[Workspace]
server            = "****"
datacenter        = "dc-1"
folder            = "/dc-1/vm/kubermatic"
default-datastore = "exsi-nas"
resourcepool-path = ""
```

**Acceptance criteria**

Being able to create a fully working vSphere user cluster when a non-default folder is provided, make sure that:

- PVs can be provisioned
- No errors are found in `controller-manager` and `kubelet` logs.

**Comment by neubi4** [comment]
Bump, this Issue still exists in v2.17.2 EE.

/reopen
