### ISSUE TITLE
Display number of GPUs for AWS provider

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#6464]

**Comment by zreigz** [comment]
When the GPU flag is enabled for global settings then AWS can display VMs with GPU.
Extend VM size list for GPU. 
It would be good to be able to filter VMs by GPU

**Comment by floreks** [comment]
Fixed by: https://github.com/kubermatic/kubermatic/commit/d98029a5d0f4be7b67d4bba8228b6dd8648a4c56

/close
