### ISSUE TITLE
Preset management improvements

### ISSUE THREAD

**Issue by floreks** [kubermatic/kubermatic#6480]
Based on the discussion from the `sig-ui` meeting:

> - How do we make sure to not override a preset (GitOps workflow?)?
> - Can we add a flag to the preset-crd that the preset is not editable in the UI, so that customers cannot destroy their own work via UI or GitOps?

**Comment by toschneck** [comment]
As Sasha ask for some first feedback about the new fancy Preset Management. I really like it and it goes in the right direction! It's very helpful feature to restrict permission based on our datacenter model, what e.g. can separate dev/prod environments.


Some Improvements what came into my mind after reviewing it:

1.  The Domain notation should be made clear. If I want to enter the the domain name it would be helpful to see the used pattern: e.g. `example.com`. A tool tip can maybe also hint that this matching against the domain of sign in e-mails.
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/54123917-bb78-4e91-aa36-6c8f5299c4c2)

2. The yaml struct allows to enter multiple providers, so the UI should be doing the same (just to be consistent)
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/b2e7b48d-cb4e-4631-a38b-bfa00ab8b9a4)

3.1 The datacenter restrication is unclear what to enter. I think it's the datacenter name, but e.g. with a cloud provider like vSphere what using similar names it could be confusing. It would be great if we may can list hier all available datacenters as we do it the `Dynamic Datacenter` section.
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/923f43d9-e8bc-47a1-b4cd-b672b9170f19)
3.2  In future the restriction to an OIDC based group would be also very good, similar use case for datacenters #6506

4. A more general Feedback - Customers also often want to manage presets on the project level. This means a project admin could create some presets and manage them for the team. I know this currently not reflected in the data model, but would be future separate user story. 
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/4083514f-3e49-42eb-b88e-9d7c04992836)

**Comment by shaase-ctrl** [comment]
Thanks for the additions! I already created a user story for preset management on project level for the machine deployment as well.

**Comment by floreks** [comment]
1. Agree. We should add some regex here.
2. UI already allows adding multiple providers. You just can't add them all at the same time since it wouldn't be really user friendly. You have to add/edit it one at a time.

3.1. Agree. If someone comes up with a good description/hint we can easily add it.

3.2 & 4. We can mark them as potential future improvements. We have to first figure out if and how we'd want to introduce such changes upstream.

**Comment by toschneck** [comment]
> 3.1. Agree. If someone comes up with a good description/hint we can easily add it.
I would query the data centers directly from the API endpoint and show the list of data centers what are available, this is the most save way to have valid user inputs
Otherwise we should name it pot. "Seed Datacenter"  - but it's also not super clear here https://docs.kubermatic.com/kubermatic/master/concepts/seeds/

**Comment by zreigz** [comment]
Some discussion needed

**Comment by floreks** [comment]
The linked PR will add regex validation to domain names and autocompletion for the datacenter restriction input field. 

If any other improvements will be needed, please create a new issue with a clear description of what should be added.
