### ISSUE TITLE
Proposal kubermatic offline

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#650]
In some environments we dont have internet access, so pulling from docker hub/ quay, etc. does not work.
In such environments there's a local docker registry which we need to use.

We need a script for:
- [ ] download all images on your local machine 
- [ ] re-tag the images 
- [ ] push images to the customer registry

Additional: 
- [ ] enable helm charts to use the custom registry
- [ ] copy socat from a docker container

**Comment by scheeles** [comment]
@mrIncompetent anything to add

**Comment by mrIncompetent** [comment]
changed the description a bit, lgtm

**Comment by scheeles** [comment]
@mrIncompetent what do we do with kube-machine? Can we create a complete image with Docker and socat

**Comment by scheeles** [comment]
we should copy socat in generell from a infra docker- container ?

**Comment by mrIncompetent** [comment]
closed in favor of https://github.com/kubermatic/kubermatic/issues/840
