### ISSUE TITLE
2FA for Kubermatic Dashboard

### ISSUE THREAD

**Issue by cedi** [kubermatic/kubermatic#6500]
**User Story**
I as an Kubermatic User would like to use 2FA Authentication for the Kubermatic Dashboard in order to secure my Kubermatic Logins.
If I loose access to my Token Device I am still able to login to my Kubermatic Dashboard using Recovery Codes.

**Acceptance criteria**
- [ ]  2FA / MFA using TOTP Tokens is Supported
- [ ] After Logging into Kubermatic I am presented with a Screen to enter my TOTP Token
- [ ] If I am unable to retrieve a TOTP Token (due to my Authenticator App Broken or Token Device inaccessible) I can still authenticate using Recovery Tokens

**Additional Information**
This might be out of scope for the Kubermatic Project itself and rather inside the DEX Container, used for OIDC Authentication.
So if OIDC is used, there are several places, where the OTP Token could be retrieved:
1. During the OIDC Provider Login - The OIDC Provider (GitHub, GitLab, OpenStack Keystone, ...) asks the TOTP Token during Login
2. Dex itself asks for the TOTP Token, after receiving a affirmative response from the OIDC Provider
3. Kubermatic asks for the TOTP Token after it received a valid OIDC Token

DEX itself currently does not support 2FA using TOTP: dexidp/dex#352 dexidp/dex#763

**Comment by kron4eg** [comment]
@cedi few points:

* Dex is not a hardcoded thing, you can use any OIDP (keycloak for example)
* Even more, Dex can (and most likely should) be configured to use some other identity provider (google for example, or any other), and those upstream identity providers could (and should) be configured for 2FA.

I'm trying to say that 2FA is only makes sense in the system that manages identities and Kubermatic doesn't do any of that.
