### ISSUE TITLE
Give the user the possibility to configure presets for machine deployments

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6505]
**User Story**
As an User I want to configure machine deployment presets for my projects and fellows so that they do not need to redo it themselves.

**Acceptance criteria**
- Create the possibility to configure presets for machine deployments on all necessary levels of user interaction 
(kkp-admin wants to create general presets for all users and projects, project-owner wants to create specific presets for their deployments)
- Consider that each deployment must succesfully work before it is stored as a preset
- Configure error messages that help debug failing presets
- Make presets configurable via automation
- If presets are managed externally (via automation), make it visible for the user that he cannot manage them in the UI

**Comment by toschneck** [comment]
The preset filtering musst ensure, that the machine deployment can match to the dedicated cloud provider.

Also all kind of presets should follow the same restrictions and should be able to get filtered by:
- domain
- datacenter

--- potential future ---
- Kubermatic Project
- OIDC groups

**Comment by floreks** [comment]
@shaase-ctrl @toschneck 

We've had an initial discussion on this topic and we have a few remarks. First, we'd like to call it a `Machine Template` as it would contain some initial values for the machine deployments and there would not be any need to store it securely.

> Create the possibility to configure presets for machine deployments on all necessary levels of user interaction
(kkp-admin wants to create general presets for all users and projects, project-owner wants to create specific presets for their deployments)

Does it mean that we will have to support 3 different scopes?
1. Global presets - created and managed by KKP admin
2. Per-project presets - created and managed by KKP admin or project owner
3. Per-user presets - created and managed by KKP user (it would be available for all user projects)

> Consider that each deployment must succesfully work before it is stored as a preset

It must be noted that it will not be possible to validate and be 100% sure that the created template will be valid for all configurations. We have very limited possibilities to validate the template before its' creation. In example selecting different credentials for the same template might cause a whole template to be invalid.

> Also all kind of presets should follow the same restrictions and should be able to get filtered by:
>
> - domain
> - datacenter

As for the datacenter restriction, it will be applied by default and mandatory for all machine templates as datacenter selection highly impact what kind of node settings are offered by the provider API.

cc @maciaszczykm @lsviben @zreigz

**Comment by shaase-ctrl** [comment]
@floreks

What kind of `Machine Template` would be the easiest to implement and maintain?
I added some requirements that I deemed useful, if they are to hard to implement or even impossible, let us discuss them. I imagined the workflow like this: user creates a template, he can then test this and if it is sucessfully deployed, he can store it. If for example the process is not successful we ask him if he really wants to store this template. Nothing to fancy.

**Comment by toschneck** [comment]
Regards to the different scops:
>Does it mean that we will have to support 3 different scopes?
>1. Global presets - created and managed by KKP admin
>2. Per-project presets - created and managed by KKP admin or project owner
>3. Per-user presets - created and managed by KKP user (it would be available for all user projects)

Sounds good for me, the only thing we should provide additional is also an option to set MachineDeploymentTemplates (and every other Preset) for OIDC groups as well. E.g. if a customer want's to store "production template", maybe only a few people will need to see it, but should use all the same
