### ISSUE TITLE
Add KubeVirt as an accesible addon/application

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#6512]
The addon should be configurable, users must have a possibility to enable appropriate KubeVirt's feature gates.

**Comment by mfranczy** [comment]
Closing in favor of platform extension mechanism.

**Comment by mfranczy** [comment]
Re-opening since we still have to add an addon (called application) with new mechanism that is currently in progress

**Comment by mfranczy** [comment]
I think we new applications platform it could be added now to KKP 2.22
FYI @csengerszabo

**Comment by wozniakjan** [comment]
I am considering adding KubeVirt into the default application catalog, wdyt @csengerszabo?

https://github.com/kubermatic/kubermatic/tree/v2.24.0/pkg/ee/default-application-catalog/applicationdefinitions
