### ISSUE TITLE
Create contribution guidelines for KKP

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6548]
**User Story**
The goal of this issue is to make the life of the contributors easier providing contribution guidelines.

Between the topics that should be treated, it would be good to have:

* How to deal with API changes (i.e. generate swagger specs, docs, client).
* How to write tests and test locally.

**Acceptance criteria**

Contributing documentation is created.

**Comment by irozzo-1A** [comment]
see https://github.com/kubermatic/kubermatic/pull/6529#discussion_r573547356

**Comment by shaase-ctrl** [comment]
Contribution guidelines have been established.
