### ISSUE TITLE
Add controller in user-cluster controller manager to notify when nodes are ready to complete CSI migration

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6551]
The goal of this task is to introduce a new controller in the user-cluster controller manager, which role is to handle a condition in `Cluster` resources where an in-tree cloud provider to CSI migration is progress, that signals when all the nodes have been migrated not to use the kubelet cloud provider functionalities (attach/detach). This will allow completing the migration.

The controller will:

- Reconcile `Cluster` resources having the CSI migration annotation (seed-cluster side).
- For each of the `Cluster`s check that all nodes have the CSI migration feature gates and Kubelet `cloud-provider` flag is unset or empty.
- If the check passes the `Cluster` condition to `true`, set to `false` otherwise.

**Comment by irozzo-1A** [comment]
Actually, the Kubelet feature gates are not currently reflected in any resource (e.g. machine, node) they are only provided with a flag to the machine-controller.

I see two options:

- We move the Kubelet feature gates to the machine spec in a way it can be observed by the controller (requires a change in mc).
- We start by manually signal that the machines have been rolled out, it will be up to an operator to annotate the cluster resource for instance to signal that.

**Comment by irozzo-1A** [comment]
xref: https://github.com/kubermatic/machine-controller/issues/897

**Comment by irozzo-1A** [comment]
@xmudrii As we discussed  the controller will need to watch machines in user-cluster and update cluster in seed-cluster you will need to pass both seed and user mgrs when you create the controller e.g.:

https://github.com/kubermatic/kubermatic/blob/54533b205f31640d005c67ef3388e4fae5dc0814/cmd/user-cluster-controller-manager/main.go#L297

**Comment by mlavacca** [comment]
I'm working on it and I'd like to discuss an aspect with you. This controller's goal is to set the annotation `v1.kubelet-flags.machine-controller.kubermatic.io/ExternalCloudProvider: "true"
` on all the machines of the user cluster; once it is done, it updates the cluster status setting the `ClusterConditionCSIKubeletMigrationCompleted` condition to true. There is the possibility to have an inconsistent status in which the cluster status is updated, but the machine controller hasn't updated the kubelet flags yet. I see a lack of feedback to communicate the effective rolling out of nodes in the machine API. What do you think @irozzo-1A @xmudrii?

**Comment by irozzo-1A** [comment]
@mlavacca Actually the controller is not going to set the annotation on the machines, it is watching the machines and setting the condition `ClusterConditionCSIKubeletMigrationCompleted` to `true` on cluster resource when all machines have the wanted feature gates.
