### ISSUE TITLE
Add mutating webhook for Cluster resources to detect CCM/CSI migration

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6555]
The goal of this issue is to create a mutating webhook for Cluster objects that does the following things:

* Add the CSI/CCM annotations signaling that migration is needed when a `Cluster` is updated with `externalCloudProvider` feature.
* Ensure that `UseOctavia` is set to `false` when a `Cluster` is updated with `externalCloudProvider` feature, the reason behind this is that in-tree cloud provider defaults it to `false` and CCM defaults it to `true`.

**Comment by xmudrii** [comment]
This has been fixed.
/close
