### ISSUE TITLE
Make leader election lease duration configurable for kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubermatic#6558]
**User Story**

We've observed in some environments that rolling out NodeDeployments might cause kube-controller-manager and kube-scheduler to lose the leader election. As a result, both components are stuck in the permanent CrashLoopBackOff.

The issue can occur when a new node joins the cluster and the old node starts draining, i.e. all pods running on the old node are being rescheduled to the new node. When draining starts, the time needed to renew the leader election for kube-controller-manager and kube-scheduler goes to 10-15 seconds instead of the usual 2 seconds.

By default, both components have a deadline of 10 seconds and if the leader election is not successfully renewed in those 10 seconds, the affected component would crash. If it takes more than 10 seconds for the leader election to be renewed after restarting, the component would get stuck in CrashLoopBackOff.

We believe that this issue depends on the environment where the seed cluster is running, the performance of the seed cluster, and the available resources. So far, we've managed to reproduce this issue in some environments where the seed cluster is running on OpenStack and the user clusters are also running on OpenStack. The affected user clusters have 150+ pods.

**Acceptance criteria**

After investigating, we found that various factors related to the performance of the seed cluster can contribute to this issue. One of the recommended solutions for this problem is to increase `--leader-elect-renew-deadline`.

* `--leader-elect-renew-deadline` is configurable
* `--leader-elect-lease-duration` is configurable
* `--leader-elect-retry-period` is configurable

**Comment by xmudrii** [comment]
One of the possible implementations would be to make those two flags configurable on the Cluster level. We could modify the [ComponentSettings struct](https://github.com/kubermatic/kubermatic/blob/e7e2308c77eeac2b5ff7914450124a46012d881e/pkg/crd/kubermatic/v1/cluster.go#L341-L342) for ControllerManager and Scheduler to add a new field for each flag. If users would want to apply those settings on the seed-level, they could use a mutating webhook.

**Comment by jplgec** [comment]
If `--leader-elect-renew-deadline` (default: 10s)  is configurable, then `--leader-elect-lease-duration` (default: 15s) has to be as well. Documentation says that the renew-deadline "must be less or equal to the lease duration" (see [here](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)).
