### ISSUE TITLE
Add error metrics to kubermatic controller & api

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#656]
Probably a counter.

Should be incremented in: api/pkg/controller/cluster/controller.go:312
```golang
func (cc *controller) handleErr(err error, key interface{}) 
```

**Comment by metalmatze** [comment]
With #756 closed, I'd like to know what kind of metrics you still want to see. 
Maybe there are enough examples in the code now, that somebody else more involved with the controller & api can take a look again?!

**Comment by mrIncompetent** [comment]
Sure, this can be done by anyone.

This ticket is simply about adding a error-counter which gets incremented for each error which happens in the `sync` handler
