### ISSUE TITLE
change docker registry for specific docker images

### ISSUE THREAD

**Issue by dbagarozza** [kubermatic/kubermatic#6562]
Hi,

We have set the option "overwriteRegistry" in the Kubermatic configuration, but we have noticed that this does not apply to all Docker images.

For example, it doesn't work for Coredns and Calico because it's set hard in the code. Only for docker images that run via docker.io.

https://github.com/kubermatic/kubermatic/blob/23e493c3dc1e757e5d0ff728158b6cc7cfdf946f/pkg/resources/resources.go#L346

https://github.com/kubermatic/kubermatic/blob/5032490014ae448de964aef752149cc64260d4c5/pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go#L125

The reason I ask is because otherwise we run into the docker rate limit or is it possible to set it ?

Thanks.

Many greetings :)

**Comment by fwiedmann** [comment]
I would also appreciate being able to pass a docker mirror URL for docker.io images.
