### ISSUE TITLE
Open up NodePorts range in managed security groups

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#6583]
On providers that support programmable firewall (i.e. security groups), when no security group is provided by user input we create one automatically. Those security groups doesn't contain "allow rules" for NodePort ranges. But those ranges are required to complete certification sonobuoy conformance test suite.

Affected providers:
* [x] OpenStack
* [x] AWS
* [x] Azure
* [x] GCP

**Comment by embik** [comment]
@Zaunei just as an update, this was added via #8151 / #8327.

**Comment by embik** [comment]
I believe this is all done, I don't think there's something left to implement. Closing.
