### ISSUE TITLE
Use images with multi-arch support for KKP Components

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#6584]
**User Story**
As a user, I would like to run KKP master/seed clusters and user clusters on the arm64 platform.

When deployed a KKP User Cluster on an arm64 machine, some KKP components would not start due to using images for an incorrect architecture:

```
NAMESPACE              NAME                                        READY   STATUS             RESTARTS   AGE
kube-system            canal-gr5z5                                 1/2     CrashLoopBackOff   57         4h9m
kube-system            coredns-856777c9f5-msrjk                    1/1     Running            0          24m
kube-system            coredns-856777c9f5-spfsc                    1/1     Running            0          21m
kube-system            kube-proxy-26bsj                            1/1     Running            0          4h30m
kube-system            logrotate-czh9x                             1/1     CrashLoopBackOff   32         4h23m
kube-system            node-local-dns-6zckq                        1/1     Running            0          4h23m
kube-system            openvpn-client-6c9dd998bc-qzc2m             1/2     CrashLoopBackOff   59         5h51m
kube-system            user-ssh-keys-agent-8rqfs                   0/1     CrashLoopBackOff   31         4h30m
kubernetes-dashboard   dashboard-metrics-scraper-975c84c89-fg79d   1/1     Running            1          5h51m
kubernetes-dashboard   dashboard-metrics-scraper-975c84c89-jrb5w   1/1     Running            0          5h51m
```

(Log message `standard_init_linux.go:211: exec user process caused "exec format error"`)

Ideally, all KKP components should use repositories with multi-arch manifests, so that the same repository and tag works for any architecture.

**Acceptance criteria**
- User Clusters nodes with arm64 architecture can successfully run all KKP components.
- All Master / Seed clusters components can run on arm64 clusters as well.

**Comment by rastislavs** [comment]
Upgrade to canal with flannel v0.13.0 should resolve the issue for the canal pod (https://github.com/kubermatic/kubermatic/issues/6016)

**Comment by mlavacca** [comment]
All the user-cluster components now use multi-arch images
/close
