### ISSUE TITLE
Support Dual Stack User Clusters

### ISSUE THREAD

**Issue by Happy2C0de** [kubermatic/kubermatic#6610]
**User Story**
Add support for dual-stack user clusters for user clusters. Reimplementation of the dual-stack code was added with v1.20 and it's actively in the code for years. Dual-stack is certainly a must for many 2021 IT infrastructures.

IPv6 is the new standard and critical for many public facing services. Documentation can be found here:
https://kubernetes.io/docs/concepts/services-networking/dual-stack/
Kubenet or Calico support dual-stack deployments.

**Acceptance criteria**
User clusters (possibly also Kubermatic management clusters) can be run in dual-stack mode such that Pods and Services get both, an IPv4 and an IPv6 address.

**Comment by Happy2C0de** [comment]
Question:
Was IPv6 already discussed in any of the Kubermatic use-cases? What's the state of the code to support IPv4/IPv6 clusters?

**Comment by Happy2C0de** [comment]
/remove-lifecycle stale

I think it's still important! Dual Stack is "beta" since k8s v1.21 and a feature that is required

**Comment by bpereto** [comment]
this is an important feature. can we get more info or statement for the roadmap?

/remove-lifecycle stale

**Comment by shaase-ctrl** [comment]
We had to do some housekeeping first and replace our OpenVPN with Konnectivity. This will happen in 2.19. We will work on dual-stack support with the release after the next one. Does this sound sufficient? @bpereto

**Comment by bpereto** [comment]
sure, I will look forward to release 2.20.  👍🏼

**Comment by rastislavs** [comment]
Implemented. Further enhancements to be made as part of https://github.com/kubermatic/kubermatic/issues/10860
