### ISSUE TITLE
Default Constraints - endpoints

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#6631]
**User Story**
Create Default Constraint API Endpoints
All the issues included:
https://github.com/kubermatic/kubermatic/issues/7255
https://github.com/kubermatic/kubermatic/issues/7306
https://github.com/kubermatic/kubermatic/issues/7320
https://github.com/kubermatic/kubermatic/issues/7338

**Comment by imharshita** [comment]
https://github.com/kubermatic/kubermatic/issues/7255
