### ISSUE TITLE
Expose Strategy LoadBalancer broken

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#6645]
**User Story**
After using >= `2.16.x` KKP version, the expose strategy LoadBalancer does not work anymore. UI throws the following error and can't connect to the external Loadbalancer what point to the user cluster Kubernetes API server
```
Error 500failed to create restMapper: Get "https://104.199.103.82:30465/api?timeout=32s": dial tcp 104.199.103.82:30465: connect: connection refused
```
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/403eafe3-b030-41f2-ade1-81d0c570f6f2)

The error occurs also on dev.kubermatic.io. Caused by this error NO user can connect anymore by kubectl as well and getting the error:
```
The connection to the server 104.199.103.82:30465 was refused - did you specify the right host or port?
```

**How to reproduce**
1. Create a new KKP user cluster
2. If your default expose Strategy is not `LoadBalancer`, execute `kubectl edit cluster xxx` change `exposeStrategy: LoadBalancer`.
3. Errors occurs and user cluster control plan is not reachable anymore

**Root Cause**
The service account of the created nodeport-proxy-envoy in the user cluster namespace, is missing the RBAC permission to list resource `endpoints`. See:
`kubectl logs -l app=nodeport-proxy-envoy --since 5m --all-containers -n cluster-xxx`
```
E0308 08:38:01.739997       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:cluster-pptgf5rq7s:nodeport-proxy" cannot list resource "endpoints" in API group "" in the namespace "cluster-pptgf5rq7s"
E0308 08:38:40.092938       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:cluster-pptgf5rq7s:nodeport-proxy" cannot list resource "endpoints" in API group "" in the namespace "cluster-pptgf5rq7s"
E0308 08:39:37.633697       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:cluster-pptgf5rq7s:nodeport-proxy" cannot list resource "endpoints" in API group "" in the namespace "cluster-pptgf5rq7s"
```
**Temporary Workaround**
Patch manual the RBAC rules of the role `nodeport-proxy` in the user cluster namespace:
1. Pause cluster: `kubectl edit cluster xxx:` > `paused: true`
2. Patch RBAC `kubectl edit role nodeport-proxy -n cluster-xxx` and modify the role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodeport-proxy
  namespace: cluster-xxxx
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints     #<<<<< add
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resourceNames:
  - front-loadbalancer
  resources:
  - services
  verbs:
  - update
```
**What's needed?**:
- Very Quick bugfix and bugfix release for 2.16.x
- long-term: a end-2-end test what verifies that the expose strategy `LoadBalancer` is working

**Acceptance criteria**
- [ ] bugfix release handels expose strategy correct

**Comment by irozzo-1A** [comment]
@toschneck Agree that e2e tests are needed here. Unfortunately, they are not that simple to put in place, but as I will start working on the e2e for the new expose strategy I'll make an assessment.
