### ISSUE TITLE
Fix default version settings for operator

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6683]
**User Story**

The default version settings used by the operator in master branch and `release/v2.16` have the following issues:
* Automatic update from 1.15 should not have a `*` in the `To` field as it is not supported but refer to a fixed version (e.g. 1.6.13). See https://github.com/kubermatic/kubermatic/blob/b115d108db0c3bd93f7511ee38ee0c05c53ff2d2/pkg/version/manager.go#L190-L194
* We shave automatic updates from 1.16 to 1.17 as it is deprecated.

https://github.com/kubermatic/kubermatic/blob/6f6157c6304e0ed37205472e0e57e15279fe1283/pkg/controller/operator/common/defaults.go#L214-L237

**Acceptance criteria**

The default version settings of the operator trigger automatic migration to 1.15 an 1.16 to 1.17.

**Comment by irozzo-1A** [comment]
cc @toschneck

**Comment by toschneck** [comment]
Thanks for taking care :hugs:
