### ISSUE TITLE
Updating exposeStrategy breaks communication between nodes and control plane

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6685]
**User Story**
The `exposStragegy` field in the `Cluster` resource is today mutable, but changing it for an existing cluster would lead to an interruption of the communication between Kubelet and OpenVPN client and the control plane.
This problem is related to kubeconfig used by the Kubelet and the OpenVPN client config getting stale after the expose strategy change, and could be addressed by recycling the Machines (or fixing in place but we have no simple way of doing it).

I think the simpler approach is to make the `exposeStrategy` field immutable, by rejecting updates in the validating webhook.

**Acceptance criteria**
Forbid `exposeStrategy` updates or handle them correctly.

**Comment by irozzo-1A** [comment]
@toschneck proposed to have an annotation as a guard to be able to update the `exposeStrategy` e.g.
if annotation `k8c.io/enable-expose-strategy-update` is present on `Cluster` update is allowed.
Personally, I would not bother as I think exposeStrategy updates are corner cases, and if they are really needed we should invest some time documenting how to do it properly.

In addition, if we make `exposeStrategy` immutable an operator that knows what he's doig can still temporarily disable the validation in the `validatingwebhookconfigurations`.

**Comment by toschneck** [comment]
@irozzo-1A  I like this idea
> proposed to have an annotation as a guard to be able to update the exposeStrategy e.g.
if annotation k8c.io/enable-expose-strategy-update is present on Cluster update is allowed.

I don't think this are really to much corner cases. Because during a setup of a new environment it could be that you want to test different expose strategies. Alfo in regards of an support case. It could be helpful to be able to change the expose strategy on cluster level.

And for sure we need to document how you could do it.

**Comment by irozzo-1A** [comment]
@toschneck Yeah, but for testing, it's still possible to change the expose strategy at the seed level and create a new cluster. I agree that there is some potential value in changing dynamically the expose strategy, but to do it properly we need to roll out all the machines as we don't have any mechanism to apply changes in place to the workers once they are provisioned.

My advice is to keep it simple and prevent it for the moment, this will make the contract clear. If someone really wants to do it he can:

1. temporarily disable the operator
2. deactivate the cluster validation webhook
3. edit the expose strategy
4. rollout the md

It's not dramatically more complex. If use cases will arise we can invest some more in this, at the moment I don't think we have enough evidence about the actual value.

**Comment by toschneck** [comment]
@irozzo-1A agree on your opinion. But please take care that this get documented. Maybe there is a more general section for this needed, but currently no much users know how to do this:
>>>
temporarily disable the operator
deactivate the cluster validation webhook
edit the expose strategy
rollout the md

**Comment by toschneck** [comment]
Created a new issue, from my side we can then close this issue? @irozzo-1A 
Didn't test validation but I think it will work :-P

**Comment by xrstf** [comment]
The Cluster validation webhook forbids changes to the expose strategy: https://github.com/kubermatic/kubermatic/blob/12982bc01300daef83e81285d5c4dac154a5afdc/pkg/validation/cluster.go#L163-L169

This has worked well, so I think we can close this.
