### ISSUE TITLE
Draining AWS spot instances upon vms deletion

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#6723]
**User Story**
Once a spot instance goes down for whatever reasons, it should be possible to drain that node and move all the pods which are running on the failing node to another node as soon as possible.

**Acceptance Criteria**
- Drain the upon-deletion node 
- Make sure that all the pods have been moved successfully to another running node 
- Make sure that any lb is not forwarding any traffic to the failing node

**Comment by kron4eg** [comment]
Is this about automating https://github.com/aws/aws-node-termination-handler?
