### ISSUE TITLE
Preset Limitation to Datacenter  is not working

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#6729]
**User Story**
If I specify a preset over the UI  and limit it to a datacenter (I expect this is a Kubermatic Datacenter) is not working.
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/6e158e27-103e-49a1-80e6-693aa82841d2)

As a user I still get the preset chooseable for other data centers of the cloud provider.
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/86e94a1b-fc2b-46b4-b456-ac114c8a65c1)

Also I don't know how it should work, because the preset struct, don't have a field for filter it:
https://github.com/kubermatic/kubermatic/blob/master/pkg/crd/kubermatic/v1/preset.go#L97

**Acceptance criteria**
- [ ] presets get limited to datacenters

**Comment by floreks** [comment]
The preset structure does have a filter for that. It just uses polymorphism of the interfaces to manage common properties.

Preset provider is a common structure for all providers.
https://github.com/kubermatic/kubermatic/blob/1e07f7fb76073435b51f1c6f40a90adb5d78ecc8/pkg/crd/kubermatic/v1/preset.go#L203-L205

The key here is to use correct dc names that can be taken from i.e. dynamic datacenters list. It is actually described in our v2.17 documentation with a side note to be aware and use correct names.
https://docs.kubermatic.com/kubermatic/v2.17/tutorials_howtos/administration/presets/#checking-configured-presets

I have tested it on dev and it works correctly.

![image](https://user-images.githubusercontent.com/2285385/115530025-b1188b00-a293-11eb-9108-be12d75ebc0a.png)

![image](https://user-images.githubusercontent.com/2285385/115529944-a0681500-a293-11eb-80b4-642cfec4a06a.png)

Tokyo DC selected in the wizard
![image](https://user-images.githubusercontent.com/2285385/115530113-c4c3f180-a293-11eb-8dd3-9a04433e98c6.png)

Frankfurt DC selected in the wizard
![image](https://user-images.githubusercontent.com/2285385/115530160-d0afb380-a293-11eb-827c-82d36a747bba.png)
