### ISSUE TITLE
Kubermatic API: Patch of MachineDeployments UX improvable

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#6799]
no high prio, but hard to find if you run into

**User Story**
If a user currently updates the machine deployment and changes the OS system over the KKP API endpoint:
```
/api/v2/projects/{project_id}/clusters/{cluster_id}/machinedeployments/{machinedeployment_id}
```
It seams, that existing Operating System does not changes if e.g. spec changes like here:
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/cc9d4794-27a4-45dd-97e7-e8f6902e68d2)
The get response still contains the old OS.

Only if also the old OS get set to null, the patch works.
![image.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/36588f56-70b4-4fd6-b03a-c79d6ab7eee7)

**Acceptance criteria**
From the UX perspective this not ideal and could cause a lot of try-and-error at the use side. It would be better if the API:
- apply the patch correctly
- API spec gives an hint
- OR all operating system specs needs to be set, nevertheless if its's null or not (not preferred)

**Comment by csengerszabo** [comment]
- seems to be a small change, can go to one of the next patch releases
- this needs to be backported to 2.20 as well

**Comment by dharapvj** [comment]
/reopen

I don't think that original intention of this issue is resolved. We have only allowed to change one param - OS to get recognized. We need to allow patching entire MD object!

Please see [this comment](https://github.com/kubermatic/kubermatic/pull/11035#issuecomment-1256927318)

**Comment by ahmedwaleedmalik** [comment]
> I don't think that original intention of this issue is resolved. We have only allowed to change one param - OS to get recognized. We need to allow patching entire MD object!

We can already patch the entire MD object. 

> Why would we add method to patch one attribute at a time?!
The original issue was to say that if we provide updated MD definition, it should reconcile ask the fields.. otherwise POST body processing is ambiguous and is not consistent with processing logic for all the other POST calls e.g cluster, project etc

>> The original issue was to say that if we provide updated MD definition, it should reconcile ask the fields.

Can you elaborate on what you mean by that?

This PR covers these points if I understand it correctly:
```
apply the patch correctly
API spec gives an hint
```

I'd need a bit more clarity and then for sure I can take care of the fix. ;)

**Comment by ahmedwaleedmalik** [comment]
@dharapvj can we close this issue?
