### ISSUE TITLE
Default Constraints - UX design

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#6808]
UX design for default constraints.

Most of the info is here - Proposal: [Default Constraints Proposal](https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/default-constraints.md)

The default constraints workflow is like this:

1. Kubermatic admins manage the default constraints somewhere in the admin panel or a special OPA integration page, it should be similar to the way the current constraints are made for the user clusters. 
2. Those default constraints are propagated to all clusters with OPA-integration, it would be good if we can mark them somehow, as they will be undeletable and uneditable (in the existing cluster page view)

Additions for EE:
1. Activating/Deactivating Constraints - they should have some checkbox or something so that the admins can change this. Also it should be visible if the Constraint is deactivated. Deactivating a default constraint, also deactivates it for all user clusters. 

2. Filtering - add selectors for Constraints:
 a. based on providers - a list of providers for which this constraint should apply to
 b. based on cluster labels - basically a Kubernetes LabelSelector 
the filtering is maybe a bigger topic as it also touches Constraint Templates so we can discuss it separately.

**Comment by cschieder** [comment]
kubermatic/dashboard#3379 This is closed, so I believe this here should be closed too?

**Comment by lsviben** [comment]
> [kubermatic/dashboard#3379](https://github.com/kubermatic/dashboard/issues/3379) This is closed, so I believe this here should be closed too?

right, ill close it
