### ISSUE TITLE
Release Test Policy

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#6815]
**User Story**
As a user, I want to receive a well tested release so that I do not need to wait for additional patch releases.

**Acceptance criteria**
Create a documentation for the manual steps
- manual setup of KKP, seed deployment, user cluster deployment, delete everything
Create a github template for the test story / github template
Upgrade from 2.16 to 2.17 is a seperate task /story

The general idea is to derive a standard policy for the releases as the amount of QA is extremely vaste. We need to figure out a way to efficiently get through a  standard process that deliver takes care about some assumptions:

- We do run end to end tests for everything, no need to repeat those
- EE has a higher priority then CE, the idea is that if EE works, CE will also work (less complexity on CE)
- Installing a release is possible and all features are working as intended
- Updating from the last to the latest version is documented and works as intended (via operator only for all versions after 2.16)
- Create an internal documentation similar to KubeOne
- Create a distinct step by step testing plan from most important to less important

- Our experience should result in next steps on how to improve the QA on a release

Put the resulting testing steps for now into  [Kubermatic Release Policy - Manual steps](https://docs.google.com/document/d/1HNT8eU80ziLRALsL38biTgYSt83MwsmJiNRpmDOgcLY) . Feel free to edit and improve the structure.

**Comment by lsviben** [comment]
Agreed with @shaase-ctrl that for now we collect our steps in a google doc. So I added a doce where we can put the manual testing steps for the release. 

Feel free to edit and improve it, i just made some skeleton from some tasks I see above. [Kubermatic Release Policy - Manual steps](https://docs.google.com/document/d/1HNT8eU80ziLRALsL38biTgYSt83MwsmJiNRpmDOgcLY)
