### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by stroebitzer** [kubermatic/kubermatic#6844]
**User Story**
According to the [release notes]( https://github.com/kubermatic/machine-controller/releases/tag/v1.21.0) we do support ARM processors.

On starting a cluster on [run-env](https://run.lab.kubermatic.io/) (running machine-controller:v1.23.1) I get the following error message (choosing AWS with the default Node Size t4g.small):

> (combined from similar events): failed to create machine at cloudprovider, due to failed create instance at aws, due to InvalidParameterValue: The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI. status code: 400, request id: 5d9ee175-7b76-43be-9a21-f0e93c38049d

--

**Acceptance criteria**

Either 
* ARM works, as expected
* filter out ARM machine types until we fully support it

**Comment by kron4eg** [comment]
cc @zreigz

**Comment by zreigz** [comment]
@stroebitzer Hi, we have this topic in our sprint backlog. I am not sure about this sprint because we will be busy with documentation and tests but I will add high priority to this bug.
cc @shaase-ctrl

**Comment by irozzo-1A** [comment]
This is not the only gap for having ARM support unfortunately, see https://github.com/kubermatic/kubermatic/issues/6584

**Comment by shaase-ctrl** [comment]
https://github.com/kubermatic/dashboard/pull/3325

**Comment by maciaszczykm** [comment]
@shaase-ctrl @zreigz Can you specify what is missing here?

**Comment by irozzo-1A** [comment]
@maciaszczykm https://github.com/kubermatic/kubermatic/issues/6016 this one is the last missing piece probably

**Comment by shaase-ctrl** [comment]
Thanks @irozzo-1A

**Comment by moadqassem** [comment]
I have created a testing cluster on aws cloud provider and it seems that the cluster is functional with arm machine as worker nodes. At the moment it is not possible in the UI to choose machine instances that support arm arch due to some filtering in the UI, which filters out any arm machines. There is a new ticket added in the dashboard to make possible to pick a machine that has arm arch.

**Comment by moadqassem** [comment]
https://app.zenhub.com/workspaces/work-in-progress---the-a-team-5fa971db111c0d0018ce0008/issues/kubermatic/dashboard/3559

**Comment by siredmar** [comment]
@moadqassem which release did you test with for using arm nodes?
I am trying to something similar with arm64 running kubeedge.
