### ISSUE TITLE
Some pods fail to start for some time with an error from the OCI runtime

### ISSUE THREAD

**Issue by clive-jevons** [kubermatic/kubermatic#6847]
**User Story**

As a user of the platform I want all my pods to start quickly and without errors.

For some pods when being started they will encounter errors similar to:

Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: read init-p: connection reset by peer: unknown

before eventually being able to start correctly.

This may be related to the following issue: https://github.com/moby/moby/issues/40835

**Acceptance criteria**

Pods (which are configured correctly and don't contain any inherent problems / bugs) can start correctly first time without encountering the described error.

**Comment by toschneck** [comment]
Some more related issues arround:
https://github.com/moby/moby/issues/40835 
https://github.com/docker/docker.github.io/issues/7962  

seams this couldn't get stabled reproduced. Maybe the docker/kernel combo is casing the issue, try now newest Flatcar release
![image](https://user-images.githubusercontent.com/4659261/114208922-53647480-995e-11eb-8fb1-9c06a5a5053e.png)

**Comment by toschneck** [comment]
Update unfortunately didn't solve the problem, still:
```
Warning Failed 7m37s kubelet Error: failed to start container "sregproxy": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: read init-p: connection reset by peer: unknown
```

On Ubuntu 20.04 based Nodes the error did not occur

**Comment by kron4eg** [comment]
We've seen this issue before. 

General info: https://www.cloudfoundry.org/blog/the-garden-team-and-the-strange-case-of-a-connection-being-reset/
Kubermatic fix: https://github.com/kubermatic/kubermatic/pull/6467

Please make sure that you don't have any Pods with very-tight cpu/mem limits.

**Comment by irozzo-1A** [comment]
The issue could be indeed related to a low memory limit and `runc` not handling properly the container init phase (see https://bugzilla.redhat.com/show_bug.cgi?id=1904558).

I reproduced the issue with the following worker node (I did not try yet with other settings):

```
$ uname -rv
5.10.25-flatcar #1 SMP Wed Mar 24 17:11:24 -00 2021
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2765.2.2
VERSION_ID=2765.2.2
BUILD_ID=2021-03-24-1749
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2765.2.2 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
$ runc --version
runc version 1.0.0-rc92+dev.docker-19.03
commit: 3d68c79de7184b0eba97946d4f478736f46bf207
spec: 1.0.2-dev
$ cat /etc/kubernetes/kubelet.conf | grep cgroupDriver
cgroupDriver: systemd
```

In order to reproduce I did the following:

```
$ cat << EOF | kubectl create -f -
> apiVersion: v1
> kind: Pod
> metadata:
>   generateName: pause-
>   namespace: default
> spec:
>   containers:
>   - args:
>     - pause
>     image: k8s.gcr.io/pause:3.2
>     name: pause
>     resources:
>       limits:
>         memory: 20M
> EOF
```

And I observed the following:

```
$ kubectl describe pod pause-5g7sk | tail
  Type     Reason                  Age                     From               Message
  ----     ------                  ----                    ----               -------
  Normal   Scheduled               8m2s                    default-scheduler  Successfully assigned default/pause-5g7sk to ip-172-31-55-180.eu-central-1.compute.internal
  Warning  FailedCreatePodSandBox  7m58s (x4 over 8m2s)    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "pause-5g7sk": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: read init-p: connection reset by peer: unknown
  Normal   SandboxChanged          7m58s (x4 over 8m1s)    kubelet            Pod sandbox changed, it will be killed and re-created.
  Warning  Failed                  7m56s                   kubelet            Error: failed to start container "pause": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:359: waiting for our first child to exit caused: signal: killed: unknown
  Normal   Pulled                  7m11s (x4 over 7m57s)   kubelet            Container image "k8s.gcr.io/pause:3.2" already present on machine
  Normal   Created                 7m11s (x4 over 7m57s)   kubelet            Created container pause
  Warning  Failed                  7m10s (x3 over 7m57s)   kubelet            Error: failed to start container "pause": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: read init-p: connection reset by peer: unknown
  Warning  BackOff                 2m58s (x22 over 7m55s)  kubelet            Back-off restarting failed container
```

On the worker node, I can see OOM-killer being triggered with: `dmesg -wHt | grep "oom"`

```
oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=docker-a016c7c57108e10eec66c41c5cb2b37d211c86e887a06f14cd3a1ca91977b4fb.scope,mems_allowed=0,oom_memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod09bbf857_2829_4a63_8a1f_fd27298458b7.slice,task_memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod09bbf857_2829_4a63_8a1f_fd27298458b7.slice/docker-a016c7c57108e10eec66c41c5cb2b37d211c86e887a06f14cd3a1ca91977b4fb.scope,task=runc:[2:INIT],pid=74806,uid=0
Memory cgroup out of memory: Killed process 74806 (runc:[2:INIT]) total-vm:346964kB, anon-rss:4904kB, file-rss:576kB, shmem-rss:696kB, UID:0 pgtables:112kB oom_score_adj:991
oom_reaper: reaped process 74806 (runc:[2:INIT]), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

I verified experimentally on this environment that memory limits <= 20M seem to consistently end up on this issue (please don't take this as a law of nature :-)).

@clive-jevons Could you please verify if this is compatible with what you are observing?

**Comment by clive-jevons** [comment]
Hi @irozzo-1A  - yup, I can confirm the same. With a request of e.g. 5Mi the Pod fails to start with the error message described. If I increase it to, e.g., 50Mi, then it starts no problems.

An additional observation: I accidentally initially configured the Deployment with an Image which the cluster could not pull - in this setup I ran into the OCI Runtime Error rather than an error pulling the image ... not sure if this is relevant, but it hence appears to be something that happens before the image is pulled?

**Comment by irozzo-1A** [comment]
> An additional observation: I accidentally initially configured the Deployment with an Image which the cluster could not pull - in this setup I ran into the OCI Runtime Error rather than an error pulling the image ... not sure if this is relevant, but it hence appears to be something that happens before the image is pulled?

@clive-jevons Interesting, with the elements I have I'm not sure it's related, but feel free to file another issue if needed ;-)

**Comment by toschneck** [comment]
@irozzo-1A I discovered also one more difference, that we using at ubuntu already containerd, couldn't we also switch in flatcar to containrd and see if the error is also present there?
![image](https://user-images.githubusercontent.com/4659261/114598752-8a09fa00-9c92-11eb-9207-afc800042873.png)

**Comment by irozzo-1A** [comment]
@toschneck Both `containerd` and `docker` rely on `runc`, so I would not consider this as discriminant. But very likely the `runc` version plays a role, and maybe kernel as well.

We could definitely try something like:
https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/use-a-custom-docker-or-containerd-version/

**Comment by shaase-ctrl** [comment]
Thanks for the request. If there are anything else, please open another request.
