### ISSUE TITLE
Deprecate and remove Pod Security Policy feature

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#6854]
PodSecurityPolicy is deprecated starting with the Kubernetes 1.21 release. The feature will be removed in the Kubernetes 1.25 release. Currently, there's no built-in replacement, but it's planned for the future.

We should:

Show a warning that PodSecurityPolicy is deprecated if the feature is enabled
Write recommendations for users using PodSecurityPolicy - we can recommend using OPA. 
Schedule feature to be removed once Kubernetes 1.25 goes EOL

More information: https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

**Comment by embik** [comment]
@csengerszabo can this epic be closed?

**Comment by csengerszabo** [comment]
I think yes, but I'll double check it
