### ISSUE TITLE
Cluster Validation Webhook ignores CA Bundle for vSphere

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#6863]
**Bug Report**
At the customer we have the following environment:
- Custom CA-Bundle
- vSphere is secured behind a custom certificate (CA is included in CA Bundle)
- KKP `weekly-2021-13`

Related to #6859, we add the CA to the CA Bundle and the Machine Controller respects it and creates the machines. Unfortunately it's seams the Cluster validation webhook implementation doesn't consider CA bundle at got this error:
```
Error 400 invalid cluster: invalid cloud spec: failed to create vCenter session: Post "https://xxxxx/sdk": x509: certificate signed by unknown authority 
```
![image](https://user-images.githubusercontent.com/4659261/114187531-64a28680-9948-11eb-82ca-b36621141387.png)

This error get produced when a cluster gets created at the UI and blocks the cluster creation.

@shaase-ctrl Please prio this, so we can remove the `insecure=true` flag.

Just for the ref, the CA Bundle is valid:
![image](https://user-images.githubusercontent.com/4659261/114187993-ed212700-9948-11eb-8a36-56594cc559af.png)

**Acceptance criteria**
- Cluster Validation respects CA bundle at cluster creation

**Comment by kron4eg** [comment]
xref https://github.com/kubermatic/kubermatic/pull/6907

**Comment by lsviben** [comment]
Reopening as the error still occurs after the fix
