### ISSUE TITLE
Failure in status=pending if partial creation failed

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#69]
I0922 12:15:59.735642       5 controller.go:318] Syncing cluster "cluster-xdma4f2966"
I0922 12:15:59.736046       5 controller.go:291] Launch timeout for cluster "xdma4f2966" after 23m8.736040036s
I0922 12:15:59.742208       5 controller.go:320] Finished syncing namespace "cluster-xdma4f2966" (6.566312ms)
E0922 12:15:59.742377       5 controller.go:420] Error syncing cluster with key cluster-xdma4f2966: error in phase "Failed" sync function of cluster "xdma4f2966": secrets "apiserver-tls" already exists

**Comment by scruplelesswizard** [comment]
The bug itself has been squashed, but it existed because we set the name of the secret to check for duplicate in the code, but generate the secret from a loaded file. 

To easily resolve this we should read the secret's name and namespace from the file, then check for duplicates using the actual name and namespace, and then deploy the file if it doesn't exist... Magic strings ;)

**Comment by mrIncompetent** [comment]
https://github.com/kubermatic/api/issues/73 targets the improvement
