### ISSUE TITLE
Reconciliation of coredns PodDisruptionBudget failed when upgrading to KKP 2.17

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6912]
The following error log was found in `user-controller-manager` after upgrading from KKP 2.16 to KKP 2.17:

```
{"level":"error","time":"2021-04-20T12:44:36.228Z","caller":"resources/controller.go:226","msg":"Reconciling failed","error":"failed to reconcile PodDisruptionBudgets: failed to ensure PodDisruptionBudget kube-system/coredns: failed to create object *v1beta1.PodDisruptionBudget \"kube-system/coredns\": resourceVersion should not be set on objects to be created"}
```

**Comment by irozzo-1A** [comment]
Thx @imharshita for reporting

**Comment by imharshita** [comment]
Imp: This issue was recognised after performing `MIgration to Operator` i.e, older version was installed through Helm charts (no operator charts) then was migrated to operator following this doc: https://docs.kubermatic.com/kubermatic/v2.17/tutorials_howtos/upgrading/upgrade_from_2.14_to_2.15/chart_migration/

**Comment by moadqassem** [comment]
@imharshita So I have been investigating briefly about this issue, and I have the impression that, the error message is a bit misleading. The PodDisruptionBudget resource is actually created, even though the error message was there, so probably this a transient error. One thing that we must consider however, is watching the  PodDisruptionBudget object once is deleted. The reason behind that is, if the resource is deleted and there was no sync loop happening, and the coredns deployment has been scaled down or removed, there is a good chance that we loose all coredns pods. 

I have actually tested it and I hit that issue two times out of 5. To be safe I would just watch for that resource so it is created as soon as it was deleted and avoid to wait till the next sync loop. 

Here is the PR for it https://github.com/kubermatic/kubermatic/pull/6913

**Comment by irozzo-1A** [comment]
I think that the problem could be the following.

When we ensure `PodDisruptionBudgets` we set re-create flag: 

https://github.com/kubermatic/kubermatic/blob/c6ad6f360e833eb092729c55881fba2d2495dca7/pkg/resources/reconciling/zz_generated_reconcile.go#L354-L356

This means that we delete and create the resource like this:

https://github.com/kubermatic/kubermatic/blob/c6ad6f360e833eb092729c55881fba2d2495dca7/pkg/resources/reconciling/ensure.go#L123-L128

This fails the first time as `resourceVersion` is set to the value coming from the existing object, and it will succeed in successive reconciliations as we delete it.

If my analysis is correct it is transient indeed.
