### ISSUE TITLE
Prepare release notes for KKP 2.17

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6914]
The goal of this task is to prepare a release notes draft to prepare the release notes for the new release (using https://github.com/kubermatic/gchl).

See also: https://github.com/kubermatic/kubermatic/blob/5b7a9dfde744b0d91e40e5547271595e6803559d/docs/release-process.md

**Comment by imharshita** [comment]
This PR adds  changelog for the release https://github.com/kubermatic/kubermatic/pull/6922
