### ISSUE TITLE
Assume role with ExternalId support for AWS

### ISSUE THREAD

**Issue by kirek007** [kubermatic/kubermatic#6921]
**User Story**
I would like to use assume role feature in order to deploy infrastructure in AWS account I don't have other access to using ExternalId role and trusted relationships.

**Acceptance criteria**
During cluster creation in AWS I'm able to provide Role I would like to assume to.

**Comment by moadqassem** [comment]
Hello @kirek007, 

Thank you for providing us with this feature request.  So you propose to provide an aws IAM role and based on that role KKP should be able to create all aws resources such as vms to create a user cluster instead of using aws access key and secret?

**Comment by kirek007** [comment]
Yes. The idea is to deploy clusters into 3rd party account. The safest way is to setup external assume role that resides in 3rd party account. My account is allowed to assume this external role in order to manage resources in 3rd party account using my own key and secret.

**Comment by simon-wessel** [comment]
Machine Controller support, API support and UI support have been added.
/close
