### ISSUE TITLE
Add support for containerd

### ISSUE THREAD

**Issue by stepa-ict** [kubermatic/kubermatic#6930]
**User Story**
Hi there,
I recently gave a try KKP on private DC. The main consideration is the need for containerd CRI. The first try was with kubeadm provider with VMs as worker nodes and it passed ok. When I was preparing the node to join in the cluster, I install containerd CRI and it was good.
The second try was with digitalocean provider and machine deployment is created droplet on DO but by default with docker CRI. I spent a lot of time reading docs and trying to find a solution to set CRI to containerd for machine deployment but with no luck.

**Acceptance criteria**
Option to set desired CRI with labels on machine deployment or with addons.

Thanks in advance.

**Comment by toschneck** [comment]
@shaase-ctrl this is a very valid issue and containerd support at all providers and OS should be part of the next release.

**Comment by kron4eg** [comment]
FYI: Prior to kubernetes 1.22 the default container runtime is `docker`, it's possible to switch to containerd using a machine-controller's flag `-container-runtime=containerd`. For kubernetes >= 1.22 the `-container-runtime` flag will always be set to `containerd`.

So once the Kubermatic API will be in place, it should also influence that flag of machine-controller deployment.

**Comment by stepa-ict** [comment]
Thank you @kron4eg,
It's good to hear that. 
I'll try it in the few next days, and write a response here.
Is there any part of documentation about this flag?
