### ISSUE TITLE
Creating centos machine deployment fails on GCP

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#6932]
KKP dashboard proposes centos as an option for workers os, but when selecting it the md deployment fails with the following error:

```
failed to create initial MachineDeployment: admission webhook "machine-controller.kubermatic.io-machinedeployments" denied the request: validation failed: An error of type = InvalidConfiguration, with message = Invalid or not supported operating system specified "centos": os not supported occurred
```

**Comment by irozzo-1A** [comment]
Same for alibaba cloud

**Comment by zreigz** [comment]
According to the source code:  https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/gce/config.go#L46
the GCP supports only Ubuntu OS. The Centos and Redhat must be removed from the the UI.

**Comment by zreigz** [comment]
I will create a issue for the Dashboard

**Comment by zreigz** [comment]
New issue for the UI: https://github.com/kubermatic/dashboard/issues/3323
