### ISSUE TITLE
API Tokens for programmatic access

### ISSUE THREAD

**Issue by kirek007** [kubermatic/kubermatic#6963]
**User Story**
As a user I would like to integrate Kubermatic with another system that will manage Kubermatic via API. Currently I don't see any way to generate a long live token that could be used for that.
Token can not be bound to any user.
Token can not be bound to any project
Token will have admin rights. (Can create project, cluster, assign users to clusters, download kubeconfigs)

**Acceptance criteria**
It's possible to generate long live API token with admin rights

**Comment by irozzo-1A** [comment]
Hi @kirek007,

Thx for opening this.

@zreigz is this use case covered by https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/service-account-v2.md?

**Comment by zreigz** [comment]
We going to extend the existing service account to be able to create and manage projects. We would like to keep service accounts as a project scope resources with some extra privileges.

**Comment by HaveFun83** [comment]
We have the same requirement here.

**Comment by kirek007** [comment]
@zreigz Is there any ETA for that? 
I would like to be able to manage projects via API. Is it possible to generate that kind of token right now?

**Comment by zreigz** [comment]
@kirek007 I've introduced the `project managers` group for SA on the master version. The SA in this group can manage projects/members/SA. Can't interact with clusters.

Described here: https://docs.kubermatic.com/kubermatic/master/guides/service_account/using_service_account/
Chapter: `Using service accounts with KKP`

**Comment by kirek007** [comment]
@zreigz does it mean that `project manager` has to create new project and a new SA with `editor` permission and use the editor account to create cluster?

**Comment by zreigz** [comment]
exactly
