### ISSUE TITLE
Extend service account functionality to support project creation

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#6983]
**User Story**
A service account is assigned to one of the already defined groups: `editors` or `viewers`. The goal is to add a new group. If SA is assigned to this new group then can create a project. To be able to create a new project by SA the human user must be specified to avoid the situation when a newly created project is orphan. 

**Acceptance criteria**
The new group can be selected during SA creation
During SA creation with this new group, the list of the human user must be specified.
All defined human users from the list are owners of the newly created project and the SA has (owner or editor: must be discussed ) rights.

**Comment by shaase-ctrl** [comment]
- The SA should only be able to to this, if it has editors permission, correct? 
- The question is if we need any other permission for the SA then editor? 
- Does a viewers permission make sense on a SA?
- What happens if all people associated to the group loose access to KKP?
- How do we revoke access for the token itself?

**Comment by scheeles** [comment]
We should have a group `projectmanagers` (name tbd) this group can only do Create/Update/Delete projects and Add/Remove members & service accounts. No cluster view/edit rights. 

> * The SA should only be able to to this, if it has editors permission, correct?

No if he has the new group permission 
> * The question is if we need any other permission for the SA then editor?
> * Does a viewers permission make sense on a SA?

Yes perhaps you only want to collect status information via a SA from KKP 
> * What happens if all people associated to the group loose access to KKP?

This problem today already exist. If the Owners don't have access anymore the KKP Admin needs to fix this
> * How do we revoke access for the token itself?

Already available you can delete the token via api/UI

**Comment by zreigz** [comment]
@shaase-ctrl @scheeles thanks for the explanation and thoughts. Now I know the new group `projectmanagers` (like the name) can manage only projects, project members, and project SAs. This is the most valid information for me from an implementation perspective.
