### ISSUE TITLE
Plaform Extension mechanism

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#6992]
**User Story**
As a cluster admin/developer I want to rely on better mechanism to add extensions to my cluster than the current addons implementation which should stay simple. I expect that mechanism will support proper reconciliation of an extension. Currently we are strugling with more complex projects to add them to KKP (like KubeVirt).

**Acceptance criteria**
* Platform extension mechanism that is able to manage extensions like KubeVirt, Multus etc.
* Clear definition of an extension (what is and what it is not)

**Comment by shaase-ctrl** [comment]
@SimonTheLeg can we close this as this is now "applications"?

**Comment by SimonTheLeg** [comment]
No I don't think so. I think this issue specifically targets highly complex components like KubeVirt or Network CNIs, which cannot be handled with applications.

**Comment by mfranczy** [comment]
as I understood sig-networking plans to deliver CNI plugins as applications, is that correct @rastislavs?

**Comment by rastislavs** [comment]
> as I understood sig-networking plans to deliver CNI plugins as applications, is that correct @rastislavs?

yes, see https://github.com/kubermatic/kubermatic/pull/11353
