### ISSUE TITLE
Bare Metal Provisioning in KKP using TB driver 

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#7015]
**User Story**
As a user, I would like to create a bare metal user cluster using KKP. The current approach is, creating a KubeAdm cluster, which will create the control plane components and then run some kubeadm commands on the pre-existed worker nodes so that they join the cluster. Since machine controller v1.28.0, it is possible to provision bare metal worker nodes using [TinkerBell](https://tinkerbell.org/) driver to provision those machines and eventually join the user cluster.
   
**Acceptance criteria**
- Bare metal provider is supported on the api level to communicate with the API. 
- Bare metal provider is supported in the UI and some of the configs could be on a DC level such as TinkerBell related config(tink-server and image repo)
- Full blown e2e tests with the proper infrastructure could be vSphere but ideally equinix since TB is pretty much compatible with it.
- Documentation about setting up the TB provisioner in general and also the creation of bare metal user clusters

**Comment by csengerszabo** [comment]
Can this be closed? @moadqassem @cschieder if yes, please close, if no, please comment what's missing

**Comment by moadqassem** [comment]
Yes I guess so. If we need to work more on this topic a new ticket should be created as some of these requirements are kinda outdated
