### ISSUE TITLE
Initial nodes are never prosioned (aws)

### ISSUE THREAD

**Issue by kirek007** [kubermatic/kubermatic#7035]
**User Story**
As a User I'm creating a cluster in AWS. Control Plane components are up and running while nodes stays in "not provisioned state". By not provisioned state I mean that EC2 instances are created, machine-deploymeny sends enevet that found there instances (including proper Ip address) but they are not join cluster. Machine-deployment controller still sends events that ec2 instances are there but nodes are not assigned to ec2.
It's not happening always, but it already happen 4 or 5 times. 

Is it a known issue? Where should I start looking for some useful log? 
I've checked all machine,machineset and machinedeployment objects for some events, but there was none (except hundreds events that  ec2 instances is found). I've also checked machine-controller logs without luck. 

I'm using KKP 2.17
**Acceptance criteria**
Initial nodes should join cluster.

**Comment by kron4eg** [comment]
Please ssh to the instance and watch for setup logs (`journalctrl -fu setup`), there should be some indications why it failed.

**Comment by kirek007** [comment]
Thanks @kron4eg for information, are there any default credentials I can use to ssh into machine (before user ssh agent deployemnt)?

**Comment by kirek007** [comment]
Looks like this is related to deploying worker nodes to the subnet that doesn't have access to the internet.

What's more interesting is that the root cause was an option "Assign public IP" in UI that is broken because if there is no value provided it's NULL (empty box) but public IP is assigned. I'll create dedicated ticket for that
