### ISSUE TITLE
Clean up Alertmanager RBAC  for user impersonation clients

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/kubermatic#7086]
Currently, if monitoring is enabled for user cluster MLA, RBAC objects will be created for user impersonation clients to work with ALertmanager APIs. If the user disables monitoring later, those RBAC objects will not be removed.
Although those RBAC objects doesn't hurt, we should probably clean them up if monitoring is disabled.

**Comment by rastislavs** [comment]
Closing as not necessary for now.
