### ISSUE TITLE
kubermatic gets confused from multiple kubeconfig files generated by kubeone

### ISSUE THREAD

**Issue by shibumi** [kubermatic/kubermatic#7093]
**User Story**

Hello Kubermatic,

I am working on a new blog post right now. The idea is to have a good tutorial for deploying Kubermatic on Hetzner.
While doing so I have encountered an issue that I do not understand.

What I have so far:

I have downloaded the kubeone repository and created a master kubernetes cluster as described here: https://shibumi.dev/posts/kubernetes-on-hetzner-in-2021/

The cluster is functional and ready. I can connect to it and the API is responding:

```
❯ kg nodes
NAME                                 STATUS   ROLES    AGE     VERSION
node/master-control-plane-1          Ready    master   13m     v1.19.3
node/master-control-plane-2          Ready    master   12m     v1.19.3
node/master-control-plane-3          Ready    master   11m     v1.19.3
node/master-pool1-677d454446-cgfx8   Ready    <none>   7m55s   v1.19.3
```

My next step was:

1. Downloading the kubermatic-installer CE 2.16.10
2. modifying the kubermatic config and the value conf accordingly.
3. Running: ./kubermatic-installer deploy --config examples/kubermatic.example.ce.yaml --helm-values examples/values.example.yaml --storageclass hetzner

kubermatic.example.ce.yaml has the following changes:

* new domain
* generated secrets

values.example.yaml has the following changes:

* new domain
* generated secrets
* new mail for static login

When running the command in step 3 I get the following error message:

```
❯ ./kubermatic-installer deploy --config examples/kubermatic.example.ce.yaml --helm-values examples/values.example.yaml --storageclass hetzner
INFO[02:47:46] 🛫 Initializing installer…                     edition="Community Edition" version=v2.16.10
INFO[02:47:46] 🚦 Validating the provided configuration…
WARN[02:47:46]    Helm values: kubermaticOperator.imagePullSecret is empty, setting to spec.imagePullSecret from KubermaticConfiguration
INFO[02:47:46] ✅ Provided configuration is valid.
ERRO[02:47:46] ❌ Operation failed: failed to construct mgr: Unauthorized.
```

Do you have any idea?

**Comment by kron4eg** [comment]
Seems like you didn’t species correct KUBECONFIG.

**Comment by shibumi** [comment]
@kron4eg  I did. Even with doing: --kubeconfig <path to the kubeconfig generated by kubeone or via doing --kube-context <context I have selected right now>.

**Comment by shibumi** [comment]
@kron4eg 

```
$ terraform output -json > output.json
$  kubeone apply -m kubeone.yaml --tfjson output.json
$ cp master-kubeconfig $HOME/.kube/config
$ kubectl get nodes 
NAME                                 STATUS   ROLES    AGE     VERSION
master-control-plane-1          Ready    master   6m33s   v1.19.3
master-control-plane-2          Ready    master   5m42s   v1.19.3
master-control-plane-3          Ready    master   4m42s   v1.19.3
master-pool1-574797b5c9-znwsc   Ready    <none>   49s     v1.19.3
$ cd ../kubermatic-installer
$ ./kubermatic-installer -v deploy --config examples/kubermatic.example.ce.yaml --helm-values examples/values.example.yaml --storageclass hetzner --kubeconfig ~/.kube/config
DEBU[15:15:53] $ KUBECONFIG=/home/chris/.kube/config helm version --client --template {{ .Version }}
INFO[15:15:53] 🛫 Initializing installer…                     edition="Community Edition" git=a751f7e62f866d0fa8b1d2805400977ac909481e version=v2.16.10
INFO[15:15:53] 🚦 Validating the provided configuration…
WARN[15:15:53]    Helm values: kubermaticOperator.imagePullSecret is empty, setting to spec.imagePullSecret from KubermaticConfiguration
INFO[15:15:53] ✅ Provided configuration is valid.
ERRO[15:15:53] ❌ Operation failed: failed to construct mgr: Unauthorized.
$ kubectl get nodes
NAME                            STATUS   ROLES    AGE     VERSION
master-control-plane-1          Ready    master   10m     v1.19.3
master-control-plane-2          Ready    master   9m39s   v1.19.3
master-control-plane-3          Ready    master   8m39s   v1.19.3
master-pool1-574797b5c9-znwsc   Ready    <none>   4m46s   v1.19.3
```

This definitely does not work as intended. Or did I forget anything?


Some version numbers (kubectl):

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-04-09T16:47:30Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

helm:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

kubeone:

```
{
  "kubeone": {
    "major": "1",
    "minor": "2",
    "gitVersion": "v1.2.1",
    "gitCommit": "51a3729d1f5868e740861bec9fb6b8083bebf6ec",
    "gitTreeState": "",
    "buildDate": "2021-05-01T00:07:37+00:00",
    "goVersion": "go1.16.3",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "machine_controller": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.0",
    "gitCommit": "",
    "gitTreeState": "",
    "buildDate": "",
    "goVersion": "",
    "compiler": "",
    "platform": "linux/amd64"
  }
}
```

kubermatic-installer:
```
❯ ./kubermatic-installer version
Component                              | Version                                  | App Version
---------------------------------------+------------------------------------------+------------------------------
Kubermatic Community Edition Installer | a751f7e62f866d0fa8b1d2805400977ac909481e | v2.16.10
alertmanager                           | 2.0.14                                   | v0.21.0
blackbox-exporter                      | 1.0.8                                    | v0.17.0
cert-manager                           | 1.4.2                                    | v0.16.1
grafana                                | 1.4.9                                    | 7.1.5
helm-exporter                          | 1.0.6                                    | 0.4.3
iap                                    | 3.1.2                                    | v6.1.1
karma                                  | 0.0.13                                   | v0.68
kube-state-metrics                     | 1.0.10                                   | v1.9.7
kubermatic-operator                    | 0.2.6                                    | v2.16.10
loki                                   | 0.0.10                                   | v1.6.1
minio                                  | 1.0.20                                   | RELEASE.2020-09-10T22-02-45Z
nginx-ingress-controller               | 1.1.9                                    | 0.44.0
node-exporter                          | 1.1.0                                    | v1.0.1
nodeport-proxy                         | 1.6.1                                    | v2.16.10
oauth                                  | 1.5.1                                    | v2.24.0
prometheus                             | 2.3.1                                    | v2.23.0
promtail                               | 0.1.6                                    | v1.6.1
s3-exporter                            | 1.1.4                                    | v0.4
velero                                 | 1.4.8                                    | v1.5.3
```

**Comment by shibumi** [comment]
Hey everybody, so after another weekend of debugging I found the issue.
It has something to do with my kubeconfig.

I generate my `KUBECONFIG` export variable as follows:

`KUBECONFIG="$(find ~/.kube/configs/ -type f -exec printf '%s:' '{}' +)"`

This produces a variable like this:

```
/home/chris/.kube/configs/REDACTED-stage-kubeconfig:/home/chris/.kube/configs/REDACTED-production-kubeconfig:/home/chris/.kube/configs/REDACTED-master-kubeconfig:
```

With kubectl this works perfectly fine, but kubermatic seems to get confused by it:

Output with my KUBECONFIG variable set + alternative path to a single config file with just one cluster:
```
❯ ./kubermatic-installer deploy --config examples/kubermatic.example.ce.yaml --helm-values examples/values.example.yaml --storageclass hetzner --kubeconfig ~/.kube/config
INFO[15:02:12] 🛫 Initializing installer…                     edition="Community Edition" version=v2.16.10
INFO[15:02:12] 🚦 Validating the provided configuration…
WARN[15:02:12]    Helm values: kubermaticOperator.imagePullSecret is empty, setting to spec.imagePullSecret from KubermaticConfiguration
INFO[15:02:12] ✅ Provided configuration is valid.
ERRO[15:02:12] ❌ Operation failed: failed to construct mgr: Unauthorized.
```

Output with my KUBECONFIG set and no --kubeconfig parameter being used:
```
❯ ./kubermatic-installer deploy --config examples/kubermatic.example.ce.yaml --helm-values examples/values.example.yaml --storageclass hetzner
INFO[15:03:00] 🛫 Initializing installer…                     edition="Community Edition" version=v2.16.10
INFO[15:03:00] 🚦 Validating the provided configuration…
WARN[15:03:00]    Helm values: kubermaticOperator.imagePullSecret is empty, setting to spec.imagePullSecret from KubermaticConfiguration
INFO[15:03:00] ✅ Provided configuration is valid.
ERRO[15:03:00] ❌ Operation failed: failed to construct mgr: Unauthorized.
```

In both cases a simple `kubectl get nodes` works as expected, but kubermatic fails. If I remove the KUBECONFIG variable entirely and just specify the kubeconfig via the `--kubeconfig` parameter it works as expected:

```
❯ ./kubermatic-installer deploy --config examples/kubermatic.example.ce.yaml --helm-values examples/values.example.yaml --storageclass hetzner --kubeconfig ~/.kube/config
INFO[14:53:19] 🛫 Initializing installer…                     edition="Community Edition" version=v2.16.10
INFO[14:53:19] 🚦 Validating the provided configuration…
WARN[14:53:19]    Helm values: kubermaticOperator.imagePullSecret is empty, setting to spec.imagePullSecret from KubermaticConfiguration
INFO[14:53:19] ✅ Provided configuration is valid.
INFO[14:53:19] 🧩 Deploying kubermatic stack…
INFO[14:53:19]    💾 Deploying kubermatic-fast StorageClass…
INFO[14:53:20]    ✅ Success.
INFO[14:53:20]    📦 Deploying nginx-ingress-controller…
INFO[14:53:21]    ✅ Success.
INFO[14:53:21]    📦 Deploying cert-manager…
INFO[14:53:21]       Deploying Custom Resource Definitions…
......
```

I will change the issue title accordingly.

**Comment by shibumi** [comment]
Another update. The reason for all of this seem to be the same user name generated by kubeone for different clusters:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://49.12.22.127:6443
  name: master
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.88.10.10:6443
  name: ob-stage
contexts:
- context:
    cluster: master
    user: kubernetes-admin
  name: kubernetes-admin@master
- context:
    cluster: ob-stage
    namespace: chartmuseum
    user: kubernetes-admin
  name: kubernetes-admin@ob-stage
current-context: kubernetes-admin@ob-stage
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

I do not think this is related to Kubermatic, hence I am closing this ticket here.

**Comment by almereyda** [comment]
Did you at some point consider filing this against KubeOne, as in is this an actual issue that will most probably resurface in other environments?

**Comment by shibumi** [comment]
@almereyda good point! I will open an issue for this for KubeOne.

**Comment by udupicloud** [comment]
Hi everyone,

I am new to KKP. I have deployed this on-prime. I need help for this issue given below.
I did not find any proper document step wise to Install and configure KKP from scratch.

ceph@node3:~$ ./kubermatic-installer deploy --config examples/kubermatic.example.yaml --helm-values examples/values.example.yaml --storageclass azure  --kubeconfig ~/.kube/config
INFO[0000] 🚀 Initializing installer…                     edition="Community Edition" version=v2.21.1
INFO[0000] 🚦 Validating the provided configuration…     
WARN[0000]    Helm values: kubermaticOperator.imagePullSecret is empty, setting to spec.imagePullSecret from KubermaticConfiguration 
INFO[0000] ✅ Provided configuration is valid.           
INFO[0000] 🚦 Validating existing installation…          
INFO[0001] ✅ Existing installation is valid.            
INFO[0001] 🛫 Deploying KKP master stack…                
INFO[0001]    💾 Deploying kubermatic-fast StorageClass… 
INFO[0001]    ✅ StorageClass exists, nothing to do.     
INFO[0001]    📦 Deploying nginx-ingress-controller…     
INFO[0001]       Deploying Helm chart…                  
INFO[0001]       Release is up-to-date, nothing to do. Set --force to re-install anyway. 
INFO[0004]    ✅ Success.                                
INFO[0004]    📦 Deploying cert-manager…                 
INFO[0004]       Deploying Custom Resource Definitions… 
INFO[0005]       Deploying Helm chart…                  
INFO[0005]       Release is up-to-date, nothing to do. Set --force to re-install anyway. 
INFO[0008]    ✅ Success.                                
INFO[0008]    📦 Deploying Dex…                          
INFO[0008]       Release is up-to-date, nothing to do. Set --force to re-install anyway. 
INFO[0008]    ✅ Success.                                
INFO[0008]    📦 Deploying Kubermatic Operator…          
INFO[0008]       Deploying Custom Resource Definitions… 
INFO[0012]       Migrating UserSSHKeys…                 
INFO[0012]       Migrating Users…                       
INFO[0012]       Migrating ExternalClusters…            
INFO[0012]       Deploying Helm chart…                  
INFO[0012]       Release is up-to-date, nothing to do. Set --force to re-install anyway. 
INFO[0012]    ✅ Success.                                
INFO[0012]    📝 Applying Kubermatic Configuration…      
INFO[0012]    ✅ Success.                                
ERRO[0012] ❌ Operation failed: failed to apply Kubermatic Configuration: KubermaticConfiguration.kubermatic.k8c.io "kubermatic" is invalid: spec.ingress.certificateIssuer.apiGroup: Invalid value: "null": spec.ingress.certificateIssuer.apiGroup in body must be of type string: "null". 
ceph@node3:~$ 

Please help

**Comment by almereyda** [comment]
Hi @udupicloud please open a new issue at https://github.com/kubermatic/kubermatic/issues/new/choose so your experienced regression can be analysed independently from this conversation here, which had been closed already.

**Comment by udupicloud** [comment]
Thanks @almereyda
