### ISSUE TITLE
Integration of AWS

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#71]
- [ ] Investigate the integration of AWS 
- [ ] How do we handle Region/Zones (DC only support Datacenter)
- [ ] Check if we create an own AMI with all deps

**Comment by scheeles** [comment]
We can reuse some of the docker machine coding:

https://github.com/docker/machine/tree/master/drivers/amazonec2

**Comment by lbb** [comment]
@scheeles Wouldn't we have to refactor the old providers ?
Or was it meant to just reuse some of the code ?

**Comment by scheeles** [comment]
I an first phase copy 1 to 1 as it is for DC.

Which the #81 we will refactor it an move to clear interface

**Comment by scruplelesswizard** [comment]
@realfake What is the status on this?

**Comment by lbb** [comment]
What has been done:
* Creation of aws cluster provider
    - Adding aws dc to datacenter.yaml
    - Rebuild helm packages  
    - Deployed new packages
    - SUCCESSfully adding an was provider
* Adding a node / Creating a node.
    - ISSUE: template is missing error is generated in line https://github.com/kubermatic/api/blob/feature/aws-integration-provider/provider/cloud/aws/provider.go#L168
