### ISSUE TITLE
Impossible to evict kubermatic-master-controller-manager

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#7110]
error when evicting pod "kubermatic-master-controller-manager-c5896967c-7wcxt" (will retry after 5s): 
Cannot evict pod as it would violate the pod's disruption budget.
evicting pod kubermatic/kubermatic-master-controller-manager-c5896967c-7wcxt

The pod disruption budget does not tolerate any disruptions:
```
kubectl get poddisruptionbudgets.policy -n kubermatic kubermatic-master-controller-manager
NAME                                   MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
kubermatic-master-controller-manager   1               N/A               0                     20d
```

**Comment by xrstf** [comment]
How would you suggest we fix this? Honest question :) Should the operator only create the PDB if the replica count is >= 2?

**Comment by kron4eg** [comment]
@xrstf yeah, seems like so. And in absent of additional replicas PDBs don't make sense.
