### ISSUE TITLE
Migrating Metrics Server to User Cluster in Konnectivity Setup

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#7113]
API extension servers are not supported in the control networks when using Konnectivity, this means that the `metrics-server` has to be moved on the user-cluster side as a pre-requisite.

Find more information here: https://github.com/kubernetes/kubernetes/issues/92374

**Comment by PratikDeoghare** [comment]
We most likely won't do this. Waiting for feedback on https://kubermatic.slack.com/archives/D02787P896F/p1628762657000600

**Comment by rastislavs** [comment]
Turned out as not necessary for the integration of KKP with Konnectivity.

**Comment by rastislavs** [comment]
After reconsideration, we decided to continue with this store to simplify the networking stack even further.
