### ISSUE TITLE
Introduce feature gate for Konnectivity deployment

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#7114]
The goal of this task is to introduce a feature gate, to be used to enable the usage of Konnectivity instead of OpenVPN.
The feature gate should be added by default on newly created clusters, so that they make use of Konnectivity. 

https://github.com/kubermatic/kubermatic/blob/4061ff2771fd0261f1e5fce5cf06f3947ec4f0fc/pkg/features/features.go#L25-L56

**Comment by PratikDeoghare** [comment]
The PR adds the feature gate but does not make it default for new installations as required by https://github.com/kubermatic/kubermatic/issues/7114

> The feature gate should be added by default on newly created clusters, so that they make use of Konnectivity.

This will be the last task after implementing Konnectivity.

**Comment by almereyda** [comment]
Now that #7504 has been merged, and the feature gate seems present, @rastislavs left a last comment in https://github.com/kubermatic/kubermatic/pull/7504#issuecomment-912396775 to return here:

> The only thing I wish this would include is a per-user cluster option for enabling Konnectivity, as right now it will be enabled for whole KKP installation by the feature gate. That can be quite risky for existing KKP deployments :) But I guess this can be done in a future change as well.

Looking forward to the release of 2.18 and eager to test pre-releases, when they arrive.

**Comment by moadqassem** [comment]
@PratikDeoghare Can you please review this?

**Comment by rastislavs** [comment]
@PratikDeoghare I don't think we should keep this issue open until Konnectivity is finally enabled as default, as we have a whole epic for Konenctivity (#6188) and making it the default should be the last step in it. Therefore I created a separate issue under the Konenctivity epic for making it the default (#8129). Closing this one as the feature gate is already implemented.
