### ISSUE TITLE
bump cert-manager API version v1alpha2 -> v1

### ISSUE THREAD

**Issue by irbekrm** [kubermatic/kubermatic#7119]
`cert-manager` is deprecating all alpha and beta API versions in the next release (see [cert-manager#4021](https://github.com/jetstack/cert-manager/pull/4021)) and will be removing them in `v1.6`.

`v1` API has been available since `cert-manager` `v1.0.0`-  it might now make sense for `kubermatic` to bump the API version `v1alpha2` -> `v1` i.e [here]( https://github.com/kubermatic/kubermatic/blob/master/pkg/install/stack/kubermatic-master/certmanager.go).

**Comment by xrstf** [comment]
This has been fixed in #7633.
