### ISSUE TITLE
Add binary to create and configure agent dummy interface

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#7123]
When the Tunneling expose strategy is used, envoy-agent pods are deployed to KKP user clusters via a daemonset. These pods run in the host network namespace and bind to a hardcoded IP `192.168.30.10`. The interface `envoyagent` with this IP is created by an init container of the envoy-agent pod.

The aim of this task is to address some limitations of this approach - try to recover from errors & handle them properly - make sure that the interface is continuously reconciled, e.g. if it is deleted or if it's IP is manually changed on the node.

**Comment by rastislavs** [comment]
Done in https://github.com/kubermatic/kubermatic/pull/11432
