### ISSUE TITLE
Provider list empty

### ISSUE THREAD

**Issue by shibumi** [kubermatic/kubermatic#7145]
**User Story**

The provider list is empty on a fresh installed kubermatic instance on hetzner.
Has this something to do with my invalid staging certificate? I couldn't manage to switch to production. I forgot to change the `letsencrypt-staging` entry before the installation. I changed it afterwards, but the cert-manager seems to give me a staging certificate although the ingress is configured with a production certificate.

I started my chromium with `chromium --ignore-certificate-errors` to have at least a look on the kubermatic UI, but the provider list is empty:

![https://kurisu.shibumi.dev/share/img-2021-05-30-15-50-02.png](https://kurisu.shibumi.dev/share/img-2021-05-30-15-50-02.png)

**Acceptance criteria**

**Comment by kron4eg** [comment]
You seemed to forgot to configure your datacenter: https://docs.kubermatic.com/kubermatic/v2.17/tutorials_howtos/administration/dynamic_data_centers/

**Comment by shibumi** [comment]
Thanks. I did not know that I MUST have a seed cluster. I thought I could just create a master cluster with kubermatic and that's it.
I think I even saw a picture that depicts that I can use just one master cluster instead.

Would you recommend seed clusters for a small setup?

EDIT: Ah never mind. I can directly edit the seed cluster resource and apply it to master to get a mixed-cluster.

**Comment by shibumi** [comment]
Closing this. Questions has been answered :)
