### ISSUE TITLE
Under CRI-O, openvpn-server doesn't initialize

### ISSUE THREAD

**Issue by cns-ubiwhere** [kubermatic/kubermatic#7147]
**User Story**

While using a Seed cluster that uses CRI-O, openvpn-server doesn't initialize properly as iptables fails on the InitContainer. It works ok with containerd.
Upon investigation, the issue seems to be that the capability NET_RAW is needed but missing on the container. This may stem from the fact that CRI-O v1.18.0 had the following API change:

> CRI-O now runs containers without NET_RAW and SYS_CHROOT capabilities by default. This can result in permission denied errors when the container tries to do something that would require either of these capabilities. For instance, using ping requires NET_RAW, unless the container is given the sysctl net.ipv4.ip_forward. Further, if you have a container that runs buildah or configures RPMs, they may fail without SYS_CHROOT. Ultimately, the dropped capabilities are worth it, as the majority of containers don't need them. The fewer capabilities CRI-O gives out by default, the more secure it is by default. (#3119, @haircommander)

**Acceptance criteria**

`openvpn-server` pods are able to start when the seed cluster uses CRI-O as container runtime.

**Comment by irozzo-1A** [comment]
Adding the `NET_RAW` capability in the security context should make it:

https://github.com/kubermatic/kubermatic/blob/38b39ba9994b4ef75155c9607400c59c4cc8a421/pkg/resources/openvpn/deployment.go#L172

I'm not sure it's easy/worthy to put in place some logic to add it conditionally.

**Comment by cns-ubiwhere** [comment]
I apologize for intruding but imho if I understood the issue correctly, and I may be wrong there, NET_RAW is always a part of the required capabilities. It's just that containerd has it by default, and CRI-O used to at some point but changed that. Meaning that adding it will only make it explicit, and not really change anything for the containerd runtime case. Being explicit about a needed capability seems good, and there would be no practical value on having it conditional.

**Comment by irozzo-1A** [comment]
> I apologize for intruding but imho if I understood the issue correctly, and I may be wrong there, NET_RAW is always a part of the required capabilities. It's just that containerd has it by default, and CRI-O used to at some point but changed that. Meaning that adding it will only make it explicit, and not really change anything for the containerd runtime case. Being explicit about a needed capability seems good, and there would be no practical value on having it conditional.

@cns-ubiwhere, do you mean that adding `NET_RAW` capability won't fix the issue? Did you try?

**Comment by cns-ubiwhere** [comment]
@irozzo-1A it does fix the issue for me yes :). The comment was only discussing this: "I'm not sure it's easy/worthy to put in place some logic to add it conditionally.". Imho if I understood this right, it makes more sense to add it unconditionally.

**Comment by irozzo-1A** [comment]
@cns-ubiwhere I see what you meant, I'm not sure either but it would explain. Thx for your comment.

**Comment by haircommander** [comment]
(CRI-O dev here, nice to meet y'all)

Glad to hear the issue was found! yeah I agree I don't think it is realistic to add it conditionally. 

> Being explicit about a needed capability seems good, and there would be no practical value on having it conditional.

+1, if an application needs *any* capabilities, they should be passed manually, to ensure the CRI implementation does the right thing. The default capabilities provided by CRI-O is not a guaranteed API (whereas specifically added/dropped ones are)

**Comment by irozzo-1A** [comment]
@haircommander @cns-ubiwhere now that we are on the same page, the fix is quite trivial. Contributions are welcome if you are motivated ;-)
