### ISSUE TITLE
Installer fails on Kubernetes 1.21

### ISSUE THREAD

**Issue by stroebitzer** [kubermatic/kubermatic#7160]
**User Story**

On running the installer on a cluster running on GCP installed via KubeOne Dex is not coming up with the following exception

`time="2021-06-01T14:20:14Z" level=info msg="config issuer: https://hubert.lab.kubermatic.io/dex"
failed to initialize storage: failed to inspect service account token: jwt claim "kubernetes.io/serviceaccount/namespace" not found
`

This happens with Kubermatic versions 2.16.10 and 2.17.0

After re-creation of the cluster in version 1.20.7 everything looks fine again.

**Acceptance criteria**

The installer is able to install Dex.

**Comment by mate4st** [comment]
duplicate of https://github.com/kubermatic/kubermatic/issues/7051
