### ISSUE TITLE
Visualize Seed Clusters and Connections

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#7170]
**User Story**
As a kkp operator, I want to get a visual overview about my KKP architecture so that I can orient myself much better.

**Acceptance criteria**
- Display KKP visually
- Display the connected seeds in an overview
- Display the connected user clusters attached to a seed

**Comment by cschieder** [comment]
Closed due to reduced scoping discussed in [Investigate how to display the connections between regions, seeds, datacenters and user clusters#8951](https://app.zenhub.com/workspaces/work-in-progress---team-product-606ec73090e027001169c9e7/issues/kubermatic/kubermatic/8951 )
