### ISSUE TITLE
Cannot delete service accounts

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/kubermatic#7190]
**User Story**
I have service accounts with 2 tokens:
<img width="908" alt="Zrzut ekranu 2021-06-7 o 15 40 48" src="https://user-images.githubusercontent.com/2823399/121026944-dc552c00-c7a6-11eb-920d-0e7f2e7415a9.png">

After trying to delete it, there is `200` response from the API, the tokens are gone but the service account stays there:
<img width="1647" alt="Zrzut ekranu 2021-06-7 o 15 41 21" src="https://user-images.githubusercontent.com/2823399/121027052-f4c54680-c7a6-11eb-82bc-961c7e1bcff5.png">

<img width="595" alt="Zrzut ekranu 2021-06-7 o 15 43 23" src="https://user-images.githubusercontent.com/2823399/121027260-1d4d4080-c7a7-11eb-83be-a5f8e5db23d4.png">

EDIT: What is even more strange, after refreshing the page the tokens are still there (there may be UI issue as well).

**Acceptance criteria**
The service account should be deleted when API sends `200` as a response.

**Comment by zreigz** [comment]
Some controller added a finalizer to all SA. Now it's fixed and I removed them manually and works

**Comment by zreigz** [comment]
@maciaszczykm please check and close the issue

**Comment by maciaszczykm** [comment]
It works, thanks.
