### ISSUE TITLE
Update customer clusters

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#72]
https://github.com/kubermatic/api/pull/68 migrates already all RC to deps. 

Now we need a function to upgrade and downgrade the Cluster
- [x] Update the master: https://github.com/kubermatic/api/issues/80
- [ ] Update nodes

**Comment by scruplelesswizard** [comment]
Updates on the nodes is relatively easy. We can just set a key in etcd, read the key and write it to an env file. Have the unit file for the kubelet pull the kubelet down using an EnvironmentFile directive, and you are done.

**Comment by s-urbaniak** [comment]
Another idea I had was to use bootkube to bootstrap/update customer cluster objects, or even the seed cluster, by using bootkube. [1] shows a silly showcase on how to bootstrap a small k8s cluster on DO. More info in [2], and [3].

[1] https://github.com/s-urbaniak/k8sdo
[2] https://github.com/kubernetes-incubator/bootkube
[3] https://docs.google.com/document/d/1VNp4CMjPPHevh2_JQGMl-hpz9JSLq3s7HlI87CTjl-8/edit

Note this would imply a bigger intrusive change in the existing codebase. Back then bootkube didn't exist yet.

**Comment by s-urbaniak** [comment]
[4] https://www.youtube.com/watch?v=tXyV3IQ8-0k

**Comment by sttts** [comment]
Does one really want to update nodes in place? GKE doesn't do that, but replaces the machine in a rolling fashion.

**Comment by scruplelesswizard** [comment]
@sttts on cloud providers just replacing is a good option, my only concern is accomplishing that with the BringYourOwn nodes

**Comment by sttts** [comment]
For BringYourOwn you use the local packager like apt-get or yum/dnf/zypper. That case we can not really automate.
