### ISSUE TITLE
Bad error message on misconfigured gce datacenter in seed yaml file

### ISSUE THREAD

**Issue by stroebitzer** [kubermatic/kubermatic#7203]
**User Story**

On creating a KKP installation on GCE I ran into this error message

`E0609 13:02:29.578160       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 729 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3100640, 0xc00129e120)
        k8s.io/apimachinery@v0.19.4/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.19.4/pkg/util/runtime/runtime.go:48 +0x89
panic(0x3100640, 0xc00129e120)
        runtime/panic.go:969 +0x175
k8c.io/kubermatic/v2/pkg/resources/cloudconfig.CloudConfig(0xc001a61400, 0xc0001da600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        k8c.io/kubermatic/v2/pkg/resources/cloudconfig/configmap.go:181 +0x1167
k8c.io/kubermatic/v2/pkg/resources/cloudconfig.ConfigMapCreator.func1.1(0xc001410000, 0xc000bc3110, 0x478925, 0x2d51460)
        k8c.io/kubermatic/v2/pkg/resources/cloudconfig/configmap.go:63 +0x158
k8c.io/kubermatic/v2/pkg/resources/reconciling.ConfigMapObjectWrapper.func1(0x38840a0, 0xc001410000, 0x16, 0x38ecf80, 0x3866420, 0x38ecf80)
        k8c.io/kubermatic/v2/pkg/resources/reconciling/zz_generated_reconcile.go:149 +0x4d
k8c.io/kubermatic/v2/pkg/resources/reconciling.createWithNamespace.func1(0x38840a0, 0xc001410000, 0x2db68c0, 0xc0014480a0, 0xc000bc3110, 0x11c473b)
        k8c.io/kubermatic/v2/pkg/resources/reconciling/ensure.go:44 +0x4f
k8c.io/kubermatic/v2/pkg/resources/reconciling.createWithName.func1(0x38840a0, 0xc001410000, 0x0, 0x0, 0x0, 0x0)
        k8c.io/kubermatic/v2/pkg/resources/reconciling/ensure.go:55 +0x4f
k8c.io/kubermatic/v2/pkg/resources/reconciling.OwnerRefWrapper.func1.1(0x38840a0, 0xc001410000, 0xc0016b6880, 0x0, 0x0, 0x0)
        k8c.io/kubermatic/v2/pkg/resources/reconciling/wrapper.go:36 +0x45
k8c.io/kubermatic/v2/pkg/resources/reconciling.createWithNamespace.func1(0x38840a0, 0xc001410000, 0x33aaaa0, 0x7, 0xc000fca570, 0x22)
        k8c.io/kubermatic/v2/pkg/resources/reconciling/ensure.go:44 +0x4f
k8c.io/kubermatic/v2/pkg/resources/reconciling.createWithName.func1(0x38840a0, 0xc001410000, 0x33ac9c7, 0x8, 0x12, 0x33b45af)
        k8c.io/kubermatic/v2/pkg/resources/reconciling/ensure.go:55 +0x4f
k8c.io/kubermatic/v2/pkg/resources/reconciling.EnsureNamedObject(0x38bd360, 0xc001012d40, 0xc00046eca0, 0x12, 0x33b45af, 0xc, 0xc001454a80, 0x38e3760, 0xc00087a2d0, 0x38840a0, ...)
        k8c.io/kubermatic/v2/pkg/resources/reconciling/ensure.go:81 +0x1064
k8c.io/kubermatic/v2/pkg/resources/reconciling.ReconcileConfigMaps(0x38bd360, 0xc001012d40, 0xc000c3f1a0, 0x5, 0x5, 0xc00046eca0, 0x12, 0x38e3760, 0xc00087a2d0, 0xc000bc35e0, ...)
        k8c.io/kubermatic/v2/pkg/resources/reconciling/zz_generated_reconcile.go:167 +0x11a
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).ensureConfigMaps(0xc000124e00, 0x38bd360, 0xc001012d40, 0xc001a61400, 0xc000f3e4e0, 0x0, 0x0)
        k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/resources.go:400 +0x16a
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).ensureResourcesAreDeployed(0xc000124e00, 0x38bd360, 0xc001012d40, 0xc001a61400, 0x0, 0x0)
        k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/resources.go:110 +0x4a5
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).reconcileCluster(0xc000124e00, 0x38bd360, 0xc001012d40, 0xc001a61400, 0x0, 0x0, 0xed852b2d2)
        k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/pending.go:52 +0x115
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).reconcile(0xc000124e00, 0x38bd360, 0xc001012d40, 0xc001010170, 0xc001a61400, 0xa, 0x1, 0x0)
        k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:281 +0x2a5
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).Reconcile.func1(0x0, 0x7fff6527a047, 0x0)
        k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:245 +0x1f8
k8c.io/kubermatic/v2/pkg/crd/kubermatic/v1/helper.ClusterReconcileWrapper(0x38bd360, 0xc001012d40, 0x38e3760, 0xc00087a2d0, 0x7fff6527a047, 0x0, 0xc001a61400, 0x38a43e0, 0x28, 0x37c0648, ...)
        k8c.io/kubermatic/v2/pkg/crd/kubermatic/v1/helper/helper.go:57 +0xf3
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).Reconcile(0xc000124e00, 0x0, 0x0, 0xc0001edf04, 0xa, 0xc001239c00, 0x0, 0x0, 0x0)
        k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:229 +0x645
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008a6d80, 0x2e78900, 0xc00067efa0, 0x6e4a455769356d00)
        sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:244 +0x2a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008a6d80, 0x203000)
        sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:218 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0008a6d80)
        sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:197 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0010178a0)
        k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0010178a0, 0x3866660, 0xc001001c80, 0x58463255556c5401, 0xc0001c1560)
        k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0010178a0, 0x3b9aca00, 0x0, 0x73466e626e703201, 0xc0001c1560)
        k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0010178a0, 0x3b9aca00, 0xc0001c1560)
        k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:179 +0x416
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0`

which is caused by a seed.yaml like this:

> apiVersion: kubermatic.k8s.io/v1
> kind: Seed
> metadata:
>   name: kubermatic
>   namespace: kubermatic
> spec:
>   country: DE
>   location: Frankfurt
>   datacenters:
>     gcp-frankfurt:
>       country: DE
>       location: EU (Frankfurt)
>       spec:
>         gcp:
>           region: "europe-west3"
>           regional: false
>           zone_suffixes: []
>   kubeconfig:
>     name: kubeconfig-cluster-example
>     namespace: kubermatic

I missed to fill in the zone. It was very hard to find the reason for the problem and I had to dig into the code.

In kubermatic-2.16.10/pkg/resources/cloudconfig/configmap.go the following line

localZone := dc.Spec.GCP.Region + "-" + dc.Spec.GCP.ZoneSuffixes[0]

does not check if the list of zones has at least one entry. Which causes the not very helpful error message.

**Acceptance criteria**

On missing the zones a proper error message should be printed out to fix the config.

**Comment by xrstf** [comment]
Fixed by #8525.
