### ISSUE TITLE
Openstack - LB name not unique enough when running multiple clusters in one tenant

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#7229]
**User Story**
The default naming schema in the Openstack Cloud Provider is not Unique enough when creating more then one cluster in one tenant.
In the OCCM we have following name generation
https://github.com/kubernetes/cloud-provider-openstack/blob/4d6ecb67ad4082a430333533b6644a86d64543ae/pkg/openstack/loadbalancer.go#L806

Which identifies a LB via ServiceName, Namespace and a Cluster name. The cluster name defaults to kubernetes.
So if you deploy to K8S cluster in one tenant and then the same services in the same namespace (f.e. Promethues in namespace monitoring), they will get the same names, and both controller try to reconcile the same OS LB.

For manual installations the OCCM has the option --cluster-name, but that is not configurable in KPP.

The fix could be to add --cluster-name option to the OCCM in https://github.com/kubermatic/kubermatic/blob/master/pkg/resources/cloudcontroller/openstack.go

**Comment by xmudrii** [comment]
Suppressed by #7330 and #7332 
/close
