### ISSUE TITLE
Openstack Cluster stuck in deletion when network not found

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#7241]
**User Story**
Openstack cluster stuck in deletion with error `failed cloud provider cleanup: failed to delete network 'kubernetes-xlkxth9pbp': failed to get network 'kubernetes-xlkxth9pbp' by name: no network named 'kubernetes-xlkxth9pbp' with external=false found`

When trying to delete network and is already deleted/missing then deletion should progress instead of throwing error
So as far as I could see it, we need to:
- wrap error here https://github.com/kubermatic/kubermatic/blob/6b5514d04b1f4eeba369fe5af414717be66bdfe9/pkg/provider/cloud/openstack/helper.go#L280 with %w, so that here https://github.com/kubermatic/kubermatic/blob/6b5514d04b1f4eeba369fe5af414717be66bdfe9/pkg/provider/cloud/openstack/provider.go#L360
we can unwrap the error and check if the error value is `ErrNotFound` using
`if errors.Is(err, ErrNotFound) {
    // something wasn't found
}`
and move on to removing finalizer

**Fixes**  #7112

**Acceptance criteria**
Not return error when a resource, (network in this case) is not found i.e, `failed to get network by name`, in order to complete cluster deletion

**Comment by youssefazrak** [comment]
Fixes #7112
