### ISSUE TITLE
Optionally bind Presets to Projects

### ISSUE THREAD

**Issue by Happy2C0de** [kubermatic/kubermatic#7260]
**User Story**
Dear Kubermatic
In order to implement full multi-tenancy, one needs to migrate from email bound resources to project bound resources. This is critical because granting access to resources by email domains is very, very limited. IMO, this is bad practice.

Additionally, the Service Accounts used to access the rest-api is kind of limited in its functionality. E.g. a project is bound to certain members of an organisation. Even if you are lucky and all members have the same email domain (normally, that's not the case), service accounts would not be able to use Presets. That's not what I would expect to see from a multi-tenancy capable project nor from service accounts.
I am happy to help with the implementation but it requires certain design decisions from your side.

e.g.:
```
curl -X 'GET' 'https://ENDPOINT/api/v1/providers/openstack/presets/credentials?datacenter=DC' \
  -H 'accept: application/json' \
  -H 'authorization: Bearer TOKEN'
```
, if TOKEN belongs to a Service Account no preset that is limited to email domains will be shown.

**Acceptance criteria**
Users should be able to bind presets to certain projects ~~and not to emails~~.

**Comment by toschneck** [comment]
Can confirm. As an enduser I want to create presets what I use for my API cluster creation tied to a project.

**Comment by csengerszabo** [comment]
- it’s a big conceptual change and we should change the existing projects as well
- migration will be a big problem, therefore a proposal neeeded e.g. how we will handle an upgrade with this feature being added

**Comment by csengerszabo** [comment]
Probably we should not remove email binding, just add the project binding

**Comment by embik** [comment]
As mentioned by @csengerszabo, we're going to keep the email binding functionality around, at the very least for being backwards compatible. The focus of this issue is therefore to _add_ the functionality to bind presets to projects, not removing the email binding (which can be used as alternative to project bindings).

**Comment by embik** [comment]
This has been done and will be in KKP 2.22.
