### ISSUE TITLE
kube-state-metrics appversion is outdated

### ISSUE THREAD

**Issue by rwin-novo** [kubermatic/kubermatic#7276]
**User Story**
You are probably aware of this, but anyways.
The kube-state-metrics Helm chart still installs `appVersion: v1.9.7` but according to its [compatibility matrix](https://github.com/kubernetes/kube-state-metrics#compatibility-matrix), this version doesn't even support Kubernetes v1.17 and up yet. For K8s v1.21, one needs at least kube-state-metrics v2.0.0.

**Acceptance criteria**
* the kubermatic repository contains the kube-state-metrics with appversion v2.0.0+ 
* the newer kube-state-metrics has been tested and it works with KKP

**Comment by mate4st** [comment]
https://github.com/kubermatic/kubermatic/pull/7571
