### ISSUE TITLE
Add new machine status `JoinClusterTimeoutMachineError` to the upstream machine-type

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#729]
Remote issue https://github.com/kubernetes/kube-deploy/issues/503

**Comment by mrIncompetent** [comment]
Estimated to 1 story point

**Comment by alvaroaleman** [comment]
PR created: https://github.com/kubernetes-sigs/cluster-api/pull/681

**Comment by alvaroaleman** [comment]
Fixed via kubernetes-sigs/cluster-api#681
