### ISSUE TITLE
Remove configuration from code

### ISSUE THREAD

**Issue by scruplelesswizard** [kubermatic/kubermatic#73]
Allow dynamic changes in the application without modifying the logic, specifically sourcing information on the namespaces/containers/deployments/etc from a configuration file instead of using magic strings in the application logic

**Comment by scruplelesswizard** [comment]
This should also focus on making the api and kubermatic repos independent of each other (i.e. separate kubermatic(configuration) repos could be used for different clusters without changing the api repo at all)

**Comment by scheeles** [comment]
After 390f3db1a36a6a7e59dde6d2808d6b7230138ad6, the only thing what is inside this repo is the https://github.com/kubermatic/api/blob/develop/datacenters.yaml

We should move this also to kubermatic and add it as a secret
