### ISSUE TITLE
cluster-controller sending on closed channel

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#731]
The cluster controller at syseleven just crashed with one of its goroutines and is dandling in an inconsistent state, not terminating. 
I only found out because Prometheus alerts where sent into your #alerting-syseleven slack channel and I looked into the alert.

```
I0208 07:11:42.222519       8 leaderelection.go:243] lock is held by cluster-controller-v1-157767814-6g22f-kubermatic-cluster-controller and has not yet expired
I0208 07:11:42.238889       8 leaderelection.go:203] failed to renew lease kube-system/kubermatic-cluster-controller: timed out waiting for the condition
I0208 07:11:42.268194       8 main.go:196] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kubermatic-cluster-controller", UID:"45fed553-e410-11e7-aa6b-fa163e12ceaa", APIVersion:"v1", ResourceVersion:"90690875", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' cluster-controller-v1-157767814-gb9rd-kubermatic-cluster-controller stopped leading
E0208 07:11:42.268272       8 main.go:162] ==================== OnStoppedLeading ====================
I0208 07:11:42.519902       8 controller.go:371] Shutting down cluster controller
E0208 07:11:42.519947       8 main.go:113] Stopping os signal notifier: <nil>
E0208 07:11:42.519954       8 main.go:136] Stopping internal http server: <nil>
I0208 07:11:42.522830       8 main.go:140] Shutting down the internal http server
E0208 07:11:42.732666       8 main.go:180] Stopping controller: <nil>
panic: close of closed channel

goroutine 1 [running]:
main.main.func6(0x0, 0x0)
	/go/src/github.com/kubermatic/kubermatic/api/cmd/kubermatic-cluster-controller/main.go:181 +0x9c
github.com/kubermatic/kubermatic/api/vendor/github.com/oklog/run.(*Group).Run(0xc420549e30, 0xc4201aac00, 0x2)
	/go/src/github.com/kubermatic/kubermatic/api/vendor/github.com/oklog/run/group.go:47 +0x141
main.main()
	/go/src/github.com/kubermatic/kubermatic/api/cmd/kubermatic-cluster-controller/main.go:185 +0xbaf
```

Sadly the controller keeps on running as it is in a inconsistent state.
Like this it seems that it is able to stay in a deadlock or something, but it's not possible to be scraped by Prometheus in this state anymore.
It is just sitting there doing nothing and blocks new instances being scheduled.

@mrIncompetent

**Comment by metalmatze** [comment]
Deleting the dangling pod manually, terminated that pod and scheduled a new one. This new pod is running correctly and is able to be scraped.

**Comment by metalmatze** [comment]
I'm also leaving a related discussion on the machine controller on this issue:
https://github.com/kubermatic/machine-controller/pull/60

I know that we're already using `run.Group` in the cluster-controller, but something still seems to be wrong with the implementation.

**Comment by p0lyn0mial** [comment]
alright, so I think I have reproduction on my local machine. Just want to clarify one part, namely "Sadly the controller keeps on running as it is in a inconsistent state." 

From the attached logs I can tell that sending on closed channel caused a panic which usually terminates the whole process. The only way to prevent this is to `recover` which is not present in our codebase. Moreover there are no further logs messages, which may indicate that the process terminated but also it may indicate that further logs were not attached. Furthermore my local reproduction gives the same output but the process is terminated. Just by looking at the code I don't see any recovery logic that could prevent termination.

Having said all that, it was very strange that the controller was not terminated. @metalmatze do you think the following were possible ?

- process was termineted, but the pod inside which the process were running was not terminated?

- controller was running inside a different process that wasn't terminated ?

**Comment by mrIncompetent** [comment]
I had the issue once on my system - The process did not terminate.
Though i cannot reproduce it anymore.
