### ISSUE TITLE
Replace deprecated Go Dep in Metering Tool

### ISSUE THREAD

**Issue by simon-wessel** [kubermatic/kubermatic#7310]
Switch to Go Modules to get rid of deprecated dependency management tool Go Dep.

**Comment by kron4eg** [comment]
@simon-wessel what Go Dep?

**Comment by simon-wessel** [comment]
This one: https://github.com/golang/dep

**Comment by kron4eg** [comment]
> Switch to Go Modules to get rid of deprecated dependency management tool Go Dep.

it has been done long ago

**Comment by simon-wessel** [comment]
This is for the Metering Tool. It still uses Go Dep.

**Comment by simon-wessel** [comment]
This belongs to #6587, but it is better suited in in the metering tool repository. I will recreate it over there.
