### ISSUE TITLE
Move seed-cluster setup and kubermatic-installer job into a new repo

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#735]

**Comment by metalmatze** [comment]
Before moving the kubermatic-installer job. I plan on replacing it with the helm plugin in our drone pipeline. Do we still need it for manual deployments? :thinking:

**Comment by mrIncompetent** [comment]
We will always need that installer. 
How else should customers be able to install it on their own?

**Comment by metalmatze** [comment]
That's why I was asking. We should discuss how we can keep them in sync, the installer job and the drone ci step. Something I didn't see when developing the ci plugin :sweat_smile:
