### ISSUE TITLE
kubectl proxy broken with tunneling expose strategy

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/kubermatic#7350]
**User Story**
When using the new expose strategy [kubectl proxy](https://kubernetes.io/docs/tasks/extend-kubernetes/http-proxy-access-api/#using-kubectl-to-start-a-proxy-server) does not work, the reason is that SNI is used by envoy proxy to route requests to the right cluster at seed level, and when using the proxy this information is missing.

**Acceptance criteria**
Find a strategy to overcome the limitation or at least document it.

**Comment by embik** [comment]
/remove-lifecycle rotten

Not sure if this is still the case or not, but doesn't seem to be a good idea to have it silently closed as stale without a human checking on it.
