### ISSUE TITLE
Make VPN URL available via API

### ISSUE THREAD

**Issue by toothstone** [kubermatic/kubermatic#7352]
**User Story**
I would like to get the VPN URL for a cluster as part of an API call, similar to the status API URL which is part of the [cluster detail endpoint](https://docs.kubermatic.com/kubermatic/v2.17/references/rest_api_reference/#/project/getClusterV2).

Currently we use a command like this to get the VPN port for a cluster manually:
```
> kubectl get services openvpn-server -n cluster-dkbz2j2v82 -o json | jq ".spec.ports[0].nodePort"
> 30015
```
But in an automation setup this is not feasible.

**Acceptance criteria**
The response for a cluster's details contains a "vpn" (or similar) section with an entry "url" which provides the above information.

**Comment by toothstone** [comment]
Can anyone recommend a work-around which can be automated?

**Comment by rastislavs** [comment]
Hi,
what is the use-case for such feature request?
OpenVPN is just an internal component for seed-to-usercluster control plane communication, it is not intended to be used for any other purposes.

**Comment by toothstone** [comment]
The use-case is to enable the required control plane communication when the seed cluster is not directly accessible from the userclusters, in my case I have to configure a haproxy accordingly - accepting connections coming from userclusters and forwarding them to the according VPN port on the seed workers. I hope that makes sense!

I'm currently working around this by directly accessing the k8s API (effectively running the above command), but I would be very happy if I could drop that additional dependency along with the high-risk credentials it requires from my app.

**Comment by rastislavs** [comment]
Thanks for the explanation @toothstone. If opening whole nodeport range for usercluster-to-seed connections in your infrastructure is not feasible, then maybe the Tunneling expose strategy ([Documentation](https://docs.kubermatic.com/kubermatic/v2.18/guides/kkp_networking/expose_strategies/), [Proposal](https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/http-tunnel-expose-strategy.md)) would be something that may be interesting for you. In that case, your would only have to configure your infrastructure with a fixed set of ports. It is still in alpha stage, but already working.

The reason why I am reluctant to exposing the OpenVPN nodeport is that we in fact plan to replace OpenVPN with [Konnectivity](https://github.com/kubermatic/kubermatic/blob/master/docs/proposals/konnectivity-openvpn.md).

**Comment by toothstone** [comment]
Thanks for the pointers - I'm personally not that familiar with the underlying KKP infrastructure, but my team will reconsider our current approach when the new expose strategies are considered stable.

If you're certain that the API won't/shouldn't expose the VPN port, feel free to close this issue.
