### ISSUE TITLE
Improve Kubermatic CRD installation management

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#7372]
**User Story**
Currently as a operator of Kubermatic KKP, I need to take care manually that the deployed CRDs at the connected seed cluster is valid and in the right version deployed.

For ref see: `Add CRDs for kubermatic components in seed cluster` https://docs.kubermatic.com/kubermatic/v2.17/guides/installation/add_seed_cluster_ee/

This behavior is really error prune, as also our controllers e.g. the `master-controller-manger` see #7371 don't validate if the correct CRD version is deployed or if some API object is missing. The crashing pods even don't give a helpful hint, that a CRD is missing or outdated.

Currently we already deploy quite  a set of resources. So for end users it would be great, if the Kubermatic operator (or some other controller like the seed controller) takes care about the life-cycle of the CRDs, it would be prevent that users miss to add or update the needed CRDs at the seeds.

**Acceptance criteria**
- [ ] Usability of the CRD Management at the seed clusters is  increased

**Comment by xrstf** [comment]
This was fixed in #8552. The KKP installer now sets up the CRDs on master and seed clusters.
