### ISSUE TITLE
Swagger definition of Kubeconfig response incorrect/breaks generated python client

### ISSUE THREAD

**Issue by toothstone** [kubermatic/kubermatic#7389]
**User Story**
As of at least KKP 2.16/2.17 (KKP API version 2.11), the [swagger.json](https://docs.kubermatic.com/kubermatic/v2.17/references/rest_api_reference/swagger.json) definition for the kubeconfig endpoints models their response as an array of integers, which is not what is actually in the response. As such, a generated Python API client  (e.g. from `swagger-codegen generate -i https://<our-kkp-domain>/api/swagger.json -l python -o python-kubermatic`) fails when one is using the `get_cluster_kubeconfig_v2` method, since it can't parse the response into the type given by the definition.

I manually changed the Kubeconfig response definition (to type `string`, format `binary`) and now the generated client returns the correct Python `string` representation of the Kubeconfig file contents.

**Acceptance criteria**
The swagger.json definitions contains the correct response type and format, so that generated clients can use the kubeconfig endpoints and return an appropriate object.

**Comment by toothstone** [comment]
/remove-lifecycle stale

Is still a problem as of 2.19.2

**Comment by toothstone** [comment]
@embik Is there a chance you could have a look at this API issue as well?
Fixing this would allow me to retire my 'fork' of the API definition and pull it directly from upstream again.

**Comment by embik** [comment]
Sure @toothstone, I will take a look.

**Comment by embik** [comment]
Just to update this after a month, I was looking into it but so far haven't been able to convince go-swagger to generate the correct spec. But I haven't forgotten about it.

**Comment by toothstone** [comment]
/remove-lifecycle stale


Still an issue as of 2.21, see https://docs.kubermatic.com/kubermatic/v2.21/references/rest-api-reference/swagger.json line 33264
