### ISSUE TITLE
Swagger definition discrepancy in NodeDeploymentSpec: replicas are required, yet omitted in response

### ISSUE THREAD

**Issue by toothstone** [kubermatic/kubermatic#7392]
**User Story**
The current swagger.json API definition says that the `replicas` attribute is required for a `NodeDeploymentSpec`, but in reality the KKP API will omit this attribute completely in a response if `replicas` is zero. This breaks generated clients, since the attribute is supposed to be non-optional and a value/type of e.g. `None` (in Python) is considered invalid for the attribute.

**Acceptance criteria**
Preferably, the KKP API responses for NodeDeploymentSpecs contain `"replicas": 0` if that is the number of replicas (instead of just omitting it).
Alternatively, the swagger definition is changed (removing `replicas` from the required section) so that generated clients accept a response where it is missing.

**Comment by toothstone** [comment]
/remove-lifecycle stale

Issue still present as of KPP 2.18

**Comment by toothstone** [comment]
/remove-lifecycle stale

Issue still present as of KPP 2.19.2

**Comment by embik** [comment]
Hi @toothstone, this should be fixed by #9679. Apologies this took some time to get noticed.

**Comment by toothstone** [comment]
@embik Awesome, thanks!
