### ISSUE TITLE
Bug: Wrong Helm chart crd directory name

### ISSUE THREAD

**Issue by Happy2C0de** [kubermatic/kubermatic#7406]
**User Story**
Helm charts are not valid. 
Following charts are affected:
- `charts/backup/velero`
- `charts/cert-manager`
- `charts/kubermatic`

The official helm documentation tells you:
> There is now a special directory called `crds` that you can create in your chart to hold your CRDs

See: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

Your directory name is `crd` not `crds`. This is important because Helm will not deploy any CRDs to the cluster and the installation fails.

You can reproduce it by generating the k8s manifests with Helm 3:
```
$ cd charts/backup/
$ helm template velero --include-crds | grep CustomResourceDefinition -c
0
$ mv velero/crd velero/crds
$ helm template velero --include-crds | grep CustomResourceDefinition -c
11
```
In the current charts, no CRDs are included in the output. If you change the directory name from `crd` to `crds` and execute the command again, you see that the CRDs are generated and accordingly, they will be deployed to the cluster.

**Acceptance criteria**
- Fix the given charts to follow Helm standard with directory name `crds`.
- Update documentation in https://github.com/kubermatic/docs

**Comment by xrstf** [comment]
> Your directory name is crd not crds. This is important because Helm will not deploy any CRDs to the cluster and the installation fails.

Helm is not supposed to install CRDs. Because Helm is terrible at managing CRDs and will never, ever, ever update them. For this reason we moved away from that and installing the CRDs ourselves.
