### ISSUE TITLE
Strange behavior adding nodes to seed cluster

### ISSUE THREAD

**Issue by siredmar** [kubermatic/kubermatic#7412]
Hi!
I currently am trying to evaluate a solution where i use Azure AKS clusters to have a way of running KubeEdge. KubeEdge brings k8s to your IoT device as k8s node. Then you can deploy some workload on those nodes.
What i currently did was:
Create two AKS nodes: main and seed. In the main cluster i installed Kubermatic Kubermetes Platform. I then created a new project and manually added the kubeconfig of the seed cluster to it.
I installed kubeedge on the seed cluster.
My seed cluster has one AKS worker node running the cloudcore of KubeEdge.

```sh
$ kubectl get nodes                                 
NAME                                STATUS   ROLES               AGE   VERSION
aks-agentpool-23303655-vmss000000   Ready    agent               41h   v1.19.11
$ kubectl get service                                                                   
NAME        TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                           AGE
cloudcore   LoadBalancer   10.0.41.116   x.x.x.x       10002:30002/TCP,10000:30000/TCP   114m
```

I’m able to connect a KubeEdge device to the cloudcore and therefore the cluster.
However, all my KubeEdge nodes do have the role master meaning that some master related stuff isrunning on my edge devices. I don’t want this.

```sh
$ kubectl get nodes  
NAME                                STATUS   ROLES               AGE   VERSION
aks-agentpool-23303655-vmss000000   Ready    agent               41h   v1.19.11
node0                               Ready    agent,edge,master   60m   v1.19.3-kubeedge-v1.7.1
node1                               Ready    agent,edge,master   27m   v1.19.3-kubeedge-v1.7.1
node2                               Ready    agent,edge,master   27m   v1.19.3-kubeedge-v1.7.1
node3                               Ready    agent,edge,master   27m   v1.19.3-kubeedge-v1.7.1

$ kubectl get pods -o wide                 
NAME                                               READY   STATUS    RESTARTS   AGE    IP            NODE                                NOMINATED NODE   READINESS GATES
coredns-66c464876b-pn6jv-x-kube-system-x-tenant1   0/1     Running   0          64m    172.18.0.2    node0                               <none>           <none>
tenant1-0                                          2/2     Running   0          131m   10.244.0.24   aks-agentpool-23303655-vmss000000   <none>           <none>
```

Does anyone here can tell me what is going wrong and how to prevent those nodes from becoming masters?

**Comment by kron4eg** [comment]
Hi,

KKP doesn't label any nodes with role=master, it must be KubeEdge itself somehow. Please address this issues in there.

**Comment by siredmar** [comment]
I looked in the KubeEdge source code and could not find any reference to this master role... 
Do you think it's possible that Azure sets those labels? 
I just looked at the labels for node0 and saw this:
```
$ kubectl describe node node0                
Name:               node0
Roles:              agent,edge,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    edgefarm.tenant=tenant1
                    kubernetes.azure.com/role=master
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=node0
                    kubernetes.io/os=linux
                    kubernetes.io/role=master
                    node-role.kubernetes.io/agent=
                    node-role.kubernetes.io/edge=
                    node-role.kubernetes.io/master=
```

**Comment by siredmar** [comment]
And am i using kubermatic the right way? Is it even made for such a scenario i am trying to use it?

**Comment by siredmar** [comment]
I was using Kubermatic the wrong way. I close this.
