### ISSUE TITLE
User Cluster - Canal Settings

### ISSUE THREAD

**Issue by stepa-ict** [kubermatic/kubermatic#7414]
**User Story**
Hi,
I have successfully installed bringyourown{} user cluster. By default, there is addon canal that installs canal cni to user cluster. Now I have to reconfigure canal (flannel as part of) to use host-gw backend instead of vxlan. 

I found configmap canal-config in the user cluster in ns kube-system, and when I changed this option here, the option was reset to default value.

I suppose that this has to be changed to the definition of user cluster or addon itself, but I didn't find any part of documentation that related to this kind of option.

**Acceptance criteria**
I'd like to know where and how I can change addon canal backend type.

Thank you guys in advance,

**Comment by stepa-ict** [comment]
Is there anybody just to give me advice how to change canal addon setting for backend vxlan to host-gw. 

Thanks again,
Vlada

**Comment by kron4eg** [comment]
We don’t support any settings for CNI, but you could use your own addons image to provide own CNI manifests including configs.

**Comment by stepa-ict** [comment]
Thanks for the reply and recommendation.
I'll try this today.

**Comment by kron4eg** [comment]
@stepa-ict we have some docs describing the process how to configure custom addons: https://docs.kubermatic.com/kubermatic/v2.17/guides/addons/#custom-addons

**Comment by stepa-ict** [comment]
Hi @kron4eg,

I can confirm that I solved the problem. This is a very good and flexible way to choose what will be installed on every user cluster. 
I took the addon directory from [here](https://github.com/kubermatic/kubermatic/tree/master/addons), changed canal config and recreate the image in the private registry.

Thanks again, and you've been doing great things with Kubermatic Ecosystem.

**Comment by kron4eg** [comment]
Thanks for reporting back!
