### ISSUE TITLE
Add Annotations Metadata to MachineDeployments

### ISSUE THREAD

**Issue by Happy2C0de** [kubermatic/kubermatic#7446]
**User Story**
Add the possibility to add Annotations to the MachineDeployments within Kubermatic. This is a general feature from k8s and allows to annotate the machine deployments.
This is especially useful in combination with cluster-autoscaler which required certain annotations. It's not very user-friendly to "hack" the annotations via kubectl after the MD were created.

See cluster-autoscaler annotations:
[Kubeone:Addons/cluster-autoscaler-docs](https://github.com/kubermatic/kubeone/tree/master/addons/cluster-autoscaler#choosing-machinedeployment-objects-for-autoscaling)

**Acceptance criteria**
- Allow to specify Annotations while creating nodedeployments/machinedeployments.
- Add Annotations to the Dashboard while creating initial and additional machinedeployments.

**Comment by kron4eg** [comment]
So what’s the problem exactly to ether kubectl edit/apply machinedeployment or kubectl annotate machinedeployment?

**Comment by Happy2C0de** [comment]
We had several feedbacks that it is not very convenient to add annotations to MDs after you created the node pool. I share this thought, especially if one is forced to have an initial machine pool defined (yes, one is able to set it to 0, but the MDs is created anyway). 

I would like to manage the MDs either from manifests only or I would like to have all options of the K8S resource within Kubermatic. A mixture of both is in my opinion not very user-friendly and leads to confusion. IMO, there is no reason not supporting Annotations.
Additionally, there is an option to add "labels" to the machines, why not annotations too? This is just a corollary of this option, which solves some misunderstandings (and we had them multiple times).

**Comment by kron4eg** [comment]
In our infrastructure we treat MD objects as "just another kubernetes object, along with deployments and configMaps, etc...", we persist them in git, we edit them via PRs, including annotations. Which I advise you to do too.

**Comment by Happy2C0de** [comment]
I agree to this strategy for experienced K8S users and we do it likewise. But not all of the users on the platform are that experienced and do it like this. A lot of the users work only with the UI and deploy their applications on the k8s cluster without touching MDs anymore (what's totally understandable IMO). For them, there is no user-friendly option to add annotations except adding them via kubectl. In order to better integrate cluster-autoscaler into Kubermatic, I think there is a need to support setting min/max values for the cluster-autoscaler via UI or at least, adding custom Annotations via the UI.
What do you think?

Especially, for the initial MD. It's not intuitive to set replicas=0 initially and manage MDs afterwards.

**Comment by kron4eg** [comment]
I'm sorry, but I fail to understand how can one be a "kubernetes user" and at the same time "not using kubectl".

**Comment by Happy2C0de** [comment]
I didn't say users don't use "kubectl", but doing `kubectl edit/annotate md X` is also bad practice and not user-friendly when it is not needed. I hope you agree to that!?
The user should not "hack"/add the annotations to the MD resource after creation. I think this is not very user-friendly and also not best-practice in k8s.

I think, there is a need to set all important k8s resource options via the REST-API and the UI. Don't you agree to that? Why are labels more important than annotations for your project? Why are labels supported but not annotations? 
KubeOne and MachineController supports annotations natively. So, I just request to pass this option to the Kubermatic platform and I don't get why this is a critical change, is it?
