### ISSUE TITLE
Support working declaratively

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#7454]
**User Story**
We have identified a lot of related tasks and technical debt and this epic is meant to coordinate between them:

* #6471
* #6337
* #5971
* #6692
* #7372
* #7398
* #7403

All of these eventually aim towards a single goal: turning KKP from an API-driven system to a declarative one, where working with custom resources directly (e.g. via `kubectl`) is well supported.

Another main aspect is the new rule regarding the `*.k8s.io` namespace: we currently use it and need to stop doing so.

To prevent changing our custom resources twice (once to change their API group to move away from k8s.io, and once when we turn it into a stable API), I suggest we for now keep the existing CRDs (using the cheating annotation) and then perform one big refactoring.

**Road to Success**

* Step 1: Gather requirements for the new architecture. We need to know what we want to achieve before we make any design decisions.

**Comment by xrstf** [comment]
cc @moadqassem

**Comment by embik** [comment]
This is a random thought I had, but should `Clusters` (eventually) become namespaced resources if we move to declarative support via Kubernetes API and CRDs? Otherwise, transferring the concept of a project becomes difficult, especially when it comes to (RBAC) permission management.
