### ISSUE TITLE
ClusterRole promtail gets deleted automatically

### ISSUE THREAD

**Issue by squ94wk** [kubermatic/kubermatic#7468]
**Bug report**
ClusterRoles created in a user cluster with the name `promtail` (and likely many other resources) immediately get deleted automatically after creation.

**Expected behavior**
I can create a ClusterRole named `promtail`.

**Actual behavior**
Every time I create a ClusterRole named `promtail` it automatically gets deleted:

```
$ kubectl create -f - << 'EOF'
 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: promtail
 rules:
   - apiGroups:
       - ""
     resources:
       - nodes
       - nodes/proxy
       - services
       - endpoints
       - pods
     verbs:
       - get
       - watch
       - list
EOF
sleep 1
kubectl get clusterrole promtail
clusterrole.rbac.authorization.k8s.io/promtail created
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "promtail" not found
```

**Comment by squ94wk** [comment]
Feel free to rename the issue and add information.

**Comment by squ94wk** [comment]
In our opinion, components installed with KKP should always include a prefix to avoid such naming collisions. Especially with cluster scoped resources.

This issue does not only affect new installations, but also isn't backwards-compatible, even if a feature is not enabled.

**Comment by kron4eg** [comment]
@jiachengxu PTAL

**Comment by jiachengxu** [comment]
Can you please add more infomation about this? Where did you create the ClusterRole with the name `promtail`? In master cluster, seed cluster, or a user cluster?

**Comment by squ94wk** [comment]
@jiachengxu Updated issue description.

**Comment by jiachengxu** [comment]
@squ94wk Thanks, and which KKP version are you using?

**Comment by squ94wk** [comment]
2.17.1 ee with customizations

**Comment by jiachengxu** [comment]
@squ94wk Thanks for your reporting and I found the issue. We are currently working on a feature called User Cluster MLA(Monitoring, Logging, and Alerting) which is planed for 2.18, and this `promtail` name was preserved for the promtail which will be deployed in user cluster by this feature.
However, we have them renamed with prefix `system:kubermatic:mla` on master branch: https://github.com/kubermatic/kubermatic/blob/master/pkg/resources/resources.go#L587-L588
but not on release 2.17.1: https://github.com/kubermatic/kubermatic/blob/v2.17.1/pkg/resources/resources.go#L584-L585

**Comment by squ94wk** [comment]
@jiachengxu Thanks for your reply.

For reference, the commit [a8a24edeeb3cf61306862b9619e59a31ed2320ca](https://github.com/kubermatic/kubermatic/commit/a8a24edeeb3cf61306862b9619e59a31ed2320ca) adds the change.
We'll probably cherry pick this before 2.18, since we're currently not using MLA.

**Comment by xrstf** [comment]
I am backporting #6881 to 2.17, as this is a critical bug IMHO.
