### ISSUE TITLE
kubermatic-dashboard upgrade to weekly release failed

### ISSUE THREAD

**Issue by HaveFun83** [kubermatic/kubermatic#7483]
**User Story**
Hello Kubermatic Team,
we upgraded our test env to the latest kkp weekly release "weekly-2021-31" and now we got the following error from the kubermatic-dashboard pod
```
Warning  Failed          25m (x3 over 26m)     kubelet            Failed to pull image "quay.io/kubermatic/dashboard:weekly-2021-31": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/kubermatic/dashboard:weekly-2021-31 not found: manifest unknown: manifest unknown
```
Looks like there are no new weekly since weekly-2021-22 anymore
https://quay.io/repository/kubermatic/dashboard?tag=latest&tab=tags

**Acceptance criteria**
weekly releases should contain all necessary image to run without ImagePullBackOff

**Comment by toschneck** [comment]
@HaveFun83  32 should be there again

**Comment by HaveFun83** [comment]
@toschneck thanks for looking into it.

**Comment by HaveFun83** [comment]
@toschneck only cosmetic but after upgrade to weekly-2021-34 the dashboard show `v2.14.0-662-gbfbb48dd` as version in the browser
