### ISSUE TITLE
Kubelet fail to run due to too many open files

### ISSUE THREAD

**Issue by jacmathew** [kubermatic/kubermatic#7490]
**Issue**
kubelet service on the node fail to run and exit which leads to cluster stability issues. Below is what is observed on the kubelet logs.

```kubelet[111106]: goroutine 1 [running]:
 kubelet[111106]: F0812 16:26:52.166979  111106 server.go:269] failed to run Kubelet: inotify_init: too many open files
 kubelet[111106]: E0812 16:26:52.166955  111106 server_linux.go:27] unable to create watcher for lockfile: inotify_init: too many open files
 kubelet[111106]: I0812 16:26:52.166937  111106 server.go:499] watching for inotify events for: /tmp/kubelet.lock
 kubelet[111106]: I0812 16:26:52.166870  111106 server.go:494] acquiring file lock on "/tmp/kubelet.lock"
 kubelet[111106]: I0812 16:26:52.166588  111106 server.go:416] Version: v1.20.9
 kubelet[111106]: I0812 16:26:52.145366  111106 fsstore.go:59] kubelet config controller: initializing config checkpoints directory "/etc/kubernetes/dynamic-config-dir/store"
 kubelet[111106]: I0812 16:26:52.145357  111106 controller.go:267] kubelet config controller: ensuring filesystem is set up correctly
 kubelet[111106]: I0812 16:26:52.145258  111106 controller.go:101] kubelet config controller: starting controller
```
This issue is observed in containerd as well as docker runtimes. The work around tried was increasing the fs.file-max and fs.inotify.max_user_instances parameters to higher values and restarting the node (as restarting kubelet wont happen due to the above mentioned issue)

Would like to understand what are the recommended values for the above menntioned sysctl parameters and what will be the root cause of the issue.

Enviornment details as below

OS: Ubuntu 20.04
Kubernetes: 1.20.9

**Comment by mfranczy** [comment]
We need more information about OS status, please execute
`systctl fs`
`cat /etc/security/limits.conf`

and as a root run the script (please don't share the ouput publicly, rather give us some access to the location of the log file)
`for pid in /proc/[0-9]*; do printf "pid %6d fd %4d %s\n" $(basename $pid) $(ls $pid/fd | wc -l) $(cat $pid/cmdline | tr -d '\0'); done`

additionaly what were the original values you changed for `fs.file-max` and `fs.inotify.max_user_instances`?

Depends on the result we might want to ask you to execute other commands.

**Comment by mfranczy** [comment]
After receving logs on the slack channel and short conversation, I was informed the issue was caused by promtail.
I advise to change of `fs.inotify.max_user_instances` to 512 and monitor the number of inotify descriptiors .

@shaase-ctrl we have to revisit sys settings for our monitoring stack, I don't close that issue yet.

**Comment by mfranczy** [comment]
we already have changed the inotify limit for promtail
https://github.com/kubermatic/kubermatic/blob/master/charts/logging/promtail/values.yaml#L41

**Comment by toschneck** [comment]
@mfranczy I think this would be an general good idea to increase the limit, as also other applications as promtail could cause such issues. On another node even the new value in the promtail chart was to low. So I needed increase it to `8192`

based on https://github.com/giantswarm/k8scloudconfig/pull/617#issuecomment-562356792
this brought up the kubelet, but not sure if this is a permanent solution
```
sysctl -w fs.inotify.max_user_instances=8192
systemctl restart kubelet
```
