### ISSUE TITLE
Create dynamic scrape config for user cluster prometheus

### ISSUE THREAD

**Issue by stepa-ict** [kubermatic/kubermatic#7542]
**User Story**
Hi,
we've been trying to create a custom scrape config for user cluster prometheuses and we need to add service discovery config like:
      _**kubernetes_sd_configs:
          - api_server: https://apiserver-external.cluster-xxxxxx.svc.cluster.local.**_
Since this is configured in kubermaticconfiguration or in kubermatic values file we need to pass variable for user cluster name.
We saw there is 'address.internalURL: apiserver-external.cluster-xxxxxx.svc.cluster.local.' in user cluster definition. Is there posibility to take value of user cluster name or value address.internalURL to pass in user cluster prometheus scrape config?

**Acceptance criteria**
Create dynamic scrape config with user cluster inernal_URL.

It would be valuable to know where is default scrape config for user cluster prometheus.

Thanks guys,

**Comment by stepa-ict** [comment]
Hi,
I was on vacation, so now this issue becomes important. 
Can I expect some info about above mentioned cluster name variable?

Thanks for your time in advance,
Vlada

**Comment by xrstf** [comment]
That's indeed a very valid usecase. We should add another round of Go templating to make the custom scrape configs dynamic.

**Comment by xrstf** [comment]
It's not documented right now, but the custom configs for Prometheus are already templated: https://github.com/kubermatic/kubermatic/blob/master/pkg/resources/prometheus/configmap.go#L84-L101 (since #4704)

So you can use `{{ .APIServerHost }}` (long for `{{ .Cluster.Address.InternalName }}`) in your configs and be good to go.
