### ISSUE TITLE
Etcd backup restore missing perissions to access s3-settings configmap

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#7544]
When using the new backup and restore feature (https://docs.kubermatic.com/kubermatic/v2.17/cheat_sheets/etcd/backup-and-restore/), during the restore phase, the etcd pods are crashlooping because their service account doesnt have access to the `s3-settings` configmap on `kube-system`.

`{"level":"info","time":"2021-08-19T15:59:50.939Z","caller":"etcd-launcher/main.go:559","msg":"restoring datadir from backup","backup-name":"test-backups-2021-08-19t17-26-14"}
{"level":"fatal","time":"2021-08-19T15:59:50.944Z","caller":"etcd-launcher/main.go:98","msg":"failed to restore datadir from backup","error":"failed to get s3 client: failed to get CA bundle ConfigMap: configmaps \"cluster-mg4z4wp4lg-ca-bundle\" is forbidden: User \"system:serviceaccount:cluster-mg4z4wp4lg:etcd-launcher\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""}`

Adding a clusterrole and clusterrolebinding giving permission fixes the issue and the restore finishes succesfully.

**Comment by judge-red** [comment]
I've also previously reported this in #7505
