### ISSUE TITLE
Support Cilium as a second Network Stack 

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#7577]
**User Story**
Provide an option that we can switch the networking stack for new Installation to Cilium

**Acceptance criteria**
During the Installation of KKP I can decide that Cilium is the default network stack

**Comment by irozzo-1A** [comment]
With the changes I made in #7174  is now possible to specify the CNI plugin in the Cluster CRD, at the moment only Canal is supported, but I was thinking of adding a BYO (bring your own) option, where we do not enforce any CNI and it's up to the cluster administrator to deploy its CNI of choice.
Of course with the same mechanism would be also possible to have Cilium as a built-in alternative to Canal.

**Comment by WeirdMachine** [comment]
https://github.com/kubermatic/kubermatic/pull/7851
https://github.com/kubermatic/kubermatic/pull/7853
https://github.com/kubermatic/kubermatic/pull/7850
