### ISSUE TITLE
kubectl logs / kubectl exec timeouted

### ISSUE THREAD

**Issue by subpathdev** [kubermatic/kubermatic#7580]
**User Story**
As a admin of an user cluster I want to use `kubectl logs` to debug my nodes. Also extended debug features with `kubectl exec` cannot be used.

**Acceptance criteria**
- kubectl logs and kubectl exec can be used in a user cluster.

**Setup**
I has setted up an Kubernetes Cluster on Hetzner as described  by @shibumi in his [tutorial.](https://www.kubermatic.com/blog/kubernetes-on-hetzner-with-kubermatic-kubeone-in-2021/) 
Instead of using kubernetes 1.19 as the tutorial suggests, I've used kubernetes 1.21.2.
On that cluster I've installed kubermatic 2.17.3 with the kubermatic installer. (Also oriented by the [tutorial](https://shibumi.dev/posts/kubermatic-on-hetzner/) made by @shibumi)

As seed cluster I'm using the same cluster, wehere the core components from kubermatic can be found.

After the creation of an user cluster, I downloaded the kubeconfig and execute `export KUBECONFIG=$(realpath <downloaded kubeconfig>)`. When I run `kubectl logs` in this I received the following error message:
```
Error from server: Get "https://<public ip from node>:10250/containerLogs/kubernetes-dashboard/dashboard-metrics-scraper-975c84c89-557q5/dashboard-metrics-scraper": dial tcp <same public ip from node>:10250: i/o timeout
```

After searching, if I made a mistake, I found the issue in the Iptables rules on the api server in the seed cluster.
I open a shell on the `dnat-controller`  of the apiserver pod of the user cluster and executing there the following command:
```
iptables -t nat -F
```

When I change now to the user cluster again und executing `kubectl logs` I receive the log files.

In the story above I wrote a lot about `kubectl logs` an nothing about `kubectl exec` but the issues are the same and also the solution.

**Comment by shibumi** [comment]
@subpathdev I remember that I had a similar issue just with accessing user clusters via kubectl (on my laptop).

@kron4eg  is it possible that this issue is a duplicate of this one? https://github.com/kubermatic/kubermatic/issues/7187

Both  are definitely networking related and I have the feeling that `iptables -t nat -F` would have fixed my issue. (maybe).

**Comment by siredmar** [comment]
I'm facint the exact same issue.

**Comment by rastislavs** [comment]
Hi @subpathdev,
could you please add some more details?

- I assume you are using the default, [NodePort expose strategy](https://docs.kubermatic.com/kubermatic/v2.18/guides/kkp_networking/expose_strategies/)
- I assume that you already set up your DNS record to point towards the `nodeport-proxy`'s service external IP as described in the [Update DNS](https://docs.kubermatic.com/kubermatic/v2.18/guides/installation/add_seed_cluster_ce/#update-dns) section of the documentation
- I assume kubectl access to you user cluster was already working, just kubectl exec / logs was not working


If the above is true, than could you please check whether:
- the `openvpn-client` pod in the `kube-system` namespace of your user cluster is up & running
- `openvpn-server` pod in cluster's namespace in the seed cluster is up & running

In case that `iptables -t nat -F` indeed solved your issues, could you please provide the `iptables-save` output from the apiserver pod before, and after fixing the issue?
