### ISSUE TITLE
Maintain Terraform Provider

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#7598]
**User Story**
As a user, I want to be able to use all the features of KKP with terraform so that I can automate with terraform completely.

**Acceptance criteria**
- terraform works out of the box
- all features can be used
- Updates occur regularly

**Comment by Happy2C0de** [comment]
@shaase-ctrl 
Any news on this?
We are looking forward to have a Kubermatic Terraform provider!

This repo:
https://github.com/kubermatic/terraform-provider-kubermatic
is a bit outdated. What's the status of this issue? I would really like to see a well maintained Terraform provider. In modern GitOps this is very convenient to have.

Thanks in advance for your help, and it would be great if you good give me a status update on this. Happy to contribute if needed.
