### ISSUE TITLE
Use non preemtible machines for the EU cloud cluster

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#762]
Replace the nodes with non preemtible machines.
Make sure we use the SSD boot disk beta feature

**Comment by metalmatze** [comment]
Should we simply use the same node size as right now with the preemptible machines?

**Comment by mrIncompetent** [comment]
Can you check the resource utilization in grafana?

**Comment by metalmatze** [comment]
I think we should be fine with using the same machine type `n1-highmem-2 (2 vCPUs, 13 GB memory)` but running 3 instead of 4 machines. We can easily scale up if we need to on GCP anyway.

**Comment by mrIncompetent** [comment]
Yes, 3 should be fine

**Comment by metalmatze** [comment]
I've created a new node pool with this command:
```
gcloud container node-pools create highmemory --cluster=kubermatic-cloud-europe-west3-c-1-master --zone=europe-west3-c --project=kubermatic-prod --machine-type=n1-highmem-2 --disk-size=100 --image-type=COS --num-nodes=3 --enable-autoscaling --min-nodes=3 --max-nodes=7 --disk-type=pd-ssd
```
The necessary service-account is coming in a PR to the secrets repository?!

**Comment by mrIncompetent** [comment]
Lgtm. Yeah secrets repo seems fine

**Comment by mrIncompetent** [comment]
@metalmatze Whats the status here?
You replaces the nodes but the service-account PR for the secrets repo is missing?

**Comment by metalmatze** [comment]
Oh, didn't see your comment on Friday, that I should put the json for that service account into the secrets repository. PR is coming.
All machines are replaced by static highmemory ones. Running really smooth so far! :relaxed:
