### ISSUE TITLE
sshkey agent override authorized file unconditionally

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/kubermatic#7635]
UPDATE:

It's not supported to have both sshkey agent and preexisting ssh keys, thus docs should be fixed.

ORIGINAL
-----
In https://docs.kubermatic.com/kubermatic/v2.17/tutorials_howtos/administration/user_settings/user_ssh_key_agent/ it's stated that

>any previously added ssh keys in the worker nodes(except the keys that have been added during the cluster creation) will be deleted

But unfortunately that's not the case, agent overrides the authorized_file (almost, meaning if contents do not match) unconditionally.

https://github.com/kubermatic/kubermatic/blob/ad4ca9f86fc62b9d0fd3728b85173b5821a3e470/pkg/controller/usersshkeysagent/usersshkeys_controller.go#L179-L189

**Comment by dermorz** [comment]
@kron4eg 
> It's not supported to have both sshkey agent and preexisting ssh keys, thus docs should be fixed.

Isn't that already documented? Maybe it just needs to be re-worded slightly. What is confusing you in this passage?

> once the agent is deployed after the cluster is created, any previously added ssh keys in the worker nodes (except the keys that have been added during the cluster creation) will be deleted.

Maybe the part in the parentheses is not clear enough, that "during cluster creation" means in the KKP dashboard?

**Comment by kron4eg** [comment]
> Maybe it just needs to be re-worded slightly. What is confusing you in this passage?

Yes, we should be crystal clear that "it's not supported to have both sshkey-agent keys and preexisting ssh keys".
