### ISSUE TITLE
Test cluster provisioning and upgrading on all supported providers

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#7656]
This issue assumes:

* Create a Kubernetes cluster running latest-1 (1.21) release
  * Keep default settings
* Wait for cluster to be ready, then download the kubeconfig for it
* Ensure that all nodes are ready by running `kubectl get nodes`
* Ensure that basic operations work
  * Create a Deployment, try exposing it using NodePort Service, make sure you can reach it out
  * If external CCM is deployed, ensure that:
    * Node object has proper IP addresses (`kubectl get nodes -o wide`)
    * Each node has `providerID` set (`kubectl describe node <node-name> | grep -i providerid`)
    * If supported, create a LoadBalancer Service and make sure it's reachable
    * If supported, create a PersistentVolume and mount it in a pod
* Upgrade the cluster to the latest Kubernetes release, wait for the upgrade to complete.
* Upgrade all machine deployments, so they match the controlplane version.
* Wait for all Machines to get rolled out
* Ensure that all nodes are ready by running `kubectl get nodes`
* Ensure that all resources are created earlier are still functioning
* Try recreating some of resources created earlier

**Acceptance criteria:**
* All manual tests are passing
* All Kubernetes conformance tests are passing

**Supported providers:**
* AWS
* Azure
* DigitalOcean
* GCP
* Hetzner Cloud
* OpenStack
* Packet (Equinix Metal)
* VMware vSphere
* KubeVirt

This is part of #7655

**Comment by WeirdMachine** [comment]
Testing VMware vSphere
