### ISSUE TITLE
Test cluster provisioning and upgrading on all supported operating systems

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#7657]
This issue assumes following all the steps from #7656, but this time choose a single provider (for example AWS) and test all supported operating systems.

**Acceptance criteria:**
* All manual tests are passing
* All Kubernetes conformance tests are passing

**Supported operating systems:**
* (depending on the provider)

Part of #7655

**Comment by WeirdMachine** [comment]
Testing VMware vSphere
