### ISSUE TITLE
Test OPA integration

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#7659]
**Steps**

Test with cluster versions:
- 1.21.3
- 1.22.1 

* Create a user cluster, enable OPA integration.
* Wait for cluster to be ready.
* Use OPA features and see if they work:
   (for Constraint Template and Constraint examples- [opa docs](https://open-policy-agent.github.io/gatekeeper/website/docs/howto/)
   - create/edit/delete a Constraint Template in admin panel ( can be done even before cluster is made) 
        - test Constraint template filtering
   - create/edit/delete  a Constraint in the cluster view 
        - test if it really works on user cluster
        - check if violations are visible on the cluster view
   - create/edit/delete a Default Constraint in the admin panel (can be done even before cluster is made)
       - check if it arrives to the user cluster, test if it works
       - test Default Constraint filtering
       - Activate/Deactivate Default Contraints, check if deactivated ones are not present on user clusters
    - test AllowedRegistires(works like a Default Constraint in the background)
       - create an AllowedRegistry (careful as it could break the user cluster), and check if you can create pods with various image registires
* Delete cluster.
* Make sure the cluster gets cleaned up properly.

- Test upgrade from 1.21.3 to 1.22.1
    - create some CT and constraints in 1.21.3
    - upgrade to 1.22.1
    - check if it all still works

**Acceptance criteria**
* OPA works as advertised.

Part of #7655

**Comment by mfranczy** [comment]
> 
>     create/edit/delete a Constraint Template in admin panel ( can be done even before cluster is made)
>         test Constraint template filtering
>     create/edit/delete a Constraint in the cluster view
>         test if it really works on user cluster
>         check if violations are visible on the cluster view
>     create/edit/delete a Default Constraint in the admin panel (can be done even before cluster is made)
>         check if it arrives to the user cluster, test if it works
>         test Default Constraint filtering
>         Activate/Deactivate Default Contraints, check if deactivated ones are not present on user clusters
>     test AllowedRegistires(works like a Default Constraint in the background)
>         create an AllowedRegistry (careful as it could break the user cluster), and check if you can create pods with various image registires
> 

works ok

> Delete cluster.
> Make sure the cluster gets cleaned up properly.

cluster has been sucessfuly deleted

> Test upgrade from 1.21.3 to 1.22.1
> 
>     create some CT and constraints in 1.21.3
>     upgrade to 1.22.1
>     check if it all still works

works as expected

additionaly I found some user experience issues:
* user should be instructed to paste the spec of a new constraint, not the whole CR
* in case YAML definition is wrong, after pressing a submit button nothing happens, some error should popup
* pasting the whole yaml might be tricky, especially the CRD with target rules of ConstraintTemplate (not sure how to solve that better, some yaml validator in the text area?)
* OPA constrains load slowly
* It's not allowed to edit the constraint name. In that case the form should not give you such a possiblity (it should be locked)
