### ISSUE TITLE
Test option to specify initContainer in promtail chart(#7388)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7684]
**steps:**
* set `Values.promtail.initContainer.enabled` 
* install promTail charl

**Acceptance criteria:**
* when  `Values.promtail.initContainer.enabled: True` Promtail DS has init container setting  the kernel parameter `fs.inotify.max_user_instances` 
* the kernel parameter has been updated on the node.

**Comment by zreigz** [comment]
tested on seed and user cluster:
`fs.inotify.max_user_instances` set to 255
