### ISSUE TITLE
Test Blackbox Exporter configuration, scrape config, dashboard(#7376)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7685]
**Acceptance criteria:**
- A Blackbox Exporter module that can be used to perform health status checks for HTTPS endpoint with TLS verify skipped.
- A Blackbox Exporter dashboard in Grafana.
- A scrape job in Prometheus will be used to check the health status of ClusterIP services of user cluster Kubernetes API servers.

for more information, please take look at #7376

**Comment by wurbanski** [comment]
Default configuration works out of the box, service discovery works.
