### ISSUE TITLE
Test Allow to specify sidecars in Alertmanager Helm Chart(#7329)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7692]
**Steps:**
* edit `.Values.alertmanager.sidecarContainers` to define a sidecar
* edit `.Values.alertmanager.sidecarServicePorts` to define the port exposed in the service
* install chart

**Acceptance criteria:**
* sidecar is added to AlertManager STS
* sidecar is exposed in the AlertManager service

for more information, please take look at #7329

**Comment by wurbanski** [comment]
Sidecars work correctly. I added PR with some in-chart documentation, since it's not a feature expected to be used by end-users https://github.com/kubermatic/kubermatic/pull/7801
