### ISSUE TITLE
Test Add Grafana link to dashboard (#3642)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7693]
**Acceptance criteria:** 
link to grafana is only visible if  if user cluster monitoring or user cluster logging is enabled.

for more information, please take look at kubermatic/dashboard#3642

**Comment by wurbanski** [comment]
The Panel for `Montoring, Logging and Alerting` is hidden with neither metrics nor logs are enabled for a cluster. Works as expected.
