### ISSUE TITLE
Test Add kube-state-metrics addon (#7513)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7695]
**Steps:**
* enable kube-state-metrics addon

**Acceptance criteria:**
* kube-state-metrics is up and running

for more information, please take look at #7513

**Comment by jiachengxu** [comment]
I just noticed this is related to user cluster MLA, which I was involved in, so I will unassign myself, and let other people test this.
/unassign

**Comment by WeirdMachine** [comment]
Works as expected, but a general error was found on deleting addons:
https://github.com/kubermatic/kubermatic/issues/7817
