### ISSUE TITLE
Test Cluster Template

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7698]
**Steps:**
* create a cluster template at each scope
  - [x]  User
  - [x] Project
  - [x] global
 
For each scope : 
* create a template cluster instance 
  * ensure cluster is creating according to the template
  * ensure cluster instance template can be listed 
* increase number of replicas in  the cluster instance template
  * ensure new cluster is created
* decrease number of replicas in cluster  instance template
  *  ensure a cluster is deleted accrodingling
*  delete cluster template instance 
   * ensure all related clusters are removed
  

**Acceptance criteria:**
* template cluster works as expected

for more information, please take a look at :
- Add cluster templates as a general feature #3618 
- Add controller for cluster templates #7364
- Add endpoints for cluster templates instances #7286 
- Add endpoints for list cluster templates #7298 
- Patch endpoint for cluster template instances #7318 
- Add endpoint for cluster templates #7150 
- Fix for number of endpoints #7168
- Add endpoints for deletion of cluster templates #7197)

**Comment by lsviben** [comment]
Tested all, works ok from what I could see. 

Some features listed above we didnt implement in the end:
- listing cluster template instances
- changing number of replicas
- delete cluster template instance and with it all connected clusters

Instead what happens now is that a cluster template instance creates all the set replica clusters, then deletes itself. So the clusters from then on behave like regular clusters and are not connected with the Cluster Template (except label which says from which cluster template they were created)
