### ISSUE TITLE
Test Support the metering tool configuration in the API (#7601)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7701]
**Steps:**
* Tests the follwing endpoints:
  * Configures KKP metering tool. (post: /api/v1/admin/metering/configurations)
  * Creates or updates the metering tool credentials. (post: /api/v1/admin/metering/credentials)

**Acceptance criteria:**
* Support the enabling/disabling and configuring the metering tool in KKP API, so it is possible to manage the metering tool from the UI.

for more information, please take look at #7601

**Comment by lsviben** [comment]
Found 2 issues during testing:
https://github.com/kubermatic/kubermatic/issues/7828
https://github.com/kubermatic/kubermatic/issues/7827
