### ISSUE TITLE
Test Integrate metering into KKP dashboard

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7703]
**Acceptance criteria:**
User should be able to:
* edit meterigin configuration
* list and download metering report
* edit credentials 

as defined in  kubermatic/dashboard#3656

for more information, please take look at kubermatic/dashboard#3564

**Comment by simon-wessel** [comment]
Documentation: https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/metering/

**Comment by WeirdMachine** [comment]
@aborilov can we close this?
