### ISSUE TITLE
Test Support different s3-settings in each Seed #7428

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7705]
**Acceptance criteria:**
* different s3-settings  can be configured for each Seed

for more information, please take look at #7428

**Comment by PratikDeoghare** [comment]
Where? https://dev.kubermatic.io/settings/bucketsettings

What? 
The fields were empty at the start. 

Setting the fields back to empty doesn't work. 

The `Endpoint` field has note under it that if left unspecified `s3.amazonaws.com` will be used. So I expected to be able to 
set it to empty. 

![editendpoint.png](https://images.zenhubusercontent.com/60f52e6e1a8ac47b408a94ef/58b40305-0df5-494b-9959-56022db48a86)
