### ISSUE TITLE
Test AWS spot Instance (#7073)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7710]
**Steps:**
* create a cluster with spot instance.

**Acceptance criteria:**
* cluster is created with spot instances

for more information, please take look at kubermatic/dashboard#3607 and #7295

**Comment by rastislavs** [comment]
Creation of a cluster with spot instances was successful, verified the ec2 instance types in AWS console, also verified that the `aws-node-termination+handler` addon was installed.
