### ISSUE TITLE
Test  option to filter AWS instance types by architecture(#3600)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7711]
**Acceptance criteria:**
In the dashboard check that instance types:
* are filtered by architecture

for more information, please take look at kubermatic/dashboard#3600 and #6940

**Comment by rastislavs** [comment]
EC2 instances are properly filtered by selected architecture in the KKP UI.
Both x64 and arm64 machine deployments can be started, but with this usability issue for the arm64 ones: https://github.com/kubermatic/kubermatic/issues/7786
