### ISSUE TITLE
Test Azure LoadBalancer SKU (#3455)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7714]
**Steps:**

For each sku

- [x] standard
- [x] basic

* create a cluster with the corresponding SKU
* create a lb service
  * ensure lb is created with the correct SKU

for more information please take a look at kubermatic/dashboard#3455, #7208 and #7271

**Comment by simon-wessel** [comment]
Tested and the LB has been created with the correct SKU in all three cases:
- choosing Basic
- choosing Standard
- leaving the option empty/using the default value -> resulting in SKU Basic as intended

/close
