### ISSUE TITLE
Test vNet resource group field for Azure (#3275)

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7715]
**steps**:

- Create a ressouce group for the vnet
- create a cluster in a different resource than one of the vnet 
  - ensure cluster is created in one resource group and the vnet in another

for more information please take a look at kubermatic/dashboard#3275, #6908, kubermatic/dashboard#3399

**Comment by simon-wessel** [comment]
Creating the VNet in a different resource group works, but the cluster deletion was stuck afterwards. Ticket: https://github.com/kubermatic/kubermatic/issues/7816

**Comment by simon-wessel** [comment]
Stuck cluster was fixed in https://github.com/kubermatic/kubermatic/pull/7818
/close
