### ISSUE TITLE
Test Azure availability sets

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7716]
**Acceptance Criteria**

- A new check box is added in the KKP dashboard that specify whether the clusters worker nodes are created in availability set.
- If the check box is enabled then the availability zones drop down list on the add machine deployment step should be disabled as it is not possible to create both worker machines in Availability Sets and Availability Zones.

**Comment by rastislavs** [comment]
As mentioned in the description, either "Assign Availability Set" or Availability Zone can be selected when creating a new cluster / machine deployment. Creation of a new cluster verified to work both ways.
