### ISSUE TITLE
Test Storage policy in vSphere #7423

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7720]
**Steps:**
* create a cluster
* ensure DefaultStoragePolicy field has been added to the vSphere datacenter spec and storagePolicy to the vsphere CloudSpec at cluster level

for more information, please take look at #7423

**Comment by jiachengxu** [comment]
I noticed a bug that the csi-migration-webhook will be enabled when the StoragePolicy was set, which blocked the creation of storage classes.
This is fixed in: https://github.com/kubermatic/kubermatic/pull/7799
and I will test it one more time with the fix

**Comment by jiachengxu** [comment]
I have tested this feature by setting the storage_policy in Seed to `e2e-test-policy` and I can see this has been passed to `cluster.spec.cloud.vsphere.storagePolicy`, as well as the `parameters.storagepolicyname` in StorageClass `vsphere-csi` in user cluster.
/close
