### ISSUE TITLE
Test vSphere resource pool #3471

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7721]
**Acceptance criteria:**
when creating a cluster ensure there is an  option to specify vSphere resource pool and resource are created in the resource pool

for more information, please take look at kubermatic/dashboard#3471

**Comment by jiachengxu** [comment]
During testing this feature, I found that ResourcePool is not in the vSphere Preset definition, however, if I select the preset during the cluster creation, I am not able to set values for ResourcePool
The following PRs add ResorucePool to preset:
https://github.com/kubermatic/kubermatic/pull/7796
https://github.com/kubermatic/dashboard/pull/3693 
I will retest this feature with the above fixes.

**Comment by jiachengxu** [comment]
I have tested this feature by adding `e2e-resource-pool` to preset, and created vSphere cluster from it.
I can see that resource pool value has been propagated to cluster.spec.cloud.vsphere.resourcePool, and the VM is created under the e2e-resource-pool as expected.
/close
