### ISSUE TITLE
Test Add container runtime selector #3448

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7726]
**Acceptance criteria:**
* ensure a cluster can be created with `containerd` engine 

for more information, please take look at kubermatic/dashboard#3448 and #7225

**Comment by jiachengxu** [comment]
I have tested this in test env with KKP.
I created a cluster on AWS with containerd selected, and I verified the the cluster was containerd as container runtime by doing `kubectl describe <node_name>`, and looking into the `Container Runtime Version`.
/close
