### ISSUE TITLE
Test network configuration for user clusters #3460

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7727]
**Acceptance criteria:** 
in the cluster creation wizard check, these field can be specified and cuslter is created with this configuration:

- Pods CIDR
- Services CIDR
- Proxy mode (`iptables` or `ipvs` )

for more information, please take look at kubermatic/dashboard#3406, #6970

**Comment by rastislavs** [comment]
The network configuration works as expected.
