### ISSUE TITLE
Test NodeLocalDns

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#7730]
**Acceptance criteria:**
* check NodeLocal DNS can be enabla and disable, and works acoodingly ( cf #7091, #7075 )
* when is deployed, check ds as toleration `CriticalAddonsOnly` cf #7466

**Comment by mlavacca** [comment]
Didn't find anything in the UI to enable/disable this feature. As it is written in the PRs, such a field is immutable and set by default, but it is not possible to disable it from the UI. @rastislavs am I supposed to be able to set it from the UI?

**Comment by mlavacca** [comment]
`CriticalAddonsOnly` toleration verified in the `node-local-dns` ds.

**Comment by rastislavs** [comment]
@mlavacca you are right, it seems that this option was not exposed in the UI. So ATM it is only possible to set it when creating clusters via API.

**Comment by mlavacca** [comment]
The UI part will be implemented after the release. For the time being, I checked the API functionality and it works as expected:
* The field is immutable for existing clusters
* It can be set for new clusters (defaulted to true)

/close
