### ISSUE TITLE
Terminology question

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#778]
based on #769 

Let's define a clear terminology which we will use also at Customer side 

`Master cluster`: Initial/First/Master kubernetes cluster in a kubermatic setup. It's purpose is to serve the kubermatic dashboard and API. Also it hosts the ssh keys of a user & it currently hosts the cluster custom resources.

`Seed cluster`: A kubernetes cluster which only hosts the master components of a customer cluster.  Not used if we use a single `Master cluster`

`Customer cluster`: A cluster, you created via the kubermatic Dashboard/Components. 

Should we call it `Customer cluster` or `User cluster`

**Comment by metalmatze** [comment]
So far I've only heard the term Customer Cluster. But I like User Cluster too, as Customer Cluster sounds like everyone has to pay.

**Comment by mrIncompetent** [comment]
We have an "official" terminology https://github.com/kubermatic/kubermatic-installer

Changing to `User cluster` seems good to me. 
But i would accept both to not cause confusion due to a hard change.

**Comment by mrIncompetent** [comment]
After https://github.com/kubermatic/kubermatic-installer/pull/5 has been merged, we can consider this done?
@metalmatze
