### ISSUE TITLE
GCP

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#7808]

**Comment by mfranczy** [comment]
I tested manually the upgrade and it's fine. Still waiting for conformance tests results, it takes a while.

**Comment by mfranczy** [comment]
Result: 

Plugin: e2e
Status: failed
Total: 6432
Passed: 307
Failed: 13
Skipped: 6112

Failed tests:
[sig-storage] Downward API volume should provide container's memory limit [NodeConformance] [Conformance]
[sig-node] Downward API should provide pod name, namespace and IP address as env vars [NodeConformance] [Conformance]
[sig-cli] Kubectl client Guestbook application should create and stop a working application  [Conformance]
[sig-storage] Downward API volume should provide container's cpu request [NodeConformance] [Conformance]
[sig-node] Downward API should provide host IP as an env var [NodeConformance] [Conformance]
[sig-storage] Projected downwardAPI should provide container's memory limit [NodeConformance] [Conformance]
[sig-storage] Downward API volume should provide container's memory request [NodeConformance] [Conformance]
[sig-storage] Projected downwardAPI should provide container's memory request [NodeConformance] [Conformance]
[sig-storage] Projected downwardAPI should provide container's cpu limit [NodeConformance] [Conformance]
[sig-node] Downward API should provide pod UID as env vars [NodeConformance] [Conformance]
[sig-node] Downward API should provide container's limits.cpu/memory and requests.cpu/memory as env vars [NodeConformance] [Conformance]
[sig-storage] Projected downwardAPI should provide container's cpu request [NodeConformance] [Conformance]
[sig-storage] Downward API volume should provide container's cpu limit [NodeConformance] [Conformance]

Plugin: systemd-logs
Status: passed
Total: 3
Passed: 3
Failed: 0
Skipped: 0

some tests failed, I have to investigate what happened

**Comment by mfranczy** [comment]
I ran another tests and looks like those tests were just flaky, different output.
Generally speaking the cluster works fine.
