### ISSUE TITLE
Addons Container not releases for 2.18

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubermatic#7844]
It looks like there is no addon container with the release tag, only the RC candidate. 

![2021-09-20-141717_1871x305_scrot](https://user-images.githubusercontent.com/9881497/134000828-7a8ae897-2c30-4fd1-a289-73d5345f778c.png)

Or did the registry location changed? Then the docs need a update.

**Comment by kron4eg** [comment]
addons are available at https://quay.io/repository/kubermatic/addons?tag=latest&tab=tags

**Comment by qeqar** [comment]
and i see you release the tag now.

Will use that as it is clearer as latest.
