### ISSUE TITLE
Migration script and documentation for KKP3 CRDs

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#7866]
**User Story**

When we switch to KKP3, we will change the API groups of our CRDs so that we move from the forbidden *.k8s.io and also that we unify our api groups:

kubermatic.k8s.io + operator.kubermatic.io -> kubermatic.k8c.io 

After the change, we wont support the old ones anymore.

Add a migration script and documentation for the migration to the new KKP CRDs. 

**Acceptance criteria**
- [ ] User clusters are working during the migration
- [ ] Migration script is ready and tested
- [ ] Migration is documented

**Comment by xrstf** [comment]
> Add a migration script and documentation for the migration to the new KKP CRDs.

Instead of a script, this should be part of the KKP installer. It's already built to have sub commands, so we can easily add a `migrate-crds` subcommand.
