### ISSUE TITLE
Replace old *k8s.io CRDs with new kubermatic.k8c.io CRDs in code

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#7868]
**User Story**
Make the switch in the codebase. 

This will require a temporary code freeze to avoid conflicts.

**Acceptance criteria**
- [ ] Old CRDs are removed and not used anymore
- [ ] Tests are passing, KKP working as expected

**Comment by kron4eg** [comment]
/close

this has been completed
