### ISSUE TITLE
Move metering report download links to the Seed Status

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#7872]
**User Story**
Metering download links are now generated and available just through the REST API endpoint.To support a declarative approach, we should have those links in the Seed object Status.  

**Acceptance criteria**
- [ ]  Metering report download links are in the Seed object Status

**Comment by simon-wessel** [comment]
Just to add some information about the download links:
The S3 specification only allows generating pre-signed links which are valid for up to 7 days ([Source](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)). As far as I know, permanent links are not possible for buckets with non-public content. This is why the API generates them on demand.

**Comment by toschneck** [comment]
@dharapvj FYI
