### ISSUE TITLE
UserCluster MLA E2E tests: Deploy, Grafana Org and Datasource

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#7890]
Test that MLA deployed and check that corresponding Grafana Org and Datasource created

**Comment by aborilov** [comment]
* test metrics - we generate some metrics in the user cluster, force them to be pushed to the seed cluster and then query cortex in the seed cluster to see if read path is working
* test logs - we generate some logs in the user cluster, force them to be pushed to the seed cluster and then query Loki to see if read path is working
