### ISSUE TITLE
End 2 End Networking Benchmarking of KKP 

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#7924]
**User Story**
As a user I want to know all relevant latencies throughout the Kubermatic Platform Stack so that specific requirements (like 5G) can be matched.

Root - Seed - User - Workload in user cluster (pods, deployments)

End user workload perspective
- Responsiveness within the user cluster; https://github.com/vmware-tanzu/k-bench
- Any action on the user does in terms of editing the cluster (covered by k-bench)
- Latency from outside of the application (example accessing software from my car)
- East / West traffic within the cluster

End user management perspective
- Add machine deployments
- Add new cluster with machine deployments
- Upgrading machine deployment
- Recovery of nodes

Competitor Benchmark
- Comparison to KubeOne (vanilla k8s)
- Comparison to EKS

**Problems in perception**
- What type of latency could be misleading?
- Reproduceable measurements

**Acceptance criteria**
- Cilium as CNI
- Clean KKP Installation on AWS

**Comment by PratikDeoghare** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Work-in-Progress---The-A-Team-5fa971db111c0d0018ce0008/issues/kubermatic/kubermatic/7924?planning-poker) with ZenHub @rastislavs
