### ISSUE TITLE
MachineSpec: Authentication failed occurred when `$` is contained in password

### ISSUE THREAD

**Issue by cedi** [kubermatic/kubermatic#7960]
We had a user with a `$` in his password, which he used for his OpenStack credentials.
He is able to login perfectly fine to OpenStack Horizon with this password, as well as authenticating in KKP (since we use OpenStack Keystone as OAuth Backend in KKP.
He is also able to create a new Cluster using this password as the Login in his CloudProvider settings in the KKP-Dashboard UI.

However, the MachineDeployment is unable to deploy nodes, since it tries to interpret the `$` in the password, since the password is stored in a Kubernetes Object in etcd.
This throws the error:
```
admission webhook "machine-controller.kubermatic.io-machinedeployments" denied the request: failed to default machineSpec: An error of type = InvalidConfiguration, with message = A request has been rejected due to invalid credentials which were taken from the MachineSpec: Authentication failed occurred
```

I believe the problem could be fixed by properly escaping the password.

**Comment by kron4eg** [comment]
update:

after debug session no issue has been found.
