### ISSUE TITLE
Introduce Applications

### ISSUE THREAD

**Issue by themue** [kubermatic/kubermatic#7974]
This epic targets the introduction of a new mechanism for users to install their applications. For improvements to the Addon-mechanism, which is used by Kubermatic to deploy mandatory components, see https://github.com/kubermatic/kubermatic/issues/6180. 

The current implementation of Addons has some flaws that make the usage and maintenance of Addons cumbersome for cluster administrators:

- Mandatory core components of user clusters are named “Default Addons” which implies that these are optional
- To add “Custom Addons” the cluster admin needs to bundle manifests and templates for these Addons in a Docker image that is based on the official addon-manifest docker image by Kubermatic
- It’s currently only possible to deploy multiple instances of the same Addon when using a workaround
- Complex Addons can leave a trail of reconciliation errors until successfully deployed because all manifest files are applied at the same time
- Addons are strictly tied to KKP versions due to the composition logic of the manifest image tag; for any provided manifest image the tag gets overwritten with `:<KKP VERSION>[-CUSTOM SUFFIX]`
- Creating a cluster is a two-step process; firstly you have to create a cluster and only  afterwards you can select custom Addons

## Default Addon

A *Default Addon* is installed on all user clusters based on configuration. The user can not delete *Default Addons*. These will remain unchanged after this proposal

- Shipped by Kubermatic,  tied to KKP version
- Tested by Kubermatic (Kubernetes versions)
- Supported by Kubermatic

## Application

An *Application* is an additional component installed in all user clusters on-demand, but not shipped with KKP. It is provided by the customer or a third party (e.g. helm community):

- Shipped by the customer
- Not tested nor supported by Kubermatic
- Could break clusters
- The customer is fully responsible

## Application by Kubermatic

An *OptionalApplication* is installed in a user clusters on demand during runtime or at cluster creation. The user can also uninstall and reinstall them. They are visible in the KKP UI.

- Shipped by Kubermatic, tied to KKP version (KKP version will be enforced using the aforementioned constraint feature)
- Tested by Kubermatic (Kubernetes versions and customizations)
- Supported by Kubermatic

*Note: From a technical perspective, Applications and Applications by Kubermatic will be handled the same way. However from a contractual perspective, it is important to differentiate: Applications by Kubermatic are supported by Kubermatic, while regular Applications are not.*

**Comment by vgramer** [comment]
the first version of application feature has been delivered in KKP 2.21
