### ISSUE TITLE
Allow Cluster Admin to install Applications during Cluster Creation

### ISSUE THREAD

**Issue by themue** [kubermatic/kubermatic#7975]
**User Story**

As a KKP Admin I want to be able to pick Addons during cluster creation so it is automatically installed once the cluster is ready. 

See also: #6000 #1904

**Comment by cschieder** [comment]
Isn't there already an epic for this topic here #6180 - [Zenhub Link](https://app.zenhub.com/workspaces/work-in-progress---team-product-606ec73090e027001169c9e7/issues/kubermatic/kubermatic/6180)?

**Comment by SimonTheLeg** [comment]
@cschieder I think before it was. It would basically be a sub-epic of 6180. With the new split in Applications and Addons, from my perspective it makes sense to move this into introduce applications and keep them separate
