### ISSUE TITLE
Update customer master

### ISSUE THREAD

**Issue by sttts** [kubermatic/kubermatic#80]
Update order:
- update etcd
- update apiserver
- update scheduler + controller manager
- update nodes

Proposed extension of the phase automaton:
- Current phases: Unknown, Pending, Launching, Failed, Running, Paused, Deleting
- New phase: Updating

When _Updating_, we add UpdatePhases:
- Start, UpdateEtcd, UpdatedEtcd, UpdateApiserver, UpdatedApiserver, UpdateController (including scheduler), UpdatedController, Done

An UpdateController will watch cluster with Phase _Updating_ and do:
- Start: switch to UpdateEtcd
- UpdateEtcd: if version differs, change etcd deployment -> UpdatedEtcd
- UpdatedEtcd: wait until etcd is healthy -> UpdateApiserver
- UpdateApiserver: if version differs, change apiserver deployment -> UpdatedApiserver
- UpdatedApiserver: wait until apiserver is healthy -> UpdateController
- UpdateApiserver: if version differs, change scheduler+controller-managers deployments -> UpdatedControllers
- UpdatedControllers: wait until scheduler+controller-manager is healthy -> Done

The ClusterController will watch clusters with Phase _Updating_ and _UpdatePhase_ "Done" and switch it to Running.

**Comment by sttts** [comment]
What about rollback if a step fails?

**Comment by scruplelesswizard** [comment]
I think we should take a look at the dependencies... Usually there isn't an issue with etcd version vs kube version, but i.e. etcd3 there could be some issues with older k8s versions, and iirc it required a manual step in the upgrade

In general though, usually k8s components tend to be backwards compatible, so I think we should be okay to leave components in their new state, assuming they are running, and only roll back if they are failing

**Comment by sttts** [comment]
A new controller/scheduler will not be compatible with an old apiserver. Same for the kubelet.

**Comment by scheeles** [comment]
I think, when the update fails we should rollback. The main questions is, if the update fails if a rollback will work.

Additional we should have the option, to set the version you would like to update and perhaps als to downgrade. E.g. if you are on 1.4.3 and there is 1.4.6 and 1.5.0 available the user should use to which version he wants to go.

I think we should do it in an similar way as google is doing it with GKE.
