### ISSUE TITLE
Add reconciling for cloud-infrastructure (Proposal)

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#800]
Current state:
The cluster controller does a one-time setup at the cloud-provider for each cluster.
This includes:
- AWS
  - Search for default infrastructure
  - Creation of security groups
  - Creation of instance profiles
- OpenStack
  - Search for default infrastructure
  - Creation of security groups
  - Creation of network, subnet & router

The problem:
With newer versions of the cluster controller it might be necessary to change the security groups (or anything else infrastructure related) we create.
While that works for new clusters, it certainly does not for already existing clusters.

Desired state:
Instead of doing a one-time setup at the cloud provider, we should integrate it into the normal reconciling loop. So on each synchronization loop of a cluster, we check if the infrastructure at the cloud provider still matches what we actually need.
For most things a `if !exists { create() }` should be enough. But for something like a security group we actually need to check if it looks the way we want, and if not, we modify it.

**Comment by alvaroaleman** [comment]
Yeah, definitely makes sense
