### ISSUE TITLE
Enable Loadbalancer health check for Openstack Octavia on KKP

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8010]
**User Story**
As a user, I want to have a working health check for my Octavia Loadbalancer so that an unhealthy node get rescheduled. 

**Acceptance criteria**
- Octavia LB health check is working as intended
- Unhealthy nodes get rescheduled

Original problem:
Openstack cloud controller manager added a flag in the Loadbalancer spec to indicate whether or not to create a health monitor for the service load balancer. This feature is not enabled in Kubermatic, the only way to enable it is to pause the cluster then update the cloud-config  to include create-monitor=true, and this is not the best way to do it.
```
kubectl -n cluster-*** edit cm cloud-config
apiVersion: v1
data:
 config: |
    .....
   [LoadBalancer]
    .....
   create-monitor = true.      <-------
```
Why this feature is needed?
This feature will help us to know if a loadbalancer member is healthy or not. If we do not have a health monitor, failed members are not removed from the pool. This can lead to service disruption for our clients.

**Comment by syjabri** [comment]
Yes, adding the annotation to service of type Loadbalancer **loadbalancer.openstack.org/enable-health-monitor: "true"** helps but not by default for all loadbalancers in the customer clusters.

**Comment by kron4eg** [comment]
> Yes, adding the annotation to service of type Loadbalancer **loadbalancer.openstack.org/enable-health-monitor: "true"** helps but not by default for all loadbalancers in the customer clusters.

Loadbalancers in the user clusters are the responsibility of the user, isn't it?

**Comment by syjabri** [comment]
> Help me out, if we cannot use this as an default option, how is this supposed to work?

if we can't use it as a default option, the only solution to not have problems with customers is to document the necessary steps and this is feasible.

> Loadbalancers in the user clusters are the responsibility of the user, isn't it?
Yes, but we can't ignore customer problems.

**Comment by moadqassem** [comment]
FYI, you can actually override the cloud config in the machine deployment using this field https://github.com/kubermatic/machine-controller/blob/master/pkg/providerconfig/types/types.go#L124, however I would strongly recommend if you are not sure about the configs to leave that out, as this will have a direct impact on your cluster.

**Comment by qeqar** [comment]
The Cloud config override in the Machine Controller should only effect machines created from it, or?

The openstack-cloud-controller uses the default one.

And as most of the customer cluster machine deployments get created via UI and i don't see a way to update the cloud config there.
