### ISSUE TITLE
Enhance Resource Quota per project and user level

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8042]
**User Story**
As a KKP admin, I want to limit the resources consumed for projects and users individually so that I can better distribute available resources between my users.

**Acceptance criteria**
- User can set a sensible quota per project (self management)
- Admin can set a sensible quota per project
- Admin can set a sensible quota per project and as a general default separately
(e.g. only create 100 projects per user and consume not more than 10.000 vCPU per project as a general rule)
- Admin can set a sensible quota per user
- Admin Panel supports this via UI and gives good overviews (users with limits, users without limits, projects with limits etc.)
- API is working accordingly

**Comment by undefinedhashtag** [comment]
Hey guys, any idea when this could be realized? :)

**Comment by shaase-ctrl** [comment]
This epic is in active development right now. It will become available in a release after April.

**Comment by csengerszabo** [comment]
Created a quick [mockup](https://app.moqups.com/7ea2kh3jjgOP1QmOaYhwVeK40fsg526D/view/page/ad64222d5), how about something like this?

**Comment by lsviben** [comment]
> Created a quick [mockup](https://app.moqups.com/7ea2kh3jjgOP1QmOaYhwVeK40fsg526D/view/page/ad64222d5), how about something like this?

@cschieder @maciaszczykm @floreks could you take a look?
