### ISSUE TITLE
NodePort range is not opened up for existing clusters

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#8079]
Right now this condition blocks updates to existing security groups:

```
if cluster.Spec.Cloud.Openstack.SecurityGroups == "" {
    // Create security groups.....
}
```

Example: https://github.com/kubermatic/kubermatic/blob/master/pkg/provider/cloud/openstack/provider.go#L231

If we create a new cluster the appropriate nodeports will be opened but this change won't reflect in existing clusters. Which is not the expected workflow. The issue is there for all cloud providers.

**Comment by xrstf** [comment]
We intend to solve this via proper reconciling, but in the meantime if this is a real blocker, customers can `kubectl edit` the Cluster object and remove `spec.cloud.openstack.securityGroups` value and KKP will then forget that it already created the group and try again. And this will already be done very carefully: https://github.com/kubermatic/kubermatic/blob/e8be61f5a846e6099c998a8b967f1868290a6bde/pkg/provider/cloud/openstack/helper.go#L160

So while this is a bug and we will fix it, it's not super urgent as customers can work around this quite easily.
