### ISSUE TITLE
NodeController

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#81]
- [ ] refactor the api-server and move the creation of Nodes into a separate node controller #83 
- [ ] clear interface for integration of more provider #84
- [ ] GCP integration https://github.com/kubermatic/api/issues/76
- [ ] Azure integration
- [ ] Openstack integration
- [ ] Vmware integration
- [ ] Update nodes

**Comment by mrIncompetent** [comment]
Duplicate
