### ISSUE TITLE
configurable cloud config for clusters

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubermatic#8126]
As we have a constant pain in not being able to modify the cloud config of KKP Customer Clusters, we would like to have them generally configurable.

For example, we have already two open tickets: #8010 and #7955. These tickets want to make specific options configurable. 

But we would like to have a more generic solution to set such options. The best place would be the kubermaticconfiguration, also it would be great to be able to define overrides in the cluster object itself.

The cluster object could then also be used to handle transitions for existing clusters.

**Comment by kron4eg** [comment]
cc @shaase-ctrl

**Comment by shaase-ctrl** [comment]
As discussed we could think about a solution per seed cluster to make these defaults configurable. We will investigate further.
