### ISSUE TITLE
Enable Konnectivity by default for newly created user clusters

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#8129]
In KKP UI, the Konnectivity checkbox on the cluster creation page should be enabled (checked) by default:

![image.png](https://images.zenhubusercontent.com/5f9feacdd87c6f0418bee1e8/29fecc52-c258-4819-8c1a-0068fde3055d)

Note: in case that the Konnectivity feature gate in KKP is not enabled, this checkbox should not be shown at all (which should already be the case) and the value should not be set in the API call.

**Comment by maciaszczykm** [comment]
This will also have impact on https://github.com/kubermatic/dashboard/issues/3807.
