### ISSUE TITLE
Gatekeeper-Audit Deployment is not adjusting to Cluster Size

### ISSUE THREAD

**Issue by mfahlandt** [kubermatic/kubermatic#8166]
If you enable Gatekeeper in a User Cluster and the Cluster is heavily utilized or  a lot of constrains are in place, you run into the issue that the gatekeeper-audit deployment (namespace: "gatekeeper-system")  will eventually fail with OOMKilled.

This was recognized by the Gatekeeper developers in the following issues as well.

https://github.com/open-policy-agent/gatekeeper/issues/339
https://github.com/open-policy-agent/gatekeeper/issues/780 

The case is a strict limit to the deployed resources. If you change the limits & requirements in the deployment it will get overwritten by the crd it seems. 

What did you expect to happen:
Either an upscaling of the gatekeeper-audit deployment  or the possibility to adjust the limits for the deployment  in order to match the requirements

KKP Version: 2.18.2
Enviroment: VSphere
UserCluster: 16 Nodes a 6 CPU 16 Gig Mem

**Comment by embik** [comment]
Note: Gatekeeper Audit can be configured to chunk the processing of resources (see https://open-policy-agent.github.io/gatekeeper/website/docs/audit#configuring-audit) to make the memory consumption more consistent.

**Comment by mfahlandt** [comment]
> Note: Gatekeeper Audit can be configured to chunk the processing of resources (see https://open-policy-agent.github.io/gatekeeper/website/docs/audit#configuring-audit) to make the memory consumption more consistent. By default there's not chunk size configured, which means it can use "infinite" memory (well, until the pod memory limit hits).

Yes, of this i'am aware. However, we had the same issue in the MLA stack for User Cluster, that the default deployment is to small for large clusters, so i think this still should scale or be adjustable
