### ISSUE TITLE
Preset restriction to data center is visible in UI but not implemented

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#8170]
**User Story**
The likely improvement of the Presets to bind to the data center is visible in the UI, but not implemented in the API or in the Preset spec. 

This confuses users, ether we should disable the not working option as long as it's not implemented or we should quickly introduce it.
![Selection_268.png](https://images.zenhubusercontent.com/5b6454d031c5fe7463837d8b/f602fcf6-16d7-418d-99f8-02112d33c982)

Similar to https://github.com/kubermatic/kubermatic/issues/7260 the Preset functionality should be improved so user can manage the access to credentials in a more detailed way.

**Acceptance criteria**
- [ ] implemented or deactivated

**Comment by Happy2C0de** [comment]
@toschneck 
Thank you for picking up this topic. 👍 
IMO, it would be best to have a `presetprojectbinding` similar to the `userprojectbinding`. This would allow fine-grained assignment of presets to projects.

**Comment by toschneck** [comment]
Yeah ĺike this as well. But  I think you will have multiple levels where presets make sense:
- Global: e.g. some dev accounts what get cleanup and everyone should use it easy
- per datacenter: some special per datacenter preset config
- per project (also cluster template helps) to give a project lead the capability to manage secrects
- per user: so every user could potential store their private credentials

**Comment by Happy2C0de** [comment]
Yes, the cluster template implementation has a good granularity!
Thank you a lot for taking up this topic. I am looking forward to see some progress in this direction :)
