### ISSUE TITLE
Investigate disk.enableUUID set to true in KKP 

### ISSUE THREAD

**Issue by moadqassem** [kubermatic/kubermatic#8238]
**User Story**
To provision user clusters on top of vSphere, we need to prepare a VM template which can be used by machine controller to clone VMs for user clusters. In the documentation we mention that, the template VM should have the `disk.enableUUID` property set true. I believe this was added their by mistake, due the fact that, if template VM enable disk UUID the cloned VM will inherit that UUID which would impose a huge storage inconsistency for that cloned VM as the it is using a disk UUID of another VM. 
  
**Acceptance criteria**
- Test what happens if the `disk.enableUUID` is true in the template VM
- Adjust the documentation accordingly if the mentioned concerns above are valid in both K1 and KKP docs.

**Comment by WeirdMachine** [comment]
According to vmware docs for csi it is required that  disk.enableUUID is set to true, although i had no issues when it was not set.  

https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html

**Comment by moadqassem** [comment]
> According to vmware docs for csi it is required that  disk.enableUUID is set to true, although i had no issues when it was not set.  
> 
> https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html
> 

We need to distinct an important thing here. When you are talking about setting the disk.enableUUID you are talking about setting it on the worker node itself not on the template instance(the machine template that we clone our worker nodes of). This is a very important detail.

**Comment by WeirdMachine** [comment]
Since this is a requirement for the storage csi plugin to work properly I created a follow up ticket about the hardware version requirement, that should be ensured like the disk.enableUUID parameter.
https://github.com/kubermatic/machine-controller/issues/1118
