### ISSUE TITLE
Kubernetes Dashboard to old to show Ingress resources for 1.22 clusters

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubermatic#8241]
We have a KKP 2.18.2 installation and 1.22 Customer Cluster.

KKP still installs the k8s-dashboard V2.0.4.
That dashboard uses ingress.extension to show ingress and that is not supported in 1.22 anymore.

So I get a 404 in that page: 
![image](https://user-images.githubusercontent.com/9881497/142213148-e1fe5555-3206-4592-87f0-ccab3f017339.png)

i tested the newest dashboard version v2.4.0 where it's works again.

**Comment by Zaunei** [comment]
Should be fixed with master with #8172.

**Comment by embik** [comment]
The cherrypick for 2.18 has just been merged, so this should be included in the next 2.18 patch release and in the next KKP release.

**Comment by embik** [comment]
This is fixed with https://github.com/kubermatic/kubermatic/releases/tag/v2.18.3, I'll close this ticket as a release including it is available. Please reopen if you have any follow-ups!
