### ISSUE TITLE
Research: Dex as multi-IdP Broker

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#8261]
One of the challenges for reworking our OIDC implementation is to support multiple IdPs **simultaneously**. In order to solve this challenge, it might be possible to use DEX as a multi-IdP bundler.
Being able to offload the multi-IdP functionality to DEX, would save us a lot of refactoring as we only have to support DEX as IdP and can keep our current single IdP functionality in place. Additionally we would be able to use all of the IdPs that DEX supports. Therefore this possibility should be researched.

**Acceptance criteria:**
- DEX is being used with multiple identity providers simultaneously
- It is possible for one email address to be a member of more than one IdP 
- DEX makes it possible from the issued token to see the email address. We need the email address later for display purposes in the FE

**Implementation Hints:**
- In order to check if it is possible for one email address to be in more than one IdP, it makes sense to check the `sub` field. This needs to be a globally unique identifier

**Comment by embik** [comment]
Note: I'm not 100% sure about the context of this issue, but dex is already used (or rather, can be used) as a multi-provider IDP broker. See https://docs.kubermatic.com/kubermatic/v2.18/guides/kkp_security/securing_system_services/ for mention of Dex and Identity-Aware proxy configuration. Dex is installed as part of a KKP master setup (from https://github.com/kubermatic/kubermatic/tree/master/charts/oauth).

**Comment by SimonTheLeg** [comment]
@embik 
Yeah this exactly the context. Basically I think it makes sense to see if dex can also be configured to handle multiple IdPs at the same time, without any ID collision (which I don't want to go into details, but you can check-out section 2.5.3 from the [spec](https://openid.net/specs/openid-connect-basic-1_0.html)). And if that is the case, we can change on our side to not use the email from the claim, but the subject which was generated by dex without the need to implement any multi-IdP solution.

**Comment by Happy2C0de** [comment]
Also some thoughts from my side ✌️ :)
Email is not persistent in many IdPs, what's good! You can provide primary and secondary emails and switch in between them. @SimonTheLeg mentioned it correctly, the focus should be on a unique identifier like `sub` whereby `sub` is an IdP specific property. Here, one might have to make a link btw. initial login email and `sub` fields from IdPs (not sure).

KKP has a problem because it maps `email` and `sub` to the user property and afaik, it doesn't reconcile them, does it?
The email gets hashed to the User Name/ID of the KKP User CRD and `sub` gets mapped to the `spec.ID` of the user. Not sure if this ID is even used or reconciled, is it?

**Comment by SimonTheLeg** [comment]
@Happy2C0de 
Basically yes. So KKP creates a user-object which includes:
* k8s-object-Name ⟹  base16 representation of sha256 of email address (https://github.com/kubermatic/kubermatic/blob/master/pkg/provider/kubernetes/user.go#L112)
* spec.Id ⟹  sha512 of the `sub` field + "_KUBE" suffix https://github.com/kubermatic/kubermatic/blob/master/pkg/util/hash/user.go#L30-L31
* and then name and email come from the corresponding claims (https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/middleware/middleware.go#L283)

And all of the values will get saved into the k8s object. If by "reconcile" you mean stored in k8s then all of these get stored there (is some shape or form 😄 ). This in turn means they are available to the backend during other calls, as the backend carries them through the context. 
Although this is not 100% spec conform, the larger issue lies in how KKP determines if a user already exists or not. For this it loops through all k8s user objects and returns the first match directly on the `Spec.Email` field (https://github.com/kubermatic/kubermatic/blob/master/pkg/provider/kubernetes/user.go#L84). In the greater context this currently means that if a user with this address already exists the backend simply is going to assume that user already exists and fetches the object, instead of creating a new user. And yes this is the major refactoring we have to do in order to support users with the same mail addresses.

I hope this helps a bit in clearing up any open questions. On another note: This ticket here is one step before the aforementioned refactoring. Basically, we need to see how DEX handles multiple IdPs. To put it casually this ticket is about finding out if DEX bundles all the IdPs and returns unique `sub` fields or if the combination of `sub` and `issuer` is unique and if there is anything else to look out for. So step-by-step we will get there :)

**Comment by Happy2C0de** [comment]
@SimonTheLeg 
Thanks for the feedback. :) Yes, the mapping to the k8s object properties was more or less clear even though I wasn't able to reproduce the sha256 of the `sub` field, once I tried it. (I tried it, because in certain admin situations like provisioning a new user & project, it would be very helpful to pre-create a User via API, and I tried to find out if this is feasible with KKP. Afaik, it's not) Probably, I just missed a tiny element.

But, I was not aware of the looping, which certainly helps with the understanding. Thanks for the pointer. 👍 
With "reconcile", I mean the `sub` field. We already connected two IdPs via Dex to KKP and login with identical Emails worked with both IdPs. Afair, the one thing that didn't work was the update of the `spec.sub` field. I am not even sure, if this field is anywhere used at the moment. But, with the future plans you mentioned, it will certainly become more relevant.

Very good approach though. I am looking forward to see some progress on this topic. 
An additional trap that you might want to look out for. What if a user changes its primary email within a given IdP? --> The user is the same and the `sub` field persists, but KKP will create a new User with no project and preset bindings what locks the user out of its KKP projects.

**Comment by SimonTheLeg** [comment]
I have finished a small test:

## Setup

I created a keycloak with two realms `rainbows-and-unicorns` and `darkness-my-old-friend`, that are going to act as our two identity providers.
![image](https://user-images.githubusercontent.com/20774623/143413323-12f695e1-11f5-40ae-a6e7-3a0ae8d582cb.png)

In both the IdPs I created an identical user
![image](https://user-images.githubusercontent.com/20774623/143416495-1cf81318-5997-4078-98ab-a4c8ae5e3da5.png)


Then I have modified the `examples/config-dev.yaml` from dex quickstart to connect to the two IdPs
```yaml
connectors:
  - type: oidc
    id: rainbows-and-unicorns
    name: rainbows-and-unicorns
    config:
      issuer: http://localhost:8080/auth/realms/rainbows-and-unicorns
      clientID: dex
      clientSecret: 6530283e-4852-4501-ae91-3ef555a40377
      redirectURI: http://127.0.0.1:5556/dex/callback
  - type: oidc
    id: darkness-my-old-friend
    name: darkness-my-old-friend
    config:
      issuer: http://localhost:8080/auth/realms/darkness-my-old-friend
      clientID: dex
      clientSecret: 5ec1e673-4a2e-4e99-8c33-529a255c40ce
      redirectURI: http://127.0.0.1:5556/dex/callback
```

Logging in through the quickstart-sample app, dex then produces two different ID tokens for the two users:

```json
{
  "iss": "http://127.0.0.1:5556/dex",
  "sub": "CiQ4ODJkMzIyMS01MTk2LTRlOGUtYjdiNC1iMjM5YWY4YmE2YzUSFXJhaW5ib3dzLWFuZC11bmljb3Jucw",
  "aud": "example-app",
  "exp": 1637917081,
  "iat": 1637830681,
  "at_hash": "TTWUJeszfeBnKYTYZjl32Q",
  "c_hash": "Mh62yLF0V0DGX-H5Zc-SCw",
  "email": "simon@supermailprovider.com",
  "email_verified": false,
  "name": "Simon Bla",
  "preferred_username": "simon"
}
```

```json
{
  "iss": "http://127.0.0.1:5556/dex",
  "sub": "CiRkMTgxOGFkNi1hNDg3LTRjMWQtOWNlYy1mZTgyODE3NDY5ZDgSFmRhcmtuZXNzLW15LW9sZC1mcmllbmQ",
  "aud": "example-app",
  "exp": 1637917101,
  "iat": 1637830701,
  "at_hash": "wboF-jq2u8CiHr6Fn2s8gA",
  "c_hash": "DnHbK7-ycuEnzDEqVzWb6Q",
  "email": "simon@supermailprovider.com",
  "email_verified": false,
  "name": "Simon Bla",
  "preferred_username": "simon"
}
```

## Conclusions

- dex supports multiple IdPs and ensures that the sub is unique across all of them → no big surprise there, but still good to know
- dex generates the `sub` field by combining the `sub` it receives from the IdP with the configured IdP-ID (see `connectors.[].Id` field) and then base64 encodes it.

For our case this equates to:
```bash
❯ echo "CiRkMTgxOGFkNi1hNDg3LTRjMWQtOWNlYy1mZTgyODE3NDY5ZDgSFmRhcmtuZXNzLW15LW9sZC1mcmllbmQ" | base64 -d

$d1818ad6-a487-4c1d-9cec-fe82817469d8darkness-my-old-frie%
```

which is the ID in keycloak + the ID for the IdP we configured in Dex (see yaml config in Setup section)
![image](https://user-images.githubusercontent.com/20774623/143425529-362a1d5d-187c-4ee7-83d3-8e9ca5d27766.png)
However there seems to be a character-limit on the `sub` field and then dex cuts of the IdP-ID. Notice how the Idp is called "darkness-my-old-frie". As a result we might not have a reliable way to determine from which IdP the token is from. I have opened a discussion at dex to see how we can solve this https://github.com/dexidp/dex/discussions/2339

**Comment by SimonTheLeg** [comment]
Good news! After the discussion dexidp/dex#2339, we discovered a mistake in my setup. The `sub` field is Base64-**URL**-Encoded, which is not being used by `base64 -d` As a result bas64 swallowed the last characters of the ID. Actually dex is packaging the full IdP-ID in there. We can see this by using `RawURLEncoding` in Go:

```go
const sub = "CiRkMTgxOGFkNi1hNDg3LTRjMWQtOWNlYy1mZTgyODE3NDY5ZDgSFmRhcmtuZXNzLW15LW9sZC1mcmllbmQ"

dec, _ := base64.RawURLEncoding.DecodeString(sub)
fmt.Println(string(dec))
```

With this we only have a small challenge regarding extracting the IdP-ID from the `sub` field. Basically the issue is to find where the Identity ends and the IdP-ID begins, as:
* there is no separator-character to separate Identity returned from IdP and IdP-ID
* the length of the Identity can vary from IdP to IdP and there is no way for us to control the length

As a result, I think our best option is to read in the dex config, parse out all IdP-IDs and then try to string match the list against a delivered token. While this is not super nice, I think it should not pose a larger issue.
