### ISSUE TITLE
Test Konnectivity on all supported cloud providers, k8s versions and expose strategies

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#8279]
Make sure that Konnectivity works on all supported cloud providers, k8s versions and expose strategies:
 - `kubectl logs` works
 - `kubectl cp` works
 - metrics are being retrieved from the `metrics-server` and shown in KKP UI

**Comment by mlavacca** [comment]
Cloud providers:
- [ ] Alibaba
- [ ] AWS
- [ ] Azure
- [ ] DigitalOcean
- [ ] GCP
- [ ] Hetzner
- [ ] Kubevirt
- [ ] Equinix
- [ ] Openstack
- [ ] vSphere
