### ISSUE TITLE
ApplicationDefinitions are validated before create/update

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#8368]
**Acceptance Criteria**

- [x] must be implemented according to [Refactor Cluster Defaulting & Validation](https://github.com/kubermatic/kubermatic/pull/8346) criteria
- [x] validate those constraints have valid values (i.e. k8s and kkp versions range are correct)
- [x] only one source must be defined and be valid (i.e. git or helm)
- [x] only one template method must be defined and be valid (currently only helm)
- [x] the version field inside versions[] must be unique. There cannot be the same value twice inside the array
- [x] since the ApplicationDefinitions live inside the master-cluster they should be validated from there as well

**Implementation Hints**
* we think an AdmissionWebhook will be required to do all the validation
* it could be a good idea to place it in the master-controller-manager. We also think it should be a separate controller to do the validation

**Comment by SimonTheLeg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Work-in-Progress---Team-Caffeine-Overflow-6166fa570192a800141b6db9/issues/kubermatic/kubermatic/8368?planning-poker) with ZenHub @dermorz @hdurand0710 @sankalp-r @themue @vgramer

**Comment by hdurand0710** [comment]
Webhook inside kubermatic-master-controller-manager

**Comment by SimonTheLeg** [comment]
general proposal for CR validation
https://github.com/kubermatic/kubermatic/pull/9151/files

**Comment by SimonTheLeg** [comment]
During implementation of the Generic CR validation, I ran into an issue with the yaml library
https://github.com/kubernetes/apimachinery/issues/133

for which I have submitted a fix
https://github.com/kubernetes/kubernetes/pull/108570

Until the fix is merged, I will build a little workaround into it our generic validation

**Comment by SimonTheLeg** [comment]
pr for generic validation: https://github.com/kubermatic/kubermatic/pull/9333

**Comment by SimonTheLeg** [comment]
after re-reading the requirements we noticed that the logic has not been added to the webhook yet ⟹ re-opening the ticket. I will create a PR for adding it to the webhook
