### ISSUE TITLE
Interface for nodes creation

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#84]
Create a clear interface, for nodes creation.

We should try to reuse some of the docker machine stuff.  This will make it later easier to add new provider.
They already have driver for different cloud infrastuctues.
https://github.com/docker/machine/tree/master/drivers
More plugins available here:
https://github.com/docker/machine/blob/master/docs/AVAILABLE_DRIVER_PLUGINS.md

**Comment by scheeles** [comment]
https://github.com/docker/machine/blob/master/libmachine/libmachine.go

Could be the solution for the interface

**Comment by mrIncompetent** [comment]
Duplicate of https://github.com/kubermatic/api/issues/235
