### ISSUE TITLE
KKP 2.18  - etcd restore via UI fails with wrong S3 URL

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#8440]
**User Story**
After a restore of an automatic Snapshot backup get triggered the Restore config fails:
```
k describe etcdrestores.kubermatic.k8s.io 
Name:         rmfbfrjdxq
Namespace:    cluster-86qbznm5dz
Labels:       project-id=4w6pkhpgvj
Annotations:  <none>
API Version:  kubermatic.k8s.io/v1
Kind:         EtcdRestore
Metadata:
  Creation Timestamp:  2021-12-09T16:41:18Z
  Finalizers:
    kubermatic.io/finish-restore
  Generation:  2
    Manager:    seed-controller-manager
    Operation:  Update
    Time:       2021-12-09T16:41:18Z
  Owner References:
    API Version:           kubermatic.k8s.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Cluster
    Name:                  86qbznm5dz
    UID:                   b60cfd72-6af5-4a3b-9c84-971b49746074
  Resource Version:        123607413
  UID:                     f5fef70a-9d33-4c44-b85e-095611c0efea
Spec:
  Backup Download Credentials Secret:  rmfbfrjdxq-backupdownload-v9p52ntlrd
  Backup Name:                         default-backups-2021-12-09t16-13-29
  Cluster:
    API Version:       kubermatic.k8s.io/v1
    Kind:              Cluster
    Name:              86qbznm5dz
    Resource Version:  122996825
    UID:               b60cfd72-6af5-4a3b-9c84-971b49746074
  Name:                rmfbfrjdxq
Status:
  Phase:  
Events:
  Type     Reason            Age                   From                                Message
  ----     ------            ----                  ----                                -------
  Warning  ReconcilingError  7m25s (x18 over 18m)  kubermatic_etcd_restore_controller  failed to obtain S3 client: error creating s3 client: address https://minio.minio.svc.cluster.local:9000: too many colons in address
```

Environment: Multi Seed Environment with KKP `2.18.2`

![image](https://user-images.githubusercontent.com/4659261/145444483-2dc56ef8-991e-4c27-98cc-6bcc3beb1ee6.png)

Potential related, if so please back-port to fix:
Issue: #8303 
PR: #8307 #8316 
**Acceptance criteria**

**Comment by embik** [comment]
I believe this happens because the s3 endpoint in the respective `Seed` object is set to `https://minio.minio.svc.cluster.local:9000`, however the `https://` scheme prefix shouldn't be there. As reference, there's a e2e test scenario that tests restores from a minio-hosted backup, and it's giving the URL without a prefix: https://github.com/kubermatic/kubermatic/blob/7f22aeffdacb4eb0d4d9439e7fdbc774217c8654/hack/ci/testdata/seed_backup.yaml#L34.

The docs don't point this out specifically, but at least indicate it via the documented defaulting value (https://docs.kubermatic.com/kubermatic/v2.18/cheat_sheets/etcd/backup-and-restore/#enabling-the-new-controllers) `s3.amazonaws.com`. Perhaps some clarity there is needed.

**Comment by toschneck** [comment]
ok will give it a try, thanks!

**Comment by csengerszabo** [comment]
@toschneck do you have an update on this?

**Comment by akash-gautam** [comment]
I tried the fix suggested by @embik, and after that, we see a new issue that, etcdrestore controller is unable to fetch the backup that needs to be used for performing the restore. The credentials to get the backup comes from a secret that is created by the controller itself but the base64 encoding of the secrets seems to have a newline char appended to them which makes the creds invalid and the controller is unable to fetch the backups. `net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=XXXXXXXX\n/20220404/us-east-1/s3/aws4_request`

**Comment by embik** [comment]
@akash-gautam can you specify which secret you're referring to? afaik it uses the `kube-system/s3-credentials` secret (as per https://docs.kubermatic.com/kubermatic/v2.18/cheat_sheets/etcd/backup-and-restore/#s3-credentials-and-settings) and that's not created by the controller.

**Comment by embik** [comment]
Ah, the controller does create a dedicated `Secret`, but it's copied from `kube-system/backup-s3`:

https://github.com/kubermatic/kubermatic/blob/6bfcf2d84f0a5cc2831096da0961ab386ff8ff87/pkg/resources/resources.go#L1266-L1275

I'd recommend checking the source secret (that had to be created by someone manually I think) @akash-gautam, I suspect that it was created via `echo "secret" | base64` when it should have been `echo -n "secret" | base64`.

**Comment by akash-gautam** [comment]
Thanks @embik I was actually comparing `kube-system/s3-credentials` with the one created by the controller and observed that are different so thought maybe the controller is introducing the error while creating the secret but if  `kube-system/backup-s3` is the source for the controller then I can see that the secret created by the controller has the same value as `kube-system/backup-s3` secret. After updating `kube-system/backup-s3` the restore seems to be working.

**Comment by embik** [comment]
Yeah, the documentation still mentioned `kube-system/s3-credentials`, but that is no longer used in KKP 2.18 and above and was replaced with `kube-system/backup-s3`. I updated the docs (https://github.com/kubermatic/docs/pull/1032) to avoid further confusion around this.

**Comment by embik** [comment]
Since I believe this issue was resolved, I'll go ahead and close it to be ahead of the bot closing it in 30 days anyway. Please reopen if there's still an issue with this.
