### ISSUE TITLE
Don't fail if default VPC isn't available

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#848]
@mrIncompetent said that we can handle not having a default VPC in another more graceful way, so we don't increase our `kubermatic_cluster_controller_unhandled_errors_total` counter.

```
I0322 09:22:43.912329       1 controller.go:364] syncing cluster bsbf2hfp72
I0322 09:22:43.947780       1 controller.go:442] Error syncing cluster bsbf2hfp72: failed to get default vpc: unable not find default vpc
```

**Comment by mrIncompetent** [comment]
We should probably tackle this issue a bit further up the road.

The kubermatic API should do better validation. 
When no VPN & Subnet are getting specified by the user && If no default vpc & subnet exist in the account, it should not be possible to create a cluster.

**Comment by p0lyn0mial** [comment]
So, I think we have at least two options of solving this.

The first one being to provide a quick solution, but I am afraid that would only fix this specific case. That would require checking if the mentioned conditions are met and returning an appropriate error. I assume we would like to add this to `kubermatic-api server` at cluster creation?

The second one being to provide more holistic solution. I think that cluster creation can fail for many reasons: incorrect credentials, insufficient permissions and an empty pool of ports and that is just to name a few. I think we can distinguish between terminal and transient errors again. For instance when a user provides an incorrect credentials there is nothing we can do other than informing the user (fun fact: at the moment there is no way to change provided credentials:) )

**Comment by mrIncompetent** [comment]
@p0lyn0mial I partially agree.
In general the cluster-controller should handle transient and terminal errors - as it should work without the `kubermatic-api` it would be the only sane solution to introduce transient&terminal errors.

Though in combination of the `kubermatic-cluster-controller` & `kuberamatic-api` - the `kuberamatic-api` should not create a cluster resource which leads into a terminal error.

**Comment by p0lyn0mial** [comment]
I think we don't need the `bsbf2hfp72` cluster anymore. I could remove it ? If so what's the best way of doing this ?

**Comment by mrIncompetent** [comment]
Yes, please delete it.
As this cluster was broken and never reached a useable state deleting seems fine
After this timespan we should not bother writing that person an email.

**Comment by mrIncompetent** [comment]
On how to delete:
`kubectl delete cluster xxxxxxx`
Afterwards check if the controller correctly cleans it up

**Comment by p0lyn0mial** [comment]
thanks, I have also noticed that the `8mxf9zb5h` cluster has some issues. The `controller` keeps displaying the following error message = `Error syncing cluster 8mxf9zb5h: failed to delete security group kubermatic-8mxf9zb5h: AWS was not able to validate the provided access credentials`

The cluster itself is `116d` old and has its status set to `failed to validate cloud spec: cloud provider data could not be validated successfully: failed to list vpc's: AuthFailure: AWS was not able to validate the provided access credentials status code: 401, request id:`

**Comment by mrIncompetent** [comment]
Regarding `8mxf9zb5h`
It seems that the owner of that cluster made his credentials invalid (probably deleted them in aws).
For this i would delete the `kubermatic.io/cleanup-cloud-provider` & `kubermatic.io/delete-nodes` finalizers on the cluster object
