### ISSUE TITLE
Research how to integrate KubeVirt with MLA

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#8497]
Research how to integrate KubeVirt with MLA (that includes to find out what KubeVirt sends exactly). 
KubeVirt already supports Prometheus https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator.

While working on the issue consider a differnet level access for metrics, those are:
* tenant access
* global access

Acceptance criteria:
* Document that describes a way how to integrate KubeVirt metrics with MLA
* Added implementation issues to the epic

**Comment by sankalp-r** [comment]
We discussed and came to the conclusion that we will not integrate KubeVirt monitoring with KKP MLA.
To keep things simple, we suggest keeping monitoring for KubeVirt components separate.

As KubeVirt provides necessary metrics/configs for monitoring, we only have to install monitoring components(Prometheus, Grafana etc) on KubeVirt infra cluster.
Steps to enable monitoring and importing the dashboard are mentioned in KKP docs(KubeVirt).
