### ISSUE TITLE
Replace custom vpn with existing open-source vpn solution

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#851]
# Current state
Currently we use a custom written VPN solution. The VPN server component runs inside the user cluster as pod (with `hostNetwork: true`). The vpn client runs as sidecar container next to the kubernetes apiserver within our infrastructure (kubermatic -> cluster-xxxxx namespace). The client connects to the server as soon as its available via port `2222`.
This solution has a few downsides, like:
- We have to manage it
- We cannot guarantee security (we are no VPN experts)
- It requires a port on a worker node to be opened to the public

# Desired state
The custom solution should get replaced by an existing open source VPN.
Also must change the way we create the connection from the master to the worker nodes.
A better solution would be if the VPN server would run on our infrastructure. Within the user cluster, there would then only be a client which connects to the server. Though the client needs to expose his available networks to the server. That way we dont have to expose a port like `2222`.

### All master components have access to the pod network
Currently only the apiserver of a user cluster has access to the pod network. (as we only have the sidecar in the apiserver deployment at the moment). We would need to expand this to all master components (apiserver, scheduler, controller-manager). We need to figure out what component is the `vpn-server` role and is accessable from the outside.

### Do not allow connections from the user cluster - via the VPN connection - into the pod network of the seed-cluster.
This is something we either need to solve with the tools, the VPN solution offers, or we need to manage some iptables rules.

@mrIncompetent started working on a simple 1-to-1 replacement of the current solution with openvpn. Code can be found in https://github.com/kubermatic/pod-network-bridge/pull/7.

**Comment by alvaroaleman** [comment]
Sounds fine
