### ISSUE TITLE
Allow specifying ImagePullSecrets in all Helm charts

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#8520]
**User Story**
Recently we had to replace all kubeone worker nodes, which led to the issue that several critical pods ended up in imagePullBackoff, because we've ran into Docker Hub's rate limit (100 pulls / 6h for anonymous users).

We'd like to avoid this in future, particularly since this could fairly easily lead to a several hours long downtime of our KKP service. Thus we thought about either getting a Docker Pro account or mirroring the images on our private registry.

Furthermore, we'd like to theme the Dex image, which would then also come from our private registry.

However, we've noticed that both options are not currently feasible, because most of the Helm charts included in this repo don't allow specifying an ImagePullSecrets. In most cases, we could circumvent that through kustomize if there's no other way, but I don't think that's possible for the charts deployed by the kubermatic-installer.

Currently, the only (limited) workaround is to give each worker node a public IP, so they don't have to use the shared egress IP of their network (this is on OpenStack), but we'd rather not make them accessible from the internet.

**Acceptance criteria**
It must be possible to specify an ImagePullSecrets for every image used in any of the Helm charts included in this repository through the values files.

**Comment by embik** [comment]
It might not cover all Helm charts, but there's an effort to integrate upstream charts where possible: https://github.com/kubermatic/kubermatic/issues/7897. I assume a high percentage of upstream charts have image pull secrets available as option. For the remaining charts, we'll need to fix that separately.

**Comment by judge-red** [comment]
Yes, agreed, although I was kinda hoping for a quicker fix than that, because it looks like #7897 is still quite far off.

**Comment by embik** [comment]
/remove-lifecycle stale

Several of our charts that we ship without referencing an upstream chart still miss this setting.
