### ISSUE TITLE
Cluster provisioning and upgrading on all supported operating systems - Test Release 2.19

### ISSUE THREAD

**Issue by themue** [kubermatic/kubermatic#8579]
This issue assumes following all the steps from #7656, but this time choose a single provider (for example AWS) and test all supported operating systems.

**Acceptance criteria:**

- All manual tests are passing
- All Kubernetes conformance tests are passing

**Supported operating systems:**

- (depending on the provider)

Part of #8578

**Comment by imharshita** [comment]
AWS's machine Deployment with SLES OS is taking to much time to provision

**Comment by imharshita** [comment]
Creation testing:
- [ ] AWS 
-  Ubuntu
- SLES: doesn't support contaierd  https://github.com/kubermatic/dashboard/issues/4072
- CentOS
- RedHat


- [ ] GCP
- Ubuntu 
- RHEL: doesn't support rhel, issue created https://github.com/kubermatic/dashboard/issues/4075

- [ ] Equinix
- CentOS
- Ubuntu

- [ ] Openstack
- Ubuntu
- CentOS

- [ ] VMware 
- CentOS
- Ubuntu

**Comment by imharshita** [comment]
/close tested the compatibility of all supported providers with provided OS, including provisioning and upgrading.
vcenter is DOWN, so not tested.
