### ISSUE TITLE
AWS Provider reconciling - Test Release 2.19

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#8584]
The AWS Provider can now reconcile and fix itself ( https://github.com/kubermatic/kubermatic/pull/8101 ). This should be tested.

* Create a usercluster on AWS.
* Wait for it to be healthy.
* Remove for example the security group on AWS.
* (optional) Remove the status.lastproviderreconciling timestamp to trigger a reconciling
* Check that the security group has been recreated. If not, check the KKP seed-controller-manager logs and look for reconciling errors.
* Edit the Cluster object and remove something like the security group ID.
* (optional) Remove the status.lastproviderreconciling timestamp to trigger a reconciling
* Check that KKP has restored the security group ID in the Cluster object.

NB: Changing the VPC ID is **not** supported. Do not even try. :D

**Comment by lsviben** [comment]
Works as expected by the test case.
