### ISSUE TITLE
Operating System Management AWS - Test Release 2.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8585]
Supported operating systems:
- [x] Ubuntu
- [x] CentOS
- [x] Flatcar
- [x] Amazon Linux

Supported kubernetes versions:
- [x] v1.20.13
- [x] v1.20.14
- [x] v1.21.8
- [x] v1.22.5

Supported container runtimes:
- [x] docker
- [x] containerd

Please go through this issue for testing guidelines:
https://github.com/kubermatic/kubermatic/issues/8582

**Comment by kron4eg** [comment]
:heavy_check_mark: all tests passed
