### ISSUE TITLE
Check controller logs regularly - Test Release 2.19

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#8589]
This is not a binary "works - doesn't work" issue, but more of a reminder. During the testing phase we should regularly (daily at least) check the logs of all KKP components, just in case there are weird things happening, like

* reconcile loops
* repeated warnings
* unexpected invisible bugs

Note that KKP is very ... brutal in the way it logs errors. Even temporary reconciling errors ("object cannot be changed because it was changed by someone else in the meantime") are logged, but harmless. So not every error from the logs is an actual bug.

**Comment by ahmedwaleedmalik** [comment]
Closing this since it's not relevant anymore.
