### ISSUE TITLE
Upgrade External Clusters GKE - Test Release 2.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8595]

**Comment by imharshita** [comment]
GKE clusters with node pool named `preemtible-big`  always shows the status as `provisioning` with wrong number of desired replicas
![gke](https://user-images.githubusercontent.com/78943096/148465590-2e376792-54b9-4470-a028-d5d79fb17319.png)

**Comment by imharshita** [comment]
GKE cluster version upgraded from the Google Cloud Platform leads to error in KKP
`failed to list clusters: Get "https://35.200.248.40/apis/kubermatic.k8s.io/v1/clusters?labelSelector=project-id%3Dhcv9slxnml": dial tcp 35.200.248.40:443: connect: connection refused`

**Comment by imharshita** [comment]
Trying to get version leads to error while upgrading Cluster Master Version, we can replace this logic of checking if the kubeconfig is accessible by making an api request to get a value which is not getting updated/changed https://github.com/kubermatic/kubermatic/blob/master/pkg/handler/v2/external_cluster/external_cluster.go#L921
