### ISSUE TITLE
External Clusters Import AKS - Test Release 2.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8598]

**Comment by imharshita** [comment]
- Create a azure kubernetes cluster
- import the cluster in kkp using either preset or 
 manually providing credentials ( in case of invalid
  credentials it should throw an error)
- select a cluster from the list to import, can not import an already imported cluster

**Comment by lsviben** [comment]
Import is working fine based on my tests.
