### ISSUE TITLE
External Clusters Import EKS - Test Release 2.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8600]

**Comment by lsviben** [comment]
@imharshita 
Added an issue for clearing up the importing clusters issue: https://github.com/kubermatic/kubermatic/issues/8706


Also some UI/general feedback: cc: @maciaszczykm @floreks 
- small icons for choosing eks, aks, gce when importing, i can barely see them, or what is written
- when cluster is disconnected/removed, its not removed from the list, we need to refresh
- no info when something is not working after cluster is imported, its just red
- on project screen, even though we have some external clusters, they are not counted to the cluster count.
Maybe we should add a second column, or show smt like clusters/external clusters 3/6
- Kubernetes version in cluster view is cut `v1.19.13-eks-8df...`, plus there is no suggestion on version upgrade.
