### ISSUE TITLE
Test how many jobs can be run simultaneously - Test Release 2.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8602]

**Comment by xrstf** [comment]
?

**Comment by shaase-ctrl** [comment]
Sorry, my bad.

Do we have any implications that the backup or restore process has limitations that we need to be aware of?

**Comment by lsviben** [comment]
I dont think this task is needed. We dont expect users to restore a large amount of clusters at the same time so i think will close this @shaase-ctrl. Reopen if you think something needs to be tested here.

The restore happens per user cluster, and multiple restores on a particular user cluster cant happen at the same time (this is controlled by an annotation). Thats the only limitation.
