### ISSUE TITLE
Test multiple backup targets - Test Release 2.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8603]
Test procedure, but feel free to play with the feature:

- in admin panel, under Backup Destinations, create some backup destinations for your seed, check docs if needed.
- the backup destinations should be real if you plan to use them, with working credentials. For example you can use local minio if its deployed, or create a test bucket on S3
- create a cluster
- create a backup for the cluster, using a provided destination, check if its working (backups are created)
- start a backup restore, check if it succeeds

**Comment by mlavacca** [comment]
Once https://github.com/kubermatic/dashboard/pull/4124 has been fixed, Everything worked as expected.
/close
