### ISSUE TITLE
Configure multiple seeds and backup targets thereof - Test Release 2.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8604]
Test procedure, but feel free to play with it: 

- similar to https://github.com/kubermatic/kubermatic/issues/8603, but with multiple seeds
- the goal is to check that it works with multiple seeds, and that a destination for cluster etcd backups are available based on which seed the cluster is in

**Comment by lsviben** [comment]
Tested on dev as the QA has only one seed. Works as expected, getting only destination options based on which seed the cluster is a part of.
