### ISSUE TITLE
Restore from multiple backup targets in parallel - Test Release 2.19

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8605]

**Comment by lsviben** [comment]
There can only be one backup running on a specific user cluster. So this test would test running restores on different clusters. The only touching point betwneed these restores is the `seed-controller-manager` which reconciles the EtcdRestore and handles the ETCD backup for each user cluster. 

IMO this is low-priority as these jobs should not have any effect on each other.
