### ISSUE TITLE
Upgrade KKP with etcd-launcher enabled - Test Release 2.19

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#8610]
`etcd-launcher` (https://docs.kubermatic.com/kubermatic/v2.18/cheat_sheets/etcd/etcd-launcher/) is getting some major improvements in KKP 2.19, including encrypted peer traffic. Since it is doing a live upgrade when the seed hosting a `Cluster` with the `etcdLauncher` feature flag is upgraded to KKP 2.19, we should test that this live upgrade is working as intended. I did some testing during development, but it should be verified to be working again, given that etcd is so important.

Suggested process:

- Create user cluster on KKP 2.18.
- Enable `etcdLauncher` feature flag on user `Cluster`.
- Upgrade KKP to 2.19.
- Observe `etcd` Pods of user cluster upgrading itself to peer TLS, making sure the user cluster stays healthy during the upgrade and the `etcd` ring stays stable and online.

The original PR for this was https://github.com/kubermatic/kubermatic/pull/8065.

**Comment by xrstf** [comment]
Is this about upgrading KKP or about upgrading the usercluster? What exactly should one do here?

**Comment by embik** [comment]
Updated description to clarify what should be tested.

**Comment by embik** [comment]
@SimonTheLeg that "rejected connection" should not be a problem. It's annoying, but there is an open ticket here: https://github.com/etcd-io/etcd/issues/10587 (it does not fully match our problem, but I think it's a good pointer towards the likely root cause). I think I've never seen an etcd cluster with peer TLS that doesn't spam this message.

A likely cause seems to be that the peer connections over TLS start out with expecting a different server name, so the client side kills the TLS connection and tries again. That might very well be a problem with the etcd client library we use in `etcd-launcher`, for example.

From my perspective, it's not a problem (that we can solve), given that the connections are established successfully. It's kind of like DNS search domains, where several things are tried until one matches, so you'll see a bunch of `NXDOMAIN` responses in your DNS logs that aren't really issues.

**Comment by SimonTheLeg** [comment]
Ah I see, good to know. 

Well then this test concluded successfully 🎉
