### ISSUE TITLE
AWS AssumeRole - Test Release 2.19

### ISSUE THREAD

**Issue by simon-wessel** [kubermatic/kubermatic#8612]
KKP now supports creating user clusters on AWS with an [assumed IAM role](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html). This can be used to create user clusters in someone elses AWS account for which you do not have regular credentials.

Prerequisites (credentials including ARN for configured IAM role are available in the vault)
- 2 AWS Accounts A and B
- IAM Role on Account B that is allowed to be assumed by A using a [TrustRelationship](https://aws.amazon.com/blogs/security/how-to-use-trust-policies-with-iam-roles/)

How to test this
1. Choose AWS as your provider in the user cluster wizard.
1. Configure your cluster as usual except for step 3 when configuring the credentials. Use the credentials for AWS Account A as your regular credentials and set the checkmark for the AWS Assume Role feature below that. For "AssumeRole ARN" use the ARN of the mentioned IAM Role that should be assumed. If an External ID has been configured during the creation of the IAM role, it will also need to be set in the field below that.
1. Continue to create your cluster.
1. Verify that all resources are being created on AWS account B and that the cluster is fully functional.

There is also documentation available in this [PR](https://github.com/kubermatic/docs/pull/888) that is currently under review. Do not hesitate to contact me if anything is unclear :slightly_smiling_face:

**Comment by simon-wessel** [comment]
Here is the epic for the implementation: https://github.com/kubermatic/kubermatic/issues/6921

**Comment by wurbanski** [comment]
Cluster creation: ✅ 
There's a bug in UI, which is being taken care of now, I'll retest after it's finished.

**Comment by wurbanski** [comment]
UI is fixed as well and working. :)
