### ISSUE TITLE
Extended Health Status - Test Release 2.19

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8635]

**Comment by hdurand0710** [comment]
- MLA Alertmanager Health Status #8096

- Add MLA Health status in the API /health endpoint:- . extendedHealth. monitoring- . extendedHealth. logging (#8082)

- MLA health status for KKP UI #7027

**Comment by hdurand0710** [comment]
**Steps to follow to test MLA Health Status**

- Create a cluster on any provider, do not check 
  - User Cluster Logging
  - User Cluster Monitoring

![Screenshot 2022-01-11 at 18.19.26.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/ae4cd9f5-f188-45c0-aee6-c38243656942)

In KKP UI, you should have no status for 
    - User Cluster Logging
    - User Cluster Monitoring
    - MLA Gateway
    - AlertManager

- Edit your cluster and activate User Cluster Logging/Monitoring
You should now have the correct status corresponding 
![Screenshot 2022-01-11 at 18.25.17.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/f6c118cc-33bd-4603-a815-2e3af89f0201)

- Check that the Health Status for MLA Gateway, Monitoring, Logging are correct. 
```
   - For Monitoring, in the user cluster, ns mla-system 

k get deploy
NAME         READY   UP-TO-DATE   AVAILABLE   AGE
prometheus   2/2     2            2           77m

     - For Logging, in the user cluster, ns mla-system,
 k get ds
NAME       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
promtail   1         1         1       1            1           <none>          72m

    - For MLA Gateway, in the seed cluster, ns <cluster-xxx>

k get deploy
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
mla-gateway                  1/1     1            1           80m
```

**Comment by hdurand0710** [comment]
Tested ok on a cluster created on AWS. 

**After activation of Logging and Monitoring**
![Screenshot 2022-01-11 at 21.58.02.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/1455ba58-920c-4ea6-acd7-e8cc3982c215)

**After deactivation of Monitoring**
![Screenshot 2022-01-11 at 22.00.50.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/25daebab-b24a-4ad5-949b-a574e25f46fc)


**Issue 1 found after setting Logging in error**
```
Update the ds promtail is the user cluster with an invalid value, like config file
 spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml2
```

```
% k get ds
NAME       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
promtail   1         1         0       1            0           <none>          3h57m

```
-> Status for Logging should be red, but it remains green.

![Screenshot 2022-01-11 at 22.21.53.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/6dbe08df-fd81-4688-bec0-11839c820eab)
And status in `cluster CR` is also wrong -> issue in the back-end.

 
**Issue 2 found: alertmanager CR status is not set**
```% k get alertmanager alertmanager -o yaml
apiVersion: kubermatic.k8s.io/v1
kind: Alertmanager
metadata:
  creationTimestamp: "2022-01-11T17:22:23Z"
  generation: 1
  name: alertmanager
  namespace: cluster-cxhw6czvlz
  resourceVersion: "3155563"
  uid: a4adbd05-6fc4-43e3-98d0-f1a8efc9b5cc
spec:
  configSecret:
    name: alertmanager
```

```status``` is missing.
It's due to the fact that the Alermanager CRD is missing the status part: 
https://github.com/kubermatic/kubermatic/blob/master/charts/kubermatic-operator/crd/crd-alertmanagers.yaml
should contain the ```status``` fields as in the k8c one:
https://github.com/kubermatic/kubermatic/blob/master/charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml

**Comment by hdurand0710** [comment]
KKP version : v2.19.0-alpha.4

Test for `Down` Status for Monitoring.

Steps:
- Cluster is healthy with Monitoring enabled.
- In user cluster, `mla-system` ns, delete the `prometheus` pods.
Result : 
![Screenshot 2022-01-12 at 08.27.25.png](https://images.zenhubusercontent.com/613f8d176dae552873cbbca8/e8bfeb98-6c24-472d-9ef0-80a4976f247b)

Status is now red.

**Comment by hdurand0710** [comment]
Env : test-env-kkp.ee.lab.kubermatic.io
KKP: v2.19.0-alpha.4 
**Test: OK for Alaertmanager issue (issue 2)**
```
% k get alertmanager alertmanager -n cluster-cxhw6czvlz -o yaml
apiVersion: kubermatic.k8s.io/v1
kind: Alertmanager
metadata:
  creationTimestamp: "2022-01-11T17:22:23Z"
  generation: 40
  name: alertmanager
  namespace: cluster-cxhw6czvlz
  resourceVersion: "4136008"
  uid: a4adbd05-6fc4-43e3-98d0-f1a8efc9b5cc
spec:
  configSecret:
    name: alertmanager
status:
  configStatus:
    lastUpdated: "2022-01-13T06:19:38Z"
    status: "True"
```

**Comment by sankalp-r** [comment]
KKP version : v2.19.0-alpha.6

Test for `Down` status of `Logging` in user cluster

Steps:

- Cluster is healthy with `Logging` enabled.

-  In user-cluster under `mla-system` namespace, add some erroneous configuration into `promtail` daemonset to bring down related pods.

Results in red status(down/failed) for `Logging`:
![Cluster 'hardcore-hawking' in Project 'Helene'.png](https://images.zenhubusercontent.com/6109152f7cd3e478488ece09/481eb6f0-97f3-40b0-8049-c690d8a6a2a3)

After reconciliation `promtail` becomes healthy and `Logging`status gets back to green:
![Cluster 'hardcore-hawking' in Project 'Helene' (1).png](https://images.zenhubusercontent.com/6109152f7cd3e478488ece09/4b701c2c-3e1a-4b27-be45-106d1375a9fa)

**Tested OK for  Logging health status issue-1**
