### ISSUE TITLE
Test cluster provisioning and upgrading on all supported providers  - Test Release 2.19

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8640]

**Comment by hdurand0710** [comment]
This issue assumes:

Create a Kubernetes cluster running **latest-1 (1.21.8) release**
Keep default settings
Wait for cluster to be ready, then download the kubeconfig for it
Ensure that all nodes are ready by running kubectl get nodes
Ensure that basic operations work
Create a Deployment, try exposing it using NodePort Service, make sure you can reach it out
If external CCM is deployed, ensure that:
Node object has proper IP addresses (kubectl get nodes -o wide)
Each node has providerID set (kubectl describe node <node-name> | grep -i providerid)
If supported, create a LoadBalancer Service and make sure it's reachable
If supported, create a PersistentVolume and mount it in a pod
**Upgrade the cluster to the latest Kubernetes release (1.22.5)**, wait for the upgrade to complete.
Upgrade all machine deployments, so they match the controlplane version.
Wait for all Machines to get rolled out
Ensure that all nodes are ready by running kubectl get nodes
Ensure that all resources are created earlier are still functioning
Try recreating some of resources created earlier
Acceptance criteria:

All manual tests are passing
All Kubernetes conformance tests are passing
Supported providers:

AWS
Azure
DigitalOcean
GCP
Hetzner Cloud
OpenStack
Packet (Equinix Metal)
VMware vSphere
KubeVirt

**Comment by csengerszabo** [comment]
Can this be closed? @hdurand0710 if yes, please close, if no, please comment what's missing
