### ISSUE TITLE
Kubevirt - Test Release 2.19

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8643]

**Comment by sankalp-r** [comment]
KKP version: v2.19.0-alpha.8
env: test-env-kkp.ee.lab.kubermatic.io/

- NodePort svc and LB svc worked fine with assigned private IP.
- Upgrade from kubernetes version `1.21.8` to `1.22.5` worked fine.
- Conformance-test using `sonobuoy` passed on `1.21.8`.
- Conformance-test using `sonobuoy` passed on `1.22.5`.
