### ISSUE TITLE
Test cilium with iptables proxy mode - Test Release 2.19

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#8657]
Create a user-cluster on top cloud providers with iptable proxy mode for every os and check:
- [x] pod are running
- [x]  pods are accessible through pod ip
- [x]  pods are accessible through service
- [x]  install `Hubble` addon for CNI network observability and check it working

Document cloud-provider / OS compatibility matrix.

**Testing results**

Supported cloud providers:
- [x] AWS
    - [x] Ubuntu
    - [ ] CentOS
    - [x] Flatcar
    - [ ] SLES
    - [x] RHEL
- [x] Azure
    - [x] Ubuntu
    - [ ] CentOS
    - [x] Flatcar
    - [ ] RHEL
- [x] Digitalocean
    - [x] Ubuntu
    - [ ] CentOS
- [x] GCE
    - [x] Ubuntu
- [x] Hetzner
    - [x] Ubuntu
    - [ ] CentOS
- [x] Openstack
    - [x] Ubuntu
    - [ ] CentOS
    - [x] Flatcar
    - [x] RHEL
- [x] Kubevirt
    - [x] Ubuntu
    - [ ] CentOS
    - [x] Flatcar
    - [ ] RHEL
- [x] Equinix Metal
    - [x] Ubuntu
    - [ ] CentOS
- [ ] VSphere

**Testing Notes**

**Comment by wurbanski** [comment]
AWS:
* CentOS - `Ready            False   Thu, 20 Jan 2022 16:53:25 +0100   Thu, 20 Jan 2022 16:42:24 +0100   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized`

**Comment by wurbanski** [comment]
Testing closed, summary table has been PR'd to docs.

Issues referred to in https://github.com/kubermatic/kubermatic/issues/8768
