### ISSUE TITLE
Support for configuring the EventRateLimit admission plugin - Test Release 2.19

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8660]

**Comment by hdurand0710** [comment]
Support for configuring the EventRateLimit admission plugin (#8291)

**Comment by embik** [comment]
Documentation available here: https://docs.kubermatic.com/kubermatic/master/tutorials_howtos/admission_plugins/#eventratelimit-configuration

**Comment by sankalp-r** [comment]
Tested on: KKP version **v2.19.0-alpha.8**

* Tried enabling/disabling EventRateLimit Plugin from UI. Observed that api-server restarts with correct configuration.

* Set a low value of EventRateLimit configuration, and created a 40-50 pods inside a specific namespace in user-cluster.

* Observed reduced number of events for pod creation/deletion using command :
    `kubectl get event -n test --sort-by='.metadata.creationTimestamp'`

Result: **EventRateLimit admission plugin** working as expected.
