### ISSUE TITLE
Add an endpoint to list users and extend the user object to allow checking the last seen date - Test Release 2.19

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8663]

**Comment by hdurand0710** [comment]
- Add an endpoint to list users and extend the user object to allow checking the last seen date (#7989)

**Comment by simon-wessel** [comment]
The endpoint can be fetched by authenticated admins and `lastSeen` status is being updated correctly.
`isAdmin` will only show up in the user object if its value is `true`, but that does not seem to qualify as an issue.
