### ISSUE TITLE
User clusters now expose spec.auditLogging.policyPreset, which can be set to metadata, minimal or recommended to configure audit logging policy - Test Release 2.19

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8666]

**Comment by hdurand0710** [comment]
- User clusters now expose spec.auditLogging.policyPreset, which can be set to metadata, minimal or recommended to configure audit logging policy (#8161)

**Comment by rastislavs** [comment]
Tested by switching between all audit policies and verifying that `audit-config` configmap is updated accordingly + checking the audit logs.
