### ISSUE TITLE
Proper use of field userCluster.overwriteRegistry in the KubermaticConfiguration - Test Release 2.19

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#8668]

**Comment by hdurand0710** [comment]
The field userCluster.overwriteRegistry in the KubermaticConfiguration is now properly respectedby all provided addons and by more user cluster controllers: core-dns, envoy-agent, gatekeeper,konnectivity, kubernetes-dashboard, mla-prometheus, mla-promtail, node-local-dns (#8055)

**Comment by rastislavs** [comment]
Tested & verified that overwriteRegistry values is succefully propagated to all addons & user-cluster components, namely:

- gatekeeper-audit
- gatekeeper-controller
- calico-kube-controllers
- canal
- coredns
- kube-proxy
- node-local-dns
- openvpn-client
- user-ssh-keys-agent
- dashboard-metrics-scraper
- konnectivity-agent
