### ISSUE TITLE
Finish / Improve the Machine Controller Dashboard

### ISSUE THREAD

**Issue by metalmatze** [kubermatic/kubermatic#868]
- [ ] Gauge machines without associated nodes

_DO NOT DO:_
- [ ] Remove the error rates graph?
--> since nobody has a clue WHY we would remove it, an common sense says: "Hey, actually thats nice data" we wont get rid of it.

- [ ] Figure out how to display `ControllerOperation` and `NodeJoinDuration` in graphs?
--> deprecated

**Comment by pkavajin** [comment]
@pkavajin talk to henrik about - [ ] Remove the error rates graph?

**Comment by pkavajin** [comment]
DO NOT DO cuz obsolete: Figure out how to display ControllerOperation and NodeJoinDuration in graphs?

**Comment by xrstf** [comment]
All information that is available as metrics is displayed. Anything else needs to be added to the machine controller first before we can talk about visualizing it.
