### ISSUE TITLE
Test canal upgrade after KKP upgrade - Test Release 2.19

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#8680]
Test CNI upgrade works for user clusters started before upgrading KKP version to 2.18:

- create a cluster with Canal CNI version 3.8 (default) in KPP < 2.18
- upgrade kkp to last version (2.19)
- check that canal version running in the user cluster is still 3.8
- check that CNI version can be upgraded from KKP UI to a newer version (note: a cluster reconciliation may be needed before upgrade will become available, e.g. adding a label may trigger it)
- upgrade to a newer canal version
- check that new version of canal is deployed in the user cluster and is running fine

**Comment by dermorz** [comment]
- [x] create a cluster with Canal CNI version 3.8 (default) in KPP < 2.18
- [x] upgrade kkp to last version (2.19)
- [x] check that canal version running in the user cluster is still 3.8
- [x] check that CNI version can be upgraded from KKP UI to a newer version (note: a cluster reconciliation may be needed before upgrade will become available, e.g. adding a label may trigger it)
- [ ] upgrade to a newer canal version
  - [ ] explicit: upgrade CNI plugin version in the UI
  - [ ] implicit: upgrade K8s Control Plane Version in the UI
- [ ] check that new version of canal is deployed in the user cluster and is running fine
