### ISSUE TITLE
KKP 2.18+ NetworkPolicy prevents user-cluster to provision properly

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#8682]
### What happened?
Due to network policies, introduced in v2.18 in apiserver pods for user-clusters, etcd-running initContainer does not complete as it cannot resolve the etcd domain name.

This issue happens only in one environment for us. So it could be timing issue as well. But I can say that the fix is still needed to allow DNS calls.

### What should happen?
The apiserver should come up normally and cluster provisioning should work seemlessly

### How to reproduce?
1. tell-tell sign: apiserver pods in user-cluster namespace remain pending with etcd-running initContainer spewing out errors like below:
```
{"level":"warn","ts":"2022-01-11T10:43:32.864Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-39ea6999-fe2f-4041-8b1a-10c31928a243/etcd-0.etcd.cluster-hrrspd65k8.svc.cluster.local.:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
waiting for etcd
{"level":"warn","ts":"2022-01-11T10:43:39.874Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-46b99a94-07f4-4157-b01b-3a3af5e679f8/etcd-0.etcd.cluster-hrrspd65k8.svc.cluster.local.:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
waiting for etcd
```
2. Above log lines do not prove that this is a DNS issue.
3. Now lets add a netshoot debug pod and run
```
bash-5.1# dig etcd

; <<>> DiG 9.16.22 <<>> etcd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 25337
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 4b506ba176c2d27d0100000061dd5feb4c15447fe214b316 (good)
;; QUESTION SECTION:
;etcd.                          IN      A

;; AUTHORITY SECTION:
.                       30      IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2022011002 1800 900 604800 86400

;; Query time: 35 msec
;; SERVER: 169.254.20.10#53(169.254.20.10)
;; WHEN: Tue Jan 11 10:46:03 UTC 2022
;; MSG SIZE  rcvd: 136
```
4. Now lets add a label to netshoot pod so that it gets covered by `default-deny-all-egress` NetworkPolicy.
```
# in a separate command prompt
$ k label pod tmp-shell app=apiserver
pod/tmp-shell labeled
```
5. Now if we re-issue dig command inside the labeled netshoot pod
```
bash-5.1# dig etcd

; <<>> DiG 9.16.22 <<>> etcd
;; global options: +cmd
;; connection timed out; no servers could be reached
``` 

Thus - proves that apiserver pods are actually not able to reach DNS servers configured on port 53.
Another option is to add NetworkPolicy allowing port 53

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns-port-egress
spec:
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
    - protocol: UDP
      port: 53
```
After applying above network policy, etcd-running initContainer immediately prints OK and exits
```
{"level":"warn","ts":"2022-01-11T10:52:47.065Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-ad16eb6c-2feb-410c-9a59-628d07232279/etcd-0.etcd.cluster-hrrspd65k8.svc.cluster.local.:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
waiting for etcd
OK
```

### Environment

- KKP Version: 2.18.4
- Shared or separate master/seed clusters?: Separate
- Master/seed cluster provider: vsphere seed

**Comment by rastislavs** [comment]
The assumptions in this ticket are wrong:

 - the apiserver pod uses custom dnsConfig, e.g. `kubectl get pod apiserver-xyz -n cluster-xyz -oyaml`
```
  dnsConfig:
    nameservers:
    - 10.47.246.253
    options:
    - name: ndots
      value: "5"
    searches:
    - kube-system.svc.cluster.local
    - svc.cluster.local
    - cluster.local
  dnsPolicy: None
```

This dnsConfig makes sure that the apiserver uses the dns-resolver running in the user cluster namespace, e.g.:
```
k get svc dns-resolver -n cluster-xyz
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
dns-resolver   ClusterIP   10.47.246.253   <none>        53/UDP    40m
```

The connectivity to the dns-resolver pod is allowed by the `dns-allow` policy, e.g.: 
``` describe networkpolicy dns-allow -n cluster-xyz
Name:         dns-allow
Namespace:    cluster-xyz
Labels:       <none>
Annotations:  <none>
Spec:
  PodSelector:     app=apiserver
  Not affecting ingress traffic
  Allowing egress traffic:
    To Port: <any> (traffic allowed to all ports)
    To:
      PodSelector: app=dns-resolver,cluster=xyz
  Policy Types: Egress
```

Therefore the example with the netshoot pod does not prove anything.

**Comment by dharapvj** [comment]
Thank you for bringing this to my attention. While I understand above issue, I can demonstrate this reliably in this specific kkp installation, if I add above example NetworkPolicy, etcd-running initContainer completes immediately - which otherwise remains stuck forever.
