### ISSUE TITLE
Test switching from OpenVPN to Konnectivity - Test Release 2.19

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#8686]
- create a new user cluster with Konnectivity disabled
- switch cluster to use Konnectivity
- validate that everything works fine after control plane components are redeployed (`kubectl logs` works, `kubectl cp` works, metrics are being retrieved from the metrics-server and shown in KKP UI)

**Comment by dermorz** [comment]
There is currently an issue with Konnectivity when network policies are enabled on the API server: https://github.com/kubermatic/kubermatic/issues/8718

@rastislavs is working on a fix, but until then Konnectivity remains disabled on the test env and this issue here is on hold for now.

**Comment by dermorz** [comment]
* [x] Disabled feature gate on KKP
* [x] Enabled feature gate on KKP
* [x] OpenVPN ➡️ Konnectivity
    * [x] `kubectl logs` works
    * [x] `kubectl cp` works
    * [x] Metrics in KKP UI
* [x] Konnectivity ➡️ OpenVPN 
    * [x] `kubectl logs` works
    * [x] `kubectl cp` works
    * [x] Metrics in KKP UI
