### ISSUE TITLE
metering  test disable -Test Release 2.219

### ISSUE THREAD

**Issue by vgramer** [kubermatic/kubermatic#8695]
though the dashboard disable metering:

**Acceptance criteria:**

- seed resource is updated with metering disable
- metering resources are removed in `kubermatic` namespace
  - deployment `kubermatic-metering`
  - cronJob `kubermatic-metering-report-weekly`

**Comment by xrstf** [comment]
I checked this and it works as expected. Enabling and disabling the metering feature from the dashboard correctly removes/recreates the Deployment/CronJob.
