### ISSUE TITLE
Wrong ClusterID in vSphere cloud config

### ISSUE THREAD

**Issue by heilerich** [kubermatic/kubermatic#8705]
**Problem**
Container Volumes created by the CSI are marked with the wrong cluster name in vSphere. This works, but makes it very difficult to tell which of the volumes, that show up in vSphere, belong to which user cluster.

**Cause**
The ClusterID field in the cloud config for vSphere is currently populated with the value from the cluster field in the datacenter configuration

https://github.com/kubermatic/kubermatic/blob/03641d064f518bbf26622d531d2bcca1e3bdbba2/pkg/resources/cloudconfig/configmap.go#L312

For the latter the [documentation](https://docs.kubermatic.com/kubermatic/v2.18/tutorials_howtos/project_and_cluster_management/seed_cluster/) states that it should (a) contain the name of the vSphere compute cluster (which is completely unrelated to the CSI) and (b) is currently unused.

The ClusterID value in the cloud config is used by vSphere CSI to set the metadata of the created container volumes. This causes the above mentioned problem.

**Solution**
The line linked above should be 

```go
ClusterID:        cluster.Name
```

This is the value used in other cloud configs (e.g. AWS).

A quick search of the CCM sources and documentation yielded no usage of the `cluster-id` field in the CCM. The CSI only seems to use the value setting the above mentioned metadata. I think fixing this should cause no problems in existing deployments.

**Comment by dharapvj** [comment]
As mentioned in [this page](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-BFF39F1D-F70A-4360-ABC9-85BDAFBE8864.html), the ClusterID must be unique across each kubernetes cluster.

Due to common clusterID, we are hitting against the issue describe in [this VMWare KB](https://kb.vmware.com/s/article/84446)
