### ISSUE TITLE
Propagated LB service has no connection with user cluster

### ISSUE THREAD

**Issue by michalvanco** [kubermatic/kubermatic#8712]
### What happened?
If you create a user cluster and there setup metal LB + nginx for example, then the service of type LB is created on user cluster -> because it's the KubeVirt setup it means that the LB service will be created on the underlying resource cluster, but unfortunately there is no connection between the service on resource cluster vs the user cluster.

So in case that you have multiple user clusters, there is way to discover which service belongs to which user cluster.

### What should happen?
There should be a clear connection (through annotation or label) on the service on KubeVirt cluster with information about source user cluster and service name from user cluster).

### How to reproduce?
See the steps above.

### Environment
* KKP + KubeVirt setup

- KKP Version: 2.18.2
- Shared or separate master/seed clusters?: shared
- Master/seed cluster provider: static kubeone cluster + KubeVirt cluster using bare-metal

**Comment by hdurand0710** [comment]
@michalvanco , when we will implement #8489 (planned for Q1 2022), the Vm/Vmi, LB service created in the infra cluster, will be created and isolated in dedicated `user-<cluster name>` namespace.
Then in the under Kube (infra) cluster, you will find all objects associated to a given user cluster (VM/Vmi, LB )  in the dedicated namespace `user-<cluster name>`.
That's the proposed way of solving it.
