### ISSUE TITLE
external-ccm-migration causes usercluster-controller to get stuck

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#8715]
### What happened?

After migration of user-cluster to external CCM (vsphere), the user-cluster-controller manager pod get stuck with below error.

```
{"level":"error","time":"2022-01-12T16:37:19.139Z","caller":"resources/controller.go:283","msg":"Reconciling failed","error":"failed to reconcile ValidatingWebhookConfigurations: failed to ensure ValidatingWebhookConfiguration /validation.csi.vsphere.vmware.com: failed waiting for the cache to contain our latest changes: timed out waiting for the condition"}
```

But if we check the cluster, it has required webhook config
```
$ k get validatingwebhookconfigurations -A
NAME                                          WEBHOOKS   AGE
validation.csi.vsphere.vmware.com             1          83m
```

user-cluster-controller pod does not pickup new config even after restarting

### What should happen?
CCM migration should successfully complete

### How to reproduce?
Have a user-cluster in vsphere created as part of kkp v2.17. 
Upgrade kkp to v2.18
do a CCM migration via UI

### Environment

- KKP Version: v2.18.4
- Shared or separate master/seed clusters?: separate
- Master/seed cluster provider: vsphere

**Comment by xrstf** [comment]
Is this cluster still running somewhere?
