### ISSUE TITLE
Support Openstack Application Credentials in KKP Presets

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8758]
### What would you like to be added? / User Story

As an kkp-admin, I want to configure presets with Openstack applications credentials so that my users can easily use the presets with applications credentials as well.

### Acceptance criteria
- Application Credentials are configurable in the Admin Interface
- Users can use both types of credentials
- Users can easily differentiate what type of credential set they are going to use
-

**Comment by xrstf** [comment]
This might be more appropriate in the dashboard repo. Should we move the ticket?

**Comment by shaase-ctrl** [comment]
Feel free, I do not know if API is ready.

**Comment by ahmedwaleedmalik** [comment]
Issue moved to [kubermatic/dashboard #4187](https://github.com/kubermatic/dashboard/issues/4187) via [**ZenHub**](https://www.zenhub.com/)
