### ISSUE TITLE
Implement error metric in kubermatic-api

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#877]
We need to expose a metrics stating what errors we ran into.
This should be implemented in a Middleware.

This is the most critical metrics for us.
As soon as this counter is >1 over 10min, we should get alerted.

**Comment by metalmatze** [comment]
https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerCounter

**Comment by mrIncompetent** [comment]
@metalmatze You mentioned during the backlog grooming that we might already have a metrics from nginx for the responses + status-code?

**Comment by mrIncompetent** [comment]
The final goal is that we alert on fatal errors on the kubermatic-api. If a alert on `status-code>=500` is possible via the nginx metrics, we should rather use that.

**Comment by metalmatze** [comment]
All the metrics that the nginx ingress controller exposes are:
```
ingress_controller_ssl_expire_time_seconds{host="alertmanager.dev.kubermatic.io"} -6.21355968e+10
ingress_controller_ssl_expire_time_seconds{host="dev.kubermatic.io"} -6.21355968e+10
ingress_controller_ssl_expire_time_seconds{host="grafana.dev.kubermatic.io"} -6.21355968e+10
ingress_controller_ssl_expire_time_seconds{host="prometheus.dev.kubermatic.io"} -6.21355968e+10
ingress_controller_success{count="reloads"} 84
nginx_connections_total{ingress_class="nginx",namespace="",state="accepted"} 10533
nginx_connections_total{ingress_class="nginx",namespace="",state="active"} 1
nginx_connections_total{ingress_class="nginx",namespace="",state="handled"} 10533
nginx_connnections{ingress_class="nginx",namespace="",state="reading"} 0
nginx_connnections{ingress_class="nginx",namespace="",state="waiting"} 0
nginx_connnections{ingress_class="nginx",namespace="",state="writing"} 1
nginx_requests_total{ingress_class="nginx",namespace=""} 262997
```

So we need to add the middleware handler of the Prometheus client

**Comment by mrIncompetent** [comment]
Agree, a middleware is the way to go!
