### ISSUE TITLE
Changing from application credentials to user credentials in Openstack

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8809]
### What happened?
User tried to enter his user credentials instead of the previously used app credentials and the tenant ID was missing. 

### What should happen?
It should not be possible to switch credential type after cluster creation

### How to reproduce?
setup cluster with app credentials and change to user credentials

### Environment

- KKP Version: 2.17.5 
- Shared or separate master/seed clusters?: combined
- Master/seed cluster provider: openstack

**Comment by embik** [comment]
@csengerszabo this is the opposite of #8048. This ticket says it should not be possible to switch credential types, while #8048 specifically asks for that. Which one should remain open?

**Comment by shaase-ctrl** [comment]
I have not worked on this topic for a long time therefore my thoughts might be incomplete.

Application credentials are derived from user credentials. Changing credentials is needed esp. when there are leaked credentials. Changing the type of credentials has which impact to the system (app or user credentials)?

**Comment by csengerszabo** [comment]
After a brief dive into this topic, I found valuable to keep the possibility to change the credentials, and currently I don't see a reason why it should not be able to be changed.

- So is changing even possible at the moment? As this issue states, it is, at least until some point. Then I guess this issue can be closed.
- Then the question is: what is not possible to do from the acceptance criteria of #8048 currently, and should we even implement them or is it okay as it is now?
- If we change credentials, would they be applied dynamically to the running cluster?

**Comment by embik** [comment]
This is an issue with the UI; if you update credentials manually and include a project ID when switching from application credentials to user credentials, all components get rotated automatically and things work just fine. I tested with deploying a new node, which worked without problems.

One thing that should be documented (but I think it should be shown in the UI flow as well) is that machines need to be manually rotated, as old machines will keep running with the old credentials under `/etc/kubernetes/cloud-config`.

I'll raise a ticket for the dashboard, but from a KKP backend perspective this already works.

**Comment by embik** [comment]
Closing in favour of https://github.com/kubermatic/dashboard/issues/4702, as rotating/changing credentials is possible and just needs proper UI support.
