### ISSUE TITLE
Limits not configurable for customer cluster Nodeport-Proxy-Envoy - Test Release 2.20

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubermatic#8826]
### What happened?
I have at least one cluster where the nodeport-proxy-envoy is using ~70mb of memory,
as we have a hardcoded limit if 64, in get constant OOMs.

### What should happen?
In the same way that we can set this for the seeds, we would need that in the cluster overrides too
### Environment

- KKP Version: 2.18.5
- Shared or separate master/seed clusters?: seperate 
- Master/seed cluster provider: Openstack

**Comment by moadqassem** [comment]
@qeqar Can you please specify, on which cloud provider the user cluster is created?

**Comment by qeqar** [comment]
We are using Openstack
