### ISSUE TITLE
Hetzner machine spec does not consider network defined in cluster spec - Test Release 2.20

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#8868]
### What happened?

As reported on the Kubermatic community slack, when creating a cluster on Hetzner and passing the Hetzner network in the cloud spec and not on the datacenter level, the creation of the (initial) machines fails with:

```
failed to create machine at cloudprovider, due to network "" does not exist
```

### What should happen?

The network passed on the Hetzner cloud provider spec should propagate to the `MachineDeployments` created for the cluster.

### How to reproduce?

- Set up Hetzner datacenter in your `Seed` with `network: ""`
- Create a Hetzner cluster with `network: "your-network-name"`
- Check the `MachineDeployment` for the configured network; expected value should be `your-network-name`, but will be an empty string

### Environment

- KKP Version: 2.19.0
- Shared or separate master/seed clusters?: Shared
- Master/seed cluster provider: -

**Comment by moadqassem** [comment]
@embik Can you please share the MD ?

**Comment by moadqassem** [comment]
Also does it work when you create a new machine deployment(not the initial one) ?

**Comment by embik** [comment]
@moadqassem I don't have a `MachineDeployment` around anymore but it had `networks: [""]` in the spec, if that helps. I can get the full one if needed.

I also didn't try additional machine deployments, but I assume they wouldn't pass validation. That the initial one was even created is likely due to #8837.

**Comment by moadqassem** [comment]
@embik IMHO an addition of new machine would pass the validation.

**Comment by moadqassem** [comment]
Ok I guess I found the issue here.

**Comment by embik** [comment]
I already opened #8872 to fix this :-)
