### ISSUE TITLE
API endpoints for Nutanix category keys and values

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#8927]
### What would you like to be added? / User Story

Nutanix uses a tagging system called categories, which works with a key=value pair to assign a category to resources like VMs. It works differently from normal tags though: Both category key/name and category value need to pre-exist to be assigned to a resource.

We should therefore add autocompletion endpoints to the KKP API that allows the UI to query for category keys and values. It should exclude the KKP categories because they are created and assigned to `MachineDeployments` in any case, and we don't want users to override those values.

### Acceptance criteria

- Expose API endpoint `/v2/providers/nutanix/{dc}/categories` for category keys
- Expose API endpoint `/v2/projects/{project_id}/clusters/{cluster_id}/providers/nutanix/categories` for category keys via cluster credentials
- Expose API endpoint `/v2/providers/nutanix/{dc}/categories/{category}/values` for category values
- Expose API endpoint `/v2/projects/{project_id}/clusters/{cluster_id}/providers/nutanix/categories/{category}/values` for category values via cluster credentials

**Comment by csengerszabo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-Input--Estimation-5fa947bf2732730014ef98c1/issues/kubermatic/kubermatic/8927?planning-poker) with ZenHub @ahmadhamzh @ahmedwaleedmalik @embik @floreks @kron4eg @maciaszczykm @mlavacca @moadqassem @PratikDeoghare @simon-wessel @WeirdMachine @xmudrii @xrstf

**Comment by embik** [comment]
Did I not assign this points already? Apologies for that, this basically done, not sure planning poker makes sense.

**Comment by Waseem826** [comment]
I'm getting `400: Invalid Request` error from `/api/v2/providers/nutanix/{dc}/categories` endpoint. I see that we have another endpoint to list categories `/api/v2/projects/{project_id}/providers/nutanix/{dc}/categories` which works fine so I'm wondering which endpoint should we use?
