### ISSUE TITLE
Cinder CSI Addon is missing required CRD's

### ISSUE THREAD

**Issue by tplueer** [kubermatic/kubermatic#8928]
### What happened?

The csi-snapshot controller which is located inside the cinder csi addon needs three crd's which are currently not installed by default. This results in a large amount of errors which are logged inside the user cluster.

```
E0209 09:09:05.323897       1 reflector.go:156] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
E0209 09:09:06.337292       1 reflector.go:156] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```

### What should happen?

The required crds should be automatically installed by kubermatic.

https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd

### How to reproduce?

Create a cluster with the openstack provider in version 1.22.5

### Environment

- KKP Version: v2.18.4
- Shared or separate master/seed clusters?: Separate
- Master/seed cluster provider: Openstack

**Comment by WeirdMachine** [comment]
Hey @tplueer. Thanks for pointing out. In general we do not support CSI Snapshotting very well. As this is basically an Issue which affects all CSI drivers on all providers, I opened https://github.com/kubermatic/kubermatic/issues/9013 and going to close this.
