### ISSUE TITLE
CRD migration test plan - Test Release 2.20

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#8947]
## KKP 2.20 Test Plan

In 2.20, we ship basically only one big change: the CRD migration to kubermatic.k8c.io. This includes a necessary migration using the KKP installer.

We need to test this migration properly.

### Test Procedure

1. Setup a KKP 2.19 system. A shared master/seed system is sufficient.
1. Create a handful of userclusters.
1. Configure things like OPA, MLA, create AllowedRegistry resources, etc -- basically just make use of as many KKP things as possible
1. Run the migration as documented in https://github.com/kubermatic/docs/pull/930
1. Verify that userclusters still work
1. Verify that settings made in 2.19 are still present in 2.20.
1. Reset entire test system and start from step 1 again.

**Comment by moadqassem** [comment]
Works as expected
