### ISSUE TITLE
On Premise Capacity Monitoring/Management via KKP

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8949]
### What would you like to be added? / User Story
As a KKP Admin, I want to be able to do capacity management within KKP on vSphere and Nutanix properly so that I must not rely on another interface or alert system.

### Acceptance criteria
- Alerting is done within KKP for upcoming capacity issues
- vSphere
- Nutanix
- Openstack

**Comment by wurbanski** [comment]
After discussions, we have decided that this capability is for now outside of scope for KKP, but as this feature would be very useful we will create a set of exporters and rules that can be easily used and add them to https://github.com/kubermatic/community-components
