### ISSUE TITLE
Investigate how to display the connections between regions, seeds, datacenters and user clusters

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#8951]
As a kkp admin, I want to see the relationship between the components visually in the KKP dashboard, so that I have a better understanding of my configuration

Acceptance Criteria
- limitations in current setup
- requirements for future development

**Comment by csengerszabo** [comment]
How about standardizing location and region parameters by ourselves with custom matching rules? Since this consists of finite elements. It would be a one-off work first, and sometimes would need an update as providers may have new locations, or we may have new providers. What do you think?

**Comment by shaase-ctrl** [comment]
We are going with an easy mechanism first:

we display in the admin panel an overview consisting of:

all available seeds
- total amount of clusters per seed
- all available providers per seed
- all available datacenters per seed

This way it is easy to get an overview for admins, what is configured how and where does the workload majortiy resides.

**Comment by cschieder** [comment]
[Design Draft, Admin Panel "Seed Configuration"](https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=6457%3A47599 )
![Admin Settings-Seed1](https://user-images.githubusercontent.com/49145827/162896358-177a9154-e9bc-46a8-b6ab-847fb953f361.png)
![Admin Settings-Seed2](https://user-images.githubusercontent.com/49145827/162896360-62c5bec1-7d9e-4644-8d63-0fc2637d7a40.png)

**Comment by cschieder** [comment]
Closed, Exploration resulted in [Seeds in the UI#9583](https://app.zenhub.com/workspaces/work-in-progress---team-product-606ec73090e027001169c9e7/issues/kubermatic/kubermatic/9583)
