### ISSUE TITLE
Write a slack bot for cat gifs

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#899]
- Posts a random cat gif per day via direct message
- People should be able to subscribe/unsubscribe to the bot
- When writing `gimme more` the bot will send a new cat gif
- When writing `gimme more!` the bot will send 10 cat gifs at once.

**Comment by metalmatze** [comment]
https://github.com/nlopes/slack

**Comment by guusvw** [comment]
like to have a `send kittens to USER` command, to cheer up my colleagues

**Comment by mrIncompetent** [comment]
Maybe there's a chance to include a blockchain as well?!
@guusvw @metalmatze

**Comment by metalmatze** [comment]
How can we make this super disruptive? I mean Blockchain is a good first step, but maybe something like IPFS helps too?

**Comment by cbrgm** [comment]
https://github.com/cbrgm/kitty-slack

Pull requests welcome guys! Commands are working, "Cat of the Day" and "Send to user" feature coming soon.

**Comment by kdomanski** [comment]
How about just enabling giphy integration?

**Comment by mrIncompetent** [comment]
We had the Giphy integration at some point. Somehow it got removed :thinking:

**Comment by guusvw** [comment]
Could be a good topic, if someone on the hackathon running out of energy/brain power ;)

**Comment by mrIncompetent** [comment]
@cbrgm already wrote it. See https://github.com/kubermatic/kubermatic/issues/899#issuecomment-383295162
