### ISSUE TITLE
Implement CSI Snapshotter

### ISSUE THREAD

**Issue by mate4st** [kubermatic/kubermatic#9013]
### What would you like to be added? / User Story
CSI Snapshotter is part of the CSI Spec and CSI driver may require it. See: https://github.com/kubermatic/kubermatic/issues/8928

https://github.com/kubernetes-csi/external-snapshotter

The snapshotter should be independent of the csi driver, which does not always seem to be the case.

It consist of 3 components: 

- Snapshot CRD
- Snapshot Controller
- Validating Webhook

### Acceptance criteria
* Make sure all mentioned components are deployed together with the csi driver
* Note that some csi driver provide some of the components as part of their csi driver

**Comment by WeirdMachine** [comment]
Missing the external-snapshotter and webhook for cinder csi
