### ISSUE TITLE
Tagging capability of machines

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#9024]
**User story:**
As a KKP admin
I'd like to add tags for machines of all the available providers
in order to being able to separate them inside the providers for example from non-Kubermatic machines for reporting and expense organizing reasons.

**Acceptance criteria:**
- As a KKP admin on the UI I am able to add tags when provisioning a new cluster
- As a KKP admin on the CLI I am able to add tags when provisioning a new cluster

**Comment by embik** [comment]
Isn't this already the case? For those cloud providers that support provider tags, the UI has the option to add tags to the initial `MachineDeployment`. In addition, afaik KKP tags resources by default to signal cluster and KKP project relationships.

**Comment by csengerszabo** [comment]
It would be ideal to achieve consistency among all providers with tagging in KKP. Do we need providers to support tagging in order to add tags to the Machines or could we do it somehow without them supporting it?

**Comment by embik** [comment]
`Machines` can already be "tagged" with Kubernetes labels across all providers, if we're talking about tagging on the Kubernetes API level. On the provider APIs level, it might be worth looking into unifying this, but the concept of "tags" will very likely differ between providers enough to cause headaches. For example, Nutanix provides something called "categories" that is very close to key-value tags, but it needs keys and values to be pre-existing before assigning them. But other providers treat them as "any key and value is possible".

The question is where you want those tags to exist. Kubernetes API? Already possible and unified through labels on `Machines`. Tags on the actual Virtual Machine as seen by the provider? Supported where possible, but harder to unify.

**Comment by csengerszabo** [comment]
Okay, I understand the constraints. Then can we have a rough effort estimation on making able to unifying tagging the actual VMs as seen by the providers? Thanks a lot!

**Comment by csengerszabo** [comment]
Summing this up: concept of labeling or tagging VMs can be different at particular providers, that's why unifying them is not trivial. There are some providers where we already support VM tagging with "Provider Tags" function. Next step is analyzing potential customer use cases where they could utilize this feature besides what we already know: billing and expense organizing among their teams.

**Comment by csengerszabo** [comment]
Potential customer use cases:

- Budget calculations: separate budget for separate use cases, separate teams etc. As they may have multiple architectures for multiples use cases on the same provider and on others they may already use tagging, and they cannot use it just with KKP.
- Predictions of workload usage from the categorized and collected data (usage of tagged machines).
- Bill to the various departments the spending of various architectures.
- Ops: marking Kubermatic machines regarding not doing backups for these machines and exclude them from being shutdown at night automatically.

Importance for the client: tagging machines manually for these use case above manually is getting more "impossible", because of the systems's constant autoscaling.

Can we say something about a potential approximate development effort for this like in epic points?
