### ISSUE TITLE
Regression: Machine-controller can't delete machine ressource on AWS

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#903]
If you delete a machine on cloud.kubermatic.io on AWS. The VM instance is delete but the controller can't delete the ressource. 

If you delete the finalizer manually it works correct.

Check my cluster https://cloud.kubermatic.io/clusters/europe-west3-c-1/bn9h58ck2r

All nodes on AWS are gone but the machine-controller still waits.

```
I0416 00:38:23.136837       1 machine.go:405] deletion of instance i-041a3e9fe286152da got triggered. Waiting until it fully disappears
```

**Comment by p0lyn0mial** [comment]
@mrIncompetent in the slack channel you wrote
> The controller wait until the instance on aws is really gone. That takes up to 15min... Though that behavior is not needed anymore as it was implement with a wrong assumption in mind

does it mean we can simply remove the check from the machine-controller ?
or this is `AWS` specific ?

**Comment by mrIncompetent** [comment]
Not quite. The controller needs to handle the case, when the provider returns a `InstanceNotFoundErr` or a instance with the status `InstanceStatusDeleted`.
In both cases the finalizer needs to be removed.

I have some code prepared i only need to test - fairly small change
