### ISSUE TITLE
Support VMware Cloud Director as Cloud Provider

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#9055]
As a user, I want to run workload on vcloud director so that I can leverage these environments as well.

**Comment by csengerszabo** [comment]
@ahmedwaleedmalik there are 2 epics regarding this topic and I see you did things to both of them, can we somehow merge their content together into one epic and close the one that is not needed?

**Comment by ahmedwaleedmalik** [comment]
Hey @csengerszabo are you talking about https://github.com/kubermatic/kubermatic/issues/4772 or https://github.com/kubermatic/kubeone/issues/1987? 

Basically https://github.com/kubermatic/kubeone/issues/1987 is for `kubeone` so I'm not sure if I can somehow link that within this epic.

**Comment by csengerszabo** [comment]
Aah okay and I also did not pay attention that those two are for different repositories. So this is a great day for learning for both of us 😉
