### ISSUE TITLE
Label missmatch between node-port-proxy and frontend-service

### ISSUE THREAD

**Issue by qeqar** [kubermatic/kubermatic#9059]
In KKP 2.19.1 is a update on a app label, but the service still expected the old one, so the servioce had no endpoint.

`kubectl describe svc --namespace cluster-m98wggk2tz front-loadbalancer 
Name:                     front-loadbalancer
Namespace:                cluster-m98wggk2tz
Labels:                   <none>
Annotations:              <none>
Selector:                 app=nodeport-proxy-envoy
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.99.59.94
IPs:                      10.99.59.94
LoadBalancer Ingress:     45.94.111.20
Port:                     cluster-m98wggk2tz-apiserver-external-30642  30642/TCP
TargetPort:               30642/TCP
NodePort:                 cluster-m98wggk2tz-apiserver-external-30642  31790/TCP
Endpoints:                <none>
Port:                     cluster-m98wggk2tz-openvpn-server-31120  31120/TCP
TargetPort:               31120/TCP
NodePort:                 cluster-m98wggk2tz-openvpn-server-31120  31455/TCP
Endpoints:                <none>
Port:                     healthz  8002/TCP
TargetPort:               8002/TCP
NodePort:                 healthz  31529/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age                From                Message
  ----    ------                ----               ----                -------
  Normal  EnsuringLoadBalancer  27m (x2 over 29m)  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   26m (x2 over 28m)  service-controller  Ensured load balancer`

and the nodeport proxy
`Name:         nodeport-proxy-envoy-7d45959c78-nlkts
Namespace:    cluster-m98wggk2tz
Priority:     0
Node:         dev-imke-seed-ix1-7fbf6c7775-k427q/192.168.1.248
Start Time:   Wed, 23 Feb 2022 10:18:32 +0100
Labels:       app=nodeport-proxy
              pod-template-hash=7d45959c78
Annotations:  cni.projectcalico.org/podIP: 10.244.5.80/32
              cni.projectcalico.org/podIPs: 10.244.5.80/32

SNIP.....`

In additon we see reconceiling errors wen updateing to 2.19.1, with exactly this change which is not allowed.

**Comment by qeqar** [comment]
this is the MT that breaks it: https://github.com/kubermatic/kubermatic/pull/9018
in the file [pkg/resources/nodeportproxy/nodeportproxy.go](https://github.com/kubermatic/kubermatic/pull/9018/files#diff-a8c7447895f60d1db0d6a70b86f819b1329b41ffa19a26a71c5c124902f6f535) Line 41

**Comment by embik** [comment]
Hey @qeqar, thanks for raising this, sorry about this ... The issue actually lies a few lines down at https://github.com/kubermatic/kubermatic/pull/9018/files#diff-a8c7447895f60d1db0d6a70b86f819b1329b41ffa19a26a71c5c124902f6f535L247, where the `name` constant was overshadowed by a variable ... Since the constant existed, removing the variable did not raise any compiler issues, but `name` was still used further down the code.
