### ISSUE TITLE
Add validation for GCP, Azure, AWS, DO, Hetzner, Equinixmetal, OpenStack - Test Release 2.20

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#9066]
# Instructions

On existing cluster try to: 
* "edit provider" form
* input incorrect credentials
* watch them being rejected

- [x] AWS
- [x] GCP
- [x] Azure
- [x] DigitalOcean 
- [x] Hetzner
- [x] Equinixmetal
- [x] OpenStack

# References

xref https://github.com/kubermatic/kubermatic/issues/8972
xref https://github.com/kubermatic/kubermatic/pull/9223

**Comment by kron4eg** [comment]
change is not included in release/v2.20

**Comment by ahmedwaleedmalik** [comment]
Reopening this based on our discussion in the daily.
