### ISSUE TITLE
Endpoints to get EKS resources - Test Release 2.20

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#9067]
# Instructions

- Create a cluster on AKS or load existing cluster using `external` preset.
- Import the external cluster using KKP dashboard
- Ensure that it's successfully imported

Test the following endpoints:

- [ ] /api/v2/providers/eks/vpcs
- [ ] /api/v2/providers/eks/subnets
- [ ] /api/v2/providers/eks/securitygroups
- [ ] /api/v2/providers/eks/regions

# References

xref https://github.com/kubermatic/kubermatic/issues/8907

**Comment by kron4eg** [comment]
Change is not included in the release/v2.20
