### ISSUE TITLE
Provider Reconciling for GCP - Test Release 2.20

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#9069]
# Instructions

- Create a cluster on GCP
- Ensure that the cluster is up and healthy
- Either use `gcloud` CLI or the [dashboard](https://cloud.google.com) to perform the following actions
   1. Delete `firewall-{cluster-name}-nodeport` firewall rule.
   2. Wait for 2-3 mins, ensure that it is re-created
- Delete the cluster 
- Ensure ALL firewall rules, routes, etc. are removed and there are no remanent resources.

# References

xref https://github.com/kubermatic/kubermatic/issues/8142

**Comment by kron4eg** [comment]
This change is not included in the release/v2.20

**Comment by moadqassem** [comment]
@kron4eg This one has been already implemented in 2.19 why it is not included? It should be ported to it

**Comment by kron4eg** [comment]
@moadqassem I don't know why, but the https://github.com/kubermatic/kubermatic/pull/8810 PR that closed #8142 is not in the release/v2.20 branch, thus not included.
