### ISSUE TITLE
Fix for panic in installer - Test Release 2.20

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#9070]
# Instructions

- Leverage on [run-kubermatic-in-kind](https://github.com/kubermatic/kubermatic/blob/master/hack/local/run-kubermatic-kind.sh) for KKP installation
- Ensure that chart `name` and `versions` are correctly parsed from the helm release(`helm list`)
- Install another random chart, like minio, using a custom name (i.e. do not name the Helm release "minio", but "minio-is-a-cool-name")
Run the KKP installer; it should not choke on the weird Helm release.

# References

xref https://github.com/kubermatic/kubermatic/pull/8954

**Comment by ahmedwaleedmalik** [comment]
@xrstf I'd like to get your second opinion on the instructions for testing this.

**Comment by xrstf** [comment]
I would add, if you really want to test this:

* Install another random chart, like minio, using a custom name (i.e. do not name the Helm release "minio", but "minio-is-a-cool-name")
* Run the KKP installer; it should not choke on the weird Helm release.
