### ISSUE TITLE
Extend endpoint to create native EKS cluster - Test Release 2.20

### ISSUE THREAD

**Issue by mlavacca** [kubermatic/kubermatic#9074]
Since the UI is not implemented yet, we should verify that this endpoint works as expected with the following command: 
```
POST https://dev.kubermatic.io/api/v2/projects/<your project name>kubernetes/clusters
Accept: application/json

{"name":"test-cluster", "cloud":{"eks":{"name":"test-cluster", "accessKeyID":"xxx", "region": "eu-central-1", "secretAccessKey": "xxx", "clusterSpec":{"version": "1.20", "vpcConfigRequest": {"securityGroupIds": ["sg-026932770ef4d761c"],"subnetIds": ["subnet-01775486559312b19", "subnet-3672ba7a"]}, "roleArn": "xxx"}}}}
```

It should create a new cluster in EKS, which should be running and available for the connection from the UI.
After issuing the above command, connect to the new cluster, and check that is fully functional.

## References
xref #8434

**Comment by kron4eg** [comment]
The change is not included in v2.20
