### ISSUE TITLE
Deploy Monitoring Stack to US and Asia datacenters

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#913]
Our Asia & US seed clusters for cloud.kubermatic.io were broken as 2 CustomResourceDefinition's were missing.

`servicemonitors.monitoring.coreos.com` & `prometheuses.monitoring.coreos.com`
Both have been now manually created.

Todo's within this issue:
- [x] Deploy monitoring stack to non-master seed clusters
- [x] Verify that our existing alerting works within those clusters
- [x] Verify we always deploy those CustomResourceDefinition's

**Comment by xrstf** [comment]
We do not use the CRDs anymore, so point three of that checklist is moot.

**Comment by xrstf** [comment]
As with cloud/eu, I've silenced all alerts with `alertname="KubeSchedulerDown"` or `alertname="KubeControllerManagerDown"` for 10 years, because those scraping rules do not work on GKE-managed clusters.
