### ISSUE TITLE
kubevirt-cloud-controller-manager in CrashLoopBackOff

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#9157]
### What happened?
After upgrading KKP with kubevirt-cloud-controller-manager v0.0.9, the new kubevirt-cloud-controller-manager does not start.
```
% k get po kubevirt-cloud-controller-manager-6777d5b99f-tthl5
NAME                                                 READY   STATUS             RESTARTS   AGE
kubevirt-cloud-controller-manager-6777d5b99f-tthl5   0/1     CrashLoopBackOff   15         54m
```

Logs of the previous:
```
 k logs kubevirt-cloud-controller-manager-6777d5b99f-tthl5 -p
{"level":"info","time":"2022-02-28T19:06:25.644Z","logger":"http-prober","caller":"http-prober/main.go:127","msg":"Probing","attempt":1,"max-attempts":100,"target":"https://apiserver-external.cluster-gjdktm5x89.svc.cluster.local./healthz"}
{"level":"info","time":"2022-02-28T19:06:25.654Z","logger":"http-prober","caller":"http-prober/main.go:116","msg":"Hostname resolved","hostname":"apiserver-external.cluster-gjdktm5x89.svc.cluster.local.","address":"10.47.254.86:443"}
{"level":"info","time":"2022-02-28T19:06:25.657Z","logger":"http-prober","caller":"http-prober/main.go:140","msg":"Endpoint is available"}
{"level":"fatal","time":"2022-02-28T19:06:25.661Z","logger":"http-prober","caller":"http-prober/main.go:159","msg":"failed to execute command: exec format error"}
```

` exec format error` makes me feel that the new kubevirt-cloud-controller-manager:0.0.9 has been compiled with a Darwin OS, not a Linux.
We should recompile with `GOOS=linux`.

### What should happen?
It should start.

### How to reproduce?
On `dev`, create a KubeVirt Cluster.

### Environment
Dev

- KKP Version: g884b33c2
- Shared or separate master/seed clusters?:shared
- Master/seed cluster provider: Kubevirt

**Comment by sankalp-r** [comment]
Republished the image with the correct OS.
And it's working now.

**Comment by hdurand0710** [comment]
Hi @Sankalp,
You need to increase the image version and also in KKP. If not, for all the dockers where the image is already downloaded, it would still keep the old image.
