### ISSUE TITLE
Investigate on how to route apiserver->node traffice over openvpn

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#916]
What iptables rules & route's must be created that all traffic from the apiserver to the kubelets (node-ip's) is routed via OpenVPN?

That would fix `kubectl logs, etc.` for BYO & enable us to use private node networks

**Comment by p0lyn0mial** [comment]
that might be an interesting quest :)

**Comment by thz** [comment]
Just an idea: use iptables to match the traffic (apiserver as source) and add a mark ( `-j MARK --set-mark 42` ). Then add `ip rule` for sending marked traffic to a dedicated routing table. That table can now have a default route to the vpn peer.

**Comment by mrIncompetent** [comment]
If you're interested in testing this, feel free to create a cluster on dev.kubermatic.io, set it to `paused=true` (`kubectl edit cluster xxxxx`) & start hacking.

I got a working solution by modifying the client-config (The one which sits on the server and defines overrides for clients). But this is quite a bad solution as we need to restart the server. 
If we can get a solution just by modifying iptables rules & the route table that would be awesome!

**Comment by mrIncompetent** [comment]
Investigation has been done

**Comment by p0lyn0mial** [comment]
I'm curious how it was implemented :) Do we have a diagram or something :) ?

**Comment by mrIncompetent** [comment]
@thz can you create an epic which will cover this topic and create issues for:
- Implementing a IPAM controller
- Finish the DNAT implementation
- Document how its done and what can be configured

**Comment by thz** [comment]
Oh. Missed that one. Yes, will do.
