### ISSUE TITLE
v2.20.0-alpha.0 release bundle includes outdated CRDs by default

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#9160]
### What happened?

Downloading the `v2.20.0-alpha.0` release bundle and trying to install a separate Seed reveals that the CRDs in `charts/kubermatic-operator/crd` are the wrong ones (the old `k8s.io` ones). The install documentation directs you to apply those CRDs though, which will not work with v2.20.

### What should happen?

The new `k8c.io` CRDs should be in this directory by default.

### How to reproduce?

1. Download release bundle from https://github.com/kubermatic/kubermatic/releases/tag/v2.20.0-alpha.0.
2. Unarchive the bundle.
3. Go to `charts/kubermatic-operator/crd`.
4. Inspect the CRDs in this directory and see the API group being `kubermatic.k8s.io`.

### Environment

- KKP Version: v2.20.0-alpha.0
- Shared or separate master/seed clusters?: Separate
- Master/seed cluster provider: -

**Comment by embik** [comment]
Alternatively, we need to update the docs to point to the `k8c.io` directory when installing a Seed and applying CRDs (?).

**Comment by xrstf** [comment]
https://github.com/kubermatic/docs/pull/883 should help.

**Comment by kron4eg** [comment]
@xrstf does it mean that technically this issue is invalid?

**Comment by embik** [comment]
IMO, fixing the seed setup documentation is really important, but I think we should not longer include the old CRDs in our release archives at all. It's unnecessary and somewhat confusing. So the docs PR will decrease the impact, but changing the release archives is a separate step in my eyes.

**Comment by kron4eg** [comment]
Seems like old CRDs are required, anyway they are removed from the master branch and their "usage" is documented.
