### ISSUE TITLE
Equinix Metal cluster provisioning and upgrading - Test Release 2.20

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#9196]
Please go through https://github.com/kubermatic/kubermatic/issues/9188 for instructions. 

Supported Operating Systems:
- [ ] Ubuntu
- [ ] CentOS

Supported kubernetes versions:
- [ ] v1.20.13
- [ ] v1.20.14
- [ ] v1.21.8
- [ ] v1.22.5

Supported container runtimes:
- [ ] docker
- [ ] containerd

Upgrades:
- [ ] Upgrade from v1.20.13 -> v1.20.14
- [ ] Upgrade from v1.20.14 -> v1.21.8
- [ ] Upgrade from v1.21.8 -> v1.22.5

Operating system manager:
- [ ] Ubuntu
- [ ] CentOS

**NOTE:** Use any Kubernetes version for testing OSM

**Comment by xmudrii** [comment]
Works as expected.
