### ISSUE TITLE
Cilium mount-cgroup fails on centos

### ISSUE THREAD

**Issue by mate4st** [kubermatic/kubermatic#9222]
### What happened?
Cilium fails on nodes with centos. 
The mount-cgroup init container fails with error and prevents cilium to start:
```
[root@undefined-meninsky-66cf649745-w6prl containers]# cat cilium-mqlb2_kube-system_mount-cgroup-315b3d0ac316f2bfb72eacc37d0bd5e3cde91c346b31f4a7c317c452b70211d7.log
2022-03-03T14:22:25.387654016Z stderr F nsenter: cannot open /hostproc/1/ns/cgroup: No such file or directory
```

**Comment by WeirdMachine** [comment]
This issue most likely exists due to an incompatible Linux Kernel used by CentOS 7 that requires an extra third-party kernel provided by [ElRepo](http://elrepo.org/tiki/tiki-index.php) whereas CentOS 8 ships with a supported kernel.

**Comment by csengerszabo** [comment]
Start a known issue list
