### ISSUE TITLE
missing annotation on nodeport-proxy 

### ISSUE THREAD

**Issue by eBeyond** [kubermatic/kubermatic#9245]
### What happened?
When installing master/seed on one machine, a second would be instantiated on hcloud. But this doesn't happen. On the nodeport-proxy service is the annotation "load-balancer.hetzner.cloud/location=" missing. As such hcloud cannot decide where to place the lb and the service is in "pending" state.
After that the DNS pointing to *cluster.domain.tld has to be changed to the new IP

### What should happen?
The annotation should be set while provisioning the nodeport-proxy so the loadbalancer can be created without further modifications.

### How to reproduce?
Install Kubermatic with defaults and also the seed cluster (following example with minor modifications related to environment)

### Environment
kube-one cluster with KKP v2.19.2 and shared cluster

- KKP Version: v2.19.2
- Shared or separate master/seed clusters?: shared cluster
- Master/seed cluster provider: hcloud

**Comment by xrstf** [comment]
From what I can see, we do put the annotations on the Nodeport Proxy Service: https://github.com/kubermatic/kubermatic/blob/master/pkg/controller/operator/seed/resources/nodeportproxy/service.go#L49-L52 -- maybe I am misunderstanding your issue?

**Comment by eBeyond** [comment]
I've tried it several times with the installer v2.19.2, Everytime the loadbalancer wasn't ceated due to the missing annotation. I've now created a script, as a workaround, which manually sets the annotation after finishing the run of kubermatic.

**Comment by xrstf** [comment]
That's a nice but unfortunate workaround. Can you provide anonymized config files to reproduce the issue? If the annotations are configured but don't make their way onto the Service, that's quite a bug.

**Comment by eBeyond** [comment]
Ahhhh, sorry... Now I've seen what you mean... Sorry... NO BUG
