### ISSUE TITLE
[usercluster-mla] seed controller should tolerate unavailability of grafana secret in mla namespace

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/kubermatic#9277]
### What happened?
If we turn on user-cluster-mla on a seed but have not installed user-cluster mla components in mla namespace, the seed-controller pods go into crashloop and are very difficult to recover from there on. They specifically check for a secret named grafana in mla namespace.

This also becomes an issue if we manually delete grafana secret in MLA namespace on seed for any reason (e.g. like cleaning up entire namespace for user-mla stack upgrades etc)

### What should happen?
Ideally, seed-controller being an critical component for rolling out updates to all user-clusters etc, should be up as much as possible and just because of grafana secret, entire seed-controller should not crash. 

### How to reproduce?
1. **Don't** install user-cluster mla components in mla namespace on seed
2. enable user-cluster mla in operator as well as in seed.yaml

### Environment

- KKP Version: 2.18.5
- Shared or separate master/seed clusters?: separate
- Master/seed cluster provider: ANY (in our case, it was Azure as master and vsphere as seed)

**Comment by dharapvj** [comment]
Need to test the fix in sandbox env to see if it works (with KKP 2.20)

**Comment by dharapvj** [comment]
/remove-lifecycle stale

still need to be verified

**Comment by wurbanski** [comment]
This is confirmed to be fixed in the current master, as such will be fixed in the upcoming release.
