### ISSUE TITLE
GCP: Finalizer kubermatic.k8c.io/cleanup-gcp-firewall-nodeport is not created

### ISSUE THREAD

**Issue by dermorz** [kubermatic/kubermatic#9308]
### What happened?
When I create a user cluster on GCP and delete it afterwards the firewall rule `firewall-<CLUSTER_ID>-nodeport` is not getting cleaned up.

When looking at the finalizers on the cluster object, we see that `kubermatic.k8c.io/cleanup-gcp-firewall-nodeport` is missing.
```
$ kubectl get -n kubermatic cluster lktnn8lxtq -oyaml | yq '.metadata.finalizers'
- kubermatic.k8c.io/cleanup-credentials-secrets
- kubermatic.k8c.io/cleanup-etcdbackupconfigs
- kubermatic.k8c.io/cleanup-gcp-firewall-icmp
- kubermatic.k8c.io/cleanup-gcp-firewall-self
- kubermatic.k8c.io/cleanup-gcp-routes
- kubermatic.k8c.io/cleanup-kubermatic-constraints
- kubermatic.k8c.io/cleanup-usersshkeys-cluster-ids
- kubermatic.k8c.io/delete-nodes
```

### What should happen?
The finalizer `kubermatic.k8c.io/cleanup-gcp-firewall-nodeport` should be created so the firewall rule on GCP gets cleaned up on cluster deletion.

### How to reproduce?
1. Create a user cluster on GCP.
2. Check `.metadata.finalizers` on the `Cluster` object.
3. Delete cluster.
4. Search on the GCP console for the ID of the just deleted cluster.

### Environment

dev.kubermatic.io (2022-03-11)

### References
https://github.com/kubermatic/kubermatic/issues/8142
https://github.com/kubermatic/kubermatic/pull/8810
https://github.com/kubermatic/kubermatic/issues/9069

**Comment by xrstf** [comment]
Can you share the Cluster object? I tried to reproduce this on dev, but no firewall rules for nodeports are being created (and so there is also no finalizer). Did your cluster have more CIDRs configured somehow?
