### ISSUE TITLE
Dual-stack support for Equnix Metal clusters

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9359]
Add dual-stack support for KKP user-clusters on this cloud provider:

- [ ] Investigate dual-stack capabilities of the provider
- [ ] Add dual-stack support for KKP-managed cloud-provider configuration
- [ ] Add dual-stack support for the cloud-provider in machine-controller

**Comment by PratikDeoghare** [comment]
Currently failing with `The facility am6 has no provisionable c3.small.x86 servers matching your criteria.`

Pausing work on this due to current work in progress on Equinix metal.

**Comment by PratikDeoghare** [comment]
cc @moadqassem
