### ISSUE TITLE
Add project ownerRef validation to webhooks

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#9367]
To achieve a kubernetes native API, we need to make sure that when creating projects not through the KKP API, the same rules apply. 

The KKP API automatically sets the User OwnerReference to the Project based on which user(or KKP serviceAccount) made the request. This is essential for creating the RBAC rules for Users further along the way. So to make sure users create proper Projects, we need to validate them and check if they have the proper OwnerReference set.

**Comment by xrstf** [comment]
> validate project requirements, like setting up an owner

Did #9292 do something to fix this already?
