### ISSUE TITLE
Unable to create dev env.

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubermatic/kubermatic#9415]
### What happened?
The command `go get k8c.io/kubermatic` is throwing an error: `go: downloading k8c.io/kubermatic v8.88.1+incompatible`

### What should happen?
The command shouldn't throw any error and create a dev env.

### How to reproduce?
Run the command `go get k8c.io/kubermatic` in your terminal.

### Environment

- OS: Windows + WSL(ubuntu)
- KKP Version:
- Shared or separate master/seed clusters?:
- Master/seed cluster provider:

**Comment by embik** [comment]
Hey @jayesh-srivastava, can you please expand on your expected workflow here? What do you expect this to do? Using `go get` is not a supported installation method for KKP, please see https://docs.kubermatic.com/kubermatic/v2.20/ for details on how to set up KKP.

**Comment by embik** [comment]
If you are planning to work on the KKP code, checking it out via `git` is the supported way to do so.

**Comment by jayesh-srivastava** [comment]
@embik Yes git cloning would be enough!

**Comment by embik** [comment]
Hey @jayesh-srivastava, we closed this via #9416 because we think that is the best way to clone  (via SSH), but the repo can be cloned by any method that works for you. Please reopen this ticket or add a comment if you're still facing difficulties with this.
