### ISSUE TITLE
Make Projects easier to apply with kubectl

### ISSUE THREAD

**Issue by lsviben** [kubermatic/kubermatic#9425]
To work properly, projects in KKP require a User ownerReference. As it is clunky to apply ownerReferences through `kubectl` we should make this easier. 

The idea is to add a `spec.owner`, and then have a mutating webhook set the ownerReference based on the owner. This would also simplify the API code a bit.
We would also need to migrate existing Projects and set the `spec.owner` for them based on existing ownerReference.

**Comment by xrstf** [comment]
This was effectively fixed via #9516.
