### ISSUE TITLE
Spike: Examine Openshift/Origin user management

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#943]
See if we can utilise some components/logic

**Comment by p0lyn0mial** [comment]
I've been looking how the user management has been implemented in `Openshift`. I get the impression it's a different kettle of fish. Not only there is no user management library to use. The whole concept is built-in and it is integral part of the server. But also the API server has been built differently. They utilised `api-server` library the same you would use to build `api-extension` with `admission` and `authoriser` stuff. All this makes the server more like standard `kube-API` server. In addition to that they also have made different assumptions for example a project is namespaced and it seems like everything revolves around this.


I think it would be hard to use `Openshift` since it it a different project/product that doesn't expose library/framework to play with.

**Comment by p0lyn0mial** [comment]
@scheeles, @mrIncompetent PTAL

**Comment by mrIncompetent** [comment]
sgtm

**Comment by scheeles** [comment]
sgtm, Idea was more that we could copy some pieces of the code base and not the whole `Openshift`
