### ISSUE TITLE
FIX storage on Prodyna setup

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#945]

**Comment by kdomanski** [comment]
Requires manually setting `enableUUID` option on each worker node within the cluster, e.g.
`./govc_linux_amd64 vm.change -e="disk.enableUUID=1" -vm /Datacenter/vm/new-test-seed/worker-2`

See https://storagehub.vmware.com/export_to_pdf/kubernetes-vsphere-cloud-provider section `Enable disk UUID on Node virtual machines`
