### ISSUE TITLE
Discussion: Removal of prometheus-operator

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#947]
IMO: The Prometheus-Operator does not bring any benefit for our Kubermatic installation.

Instead it adds complexity
- Additional CRD handling code in the cluster-controller
- ServiceMonitors instead of simple annotations

Bugs caused by the prometheus-operator:
- CRD was missed in non-master seed-clusters, causing all user-clusters to be broken as they could not be processed, as no prometheus resource could be created
- CRD validation was/is broken, which broke:
  - Kubermatic-installer -> Was not able to install monitoring charts, which get installed first
  - Creation of user-clusters -> No prometheus custom resource could get created

IMO: 
Compared to the etcd-operator which does specific domain logic to scale a etcd-cluster, the prometheus-operator is nothing more than complex template logic.
It does not add any useful feature, we could benefit from. 

There is absolutely no need to template a prometheus custom resource, which in the end gets processed by an operator, which does additional templating to create a deployment.

The prometheus-operator makes sense when having multiple teams want different configurations for prometheus. We don't have this case.

**Comment by alvaroaleman** [comment]
Just for clarifications, at which points do we currently

* Deploy the prometheus operator
* Use Prometheus operator specific crds?

**Comment by mrIncompetent** [comment]
> - Deploy the prometheus operator

We deploy the prometheus-operator currently within our monitoring helm charts.
Those belong to the kubermatic-installer.

> - Use Prometheus operator specific crds?

In our monitoring helm charts as well as in the kubermatic cluster-controller.

**Comment by metalmatze** [comment]
First of all let me start by saying that I'm still confused by the timing of this discussion. :confused:
Back in October, when I started, I was asked by you guys and @scheeles especially, to create our monitoring stack with the Prometheus Operator (I never used it back then).
Everything with the Operator is working now and we have a solid foundation to build upon and improve our monitoring (of course there are bugs every now and then, but that's no different from any software we run).

Yes, you could probably do 90% of what we do without the Operator by just writing big configurations on your own and a bit of code in the Kubermatic API (would probably duplicate from what the Operator does at times for us now). I honestly don't think that it is worth the time of rewriting everything without the Operator now. Plus we still have the benefits of easy upgrades to Prometheus & Alertmanager and other shenanigans.
So, personally, I'm willing to continue to work with the Operator and also help out if the Operator's CRDs cause confusion (by bug fixing and teaching, it's really not that complicated).

**The discussion in general would probably be a different one, if we would have had this discussion at the beginning of building the monitoring stack.**

I'm honestly just a bit pissed about having this discussion now, with everything up and running. I feel like we're talking about the 5% difference of both approaches. Nevertheless I'm open for your opinions.

---

> The prometheus-operator makes sense when having multiple teams want different configurations for prometheus. We don't have this case.

We actually have this case. We have a "team" per cluster which scrapes all master components of that clusters and soon starts alerting from within the cluster. Then we have Kubermatic Team which monitors the seed cluster and other components needed to run Kubermatic itself, plus it scrapes the cluster Prometheuses via Federation for longer retention. Again soon I want to run the Prometheus for Loode's global view with the Operator too. Thanos support just landed. So these are the 3 different tiers we run.

We basically get this approach for free right now and it makes our monitoring really scablable already. 
If you want to read more on this please check the Prometheus Docs.

https://prometheus.io/docs/prometheus/latest/federation/#hierarchical-federation
> For example, a setup might consist of many per-datacenter Prometheus servers that collect data in high detail (instance-level drill-down), and a set of global Prometheus servers which collect and store only aggregated data (job-level drill-down) from those local servers. This provides an aggregate global view and detailed local views.

**Comment by mrIncompetent** [comment]
> First of all let me start by saying that I'm still confused by the timing of this discussion. confused
Back in October, when I started, I was asked by you guys and @scheeles especially, to create our monitoring stack with the Prometheus Operator (I never used it back then).

That is true and i'm sorry for this. I did not take a look at it back then.
We had no opinions about the whole topic back then.

> Everything with the Operator is working now and we have a solid foundation to build upon and improve our monitoring (of course there are bugs every now and then, but that's no different from any software we run).

True, but i personally think the operator introduces a complexity which is not worth it.
The complexity comes from
- ServiceMonitor files instead of a simple annotation
- prometheus & serviceMonitor go types in our codebase (Including the logic handling them)

> Yes, you could probably do 90% of what we do without the Operator by just writing big configurations on your own and a bit of code in the Kubermatic API (would probably duplicate from what the Operator does at times for us now). I honestly don't think that it is worth the time of rewriting everything without the Operator now. Plus we still have the benefits of easy upgrades to Prometheus & Alertmanager and other shenanigans.

Could you elaborate what the missing 10% is?
`big configurations` - So instead of one configuration in Prometheus we now have n ServiceMonitors which in the end get combined to a single configuration. 
I'm quite certain, that a config using the integrated kubernetes-service discovery results in something simpler than the Prometheus-Operator approach. 

Or are we using some specialized configuration?

I honestly think it's worth the time replacing the current approach with default kubernetes manifests.
At least for me, the approach is simpler and more easy to maintain. Also i think replacing the current stack won't take more than 2 days -  we're replacing prometheus with prometheus here.

> Plus we still have the benefits of easy upgrades to Prometheus & Alertmanager and other shenanigans.

Since Prometheus follows semantic versioning & has pretty good release notes i'm fine with just spending 2 days per major release in an update.
Furthermore, we now not only need to monitor the Prometheus releases, we also need to monitor the prometheus-operator releases. 
Also have you though about what happens when the operator promotes a new API version?

> The discussion in general would probably be a different one, if we would have had this discussion at the beginning of building the monitoring stack.

If i would have known about the operator as much as i do today, i would have voted against it back then.
Sadly i missed the opportunity.

> I'm honestly just a bit pissed about having this discussion now, with everything up and running. I feel like we're talking about the 5% difference of both approaches. Nevertheless I'm open for your opinions.

Which is totally understandable and mostly my fault as i was not researching about the operator back then. But now having 3 people in the team thinking the operator adds far more complexity than benefits, needs us to rethink our approach.
If we're talking about outcome, i'm fine with calling it 5%.
But the way to get there, is - at least for me - is fundamentally different and is needs a discussion.

> We actually have this case. We have a "team" per cluster which scrapes all master components of that clusters and soon starts alerting from within the cluster. 

For this to work, we need (ignoring alerting):
- ServiceMonitor for each component (6 at the moment)
- A prometheus CR
- The ServiceMonitor & Prometheus go type copied into our codebase
- A dedicated create&apply logic for the ServiceMonitor & Prometheus in our codebase

Instead of having:
- 2 annotations per component
- 1 Prometheus Deployment (We already handle deployments)
- 1 Prometheus ConfigMap (We already handle deployments)

> Then we have Kubermatic Team which monitors the seed cluster and other components needed to run Kubermatic itself, plus it scrapes the cluster Prometheuses via Federation for longer retention. 

For this to work, we need:
- ServiceMonitor for each component (8 at the moment)
- A prometheus CR

Instead of:
- Prometheus StatefulSet
- Prometheus ConfigMap
- Prometheus PVC
- Prometheus Service
- 2 annotations per component

> Thanos support just landed. So these are the 3 different tiers we run.

What we already could have properly integrated when we would not rely on the operator.
Instead we right now have 2 ways of deploying a Prometheus. The operator & default Kubernetes manifests.

> We basically get this approach for free right now and it makes our monitoring really scalable already.
If you want to read more on this please check the Prometheus Docs.

My take of `free`:
- Maintaining external CRD go types on our codebase + the logic to handle them
- A new - for us useless - concept of ServiceMonitor
- An abstraction for something everyone knows here - kubernetes manifests
I cannot consider this free.

My take on `scablable`:
Where does the Prometheus-Operator now solves any problem we had in terms of scaleability we would have when using Kubernetes manifests?

I think the complexity of introducing a operator + a new concept of ServiceMonitors does not justify the update logic mentioned.
The prometheus-operator is still for me nothing more than a big Helm Chart. Nothing you mentioned says something different. And i very much dislike introducing a operator just to do 3 versions of a Prometheus deployment.

So there's no misunderstanding, i think the architecture of having 1 Prometheus per user-cluster, 2 per seed-cluster & 2 for the master "Loodse" one is perfectly fine. I would not change anything here.
Just using the Prometheus-Operator here feels like unecessary complexity for me.

**Comment by mrIncompetent** [comment]
Getting back to this:
The only outcome from the chat with the prom-guys has been that the only thing the operator does, that you cannot do without the operator:
- A graceful update of the Alertmanager

The things we benefit from the operator:
- Update management
- Graceful Alertmanager updates
- Multiport scraping via ServiceMonitor

Right?

**Comment by metalmatze** [comment]
Yes.
I still think we benefit from the Operator, but as people don't stop discussing it. I will simply remove it, so I can focus on important stuff again.

**Comment by metalmatze** [comment]
Expect a PR next week.

**Comment by mrIncompetent** [comment]
discussion closed for action issue: https://github.com/kubermatic/kubermatic/issues/1156
