### ISSUE TITLE
Display error message for finalizer in events

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#9537]
As a user, I want to see error messages in Events so that I do not have to screenshot an error message to capture it.

![error message cluster deletion.jpg](https://images.zenhubusercontent.com/5f883d9f199cab5256a585cd/93f4f5a4-d19f-48c5-9ba9-a4d391b4c855)

**Comment by embik** [comment]
You don't have to screenshot the error message, you can click it to copy it to your clipboard :-)

**Comment by xrstf** [comment]
We have recently improved error handling and are now emitting more errors as events. So this might already be fixed now.
