### ISSUE TITLE
cloud-provider-kubevirt: copy labels from infra node to user cluster node

### ISSUE THREAD

**Issue by hdurand0710** [kubermatic/kubermatic#9565]
For [VM affinity](https://github.com/kubermatic/kubermatic/issues/8742), to control the placement of the customer pods (pods in the user cluster) on the infra cluster nodes, we need to copy some labels from the infra node to the user cluster nodes.
This should be done in `cloud-provider-kubevirt` that is already replicating 2 labels [Code for label replication](https://github.com/kubermatic/cloud-provider-kubevirt/blob/master/pkg/cloudprovider/kubevirt/zones.go#L63)).

As we do not want to copy all labels, part of this User Story is to determine how to configure which labels are copied.

**Comment by mfranczy** [comment]
this has to be determined together with upstream community to get list of labels we should copy from infra to tenant clusters.

**Comment by mfranczy** [comment]
we copy region, zone and flavor.

**Comment by mfranczy** [comment]
we copy region, zone and flavor.
