### ISSUE TITLE
Integrate Azure dual-stack machine-controller API in KKP

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9617]
Integrate https://github.com/kubermatic/machine-controller/issues/1251 into KKP

Also test dual-stack end-to end on all supported OS platforms.

**Comment by PratikDeoghare** [comment]
Moving this to stalled. For some operating systems we still don't have working dualstack cluster. 

CentOS -- Cilium agent crashes. 
Flatcar -- DHCPv6 is broken. 

TODO: Link issues here.

**Comment by PratikDeoghare** [comment]
Integration is complete. It is not yet supported for some combinations of cloud provider, cni and operating systems. 

Supported/un-supported combinations are tracked in [this test](https://github.com/kubermatic/kubermatic/blob/master/pkg/test/dualstack/cloud_providers_dualstack_test.go#L94) where unsupported combinations are commented out. 

This epic tracks progress of investigations of unsupported combinations. #9994
