### ISSUE TITLE
Integrate AWS dual-stack machine-controller API in KKP

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#9618]
Integrate https://github.com/kubermatic/kubermatic/issues/9294 into KKP

Also test dual-stack end-to end on all supported OS platforms.

**Comment by PratikDeoghare** [comment]
Integration is complete. It is not yet supported for some combinations of cloud provider, cni and operating systems. 

Supported/un-supported combinations are tracked in [this test](https://github.com/kubermatic/kubermatic/blob/master/pkg/test/dualstack/cloud_providers_dualstack_test.go#L94) where unsupported combinations are commented out. 

This epic tracks progress of investigations of unsupported combinations. #9994
