### ISSUE TITLE
Define Project type

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#967]
Define a new CRD type `Project` that will have the following structure

```
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
        
        Spec ProjectSpec `json:"spec"`
}
```

where `ProjectSpec` is:
```
type ProjectSpec struct {
	Name   string   `json:"name"`
}
```

we will take the `UID` from `metav1.ObjectMeta`

child of #966

**Comment by p0lyn0mial** [comment]
@mrIncompetent PTAL

**Comment by mrIncompetent** [comment]
This will prevent having the same Project name twice?

So 2 different Users won't be able to create a "Default" project?

**Comment by p0lyn0mial** [comment]
yes, the project names are unique and since they will live on `master` it will not be possible.

later on we could introduce `Spec.Name` field that would allow for duplication.

**Comment by mrIncompetent** [comment]
As this is a fundamental type, we should already introduce the `Spec.Name`

**Comment by p0lyn0mial** [comment]
alright, do we want to have `Description` as well ?
