### ISSUE TITLE
etcd Backup Settings: Lowercase validation for etcd Backup Credentials

### ISSUE THREAD

**Issue by archups** [kubermatic/kubermatic#9707]
### Description of the feature you would like to add / User story

As a end user
I would like to enforce lower case letters validation during Credentials creation time as part of etcd Backup Settings from the UI
in order to avoid the end user from entering the credentials with UPPER CASE and in turn avoid getting below error
```"Invalid value "XXX-XXX" : a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')```

### Solution details

- Requirement 1
- Requirement 2
- Requirement 3

### Use cases

It would be nice to have validation from UI for the inputs provided, since the end user will not be aware until the error occurs.

**Comment by ahmedwaleedmalik** [comment]
From front-end/API side the destination name for the backup should be a valid lowercase RFC-1123 subdomain.
