### ISSUE TITLE
Remove existing project v1 routes

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#971]
the only ones that will be needed are (for the time being)

- `/projects` (`GET`, `POST`)
- `/projects/{project}` (`GET`, `PUT`)

child of #966

**Comment by p0lyn0mial** [comment]
@mrIncompetent I hope it is safe to remove existing paths

**Comment by mrIncompetent** [comment]
Yes, those are not in use at all.
