### ISSUE TITLE
Extend v1.User

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#972]
Since `CRD` type doesn't support versioning, we would like to extend existing `v1.User` type to store a list of projects and groups a user belongs to.

```
type UserSpec struct {
	...
	Projects []Project `json:"projects, omitempty"`
}
```

where `Project` will be defined as

```
type Project struct {
	ID  string `json:"id"`
        Group string `json:"group"`
}
```

Note that the `Project` defined under `v1.User` is different from the one defined under `v1.Project`

child of #966

**Comment by p0lyn0mial** [comment]
@mrIncompetent I think that extending existing `v1.User` type is safe, since we only add a new field.

**Comment by mrIncompetent** [comment]
Yes, adding fields is save. Did this before
