### ISSUE TITLE
"Upgrade system on first boot" is not working with vSphere Cloud Provider

### ISSUE THREAD

**Issue by archups** [kubermatic/kubermatic#9724]
### What happened?

During cluster creation process using vSphere Provider,  when "Upgrade system on first boot" option is selected then the machinesets are not working as expected. When this option is turned off, it works fine.

### Expected behavior

When you select the "Upgrade system on first boot", the cluster creation should work fine as well, without any issues.  Similar to how it works when this option is not selected. 

### How to reproduce the issue?

From KKP dashboard, navigate to the project and select the "Create Cluster" under "Clusters" menu. 
Then select "vSphere"  at "Provider" tab, next fill out the information at "Cluster" tab, next at the "Settings" tab under "Basic Settings"  select the "Upgrade system on first boot"  option and proceed with other details to create cluster.
You will observe that the machinesets is not working properly (status does not turns to Running). 

### How is your environment configured?

- KKP version: 2.19.2
- Shared or separate master/seed clusters?: Separate Master and Seed Cluster.

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Azure for KKP Master setup and vSphere for Seed and User Clusters setup

### What operating system are you running in your user cluster?

Operating System: Ubuntu 20.04

**Comment by csengerszabo** [comment]
@archups what do you do when the machinesets' status is not running after boot? And what does it cause?

**Comment by WeirdMachine** [comment]
After an upgrade, there is a boot-efi.mount job running which prevents the setup service to start, therefore kubelet is never installed. We do not have any mechanism to check weather the service runs successful which leads to a node that will never join the cluster. After executing the setup service the node successfully joins the cluster:
`sudo systemctl start setup.service`

Relevant failure logs:
```
May 29 20:47:31 quirky-volhard-79dcccd7c5-z976c systemd[1]: Requested transaction contradicts existing jobs: Transaction for setup.service/start is destructive (boot-efi.mount has 'stop' job queued, but 'start' is included in transaction).
May 29 20:47:31 quirky-volhard-79dcccd7c5-z976c cloud-init[1394]: Failed to start setup.service: Transaction for setup.service/start is destructive (boot-efi.mount has 'stop' job queued, but 'start' is included in transaction).
May 29 20:47:32 quirky-volhard-79dcccd7c5-z976c systemd[1]: boot-efi.mount: Succeeded.
```

I assume this only happens when there is a large update with a lot of packages. So one easy workaround for this issue could be to upgrade the used template VM.

**Comment by WeirdMachine** [comment]
Further research reveals that cloud-init schedules a restart after the package upgrade which takes too long and runs into a timeout. Therefore stop jobs are still running and prevent systemd to start the setup service.
See: https://github.com/canonical/cloud-init/blob/main/cloudinit/config/cc_package_update_upgrade_install.py#L71
