### ISSUE TITLE
Handle NetApp S3 storage without `--region` or `--bucket-location` option for ETCD Backups

### ISSUE THREAD

**Issue by archups** [kubermatic/kubermatic#9725]
### Description of the feature you would like to add / User story

As a end user  
I would like to perform ETCD backup setup with NetApp Data ONTAP 9.8P8 S3 storage for my KKP setup. 
in order to enable backup and restore setup for disaster recovery support and to plan KKP setup upgrades to next minor release.

When the end user is trying to perform the data upload using NetApp S3 storage without passing `--region` or `--bucket-location` then it is leading to failure in the data upload. 

### Solution details

- Provide support for NetApp Data ONTAP 9.8P8 S3 storage i.e. handle  `--region` or `--bucket-location` options internally at KKP side in case of NetApp S3 storage for ETCD backups so that data upload is successful when the  `--region` or `--bucket-location` option is not passed. 

### Use cases

For the organization which uses vSphere as infrastructure and NetApp as the storage service. Since, S3 storage is compatible for  KKP ETCD backups, it would be choice to use NetApp Data ONTAP 9.8P8 S3 storage for this ECTD backup data storage purpose.

**Comment by csengerszabo** [comment]
@moadqassem and @lsviben already worked on a backup story - so this seems to be an extension of their work

**Comment by lsviben** [comment]
For me this looks like that they need to have custom store and delete containers instead of the ones defined here:
https://github.com/kubermatic/kubermatic/blob/master/pkg/controller/operator/defaults/defaults.go#L760-L808

Custom ones can be set in the KubermaticConfiguration. I think they can use the same container, just add the options they need? Unless they want to dynamically change the `--region` and `--bucket-location`

**Comment by ahmedwaleedmalik** [comment]
@archups As discussed, we've updated the documentation for this with https://github.com/kubermatic/docs/pull/1079/files

The updated documentation is available at:
https://docs.kubermatic.com/kubermatic/v2.20/cheat_sheets/etcd/backup-and-restore/

Closing this issue as a result.
