### ISSUE TITLE
Add Mouse Over Explanation for "Konnectivity"

### ISSUE THREAD

**Issue by shaase-ctrl** [kubermatic/kubermatic#9742]
As a user, I want to know what "Konnecitivity" is so that I am not unaware of a component (or think its a spelling mistake).

Acceptance Criteria
* Present information via mouse over similiar to mouse over of External CCM

**Comment by cschieder** [comment]
[kubermatic/dashboard/#4448](https://github.com/kubermatic/dashboard/issues/4448)  - made this issue in dashboard earlier, if that's fine for you then we can close this one
