### ISSUE TITLE
Limited Service Account

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubermatic#975]
I'd like to create a service account that would be limited in terms of powers it has. I'd like to use this account instead of `admin` account. This account would be used for impersonation purposes. For example whenever we would like to operate on project's resource one would use this account.

child of #966

**Comment by p0lyn0mial** [comment]
@mrIncompetent what do you think ?

**Comment by mrIncompetent** [comment]
Are we talking about then kubermatic serviceaccount which currently gets used by the cluster-controller & api?
Then yes. We created a ClusterRoleBinding to `admin`  to quickly solve the RBAC migration back in 1.6. It was always on my list to eventually fix this but never had the time to to so.
