### ISSUE TITLE
Test KubeOne Cluster Import for AWS

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#9760]
Testing will include the following steps:

- [x] create kubeone cluster manually for AWS
- [x]  import the cluster using API
- [x]  check if the kubeone controller is able to create the kubeconfig secret for the same
- [x]  upgrade kubeone control plane using API
- [x]  check if the kubeone upgrade pod is created and completed
- [x]  migrate kubeone container runtime using API
- [x]  check if the kubeone migrate pod is created and completed
- [x]  test upgrade of md using API
- [x]  test md scale using API

**Comment by xrstf** [comment]
This ticket needs more information before it can be worked on.
