### ISSUE TITLE
Test KubeOne Cluster Import for Nutanix

### ISSUE THREAD

**Issue by imharshita** [kubermatic/kubermatic#9764]
Testing will include the following steps:

- [ ] create kubeone cluster manually for Nutanix
- [ ]  import the cluster using API
- [ ]  check if the kubeone controller is able to create the kubeconfig secret for the same
- [ ]  upgrade kubeone control plane using API
- [ ]  check if the kubeone upgrade pod is created and completed
- [ ]  migrate kubeone container runtime using API
- [ ]  check if the kubeone migrate pod is created and completed
- [ ]  test upgrade of md using API
- [ ]  test md scale using API

**Comment by xrstf** [comment]
This ticket needs more information before it can be worked on.
