### ISSUE TITLE
Unified event monitoring

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#9767]
### Description of the feature you would like to add / User story

As a KKP admin
I would like to see all the events from all clusters at one place
in order to quickly see the status of all my clusters.

### Solution details

- Events menu in the main navigation bar linking to the events Grafana page
- Events should be searchable and stored historically
- Error messages should be as user-friendly and solution-orientated as they can be
- Storing the events in a common database
- Seeing all the events at once from all KKP clusters
- Being able to filter for Projects
- Being able to filter for User clusters
- Making this feature only available if they enable the MLA stack
- EE feature

### Alternative approaches

- Checking events inside each clusters workspace separately
- Connecting Kubernetes API to a custom database and collect the events

### Use cases

- Monitoring the all KKP clusters health from one place

**Comment by jacmathew** [comment]
It will be great to consolidate critical events across user clusters at a single place. It can be additional grafana page which will provide a cockpit view and for details we can always go through the existing grafana dashboards.

**Comment by csengerszabo** [comment]
as we discussed, solution for persistent Event logs/messages of cluster can be / should be part of this epic, FYI: @Waseem826
