### ISSUE TITLE
Kubermatic public documentation

### ISSUE THREAD

**Issue by cbrgm** [kubermatic/kubermatic#977]
After a talk with Henrik, Matthias and Sebastian, a public documentary is planned for Kubermatic.
We can use the following as content ideas:

https://github.com/openshift/openshift-docs
https://github.com/coreos/tectonic-docs
https://github.com/coreos/etcd/tree/v3.2.17/Documentation/op-guide

https://cloud.google.com/container-engine/docs/
https://github.com/MicrosoftDocs/azure-docs
https://github.com/kubernetes/kubernetes.github.io

**Comment by cbrgm** [comment]
First approach of the hugo directory structure for the new documentation site can be found here:
https://github.com/kubermatic/docs/tree/kubermatic-docs

**Comment by mrIncompetent** [comment]
@cbrgm Can you open up a PR for the groundwork?
I would rather create sub-tasks for the individual topics to document instead of having one big issue

**Comment by cbrgm** [comment]
I would move sub tasks to the kubermatic/docs repository if you don't mind?

**Comment by mrIncompetent** [comment]
sounds good

**Comment by cbrgm** [comment]
@mrIncompetent could you grant me ownership of the kubermatic/docs repo? I'd like to create a master branch, currently development branch is default..

**Comment by mrIncompetent** [comment]
I'll create a master branch based from develop. Please create a PR afterwards to master

**Comment by mrIncompetent** [comment]
`master` branch is created

**Comment by cbrgm** [comment]
Thanks, @mrIncompetent !

**Comment by cbrgm** [comment]
Content contribution tutorial for kubermatic docs can be found [here](https://github.com/kubermatic/docs/blob/master/content/overview/contributing/_index.en.md).

**Comment by mrIncompetent** [comment]
Please post the link in slack

**Comment by cbrgm** [comment]
Closing this one. Issue moved to https://github.com/kubermatic/docs/issues/21
