### ISSUE TITLE
Maintain Network Policies

### ISSUE THREAD

**Issue by mate4st** [kubermatic/kubermatic#9792]
Via the `kubeSystemNetworkPolicies` feature flag, it is possible to let KKP create network policies for user clusters to isolate kube-system namespace.

This feature needs some maintenance due to new components added without the proper network policies. 

Also we disabled it by default due to issues with cilium that might have been resolved by now: 
https://github.com/kubermatic/kubermatic/pull/8545

**Comment by rastislavs** [comment]
Related issue: https://github.com/kubermatic/kubermatic/issues/9546
