### ISSUE TITLE
Dex for k8s dashboards

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubermatic#9804]
### Description of the feature you would like to add / User story

As a KKP user
I would like to authenticate into Kubernetes cluster dashboards with the same credentials of authenticating into KKP
in order to get rid of service accounts and be able to manage cluster permissions globally with Dex

### Solution details

- Login to Kubernetes dashboards with SSO provider like Gsuite, Microsoft or GitHub account
- being able to manage the permissions globally and restrict users and user groups from full access of separate Kubernetes clusters

### Alternative approaches

- Service accounts

### Use cases

-

**Comment by floreks** [comment]
The merge order for related issues should be:
1. API PR (https://github.com/kubermatic/kubermatic/pull/10072)
2. Infra update (#10015)
3. Dashboard update (https://github.com/kubermatic/dashboard/pull/4585)

**Comment by ahmedwaleedmalik** [comment]
This is done now :) Awesome job @floreks ✌️
