### ISSUE TITLE
Component images for Kubernetes 1.24

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#9818]
#9736 is adding support for deploying Kubernetes 1.24 clusters, but upstream components like CCMs, CSI drivers, etc, do not (officially) support it. This issue tracks components that might need updating or a documentation note saying it is compatible with 1.24.

- [x] [cluster-autoscaler](https://github.com/kubernetes/autoscaler) (#9831)
- [x] kubernetes-dashboard (#9948)
- [x] vertical-pod-autoscaler (VPA) - (#9837 was probably enough)
- [x] Anexia CCM (no never version available)
- [x] [Openstack Cinder CSI](https://github.com/kubernetes/cloud-provider-openstack) (#9935)
- [x] Openstack CCM (#9935)
- [x] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) (no new version available)
- [x] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) (no new version available)
- [x] Kubevirt CSI (no new version necessary as per sig-virtualization)
- [x] Kubevirt CCM (no new version necessary as per sig-virtualization)
- [x] Nutanix CSI (does not follow Kubernetes releases; version skew policy should support 1.24)
- [x] vSphere CSI (no newer version available)
- [x] vSphere CCM (#10203)

Please add to the list if something is missing.

Also check for `TODO: 1.24` notes in KKP code base when working on this.

**Comment by dharapvj** [comment]
FYI... https://github.com/kubermatic/kubermatic/issues/10461
Vsphere CSI new version is now available which supports k8s 1.24
