### ISSUE TITLE
creating endpoint to seed configuration 

### ISSUE THREAD

**Issue by ahmadhamzh** [kubermatic/kubermatic#9834]
regarding Admin Panel Seed Configurations https://app.zenhub.com/workspaces/work-in-progress---team-product-606ec73090e027001169c9e7/issues/kubermatic/dashboard/4397

we display in the admin panel an overview consisting of:
- all available seeds
- total amount of clusters per seed
- all available providers per seed
- all available datacenters per seed

and also we display all providers for each seed ,and all datacenters for each provider ,and the number of clusters in each datacenter 

currently Most information needed is already combined in the Datacenter endpoint or the Admin Seeds endpoint except the amount of clusters for each provider or data center 

an ideal solution would be to call only one endpoint to get the data from it where the endpoint get the seeds > providers for each seed > datacenters for each povider > number of clusters in each datacenter

**Comment by KhizerRehan** [comment]
Add a new endpoint to gather all cluster information for all the seeds.
