### ISSUE TITLE
Support for VLAN provisioning with whereabouts IPAM

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/kubermatic#9875]
As a customer I want to have a native support for network isolation that each Virtual Machine created in the dedicated cluster namespaces has its own VLAN.

Acceptance criteria:
* VLAN isolation enabled by flag (cluster spec)
* Subnets controlled by us (range etc - we set /24 netmask.)  - annotate cluster namespace with the used subnet for calc
* Add start and end subnets range fields in a seed configuration
* Update doc with KubeVirt requirements about Multus, OVS and whereabouts deployment

**Comment by hdurand0710** [comment]
- hard-code the ovs bridge name: `kubevirt-bridge`
