### ISSUE TITLE
Secure access to the Kubernetes API of specific user clusters

### ISSUE THREAD

**Issue by PratikDeoghare** [kubermatic/kubermatic#9951]
### Description of the feature you would like to add / User story

We would like the Kubernetes API of specific user clusters (or projects would work as well) to be accessible from our internal network   (or its egress IP) only for security reasons. Ideally outside requests would be blocked even before getting to the apiserver. With this all apiserver vulnerabilities could be secured.

### Solution details

TBD

**Comment by rastislavs** [comment]
Duplicate of https://github.com/kubermatic/kubermatic/issues/10407
