### ISSUE TITLE
Setup internal k8s cluster on vSphere

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/kubermatic#997]
### vSphere Cluster.

Address: https://photon-machine.fritz.box
Username: `administrator@vsphere.local`
Password: `roh7uH+ac4th`

### Cluser dimension:
1x Master
2x Worker

### Setup 
For setting up the cluster have a look at https://github.com/kubermatic/kubermatic-installer/tree/master/kubeadm-seed-installer
To be able to utilize the vSphere storage within the k8s cluster, we need to set the cloud-provider flag & provide a cloud-provider config. Have a look at https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/

### Cloud-Config
We have an example cloud-config for one of our customers, though storage seems not to work (timeout while mounting the volumes) - The reason is still unclear. The config can be found in the secrets repository (encrypted): https://github.com/kubermatic/secrets/blob/prodyna/seed-clusters/kubermatic.prodyna.com/kubeadm-seed-installer-assets/cloud.conf

**Comment by scheeles** [comment]
LGTM
